### ISSUE TITLE
[BUG] bug title 

### ISSUE THREAD

**Issue by cristicmf** [apache/incubator-dolphinscheduler#1007]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

Does that project provide coordinated services for distributed tasks in the form of jar packages. Please give more details, thx

**Comment by dailidong** [comment]
I'm soryy , I can't unstand what you said clearly, maybe you can list some examples.
document is here: https://dolphinscheduler.apache.org/en-us/docs/user_doc/quick-start.html

**Comment by cristicmf** [comment]
Does this project has the jar packages that provide  coordinated services for distributed tasks .if it can provide the jar ,please give a demo.

**Comment by qiaozhanwei** [comment]
what do you mean ? I don't konwn clear，please desc detail
