### ISSUE TITLE
[BUG] 分布式任务时，任务被移除，任务卡在已提交状态

### ISSUE THREAD

**Issue by kimmxu** [apache/incubator-dolphinscheduler#1012]
2019-10-14 12:11:18.476  INFO 49523 --- [Thread-Executor] c.e.s.worker.runner.FetchTaskThread      : task : 6545 ready to submit to task scheduler thread
2019-10-14 12:11:18.476  INFO 49523 --- [Thread-Executor] c.e.common.queue.TaskQueueZkImpl         : consume task /escheduler/tasks_queue/2_3306_2_6545_174422043

debug：代码定位在
cn.escheduler.server.worker.runner.TaskScheduleThread 的 getTaskLogPath方法 
((TaskLogDiscriminator) ((SiftingAppender) ((LoggerContext) LoggerFactory.getILoggerFactory())
                .getLogger("ROOT")
                .getAppender("TASKLOGFILE")) 返回 null 导致 任务一直卡在已提交状态，无法执行，也无法重置状态

**Comment by dailidong** [comment]
please update/add title and description in English! thx

**Comment by lgcareer** [comment]
please give more detail description.such as more log.

**Comment by nauu** [comment]
If you start worker without any profile, The method `.getAppender("TASKLOGFILE")` will return NULL, Because it define in `worker_logback.xml`.

Try to start worker with`-Dspring.profiles.active=worker`

**Comment by amenglu** [comment]
把配置文件路径假如到classpath里
-Dlogging.config=classpath:logback-worker.xml

**Comment by xingchun-chen** [comment]
No reply for a long time, temporarily close the issue

**Comment by keepmeup** [comment]
> If you start worker without any profile, The method `.getAppender("TASKLOGFILE")` will return NULL, Because it define in `worker_logback.xml`.
> 
> Try to start worker with`-Dspring.profiles.active=worker`

Is this plan feasible? I tried, but the error was reported.Still NullException
