### ISSUE TITLE
One-click deployment optimization, use the boot, target 30 minutes to get started  （一键部署优化，使用上引导，目标30分钟上手）

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#104]
One-click deployment optimization, use the boot, target 30 minutes to get started

---
一键部署优化，使用上引导，目标30分钟上手

**Comment by lidongdai** [comment]
更加友好的上手，在这些图标上加上更友好的提示，运动改成“手动运行”， 旁边的上线改为"流程上线"， 定时里的上线改为“定时上线”
