### ISSUE TITLE
上线/下线、运行/停止等是否可做成批量操作？

### ISSUE THREAD

**Issue by 1990hjp** [apache/incubator-dolphinscheduler#1040]

**Comment by dailidong** [comment]
add/update title and desc in English , thx!

**Comment by wangsvip** [comment]
是的,这个问题很好,每次建立多个任务,都要一个一个点,上线下线,很不方便!

**Comment by gabrywu** [comment]
the DAG is created one by one, so it's better to online one by one.

**Comment by yangyichao-mango** [comment]
Hi,
I agree with @gabrywu .
if you have any question or suggestion, please put forward.

**Comment by xingchun-chen** [comment]
+1

**Comment by gabrywu** [comment]
wow, we close this issue firstly , @1990hjp  feel free to reopen if necessary

**Comment by Nick-0723** [comment]
> the DAG is created one by one, so it's better to online one by one.

如果是批量导入任务，那一个一个上线将是灾难 / If it is a batch import task, it will be a disaster to go online one by one
