### ISSUE TITLE
[BUG] zkNode taskQueue can not be removed when delete prorcessInstance

### ISSUE THREAD

**Issue by zhanghuidouble** [apache/incubator-dolphinscheduler#1061]
**Describe the bug**
The taskQueue str is ${processInstancePriority}_${processInstanceId}_${taskInstancePriority}_${taskId}_${task executed by ip1},${ip2}...

but the ProcessInstanceService.deleteProcessInstanceById delete node is  ${processInstancePriority}_${processInstanceId}_${taskInstancePriority}_${taskId}

**To Reproduce**
Steps to reproduce the behavior, for example:
1. shutdown all worker services
2. start processInstance
3. the taskInstance status is submit success,delete processInstance
4. the task queue is still on the zk /taskflow/tasks_queue/

**Which version of Easy Scheduler:**
 -[dev-1.1.0]

**Comment by zhanghuidouble** [comment]
1. 我不太明白为什么taskQueue 上节点拼接串要加上 worker ip 生成的字符串，其实这个串只到taskInstanceId 也是可以的，worker取到节点后，可以通过taskInstance中的workerGroupId 来查询到最新的具体的worker ip 有哪些，不知道有什么别的考虑？

2. 这个串  是根据worker 分组的ip 拼接的，但是worker 分组的ip是可以随时编辑的，也就是目前的情况除非记录这个taskQueue 到taskInstance中，否则是无法在删除 工作流实例的时候再拼接处当时这个taskQueue 的

@qiaozhanwei

**Comment by Technoboy-** [comment]
this bug has already fixed in recent branch

**Comment by zhanghuidouble** [comment]
是的，我看了一下，最新的修复，也是重新拼接了一下后面的ip 串，但是我还是上面的问题，这个workerGroup中的ip是可以编辑的，如果在删除工作流实例的时候，workerGroup中的ip发生了变化，那么这个串也是不一致的，还是不能被删除。 @Technoboy-

**Comment by Technoboy-** [comment]
yes, we will discuss and reply u later or you can participate in wechat group

**Comment by dailidong** [comment]
very good idea， we will resolve it later!

**Comment by dailidong** [comment]
and could you add my wechat(510570367)?  when added, tell me your github ID is:zhanghuidouble , thx!

**Comment by CalvinKirs** [comment]
fix by 1.3.X
