### ISSUE TITLE
[Feature]Add click-to-zoom function to images in official documents. (官网文档中的图片添加点击放大的预览功能)

### ISSUE THREAD

**Issue by elonlo** [apache/incubator-dolphinscheduler#1066]
**Ex.**
<img width="1421" alt="Snipaste_2019-10-21_22-26-42" src="https://user-images.githubusercontent.com/5669148/67214216-ebf8f300-f451-11e9-8b1c-cb1fc6b15a53.png">

**Comment by dailidong** [comment]
good idea，thx！

**Comment by chengshiwen** [comment]
We will consider the feature in https://github.com/apache/incubator-dolphinscheduler-website, thx!
