### ISSUE TITLE
[BUG] login api: password passed as plain text

### ISSUE THREAD

**Issue by coding-now** [apache/incubator-dolphinscheduler#1067]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
login api: password passed as plain text(系统登录接口，前端明文传输密码）
vue前端应做加密处理.....
**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.0.4]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
good idea，thx！

**Comment by chengshiwen** [comment]
Encrypting passwords at the front-end is a difficult thing, involving cryptography, such as symmetric encryption and asymmetric encryption. https is the most considered solution.
