### ISSUE TITLE
[BUG] prompt resource not exsit when administrative users delete data sources created by ordinary users in the data source center

### ISSUE THREAD

**Issue by galesun** [apache/incubator-dolphinscheduler#1075]
**First, I logged in to admin and deleted the normal user.** when the management user deletes the data source created by ordinary users in the data source center, it prompts resource not exsit, and the background query database finds that the corresponding data exists, and the back-end data displayed in the web interface is normal

**Comment by dailidong** [comment]
which version？

**Comment by galesun** [comment]
Sorry, there is no version listed. The version I use is 1.1.0 




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            李志超
                            
                            
                                
                                    邮箱：lzcwj2008@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 10/28/2019 21:25, dailidong wrote: which version？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-dolphinscheduler/issues/1075?email_source=notifications\u0026email_token=AKOTCH3WS2R76CBL67SNGMLQQ3R3JA5CNFSM4JD3OEHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECM3I3A#issuecomment-546944108",
"url": "https://github.com/apache/incubator-dolphinscheduler/issues/1075?email_source=notifications\u0026email_token=AKOTCH3WS2R76CBL67SNGMLQQ3R3JA5CNFSM4JD3OEHKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECM3I3A#issuecomment-546944108",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dailidong** [comment]
for now, maybe you can try delete resource first, and then delete the related user!

we will confirm this issue, thanks a lot!

**Comment by lgcareer** [comment]
Did you resolved?

**Comment by xingchun-chen** [comment]
This issue has been resolved in version 1.2.0
