### ISSUE TITLE
Front end input box does not have length limit(前端输入框没有做长度限制)

### ISSUE THREAD

**Issue by samz406** [apache/incubator-dolphinscheduler#109]
The front-end input box is not limited in length and can be input without restrictions.

---
前端输入框没有做长度限制，可以无限制输入。

**Comment by millionfor** [comment]
具体哪个输入框 ？

**Comment by samz406** [comment]
目前发现的有创建项目，创建用户，输入框可以无限制输入。

**Comment by hyperknob** [comment]
现在发现，局部变量输入框的长度有限制

**Comment by dailidong** [comment]
@break60 check this issue resolved ? if resolved, please close this issue
