### ISSUE TITLE
When a task fails to execute on an executor, the priority is to try to retry the task on another executor within the same WorkerGroup.[当某个task在某台执行机上执行失败时，优先尝试在同WorkerGroup内的另外一台执行机上重试此task]

### ISSUE THREAD

**Issue by liehuoqiangni** [apache/incubator-dolphinscheduler#1111]
1.At present, each worker obtains the tasks in the task queue in a preemptive way and executes the acquired tasks in an exclusive way.[目前，各worker之间以抢占的方式来获取任务队列中的任务，并以独占的方式来执行获取到的任务]

2.Therefore, the same failed task may be retried repeatedly on the same executor.[因此，同一个失败的task可能在同一台执行机上反复重试]

3.If another executor retries the task, it can avoid or alleviate the task failure caused by the resource shortage of the executor or the heterogeneous environment.[若换一台执行机来重试此task，可以避免或减轻因执行机的资源紧张或异构环境而造成的task运行失败]

4.Remarks：The "executor" mentioned above refers to the physical machine or KVM.[备注：上文提到的'执行机'是指物理机或KVM]

**Comment by dailidong** [comment]
good idea! we will implement it in the future!

**Comment by dailidong** [comment]
or you can do it if you have interesting in it!

**Comment by gabrywu** [comment]
Good suggestions

**Comment by chengshiwen** [comment]
Close this issue since fetching the task in worker has removed in 1.3.x. So please the latest version
