### ISSUE TITLE
[Feature]Sql task #{}、${} of the SQL statement like mybatis? 

### ISSUE THREAD

**Issue by ChunMengLu** [apache/incubator-dolphinscheduler#1122]
Sql task support for parameter substitution rules like mybatis。

```sql
create table xxxx_${date} as select * from xxxx
```

to support this parameter requires direct splicing.

**Comment by dailidong** [comment]
you can see dev-db branch, we use mybatis-plus as ORM frame in the new version！

**Comment by ChunMengLu** [comment]
Good job！

**Comment by CalvinKirs** [comment]
done
