### ISSUE TITLE
[BUG] bug title 接口文档无法打开（http://52.82.13.76:8888/easyscheduler/doc.html?language=zh_CN&lang=cn）

### ISSUE THREAD

**Issue by xujiapei** [apache/incubator-dolphinscheduler#1133]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
api address updated: http://106.75.43.194:8888/easyscheduler/doc.html?language=zh-CN&lang=cn

**Comment by khadgarmage** [comment]
@dailidong Is it possible to think about a domain name?

**Comment by dailidong** [comment]
the demo address: http://106.75.43.194:8888/
