### ISSUE TITLE
[QUESTION] where to find the log? 任务执行时的源码中info日志在哪看？

### ISSUE THREAD

**Issue by chenyuan9028** [apache/incubator-dolphinscheduler#1134]
![image](https://user-images.githubusercontent.com/30412237/67928636-767de700-fbf6-11e9-8acf-1e61995d5fd3.png)

the code location: cn.escheduler.server.worker.task.AbstractCommandExecutor 

where to find the log in the source code? I find nothing abount these in logs/worker-server.log or 
logs/master-server.log.

**Comment by dailidong** [comment]
The task execution log contains the corresponding log information in the logs directory of the worker machine
---
任务执行日志是在worker机器上的logs目录下有对应的日志信息
