### ISSUE TITLE
[BUG] the 'file' feild of appender 'TASKLOGFILE' in logs/worker_logback.xml maybe wrong!

### ISSUE THREAD

**Issue by chenyuan9028** [apache/incubator-dolphinscheduler#1135]
version: 1.1.0
![image](https://user-images.githubusercontent.com/30412237/67930160-12f5b880-fbfa-11e9-8a55-4e50c2e41c69.png)

the file name maybe as following:
${log.base}/${processDefinitionId}/${processInstanceId}/${taskInstanceId}.log

it is lack of a '$' that may cause the local dir is 
![image](https://user-images.githubusercontent.com/30412237/67930279-5d773500-fbfa-11e9-9bf2-52a5e1017986.png)

**Comment by Technoboy-** [comment]
yes, it has been fixed in the lastest branch .

**Comment by dailidong** [comment]
> yes, it has been fixed in the lastest branch .

in the dev-db branch, will be released later!
