### ISSUE TITLE
[QUESTION] what’s the best deploy mode you suggest?

### ISSUE THREAD

**Issue by chubbyjiang** [apache/incubator-dolphinscheduler#1147]
In production env, how much MasterServer/WorkerServer node should in the cluster ? The minimum is 1, what is the best number of them?
And should they deploy in the same node? or in different node?
THX.

**Comment by dailidong** [comment]
I suggest you use 3 nodes for stability if you don't have too many tasks to run. and distribute Master/Worker server on different nodes is better .  It's just a suggestion！

if you only have one node, you of course only can deploy them together! 

By the way, how many machines you need is determined by your business. The DolphinScheduler system itself does not use too many resources. Test more, and you'll find the right way to use a few machines
