### ISSUE TITLE
modify a small point about build the project to tarball file when decompressed to a separate folder, such as tarball file name.

### ISSUE THREAD

**Issue by shaozhipeng** [apache/incubator-dolphinscheduler#1152]
build完成后的tarball直接解压的时候能在一个单独文件夹里，而不是tarball所在的文件夹
谢谢~~

**Comment by dailidong** [comment]
please update/add title and  description in English! thx!

**Comment by shaozhipeng** [comment]
Well, I am so sorry describe the issue using Chinese. I just want to modify a small point about build the project to tarball file when decompressed to a separate folder, such as tarball file name.

**Comment by shaozhipeng** [comment]
in package.xml

<includeBaseDirectory>true</includeBaseDirectory>

Just change false to true.

**Comment by chengshiwen** [comment]
Close this issue since it has been resolved
