### ISSUE TITLE
[Feature] Use MyBatis xml instead of write Java code

### ISSUE THREAD

**Issue by BruceQiu90** [apache/incubator-dolphinscheduler#1153]
I have seen escheduler-dao module source code and I found that the database-related operations are used mybatis annotations and java code. I think write SQL in xml file will easier to maintain if the project grows larger.

---

我看了 escheduler-dao 模块的代码，发现里面关于数据库相关的操作，都是通过注解加 Java 代码的方式。我想是不是使用 MyBatis 的 xml 方式写相关的 SQL 语句后期更加容易维护一些。

**Comment by dailidong** [comment]
good job,  we already used xml in the new coming version , for now not ready for released yet , but you can have a look at dev-db branch, haha!
