### ISSUE TITLE
[BUG] execute shell beeline -f export csv file,the result is not expected

### ISSUE THREAD

**Issue by bestprize999** [apache/incubator-dolphinscheduler#1160]
With escheduler 1.1.0 execute a shell script,the shell file sample.sh as followed:
beeline --verbose=false --silent=true --outputformat=csv2 -f sample.hql >result.csv
sample.hql file as followed:
select * from sample;
We expect the result is table sample's all records.
We deploy escheduler with user etl,the shell's owner is hive. The process and task is created with es user hive whose tenent is hive.
Step 1:
With linux user hive,we execute the shell sample.sh
sh sample.sh
the result is we expected.
Step 2:
With linux user etl,we execute the shell sample.sh
sudo -u hive sh sample.sh
the result is we expected.
Step 3:
With escheduler execute the shell sample.sh
the result is not we expected.On the top of the csv file,there are some blank lines including "^M".

以es调度一个执行hive导出csv文件的shell任务，导出结果文件头几行有包含^M乱码的无数据行，而直接在linux命令行中执行该shell，结果正常。

**Comment by dailidong** [comment]
thanks!

**Comment by CalvinKirs** [comment]
This seems to be the newline character of the windows system, can you convert it?
