### ISSUE TITLE
[QUESTION] the denpendecy node task is still running when the task in the dependency has finished success

### ISSUE THREAD

**Issue by chenyuan9028** [apache/incubator-dolphinscheduler#1166]
version 1.1.0

the denpendecy node task is still running when the task in the dependency has finished success.

A工作流里有个B工作流的依赖型节点，当B工作流已经成功运行完成时，A工作流里的依赖型节点还在执行，这是不符合预期的。

![image](https://user-images.githubusercontent.com/30412237/68279786-2350dc00-00af-11ea-80f2-2d0a5ffbeb3b.png)

**Comment by dailidong** [comment]
Can we reproduce this scene so that we can locate what the problem is

---
能复现这个场景么? 方便我们定位问题！

**Comment by chenyuan9028** [comment]
I know the problem. It is because there is one  dependency task is still running，but not the latest one，the latest one was success. Doesn't the dependency task node check the latset instance was success?
找到原因了。我的依赖节点是一个5分钟调度一次的工作流，有个工作流实例一直处在运行状态，但之后的调度都成功了。依赖节点不是应该检测的是最后一次运行实例有没有成功吧？
