### ISSUE TITLE
[BUG]same user and ip has two sessions, user login failed

### ISSUE THREAD

**Issue by huyaoban** [apache/incubator-dolphinscheduler#1184]
Version(版本):
1.1.0

描述：
同一用户，同一IP有2个Session，导致登陆失败。
删掉一个Session后，登陆成功

现象：
![image](https://user-images.githubusercontent.com/24906133/68462629-dd7b4b80-0247-11ea-91d2-3eac39da2f2f.png)
![image](https://user-images.githubusercontent.com/24906133/68462651-e79d4a00-0247-11ea-9b50-1fdbe5d29146.png)
![image](https://user-images.githubusercontent.com/24906133/68462665-ed932b00-0247-11ea-9f36-6d88205b6280.png)

补充：
期间mysql存在连接不上的问题
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
	
	The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 601,132 milliseconds ago.

**Comment by dailidong** [comment]
good job!

we know this issue some days ago,  and fixed it in the coming version! thx!

**Comment by lgcareer** [comment]
1.2.0 fixed
