### ISSUE TITLE
[QUESTION] Deploying dolphinscheduler-ui  failed 

### ISSUE THREAD

**Issue by zsmdata** [apache/incubator-dolphinscheduler#1188]
I install the dolphinscheduler-ui  according to the documentation (https://dolphinscheduler.apache.org/zh-cn/docs/user_doc/frontend-deployment.html)

But nginx reported a mistake：
```
open() "/app/dolphinscheduler-ui/dist/escheduler/users/get-user-info" failed (2: No such file or directory)
```
![image](https://user-images.githubusercontent.com/18065113/68520909-c6d00580-02d6-11ea-9650-45ebd77cf217.png)

And the escheduler-backend  is working fine

**Comment by glxfeng** [comment]
1、修改nginx的配置文件
location /dolphinscheduler改成location /escheduler

2、修改escheduler-1.1.0-backend的application.properties
server.servlet.context-path=/dolphinscheduler/改成server.servlet.context-path=/escheduler/
