### ISSUE TITLE
[BUG] shell task launch two datax processes

### ISSUE THREAD

**Issue by huyaoban** [apache/incubator-dolphinscheduler#1190]
Version:
1.1.0

工作流添加了一个shell节点，shell节点执行python脚本启动datax，
工作流启动后，shell节点在服务器上启动了2个datax进程

![image](https://user-images.githubusercontent.com/24906133/68522228-0e10c300-02e4-11ea-8c59-3994803e699b.png)
![image](https://user-images.githubusercontent.com/24906133/68522231-15d06780-02e4-11ea-8ae6-5f40314a78a4.png)
![image](https://user-images.githubusercontent.com/24906133/68522234-1ff26600-02e4-11ea-887d-d5da5c09781a.png)
![image](https://user-images.githubusercontent.com/24906133/68522236-254fb080-02e4-11ea-844f-e29d68a79431.png)

**Comment by qiaozhanwei** [comment]
You can look at the worker, how many times the task was submitted, sudo-u tenant sh xxx.command, and it is to be clean before running the task, for example, if you start, delete the process instance, after that, the worker There may be previous tasks on

你可以看worker，任务提交了多少次，sudo -u 租户 sh xxx.command，还有就是在跑任务之前要保证之是干净的，比如如果你启动了，之后把流程实例删除了，之后，worker上可能会有以前的任务

**Comment by huyaoban** [comment]
> You can look at the worker, how many times the task was submitted, sudo-u tenant sh xxx.command, and it is to be clean before running the task, for example, if you start, delete the process instance, after that, the worker There may be previous tasks on
> 
> 你可以看worker，任务提交了多少次，sudo -u 租户 sh xxx.command，还有就是在跑任务之前要保证之是干净的，比如如果你启动了，之后把流程实例删除了，之后，worker上可能会有以前的任务


这个流程今天是第一次跑任务，而且只有这一个流程在跑

**Comment by lgcareer** [comment]
Did you resolved?

**Comment by xingchun-chen** [comment]
Don't reply for a long time, it will be close.
