### ISSUE TITLE
[BUG] wrong spell in lock implementation flow chart

### ISSUE THREAD

**Issue by haiboself** [apache/incubator-dolphinscheduler#1197]
**Describe the bug**
文档[配图](https://analysys.github.io/easyscheduler_docs_cn/images/distributed_lock_procss.png)中用词错误,如图标红部分,应该为 `取到`

**To Reproduce**
![image](https://user-images.githubusercontent.com/22912087/68565799-85cf2100-048f-11ea-878b-95a46abe120c.png)

**Comment by dailidong** [comment]
good job，would you like udpate the document and contribute to community?
contribute document: https://github.com/apache/incubator-dolphinscheduler/issues/310

**Comment by nauu** [comment]
the dev-db branch dosen't have the docs folder. so which branch shall i pr ?  @dailidong

**Comment by dailidong** [comment]
officical document address: https://github.com/apache/incubator-dolphinscheduler-website, please   
read README.md first

**Comment by nauu** [comment]
thx for reply @dailidong .  i have been fixed the issue , and the pr is here :  
apache/incubator-dolphinscheduler-website#47
