### ISSUE TITLE
[BUG] wrong network address when master-server has multiple network addresses

### ISSUE THREAD

**Issue by wangjiaqi-** [apache/incubator-dolphinscheduler#1201]
**Describe the bug**
when I run master-server(multiple network addresses), I got the network address of master-server not in the same network segment as worker-server.

**Expected behavior**
Got the network address of master-server which  in the same segment as worker-server.

**Which version of Easy Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
you can try config ip address in /etc/hosts file
