### ISSUE TITLE
[BUG] Scheduling time is not accurate

### ISSUE THREAD

**Issue by wzx-ang** [apache/incubator-dolphinscheduler#1208]
The start time of the schedule is not accurate. The start time is set at 1:12 am, but the start time varies irregularly with each execution.

调度开始时间不是准确的，设置的开始时间是凌晨1:12分，但是开始每次执行时间不同无规律。

![image](https://user-images.githubusercontent.com/10701748/68648279-f4c57c00-055a-11ea-95e8-013af1bcf4e6.png)
![image](https://user-images.githubusercontent.com/10701748/68648289-fbec8a00-055a-11ea-9576-8aa257065b7f.png)

**Comment by dailidong** [comment]
did you see the worker server log?

**Comment by dailidong** [comment]
please update/add description in English, thx!

**Comment by wzx-ang** [comment]
> did you see the master/worker server log? maybe master/worker server is too busy

It is found from the log that the master load is too high, thank you
