### ISSUE TITLE
Recommendation: Resource file upload and use, can support batch and directory structure   (建议：资源文件上传和使用，可以支持批量和目录结构 )

### ISSUE THREAD

**Issue by hyperknob** [apache/incubator-dolphinscheduler#121]
Such as the title

**Comment by lidongdai** [comment]
good idea! we will add it as new feature ideas, if anybody has same idea, please reply "+1"

**Comment by lshoo** [comment]
＋1
这个要支持啊

**Comment by zuiaiyuhuashi** [comment]
+1
这个功能一定要有，希望尽快出来

**Comment by bailgot** [comment]
文件上传，没做目录隔离，同名文件不同意义的现在只能存一份，或者个人上传文件较多，列表显示太临散了，不够直观不便管理

**Comment by zongyaoou** [comment]
希望此功能尽快能解决 , 大规模多人协作使用时 , 资源中心的文件管理显得尤其重要 ;

**Comment by phoenixhadoop** [comment]
+1

**Comment by lianayu** [comment]
+1

**Comment by dailidong** [comment]
1.3.1 support multi directory
