### ISSUE TITLE
[QUESTION] 1.1.0版本中怎么实现对shell的执行

### ISSUE THREAD

**Issue by xiaot502** [apache/incubator-dolphinscheduler#1212]
-[1.1.0-preview]
我的问题如下：在shell组件里面配置一个shell执行。
那么需要知道在哪个服务器上被执行，其次是执行的路径或者在文本框里面直接写一个脚本。
1.被执行的服务器在哪里配置。
2.如果是服务器上某个路径的一个shell文件，怎么指向这个路径。
3.如果仅仅是写的一个shell脚本的内容贴入文本框这个又如何配置。
My problem is as follows: configure a shell execution inside a shell component.
Then you need to know which server to execute on, followed by the path to execute or write a script directly in the text box.
1. Where is the executed server configured?
2. If it is a shell file of a path on the server, how to point to the path?
3. How to configure if the content of a shell script is just written and pasted into the text box?

**Comment by dailidong** [comment]
please update/add title and description in English, thx!

**Comment by lfyee** [comment]
1. Which server is determined by scheduling and has randomness
2, the server shell file, involving permissions issues, it is not recommended to do so. It is recommended that you use the storage function of the resource center, and then use the resource reference in the shell editor. The system will help you download the script to the execution directory.

1、服务器由调度决定的，具有随机性
2、服务器上某个路径下的shell文件，涉及到权限问题，不建议这么做。建议你可以使用资源中心的存储功能，然后在shell编辑器里面使用资源引用就可以，系统会帮助你把脚本下载到执行目录下。

**Comment by xiaot502** [comment]
> 1. 哪个服务器由调度确定并具有随机性
> 2. 服务器外壳文件涉及权限问题，不建议这样做。建议您使用资源中心的存储功能，然后在外壳编辑器中使用资源引用。系统将帮助您将脚本下载到执行目录。
> 
> 1.服务器由调度决定的，具有随机性。2 
> 。服务器上某个路径下的shell文件，涉及到权限问题，不建议这样做。建议您可以使用资源中心的存储功能，然后在shell编辑器里面使用资源引用就可以，系统会帮助你把脚本下载到执行目录下。

资源中心的使用，必须安装了hadoop才能在hdfs文件系统里面存储文件？如果我在不使用hdfs文件系统
的时候，给与执行账户一定的权限，也是可以实现对shell脚本的执行调用的吧？
To use the resource center, you must install hadoop to store files in the HDFS file system.If I'm not using the HDFS file system
When the execution account is given certain permissions, it is also possible to implement the execution call to the shell script, right?

**Comment by xiaot502** [comment]
首先非常感谢你的耐心解答，其实我想了解shell怎么被执行，有三个必要条件首先我要知道被执行的Server在哪个IP下面，我以哪个用户来执行，被执行文件的路径。经过我的测试，执行地址实际在工作分组这个参数来配置，用户是通过租户这个参数来引用。执行路径直接在script框里面直接写入服务器上的绝对调用路径即可比如&nbsp; &nbsp;sh&nbsp; /opt/tst.sh





---原始邮件---
发件人: "老佛爷"<notifications@github.com&gt;
发送时间: 2019年11月12日(星期二) 晚上6:30
收件人: "apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送: "xiaot502"<302983717@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [apache/incubator-dolphinscheduler] [QUESTION] 1.1.0版本中怎么实现对shell的执行 (#1212)


 
Which server is determined by scheduling and has randomness
 2, the server shell file, involving permissions issues, it is not recommended to do so. It is recommended that you use the storage function of the resource center, and then use the resource reference in the shell editor. The system will help you download the script to the execution directory. 
 
1、服务器由调度决定的，具有随机性
 2、服务器上某个路径下的shell文件，涉及到权限问题，不建议这么做。建议你可以使用资源中心的存储功能，然后在shell编辑器里面使用资源引用就可以，系统会帮助你把脚本下载到执行目录下。

**Comment by Yeleights** [comment]
1 task is run by the tenant through "sudo -u ${tenant}", tenant is a linux user
2 specify one worker to run the task, you can create worker group in Security Center, when the task can be send to the  particular worker
3 if the task dependent on resource center files, worker use "hdfs dfs -get" to get the resource files in HDFS, then run the task in /tmp/escheduler/exec/process, this path can be user define when installtion dolphinscheduler
1 执行任务的时候，调度器会采用sudo -u 租户的方式去执行
2 要指定在某个worker上去执行，可以在worker分组中配置，固定IP，这样就可以把路径写死
3 hdfs作为资源中心，在执行的时候，调度器会把依赖的jar包，文件等资源拉到worker的执行目录上，我这边是/tmp/escheduler/exec/process，该配置可以在install.sh中进行指定

**Comment by xiaot502** [comment]
非常感谢解答，令我茅塞顿开。




Thank you very much for the answer.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yelli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 上午9:16
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"涛"<302983717@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] [QUESTION] 1.1.0版本中怎么实现对shell的执行 (#1212)




1 task is run by the tenant through "sudo -u ${tenant}", tenant is a linux user
 2 specify one worker to run the task, you can create worker group in Security Center, when the task can be send to the  particular worker
 3 if the task dependent on resource center files, worker use "hdfs dfs -get" to get the resource files in HDFS, then run the task in /tmp/escheduler/exec/process, this path can be user define when installtion dolphinscheduler
 1 执行任务的时候，调度器会采用sudo -u 租户的方式去执行
 2 要指定在某个worker上去执行，可以在worker分组中配置，固定IP，这样就可以把路径写死
 3 hdfs作为资源中心，在执行的时候，调度器会把依赖的jar包，文件等资源拉到worker的执行目录上，我这边是/tmp/escheduler/exec/process，该配置可以在install.sh中进行指定

**Comment by dailidong** [comment]
version 1.2  can support task run on specified machines through by worker group

**Comment by dailidong** [comment]
this is a  great conversation
