### ISSUE TITLE
Non compliant code

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#1219]
![image](https://user-images.githubusercontent.com/29528966/68728770-2db92b80-0603-11ea-8cc9-eb5d2a5a1cc8.png)

![image](https://user-images.githubusercontent.com/29528966/68728857-6822c880-0603-11ea-9b06-a6a6b062d4cd.png)

the mapping in controller cannot be hump type.

**Comment by nauu** [comment]
i have a pr #1384  fixed this issue , can you review it ? @lenboo
