### ISSUE TITLE
Data flow architecture diagram (数据流向架构图)

### ISSUE THREAD

**Issue by hujiang75277381** [apache/incubator-dolphinscheduler#123]
请大佬 提供一个 模块之间的数据流向架构图，可以使新手读代码能更准确和更方便，谢谢

**Comment by lidongdai** [comment]
we will add doc in version 1.0.3!

**Comment by dailidong** [comment]
version 1.3 as follows:
![image](https://user-images.githubusercontent.com/15833811/96608498-064b0280-132c-11eb-80a0-d1ef8232625c.png)
