### ISSUE TITLE
The first step of the official website login in with incorrect password(官网快速上手第一步登录给的密码不正确)

### ISSUE THREAD

**Issue by ygksy** [apache/incubator-dolphinscheduler#1238]
https://dolphinscheduler.apache.org/zh-cn/docs/user_doc/quick-start.html
官网快速上手给的默认的用户名和密码登录不了

**Comment by liubinpy** [comment]
@ygksy escheduler123

**Comment by dailidong** [comment]
for now please see https://analysys.github.io/easyscheduler_docs_cn/  

---
目前大家还是看这个文档吧，https://dolphinscheduler.apache.org这个文档是为apache版本准备的，不留神提前发了！omg！

**Comment by dailidong** [comment]
for now you can download 1.1.0 release version: 

https://github.com/apache/incubator-dolphinscheduler/releases/download/1.1.0/escheduler-1.1.0-ui.tar.gz

https://github.com/apache/incubator-dolphinscheduler/releases/download/1.1.0/escheduler-1.1.0-backend.tar.gz

---
当前大家可以下载1.1.0 release版本，这个版本是进入孵化器之前的版本，apache版本也在努力测试中

**Comment by qiaozhanwei** [comment]
website has modify
