### ISSUE TITLE
1.1.0 backend instal.sh unexcepted '('

### ISSUE THREAD

**Issue by krystalics** [apache/incubator-dolphinscheduler#1242]
./install.sh: 386: ./install.sh: Syntax error: "(" unexpected
HostAddr=({ips,..})

**Comment by dailidong** [comment]
which operation do you use?

**Comment by krystalics** [comment]
ubuntu 16.04

**Comment by krystalics** [comment]
> which operation system do you use?

ubuntu 16.04LTS

**Comment by xingchun-chen** [comment]
If you still have problems, please upgrade to the latest version 1.3.2 and try
