### ISSUE TITLE
界面优化问题

### ISSUE THREAD

**Issue by wangsvip** [apache/incubator-dolphinscheduler#1247]
工作性质，我之前都是自己用Shell来实现任务调度，那样是很灵活，但是越写越复杂，一言以蔽之，后期不便于他人维护。
       更换EasyScheduler来作为项目的调度工具，我发现每次定义shell脚本来执行任务时，弹出的框也太窄了！就不能大气一点弹出半个屏幕让我来改么？我每次都是复制一篇shell,建立多个任务来进行微调，每次shell一行写的太长，我就得翻到最底下拖到最后面在进行微调，我不建议我每次微调都在文本工具里调好，再粘贴到创建shell任务界面，如果我有80个任务呢，我要在文本微调80次，在粘贴进去，如果我有八百个，八千个，八万个任务呢？我都要在文本改好贴过来用么？这也太费劲了吧，所以大气一点弹出半个屏幕来让我改，或者你要定义这个面板是可以自由拖动放大的，否则用户体验度也太差了！
       每次修改节点名称的时候我都会复制上一个节点名称，在建立下个节点名称时加个后缀，每次只要选中一行按着鼠标移动出弹窗至左边的空白处时，弹窗就会自己缩回去，为什么要缩回去？你管我鼠标移动到哪，我选中你这一行了，你就不应该缩回去！
      还有这个节点名称，为什么是nodeName?搞的我以为是物理机node节点，这里应该是一个Job下有多个Task,而这里建议更名为TaskName,任务名称！

**Comment by Yeleights** [comment]
you can upload your shell script to the resource center, then you can online modify the shell script.
###
在线编辑脚本，可以将脚本上传到资源中心，或者直接在资源中心写脚本。dolphinscheduler是调度工具，不建议将开发调试工作置于调度器中

**Comment by dailidong** [comment]
anybody else's idea?

**Comment by dailidong** [comment]
@wangsvip  when talk about IDE, what about Webank's open source IDE tool: Scripts?
