### ISSUE TITLE
 Application id error in parsing log after Flink task starts

### ISSUE THREAD

**Issue by Right-ydd** [apache/incubator-dolphinscheduler#1298]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Flink流处理任务启动后 dolphinscheduler中的任务状态变为完成，但是Flink任务，还在运行并未执行完毕或关闭

After the Flink stream processing task is started, the task status in the dolphinscheduler becomes complete, but the Flink task is still running or not closed.

    `private String findAppId(String line) {
        Matcher matcher = APPLICATION_REGEX.matcher(line);
       // 此处应去掉checkFindApp(line) 判断条件
      // The checkFindApp(line) condition should be removed here.
        if (matcher.find() && checkFindApp(line)) {
            return matcher.group();
        }
        return null;
    }`

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 创建带有Flink任务的GAG，   Create a GAG with a Flink task
2. 手动执行运行 ，  Manual execution
3. 查看任务状态 ，   View task status

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -dev

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by qiaozhanwei** [comment]
OK，#1299 pr fix this bug
