### ISSUE TITLE
请问如何获取当前跑批的日期

### ISSUE THREAD

**Issue by jinchaoxiang** [apache/incubator-dolphinscheduler#1303]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.
在shell作业中请问如何获取当前跑批的日期，有没有全局变量或者函数

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by Yeleights** [comment]
In dolphinscheduler docs, chapter **Time Customization Parameters**:
Support code to customize the variable name, declaration: ${variable name}. It can refer to "system parameters" or specify "constants".
about time parameters: 
yesterday -> $[yyyy-MM-dd-1]
today -> $[yyyy-MM-dd]
p_year -> $[yyyy]
p_month -> $[yyyy-MM]
p_day -> $[yyyy-MM-dd]
时间参数这块建议详细看一下官方文档中的，时间自定义参数章节
上面给出了一个时间自定义的例子

**Comment by jinchaoxiang** [comment]
@Yeleights 你好 能否提供下官方文档中关于这个知识点的具体地址 我在https://dolphinscheduler.apache.org/zh-cn/这个链接里没有找到
