### ISSUE TITLE
项目间任务依赖关系/Inter-project task dependencies

### ISSUE THREAD

**Issue by wangsvip** [apache/incubator-dolphinscheduler#1307]
举例：做数据仓库，就建立这一个账户，但是一个账户分了不同的小组再做，每个小组建立自己的项目，A小组的任务执行完触发B小组的任务，B再触发C小组的任务，这样做的好处就是避免了像之前A/B/C小组的任务都是定时任务，A：1点执行，B：2点执行，C：3点执行，如果说A的数据今天没过来，B到了2点执行了，C也到了3点执行了，没有数据这样执行不就是浪费集群资源么？

再举例：数据仓库分为ods、dw、dm三层，每一层都是一个项目，我在一个账户下分别建立这三个项目，每一层都由一批同事在做，我需要ods层拿到今天的数据然后触发dw层的清洗再触发dm层的计算，每一层都是环环相扣的，需要依赖的，而且是跨项目依赖，而不是你们推荐的那样，扭成一锅粥，非要建到一个工作流下，odsTask---->dwTast----->dmTask,这种做法不就乱套了么，ods的同事写完工作流，dw的同事再后面补上一层，dm的同事再补上一层？这显然是错的，一个公司里都是很多小组在做，像这种跨小组任务怎么可能扭到一个工作流里面。

目前解决方案：在dolphinscheduler没有任务依赖时，ods层数据进来的时候会在一个文件下建立状态文件，或者是mysql中建一张状态表来记录数据处理完的标识，然后下一层计算先去判断上一层输出的状态标志，再决定当前任务的执行与否。

总结：公司都是有规矩的，都是分组做事，不可能把任务扭到一起！

另外：这都啥年代了，马上0202年了，任务居然不能分页查看，每页10条？？？？
任务还不能批量上线/下线，这个也太low了吧，我建了800个任务，难道我要一个一个点的上线/下线？？？

================================================================

Example: data warehouse, this can build up an account, but an account points to do A different group, each group set up their own project, A team task execution of the trigger B team tasks, and then trigger group C B task, the advantage is avoided as before A/B/C group tasks are timing task, A: 1, B: C: on 2 points, 3 points, if A data didn't come today, carried out by 2 PM, B C also carried out by 3 PM, no data that is not A waste of cluster resources?

For example:Data warehouse is divided into ods, dw, dm three layers, each layer is a project, I respectively set up under an account this three projects, each layer by a group of colleagues in do, I need to get today's data and then trigger the ods layer dw cleaning to trigger the dm layer calculation, each layer is linked together, need to rely on, and it is cross project dependencies, rather than you recommended, twist a mess, have to build to a working flow, odsTask -- -- -- -- > dwTast -- -- -- -- -- > dmTask, this action is not were mixed, ods colleagues to finish the workflow,Dw colleagues add another layer, dm colleagues add another layer?This is obviously wrong, as there are many teams in a company, how can a cross-team task like this be twisted into a workflow.

Current solution: when dolphinscheduler does not have a task dependency, the ods layer will create a status file in a file when the ods layer data comes in, or a status table in mysql to record the status of the data processed, and the next layer will determine the status of the previous layer before deciding whether the current task is executed or not.

Conclusion: the company has rules, are working in groups, impossible to twist the task together!

Additional: this all what age, immediately 0202 years, the task incredibly can't page view, each page 10????
Tasks can not batch online/offline, this is too low, I built 800 tasks, do I want a point of online/offline???

**Comment by zixi0825** [comment]
跨项目依赖在1.2.0中已经实现了

**Comment by wangsvip** [comment]
> 跨项目依赖在1.2.0中已经实现了

好的，这个是目前遇到的最大的问题，还有很多地方最好能微调下，我有很多使用过程中的建议，如果能采纳，那这将会是一个了不起的项目。

**Comment by break60** [comment]
> > 跨项目依赖在1.2.0中已经实现了
> 
> 好的，这个是目前遇到的最大的问题，还有很多地方最好能微调下，我有很多使用过程中的建议，如果能采纳，那这将会是一个了不起的项目。
> 例如：
> 1.分页查看，每页固定10条，我觉得很不合理，至少要留给用户一个可选的条数。
> 2.批量上线下线的问题
> 3.用户创建shell任务的界面，右边弹出的框太小了，我的shell经常会写的很长，要拖到最下面才有进度条来查看后面的内容。你至少要留给我很大空间能够让我看到我的命令，或者就放弃这种右边弹框的方式，直接正中央弹出，并且这个弹框是可以随意移动，可以伸缩大小的，这样就不要纠结shell长度的问题。
> 4.创建shell任务界面的时候，所有东西都填好了，不小心在左边空白处，点了下鼠标，弹框就缩回去了，然后我填的很多东西都没有了，我很气知道么，好多次就是这样，我填了一大堆，然后就没了，我觉得应该给用户一个关闭当前弹框的按钮，而不是不小心点击了空白界面就什么都没有了。
> 5.还是shell创建页面，如果我填了很多东西，突然我想放弃这次任务，我点击了chrome左上角的后退按钮，返回到了“工作流定义”界面，这个时候弹框还会存在，我觉得这是个界面BUG。
> 6.设置定时任务点击“执行时间”按钮，会导致API使用内存不释放，导致闪退，只能重启服务，这个问题可能会修复。
> 7.建立Dependent任务时，我的任务名字会很长，回显shell名称那里，太长的任务名字显示不了，找不到哪个是我想要的，只能输入名字精确搜索，这里应该要优化一下，至少让用户能完整的看到任务名称，或者把鼠标移上去，能显示完整的名称。
> 8.我觉得建立子任务名称，不应该叫节点名称，让人很容易想成是物理机节点名称，一个Job下由多个Task组成工作流,而那里应该改为TaskName(任务名称),而不是NodeName(节点名称)。
> 9.应该让管理员控制每个账户有哪些可选的work工作组，我们之前发生了一件事，就是本来在大数据平台的建表任务，阴差阳错跑到TiDB上建表了，首先能确定你是在什么平台跑数据的，然后只授权一个默认的work工作组，，如果需要连接多个地方，在授权这个账户多个work工作组。

Regarding your suggestion, we have fixed a part in # 1339

**Comment by break60** [comment]
> > 跨项目依赖在1.2.0中已经实现了
> 
> 好的，这个是目前遇到的最大的问题，还有很多地方最好能微调下，我有很多使用过程中的建议，如果能采纳，那这将会是一个了不起的项目。
> 例如：
> 1.分页查看，每页固定10条，我觉得很不合理，至少要留给用户一个可选的条数。
> 2.批量上线下线的问题
> 3.用户创建shell任务的界面，右边弹出的框太小了，我的shell经常会写的很长，要拖到最下面才有进度条来查看后面的内容。你至少要留给我很大空间能够让我看到我的命令，或者就放弃这种右边弹框的方式，直接正中央弹出，并且这个弹框是可以随意移动，可以伸缩大小的，这样就不要纠结shell长度的问题。
> 4.创建shell任务界面的时候，所有东西都填好了，不小心在左边空白处，点了下鼠标，弹框就缩回去了，然后我填的很多东西都没有了，我很气知道么，好多次就是这样，我填了一大堆，然后就没了，我觉得应该给用户一个关闭当前弹框的按钮，而不是不小心点击了空白界面就什么都没有了。
> 5.还是shell创建页面，如果我填了很多东西，突然我想放弃这次任务，我点击了chrome左上角的后退按钮，返回到了“工作流定义”界面，这个时候弹框还会存在，我觉得这是个界面BUG。
> 6.设置定时任务点击“执行时间”按钮，会导致API使用内存不释放，导致闪退，只能重启服务，这个问题可能会修复。
> 7.建立Dependent任务时，我的任务名字会很长，回显shell名称那里，太长的任务名字显示不了，找不到哪个是我想要的，只能输入名字精确搜索，这里应该要优化一下，至少让用户能完整的看到任务名称，或者把鼠标移上去，能显示完整的名称。
> 8.我觉得建立子任务名称，不应该叫节点名称，让人很容易想成是物理机节点名称，一个Job下由多个Task组成工作流,而那里应该改为TaskName(任务名称),而不是NodeName(节点名称)。
> 9.应该让管理员控制每个账户有哪些可选的work工作组，我们之前发生了一件事，就是本来在大数据平台的建表任务，阴差阳错跑到TiDB上建表了，首先能确定你是在什么平台跑数据的，然后只授权一个默认的work工作组，，如果需要连接多个地方，在授权这个账户多个work工作组。

Regarding your suggestion, we have fixed a part in #1339

**Comment by ruxtain** [comment]
这是开源项目啊，你要用肯定免不了二开的。
