### ISSUE TITLE
The source code to compile  Package update lib

### ISSUE THREAD

**Issue by hongshouwei** [apache/incubator-dolphinscheduler#1311]
We used ideal to develop the source code of escheduler_api subproject, and changed it into a jar package to the lib jar package under the Linux environment escheduler_back. After restarting the background script, the page login password was correct and did not report an error, but could not enter the inner module

**Comment by dailidong** [comment]
Brower debug(use F12) to see the response content from api server， and you also should see api server runtime log!

**Comment by hongshouwei** [comment]
error info:failed to load resource : the server responded with a status of 502
uncaught (in promise) TypeError:cannot read property 'userType' of undefined at index.js:31

**Comment by xingchun-chen** [comment]
Is your problem solved？
