### ISSUE TITLE
ERROR 1022 (23000): Can't write; duplicate key in table 't_escheduler_task_instance'[BUG] bug title 

### ISSUE THREAD

**Issue by JOSEPH-HU** [apache/incubator-dolphinscheduler#1315]
mysql数据库版本：5.6.28
ERROR 1022 (23000): Can't write; duplicate key in table 't_escheduler_task_instance'

**Comment by dailidong** [comment]
could you show the result of execute sql command: `describe t_escheduler_task_instance`
