### ISSUE TITLE
[BUG] rename FILE successfully (mysql), while hdfs is unavailable

### ISSUE THREAD

**Issue by qrfxiaoge** [apache/incubator-dolphinscheduler#1316]
**Describe the [bug**
rename FILE successfully (mysql), while hadoop is Unavailable

**To Reproduce**
Steps to reproduce the behavior, for example:
1. rename **FILE** A to B , while hdfs server is Unavailable
hdfs服务异常时，对文件A重命名，修改为B

**Expected behavior**
the file's name should be maintained
mysql存储的文件名不变

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Requirement or improvement
throw runtimeException in catch block / rollback manually

**Comment by dailidong** [comment]
good job , would you like to submit a pr to resolve this issue?

**Comment by qrfxiaoge** [comment]
yeah. it's my pleasure.

**Comment by dailidong** [comment]
@qrfxiaoge ，please add my wechat:510570367, if you need help, when added, please tell me your github id, we have developer group, I will invite you join,  thx!

**Comment by dailidong** [comment]
@qrfxiaoge ，please add my wechat:510570367, if you need help, when added, please tell me your github id, we have developer group, I will invite you to join group,  thx!

**Comment by qrfxiaoge** [comment]
I'm already in the wechat developer group. Thanks!

please review codes later. 
https://github.com/apache/incubator-dolphinscheduler/pull/1352

**Comment by lgcareer** [comment]
> I'm already in the wechat developer group. Thanks!
> 
> please review codes later.
> #1352

please view pr #1352,  and give further information, thx

**Comment by dailidong** [comment]
has this issue  been resolved?
