### ISSUE TITLE
Find my question on the process of deploying the environment and running the project 

### ISSUE THREAD

**Issue by Aries1314** [apache/incubator-dolphinscheduler#1318]
部署本地环境就是按照开发指南进行的

1.本地 前端node环境 已经部署好  

	escheduler-ui 中配置.env 文件配置是：
	# 后端接口地址
	API_BASE = http://127.0.0.1:8888
	# 本地开发如需ip访问项目把"#"号去掉

	#DEV_HOST = 127.0.0.1

2.代码运行在idea运行 数据库是用的集群的mysql zookeeper用是集群中的zookeeper

	启动main方法 是escheduler-api的CombinedApplicationServer

	运行的结果 Alert Server ready start!

3.用谷歌浏览器按照前端开发文档上说的进行访问项目 输入账号密码 不能登录到项目中 

	F12 报错
 
	GET http://localhost:8888/escheduler/users/get-user-info?_t=0.6996130762668742 500 (Internal Server Error)

	Uncaught (in promise) TypeError: Cannot read property 'userType' of undefined
    at eval (index.js?5a24:31)

4.终端运行的node

	报错如下：
	[HPM] Error occurred while trying to proxy request /escheduler/login from 127.0.0.1:8888 to http://127.0.0.1:8888 (ENOBUFS) 	(https://nodejs.org/api/errors.html#errors_common_system_errors)
	[HPM] Error occurred while trying to proxy request /escheduler/users/get-user-info?_t=0.6996130762668742 from 127.0.0.1:8888 to http://127.0.0.1:8888 (ENOBUFS) 	(https://nodejs.org/api/errors.html#errors_common_system_errors)

接下怎么处理？

**Comment by break60** [comment]
查看8888端是不是冲突，被占用了
