### ISSUE TITLE
[Feature] User and process manage authorization improvement

### ISSUE THREAD

**Issue by KEN-LJQ** [apache/incubator-dolphinscheduler#1321]
**Improvement expected**
The process support authorization manage, the user who create the process can set it as private or public.  As the public process, the admin also can configure whether it is visible or editable for other user. 
And when the user was deleted, the public process still exists and can be edit, because it is a part of project.

**Current problem**
Currently, we want each developer has their own account as user, developer can create process within project, and each process my related by dependence. But we found out, when we delete a user, the process created by this user can not be edit anymore, and cause some js error on frontend ui.

**Comment by dailidong** [comment]
I have created a new issue for collecting permission redesign. #1333

**Comment by CalvinKirs** [comment]
please see #1333
Focus on #1333 discussion
