### ISSUE TITLE
[BUG] 文件管理-上传的文件太大时线程不工作

### ISSUE THREAD

**Issue by xwhfcenter** [apache/incubator-dolphinscheduler#1324]
上传的资源文件太大的时候，校验不通过，无法继续执行

**Comment by Yeleights** [comment]
you can add the nginx config:  client_max_body_size 1024m;

vi /etc/nginx/nginx.conf

#set the upload limit 1G
client_max_body_size 1024m;

是否配置了nginx的上传大小限制？ 可以参照上面的描述配置一下

**Comment by xwhfcenter** [comment]
是的，是nginx的大小限制造成的问题
