### ISSUE TITLE
DS功能建议/DS Feature Suggestions

### ISSUE THREAD

**Issue by wangsvip** [apache/incubator-dolphinscheduler#1339]
### 目前遇到的最大的问题，是跨项目依赖，据说1.2.0会支持这个功能；
**还有很多地方最好能微调下，我有很多使用过程中的建议，如果能采纳，那这将会是一个了不起的项目；
例如：
1.分页查看，每页固定10条，我觉得很不合理，至少要留给用户一个可选的条数。**
![image](https://user-images.githubusercontent.com/30864196/69940547-89e5e000-151d-11ea-86ff-5b3f6b10e20b.png)

**2.批量上线下线的问题**
![image](https://user-images.githubusercontent.com/30864196/69942447-83586800-151f-11ea-9c19-7b55f628de1d.png)

**3.用户创建shell任务的界面，右边弹出的框太小了，我的shell经常会写的很长，要拖到最下面才有进度条来查看后面的内容。你至少要留给我很大空间能够让我看到我的命令，或者就放弃这种右边弹框的方式，直接正中央弹出，并且这个弹框是可以随意移动，可以伸缩大小的（非常需要这个功能，对于拥有2个显示器的人来说，习惯将弹出的页面放大然后拖到另一个分屏上来编辑任务），这样就不要纠结shell长度的问题。**
![image](https://user-images.githubusercontent.com/30864196/69942599-a125cd00-151f-11ea-9e16-c0667da05950.png)

**4.创建shell任务界面的时候，所有东西都填好了，不小心在左边空白处，点了下鼠标，弹框就缩回去了，然后我填的很多东西都没有了，我很气知道么，好多次就是这样，我填了一大堆，然后就没了，我觉得应该给用户一个关闭当前弹框的按钮，而不是不小心点击了空白界面就什么都没有了。**
**5.还是shell创建页面，如果我填了很多东西，突然我想放弃这次任务，我点击了chrome左上角的后退按钮，返回到了“工作流定义”界面，这个时候弹框还会存在，我觉得这是个界面BUG。**
![image](https://user-images.githubusercontent.com/30864196/69940422-3f646380-151d-11ea-9617-73d6e46188a9.png)

**6.设置定时任务点击“执行时间”按钮，会导致API使用内存不释放，导致闪退，只能重启服务，这个问题可能会修复。**
![image](https://user-images.githubusercontent.com/30864196/69942333-6b80e400-151f-11ea-8840-4ae9fdcfcf71.png)

**7.建立Dependent任务时，我的任务名字会很长，回显shell名称那里，太长的任务名字显示不了，找不到哪个是我想要的，只能输入名字精确搜索，这里应该要优化一下，至少让用户能完整的看到任务名称，或者把鼠标移上去，能显示完整的名称。**
![image](https://user-images.githubusercontent.com/30864196/69940310-ebf21580-151c-11ea-859a-a0d05c3fb276.png)

**8.我觉得建立子任务名称，不应该叫节点名称，让人很容易想成是物理机节点名称，一个Job下由多个Task组成工作流,而那里应该改为TaskName(任务名称),而不是NodeName(节点名称)。**
![image](https://user-images.githubusercontent.com/30864196/69940611-aa159f00-151d-11ea-891e-94efb19fff59.png)

**9.应该让管理员控制每个账户有哪些可选的work工作组，我们之前发生了一件事，就是本来在大数据平台的建表任务，阴差阳错跑到TiDB上建表了，首先能确定你是在什么平台跑数据的，然后只授权一个默认的work工作组，，如果需要连接多个地方，在授权这个账户多个work工作组。**
**10.将任务下线调整任务后，每次上线都要重新选择work工作组，用户体验度不是很好；如果我上次选择过在哪个work工作组下执行任务，那这次也将会跑在上次work环境中，只有明确要更换work工作组，用户才需要重新选择，而不是每一次都要选择work工作组；至少要记住我上次的选择。**
![image](https://user-images.githubusercontent.com/30864196/69940668-c6194080-151d-11ea-9fad-70a34fbf835b.png)

**11.每次执行任务的时候，点击“运行”按钮，弹出的页面我希望能回显出我当前要运行的任务名称，如果我点错了，而弹出的框没有回显，我怎么判断当前是执行的哪一个任务？如果能把当前任务名称显示出来，我就知道我点错了任务，这个功能非常重要！！！**
![image](https://user-images.githubusercontent.com/30864196/69940779-0a0c4580-151e-11ea-988f-3983494cf3ad.png)

**12.这里当前正在运行的图标，应该为实时刷新，或者是局部刷新，要检查任务状态是否从正在运行变为已结束，而不是我每次提交了任务都要按F5来刷新当前页面看任务是否执行完成。这应该是工具自己实现的，不要让用户手动刷新！**
![image](https://user-images.githubusercontent.com/30864196/70197796-ea586580-1747-11ea-8780-a10783b56147.png)

**13.鼠标移动到一行的背景颜色太浅了，要加深一些，这样更醒目！**
![image](https://user-images.githubusercontent.com/30864196/70300896-c40ff400-1833-11ea-8c04-92c057942545.png)

**14.创建任务时，没有加收件人邮箱，后面想加上，我靠，加完邮件没有保存？直接运行？这就有问题啊，我要保存编辑，我不要运行！**
![image](https://user-images.githubusercontent.com/30864196/70308906-3dfda880-1847-11ea-954f-673e7108ef8b.png)

**15.关于补数，目前补数只能连选日期，我需要这样一个功能，选择几个日期执行任务，串行或并行执行，例如2019-12-12，2019-12-18，2019-12-20，2019-12-23，很明显这样的执行日期是不连续的，为了实现这个功能，我不得不一个日期执行完后在，在执行一个日期，这样做的效率太低了，我没法专注做其他事情，我得时刻关注当前任务是否执行完毕，然后启动下一个任务。如果你推荐我配置一个工作流来补数，我个人是很不建议的，补数是工具来实现的，我只需要点点点就好了。**
![image](https://user-images.githubusercontent.com/30864196/71617563-95005e80-2bf6-11ea-884d-04c52ba26f90.png)

**16.任务触发的问题，举例（dw层的任务是ods层的【子任务】，目前配在一个工作流）ods层的任务执行完后触发dw层的任务；此时将dw层的任务下线，工作流跑不起来（因为它的子任务下线）；其实对于工作流中的ods层任务来说，它不需要关心下游任务是否在线，只有ods层执行完成后才去判断下游任务是否是在线状态；目前这样的影响是工作流跑不起来后，我需要在工作流里设置dw层这个子任务为禁止执行才可以；我认为这是不合理的，将dw层任务下线后，是不能影响ods层正常执行的，假设有100个任务，我需要把100个工作流里的子任务禁止掉，然后在下线dw层任务；有没有考虑过这么多任务都是定时执行，修改工作流之后重新上线，不但要将任务上线，还要将定时上线，万一忘记了呢，产生误操作的可能性会变大！**

**17.shell 传日期参数这个，这里起码要加一个下拉框，让用户选择是是什么格式的，因为经常会是yyyy-MM-dd，这种格式，如果不加格式选择，我自己还要转换一次，尤其数据库那里，我要用date_format,将你们的yyyyMMdd 转为yyyy-MM-dd，这对于数据库来说是会消耗性能的。**
![image](https://user-images.githubusercontent.com/30864196/71657387-9b1f4800-2d7a-11ea-856d-3d91f969c5c2.png)

**18.执行sql的时候，这里我怎么判断我传入的参数是否是我想要的日期类型？我用这种方式来执行会报错，我要它在日志里打印出我的取值参数！**
![image](https://user-images.githubusercontent.com/30864196/76744974-0d1b0100-67b0-11ea-99c3-8775f02f773c.png)
![image](https://user-images.githubusercontent.com/30864196/76744984-11dfb500-67b0-11ea-884d-ee889f5f3744.png)

**19. 上次的界面BUG问题修复，创建新的shell，点击数据源中心，会变成这样！**
![image](https://user-images.githubusercontent.com/30864196/80473813-3ca95580-8979-11ea-9512-068a6abf4a18.png)

**20. 发现个BUG，设置变量名的地方，如果后面有空格，则不能正确获取到日期，前一天获取到的是错误的！应该输出20200427，20200428 才对！**

![image](https://user-images.githubusercontent.com/30864196/80474383-f7d1ee80-8979-11ea-8334-877bda0a9756.png)
![image](https://user-images.githubusercontent.com/30864196/80474481-189a4400-897a-11ea-9e89-dc95b642a5a2.png)

**21.界面优化问题，这里界面明明很大，第二行的参数为什么要截断？，这个要一目了然的显示出来，不要被截断！！！**
![image](https://user-images.githubusercontent.com/30864196/80474836-8a728d80-897a-11ea-9321-873a40ded3cf.png)

================================================================

The biggest problem is cross-project dependencies, which are said to be supported in 1.2.0.
There are a lot of things that you might want to fine-tune. I have a lot of Suggestions for how to use it.
Such as:
1. Pagination, fixed 10 pages per page, I think it is unreasonable, at least leave the user an optional number of pages.
2. Batch online and offline problems
3. When the user creates the interface of shell task, the pop-up box on the right is too small. My shell often writes very long, so I have to drag it to the bottom to have a progress bar to check the following content.You must be at least leave me a lot of room to let me see my command, or give up this spring box on the right way, is the central pop up directly, and the modal dialog is free to move, to scale the size of the (very need this function, with two monitors, used to enlarge the page will pop up and then dragged to another split screen editing tasks), so don't tangle of shell length problem.
Task 4. Create a shell interface, everything is filled out, accidentally in the left-hand margin, point under the mouse, bounced back, then I fill a lot of things all have no, I know, angrily this is many times, I filled out a lot of, and then you didn't, I think I should give the user a close the current play button box, rather than accidentally click on a blank screen is nothing.
5. Shell created the page. If I filled in a lot of things and suddenly I wanted to give up the task, I clicked the back button in the top left corner of chrome and went back to the "workflow definition" interface.
6. Set timing task click the "execution time" button, which will result in API usage memory not released, resulting in flash back, only restart the service, this problem may be fixed.
7. Establish Dependent tasks, task name I will be very long, echo the shell name there, is too long task name display, which is what I want, can't find can only enter the name search precision, here should be optimized, at least let users can see the task name, complete or move the mouse, can display the complete name.
8. I think creating a subtask name, instead of calling it a NodeName, is easy to think of it as a physical machine NodeName, a workflow consisting of multiple tasks under a Job, where it should be TaskName instead of NodeName.
9. Should let the administrator control each account what are the optional work group, something happened between us is in big data platform table task of building, ran to the table is built on the TiDB mistake, first of all to determine what you are running data of the platform, only then a default authorization work group, and if you need to connect to multiple places, authorized the account in multiple group work.
10. After taking the task offline and adjusting the task, we have to choose the work group again every time we go online. The user experience is not very good.If I chose which work group to work under last time, I will also work in the last work environment this time. Only when it is clear to change the work group, the user needs to choose again, instead of choosing the work group every time.At least remember my last choice.
11. When executing a task, click the "run" button and the pop-up page will display the name of the task I want to run. If I click wrong and the pop-up box does not echo, how can I determine which task is being executed?If I can display the current task name, I know I clicked the wrong task, this function is very important!!

**Comment by lenboo** [comment]
Thank you very much for your suggestions. They are all very useful. We will consider them carefully. We'll consider them  seriously!

**Comment by wangsvip** [comment]
> 非常感谢您的建议。它们都是非常有用的。我们将仔细考虑它们。我们会认真考虑他们的！

好的，请持续关注我的这个话题，我会不定时增加新的想法，以便于能了解到问题所在；拥抱开源，我希望中国能做出伟大的软件！

=================================================================

Ok, please keep paying attention to my topic, I will add new ideas from time to time, so that I can understand the problem;Embrace open source, I hope China can make great software!

**Comment by break60** [comment]
hi
![image](https://user-images.githubusercontent.com/28628088/69773874-1ebfa500-11cf-11ea-843a-09a134faad5f.png)
第11条建议应该是回显工作流名称吧？
The 11th suggestion is to echo the workflow name？

**Comment by wangsvip** [comment]
> hi
> ![image](https://user-images.githubusercontent.com/28628088/69773874-1ebfa500-11cf-11ea-843a-09a134faad5f.png)
> 第11条建议应该是回显工作流名称吧？
> The 11th suggestion is to echo the workflow name？

是的，这里点击“运行”按钮，弹框一定要回显出来/Yes, click the "run" button here, and the popover must come back

**Comment by break60** [comment]
Points 1, 3, 4, 5, 7, 11 have been optimized in the dev branch

**Comment by break60** [comment]
Regarding your 12th point, we have made a regular refresh of the page. The time is 60 seconds, and the status will be automatically refreshed after 60 seconds.

**Comment by dailidong** [comment]
great advice

**Comment by xingchun-chen** [comment]
Points 6 have fixed in 1.2.0

**Comment by wangsvip** [comment]
> 关于您的第12点，我们已定期刷新页面。时间为60秒，状态将在60秒后自动刷新。

好的，感谢，我更新了新的建议/Ok, thanks, I have updated the new suggestion

**Comment by wangsvip** [comment]
> Points 6 have fixed in 1.2.0

Ok, thanks

**Comment by wangsvip** [comment]
> Regarding your 12th point, we have made a regular refresh of the page. The time is 60 seconds, and the status will be automatically refreshed after 60 seconds.

我更新的问题！

**Comment by break60** [comment]
> > Regarding your 12th point, we have made a regular refresh of the page. The time is 60 seconds, and the status will be automatically refreshed after 60 seconds.
> 
> 我更新了问题！

OK, we'll optimize your suggestions

**Comment by wangsvip** [comment]
> > > Regarding your 12th point, we have made a regular refresh of the page. The time is 60 seconds, and the status will be automatically refreshed after 60 seconds.
> > 
> > 
> > 我更新了问题！
> 
> OK, we'll optimize your suggestions

我更新了问题！

**Comment by chengshiwen** [comment]
Most problems have been optimized, please check the latest version
