### ISSUE TITLE
[QUESTION] 目前的最新版本不支持DB2数据源吗？

### ISSUE THREAD

**Issue by wangxuetao** [apache/incubator-dolphinscheduler#1344]
我看到数据源的配置支持的很丰富，但是唯独没有发现DB2的数据源，如果想配置DB2数据源，该如何操作，希望能够得到回答，THS。

**Comment by dailidong** [comment]
not support db2， you can implement it if you have interesting in this feature.  

please update/add title/desc in English, thx!
