### ISSUE TITLE
[QUESTION] Does the latest version not support DB2 DataSources?

### ISSUE THREAD

**Issue by wangxuetao** [apache/incubator-dolphinscheduler#1345]
Hi, I see the configuration of the DataSource supports a lot, but only the DB2 DataSource is not found. How to operate if i want to configure the DB2 DataSource?  I hope to get your answers, thanks.

**Comment by dailidong** [comment]
not support db2， you can implement it if you have interesting in this feature.  

and I will add this as a new feature, maybe somebody want to implemenet it, it's not difficult!

**Comment by nauu** [comment]
im planing to implement it
