### ISSUE TITLE
maven profiles[Feature]

### ISSUE THREAD

**Issue by moonhunter1986** [apache/incubator-dolphinscheduler#1346]
工程开发布署一般有多个环境,prod,test,dev.为什么不使用maven profiles来切换呢,在本地就能编译好完整代码上传.不必到具体环境修改install.sh
![TIM图片20191128103447](https://user-images.githubusercontent.com/44829723/69772406-cf777580-11ca-11ea-8ed1-72c416257ef7.png)
![TIM图片20191128103519](https://user-images.githubusercontent.com/44829723/69772408-cf777580-11ca-11ea-9b72-10c08d69cafc.png)

**Comment by dailidong** [comment]
good idea, we will consider it later! thx!

**Comment by lenboo** [comment]
Hello @moonhunter1986 
For English only, other languages will not accept.
Please close this issue and submit a new issue in English again.
