### ISSUE TITLE
[QUESTION] How do zookeeper cluster changes change the configuration zookeeper集群更改，怎么修改scheduler相关配置

### ISSUE THREAD

**Issue by xiaot502** [apache/incubator-dolphinscheduler#1348]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
管理菜单-》zookeeper管理
显示节点不可用，而且我把zookeeper集群端口号有做修改。
我的问题是：1.怎么在已经初始化安装之后修改这个节点配置信息
2.正确的节点配置是只填写zookeeper的ip地址还是需要接上端口号（ip:port）
3.如果没有编辑的地方，界面友好性是不是差了一点儿可不可以有一个在界面上编辑的地方。
===================================================

Management menu - "zookeeper management
The display node is not available, and I changed the zookeeper cluster port number.
My question is: 1. How to modify the node configuration information after the initial installation
2. The correct node configuration should only fill in the IP address of zookeeper or should the port number (IP :port) be added?
3. If there is no editing place, is the interface less friendly? Can there be a place to edit on the interface?
**Which version of DolphinScheduler:**
 -[1.1.0-preview]
![QQ图片20191128151524](https://user-images.githubusercontent.com/57660469/69784970-0d3bc480-11f2-11ea-8d6a-4596c3024164.png)

**Comment by dailidong** [comment]
you should find zookeeper.properties in conf dir:
![image](https://user-images.githubusercontent.com/15833811/69877921-655fed00-12fe-11ea-9eec-1a5c3b13057b.png)
