### ISSUE TITLE
Apache release version

### ISSUE THREAD

**Issue by kinbod** [apache/incubator-dolphinscheduler#1363]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
When will Apache release

**Which version of DolphinScheduler:**
How much  changes between the current version and the later version, is it easy when update from current to later version?

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lenboo** [comment]
fist, We've done the publishing process in the mailing list, please subscribe to dev@helphinscheduler.apache.org for progress.
second, when the first apache release published, there would be release note in the new version.
and there also have upgrade document for the previous version to new's.
