### ISSUE TITLE
[Feature] User defined installation of nginx

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#1369]
I think the current front-end installation and deployment needs to be optimized, mainly including the following points:

- 1、`Nginx` allows users to customize the installation, because sometimes there is no network on the server
- The installation and deployment are divided into two steps:
  - Step 1: let users customize the installation of `nginx`
  - Step 2: execute the installation script. In the installation script, you only need to replace or add the related commands in the `nginx` configuration file, as well as the related operations

**Comment by dailidong** [comment]
very good idea, I will add this idea!

**Comment by dailidong** [comment]
maybe we don't need nginx.

#1376 will discussion how to simplify the deployment.  if you are interesting in it ,please leave message

**Comment by chengshiwen** [comment]
Close this issue since nginx has been removed
