### ISSUE TITLE
[Feature]  I think that the submit button on all popup windows should have an event listener, click Enter to submit the data directly

### ISSUE THREAD

**Issue by zzq1314zll** [apache/incubator-dolphinscheduler#1370]
I think that the submit button on all popup windows should have an event listener, click Enter to submit the data directly
-
我认为所有的弹窗上的提交按钮都应该有一个事件监听，点击回车直接提交数据

**Comment by lenboo** [comment]
does this cause misoperation?

**Comment by zzq1314zll** [comment]
No, when you click enter, a prompt box pops up, and the user clicks OK to submit the data, so you can delete it by mistake.
不会的呀，当点击enter ，弹出提示框，用户点击确定提交数据，这样就可以误删除了呀

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
