### ISSUE TITLE
[DISCUSSION] how to simplify the deployment of DolphinScheduler？

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#1376]
this issue will discuss how to simplify the deployment of DS, so if you have any idea about this. please leave a message.

**Comment by dailidong** [comment]
#1369   maybe we don't need nginx

**Comment by wuchunfu** [comment]
I think users can choose by themselves, just like we deploy a `web application`, which only provides a few recommended solutions

**Comment by dailidong** [comment]
please discussion on dev mail list

**Comment by dailidong** [comment]
mail list: https://lists.apache.org/thread.html/41606cfa152e01e15faab062103d94f28e96d8943f90a7aa7cad7a81%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by dailidong** [comment]
I think the logback.xml  of MasterServer/WorkerServer/APIApplicationServer/AlertServer config  combine to  one, I will submit a PR

**Comment by dailidong** [comment]
> I think the logback.xml of MasterServer/WorkerServer/APIApplicationServer/AlertServer config combine to one, I will submit a PR

dev branch has merged all service to one logback.xml

**Comment by dailidong** [comment]
#1635 merge configuration also can simplify the deployment

**Comment by dailidong** [comment]
#1511

**Comment by dailidong** [comment]
#1551 remove master server and worker server listening port (5566、7788)

**Comment by dailidong** [comment]
#1575 remove kazoo

**Comment by chengshiwen** [comment]
Close this issue since the deployment of DolphinScheduler has been simplified in 1.3.x
