### ISSUE TITLE
[QUESTION] POST request format

### ISSUE THREAD

**Issue by yh2388** [apache/incubator-dolphinscheduler#1377]
Why use 'application/x-www-form-urlencoded' instead of 'application/json'?

**Comment by break60** [comment]
![image](https://user-images.githubusercontent.com/28628088/70709223-5d994300-1d17-11ea-8850-45a9686d13e6.png)
Here is axios form parameter passing method, you want to change to other parameter passing methods, you can refer to this address: http://www.fly63.com/article/detial/1068

**Comment by yh2388** [comment]
> ![image](https://user-images.githubusercontent.com/28628088/70709223-5d994300-1d17-11ea-8850-45a9686d13e6.png)
> Here is axios form parameter passing method, you want to change to other parameter passing methods, you can refer to this address: http://www.fly63.com/article/detial/1068

It seems that after this modification,  The backend also needs to be modified, which will affect the subsequent upgrade and have a large workload, Do you have any solutions？

**Comment by yh2388** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/20351485/70764589-f4efac00-1d92-11ea-9192-6e6ac5502d38.png">
We need to change to 'payload' method integration with another system, but backend has different processing methods

**Comment by break60** [comment]
Do you need to change all post requests to json?

**Comment by yh2388** [comment]
> Do you need to change all post requests to json?

yes, we need compatible with other api that use application/json method.

**Comment by chengshiwen** [comment]
Close the question since no updates for long time
