### ISSUE TITLE
[BUG] [Resource Management]  resources can not be previewed or updated

### ISSUE THREAD

**Issue by simmonn** [apache/incubator-dolphinscheduler#1397]
**Describe the bug**
if one resource file is renamed with no suffix or no supported suffix, it can not be previewed or updated.

**To Reproduce**
STEP 1: Create a resource, whose name is test.sh. Under the circumstances,you can preview or update this resource's content.But if I take STEP 2, these actions can not be done.
STEP2: Rename test.sh to test.

**Where to find relavant code**
GOTO:
ResouceService
line:505 and 633
**Screenshots**
![image](https://user-images.githubusercontent.com/37128453/70209592-a414fd80-176b-11ea-9b27-3cdd771b149e.png)

**Which version of Dolphin Scheduler:**
[all versions]

**Requirement or improvement
Resources whose suffix is one of txt,log,sh,conf,cfg,py,java,sql,hql,xml,properties can be preview and updated whatever their names are.

change resource.getAlias() to resource.getFileName()

![image](https://user-images.githubusercontent.com/37128453/70209795-1f76af00-176c-11ea-8e62-305b93bbede9.png)

**Comment by nauu** [comment]
I think the real problem is that , When create an resource the name will add the suffix, But When rename the resource there is no suffix add to the name, So When update resource name without suffix just like "test.sh" => "test" , Then the bug reproduced.

**Comment by simmonn** [comment]
that is exactly what I mean, I provided one solution, maybe there is another solution such as adding the resource's suffix automatically to name when renaming this resource @nauu
