### ISSUE TITLE
[QUESTION]  xxx is not in the sudoeser file. The matter will be reported

### ISSUE THREAD

**Issue by yoreyuan** [apache/incubator-dolphinscheduler#1402]
**Describe the question**
There is a Worker node that does not allow users to own sudo. dolphinscheduler has been successfully installed. I specified to execute tasks on this Worker, and reported the following error：
```
cn.escheduler.server.worker.log.TaskLogger:[178]-[taskAppId=TASK_2_4_10] -> xxx 不在 sudoeser 文件中。此事将被报告。
```

**Which version of DolphinScheduler:**
 -[1.1.0]

**Requirement or improvement**
In the source code  [AbstractCommandExecutor.java](https://github.com/apache/incubator-dolphinscheduler/blob/1.1.0/escheduler-server/src/main/java/cn/escheduler/server/worker/task/AbstractCommandExecutor.java) , it is assumed that sudo is required for task execution. Because some workers cannot meet this condition in some environments, I hope this restriction can be lifted.

**Comment by lgcareer** [comment]
please check your install user whether in sudoeser file

**Comment by xingchun-chen** [comment]
Don'y reply for a long time, it will be close
