### ISSUE TITLE
[BUG] There are some word errors and inconsistencies in project website

### ISSUE THREAD

**Issue by ghost** [apache/incubator-dolphinscheduler#1411]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Some words are wrong and inconsistent:
1. In http://dolphinscheduler.incubator.apache.org/en-us/, "Rich Scanerios" should be "Widely Scenarios" or "Rich Scenarios" 
2. In http://dolphinscheduler.incubator.apache.org/en-us/docs/user_doc/subscribe.html, http://dolphinscheduler.incubator.apache.org/en-us/docs/development/developers.html,  The words in the list on the left should follow the hump nomenclature, For example, "Backend deployment" should be "Backend Deployment", etc.

**To Reproduce**
 Open the website, and search the keywords mentioned above.

**Expected behavior**
As described above

**Comment by gfjia-tech** [comment]
I want to fix this bug

**Comment by AhahaGe** [comment]
I will fix this in the coming days.

**Comment by AhahaGe** [comment]
For the Second part, I checked the source code but could not find subscribe file and developer.md  only contains word TODO。 So I just edit the first part.
