### ISSUE TITLE
[BUG] cant start task when i upgrade to version 1.2.0 from 1.1.0

### ISSUE THREAD

**Issue by henliqi** [apache/incubator-dolphinscheduler#1414]
**Describe the bug**
Its really hard to upgrade to version 1.2.0,all the table names has been changed,and a lot shell script must to reconfig.just like reinstall another software ,and when i finish it all the feautrue is ok.but cant start Process when i click the start button .and the success tip is is show,
i try to find the problem in the backend logs but cant find any exceptions,just a few info logs. 

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to Process definition page
2. Click on start button and success tip is slid
3. Go to  process_instance page and no instance display

**Which version of Dolphin Scheduler:**
 -[1.2.0-release]

**Comment by lgcareer** [comment]
did you see t_ds_command table, whether exists data about this process definition.

if have data, please see master server runtime log,  maybe you will find some exception info

**Comment by henliqi** [comment]
yes i find the data  about this process definition in  t_ds_command table,and search all runtime log but no exception .
i notice that old version system have process Messages in queue,when i upgrade to the new version if the Messages will be remove or not ?if not the process Messages in new system will be block and No exceptions.
do you think so?






At 2019-12-09 16:47:13, "lgcareer" <notifications@github.com> wrote:


did you see t_ds_command table, whether exists data about this process definition.

if have data, please see master server runtime log, maybe you will find some exception info

**Comment by qiaozhanwei** [comment]
建议在升级的时候，流程和任务的状态都是终态（成功，失败，停止，暂停），command表，zk队列都不要有数据

It is recommended that when upgrading, the status of processes and tasks are final (success, failure, stop, pause), and there should be no data in the command table and zk queue

**Comment by xingchun-chen** [comment]
Whether the issue has been resolved, if it is resolved, please close it

**Comment by xingchun-chen** [comment]
Do not reply for a long time, temporarily close the issue
