### ISSUE TITLE
V1.2 前端访问失败（无法找到相应资源）

### ISSUE THREAD

**Issue by herbtea0223** [apache/incubator-dolphinscheduler#1415]
后端服务已启动，无法访问dolphinscheduler login页面（页面显示一直加载中）

**nginx日志（access.log）如下：**

*s open() "/前端文件解压目录/dist/escheduler/login" failed (2: No such file or directory), client: 192.xxx.xxx.xx, server: localhost ,request : "POST /edolphinscheduler/login HTTP/1.1

 "GET /dolphinscheduler/users/get-user-info?_t=0.04084118967320416 HTTP/1.1" 502 3693 "http://ip:8888/"

前端解压的目录中无 上述目录

**Comment by dailidong** [comment]
please make sure that which verison do you use?  
1.2 version front-end not exists word "escheduler"

**Comment by dailidong** [comment]
english is needed

**Comment by herbtea0223** [comment]
It's my mistake,thank you for your reply.
