### ISSUE TITLE
[BUG] gitignore file imperfect

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#1420]
I forked the project and checkout branch dev-db, Then i run 'mvn clean install -Prelease -Dmaven.test.skip=true' to build the project. I found 
`dolphinscheduler-dist/dolphinscheduler-backend/target` 
`dolphinscheduler-dist/dolphinscheduler-front/target/` 
`dolphinscheduler-dist/dolphinscheduler-src/target/` 
`dolphinscheduler-ui/dist` 
`dolphinscheduler-ui/node` 
was in the untracked files list.

I checked the .gitignore file and found it is imperfect. To solve it we can edit the .gitignore file and add this lines:
`**/**/target/**`
`dolphinscheduler-ui/dist`
`dolphinscheduler-ui/dist`

@qiaozhanwei  
Is it a bug? And can I update the .gitignore file?

**Comment by qiaozhanwei** [comment]
agree，you can optimize it

**Comment by gaojun2048** [comment]
> agree，you can optimize it

ok
