### ISSUE TITLE
Duplicate code for this project

### ISSUE THREAD

**Issue by zjcnb** [apache/incubator-dolphinscheduler#1421]
Hi, i found @Data annotation for this project. But it 's still has setter and getter method.  i think it is duplicate code. I want to remove it!  What do you think?

**Comment by lenboo** [comment]
thank you very much for your issue.
the getter and setter are depended in the mybatisplus plugin, you can test that.

**Comment by zjcnb** [comment]
OK，i will try



---Original---

**Comment by Technoboy-** [comment]
> Hi, i found @DaTa annotation for this project. But it 's still has setter and getter method. i think it is duplicate code. I want to remove it! What do you think?

Hi brother, we discuss and confirm, it's duplicate code . so would you like to fix this issue?

**Comment by zjcnb** [comment]
yes，i do

**Comment by zjcnb** [comment]
> > Hi, i found @DaTa annotation for this project. But it 's still has setter and getter method. i think it is duplicate code. I want to remove it! What do you think?
> 
> Hi brother, we discuss and confirm, it's duplicate code . so would you like to fix this issue?

yes，i do

**Comment by Technoboy-** [comment]
We have remove lombok dependency in our latest branch , and thanks for your contribution
