### ISSUE TITLE
Character length limit of node custom parameter in workflow definition

### ISSUE THREAD

**Issue by uzdz** [apache/incubator-dolphinscheduler#1437]
The maximum length of node custom parameter in workflow is 64? Please measure whether need to add this limit. My business encrypts strings and the length is far longer than 64.

EasyScheduler Version：1.1.0

**Comment by uzdz** [comment]
![image](https://user-images.githubusercontent.com/28328355/70532430-fd2cc900-1b91-11ea-8cf0-89c753062425.png)

**Comment by lenboo** [comment]
@uzdz 
for english only, 
please update the title and content to english.

**Comment by uzdz** [comment]
> @uzdz
> for english only,
> please update the title and content to english.

Okay

**Comment by lenboo** [comment]
thank you very much.
i think this is a simply change on the code, tThe main problem is that this value is set appropriately. 64 or 128, 256 ?

**Comment by uzdz** [comment]
Is it necessary to set the MaxLength property? If a user-defined parameter corresponds to the table field of MySQL, in order to control the length of MySQL field, I think 256 should be enough, but if there is no MySQL limit, I don't think this property needs to be specified.

This is just a suggestion. Now I solve this problem by writing parameter values directly after the script.

**Comment by lenboo** [comment]
this user-defined parameters are saved in db with json type, the field type is text. so there is not length limit in mysql.
but i think every input should be specified in case of memory problem. and 256 should be enough.  
if you are willing to, please submit pr to improve that.

**Comment by nauu** [comment]
The maxlength is 128 in version 1.2 ,  Does it need change to 256?

**Comment by uzdz** [comment]
> The maxlength is 128 in version 1.2 , Does it need change to 256?

I think it should be changed to 256. Because this is not a hard work, but if the input cannot be made in the development scenario, it will affect the user's use.
