### ISSUE TITLE
[BUG] code comment error

### ISSUE THREAD

**Issue by clay4444** [apache/incubator-dolphinscheduler#1442]
**Describe the bug**
in this class: org.apache.dolphinscheduler.server.master.runner.MasterSchedulerThread. the line number 104, zkMasterClient.getMasterLockPath() The lock path obtained may should be /dolphinscheduler/lock/masters,  but in the comment, is's /dolphinscheduler/lock/failover/master, I think it's easy to mislead people who read the source code,  please check this,  if it does, I can open a pr to fix it

**To Reproduce**
None

**Expected behavior**
Node

**Screenshots**
None

**Which version of Dolphin Scheduler:**
latest version

**Additional context**
None

**Requirement or improvement
None

**Comment by lenboo** [comment]
welcome pr to  fix it

**Comment by dailidong** [comment]
+1, please fix it

**Comment by clay4444** [comment]
@lenboo  
  hi, I have fix the issue in the pr, may be you can review it, so I can close the issue
