### ISSUE TITLE
Seek help! How can I deploy the dolphin scheduler offline?

### ISSUE THREAD

**Issue by haotengteng** [apache/incubator-dolphinscheduler#1448]
求助！请问dolphinscheduler如何离线部署？

**Comment by haotengteng** [comment]
There are many places in the installation script that are installed through yum. In addition, the docking with zookeeper is through kazoo, a three-party Library of Python. This is also installed through pip. How to deal with it offline?

**Comment by dailidong** [comment]
good idea, thx

we are working at simplifying deploy.   documents should consider offline situation.  we will update the document

**Comment by dailidong** [comment]
by the way,  English is needed

**Comment by chengshiwen** [comment]
Close this issue since DolphinScheduler has supported offline-deployment in 1.3.x
