### ISSUE TITLE
[Feature]前端访问支持vue通过NGINX部署在子目录或者二级目录

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#1450]
当前访问：http://127.0.0.1/
支持二级目录 dolphinscheduler 后访问: http://127.0.0.1/dolphinscheduler/

**Comment by break60** [comment]
+1

**Comment by phoenixhadoop** [comment]
Now , Dolphinscheduler-1.2.1 has support for secondary directory access to the vue.
Thanks a lot.

**Comment by chengshiwen** [comment]
Close the issue since it has been resolved
