### ISSUE TITLE
[BUG] dolphinscheduler compile failed

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#1456]
**Problem description:**

Now I have a problem. I have cloned the latest code from GitHub, but when I compile it, I fail to compile it.

**Compile command:**

```shell
mvn -U clean package -Prelease -Dmaven.test.skip=true
```

**The following is the compile error information:**

![image](https://user-images.githubusercontent.com/29206593/70683494-88ff3c00-1cdd-11ea-876e-0727e487d067.png)

**Current version:**

`1.2.0 dev branch`

**Compiling environment:**

`MacOS 10.15.2`

**Expected results:**

Hope to be able to compile successfully in any environment and run it successfully.

**Comment by lenboo** [comment]
please cat README.md, there would be 'how to build'.

**Comment by sunnerrr** [comment]
need .proto file compile java class，idea have relate plugin

**Comment by wuchunfu** [comment]
I changed the compile command to `mvn clean install -Prelease`  Still failed to compile

![image](https://user-images.githubusercontent.com/29206593/70693427-69294180-1cf8-11ea-9fd3-21358f6aabb3.png)

**Comment by qiaozhanwei** [comment]
Current version:
1.2.0 dev branch ? dev or  1.2.0 branch ?

I compile dev，1.2.0 branch and incoming apache release 1.2.0 no problem

**Comment by wuchunfu** [comment]
The current branch is `dev`

I can't import `maven` dependency with `IntelliJ IDEA` tool and report the error of `Cannot resolve io.grpc:grpc-core:1.9.0`
