### ISSUE TITLE
[BUG] maven config problem and database driver is not found

### ISSUE THREAD

**Issue by wenhemin** [apache/incubator-dolphinscheduler#1458]
1.2.0-release版本：

1.项目根目录maven配置文件
```
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
	<version>${mysql.connector.version}</version>
	<scope>test<scope>
</dependency>
```

需要移除scope[test]属性，否则，编译时不会加载mysql驱动，系统使用mysql库时，报错驱动类找不到

2.官方部署文档增加描述
准备一: 基础软件安装(必装项请自行安装)
PostgreSQL (8.2.15+) or Mysql (5.5+) : 两者任选其一即可
系统默认依赖PostgreSQL驱动，使用Mysql时，需要修改application-dao.properties和quzrtz.properties配置文件，参数改为加载Mysql驱动

**Comment by lenboo** [comment]
Dolphinscheduler supports postgre sql in 1.2.0. 
If you need mysql, please modify the source follow this issue.

**Comment by wenhemin** [comment]
I think this is a bug. if the database uses postgreSql, The system dose not load mysql driver jar package, when the sqlTask job executes mysql statement, the system will report an error, mysql driver is not found.

**Comment by lenboo** [comment]
yes, that would report an error if you have not mysql connection jar in the lib, also oracle/db2... etc..
but this is not an bug. the system offers a default solution with postgre, because of license problem, we cannot put the mysql/db2/oracle jar into the lib.

**Comment by wenhemin** [comment]
oh! I understand, thank you. It is recommended to add this description the backend deployment documentation. trouble again look at this PR #1457 . related to this.
