### ISSUE TITLE
[CI/CD]Root issue to track

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1460]
This is a root issue for CI/CD, if you want to learn about the detail, you can track the email link https://lists.apache.org/thread.html/00dffebaf5f62672cc0d67ffc8317bb531f66f14dcb8decf913cbbb8%40%3Cdev.dolphinscheduler.apache.org%3E

So far, no one has objected to the UT coverage rate, so we will implement it according to the 60% UT coverage rate. 
When pmc or committer merge pr, pay attention to the codecov comments. We must ensure that the UT coverage rate 
of the submitted PR files reach 60%, and it is guaranteed that the UT coverage rate will only increase after the PR is merged.

   And this is a root issue for track the ci/cd process.

  I will break it into many scattered issues for everyone to contribute under the root issue:
* ut
* checkstyle check
* spotbugs check
* Front-end eslint check
* The CI / CD inspection and requirements are written into the code contribution document, 
   		the new PR code ut coverage is required to reach 60%, and the coverage can only be increased, not reduced. 
* We use codecov tool to replace coveralls tool in fact, and this job is done.

**Comment by dailidong** [comment]
thanks  khadgarmage do this.  welcome everyone who interesting in please join us

**Comment by CalvinKirs** [comment]
done
