### ISSUE TITLE
[CI/CD]Add checkstyle check

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1461]
follow the root issue: #1460 
Steps:
1、chose the checkstyle guidline,  google or alibaba
2、modify files which not satisfy the guildline，and pay attention not to submit too much files each time in a pr, it is better not to exceed 10, which is convenient for review, and can be split into multiple pr to submit, and the pr which you submit should follow this issue (e.g. #1461).
3、Add to github action to execute this check in ".github" directory, and we must ensure that CI / CD is successfully rebuilt, you can put the files which you modified into the maven pom.xml whitelist, to ensure the rebuilt successfully.

**Comment by nauu** [comment]
Let's start.

**Comment by nauu** [comment]
Which rule to use ? @khadgarmage

**Comment by khadgarmage** [comment]
@nauu if you what to implement it, you can start a vote ^_^

**Comment by nauu** [comment]
+1

**Comment by khadgarmage** [comment]
> +1

oh, sorry, i find @lamber-ken had start to this job some days ago, you can chose other issue? ^_^

**Comment by khadgarmage** [comment]
@lamber-ken hi, ppmc suggest we should use alibaba checkstyle.

**Comment by CalvinKirs** [comment]
done
