### ISSUE TITLE
[CI/CD]Write notes about ci/cd in contributing documentation

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1464]
follow the root issue: #1460
Content:
* The new PR code ut coverage is required to reach 60%
* The the coverage rate after merge PR can only be increased, not reduced
* UT only use junit and mockito, we worried about license issues after other library is introduced
* Before submitting the PR, you must ensure that the build passes, the ut passes, the license check、spotbugs check、checkstyle check、and eslint check all pass.

**Comment by CalvinKirs** [comment]
done
