### ISSUE TITLE
[CI/CD]Add unit test

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1465]
follow the root issue: #1460
Notice:
* The ut coverage is required to reach 60%
* UT only use junit and mockito, we worried about license issues after other library is introduced
* UT cannot include performance testing operations, blocking operations (time-consuming), and cannot rely on third-party libs. If you want to rely on testing, you can use mockito to mock.

The directory listing which will write ut is as following(if you want to contribute, you may reply "java.org.apache.dolphinscheduler.api.utils,  i want to  implement it, avoid everyone writing UT repeatedly):

```
├── java
│   └── org
│       └── apache
│           └── dolphinscheduler
│               └── api
│                   ├── ApiApplicationServer.java
│                   ├── CombinedApplicationServer.java
│                   ├── configuration
│                   ├── controller
│                   ├── dto
│                   ├── enums
│                   ├── interceptor
│                   ├── log
│                   ├── service
│                   └── utils

├── java
│   └── org
│       └── apache
│           └── dolphinscheduler
│               └── common
│                   ├── Constants.java
│                   ├── IStoppable.java
│                   ├── enums
│                   ├── graph
│                   ├── job
│                   ├── model
│                   ├── process
│                   ├── queue
│                   ├── shell
│                   ├── task
│                   ├── thread
│                   ├── utils
│                   └── zk

├── java
│   └── org
│       └── apache
│           └── dolphinscheduler
│               └── alert
│                   ├── AlertServer.java
│                   ├── manager
│                   ├── runner
│                   └── utils
```
If you had finished the ut, you should modify the pom.xml file, and add the include files like this:
```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven-surefire-plugin.version}</version>
				<configuration>
					<includes>
						<include>**/common/graph/*.java</include><!--run test classes-->
					</includes>
					<!-- <skip>true</skip> -->
				</configuration>
			</plugin>
```

--------
Note: Now,  ci has support db, if you develop mapper/dao ut, you can use it, and it had config in dolphinscheduler-dao/src/main/resources/application-dao.properties

**Comment by xingchun-chen** [comment]
I want to implement  java.org.apache.dolphinscheduler.api.controller

**Comment by khadgarmage** [comment]
i want to imeplement java.org.apache.dolphinscheduler.common.graph

**Comment by khadgarmage** [comment]
I want to imeplement java.org.apache.dolphinscheduler.common.utils

**Comment by clay4444** [comment]
I want to imeplement java.org.apache.dolphinscheduler.common.zk

**Comment by amorynan** [comment]
I want to implement java.org.apache.dolphinscheduler.common.thread

**Comment by nauu** [comment]
I want to implement  org.apache.dolphinscheduler.api.utils

**Comment by samz406** [comment]
I want to implement java.org.apache.dolphinscheduler.common.queue

**Comment by nauu** [comment]
I want to implement org.apache.dolphinscheduler.common.shell

**Comment by nauu** [comment]
I found there is a shell UT in "implement org.apache.dolphinscheduler.common.shell".

So I'd  like to implement org.apache.dolphinscheduler.alert.utils

**Comment by samz406** [comment]
I want  to implements 
org.apache.dolphinscheduler.api.service.SessionService
org.apache.dolphinscheduler.api.service.UsersService
org.apache.dolphinscheduler.api.service.TenantService
org.apache.dolphinscheduler.api.service.WorkerGroupService
org.apache.dolphinscheduler.api.service.UdfFuncService
org.apache.dolphinscheduler.api.service.AlertGroupService
org.apache.dolphinscheduler.api.service.ProjectService

**Comment by nauu** [comment]
I want to implement org.apache.dolphinscheduler.server.utils

**Comment by elonlo** [comment]
java.org.apache.dolphinscheduler.api.interceptor, i want to implement it

**Comment by elonlo** [comment]
I want to implement org.apache.dolphinscheduler.api.enums

**Comment by samz406** [comment]
and I want to implements
org.apache.dolphinscheduler.api.service.AccessTokenService
org.apache.dolphinscheduler.api.service.QueueService
org.apache.dolphinscheduler.api.service.MonitorService

**Comment by qiaozhanwei** [comment]
AlertMappert UT modify #1616

**Comment by qiaozhanwei** [comment]
CommandMapperTest UT modify #1625

**Comment by qiaozhanwei** [comment]
DataSourceMapperTest UT modify  #1642

**Comment by samz406** [comment]
I want to implements org.apache.dolphinscheduler.api.service.ResourcesService

**Comment by samz406** [comment]
and I want to implements org.apache.dolphinscheduler.api.service.BaseService

**Comment by samz406** [comment]
and I want to implements org.apache.dolphinscheduler.api.service.BaseDAGService

**Comment by samz406** [comment]
and I want to implements org.apache.dolphinscheduler.api.service.LoggerService

**Comment by samz406** [comment]
and I want to implements org.apache.dolphinscheduler.api.service.DataAnalysisService

**Comment by CalvinKirs** [comment]
done
