### ISSUE TITLE
there still have 31 tasks need to be executed

### ISSUE THREAD

**Issue by amenhub** [apache/incubator-dolphinscheduler#1466]
eschduler-worker.log日志中反复出现：
"consume tasks: [2_242208_2_283745_-1, 2_242209_2_283746_-1, 2_242210_2_283747_-1],there still have 31 tasks need to be executed"，请问需要怎么解决掉之前的31个task，或者通过其他解决办法？还请大佬赐教一下~

**Comment by lenboo** [comment]
you can find the these tasks in the zookeeper: "/dolphinscheduler/tasks_queue", you can remove them 
 when checking these are useless.

**Comment by amenhub** [comment]
> you can find the these tasks in the zookeeper: "/dolphinscheduler/tasks_queue", you can remove them
> when checking these are useless.

thankkks!
