### ISSUE TITLE
[Feature] Develops an Ambari plugin about DS

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#1469]
Many companies now use ambari to manage their big data clusters，A ambari plugin about DolpinScheduler  can be directly integrated into their amabri, and the plugin will automatically get the service address and configuration information of zk, hdfs, hive, spark ... in the cluster, and automatically generate the configuration files required by DolpinScheduler . On Ambari, we can visually manage DS configuration parameters, and start, stop, upgrade DS services, etc

1、To develop an ambari plugin, DolpinScheduler needs to support installation as an rpm package and this can be achieved through rpm-maven-plugin
2、Develop an ambari plugin according to the ambari official documentation and interface
     https://cwiki.apache.org/confluence/display/AMBARI/Defining+a+Custom+Service

to do list:

- [x] Update DolpinScheduler pom add rpm-maven-plugin

- [x] Develop an ambari plugin according to the ambari official documentation and interface
     https://cwiki.apache.org/confluence/display/AMBARI/Defining+a+Custom+Service

**Comment by gaojun2048** [comment]
I will do my first task and plan to complete it on December 16, 2019

**Comment by githubzhangchunyang** [comment]
I will do the second task--the ambari plugin of DS.
It will be finished before 2020/01/01, i think
