### ISSUE TITLE
创建工作流中编辑dag图中建议：是否考虑在dag图中增加回退按钮？

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#1473]
创建工作流中编辑dag图中建议：

1. 是否考虑在dag图中增加回退按钮，避免误操作的时候删除多了，导致使用不便。
2.是否考虑支持增加复制已经开发完的Shell节点，避免来回新增节点，在复制的节点上进行修改操作。

**Comment by dailidong** [comment]
good idea， but English is needed
