### ISSUE TITLE
[Feature]每次发布之后，能不能提供下前后端的编译包？

### ISSUE THREAD

**Issue by pengcheng4451** [apache/incubator-dolphinscheduler#1475]
window用户无法编译的包不正常，不知道是什么问题，希望能类似1.1.0，提供编译后的包。1.2.0的打包以后的版本也提供下啊，谢谢

**Comment by dailidong** [comment]
please subscribe https://dolphinscheduler.apache.org/zh-cn/docs/user_doc/subscribe.html， when released , the mail will have the binary version

By the way, English is needed.

**Comment by pengcheng4451** [comment]
Thanks,but I think you should offer binary package when new version relealse,like 1.1.0 on github.
