### ISSUE TITLE
dolphinscheduler version:1.2.0,start API in idea，Invalid server.port specified in application-dao.properties file,The startup log is as follows:

### ISSUE THREAD

**Issue by zhangdehai** [apache/incubator-dolphinscheduler#1476]
dolphinscheduler version:1.2.0,start API in idea，Invalid server.port specified in application-dao.properties file,The startup log is as follows:
![图片](https://user-images.githubusercontent.com/36880444/70777345-70188880-1dba-11ea-8c70-41ac6d96c873.png)
![图片](https://user-images.githubusercontent.com/36880444/70777371-87f00c80-1dba-11ea-9e25-cd2d91b07cac.png)

please help,thinks a lot

**Comment by zhangdehai** [comment]
application-dao.properties define as follow:**server.port=12345**

**Comment by zhangdehai** [comment]
If specified in the parameter 
![图片](https://user-images.githubusercontent.com/36880444/70778295-f03fed80-1dbc-11ea-86db-9649ad3b683e.png)
idea log console no log output,crazy.....
![图片](https://user-images.githubusercontent.com/36880444/70778415-31d09880-1dbd-11ea-9530-b79fa50d1ab9.png)

**Comment by amorynan** [comment]
could I look for ur java environment options ?

**Comment by zhangdehai** [comment]
![图片](https://user-images.githubusercontent.com/36880444/70873478-0500c900-1fe9-11ea-8720-2526731c4b3b.png)

![图片](https://user-images.githubusercontent.com/36880444/70873486-12b64e80-1fe9-11ea-8f1a-03a66fd81b5e.png)

**Comment by hhy8545259** [comment]
I have the same problem. You can do like this .

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/20966345/71094293-b3715d80-21e5-11ea-9c83-e3876860a777.png">

**Comment by lenboo** [comment]
> If specified in the parameter
> ![图片](https://user-images.githubusercontent.com/36880444/70778295-f03fed80-1dbc-11ea-86db-9649ad3b683e.png)
> idea log console no log output,crazy.....
> ![图片](https://user-images.githubusercontent.com/36880444/70778415-31d09880-1dbd-11ea-9530-b79fa50d1ab9.png)


There is not any erorrs in this image, the api server start successfully.
Because of the setting 'apiserver_logback.xml' ,there is no log displayed. you can add appender-ref "STDOUT" at the end of the logback xml.

**Comment by zhangdehai** [comment]
hi, hhy8545259  thank you very much!!

**Comment by zhangdehai** [comment]
very very
