### ISSUE TITLE
[Feature] Improve backend deployment documentation

### ISSUE THREAD

**Issue by wenhemin** [apache/incubator-dolphinscheduler#1478]
我在1.1.0升级到1.2.0版本过程中遇到如下问题，估计其他同学也会遇到，希望能完善下部署文档

1.quartz.properties文件中的instanceName参数要和1.1.0配置一致，否则quartz会创建新实例，之前版本创建的工作流都不会被调度

2.需要更新QRTZ_JOB_DETAILS表数据的JOB_CLASS_NAME字段，更新为
`org.apache.dolphinscheduler.server.quartz.ProcessScheduleJob`
因为1.1.0版本任务类是
`cn.escheduler.server.quartz.ProcessScheduleJob`

3.nginx配置文件，api-server的应用访问路径做了如下修改
`location /escheduler`
修改为
`location /dolphinscheduler`

**Comment by dailidong** [comment]
@lgcareer , please recheck

**Comment by xwhfcenter** [comment]
I reinstall the new version dolphinscheduler, without upgrading from the old. And define a new process definition and it occurs MasterSchedulerThread Blocked and the instance can not be built. 
It's different from this issue.

**Comment by lgcareer** [comment]
Now it will do the setp above when sh upgrade-dolphinscheduler.sh,so it will don't change by youself.
