### ISSUE TITLE
[BUG] The method checkEmail do not have null check

### ISSUE THREAD

**Issue by nauu** [apache/incubator-dolphinscheduler#1480]
**Describe the bug**

The method checkEmail do not have null check

When the email is empty , it wll be nullpointexception.

**To Reproduce**

goto org/apache/dolphinscheduler/api/utils/CheckUtils.java

The method checkEmail

**Expected behavior**

Include  null check

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by nauu** [comment]
I will pull a request later to fix this bug.

**Comment by dailidong** [comment]
very good!

**Comment by nauu** [comment]
This bug has been fixed.
