### ISSUE TITLE
question about the data complement

### ISSUE THREAD

**Issue by gggyd123** [apache/incubator-dolphinscheduler#1498]
1.2.0版本

并发补数时支持设置并行度吗？没有找到入口

**Comment by dailidong** [comment]
English is needed

**Comment by gggyd123** [comment]
when I complement the data,could I set the parallelism? The entry could not be found.

**Comment by dailidong** [comment]
for now,  complement data only support day task.
![image](https://user-images.githubusercontent.com/15833811/70999406-548fe380-2114-11ea-9a28-04353a68ecf2.png)

**Comment by dailidong** [comment]
if you choose Parallel execution,  if have 10 days tasks to execute,  system will start 10 tasks parallelly at the same time

**Comment by gggyd123** [comment]
I suggest that when I choose parallel execution,I can set the tasks parallelly at the same time. I don't know if that makes sense
