### ISSUE TITLE
when i specify a date range in 12/15-12/16 on complement data, the system defaults added 12/16-12/17 date range datas??

### ISSUE THREAD

**Issue by amenhub** [apache/incubator-dolphinscheduler#1510]
![image](https://user-images.githubusercontent.com/35909818/71060906-be0a0380-21a1-11ea-8fe6-101f6cd0f403.png)

can anyone help me？

**Comment by lenboo** [comment]
this is the process now. 
normally, we run the process on 12/16 to etl the data 12/15.
you select 12/15 in complement data, the default process date would be 12/16.
