### ISSUE TITLE
[Feature] task process page improve

### ISSUE THREAD

**Issue by amorynan** [apache/incubator-dolphinscheduler#1524]
when I was almost done editing a flink task process,but without click the confirm button, then click another space in this page accidentally, then the params I edited all gone ... thats the so sad for me to edit it again and again  

I want the task process param would be story temporary , at least I can do the same work again before I click the confirm button 

do not let the side page in the task editing page disper so easily...

**Comment by nauu** [comment]
I think I can improve it

**Comment by break60** [comment]
dev branch and 1.2.0-release have fixed this problem

**Comment by nauu** [comment]
@break60 which pr fixed this problem ?  could you tell me the pr number. 
I want to confirm whether it is duplicated.

Because I have some new features to this case, to cache the previous input.

**Comment by nauu** [comment]
All tasks have been done and this issue should be close.
