### ISSUE TITLE
[BUG] version 1.2 "/tmp/dolphinscheduler/" 目录权限问题 directory permission

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#1526]
从1.1版本升级到1.2版本之后，作业无法执行，从dolphinscheduler-worker.log日志中看到错误信息如下：”Unable to create directory /tmp/dolphinscheduler/exec/process/1/14/1875/7851“
After upgrading from version 1.1 to version 1.2, the job cannot be executed, the error message from the file 'dolphinscheduler-worker.log'  :”Unable to create directory /tmp/dolphinscheduler/exec/process/1/14/1875/7851“

修改目录权限为777之后作业能执行，但是产生的文件属主是dolphinscheduler，不是root
The job can be executed when the directory permission is changed to 777, but the file owner is dolphinscheduler, not root

说明文件是由dolphinscheduler用户直接生成的，不是sudo生成
This indicates that the file was generated by the dolphinscheduler user, not by sudo

这与1.1版本不一致，请问这否是个bug？
This is not consistent with version 1.1. Is this a bug?

**Comment by lenboo** [comment]
do you use the different user to install dolphinscheduler?
you can change the folder/group to the new creator using chown

**Comment by glxfeng** [comment]
我用dolphinscheduler用户安装了ds，不是用root用户。
I use user dolphinscheduler to  install ds.

修改/tmp/dolphinscheduler的属主或者权限都能防止这个错误
Modify /tmp/dolphinscheduler's owner or authority prevents this error

但我想知道的是，在1.1版本是通过sudo生成缓存文件，1.2版本是通过安装用户自己，这是版本做了修改还是一个bug？
But what I want to know is that ，the cache file was generated by sudo in version 1.1  and in version 1.2 by the user installed himself. Is this a revision of the release or a bug?

**Comment by dailidong** [comment]
a revision of the release
