### ISSUE TITLE
The workflow import user's other project or other user's project, the database table t_ds_process_definition stores data incorrectly

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1544]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

1. After the user successfully imported the workflow of user’s  project B  in project A, t_ds_process_definition.project_id is still project B, and project_id should be the project ID of project A
2. The workflow of importing other users prompts success, but the data is not stored in the database table t_ds_process_definition 

1.用户在A项目导入该用户B项目的工作流成功后，t_ds_process_definition.project_id仍为B项目的id，project_id应该为A项目的id
2.导入其他用户的工作流提示成功，但是数据未存入数据库

**version**
[1.2.0]

**Comment by Yeleights** [comment]
Current workflow import:
1 Implementing workflow import under the same project, currently more like a workflow metadata backup mechanism
2 If multi-environment publishing is required, the metadata of users, tenants, etc. in the two environments is completely consistent
Idea:
1 First implement a cross-project workflow import in a DS environment(want to do)
2 Priority recommendations for multi-environment releases come after the dolphinscheduler resource directory and platform permissions design
当前工作流导入的特点：
1 实现同一项目下的工作流导入，目前更像是一种工作流元数据备份机制
2 如果要实现多环境发布，目前需要两个环境的用户，租户等等元数据名称一致
个人想法：
1 先实现一套DS环境中的，跨项目的工作流导入(可以做)
2 多环境发布的优先级建议排在dolphinscheduler资源目录和平台权限设计之后

**Comment by dailidong** [comment]
good, 
I agree with your idea.  first implement a cross-project workflow import in a DS environment.

**Comment by qiaozhanwei** [comment]
+1
