### ISSUE TITLE
[Feature] node text edit box supports full-screen magnification(节点文本编辑框支持全屏放大)

### ISSUE THREAD

**Issue by elonlo** [apache/incubator-dolphinscheduler#1547]
**Is your feature request related to a problem? Please describe.**
The node text edit box supports full-screen magnification, which is better for long text writing experience.
节点文本编辑框支持全屏放大，这样对于长文本编写体验更好

**Additional context**
![image](https://user-images.githubusercontent.com/5669148/71398585-d8d5ef80-265b-11ea-89fd-1f800552551b.png)

**Comment by xingchun-chen** [comment]
Thank you for your suggestion. For long texts, you can edit the files in the Resource Center-> File Management page. You can reference the resource files in the script

**Comment by elonlo** [comment]
Yes, this is one way. But there are many times when development is to write SQL or text directly in the node text edit box. In this case, can we make the user experience better?

**Comment by xingchun-chen** [comment]
Yes, the experience can indeed be optimized，thank you very much

**Comment by chengshiwen** [comment]
Close by #1604
