### ISSUE TITLE
  Supplementary data shall be executed according to the interval(补数据按区间执行）

### ISSUE THREAD

**Issue by modehuan** [apache/incubator-dolphinscheduler#1550]
在系统初始化数据时，针对一些大的流水表数据不需要按日增量的方式跑数，几年的数据，按天的补数太慢了．做成按时间段跑数据可以有效解决这个问题．比如按年　按月　按周　或者自定义区间的每隔多少天执行一次．
例：定义补数区间从20160101－当前时间，每隔一年(或者一个月)时间跑一次任务．那就会在20170101跑一次前一年(20160101-20170101)数据．在20180101跑一次前一年(20170101-20180101)数据．一直跑到最新日期．．补完历史所有数据．

When the system initializes the data, it is not necessary to run the data in the way of daily increment for some large flow chart data. For the data of several years, it is too slow to supplement the data by day. Running the data by time period can effectively solve this problem. For example, running the data by year, month, week or every other day in the custom interval

For example: define the replenishment interval from 20160101 to the current time, and run the task every other year (or month). That will run the data one year before 20170101 (20160101-20170101). Run the data one year before 20180101 (20170101-20180101). Run to the latest date... Complete all the historical data

**Comment by xingchun-chen** [comment]
Please add the title in English, thanks

**Comment by lfyee** [comment]
i will fix it
