### ISSUE TITLE
[QUESTION] question title

### ISSUE THREAD

**Issue by huzhengfei001** [apache/incubator-dolphinscheduler#1553]
1. Whether the workflow of HTTP interface is supported now           
 2. The "groups" name does not exist when debugging the workserver. Do you support windows

**Comment by dailidong** [comment]
1、a little confuse. do you mean DS support Http task?     

2、groups means what？where use or you can provide a screenshot.

for now , not support windows

**Comment by huzhengfei001** [comment]
1，
![image](https://user-images.githubusercontent.com/59187408/71452069-c672c780-27bb-11ea-8bf6-6a2c0b0a808e.png)can or not support!!
2,worker server is only support on linux

**Comment by huzhengfei001** [comment]
1,&nbsp;

can or not supprot?
2,worker and master server is only can support in linux server?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dailidong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 晚上6:21
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"快乐的自己"<345591572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] [QUESTION] question title (#1553)




1、a little confuse. do you mean DS support Http task?
 
2、groups means what？where use or you can provide a screenshot.
 
for now , not support windows

**Comment by dailidong** [comment]
1， http task has been supported in version 1.2.0
2， for now worker server not suppoort windows  ， master server can run on windows
