### ISSUE TITLE
[CI/CD]Support docker compose and deploy the docker on github action

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1560]
Track the root issue #1460 
* Support docker compose, split into several different services, refer to: https://github.com/apache/skywalking/tree/master/docker
* Deploy the servers on github action and check service availability, refer to:
https://github.com/apache/skywalking/blob/master/.github/workflows/docker-ci.yaml

if you want to contribute, you may reply  "i want to implement it"

**Comment by kezhenxu94** [comment]
Need any help?

**Comment by khadgarmage** [comment]
@kezhenxu94 this task is on going
