### ISSUE TITLE
[enhancement] unsaved tasks disappear

### ISSUE THREAD

**Issue by minghai1984** [apache/incubator-dolphinscheduler#1571]
In workflow page design, several tasks dragged in are not saved. Another task is dragged in and the mouse is dragging for a while. All the unsaved tasks disappear

工作流页面设计时,拖进去几个任务都没有保存,再拖一个进去鼠标拖动着晃一晃,没保存的就全部消失了

**Comment by dailidong** [comment]
good idea

**Comment by break60** [comment]
This will not happen in the dev branch.
