### ISSUE TITLE
[QUESTION] Why reuse the version number of 1.2.0 ?

### ISSUE THREAD

**Issue by minghai1984** [apache/incubator-dolphinscheduler#1572]
Why the release does not use the new version number, and has been reusing the version number of 1.2.0, which leads to confusion and trouble in tracking code.

为啥release不用新版本号，一直复用1.2.0这个版本号，导致跟踪代码很困惑和麻烦。

**Comment by dailidong** [comment]
1.2.0 has not yet been officially released, it's being in the state of release.  for now, Currently, 1.2.0 mainly changes the front-end code.
