### ISSUE TITLE
[CI/CD]Checking the dependency licenses

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#1578]
Track the root issue #1460 
Apache has strict requirements for license, so ci needs to verify license, you can refer to skywalking or other apache dependence license check flow.

skywalking link: https://github.com/apache/skywalking/blob/master/tools/dependencies/check-LICENSE.sh
if you want to contribute, you may reply "i want to implement it"

**Comment by dailidong** [comment]
who want to contribute this feature？ please reply，thanks.

**Comment by kezhenxu94** [comment]
I'm the author of the script https://github.com/apache/skywalking/blob/master/tools/dependencies/check-LICENSE.sh, need my help to port the SkyWalking script to this project?

**Comment by khadgarmage** [comment]
@kezhenxu94 yes,  thanks for your help~~
