### ISSUE TITLE
[BUG] The method getserverlistfromzk of zookeepermonitor in monitorservice cannot be re instantiated, otherwise there is a problem in getting ZK connection

### ISSUE THREAD

**Issue by zhangguolihen** [apache/incubator-dolphinscheduler#1584]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The method getserverlistfromzk of zookeepermonitor in monitorservice cannot be re instantiated, otherwise there is a problem in getting ZK connection

**Expected behavior**
  

**Which version of Dolphin Scheduler:**
 -[1.2.1-SNAPSHOT-dev]

**Additional context**
Server monitoring is not available

**Requirement or improvement
public List<Server> getServerListFromZK(boolean isMaster){
    List<Server> servers = new ArrayList<>();
    try{
      ZKNodeType zkNodeType = isMaster ? ZKNodeType.MASTER : ZKNodeType.WORKER;
      servers = zookeeperMonitor.getServersList(zkNodeType);
    }catch (Exception e){
      throw e;
    }
    return servers;
  }

**Comment by lenboo** [comment]
already fixed
