### ISSUE TITLE
can you add Scheduled Flows to ds

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#1589]
我就觉得 一个工作流 新增一个，然后简单改了改，每次你都需要去从新设置定时时间，并且只有在定时管理那点击上线才行。这样不直观，
能否参照azkaban那样做个Scheduled Flows ，我这样可以知道工作流下次执行时间；
<img width="949" alt="微信图片_20191225150830" src="https://user-images.githubusercontent.com/37201886/71471665-3b212280-280b-11ea-95b8-0b26c18b6600.png">

**Comment by break60** [comment]
The expansion you showed in this picture, did not understand how you want to design this time
