### ISSUE TITLE
[BUG] process instance alert optimization

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/incubator-dolphinscheduler#1595]
Alert title words crowded together, for example ‘start processsuccess’，should be ‘start process success’；
The lowercase letters should be unified in the alert content (the original key is capitalized)。

**Comment by JinyLeeChina** [comment]
I'm fixed it

**Comment by JinyLeeChina** [comment]
I have fixed it

**Comment by Technoboy-** [comment]
#1608
