### ISSUE TITLE
Scheduled tasks start two tasks at the same time（同一时间启动了两个任务实例）

### ISSUE THREAD

**Issue by 865357384** [apache/incubator-dolphinscheduler#1601]
**Describe the bug**
      Scheduled tasks start two tasks at the same time
Instance definition：
    
![image](https://user-images.githubusercontent.com/24928399/71505762-6b26ff00-28b9-11ea-8965-da6f550daaf9.png)

![image](https://user-images.githubusercontent.com/24928399/71505784-7c700b80-28b9-11ea-9144-4bf2ab6492d1.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/24928399/71505827-a6c1c900-28b9-11ea-9eb9-9af248f4320f.png)

**Which version of Dolphin Scheduler:**
 -[1.1.0]

**Comment by break60** [comment]
![image](https://user-images.githubusercontent.com/28628088/71569682-c8b28a00-2b0b-11ea-839d-60d36632495b.png)
At the 10th minute, Operate the on-line button twice by mistake?

**Comment by wangchangliang1008** [comment]
Hi,has this problem been solved?

**Comment by break60** [comment]
I haven't seen this problem again. Do you still have this problem when you run the task now?

**Comment by wangchangliang1008** [comment]
yes
