### ISSUE TITLE
[Feature] merge configurations 

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#1635]
we have too many configurations in the project.some of them can be merge into one.
ex:application-api.properties/application-combined.properties, I think  the project looks more concise if can merge some configuration files.

here some suggestions:

common/common.properties + common/hadoop/hadoop.properties + zookeeper.properties = common.properties
application-api.properties+application-combined.properties = application-api.properties
remove application-master.properties /application-worker.properties
rename application-dao.properties to application.properties

**Comment by dailidong** [comment]
+1
