### ISSUE TITLE
commit successfully and cannot continue

### ISSUE THREAD

**Issue by gggyd123** [apache/incubator-dolphinscheduler#1640]
**Describe the bug**
Task remains submitted successfully and process instance cannot continue, and this problem only occasionally occurs

**To Reproduce**
Unable to reproduce stably

**Screenshots**

![运行情况](https://user-images.githubusercontent.com/11663381/71572420-f9012500-2b19-11ea-9ab7-2d9b43398fd7.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Requirement or improvement
By tracking the code, the possible problems are as follows:
![代码问题](https://user-images.githubusercontent.com/11663381/71572447-251ca600-2b1a-11ea-8f80-7f164e921281.png)

Add DB and the zk queue in the same transaction，the FetchTaskThread may not be able to get the task instance by task id

**Comment by lenboo** [comment]
same for  issue #1477 , already fixed in the dev.
