### ISSUE TITLE
定时任务时间开始小于当前编辑的时间时，定时任务将无法被执行

### ISSUE THREAD

**Issue by qinzl1** [apache/incubator-dolphinscheduler#1650]
当编辑定时任务的时间段时，QRTZ_TRIGGERS表中的NEXT_FIRE_TIME下一次执行时间等于编辑时的开始时间戳，所以当编辑完成上线时，如果编辑时的开始时间小于当前时间那么定时任务将无法被执行

**Comment by lgcareer** [comment]
I tried it on 1.2.0 and didn't find the problem described.

**Comment by dailidong** [comment]
please use English describe the issue, thanks
