### ISSUE TITLE
[BUG] project dependency failed

### ISSUE THREAD

**Issue by elonlo** [apache/incubator-dolphinscheduler#1652]
**Describe the bug**
Add dependency front-end error in project dependency node interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/5669148/71609922-3ff92400-2bc7-11ea-9129-d6c4856743db.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by Yeleights** [comment]
i will fix it
