### ISSUE TITLE
Refactor WorkerServer

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1658]
# Background
  WorkerServer executes task by scanning ZK and DB. When WorkerServer starts, it try to retrive the lock in zk, and then executes task by loading data from DB. This is not nice for distributing system, and the current implementation will result in delay executing task.

# Suggestion
  We wanna use tcp channel to refactor WorkerServer. 
 
# General Implementation Idea
 1. Using Netty for our tcp framework. 
 2. MasterServer keeps the current logic and when it picks a task, directly sends it to target worker using RoundRobin policy.
 3. WorkerServer will start up as predefined group and register itself to zk node.
 4. WorkerServer will start a tcp server listening port for executing task instead of scanning ZK and DB.
 5. Executing result will send back to the MasterServer node using the previous channel.
 

# General Failover Idea
  1. For WorkerServer, only it receives the task command and gives back the ack command to keep the task is acknowledged.
  2. If the WorkerServer executes the task normally, it will send back the result by the previous channel.
  3. If the WorkerServer died after receiving a task, MasterServer will use execution-timeout time to ping WorkerServer to detect liveness. If ping failed, try another worker node. In this case, task may execute more than once.
  4. If the MasterServer died after sending out the a task, WorkerServer will retry to rebuild the channel with N times to the original MasterServer. If failed after retry times, choose a new MasterServer to send back the result.  New MasterServer will analysis the task, decide the next process. (Stop or continue execute by instanceId/processId, or just update the status)

**Comment by Technoboy-** [comment]
If the suggestion takes into consideration, I will lead the job

**Comment by lenboo** [comment]
- MasterServer keeps the current logic and when it picks a task, directly sends it to target worker using RoundRobin policy.
what's the mean 'directly sends it to target worker using RoundRobin policy.'

- WorkerServer will start up as predefined group and register itself to zk node.
what's the ‘predefined group’



- WorkerServer will start a tcp server listening port for executing task instead of scanning ZK and DB.
- Executing result will send back to the MasterServer node using the previous channel

all of above process need stable communication network,  what should to do in unstable situation?

**Comment by dailidong** [comment]
> * MasterServer keeps the current logic and when it picks a task, directly sends it to target worker using RoundRobin policy.
>   what's the mean 'directly sends it to target worker using RoundRobin policy.'
RoundRobin's chinese name is "轮询"

> * WorkerServer will start up as predefined group and register itself to zk node.
>   what's the ‘predefined group’
I'm also curious，haha

> all of above process need stable communication network, what should to do in unstable situation?
netty can easily implement this

**Comment by dailidong** [comment]
> If the WorkerServer died after receiving a task, MasterServer will use execution-timeout time to ping WorkerServer to detect liveness. If ping failed, try another worker node. In this case, task may execute more than once.

I have a question about this, why not use zookeeper to monitor whether the worker alive or not ?  ping method seems old

**Comment by khadgarmage** [comment]
> > If the WorkerServer died after receiving a task, MasterServer will use execution-timeout time to ping WorkerServer to detect liveness. If ping failed, try another worker node. In this case, task may execute more than once.
> 
> I have a question about this, why not use zookeeper to monitor whether the worker alive or not ? ping method seems old

why not use zookeeper to monitor whether the worker alive or not ? +1

**Comment by khadgarmage** [comment]
> > > MasterServer keeps the current logic and when it picks a task, directly sends it to target worker using RoundRobin policy.

Whether or not to consider If the worker is out of memory or system resource?

**Comment by elonlo** [comment]
Regarding the third point of Failover, my consideration is this. When the MasterServer before assigning tasks to WorkerServer, the first step is to insert the task into the DB to generate an id, then send the task id to the WorkerServer for execution. 

It is assumed that the WorkerServer dies or the network overlaps after receiving the task, the MasterServer does not receive a task execution heartbeat from the WorkerServer within a certain period of time, it indicates that the task execution failed, and the MasterServer modifies the task status in the DB to a failed state.

After that, if the network recovers and receives the heartbeat of the task that has been marked as failed before, the MasterServer directly sends a task termination command to the WorkerServer.

If the user sets the number of retries, the task is retried in the MasterServer, and if not, an alert is send.

**Comment by Technoboy-** [comment]
> zookeeper

I said : WorkerServer starts up listening a port and registers itself to zk. So when MasterServer schedules a task , it can get the worker list .  But when MasterServer sends out a timeout with 5s task, and WorkerServer crashes after giving back acknowledge. In this case, we have to ping the workerServer after 5s, not relies on zk.
Let talk about ping :   Ping is a type msg with empty body in self defined binary protocol in most Rpc framework . Not ping command in OS system.

**Comment by Technoboy-** [comment]
> > > > MasterServer keeps the current logic and when it picks a task, directly sends it to target worker using RoundRobin policy.
> 
> Whether or not to consider If the worker is out of memory or system resource?

Yes, not in this phase. As tcp channel comes, some more functions should be taken into consideration.

**Comment by Technoboy-** [comment]
> Regarding the third point of Failover, my consideration is this. When the MasterServer before assigning tasks to WorkerServer, the first step is to insert the task into the DB to generate an id, then send the task id to the WorkerServer for execution.
> 
> It is assumed that the WorkerServer dies or the network overlaps after receiving the task, the MasterServer does not receive a task execution heartbeat from the WorkerServer within a certain period of time, it indicates that the task execution failed, and the MasterServer modifies the task status in the DB to a failed state.
> 
> After that, if the network recovers and receives the heartbeat of the task that has been marked as failed before, the MasterServer directly sends a task termination command to the WorkerServer.
> 
> If the user sets the number of retries, the task is retried in the MasterServer, and if not, an alert is send.

Yes, very good . we should do like what you said.
Task has many different status in scheduling system, we have to insert DB before scheduling.

**Comment by dailidong** [comment]
> > zookeeper
> 
> I said : WorkerServer starts up listening a port and registers itself to zk. So when MasterServer schedules a task , it can get the worker list . But when MasterServer sends out a timeout with 5s task, and WorkerServer crashes after giving back acknowledge. In this case, we have to ping the workerServer after 5s, not relies on zk.
> Let talk about ping : Ping is a type msg with empty body in self defined binary protocol in most Rpc framework . Not ping command in OS system.

I think zk can do this better,  if worker server down, zk can handle it immediately through listener/watch.   I assume you want to remove dependency about zk?

**Comment by qiaozhanwei** [comment]
+1

**Comment by dailidong** [comment]
what is “predefined group”？ and do you want to implement this predefined group in the first phase?

**Comment by dailidong** [comment]
+1

**Comment by qiaozhanwei** [comment]
![副本 架构图 (1)](https://user-images.githubusercontent.com/23756105/74330866-6ff23480-4dcd-11ea-9846-8a770f867f2e.png)

**Comment by dailidong** [comment]
I think this topic has been done, so I will close this issue
