### ISSUE TITLE
Incorrect URL for import workflow and view project list

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1671]
![image](https://user-images.githubusercontent.com/55787491/71649066-95a80a80-2d46-11ea-923e-045889c19852.png)
![image](https://user-images.githubusercontent.com/55787491/71649124-f0d9fd00-2d46-11ea-8872-ac87bccb9cd7.png)

**Comment by break60** [comment]
already fixed #1672
