### ISSUE TITLE
[Feature]Improve the user experience in the task definition page

### ISSUE THREAD

**Issue by nauu** [apache/incubator-dolphinscheduler#1675]
I’d like to improve the user experience in the task definition page. This idea is come from #1524, although this bug may have been fixed, I think it is still necessary to add a feature to cache previous input.

My plan is as follows:

	step 1,  I’ll create an issue to track the task, and split into multiple subtasks, such as flink、python and so on.
	step 2,  I’ll define the architecture (include actions.js, dag.vue,formModel.vue,mutations.js, and state.js) and implement one of the tasks , such as http.vue.
	step 3, Anyone who is interested in this, can reply to the issue and implement the rest of them, such as python.vue, Flink.vue and so on.

	The main ideas for doing this are as follows:

	1. Define a variable for cache in state.js, and also support the method in mutations.js and actions.js
	2. Watch the global input in formModel.vue, when the value changes cache them, when the from initial fillback the previous values.
	3. Implement each task form, just like http.vue,  python.vue and so on.  Define the cache params and watching theirs change

The subtasks as fllow:
- [x] architecture
- [x] http
- [x] flink
- [x] mr
- [x] python
- [x] shell
- [x] spark
- [x] sql
- [x] dependent
- [x] sub_process
- [x] procedure

**Comment by lenboo** [comment]
+1

**Comment by dailidong** [comment]
very good！

**Comment by nauu** [comment]
All subtasks have been done.
