### ISSUE TITLE
[suggest] The method getcurtaskparamsclass() of class abstracttask is the same as the function of class taskparametersutils  Functions can be replaced

### ISSUE THREAD

**Issue by zhangguolihen** [apache/incubator-dolphinscheduler#1682]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

The method getCurTaskParamsClass() of class AbstractTask  is the same as the function of class TaskParametersUtils Functions can be replaced

**To Reproduce**

**Expected behavior**

- Delete the method getcurtaskparamsclass() of class abstracttask

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.2.1-dev]

**Additional context**

**Requirement or improvement
Getcurtaskparamsclass() function of class abstracttask is replaced by taskparametersutils

**Comment by xingchun-chen** [comment]
@qiaozhanwei Please verify the issue

**Comment by CalvinKirs** [comment]
I have confirmed this problem. Who is interested in completing it?

**Comment by Tianqi-Dotes** [comment]
will do this
