### ISSUE TITLE
Refactor alert template

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1691]
Background
  Now, we use FreeMarker to load alert template, and only this simple function.

Suggestion
  Removing FreeMarker, use a template interface , and default implementation is concat string.  Anyone who want to extend , just implement the interface.

**Comment by qiaozhanwei** [comment]
+1，does not affect existing features

**Comment by Yeleights** [comment]
+1

**Comment by clay4444** [comment]
+1，i will implement this，
