### ISSUE TITLE
[BUG]delete processdefinition when a task aleady exec by worker lead to NPE

### ISSUE THREAD

**Issue by Yeleights** [apache/incubator-dolphinscheduler#1704]
**Describe the bug**
delete processdefinition when a task aleady exec by worker lead to NPE

**To Reproduce**
Steps to reproduce the behavior, for example:
1. a task aleady exec by worker
2. delete the task processdefinition 
3. get tenant will lead java.lang.NullPointerException

**Expected behavior**
deal with NPE

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by Yeleights** [comment]
i will fix it

**Comment by Technoboy-** [comment]
#1705
