### ISSUE TITLE
Remove swagger and springfox dependancy

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1710]
Background
  Api module rely on swagger and springfox jar to annotate api method. Not useful. 

Suggestion 
  Due to rely on many third party dependancies, and the licenses are hard to manage, so we decide to remove the two jars.

**Comment by Technoboy-** [comment]
@dailidong @qiaozhanwei

**Comment by qiaozhanwei** [comment]
swagger refer is resolve  api interface doc online，agree remove swagger ,because ui license mybe has problem . but api interface doc need find another method
