### ISSUE TITLE
[BUG] createProcessDefinition bug

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#1724]
version: 1.2.1
If different users create the same project, there will be problems.

According to the code, only the first project name will be obtained without considering the different users.

![image](https://user-images.githubusercontent.com/39816903/71797464-3a00b880-3089-11ea-9734-2c8e15b7130a.png)

![image](https://user-images.githubusercontent.com/39816903/71797595-d9be4680-3089-11ea-8036-3159208acfa3.png)

![image](https://user-images.githubusercontent.com/39816903/71797469-3f5e0300-3089-11ea-9747-d76a37955b54.png)

**Comment by Yeleights** [comment]
i will fix it
