### ISSUE TITLE
about metadata table documentation

### ISSUE THREAD

**Issue by mht-xyt** [apache/incubator-dolphinscheduler#1729]
Can you add a metadata table document for users to use, such as clean up instances, easy custom monitoring, and make migration clearer
Migrating instances, or migrating all tasks, and now copying the entire library is a mistake, and I'm trying it bit by bit.
It would be nice if there were documentation. I'm looking forward to it.

**Comment by dailidong** [comment]
good idea，thanks

**Comment by Yeleights** [comment]
+1, i will write this doc, 5days

**Comment by Yeleights** [comment]
add the metadata doc in ds-web
