### ISSUE TITLE
[BUG] Can't connect MySQL metadata databases

### ISSUE THREAD

**Issue by xwhfcenter** [apache/incubator-dolphinscheduler#1732]
java.sql.SQLException: Access denied for user 'dolphin'@'<ip>' (using password: YES)

I  have GRANT ALL ON dolphinscheduler.* TO dolphin@'%' IDENTIFIED BY '<password>';

but it cannot connect. If I change to user root, it can do it.

**Comment by liwenhe1993** [comment]
If it cannot connect, please try to use mysql-cli.

**Comment by xwhfcenter** [comment]
But the code use jdbc  to connect mysql

**Comment by liwenhe1993** [comment]
Please verify that the username and password are correct by mysql-cli.
Thanks.

**Comment by xwhfcenter** [comment]
I have fixed this problem. Because of my password of the database including a comma, then Spring boot read properties from application-dao.properties with wrong pass word. 
Maybe we should open the encryption function of Druid?

**Comment by paul-yangmy** [comment]
+1. I use v2.0.5. It also appears this problem by using $.
