### ISSUE TITLE
Refactor rpc module

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1738]
Background
  Rpc module is now using grpc for api module to show the execution log in WorkerServer .

Suggestion
  As we will refactor workerServer using Netty, a new remote module will be create and rpc module will be removed at the same time.
  And I think this should be ahead of refactor WorkerServer.

**Comment by Technoboy-** [comment]
I will lead the job, and as remote module being created,  some interested guys can participate in.

**Comment by qiaozhanwei** [comment]
+1

**Comment by liwenhe1993** [comment]
+1

**Comment by Yeleights** [comment]
+1

**Comment by dailidong** [comment]
this feature should be implemented already

**Comment by dailidong** [comment]
please give PR link next time
