### ISSUE TITLE
The SQL query node selects "no send", and the specified mailbox discovery is sent successfully.(SQL查询节点选择“都不发”，指定邮箱发现是发送成功的)

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/incubator-dolphinscheduler#174]

**Comment by lenboo** [comment]
![image](https://user-images.githubusercontent.com/29528966/56795880-f55b2700-6843-11e9-9681-3ce0575e460a.png)

![image](https://user-images.githubusercontent.com/29528966/56796215-a1047700-6844-11e9-8012-77969c1bd005.png)

The notification strategy here aims at whether to notify the process status and running information after the end of the process. This strategy can not control whether the SQL node sends mail or not. If you want to achieve the function of not sending mail, you can remove the "table / attachment" option, as shown.

**Comment by chengshiwen** [comment]
Close by #5104

We can choose whether to send mail in 1.3.6

![image](https://user-images.githubusercontent.com/4902714/114261404-efe55000-9a0c-11eb-9291-0f9bb2f987de.png)
