### ISSUE TITLE
Regularize Log print

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1740]
Background:
    Log print is not regular in all the DS module . like below :
  ```
  logger.error("start Quartz failed : " + e.getMessage(), e);
  ```

Suggestion:
  We should regularize the log print, using ”{}“ instead of ”+"  : 
  ```
  # 1 
  logger.error("start Quartz failed ", e); 
  # 2  
  logger.error("delete queue : {} fail", queueId); 
  # 3
   logger.error("complete task : {} with {} ms ", taskName, takesMS); 
  ```
We should split module or package as a group to correct the log print, like 👍 
  1. org.apache.dolphinscheduler.api.configuration
  2. org.apache.dolphinscheduler.api.controller
  pull request should only correct log without any modification.

**Comment by Yeleights** [comment]
+1 join~

**Comment by nauu** [comment]
+1
