### ISSUE TITLE
[Feature] ITaskQueue should have "hasTask" function

### ISSUE THREAD

**Issue by gabrywu** [apache/incubator-dolphinscheduler#1742]
# ITaskQueue should have "hasTask" function
## Background
In FetchTaskThread.run method ,using getAllTasks to determine if there is a task，why not using "hasTask"

## Solution

1、ITaskQueue add "boolean hasTask(String key)"  function
2、ZookeeperOperator add “public boolean hasChildren(final String key)” fuction

public boolean hasChildren(final String key){
        try {
            Stat stat = zkClient.checkExists().forPath(key);
            return stat.getNumChildren() >= 1;
        } catch (InterruptedException ex) {
            logger.error("hasChildren key : {} InterruptedException", key);
            throw new IllegalStateException(ex);
        } catch (Exception ex) {
            logger.error("hasChildren key : {}", key, ex);
            throw new RuntimeException(ex);
        }
 }

**Comment by qiaozhanwei** [comment]
+1
