### ISSUE TITLE
[Feature] why not invoke checkWorkerGroup in advance

### ISSUE THREAD

**Issue by gabrywu** [apache/incubator-dolphinscheduler#1743]
## Background
In FetchTaskThread.run method, checkWorkerGroup invoke after "queryUserQueueByProcessInstanceId", why not just after getTaskInstanceDetailByTaskId

if  checkWorkerGroup check failed  , the rest of the logic can be ignored

## Solution
checkWorkerGroup  invoked after getTaskInstanceDetailByTaskId

                    if (verifyTaskInstanceIsNull(taskInstance)) {
                        logger.warn("remove task queue : {} due to taskInstance is null", taskQueueStr);
                        removeNodeFromTaskQueue(taskQueueStr);
                        continue;
                    }

                    if(!checkWorkerGroup(taskInstance, OSUtils.getHost())){
                        continue;
                    }

**Comment by qiaozhanwei** [comment]
+1
