### ISSUE TITLE
Refactor module

### ISSUE THREAD

**Issue by Technoboy-** [apache/incubator-dolphinscheduler#1762]
Background
  Maven dependency in DS is not right, for API module relies on server module. 

Suggestion
  AS we have front module and backend module , some services are common. So we'd better add dolphinscheduler-service module for common services.
  And then we put queue/quartz/zookeeper services in the common module . api and service rely on it.

**Comment by Technoboy-** [comment]
@qiaozhanwei @dailidong

**Comment by qiaozhanwei** [comment]
+1

1，common module duty not single，contains tool classes and business logic .
so common module is only tool and service module is business logic. queue/quartz/zookeeper logic can put on service moudle
2，now It not necessary api server rely on dolphinscheduler-server moudle. for LoggerClient and quartz quote

1，common模块的职责不单一，其中包含了工具类和业务逻辑。所以common模块理论上应该就是去spring的工具类，service模块是处理业务逻辑的，比如说里面放定时逻辑，zk组件操作逻辑，LoggClient逻辑，等等。。。

2，现在dev分支上，api 模块是依赖 server模块的，这完全是没有必要的，但是由于引用了LoggerClient和定时的相关东西，所以得引用

**Comment by chengshiwen** [comment]
Close this issue since it has resolved in 1.3.x and dev
