### ISSUE TITLE
[dev_1.2.1] There are multiple pages of data. After deleting all the data on one page, the data is displayed as empty

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1768]
**Describe the bug**
![image](https://user-images.githubusercontent.com/55787491/71954811-6fd8a500-3221-11ea-8f35-0563fdc62f15.png)
User management has 2 pages of data. As shown in the figure above, after deleting the second page of data, the page shows no data. As shown in the figure below, the remaining 10 pieces of data should be displayed.

![image](https://user-images.githubusercontent.com/55787491/71954833-8252de80-3221-11ea-9830-ffe0d9640468.png)

All pages with pagination controls have this problem

**Which version of Dolphin Scheduler:**
 -[[dev_1.2.1]]

**Comment by break60** [comment]
+1

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/72065148-83b30280-3318-11ea-90d0-6725cc8af3fb.png)

When currentPage is greater than totalPage and the currentPage data is empty, the data of the previous page is returned, and currentPage is equal to totalPage


currentPage大于totalPage ，且currentPage数据为空时，返回上一页的数据即currentPage=totalPage

**Comment by break60** [comment]
The front end has been fixed accordingly, please back end to deal with this problem

**Comment by qiaozhanwei** [comment]
1. The backend try to modify, but there are too many changes, so it is recommended to modify the frontend.
2. After careful think, the backend modify seems a bit far-fetched. In theory, the backend does not care about the frontend business.

1，后端试着修改，但是修改的地方太多，所以建议前端修改
2，经过仔细考虑，后端修改貌似有点牵强，按道理来说，后端不会理会前端业务

@break60 @xingchun-chen

**Comment by xingchun-chen** [comment]
Frontend modified
