### ISSUE TITLE
[dev_1.2.1] View log error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1773]
![image](https://user-images.githubusercontent.com/55787491/71959948-d7e1b800-322e-11ea-8709-cf2939bd0262.png)
Log information exists in /data1/dolphinscheduler/logs/104/17139/22695.log

**Comment by qiaozhanwei** [comment]
you can see whether 22695 task instance host is null

**Comment by xingchun-chen** [comment]
Caused by abnormal startup of logger-server
