### ISSUE TITLE
[Feature] Dolphin supports the generation of DAGs through APIs

### ISSUE THREAD

**Issue by MessiAo** [apache/incubator-dolphinscheduler#1774]
Dolphin supports the generation of DAGs through APIs. For example, the interface side performs task configuration in the database to dynamically generate DAGs to implement task scheduling. Before using airflow, I thought of doing some through database configuration and then dynamically generating DAG py files to do

**Comment by xwhfcenter** [comment]
Agree.

**Comment by chengshiwen** [comment]
Please refer to http://106.75.43.194:8888/dolphinscheduler/doc.html
