### ISSUE TITLE
[BUG] Update from 1.1.0 to 1.2.0 then the web interface cannot show the process defenition's node

### ISSUE THREAD

**Issue by xwhfcenter** [apache/incubator-dolphinscheduler#1780]
I have finished upgraded dolphinscheduler from 1.1.0(not Apache) to 1.2.0(Apache).
And run all kind of services.
When I run it, everything is OK but the process defenition's node can not be shown.

Chrome tells me that api works well and gives a correct response.
![image](https://user-images.githubusercontent.com/6407672/72032913-bbe02400-32cb-11ea-8dce-b4720c5ddcb3.png)

**Comment by break60** [comment]
Do you mean the nodes are not displayed?
![image](https://user-images.githubusercontent.com/28628088/72229904-e3493080-35ec-11ea-8d9b-788de6975597.png)

**Comment by xwhfcenter** [comment]
Yes, all nodes can not display. I  don't know why.

**Comment by break60** [comment]
You see if there is an error in the console. In addition, I don't know what browser you are using. I recommend using the chrome browser
![image](https://user-images.githubusercontent.com/28628088/72234854-f1f21080-3609-11ea-9ace-fc4e971ce338.png)

**Comment by xwhfcenter** [comment]
Yes, I  always use Chrome

**Comment by break60** [comment]
Look at # 1761, he seems to have a problem with you
![image](https://user-images.githubusercontent.com/28628088/72306546-74cea600-36b2-11ea-806a-a765fe38ef96.png)

**Comment by xingchun-chen** [comment]
Whether the issue has been resolved, if it is resolved, please close it

**Comment by xingchun-chen** [comment]
Do not reply for a long time, temporarily close the issue
