### ISSUE TITLE
[dev_1.2.1] The node runs backward. If the next node also depends on other nodes, the process instance status is always running and will not end

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1787]
![image](https://user-images.githubusercontent.com/55787491/72049500-04aed180-32fa-11ea-822a-d2ed3528c67b.png)

1.  As shown above, choose to run backward in the task shell_file_dev_1.2.1_2；
2. Task shell_file_dev_1.2.1_4 also depends on shell_file_dev_1.2.1_3；
3.  As shown in the figure below, the status of the process instance is always running, there is no final state

![image](https://user-images.githubusercontent.com/55787491/72049509-0bd5df80-32fa-11ea-98e6-45fc4bc701c7.png)

**Comment by Rubik-W** [comment]
@xingchun-chen 
I will fix it.
