### ISSUE TITLE
[dev_1.2.1]  Click to view the history, enter the task instance page, the results of the query based on the search conditions are displayed incorrectly

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1789]
![image](https://user-images.githubusercontent.com/55787491/72060392-d5ef2600-330e-11ea-8fc1-df2cbc33b439.png)

1. As shown above, click the View History to enter the task instance page
2. As shown in the following figure, according to the status of the successful query, the request parameter processInstanceId = 92 should be passed empty

![image](https://user-images.githubusercontent.com/55787491/72060613-4f871400-330f-11ea-8ff1-866f7d1e83d9.png)

**Comment by break60** [comment]
+1
