### ISSUE TITLE
Add dataX or sqoop components to support the data pulling of the previous node and data storage of the next node

### ISSUE THREAD

**Issue by zhbdesign** [apache/incubator-dolphinscheduler#1807]

**Comment by xingchun-chen** [comment]
Please change the title in English,thanks

**Comment by dailidong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/1881  datax supported, and will be published in version 1.2.2 or later

**Comment by Eights-Li** [comment]
#1974 sqoop supported
