### ISSUE TITLE
[dev_1.2.1]Workflow instance does not show dependencies

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1810]
![image](https://user-images.githubusercontent.com/55787491/72236150-9d9e5f00-3610-11ea-82e1-3c0b18a6a68e.png)

**Comment by xingchun-chen** [comment]
@break60

**Comment by break60** [comment]
+1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xingchun-chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月13日(星期一) 下午2:32
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"数码港"<790061044@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] [dev_1.2.1]Workflow instance does not show dependencies (#1810)




@break60
