### ISSUE TITLE
[dev_1.2.1] Add multiple dependencies, the workflow definitions of the first few dependencies read the workflow definition of the last project

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1816]
![image](https://user-images.githubusercontent.com/55787491/72312120-fd087780-36c1-11ea-8969-6ad6fae3df23.png)
![image](https://user-images.githubusercontent.com/55787491/72312239-8029cd80-36c2-11ea-99ef-2b2eda128851.png)

**Comment by xingchun-chen** [comment]
@break60

**Comment by break60** [comment]
+1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xingchun-chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 中午11:37
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"数码港"<790061044@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] [dev_1.2.1] Add multiple dependencies, the workflow definitions of the first few dependencies read the workflow definition of the last project (#1816)




@break60
