### ISSUE TITLE
Under the safari browser, there are no two fields: start time and submission time

### ISSUE THREAD

**Issue by lanluyu123** [apache/incubator-dolphinscheduler#1818]
Under safari browser, project management => workflow => task instance panel, there is no start time and submission time, but there are under google browser, but I like safari browser very much, do not want to give it up, can you Fix this bug, thanks

**Comment by Yeleights** [comment]
please edit this issue in english~

**Comment by lanluyu123** [comment]
Under the safari browser, there are no two fields: start time and submission time.Tks

**Comment by break60** [comment]
> Under the safari browser, there are no two fields: start time and submission time.Tks

Currently compatible with this only for chrome browser

**Comment by linyanbin666** [comment]
I referred @DiamondYuan comments in [dayjs/issues](https://github.com/iamkun/dayjs/issues/73)   and changed  the following code in filter.js
`const formatDate = (value, fmt) => {
  value = value.replace(/(\+\d{2})(\d{2})$/, "$1:$2");
  fmt = fmt || 'YYYY-MM-DD HH:mm:ss'
  return dayjs(value).format(fmt)
}`
it's work well for me.

**Comment by CalvinKirs** [comment]
Currently compatible with this only for chrome browser
I will close it. If you need, you can submit a PR, you can reopen it when you submit pr
