### ISSUE TITLE
MasterSchedulerThread BLOCKED

### ISSUE THREAD

**Issue by xwhfcenter** [apache/incubator-dolphinscheduler#1836]
I reinstall dolphinscheduler 1.2.0 then configure my project and process definition.
But when I click run, then nothing happens. And the process instance list is null. 
Following is my jstack file, and I see that MasterSchedulerThread is BLOCKED.
Do you know why? And How can I fix it?
[stack.txt](https://github.com/apache/incubator-dolphinscheduler/files/4063770/stack.txt)

**Comment by Technoboy-** [comment]
Hi bro, is your problem resolved ?

**Comment by xwhfcenter** [comment]
> Hi bro, is your problem resolved ?
Nope, I rollback to 1.1.0. I found that 1.2.0 cannot work well. There are so many bugs.

**Comment by wenhemin** [comment]
you can look at this. #1478
