### ISSUE TITLE
[QUESTION] About the upgrade

### ISSUE THREAD

**Issue by l397051926** [apache/incubator-dolphinscheduler#1838]
Hello, can you provide some updates about 1.2.0?
And 1.2.1 are there any improvements we plan to make

**Comment by dailidong** [comment]
which version do you use for now?

**Comment by l397051926** [comment]
I used version 1.1.0

**Comment by l397051926** [comment]
> which version do you use for now?

I used version 1.1.0

**Comment by dailidong** [comment]
of course, 1.1.0 can upgrade to 1.2.0

**Comment by dailidong** [comment]
and 1.2.1 release note: 
https://github.com/apache/incubator-dolphinscheduler/releases/tag/1.2.1

**Comment by dailidong** [comment]
for now I suggest use 1.2.0
