### ISSUE TITLE
The workflow caused by the upgrade does not trigger(升级造成的工作流不触发)

### ISSUE THREAD

**Issue by modehuan** [apache/incubator-dolphinscheduler#1842]
After the system version upgrade (1.05-> 1.20), the previously configured workflow cannot dispatch tasks automatically when it is time.

系统版本升级(１.０５－＞１.２０)后，原来已配置好的工作流到时间却无法自动派发任务．

**Comment by wenhemin** [comment]
you can look at this. #1478

**Comment by dailidong** [comment]
solved or not?  if resolved, please close issue, or please give more deep information

**Comment by xingchun-chen** [comment]
Whether the issue has been resolved, if it is resolved, please close it

**Comment by xingchun-chen** [comment]
Do not reply for a long time, temporarily close the issue
