### ISSUE TITLE
[dev_1.2.1]Optimize the width of the resource file popup  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#1851]
![image](https://user-images.githubusercontent.com/55787491/72601502-80d79380-3950-11ea-94fe-9dd84f840df4.png)
![image](https://user-images.githubusercontent.com/55787491/72601703-e461c100-3950-11ea-8aeb-81d99132dad3.png)

**Comment by xingchun-chen** [comment]
@break60

**Comment by break60** [comment]
+1
