### ISSUE TITLE
[Feature] Add ETL function node

### ISSUE THREAD

**Issue by wenhemin** [apache/incubator-dolphinscheduler#1856]
I extended the ETL node on DS, Implement the function of executing SQL for data synchronization.
Synchronize data through Datax middleware, DS need not be coupled to Datax.

I can contribute code if needed by the community.

Implementation ideas:
1.Add ETL nodes in DS
2.Generate Datax json file based on configuration parameters
3.Datax python script called by shell script task to start process

Problems with the current implementation:
1.Datax does not support multi-table synchronization, a task can only synchronize one table
2.Low resource utilization, each ETL task needs to start a JVM process

<img width="846" alt="WechatIMG6269" src="https://user-images.githubusercontent.com/39549317/72661446-1fc5c380-3a15-11ea-9c0e-693ba550c31f.png">

**Comment by stopit** [comment]
come on~  it is needed by a lot of projects.

**Comment by lianjie1229** [comment]
great job

**Comment by gabrywu** [comment]
+1

**Comment by dailidong** [comment]
+1

**Comment by jessienxx** [comment]
哪个版本里面包含这个功能？

**Comment by Rubik-W** [comment]
The next release version, after 1.2.1.
