### ISSUE TITLE
[Feature] set acquireTriggersWithinLock true

### ISSUE THREAD

**Issue by gabrywu** [apache/incubator-dolphinscheduler#1863]
## Background

[quartzDoc](http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html)
The current quartz config not set acquireTriggersWithinLock， we must set it true just like:
org.quartz.jobStore.acquireTriggersWithinLock=true

## Solution

org.quartz.jobStore.acquireTriggersWithinLock=true

**Comment by dailidong** [comment]
to prevent multiple threads from pulling to the same trigger, it also avoids the risk of repeated schedule
