### ISSUE TITLE
[BUG] problem with zookeeper 3.5 version when deploying DS

### ISSUE THREAD

**Issue by nboding** [apache/incubator-dolphinscheduler#1889]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
When deploying DS with zookeeper3.5, the zookeeper monitoring status of the monitoring center will be invalid.
![图片](https://user-images.githubusercontent.com/39879133/73719385-3fb9ee80-475a-11ea-82f8-20646b376528.png)

If replace the zookeeper-3.4.14.jar package under lib / with version 3.5, the DS master cannot be started.
Only the 3.4.14 version of zookeeper was installed successfully.

**Comment by dailidong** [comment]
good job.

By the way, please update/add title/content in English, thx

**Comment by dailidong** [comment]
please add the detail exception info.
