### ISSUE TITLE
[BUG] Starting master didn't output full log to log file

### ISSUE THREAD

**Issue by Jave-Chen** [apache/incubator-dolphinscheduler#1893]
When start master use command below 
`sh ./bin/dolphinscheduler-daemon.sh start master-serve`
there is just some part of beginning output in log files, like this
![](https://user-images.githubusercontent.com/22913838/73748345-2fbf0080-4794-11ea-8923-895a5d53b2bb.png)

After modified start command in dolphinscheduler-daemon.sh ,
```
#nohup $JAVA_HOME/bin/java $exec_command > $log 2>&1 < /dev/null &
$JAVA_HOME/bin/java $exec_command
```
And added STDOUT in conf/master_logback.xml file
```
<root level="INFO">
   <appender-ref ref="STDOUT"/>
   ...
</root>
```

The same command output the full log 
![](https://user-images.githubusercontent.com/22913838/73748731-094d9500-4795-11ea-9a54-985525ff8623.png)

It seems like the log didn't output to the file correctly.

**Comment by Robustshouhualee** [comment]
I have the same problem, when use your method ,I found the error as well as you.Thanks

**Comment by dailidong** [comment]
please submit a PR solve this issue

**Comment by dailidong** [comment]
I will do this on the refactor-worker branch

**Comment by dailidong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/2120 solved this problem，it will be published next version
