### ISSUE TITLE
[QUESTION] The pyspark task actually succeeds but the web page display fails

### ISSUE THREAD

**Issue by chengcxy** [apache/incubator-dolphinscheduler#1897]
![image](https://user-images.githubusercontent.com/25173362/73821409-e4a5fb80-482e-11ea-947a-dd24c73b088f.png)
As shown in the log above, the program status is success, but the web page fails to display (below)
![image](https://user-images.githubusercontent.com/25173362/73821527-161ec700-482f-11ea-8d88-130372affc4d.png)

**Comment by dailidong** [comment]
which version?

**Comment by dailidong** [comment]
English is needed

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved, if not, please check the worker log for errors
