### ISSUE TITLE
[BUG] datax task execute failed

### ISSUE THREAD

**Issue by jamee-wang** [apache/incubator-dolphinscheduler#1927]
**Describe the bug**
datax node task execute failed, error:

[INFO] 2020-02-10 18:54:04.298  - [taskAppId=TASK-4-16-20]:[99] - tenantCode user:tester, task dir:4_16_20
[INFO] 2020-02-10 18:54:04.300  - [taskAppId=TASK-4-16-20]:[103] - create command file:/tmp/dolphinscheduler/exec/process/3/4/16/20/4_16_20.command
[INFO] 2020-02-10 18:54:04.301  - [taskAppId=TASK-4-16-20]:[116] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /work/dolphinscheduler/conf/env/dolphinscheduler_env.sh

/tmp/dolphinscheduler/exec/process/3/4/16/20/4_16_20_node.sh
[INFO] 2020-02-10 18:54:04.303  - [taskAppId=TASK-4-16-20]:[333] - task run command:
sudo -u tester sh /tmp/dolphinscheduler/exec/process/3/4/16/20/4_16_20.command
[INFO] 2020-02-10 18:54:04.313  - [taskAppId=TASK-4-16-20]:[155] - process start, process id is: 14777
[INFO] 2020-02-10 18:54:04.343  - [taskAppId=TASK-4-16-20]:[107] -  -> /usr/bin/python2.7: can't find '__main__' module in '/work/datax'
[INFO] 2020-02-10 18:54:04.343  - [taskAppId=TASK-4-16-20]:[165] - process has exited, work dir:/tmp/dolphinscheduler/exec/process/3/4/16/20, pid:14777 ,exitStatusCode:1

**To Reproduce**
1. install dolphinscheduler from dev branch package;
2. install datax on worker node;
3. create process with datax task
4. run the process

**Expected behavior**
datax task execute successfully, and data import to target table

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**
set DATAX_HOME to full path of datax.py, the task can be executed successfully.

**Requirement or improvement
- DATAX_HOME should only be the datax root path

**Comment by dailidong** [comment]
@wenhemin ， could you help to solve this issue？

**Comment by wenhemin** [comment]
Please look at the .dolphinscheduler_env.sh file
Can refer to this configuration：
  export DATAX_HOME=/opt/datax/bin/datax.py

**Comment by dailidong** [comment]
is this issue been solved? 

BTW,
@wenhemin I think write instructions about datax on the official website will be better？how do you think?

**Comment by wenhemin** [comment]
> is this issue been solved?
> 
> BTW,
> @wenhemin I think write instructions about datax on the official website will be better？how do you think?

OK, I add.

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved?
