### ISSUE TITLE
[QUESTION] got a 500 status code when save a process 

### ISSUE THREAD

**Issue by Harpsichord1207** [apache/incubator-dolphinscheduler#1930]
the dolphin version is 1.2.

I add a node to a process which already has 2 nodes and click save, the server return a 500 error, but if a add this node with same content to another process, it succeed.

**Comment by wenhemin** [comment]
You can look at the dolphinscheduler-api.log

**Comment by Harpsichord1207** [comment]
there's no new log line after I click save

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved?

**Comment by Harpsichord1207** [comment]
nope

**Comment by xingchun-chen** [comment]
You can see what error is reported in the browser console. The error message should be printed in the api log.

**Comment by chengshiwen** [comment]
Close the issue since no updates for long time
