### ISSUE TITLE
[QUESTION] [BUG] task instance is null but process instance is still running

### ISSUE THREAD

**Issue by Notos2** [apache/incubator-dolphinscheduler#1942]
![image](https://user-images.githubusercontent.com/49053679/74299705-76aa8880-4d88-11ea-9109-3d3e10460bbf.png)

![image](https://user-images.githubusercontent.com/49053679/74299748-9a6dce80-4d88-11ea-9775-9c1968f14937.png)

**Which version of DolphinScheduler:**
 -[1.1.0-preview]
 

**Requirement or improvement
- why not stop the task and restart.

**Comment by Notos2** [comment]
It happens  once in a while .  At first, I thought it was a network problem ，then I use a stand-alone zk.but it still happen.

**Comment by oceanos** [comment]
[1.2.0] met the same problem. Is there a comitter who can answer this question?
![image](https://user-images.githubusercontent.com/11856424/78094226-982e0500-7406-11ea-854e-6bbb872f1bee.png)
![image](https://user-images.githubusercontent.com/11856424/78094237-9ebc7c80-7406-11ea-9ab6-d3ef31c35acb.png)

**Comment by Notos2** [comment]
> [1.2.0] met the same problem. Is there a comitter who can answer this question?
> ![image](https://user-images.githubusercontent.com/11856424/78094226-982e0500-7406-11ea-854e-6bbb872f1bee.png)
> ![image](https://user-images.githubusercontent.com/11856424/78094237-9ebc7c80-7406-11ea-9ab6-d3ef31c35acb.png)

It has been fixed .detail :https://github.com/apache/incubator-dolphinscheduler/issues/1477
