### ISSUE TITLE
[Feature] Generating locations automatically by task definition and dependency(通过任务定义和依赖自动生成位置信息绘制DAG)

### ISSUE THREAD

**Issue by kylozw** [apache/incubator-dolphinscheduler#1943]
It's difficult to locate tasks when the workflow is huge. Under the circumstances, it's difficult to add a new task dependent on some tasks.

So I reccommend that Generating locations automatically by task definition and dependency.

It's ok to calling APIs. Now I can define workflows by calling api `/dolphinscheduler/projects/{projectName}/process/save`, but if I don't set the x and y, the workflow shows bad.

![9a79f943ly1gbtlhwd71uj21rw0u0gr4.jpg](https://wx2.sinaimg.cn/large/9a79f943ly1gbtlhwd71uj21rw0u0gr4.jpg)

BTW, it's another useful feature locating tasks.

---

如果工作流很大，包含很多任务时，很难找到指定的任务，这时添加新任务就困难了。

我建议可以通过任务的定义和依赖自动生成 DAG，包括节点的位置（类似自动绘图）。

目前通过调用 `/dolphinscheduler/projects/{projectName}/process/save` 这个 API，可以创建工作流，但是如果不指定 x 和 y 的数值，工作流展示界面就会很混乱，像图中这样。

PS：定位任务的功能也很需要。

**Comment by dailidong** [comment]
version 1.2.1 support this feature

**Comment by dailidong** [comment]
for now, i will close this issue, if not solved your problem, you can reopen it

**Comment by kylozw** [comment]
I used the version 1.2.1, and it didn't work.
