### ISSUE TITLE
[QUESTION] About workflow upload 

### ISSUE THREAD

**Issue by pigsoft2016** [apache/incubator-dolphinscheduler#1980]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
Does the project name have to be the same for the workflow to be downloaded from the development environment and uploaded to the production environment?

Can you just focus on the workflow itself and ignore the project name?

**Which version of DolphinScheduler:**
 -[1.2.0-preview]

**Comment by Eights-Li** [comment]
this question have been fix in dev,  the pr: #1676

**Comment by pigsoft2016** [comment]
ths
