### ISSUE TITLE
How to keep only one instance running at the same time

### ISSUE THREAD

**Issue by cconlyou** [apache/incubator-dolphinscheduler#1995]
If we have some processes do not support parallel execution. 
How to keep only one instance running at the same time ?

example 1 :
One instance is running by schedule service . If we start another instance by hand, how to keep these instances run by order.

example 2 :
If the schedule's interval is short, such as per minute, and the duration of each instance is not regular. We want the next instance to wait until previous instance run end.

**Comment by cconlyou** [comment]
Can anyone help me ?

**Comment by dailidong** [comment]
Duplicate of #1211,  the comments should also see

**Comment by dailidong** [comment]
if you have some comments, please comment on the #1211,  I will close this issue
