### ISSUE TITLE
Ali nail, WeChat alarm（阿里钉钉、微信告警）

### ISSUE THREAD

**Issue by boandai** [apache/incubator-dolphinscheduler#202]

**Comment by lynchlee** [comment]
good idea

**Comment by stanfen** [comment]
developing new feature of sending msg to ali nail group.

**Comment by dailidong** [comment]
WeChat has been supported for a long time

**Comment by dailidong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/2594 support Ali nail alarm
