### ISSUE TITLE
dolphinscheduler 部署 k8s 的问题

### ISSUE THREAD

**Issue by paulzanmei** [apache/incubator-dolphinscheduler#2024]
请问，dolphinscheduler 可以部署在k8s 上吗?
如果可以部署，worker 节点调度hadoop , flink ，hive 等平台的时候，需要在 worker 镜像里面一起制作这些平台的客户端在里面吗？

**Comment by liwenhe1993** [comment]
Of course, hadoop, flink, hive, and etc. can integrate into worker, if you need them, you must install packages into docker image.

**Please use English.**
