### ISSUE TITLE
build rpm package in IDEA

### ISSUE THREAD

**Issue by Aries1314** [apache/incubator-dolphinscheduler#2031]
DolphinScheduler 利用 mvn -U clean package -Prpmbuild -Dmaven.test.skip=true 在idea中编译 报错 The requested profile "rpmbuild" could not be activated because it does not exist. 结果没有生成RPM包  查了下 网上没有相关的解释 请教下

**Comment by gaojun2048** [comment]
Hi , rpmbuild profile is supported since 1.2.1 . And still have a bug with this feature , You can get the latest status at this issue : 
https://github.com/apache/incubator-dolphinscheduler/issues/2038

**Comment by Aries1314** [comment]
ok

**Comment by dailidong** [comment]
#2144

**Comment by dailidong** [comment]
English is needed

**Comment by gaojun2048** [comment]
> DolphinScheduler 利用 mvn -U clean package -Prpmbuild -Dmaven.test.skip=true 在idea中编译 报错 The requested profile "rpmbuild" could not be activated because it does not exist. 结果没有生成RPM包 查了下 网上没有相关的解释 请教下

You cannot build the rpm package in IDEA. You can only build the rpm package on a Linux system with the rpmbuild library installed. You can install the rpmbuild library by following these steps
```
yum install --y rpm-build rpmdevtools.noarch
echo "% _topdir $ YOURDIR"> ~ / .rpmmacros
rpmdev-setuptree
```

**Comment by dadong-13** [comment]
请问你的这个问题解决了吗？具体怎么操作呢
 @EricJoy2048 @Aries1314
