### ISSUE TITLE
make the source code into RPM package

### ISSUE THREAD

**Issue by barntt77** [apache/incubator-dolphinscheduler#2038]
### I want to make the source code into RPM package，but have a question。
![微信截图_20200228091709](https://user-images.githubusercontent.com/54257101/75501489-1e6fb980-5a0b-11ea-977e-6dcb5b146e9b.png)

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dolphinscheduler 1.2.1:
[INFO] 
[INFO] dolphinscheduler ................................... SUCCESS [  9.994 s]
[INFO] dolphinscheduler-ui ................................ SUCCESS [  1.827 s]
[INFO] dolphinscheduler-common ............................ SUCCESS [ 30.829 s]
[INFO] dolphinscheduler-dao ............................... SUCCESS [01:47 min]
[INFO] dolphinscheduler-rpc ............................... SUCCESS [09:46 min]
[INFO] dolphinscheduler-alert ............................. SUCCESS [01:29 min]
[INFO] dolphinscheduler-server ............................ SUCCESS [ 19.841 s]
[INFO] dolphinscheduler-api ............................... SUCCESS [06:49 min]
[INFO] dolphinscheduler-dist .............................. FAILURE [ 51.450 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21:52 min
[INFO] Finished at: 2020-02-27T11:43:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:attached-rpm (default) on project dolphinscheduler-dist: Source location /opt/apache-dolphinscheduler-incubating-1.2.1-src-release/dolphinscheduler-dist/../dolphinscheduler-ui/dist does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dolphinscheduler-dist

**Comment by gaojun2048** [comment]
Hi, I will work to fix it.
Thank you.

**Comment by barntt77** [comment]
> Hi, I will work to fix it.
> Thank you.

Do you have a compiled RPM package for download
@gaojun2048

**Comment by gaojun2048** [comment]
> > Hi, I will work to fix it.
> > Thank you.
> 
> Do you have a compiled RPM package for download
> @gaojun2048

@dailidong  Do we have a file server that releases rpm packages？

**Comment by barntt77** [comment]
> > > Hi, I will work to fix it.
> > > Thank you.
> > 
> > 
> > Do you have a compiled RPM package for download
> > @gaojun2048
> 
> @dailidong Do we have a file server that releases rpm packages？

**Comment by barntt77** [comment]
![image](https://user-images.githubusercontent.com/54257101/75838760-c9b0b200-5e01-11ea-9791-7a2bbaf20800.png)
when i want to start api server ,meet this question, need help .I have tested the same configuration locally, but have had this problem on the server

**Comment by gaojun2048** [comment]
> ![image](https://user-images.githubusercontent.com/54257101/75838760-c9b0b200-5e01-11ea-9791-7a2bbaf20800.png)
> when i want to start api server ,meet this question, need help .I have tested the same configuration locally, but have had this problem on the server


Looks like this is not a rpmbuild issue , can you create another issue about it and some one will help you fix it .

**Comment by dailidong** [comment]
@gaojun2048 , this issue can close or not?
