### ISSUE TITLE
[Feature] Ducment for really developer

### ISSUE THREAD

**Issue by xxland** [apache/incubator-dolphinscheduler#2043]
**We dont wanna use the web ui**. We need to control the dag/flow/schedule by code. I found the api document on http://106.75.43.194:8888/dolphinscheduler/doc.html, and at the page of `create a process` (`save` api), the document said: 

参数名称 | 参数说明 
-- | -- 
locations | process definition node locations info (json format) 
name | process definition name 
processDefinitionJson | process definition detail info (json format)

ok, what's the detail json format of the arguments? where can i find them? i found many document for end-user of ui and maintain/deployment, but how can I find anything for **coder**?

**Comment by dailidong** [comment]
please refer the reply content:
https://lists.apache.org/thread.html/r4de7e7f8c943b82d82f259e9b71aeefce67ff3289e52b1616d479e38%40%3Cdev.dolphinscheduler.apache.org%3E
