### ISSUE TITLE
Support condition detection type task（支持条件检测类型任务）

### ISSUE THREAD

**Issue by boandai** [apache/incubator-dolphinscheduler#205]

**Comment by lianjie1229** [comment]
+1

**Comment by lenboo** [comment]
i want to support a new task type: Conditions

* There are only two branches in the conditions task, the successful branch and the failed branch are shown in the figure:
![image](https://user-images.githubusercontent.com/29528966/73710294-8863ae80-473e-11ea-8263-c0cc03317ec9.png)


* Similar to dependent tasks, the conditions task only judges whether other tasks are executed successfully or not, and decides which branch to execute according to the judgment result, and does not participate in specific business execution.

* Two branches of conditional judgment task cannot be aggregated

- If aggregation occurs, the process may not end properly. As shown in the picture:
![image](https://user-images.githubusercontent.com/29528966/73710933-4b98b700-4740-11ea-8a25-ac51502801c1.png)

- If there is aggregation of conditions tasks, please separate the conditions tasks as subprocesses
![image](https://user-images.githubusercontent.com/29528966/73710992-7125c080-4740-11ea-8fd4-436584538401.png)



* 条件判断任务只有两个分支，成功分支和失败分支：

* 条件判断任务只判断其他任务执行成功与否，并根据判断结果决定执行哪个分支，不参与具体的任务执行。

* 条件判断任务的两个分支不能聚合
  - 如果发生聚合，可能造成流程不能正常结束。
  
  - 如果条件判断任务存在聚合，请把条件判断任务作为子流程独立出来

**Comment by yangjiajun2014** [comment]
仅供参考：
我们的DAG调度系统里把不用执行的节点标识为skip(跳过执行状态)，作为结束状态的一种。一个节点的所有前置节点都跳过执行，那么该节点也跳过执行。一个节点所有前置节点都已经结束且至少有一个节点是正常结束的，这个节点也应该被触发。我们是通过这样的机制，让多分支可以聚合。

Just for u reference:
In our DAG scheduler system,we introduce 'skipped' status,which marks a node don't need to execute but end.A node needs to skipped if all of its pre nodes were skipped.A node can be executed if all of its pre nodes ended and at least one of pre nodes ended normally.We let branches of conditional judgment task can be aggregated by such scheme.

**Comment by lenboo** [comment]
> 仅供参考：
> 我们的DAG调度系统里把不用执行的节点标识为skip(跳过执行状态)，作为结束状态的一种。一个节点的所有前置节点都跳过执行，那么该节点也跳过执行。一个节点所有前置节点都已经结束且至少有一个节点是正常结束的，这个节点也应该被触发。我们是通过这样的机制，让多分支可以聚合。
> 
> Just for u reference:
> In our DAG scheduler system,we introduce 'skipped' status,which marks a node don't need to execute but end.A node needs to skipped if all of its pre nodes were skipped.A node can be executed if all of its pre nodes ended and at least one of pre nodes ended normally.We let branches of conditional judgment task can be aggregated by such scheme.

thank you very much for suggestions!
Your suggestion is very useful. When the conditions task takes a successful branch, set the node of the failed branch and the subsequent node as skip. Finally, the aggregation node can skip the 'skip' node judgment.

你的建议很有用，当条件判断任务走成功分支的时候，将失败分支的节点和其后的节点都置为'skip'，最后聚合节点可以跳过skip节点判断。

**Comment by dailidong** [comment]
PR #2003 solve this feature
