### ISSUE TITLE
Multi-node using local files

### ISSUE THREAD

**Issue by xpdgit** [apache/incubator-dolphinscheduler#2061]
In ds, multiple nodes use the resource center and need to depend on hdfs and s3. This is more expensive for multi-node deployment and use of DS. If you use local files, reduce costs, which can extend the ease of use of this system

**Comment by dailidong** [comment]
how to implement this feature?  do you consider this situation:  different worker need download this file from the resource center,but this file only save on the special machine,  the available of the system may not be available.

how do you think?

btw, English is needed

**Comment by xpdgit** [comment]
As a distributed file system, HDFS ensures high availability of the system.But as an underlying platform, you can provide this pattern for deployment use.This is more lightweight in the eyes of the customer.Again, we left it up to the customer to decide whether to add HDFS to improve high availability or sacrifice that high availability with native files.We offer a variety of models for customers to choose.

**Comment by dailidong** [comment]
You can share file storage through multiple machines
---
你可以使用多机共享存储目录的方案
