### ISSUE TITLE
Backend deployment documentation and front-end deployment documentation， addresses cannot be accessed normally

### ISSUE THREAD

**Issue by barntt77** [apache/incubator-dolphinscheduler#2075]
![image](https://user-images.githubusercontent.com/54257101/75862177-7eb29100-5e39-11ea-9b10-56de62401aed.png)
https://github.com/apache/incubator-dolphinscheduler/tree/1.2.1
![image](https://user-images.githubusercontent.com/54257101/75862208-8c681680-5e39-11ea-9035-4b2a4c71b2f7.png)

**Comment by dailidong** [comment]
sorry for reply so late，the document are as follows:
https://dolphinscheduler.apache.org/en-us/docs/1.2.0/user_doc/quick-start.html
https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/quick-start.html

**Comment by dailidong** [comment]
some error has been corrected, thanks for telling us
