### ISSUE TITLE
It has a bug on Binary Distribution of dolphinscheduler 1.2.1 

### ISSUE THREAD

**Issue by Aries1314** [apache/incubator-dolphinscheduler#2086]
1.2.1版本 Binary Distribution包中没有 install-dolphinscheduler-ui.install 没有这个怎么部署启动前端呢？在Source code包中 就有这个文件  
![无标题](https://user-images.githubusercontent.com/55619711/75950923-96dfea00-5ee5-11ea-9796-ba34ba1af9d1.png)

**Comment by dailidong** [comment]
not a bug. 1.2.1 not use nginx as default mehtod for deploying front-end, becase jetty also can support static html/js/css.

please refer to the related doc: https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/cluster-deployment.html

when you already deployed backend , you can visite: http://192.168.xx.xx:12345/dolphinscheduler , then it should show the login page
