### ISSUE TITLE
[BUG]Spark, Flink, MR main jar packages are not displayed,Python does not display resources  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2087]
![image](https://user-images.githubusercontent.com/55787491/75955815-90f00600-5ef1-11ea-8c8f-0c3e46525277.png)
![image](https://user-images.githubusercontent.com/55787491/75955913-bda41d80-5ef1-11ea-9182-bbd9c2d3b19c.png)

**Branch**
[dev-resource-tree]

**Comment by ninyjun** [comment]
我的也是没有办法选择 主程序包  ，后来怎么解决的？
