### ISSUE TITLE
[BUG] After the resource is renamed, the parent directory of the subdirectory does not display the renamed name

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2088]
![image](https://user-images.githubusercontent.com/55787491/75956332-a3b70a80-5ef2-11ea-9145-bf7bf823d031.png)

**Which version of Dolphin Scheduler:**
 -[dev-resource-tree]

**Comment by lgcareer** [comment]
It is fixed and the code has merged to branch dev
