### ISSUE TITLE
[BUG]View authorized file resources, only show directories, and the directory tree is incorrect  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2089]
1.Authorize the user to the file /directory1/directory2.sh 【给用户授权文件/directory1/directory2.sh】
![image](https://user-images.githubusercontent.com/55787491/75957931-1a093c00-5ef6-11ea-86b8-6d31a0ef70c9.png)
2.View the user authorization file, only the  /directory1 is displayed, and there is no file directory2.sh under / directory1 in the directory tree. The directory2.sh file is displayed in the first-level directory.【查看用户授权文件，只显示目录/directory1，且目录树中/directory1下没有文件directory2.sh，directory2.sh文件显示在一级目录中】
![image](https://user-images.githubusercontent.com/55787491/75957950-255c6780-5ef6-11ea-8412-b21e82461326.png)

**Branch**
-[dev-resource-tree]

**Comment by dailidong** [comment]
title format: [BUG/FEATURE] xxx
