### ISSUE TITLE
[BUG] work flow state set error when master server down.

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2091]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
master would change the work flow state wrong on the  situation:
1. start a work flow, and tasks state are submit success.
2. master M_A cannot connect to zookeeper
3. the other masters(M_B) make the failover of the lost master M_A
4. master M_A would change the work flow state from running to success.

error logs: 

![image](https://user-images.githubusercontent.com/29528966/75959184-a87ebd00-5ef8-11ea-99b0-52f2e56f7a57.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Comment by chengshiwen** [comment]
Close since the issue has been resolved in 1.3.x
