### ISSUE TITLE
[BUG] Click the if / else node and request the / process / get-task-list? Interface to report an error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2098]
request  Interface:  http://192.168.xx.xx:12345/dolphinscheduler/projects/cxc_if/process/get-task-list?processDefinitionIdList=&_t=0.8965307575465242
![image](https://user-images.githubusercontent.com/55787491/76063756-4f2f9000-5fc3-11ea-9ffc-e94b454f1521.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0_release]

**Comment by lenboo** [comment]
@break60  whether this interface is essential ？

**Comment by break60** [comment]
Front end fixed
