### ISSUE TITLE
[BUG] When the branch flow of the if / else task is empty, the prompt is ambiguous  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2100]
当任务状态为成功或失败的分支流转都为空时，点击“确认提交”按钮，提示语改为“成功分支流转或失败分支流转不能为空”
![image](https://user-images.githubusercontent.com/55787491/76070260-2f9e6480-5fcf-11ea-8f7f-b60005b3e275.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0_release]

**Comment by xingchun-chen** [comment]
@break60

**Comment by dailidong** [comment]
Please use English

**Comment by break60** [comment]
Front end fixed
https://github.com/analysys/incubator-dolphinscheduler/commit/5fba9bee1b74429c6c2954edf79337b5672a7aa9
