### ISSUE TITLE
[BUG] After renaming the branch name, the name of Branch Flow does not change

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2101]
更改任务名称后，分支流转的名称还是更改前的任务名称
![image](https://user-images.githubusercontent.com/55787491/76071071-9e2ff200-5fd0-11ea-8702-e7b357d7b060.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0_release]

**Comment by zt-1997** [comment]
i will fix it.
