### ISSUE TITLE
[BUG] sun.misc.JavaIOFileDescriptorAccess is not portable

### ISSUE THREAD

**Issue by TisonKun** [apache/incubator-dolphinscheduler#2111]
Current implementation relies on `sun.misc.JavaIOFileDescriptorAccess` which is only accessible on oraclejdk8.

Basically the demand is getting & setting `field` field of `FileDescriptor`, so we can directly do that with reflection.

Though, I suspect the necessity we introduce `ProcessImplForWin32`. Maybe we could have a better way to support worker server to run bat script.

**Comment by dailidong** [comment]
good job

@liwenhe1993 please find some methods to solve this , thx

**Comment by liwenhe1993** [comment]
@TisonKun solved this bug, I'm checking this PR.
