### ISSUE TITLE
[BUG] Upload the shell script with 3000 lines , only display 2000 lines

### ISSUE THREAD

**Issue by Hackeruncle** [apache/incubator-dolphinscheduler#2117]
**Describe the bug**
Upload the shell script with 3000 lines , only display 2000 lines.
Although the download is 3000 lines, but the user experience is not good.

**Comment by dailidong** [comment]
good job

**Comment by dailidong** [comment]
@break60

**Comment by break60** [comment]
Very good. Let's fix this as soon as possible

**Comment by Hackeruncle** [comment]
@break60  Thanks！

**Comment by break60** [comment]
The front end has been limited to 3000 lines(#2141)
