### ISSUE TITLE
[Feature] Remove the dependency on mysql5.7

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2127]
due to use of CURRENT_TIMESTAMP, mysql 5.7 must be used, and the mysql version should not be limited

**Comment by lenboo** [comment]
1.  remove the CURRENT_TIMESTAMP  in sql file.
2. set the datetime field on code.
3. some other version dependency problems not found yet.

**Comment by dailidong** [comment]
good idea

who are interesting in do this feature?

**Comment by yangyichao-mango** [comment]
Hi @dailidong , I'm a starter and interesting in do this feature. Can you assign this to me?
