### ISSUE TITLE
  How does - jars refer to the jar package in the resource center when the spark job is submitted

### ISSUE THREAD

**Issue by osenlin** [apache/incubator-dolphinscheduler#2133]
How does - jars refer to the jar package in the resource center when the spark job is submitted

**Comment by dailidong** [comment]
![image](https://user-images.githubusercontent.com/15833811/76295620-e95b4500-62ef-11ea-837b-c1e0bbf645d9.png)

you also can refer the user doc on the  http://dolphinscheduler.apache.org
