### ISSUE TITLE
[QUESTION] FLOW run error: "there is not any tenant suitable please choose a tenant available"

### ISSUE THREAD

**Issue by haitaodd** [apache/incubator-dolphinscheduler#2177]
I have created a shell flow job, just echo something.
when I run the job, I encounter "there is not any tenant suitable please choose a tenant available"

**Comment by dailidong** [comment]
do you read [quick-start](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/quick-start.html)

**Comment by zixi0825** [comment]
> do you read [quick-start ?](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/quick-start.html)

can not use the default tenant?

**Comment by xingchun-chen** [comment]
The admin user needs to associate a tenant on the user management page, or select a tenant when saving the workflow
