### ISSUE TITLE
[BUG] SqlTask kerberos authentication process

### ISSUE THREAD

**Issue by yh2388** [apache/incubator-dolphinscheduler#2178]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
When the keytab is expired or deactivated, other tasks that did not require authentication also failed. Obviously there is something wrong with the kerberos authentication process and it should only do it when it is needed.

**Which version of Dolphin Scheduler:**
 -[1.2.1-release]

**Requirement or improvement
- Change CommonUtils.loadKerberosConf() call scope;

**Comment by dailidong** [comment]
good , we will verify this problem later

at the same time, if you are interesting in fix this problem , please submit a PR to solve, thx

**Comment by yh2388** [comment]
> good , we will verify this problem later
> 
> at the same time, if you are interesting in fix this problem , please submit a PR to solve, thx

+1
