### ISSUE TITLE
EasyScheduler service can't find java_home path

### ISSUE THREAD

**Issue by wentaowua** [apache/incubator-dolphinscheduler#22]
<img width="777" alt="WechatIMG72" src="https://user-images.githubusercontent.com/49381680/55705147-aa05e380-5a10-11e9-873e-f761c1bdf7db.png">
修改
/usr/local/src/EasyScheduler/target/escheduler-1.0.0-SNAPSHOT/bin/escheduler-daemon.sh

/usr/local/src是自己目录

![WechatIMG9](https://user-images.githubusercontent.com/49381680/55705298-0f59d480-5a11-11e9-8563-bab32f6a5a62.jpeg)

**Comment by dailidong** [comment]
sometimes, JAVA_HOME can't be found, your setting is the right way
