### ISSUE TITLE
[Feature]the fetchTaskThread cost too much time

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2207]
**Is your feature request related to a problem? Please describe.**
1.2.0-release
1. start 3 workers and 1 masters
2. create a workflow with 3K tasks 
3. when running the workflow, i find  most of the time is spent on the "fetchtaskthread" thread, and a large number of tasks are backlog in the ZK queue.
![image](https://user-images.githubusercontent.com/29528966/76831387-3300de00-6862-11ea-9a11-bcee4bd99cd6.png)

4. throng "arthas", i find some situations:
![image](https://user-images.githubusercontent.com/29528966/76831481-63487c80-6862-11ea-90d5-e24e521e34b9.png)

so i think we should  use less database and ZK interaction in "fetchtaskthread".

**Comment by dailidong** [comment]
good job

**Comment by chengshiwen** [comment]
Close this issue since `fetchTaskThread` has removed in 1.3.x
