### ISSUE TITLE
[Feature]can not get history data time when  run history or complement job

### ISSUE THREAD

**Issue by rusonding** [apache/incubator-dolphinscheduler#2208]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lenboo** [comment]
![image](https://user-images.githubusercontent.com/29528966/76836078-2765e500-686b-11ea-86db-b267b6ef1e8a.png)

i find the historical date can be obtained by complement.

**Comment by rusonding** [comment]
[yyyyMMdd] can not repace

**Comment by rusonding** [comment]
![image](https://user-images.githubusercontent.com/21210508/76836708-3bf6ad00-686c-11ea-93e8-11fc05284531.png)

**Comment by dailidong** [comment]
@lenboo

**Comment by dailidong** [comment]
hi，did you see the shell task runtime log?

![image](https://user-images.githubusercontent.com/15833811/76951583-db886e00-6946-11ea-8b47-bbb1294e24ee.png)

**Comment by rusonding** [comment]
for example ， run history job and  complement job when history date(2020-03-18), the log can print 2020-2-16 ,not 2020-3-16
