### ISSUE TITLE
[Suggestion] fastjson should be replaced by Jaskson

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#2216]
Because FastJson has vulnerabilities from time to time， I think FastJson should be replaced by Jaskson, any idea？

**Comment by dailidong** [comment]
#1431

**Comment by dailidong** [comment]
if you are interesting in implementing this feature， please leave a message，thx

**Comment by elitecodegroovy** [comment]
Replace the fastjson with secure version may be a good choice. The fastjson version is 1.2.61, which solved the problem. Please close the issue.

**Comment by gabrywu** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/2960 already merged ,this issue can be closed @dailidong
