### ISSUE TITLE
git 1.2.0-release branch compile is error  !!!!!!!

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2221]
1.2.0-release
I want to add my sms to Aert-moudle   add is ok ,i  want to compile all project in idea  for:
**mvn -U clean package -Prelease -Dmaven.test.skip=true**

I add my maven settings mirror  for:
 <mirror>
            <id>alimaven</id>
           <mirrorOf>central</mirrorOf>
            <name>aliyun maven</name>
            <url>https://maven.aliyun.com/nexus/content/repositories/central/</url>
         </mirror>
     
        
        <mirror>
            <id>repo1</id>
             <mirrorOf>central</mirrorOf>
            <name>Human Readable Name for this Mirror.</name>
            <url>http://repo1.maven.org/maven2/</url>
         </mirror>
     
         
         <mirror>
             <id>repo2</id>
             <mirrorOf>central</mirrorOf>
             <name>Human Readable Name for this Mirror.</name>
             <url>http://repo2.maven.org/maven2/</url>
         </mirror>
-------------------------------------
but  make it  is error    
error message is :
[INFO] Scanning for projects...
Downloading from nexus: http://repo.maven.apache.org/maven2/org/apache/apache/21/apache-21.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.dolphinscheduler:dolphinscheduler:1.2.1-SNAPSHOT: Could not transfer artifact org.apache:apache:pom:21 from/to nexus (http://repo.maven.apache.org/maven2): Transfer failed for http://repo.maven.apache.org/maven2/org/
apache/apache/21/apache-21.pom 501 HTTPS Required and 'parent.relativePath' points at wrong local POM @ line 49, column 10

my dependencies  is all ok ,why it not compile ???????

**Comment by feiyalun** [comment]
my add is it ,  but it not compile

        <mirror>
            <id>alimaven</id>
           <mirrorOf>central</mirrorOf>
            <name>aliyun maven</name>
            <url>https://maven.aliyun.com/nexus/content/repositories/central/</url>
         </mirror>
     
        
        <mirror>
            <id>repo1</id>
             <mirrorOf>central</mirrorOf>
            <name>Human Readable Name for this Mirror.</name>
            <url>http://repo1.maven.org/maven2/</url>
         </mirror>
     
         
         <mirror>
             <id>repo2</id>
             <mirrorOf>central</mirrorOf>
             <name>Human Readable Name for this Mirror.</name>
             <url>http://repo2.maven.org/maven2/</url>
         </mirror>

**Comment by dailidong** [comment]
Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

If you're receiving this error, then you need to replace all URL references to Maven Central with their canonical HTTPS counterparts:

Replace http://repo1.maven.org/maven2/ with https://repo1.maven.org/maven2/

Replace http://repo.maven.apache.org/maven2/ with https://repo.maven.apache.org/maven2/

If for any reason your environment cannot support HTTPS, you have the option of using our dedicated insecure endpoint at http://insecure.repo1.maven.org/maven2/


referer: https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by xingchun-chen** [comment]
whether your problem has been solved?
