### ISSUE TITLE
[QUESTION] Which version of Flink is used in DolphinScheduler

### ISSUE THREAD

**Issue by oceanos** [apache/incubator-dolphinscheduler#2226]
**Describe**
Cmd：
flink run -m yarn-cluster -ys 1 -yn 1 -yjm 1G -ytm 1G -d -c org.apache.flink.examples.java.wordcount.WordCount WordCount.jar

Error：
Caused by: java.io.FileNotFoundException: JAR file does not exist: -ys
	at org.apache.flink.client.cli.CliFrontend.getJarFile(CliFrontend.java:819)
	at org.apache.flink.client.cli.CliFrontend.buildProgram(CliFrontend.java:796)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:196)

**Version of DolphinScheduler:**
 -[1.2.0]

**Version of Flink:**
 -[1.9.0]
 -[1.10.0]

**Requirement or improvement**
- Some flink command line arguments or args order may not be compatible with the new version.
- Please add more infomation about flink task in DolphinScheduler, such as  the adaptation version.

**Comment by dailidong** [comment]
@LoveEvenWong  could you answer this issue?

**Comment by dailidong** [comment]
#711

**Comment by dailidong** [comment]
@oceanos 
because you use shell task , you can set FLINK_HOME under the conf/env/dolphinscheduler-env.sh,  you can use any version if you like

**Comment by huzekang** [comment]
I user flink 1.10 test is ok!
1. I remove  `-yn 1`  in the command (maybe `-yn` dosen't work in flink 1.10)
2. I add below  in the `conf/env/dolphinscheduler-env.sh` file
```
export HADOOP_CLASSPATH=`${HADOOP_HOME}/bin/hadoop classpath`
```
