### ISSUE TITLE
[BUG] When the data in the multi-level directory is empty,  an error pops up

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2227]
![image](https://user-images.githubusercontent.com/55787491/77024357-4c706a00-69c9-11ea-98be-d028f1734550.png)

**Which version of Dolphin Scheduler:**
-[dev-resource-tree]

**Comment by nauu** [comment]
Does anyone begin to fix this bug? If not, I will fix it.

**Comment by break60** [comment]
> Does anyone begin to fix this bug? If not, I will fix it.

already fixed
