### ISSUE TITLE
[Feature]dolphinscheduler-alert supports distributed deployment

### ISSUE THREAD

**Issue by elitecodegroovy** [apache/incubator-dolphinscheduler#2253]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Using zookeeper implements distributed lock to support the distributed deployment in order to make sure the `dolphinscheduler-alert` service is always high available.

**Describe alternatives you've considered**
Using zookeeper implements distributed lock. I have done for this solution. Please add the following setting to the configuration file **alert.properties**.
```
zookeeper.quorum=49.235.6.95:2181
scan.internal.time=60000
```

**Comment by dailidong** [comment]
please send an email to dev@dolphinscheduler.apache.org, we will talk about this topic

**Comment by elitecodegroovy** [comment]
Done!
