### ISSUE TITLE
One click commit project/follow to production from qa environment

### ISSUE THREAD

**Issue by sc750531323** [apache/incubator-dolphinscheduler#2258]
i want to a function that can click a button then the project/follow on qa can be submit to prd environment(在qa部署测试好的工作流或者项目或者任务可以一键提交到生产环境)

**Comment by dailidong** [comment]
good idea

**Comment by dailidong** [comment]
if anybody else who need this feature， please reply this issue

**Comment by CalvinKirs** [comment]
We provide import and export functions, I think what you need is it.
