### ISSUE TITLE
Ask a question about project integration plug-ins

### ISSUE THREAD

**Issue by Aries1314** [apache/incubator-dolphinscheduler#2273]
The projects on GitHub are not published on the official website. Can they be deployed locally? Can it be used to directly integrate the plug-ins of dolphin？
![无标题](https://user-images.githubusercontent.com/55619711/77270983-67541e80-6ce8-11ea-8ed3-96d484f868dc.png)

**Comment by dailidong** [comment]
you can refer: https://github.com/apache/incubator-dolphinscheduler/tags ,  as you can see, we manage the versions of DolphinScheduler  through by `tag`, you can change different tag to view the corresponding version source code 

By the way,  official website only publish the apache version that voted passed by apache general mail list
