### ISSUE TITLE
this workflow is bug , I think it's a very serious problem

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2282]
Is I also found a problem, it is a bug, is I have two workflow of a and b, then a workflow Riga, a1 node b work new b1 task dependent nodes, type selection, the chosen today, relying on a1, my situation is such, a workflow, I have the day before the creation of a1 run through a process, and then I run b process, theory should be run failed, but in fact was a success.I am also drunk, similarly I choose the type of b1 yesterday also can run successfully, but the first three days before the election run failed.That logo is faild

**Comment by feiyalun** [comment]
i use 1.2.0 version
就是我还发现一个问题， 其实算是一个bug， 就是我有两个工作流a 、b  ，然后a工作流里加a1节点， b工作中新增加个b1任务依赖节点，类型选择日，天选今天， 依赖a1， 我测的情况是这样的， a工作流里，我在创建a1前已经当天跑过a流程，然后我运行b流程，理论上应该是跑失败的，但是实际上是成功的。 我也是醉了， 同样我把b1的类型选择昨天也能跑成功， 但是选前三天就跑失败了。 那个标识是faild

**Comment by zixi0825** [comment]
i will fix it

**Comment by Rubik-W** [comment]
> i will fix it

There are many problems here.
It is recommended to analyze the code of dependency judgment from a global perspective.

**Comment by feiyalun** [comment]
Dev development of partners, also found this problem, it is suggested to discuss whether to change, I send email to dev@dolphinscheduler.apache.org, you can discuss it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rubik-W"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 中午11:54
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"飞亚伦"<874320724@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282)





  
i will fix it
  
There are many problems here.
 It is recommended to analyze the code of dependency judgment from a global perspective.

**Comment by zixi0825** [comment]
Hi,all


What should be the right workflow / task dependencies?


Premise: task A1 in workflow A, task B1 in workflow B, and B1 depends on A1



&nbsp;Detect the dependency before starting B1, and check if the instance of workflow a exists

if the instance of workflow A does not exist, the direct determination of dependency fails

if instance of workflow A exists , then

Instance of task A1 does not exist

If workflow A is executing, then B1 will wait

If workflow A has ended, the determination of dependency fails

Instance of task A1 exists

If task A1 is executing, then B1 will wait

If task A1 is executed successfully, the dependency is determined to be successful

If task A1 fails to execute, it is judged as dependency failure






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"feiyalun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午3:10
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"〖子ㄨ系〗"<649790970@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282)





 Dev development of partners, also found this problem, it is suggested to discuss whether to change, I send email to dev@dolphinscheduler.apache.org, you can discuss it. 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Rubik-W"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月24日(星期二) 中午11:54 
 收件人:&amp;nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"飞亚伦"<874320724@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282) 
 
 
 
 
 
    
 i will fix it 
    
 There are many problems here. 
  It is recommended to analyze the code of dependency judgment from a global perspective.

**Comment by feiyalun** [comment]
I think your logic is right and recommend it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"孙朝和"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午5:22
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"飞亚伦"<874320724@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282)





 Hi,all 
 
 
 What should be the right workflow / task dependencies? 
 
 
 Premise: task A1 in workflow A, task B1 in workflow B, and B1 depends on A1 
 
 
 
 &amp;nbsp;Detect the dependency before starting B1, and check if the instance of workflow a exists 
 
 if the instance of workflow A does not exist, the direct determination of dependency fails 
 
 if instance of workflow A exists , then 
 
 Instance of task A1 does not exist 
 
 If workflow A is executing, then B1 will wait 
 
 If workflow A has ended, the determination of dependency fails 
 
 Instance of task A1 exists 
 
 If task A1 is executing, then B1 will wait 
 
 If task A1 is executed successfully, the dependency is determined to be successful 
 
 If task A1 fails to execute, it is judged as dependency failure 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"feiyalun"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月24日(星期二) 下午3:10 
 收件人:&amp;nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"〖子ㄨ系〗"<649790970@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282) 
 
 
 
 
 
  Dev development of partners, also found this problem, it is suggested to discuss whether to change, I send email to dev@dolphinscheduler.apache.org, you can discuss it.  
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"Rubik-W"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年3月24日(星期二) 中午11:54  
  收件人:&amp;amp;nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"飞亚伦"<874320724@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [apache/incubator-dolphinscheduler] this workflow is bug , I think it's a very serious problem (#2282)  
   
   
   
   
   
      
  i will fix it  
      
  There are many problems here.  
   It is recommended to analyze the code of dependency judgment from a global perspective.
