### ISSUE TITLE
hive连接不上

### ISSUE THREAD

**Issue by wentaowua** [apache/incubator-dolphinscheduler#23]
<img width="1293" alt="WechatIMG10" src="https://user-images.githubusercontent.com/49381680/55705518-8a22ef80-5a11-11e9-9f12-82fd460303aa.png">

修改pom.xml文件
<img width="1027" alt="WechatIMG11" src="https://user-images.githubusercontent.com/49381680/55705648-d110e500-5a11-11e9-96fa-c15bcd8c9ed2.png">

**Comment by LINKPEF** [comment]
请问pom文件在哪里能找到？找了很久都找不到

**Comment by xingchun-chen** [comment]
Root directory 根目录下
![image](https://user-images.githubusercontent.com/55787491/98091800-d9b4f000-1ec0-11eb-8728-5bb91ace0a95.png)
