### ISSUE TITLE
.gitignore should not add "dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/taskInstance/index.vue"

### ISSUE THREAD

**Issue by itbasketplayer** [apache/incubator-dolphinscheduler#2300]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
after deployed,we can see the "任务实例" page is wrong!

**To Reproduce**
Steps to reproduce the behavior, for example:
1. deployed
2. Click on '任务实例'
3. See wrong page

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.2.1-release/1.2.0-release/dev]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
please submit a PR to solve this problem, thx
