### ISSUE TITLE
[Feature] DolphinScheduler self workflow lineage （海豚调度自身的工作流血缘关系）

### ISSUE THREAD

**Issue by LiemLin** [apache/incubator-dolphinscheduler#2305]
**Is your feature request related to a problem? Please describe.**
Is there a place to view workflow dependencies？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LiemLin** [comment]
![image](https://user-images.githubusercontent.com/16920347/77731458-f0978800-703d-11ea-8b80-76a5d83807b5.png)
@dailidong We implemented a view of the relationships between workflows based on version 1.1. like the one above. Does the community need this feature？

**Comment by LiemLin** [comment]
<img width="1247" alt="lineage" src="https://user-images.githubusercontent.com/16920347/77732493-e70f1f80-703f-11ea-9b4a-57f59ea15bb7.png">
We implemented the view of the relationships between workflows based on version 1.1. like the one above. Does the community need this feature？

**Comment by feiyalun** [comment]
i think   community need this feature

**Comment by dailidong** [comment]
@LiemLin ，sorry for see this feature too late，this feature is very good feature， please contribute to the dev branch， and maybe there need to do some change because version 1.1.0 is not apache version

**Comment by dailidong** [comment]
> i think community need this feature

thanks for reminder ,haha

**Comment by LiemLin** [comment]
Well, I'll take the time to merge the latest version

**Comment by LiemLin** [comment]
related to PR workflow lineage #2421
