### ISSUE TITLE
调度无法使用

### ISSUE THREAD

**Issue by lhlh1994** [apache/incubator-dolphinscheduler#2308]
部署完成发现调度无法使用，经过较长时间的排查，发现是mysql驱动包的问题。建议使用官方文档上的驱动版本。

同时希望能够改进一下日志，server里面quartz包下的日志无法打印到master.log，需要开启STDOUT。排查问题不方便

**Comment by dailidong** [comment]
good idea

next version will change logback config

**Comment by dailidong** [comment]
and English is needed

**Comment by jessienxx** [comment]
> 部署完成发现调度无法使用，经过较长时间的排查，发现是mysql驱动包的问题。建议使用官方文档上的驱动版本。
> 
> 同时希望能够改进一下日志，server里面quartz包下的日志无法打印到master.log，需要开启STDOUT。排查问题不方便

能说一下怎么解决的吗？我也碰到了调度无法使用的问题
