### ISSUE TITLE
The problem with ambari plugin is very urgent to ask for help

### ISSUE THREAD

**Issue by Aries1314** [apache/incubator-dolphinscheduler#2314]
请问  用ambari整合dolphin插件，在打成rpm包时是否有install-dolphinscheduler-ui? 在插件中并没提到这个install-dolphinscheduler-ui.sh 这个文件怎么处理的？

**Comment by dailidong** [comment]
@githubzhangchunyang  could you answer this question?

**Comment by gaojun2048** [comment]
In DS web can run with nginx or jetty .  The rpm package only support run web with jetty. So we deleted the install-dolphinscheduler-ui.sh file in the rpm package.

**Comment by Aries1314** [comment]
OK thanks
