### ISSUE TITLE
[BUG] Import workflow

### ISSUE THREAD

**Issue by barntt77** [apache/incubator-dolphinscheduler#2317]
![image](https://user-images.githubusercontent.com/54257101/77626243-0a729580-6f80-11ea-81d7-d1255ebc03f7.png)
I want to copy the workflow from project a to b，when i import the json profile , display success ,but not found the workflow
and i have found this question 
in the json profile ,'projectname'  limit the project name, need to modify the value

**Comment by Eights-Li** [comment]
which ds version ?

**Comment by xingchun-chen** [comment]
Versions below 1.2.1 only support importing workflows in the same project

**Comment by barntt77** [comment]
> 哪个ds版本？

1.2.0 
And it can be imported ,just need to modify the value in the download *.json 'projectname'

**Comment by xingchun-chen** [comment]
Yes, this is a solution, the import workflow between different projects will be optimized later

**Comment by barntt77** [comment]
> Yes, this is a solution, the import workflow between different projects will be optimized later

ok , should i close the issue?

**Comment by xingchun-chen** [comment]
You can close it, it will be resolved in the next version
