### ISSUE TITLE
[Question] Specify the process worker group and it does not work

### ISSUE THREAD

**Issue by oceanos** [apache/incubator-dolphinscheduler#2324]
**Describe**
When the worker group already exists on the task node, the worker group specified on the workflow does not take effect

**Reproduce**
Steps to reproduce the behavior, for example:
1. define process and  specify task node worker group
![image](https://user-images.githubusercontent.com/11856424/77752179-09199980-7062-11ea-8c5c-192a3a2c8d66.png)

2. run process and specify process worker group
![image](https://user-images.githubusercontent.com/11856424/77752081-d53e7400-7061-11ea-8620-b5d3a90fb74a.png)

3. flink task instance was executed on node-31

**Expected behavior**
1. Shouldn't it beexecuted on node-32
2. When does the worker group on the process take effect?

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Additional context**
#815

**Comment by zixi0825** [comment]
I will fix it

**Comment by zixi0825** [comment]
What should be the right worker group priority?
Process priority > Task priority  or Task priority> Process priority?

**Comment by zixi0825** [comment]
In my opinion

The priority design of worker group should be as follows:

- If you do not specify the priority of the task and choose default, the workflow's worker group will be used

- If you have specified a worker group for the task when you configure the task, the worker group in the task configuration will be used
-------------------------------------------------------------------------------------------------------------

在我看来
worker group 优先级的设计应该是这样的：
- 如果你没有指定任务的优先级，选择default的话，那么任务会采用工作流的worker group
- 如果你在配置任务时已经为任务指定了worker group ，那么会采用任务配置中的worker group

**Comment by dailidong** [comment]
> In my opinion
> 
> The priority design of worker group should be as follows:
> 
> * If you do not specify the priority of the task and choose default, the workflow's worker group will be used
> * If you have specified a worker group for the task when you configure the task, the worker group in the task configuration will be used
> 
> 在我看来
> worker group 优先级的设计应该是这样的：
> 
> * 如果你没有指定任务的优先级，选择default的话，那么任务会采用工作流的worker group
> * 如果你在配置任务时已经为任务指定了worker group ，那么会采用任务配置中的worker group

I think your idea is right, DS's origin design just like this

**Comment by dailidong** [comment]
this is not a bug,  DS's origin design just like this
