### ISSUE TITLE
[QUESTION] how to solve 【thread insufficient】problem?

### ISSUE THREAD

**Issue by lianjie1229** [apache/incubator-dolphinscheduler#2347]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
Information I found in worker log  as fllow:
[INFO] 2020-03-28 09:25:32.429 cn.escheduler.server.worker.runner.FetchTaskThread:[265] - thread insufficient , activeCount : 100 , worker
ExecNums : 100, will sleep : 1000 millis for thread resource

**Which version of DolphinScheduler:**
 1.1.0

**Additional context**

**Requirement or improvement

**Comment by Rubik-W** [comment]
You can see the worker.properties file.
`worker.exec.threads`

**Comment by dailidong** [comment]
does this issue solved or not?

**Comment by lianjie1229** [comment]
I understand this funciton,I have closed it, thanks for your reply .
















At 2020-04-13 22:07:47, "dailidong" <notifications@github.com> wrote:

does this issue solved or not?
