### ISSUE TITLE
[Question] api server, timing management interface depends on Quartz

### ISSUE THREAD

**Issue by Rubik-W** [apache/incubator-dolphinscheduler#2351]
Now, In the api server, on-line and off-line tasks depend on quartz scheduler.
```
        QuartzExecutors.getInstance().addJob(ProcessScheduleJob.class, jobName, jobGroupName, startDate, endDate,
                schedule.getCrontab(), dataMap);
```
```
        if(!QuartzExecutors.getInstance().deleteJob(jobName, jobGroupName)){
            logger.warn("set offline failure:projectId:{},scheduleId:{}",projectId,scheduleId);
            throw new RuntimeException(String.format("set offline failure"));
        }
```
QuartzExecutors.getInstance():
```
      SchedulerFactory schedulerFactory = new StdSchedulerFactory(Constants.QUARTZ_PROPERTIES_PATH);
      scheduler = schedulerFactory.getScheduler();
```
`org.quartz.threadPool.threadCount = 25`
25 worker threads are initialized by default. 
These threads will never be used.

**Comment by dailidong** [comment]
Do you think the proper value of `org.quartz.threadPool.threadCount` is ?

**Comment by Rubik-W** [comment]
This is not a problem with threadCount parameter.
The api server should not initialize the quartz thread pool, the master server uses these threads. When the api server is running and do on-line task timing, you can look at the thread pool (jstack).

**Comment by dailidong** [comment]
the deep discussion moved to the mail list : https://lists.apache.org/thread.html/r692bad0ac8b9626388504300e635b935b93518e6a06311c4a5f16560%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by Technoboy-** [comment]
This is a default value, for we want to use in server module only. But as development goes, and api module uses the same config as server. so causes the issue.
We will refactor quartz in the future. but in current version, you can set it as below in api module。
org.quartz.threadPool.threadCount = 1

**Comment by Rubik-W** [comment]
OK, I understand.
Api server and master server share a quartz instance,  share a quartz config file.
So, no problem keeping the current configuration.
