### ISSUE TITLE
org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[211] - consume tasks: [],there still have 2 tasks need to be executed

### ISSUE THREAD

**Issue by jijun0** [apache/incubator-dolphinscheduler#2353]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
Did you specify the worker groups to run the 2 tasks?   or did you find something special ？

**Comment by dailidong** [comment]
do you solve this problem or not ?

**Comment by dailidong** [comment]
referer #1466
