### ISSUE TITLE
[BUG] The worker service is not started before running the workflow, and the task is in the "submission successful" state. After starting the worker service, the task is not executed

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2355]
1. Do not start the worker service, run the workflow, and the task is in the "submission successful" state;
2. Start the worker service ,but the task is not executed.
=================================================
1.不启动worker服务，运行工作流，任务处于“提交成功”状态；
2.启动worker服务，任务没执行。
![image](https://user-images.githubusercontent.com/55787491/78123504-d3e5c080-7440-11ea-935b-5348d9c2fa23.png)
![image](https://user-images.githubusercontent.com/55787491/78123602-fc6dba80-7440-11ea-99b0-72b5d982ca0b.png)

**Which version of Dolphin Scheduler:**
 -[refactor-worker]

**Comment by shuxte** [comment]
劳驾问下这个问题是怎么解决的

**Comment by xingchun-chen** [comment]
This is a bug of the test branch during development. The dev_1.3.0 branch has solved the problem. Have you encountered the same problem?

**Comment by xingchun-chen** [comment]
The problem solved by pr：https://github.com/apache/incubator-dolphinscheduler/pull/2420
