### ISSUE TITLE
[BUG]The attachment name in excel Chinese is too long, and the attachment name in the received email becomes a string of characters

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#2359]
The attachment name in excel Chinese is too long, and the attachment name in the received email becomes a string of characters

**Comment by phoenixhadoop** [comment]
Using DS-1.2.1-release

**Comment by dailidong** [comment]
could you give a screenshot?

**Comment by phoenixhadoop** [comment]
the attachement name show as :+1: 
=UTF-8B5q+P5pyI5bmz5Y+w6LS36L2m6LWE5Lqn6L+Y5qy+5pWw5o2uLnhscw===

**Comment by johnnygo920** [comment]
I will fix it.

**Comment by yangyichao-mango** [comment]
> I will fix it.

Hi,
Glad to hear you want to fix this bug.
Can you reproduce this bug and describe it in this issue?
Thx a lot.

**Comment by johnnygo920** [comment]
issue desc:
When the attachment name is Chinese and exceeds a certain length, the attachment name of the message may appear in a garbled code.
![image](https://user-images.githubusercontent.com/61645312/87264517-cab1c880-c4f2-11ea-8499-e95e404919ea.png)
