### ISSUE TITLE
[Feature]Woker can be grouped by user

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#2360]
Woker can be grouped by users to assign a specified set of wokers to a specified user or user group, while the default worker group can be hidden from view after a new woker group is created

**Comment by dailidong** [comment]
good idea

**Comment by dailidong** [comment]
please disscuss it on the mail list, we can disscuss it further

by the way, formal disscussion should happen on the mail list



Best Regards
---------------
DolphinScheduler(Incubator) PPMC
Lidong Dai 代立冬
dailidong66@gmail.com
---------------


dailidong <notifications@github.com> 于2020年4月2日周四 下午3:26写道：

**Comment by dailidong** [comment]
subscribe is easy, please refer :
https://dolphinscheduler.apache.org/en-us/docs/development/subscribe.html


Best Regards
---------------
DolphinScheduler(Incubator) PPMC
Lidong Dai 代立冬
dailidong66@gmail.com
---------------


lidong dai <dailidong66@gmail.com> 于2020年4月2日周四 下午3:44写道：

**Comment by chengshiwen** [comment]
Close by #5122
