### ISSUE TITLE
[BUG] With kerberos enabled Hadoop cluster and dolphinscheduler cluster, woker cannot be authenticated beyond 24 hours

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#2361]
The Hadoop cluster with kerberos enabled, and the dolphinscheduler also has kerberos enabled.
When the dolphinscheduler service was started for more than 24 hours, it became clear that woker was unable to pass kerberos authentication, causing the service to become unavailable. Restart the service and it will return to normal.

**Comment by phoenixhadoop** [comment]
I have depolyed DS-1.2.1-release .
Thanks.

**Comment by zyfjstu** [comment]
common.properties
kerberos.expire.time=1

**Comment by zyfjstu** [comment]
according to ticket_lifetime, modify the following config
 common.properties
 kerberos.expire.time=1



> The Hadoop cluster with kerberos enabled, and the dolphinscheduler also has kerberos enabled.
> When the dolphinscheduler service was started for more than 24 hours, it became clear that woker was unable to pass kerberos authentication, causing the service to become unavailable. Restart the service and it will return to normal.

**Comment by chengshiwen** [comment]
Close the issue since it has been replied
