### ISSUE TITLE
[Question] DS allow to edit a online process in Process Instance(process history)

### ISSUE THREAD

**Issue by lianjie1229** [apache/incubator-dolphinscheduler#2362]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
We will get hint [process xxx not allow to edit],if we edit a online process.But if we edit it's history process instance, it succeed.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. In Process definition,edit a online process,you will get hint [process xx does not allow to edit]
2. In Process Instance,you can edit a online process history instance

**Expected behavior**
A online process does not allow to edit

**Screenshots**

**Which version of Dolphin Scheduler:**
1.1.0

**Additional context**

**Requirement or improvement
please check this is a bug or not

**Comment by dailidong** [comment]
we just design for this,  process definition you You can understand it as process  template. when the template start, it generate a procees instance,  at this time the instance has nothing to do with the template, so you can edit the instance.

maybe you have some ideas,  the discussion should happen in the mail list

**Comment by dailidong** [comment]
subscription email is also very simple, the steps are as follows:

1、Send an email to dev-subscribe@dolphinscheduler.apache.org with your own email address, subject and content.

2、Receive confirmation email and reply. After completing step 1, you will receive a confirmation email from dev-help@dolphinscheduler.apache.org (if not received, please confirm whether the email is automatically classified as spam, promotion email, subscription email, etc.) . Then reply directly to the email, or click on the link in the email to reply quickly, the subject and content are arbitrary.

3、Receive a welcome email. After completing the above steps, you will receive a welcome email with the subject WELCOME to dev@dolphinscheduler.apache.org, and you have successfully subscribed to the Apache DolphinScheduler (Incubating) mailing list.

**Comment by lianjie1229** [comment]
> we just design for this, process definition you You can understand it as process template. when the template start, it generate a procees instance,  at this time the instance has nothing to do with the template, so you can edit the instance.
> 
> maybe you have some ideas, the discussion should happen in the mail list([dev@dolphinscheduler.apache.org](mailto:dev@dolphinscheduler.apache.org),)

so I edit the instance , changes do not affect the template ?
I tested it, changes to the instance will affect the template  too

**Comment by dailidong** [comment]
![image](https://user-images.githubusercontent.com/15833811/78217303-5d070100-74ee-11ea-82dc-8f9a8fcba601.png)

`Whether to update the process definition`   this is an option,  it is selected by default, it means saving the process instance will update the corresponding process definition template.  

And, this discussion should happen in the mail list, could you forward there?

 thx
