### ISSUE TITLE
[BUG] Click on a workflow node that has multiple SQL type nodes, and the SQL edit box displays the contents of the SQL statement that is not the current click node

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#2364]
When A workflow has multiple SQL type nodes, such as node A, node B, and node C. When nodes A, B and C are clicked respectively, then A or B or C is clicked. The Sql statement displayed in the node Sql edit box is not the Sql content of the currently clicked node, for example, the Sql content of node B or node C is displayed when node A is clicked.

**Comment by phoenixhadoop** [comment]
Using DS-1.2.1-release

**Comment by xingchun-chen** [comment]
@break60  +1

**Comment by break60** [comment]
ok
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xingchun-chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 下午2:36
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"数码港"<790061044@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] [BUG] Click on a workflow node that has multiple SQL type nodes, and the SQL edit box displays the contents of the SQL statement that is not the current click node (#2364)





 
@break60  +1

**Comment by phoenixhadoop** [comment]
Is this issue sloved?

**Comment by break60** [comment]
#2366

**Comment by HelesZ** [comment]
Problems still exist in version 1.2.1

**Comment by KEN-LJQ** [comment]
Any progress of this issue?  Kind of easy to overwrite the sql content by mistake

**Comment by chengshiwen** [comment]
Close by #2354 #2366, pls check new version
