### ISSUE TITLE
[QUESTION] frontend message box keep time

### ISSUE THREAD

**Issue by Rubik-W** [apache/incubator-dolphinscheduler#2365]
How to add keep time for message box. Current keep time is lower.
![image](https://user-images.githubusercontent.com/39549317/78233744-c85dcc80-7508-11ea-8a1e-1c6b30c2d8e8.png)

**Comment by dailidong** [comment]
deep discussion on the mail list:  https://lists.apache.org/thread.html/r72c3c97f95e231ba7f89b36042b6e47f5263bce3546b15dbeebd59ff%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by dailidong** [comment]
@break60

**Comment by break60** [comment]
this.$message.success({
content: '这是一条成功提示',
duration: 2,
closable: false
})

**Comment by Rubik-W** [comment]
Can this be modified globally?
All message boxes are Increase keep time.
