### ISSUE TITLE
[BUG] sql node doesn't support muti sql statement

### ISSUE THREAD

**Issue by chenghm** [apache/incubator-dolphinscheduler#2369]
**标题** 
标题格式: [BUG][Major] sql node doesn't support muti sql statement
Priority分为四级: Critical、Major、Minor、Trivial

**问题描述**
[清晰准确描述遇到的问题]
sql节点不支持多条sql语句输入，而且单条sql语句结束不能识别分号
**问题复现步骤:**
1. [第一步]
新建工作流，创建sql节点，在节点中输入多条sql
2. [第二步]
3. [...]

**期望的表现:**
[在这里描述期望的表现]
sql节点能够支持多条sql语句输入，能够识别sql输入结束分号
**观察到的表现:**
[在这里描述观察到的表现]

**屏幕截图和动态GIF图**
![复现步骤的屏幕截图和动态GIF图](图片的url)

<img width="390" alt="无标题1" src="https://user-images.githubusercontent.com/3665396/78972369-2d847400-7b40-11ea-9335-193de5430d67.png">
<img width="929" alt="批注 2020-04-10 151914" src="https://user-images.githubusercontent.com/3665396/78973547-bc928b80-7b42-11ea-9a7f-c0e27a407bfc.png">

**DolphinScheduler版本:(以1.1.0为例)** 
 -[1.2.0]
 
**补充的内容:**
[请描述补充的内容，比如]

**需求或者建议**
[请描述你的需求或者建议]

**Comment by dailidong** [comment]
![image](https://user-images.githubusercontent.com/15833811/78641070-417f6a00-78e3-11ea-83d4-41c516b3a05b.png)
can't see the screenshot,  please upload again,thx

**Comment by chenghm** [comment]
已添加截图

**Comment by tlhhup** [comment]
I think the MainSQL only support a single statement, but you can set more pre/post statements, you can see the relevant code in `SqlTask` class. BTW：i think all of the executions should be in a transaction.

**Comment by CalvinKirs** [comment]
see #3799
