### ISSUE TITLE
运行一段时间后,worker服务无端停止运行,造成任务累积到待执行命令那里，但重启worker就好了。

### ISSUE THREAD

**Issue by knight11111** [apache/incubator-dolphinscheduler#2372]
ds调度正常运行一段时间后，启动工作流之后，任务不执行（简单shell  jps都不行），实例也没有，但是在统计管理待执行命令数那里会显示积压几个任务，而且重启一下worker服务之后，之前没有启动成功的工作流就全部正常显示运行，待执行命令数也归零了。相关属性：

3台机器的启动参数一致如下：
export DOLPHINSCHEDULER_OPTS="-server -Xmx5g -Xms5g -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"

**Comment by dailidong** [comment]
is three worker server all stop work?

By the way, English is needed, you can update/add title/desc in English, thx

**Comment by knight11111** [comment]
yes，All three worker servers are down！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dailidong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午3:18
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"秦健"<352202522@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 运行一段时间后,worker服务无端停止运行,造成任务累积到待执行命令那里，但重启worker就好了。 (#2372)





 
is three worker server all stop work?
 
By the way, English is needed, you can update/add title/desc in English, thx

**Comment by Rubik-W** [comment]
is zk working fine?

**Comment by knight11111** [comment]
ZK should be OK, because I just restart the work server to run normally. and CDH Server is OK。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rubik-W"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午3:38
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"秦健"<352202522@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 运行一段时间后,worker服务无端停止运行,造成任务累积到待执行命令那里，但重启worker就好了。 (#2372)





 
is zk working fine?

**Comment by Rubik-W** [comment]
You can see worker log file. Is there an error log.

**Comment by knight11111** [comment]
At that time, I went to read the work log. The log of work just said that the task has been established
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rubik-W"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午3:58
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"秦健"<352202522@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 运行一段时间后,worker服务无端停止运行,造成任务累积到待执行命令那里，但重启worker就好了。 (#2372)





 
You can see worker log file. Is there an error log.

**Comment by knight11111** [comment]
At that time, I went to see worker log file, and no corresponding log was generated in work


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rubik-W"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 下午3:58
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"秦健"<352202522@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 运行一段时间后,worker服务无端停止运行,造成任务累积到待执行命令那里，但重启worker就好了。 (#2372)





 
You can see worker log file. Is there an error log.

**Comment by chengshiwen** [comment]
Close the issue since no updates for long time
