### ISSUE TITLE
ProcessDefinitionService#updateProcessDefinition,no need to findProcessDefineById 2 times

### ISSUE THREAD

**Issue by itbasketplayer** [apache/incubator-dolphinscheduler#2373]
**Is your feature request related to a problem? Please describe.**
ProcessDefinitionService#updateProcessDefinition method,no need to findProcessDefineById 2 times

**Describe the solution you'd like**
between 2 findProcessDefineById,no time-consuming operations

**Describe alternatives you've considered**
findProcessDefineById 1 time

**Additional context**

**Comment by dailidong** [comment]
welcome to submit a PR to improve the quality of this class

**Comment by itbasketplayer** [comment]
ok,i will submit a PR
