### ISSUE TITLE
[BUG] bug The task instance log shows failure, but the status shows success without alarm

### ISSUE THREAD

**Issue by vortiganL** [apache/incubator-dolphinscheduler#2383]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The task instance log shows failure, but the status shows success without alarm
![image](https://user-images.githubusercontent.com/47095772/78809122-04a59700-79f9-11ea-8caa-31901df92e92.png)
![image](https://user-images.githubusercontent.com/47095772/78809216-269f1980-79f9-11ea-8050-05daca6edd4e.png)

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
which soft dose the first screenshot use ?

**Comment by vortiganL** [comment]
> which soft dose the first screenshot use ?

WeChat, corporate WeChat can be？

**Comment by chengshiwen** [comment]
Close the issue since no updates for long long time
