### ISSUE TITLE
i cannot visit the project  

### ISSUE THREAD

**Issue by JohnBarrowman65** [apache/incubator-dolphinscheduler#2398]
iam a beginner for this project
i download the release1.2.0
**Describe the question**
i run the masterServer,workerServer,apiServerApplication successful,and install the dolphinscheduler-ui is ok, nginx is ok,but i cannot visit the views.  i thinks the apiServerApplicaiton's port is 8080.but the properties is 12345? so i visit the front is 404

**Which version of DolphinScheduler:**
 -[release1.2.0]

**Comment by JohnBarrowman65** [comment]
i see the apiServer's port is 8080 ,i meants the proterties's server.port=12345 doestn't work?

**Comment by samz406** [comment]
![image](https://user-images.githubusercontent.com/3055810/78970947-0d9f8100-7b3d-11ea-9cce-01e9ff10a1f0.png)

like this ,try try

**Comment by JohnBarrowman65** [comment]
> ![image](https://user-images.githubusercontent.com/3055810/78970947-0d9f8100-7b3d-11ea-9cce-01e9ff10a1f0.png)
> 
> like this ,try try

oh,thinks,i try  try first

**Comment by JohnBarrowman65** [comment]
> ![image](https://user-images.githubusercontent.com/3055810/78970947-0d9f8100-7b3d-11ea-9cce-01e9ff10a1f0.png)
> 
> like this ,try try

thinks dalao,i can works

**Comment by samz406** [comment]
have a good time

**Comment by JohnBarrowman65** [comment]
> ![image](https://user-images.githubusercontent.com/3055810/78970947-0d9f8100-7b3d-11ea-9cce-01e9ff10a1f0.png)
> 
> like this ,try try
