### ISSUE TITLE
No process instance after run process

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#2404]
ds: 1.2.0
i deployed an standalone ds in one machine（8 vcores，8G），all services are running，then i defined an shell process, but after i click run button , there is no any instance, no exception in log of master and worker. all properties of them are default.
![image](https://user-images.githubusercontent.com/7474234/79074254-fa97d700-7d1d-11ea-8183-29416fe1eabe.png)

![image](https://user-images.githubusercontent.com/7474234/79074160-69286500-7d1d-11ea-99d2-1ac851af6a17.png)

![image](https://user-images.githubusercontent.com/7474234/79074275-14d1b500-7d1e-11ea-8557-29d17362458e.png)

![image](https://user-images.githubusercontent.com/7474234/79074313-3d59af00-7d1e-11ea-8068-968f36e69ce2.png)

![image](https://user-images.githubusercontent.com/7474234/79074332-57938d00-7d1e-11ea-8ee7-fe71d2116de9.png)

![image](https://user-images.githubusercontent.com/7474234/79074365-814cb400-7d1e-11ea-8cff-ccf8a8599360.png)

**Comment by xingchun-chen** [comment]
Hi JunjianS：


    you can check the table of  t_ds_command whether have data,if it have data, please check master service that is correct run again


陈兴春
长沙测试工程师
+86 15801675490
chenxingchun@analysys.com.cn
长沙公司地址：长沙市岳麓区尖山路39号中电软件园总部三楼，电话：0731-83522068
北京公司地址：北京市朝阳区酒仙桥路10号恒通商务园B12C座三层
易观官网：http://www.analysys.cn/
客服电话：4006-010-230 / 4006-010-231
-----------------------------------
    北京 ｜ 上海 ｜ 深圳 ｜ 成都 ｜ 长沙




 原始邮件 
发件人: JunjianS<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2020年4月13日(周一) 00:25
主题: [apache/incubator-dolphinscheduler] No process instance after runprocess (#2404)


ds: 1.2.0
 i deployed an standalone ds in one machine（8 vcores，8G），all services are running，then i defined an shell process, but after i click run button , there is no any instance, no exception in log of master and worker. all properties of them is default.

**Comment by dailidong** [comment]
if not exception in master/worker log.
then you can check quartz.properties to see the config about database
quartz.properties is under conf dir

**Comment by JunjianS** [comment]
> if not exception in master/worker log.
> then you can check quartz.properties to see the config about database
> quartz.properties is under conf dir

thanks，my fault , i forget to update the port of mysql
