### ISSUE TITLE
Zookeeper进行Master容错后调度任务出现异常

### ISSUE THREAD

**Issue by hebin-swxc** [apache/incubator-dolphinscheduler#2411]
**Zookeeper进行Master容错后调度任务出现异常** 

**问题描述**
Zookeeper进行Master容错后，由于任务设置了重试机制，任务被重复吊起，导致任务异常

**期望的表现:**
Zookeeper进行Master容错后，先判断正在进行的任务状态，再进行任务的处理

**Comment by xingchun-chen** [comment]
Thanks for your feedback.
please update the title in English，thanks!

**Comment by chengshiwen** [comment]
Close by #4840 #5044
