### ISSUE TITLE
NEED HDFS file system and HIVE datasource configuration

### ISSUE THREAD

**Issue by leijrq** [apache/incubator-dolphinscheduler#2436]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.
I want to configure HDFS file system and HIVE datasource in the DS cluster,  would you please someone provide detailed configuration and explain that ? thx so much!

**Which version of DolphinScheduler:**
 -[1.2.0]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by simon824** [comment]
You can find the detailed configuration in the documentation
https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/cluster-deployment.html
![image](https://user-images.githubusercontent.com/18065113/79403886-be38d500-7fc2-11ea-9385-4f262138fe41.png)
