### ISSUE TITLE
when i click the log buttuon,the console throw the exception.....

### ISSUE THREAD

**Issue by JohnBarrowman65** [apache/incubator-dolphinscheduler#2438]
release 1.2.0
ubuntu 18
**Describe the question**
the project is running successful,but when i click the "show log",there is nothing and my console  pint some exception,for help
![image](https://user-images.githubusercontent.com/30208746/79422122-d888a800-7fee-11ea-8fb8-d92db006c91d.png)

**Comment by xingchun-chen** [comment]
did you  start  the logger service

**Comment by JohnBarrowman65** [comment]
> did you start the logger service

i had started the aip,master,worker,which one is logger service

**Comment by JohnBarrowman65** [comment]
> did you start the logger service

oh.i got it...thinks
