### ISSUE TITLE
why thrown the java.sql.SQLException: com.mysql.jdbc.Driver when i start the alterService

### ISSUE THREAD

**Issue by JohnBarrowman65** [apache/incubator-dolphinscheduler#2441]
release 1.2.0
ubuntu
question:
the api,master,worker,logger all start successfule,but when i start the alterServer,the console thrown the "Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver" but i see i had add the mysql dependency in the dao's maven pom as the picture you can see,so ask for the help.
![image](https://user-images.githubusercontent.com/30208746/79427700-adef1d00-7ff7-11ea-9b62-ce9950af07c5.png)

**Comment by qiaozhanwei** [comment]
root pom.xml

<dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql.connector.version}</version>
                <scope>test</scope>
            </dependency>
mysql scope is test，please remove

**Comment by JohnBarrowman65** [comment]
> mysql.connector.version

ok,thx
