### ISSUE TITLE
[BUG] update  the  directory  of resource  is error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2442]
update the  directory occasionally appears the resource file does't exist, and the actual update directory is successful

![image](https://user-images.githubusercontent.com/55787491/79429815-9feecb80-7ffa-11ea-9c00-41e88eed05e9.png)
![image](https://user-images.githubusercontent.com/55787491/79429960-cd3b7980-7ffa-11ea-958e-32cefebfeffe.png)
![image](https://user-images.githubusercontent.com/55787491/79430009-e17f7680-7ffa-11ea-91ea-87c9d91237b1.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by lgcareer** [comment]
I saw the error is `resource not exist`.If need update the resource,It should exist in hdfs.

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/80198738-19b63300-8653-11ea-85d5-30835a9e2f6e.png)

![image](https://user-images.githubusercontent.com/55787491/80198701-0dca7100-8653-11ea-9702-590ebd273408.png)
