### ISSUE TITLE
[BUG] Update resource is not case sensitive  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2443]
Update lowercase letters to uppercase letters which is failed，as shown below

![image](https://user-images.githubusercontent.com/55787491/79435808-b3059980-8002-11ea-8c33-9feadd0d51f1.png)

![image](https://user-images.githubusercontent.com/55787491/79436421-6cfd0580-8003-11ea-927c-168feebdb5e7.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by lgcareer** [comment]
This reason is that the mysql is not case sensitive in the content of a field.

**Comment by xingchun-chen** [comment]
Alarm groups and queue names are not case sensitive

**Comment by zt-1997** [comment]
i will fix it

**Comment by lgcareer** [comment]
Beause in the email thread [1] didn't reache consensus to support case-sensitive,So I think it's better to close this issue.
[1]https://lists.apache.org/thread.html/r723ce0f1b8478db4e461cc32afd75337e5dddb00663a18112a4ef990%40%3Cdev.dolphinscheduler.apache.org%3E
