### ISSUE TITLE
[Feature]support multi queue for tasks other than MR

### ISSUE THREAD

**Issue by duduupup** [apache/incubator-dolphinscheduler#2446]
目前配置的队列，似乎只有MR任务生效（提交yarn上的队列名称），对于其他不依赖于Yarn的任务，能否支持队列？

**Comment by xingchun-chen** [comment]
please update title in english ,thanks

**Comment by chengshiwen** [comment]
Now, spark, flink and mr have supported yarn queue in 1.3.5
