### ISSUE TITLE
[BUG] run hive task , failed to send mail

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2448]
1.run sql-hive task ， Failed to send mail

2.The alert service does not print logs
 
![image](https://user-images.githubusercontent.com/55787491/79537198-5bc00180-80b4-11ea-9680-73446446d758.png)
![image](https://user-images.githubusercontent.com/55787491/79537267-7eeab100-80b4-11ea-8698-17150693024e.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by qiaozhanwei** [comment]
this is not have task or mail  problem , mybe hive udf  problem， I will track this problem

**Comment by xingchun-chen** [comment]
after pulling the dev code again,The problem has not been reproduced
