### ISSUE TITLE
Consulting: Compensatory rerun process(咨询：补数重跑流程)

### ISSUE THREAD

**Issue by lzy305** [apache/incubator-dolphinscheduler#245]
Hello!
   This has a workflow definition. The monthly schedule is adjusted once. Then I run the complement here. I found that I still run by day.

Timer management.
![image](https://user-images.githubusercontent.com/38307479/57067361-5c278700-6d01-11e9-92f3-f3fabfa50343.png)

Workflow parameter definition
![image](https://user-images.githubusercontent.com/38307479/57067418-85e0ae00-6d01-11e9-879c-b7d97543a576.png)

Can we make it easy to explain the flow logic of the complement?

---
您好！
  这个有个工作流定义 每月调度定时调一次. 然后我这边运行 补数. 发现还是按天跑的.

 定时器管理.
![image](https://user-images.githubusercontent.com/38307479/57067361-5c278700-6d01-11e9-92f3-f3fabfa50343.png)

工作流参数定义
![image](https://user-images.githubusercontent.com/38307479/57067418-85e0ae00-6d01-11e9-879c-b7d97543a576.png)

大佬们 能补能方便讲解下补数的流程逻辑？

**Comment by lenboo** [comment]
We are sorry for that situation. Complements are designed to run in the interval of days, where they are run every day and cannot be checked for timing tasks, but we are considering optimizing the design.If you have a better idea, please let use know.

**Comment by lzy305** [comment]
我以前的做法。
 比如补数日期 2018.01.01 ~ 2019.05.04
一.  若工作流设置了定时器. 就要根据定时器去重跑
      1.1 ，若定时器为每月(0 10 8 1 * ? *)   则补数/重跑 时间参数应该为 2018.01.01 08:10:00, 2018.02.01 08:10:00  ...... 2019.05.01 08:10:00
     1.2   若定时器为每日(0 10 8 * * ? *)  则补数/重跑 时间参数应该为2018.01.01 08:10:00，2018.01.02 08:10:00 ， 2018.01.03 08:10:00 。。。。2019.05.04 08:10:00
    1.3  若定时器为每小时(0 10 * * * ? *)   则补数/重跑 时间参数应该为 2018.01.01 00:10:00， 
           2018.01.01 01:10:00  。。。
    1.4 每分钟类似于上面
      但是涉及其他复杂的调度周期频率 目前我也没想好 😅

二.若工作流没有设置定时器 就按目前的  按天补数.

**Comment by yangqinlong** [comment]
我这里也碰到同样的补数问题。 
问下， 是在1.0.3版本里完善这个功能吗

**Comment by lenboo** [comment]
we would do this after version 1.0.3,  because there aren't enough people to do this. 
so we strongly need some people interested in  Easy Scheduler to contribute code.

**Comment by dailidong** [comment]
yes, if who interested in this issue, please leave a message, 
and if nobody want to implement this, we will do it  the next version after 1.0.3!

**Comment by sunnyingit** [comment]
这个补数功能太重要了，建议一种做法，比如补数日期 2018.01.01 ~ 2019.05.04 运行逻辑:

1. 程序判断是否需要补数，如果需要，则把补数时间写入到可以通过$[yymmdd]获取到的变量中
2. 平台通过设置全局变量 DATA=$[yymmdd],则可以拿到补数时间，然后脚本运行的时候，可以通过全局变量获得补数时间，从而调整运行时间

**Comment by xiej23** [comment]
is there any plan for this feature?  i think Supplement Data per hour is important to many users,  or we must run a workflow and wait, then run the next workflow,  for many times.

**Comment by zixi0825** [comment]
I will  implement this feature

**Comment by lzy305** [comment]
@zixi0825   when will we be able to use this feature?

**Comment by zixi0825** [comment]
> @zixi0825 when will we be able to use this feature?
the dev branch has implemented，you can try it
