### ISSUE TITLE
[BUG] cannot complement data for one day

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2450]
cannot complement data for one day.

![image](https://user-images.githubusercontent.com/29528966/79549206-443f4380-80c9-11ea-9ec9-678b65095969.png)

**Comment by xingchun-chen** [comment]
+1

**Comment by xingchun-chen** [comment]
Who wants to fix this problem

**Comment by simon824** [comment]
i will fix it

**Comment by dailidong** [comment]
> i will fix it

very good ，please leave meessage if you meet any problem
