### ISSUE TITLE
dev final state and running state run flag display

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#2451]
![终态](https://user-images.githubusercontent.com/23756105/79553605-51f7c780-80cf-11ea-9a81-1521845c992d.png)
![运行中](https://user-images.githubusercontent.com/23756105/79553611-53c18b00-80cf-11ea-9a04-3349614f0b08.png)

**Comment by qiaozhanwei** [comment]
@break60

**Comment by break60** [comment]
This is already shown, the color may not be obvious

**Comment by qiaozhanwei** [comment]
sorry，I can't see it anyway

**Comment by break60** [comment]
The color has been deepened




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qiaozhanwei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午5:18
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"数码港"<790061044@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] dev final state and running state run flag display (#2451)





 
@break60
