### ISSUE TITLE
[Feature] support more ways of alert

### ISSUE THREAD

**Issue by iture123** [apache/incubator-dolphinscheduler#2454]
Now,the alert module only support email，It is  necessary to support more ways.I strongly recommend DolphinScheduler  have a standard interface 
to help users to realize various alert.the CGI is a good idea, DS callback the CGI  developed by users.

**Comment by gaojun2048** [comment]
You can take a look at https://github.com/apache/incubator-dolphinscheduler/issues/3049

**Comment by CalvinKirs** [comment]
please see #3049
