### ISSUE TITLE
why don't support ding ding ？need more alert way

### ISSUE THREAD

**Issue by pysenic** [apache/incubator-dolphinscheduler#2458]
i find the enterprise wechat，but we use ding'ding，please support this in the future，thank

**Comment by stanfen** [comment]
support ding ding group is in developing. will be pr.

**Comment by pysenic** [comment]
nice

**Comment by JinyLeeChina** [comment]
Support dingtalk need add  taobao-sdk-java-auto.jar, this involves the issue of license. I have this feature code,  if you need,please contact me
