### ISSUE TITLE
[BUG] the output file which made by task instance will not be deleted when we try to delete the process instance

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/incubator-dolphinscheduler#2463]
the output file under the log folder which made by task  instance will not be deleted when we try to delete the process instance on the webpage

![image](https://user-images.githubusercontent.com/62231347/79689507-eb69d980-8287-11ea-9038-13e8727f33a4.png)

process_definition_id：6
process_instance_id：90
process_instance_id：93

we hava deleted the process_instance of 90 ，but the output log file remained, not be deleted together.

**Comment by chengshiwen** [comment]
Close by #2693
