### ISSUE TITLE
[BUG] The master cannot get the latest registration form of the worker

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2468]
1. set  worker Configuration  : worker.group=worker_group_188
2.start worker service，the worker group in zk is worker_group_188 ,as shown below:

![image](https://user-images.githubusercontent.com/55787491/79728525-a3e35c00-8320-11ea-930a-2fd67a5910cc.png)

3. kill the worker service, and modify worker Configuration : #worker.group=default 
4.restart the worker service, worker_group_188 wasn't deleted ,as shown below:

![image](https://user-images.githubusercontent.com/55787491/79729372-f5d8b180-8321-11ea-8329-bd434aa1cefb.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by qiaozhanwei** [comment]
This is normal，worker down，only offlie worker ， not delete worker group，this is no affect ui set worker group

**Comment by xingchun-chen** [comment]
After switching the worker configuration, running the workflow master reports an error and cannot connect to the worker
![image](https://user-images.githubusercontent.com/55787491/79733269-6c2be280-8327-11ea-935a-c63d484d0b47.png)
