### ISSUE TITLE
[BUG] The professional vocabulary is misspelled 

### ISSUE THREAD

**Issue by iture123** [apache/incubator-dolphinscheduler#2478]
The professional vocabulary is misspelled on the Official website of dolphinscheduler.For example, MySQL is written as Mysql,ZooKeeper is writtern as zookeeper.
![image](https://user-images.githubusercontent.com/12154864/79764414-e96f4b80-8357-11ea-8650-de5901b6e6ba.png)

**Comment by dailidong** [comment]
good job,  please submit a PR to solve this problem

**Comment by dailidong** [comment]
add the official website github url : https://github.com/apache/incubator-dolphinscheduler-website

**Comment by dailidong** [comment]
if you want to submit a PR for this issue, please leave a message, welcome to fix this problem

**Comment by heyzeng** [comment]
Has anyone fixed this bug? If not, can I submit this PR?

**Comment by dailidong** [comment]
> Has anyone fixed this bug? If not, can I submit this PR?

next time if nobody reponse in time(one or two days), then you can submit a PR , haha
