### ISSUE TITLE
[BUG] the Mysql needs to configure with“allowMultiQueries = true”,

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2481]
1.Since MYSQL does not support batch upload, the data source needs to be configured with“allowMultiQueries = true”, otherwise an error will be occurred when deleting resource files。mysql configuration is as follows：
spring.datasource.url=jdbc:mysql://192.168.xx.xx:3306/dolphinscheduler?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

2.It is recommended to change the database name to configurable

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by xingchun-chen** [comment]
Since MYSQL does not support batch upload, the data source needs to be configured with“allowMultiQueries = true”, otherwise an error will be occurred when deleting resource files。mysql configuration is as follows：
spring.datasource.url=jdbc:mysql://192.168.xx.xx:3306/dolphinscheduler_1.3.0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

**Comment by xingchun-chen** [comment]
need to & replace to \&

**Comment by dailidong** [comment]
it may affect install_config.conf and install.sh , who want to fix it ? please leave a message

**Comment by dailidong** [comment]
Hi,
 this issue is open to the community to fix. If anyone who wants to try, please comment on this ISSUE and I will assign it to you.  :)

**Comment by simon824** [comment]
I will fix it

**Comment by xingchun-chen** [comment]
How is this issue going
