### ISSUE TITLE
[BUG] The zookeeper.quorum configuration in install.sh is error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2484]
sed -i ${txt} "s#zookeeper.quorum.*#zookeeper.quorum=${zkQuorum}#g" conf/common.properties

conf/common.properties should be changed to conf/zookeeper.properties

![image](https://user-images.githubusercontent.com/55787491/79832764-b327df80-83dc-11ea-95ad-d2591eb886f2.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
This issue is open to the community to fix. If anyone wants to try, please comment on this ISSUE and I will assign it to you. :)

**Comment by zixi0825** [comment]
I will fix it
