### ISSUE TITLE
[BUG] The time display on web interface and database is inconsistent

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/incubator-dolphinscheduler#2485]
process_instance： schedule_time、start_time、end_time
task_instance：submit_time、start_time、end_time

![image](https://user-images.githubusercontent.com/62231347/79850265-399ceb00-83f6-11ea-8544-8f7df8a79f9a.png)

**Comment by JoshuaZhuCN** [comment]
![image](https://user-images.githubusercontent.com/62231347/79849992-d90dae00-83f5-11ea-9107-488aff55692e.png)

**Comment by xingchun-chen** [comment]
This problem is caused by the database time zone. You can change the database time zone configuration or add the configuration when connecting to the database & serverTimezone = Asia / Shanghai

**Comment by JoshuaZhuCN** [comment]
> This problem is caused by the database time zone. You can change the database time zone configuration or add the configuration when connecting to the database & serverTimezone = Asia / Shanghai
> ![image](https://user-images.githubusercontent.com/55787491/79851589-1d01b280-83f8-11ea-9006-4deea92b9396.png)
> 
> ![image](https://user-images.githubusercontent.com/55787491/79851560-12471d80-83f8-11ea-990d-7cafce4db526.png)

resolved，thx
