### ISSUE TITLE
[BUG] sh stop-all.sh,  the master service is not killed  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2492]
1. sh stop-all.sh
2. Check the master service，the master service is not killed  
 

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
I think the startup script dolphinscheduler-daemon.sh , 
these two lines :
```
    nohup $JAVA_HOME/bin/java $exec_command > $log 2>&1 &
    echo $! > $pid
```
It may be that the pid is not written into the pid file

**Comment by dailidong** [comment]
if you want to submit a PR for this issue, please leave a message, welcome to fix this problem

**Comment by muzhongjiang** [comment]
I will  fix it
