### ISSUE TITLE
[QUESTION] the zookeeper connection and session time is too short

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#2494]
the zookeeper connection and session time is too short, the default value is 300ms,  it will lead the master/worker shutdown if the network latency or the server is busy

I think 1 minutes will be better

![image](https://user-images.githubusercontent.com/15833811/79947879-593f1c80-84a5-11ea-9815-68789b260a25.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by dailidong** [comment]
I see dev branch has changed the session timeout value to 600000.
and I think the zookeeper.connection.timeout=300 in zookeeper.properties is also too short,
I suggest: 
#zookeeper.connection.timeout=30000

**Comment by dailidong** [comment]
if you want to submit a PR for this issue, please leave a message,  welcome to fix this problem

**Comment by oceanos** [comment]
i will fix it
