### ISSUE TITLE
[BUG]The task is in progress, the master and worker hang up , start the master and worker again, the process instance and task are not fault-tolerant

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2499]
1.The task is in progress
2. Worker hangs first, then hangs master
3.start the master and worker again, the process instance and task are not fault-tolerant,Status has been in progress
 

![image](https://user-images.githubusercontent.com/55787491/80054593-3e76b180-8552-11ea-9779-b243169b6e44.png)

![image](https://user-images.githubusercontent.com/55787491/80054556-299a1e00-8552-11ea-998c-9696719264a4.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by kylozw** [comment]
the same in version 1.2.1

**Comment by xingchun-chen** [comment]
The problem was reproduced again:
1. Run the workflow
2.stop master service
3.stop worker service
4.start worker service
5.start master service

There are 2 situations in the above steps:
1. The workflow is fault-tolerant and 2 task instances are generated
2. The workflow is not fault-tolerant, the workflow and tasks are always running
