### ISSUE TITLE
ambari plugin（ambari插件）

### ISSUE THREAD

**Issue by boandai** [apache/incubator-dolphinscheduler#250]

**Comment by dailidong** [comment]
Duplicate of #1469

**Comment by gaojun2048** [comment]
@dailidong  
After the development of the ambari plugin is complete, we need a file server to place the dolphinscheduler rpm packages. Users of the dolphinscheduler can add the dolphinscheduler rpm package to their own yum repo, and then can use the ambari plugin to install the dolphinscheduler.
