### ISSUE TITLE
[Feature] more user permission settings

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/incubator-dolphinscheduler#2508]
基于现在的权限状态下：
1、需增加一个查看权限
2、新增、修改为一组，删除、上线、执行各单独一组
3、查看权限只对已授权的项目有效，同时默认开放监控中心界面，对于资源中心目前由于没分类，不大好说是否默认开放

目前想到的就这些，基于想把工作流的新建任务下放给开发，但是现在的权限比较大，授权了项目后整个项目增删改和运行都能操作，有风险

Based on the current permission status:
1. Need to add a view permission
2. Add, modify as a group, delete, launch and execute as a separate group
3. The view permission is only valid for authorized items, and the monitoring center interface is opened by default. It's hard to say whether it's open by default for the resource center has no classification at present

At present, I think of all these. I want to delegate the new task of workflow to development, but now I have a relatively large authority. After I authorize the project, the whole project can be added, deleted, modified and operated, which is risky

**Comment by break60** [comment]
Good suggestion, at present we are also considering the design of ds permissions

**Comment by CalvinKirs** [comment]
please see #1333
Focus on #1333 discussion
