### ISSUE TITLE
How to Publish new job

### ISSUE THREAD

**Issue by ZhangchengHu0923** [apache/incubator-dolphinscheduler#2509]
If I have created a new job in DEV, and tested it in QA, how do I publish it to PROD，must I create the Job manually? Is there a more reliable way to do this ?

**Comment by ZhangchengHu0923** [comment]
If I have created a new job in DEV, and tested it in QA, how do I publish it to PROD，must I create the Job manually in PROD? Is there a  more reliable way to do this ?

**Comment by dailidong** [comment]
are DEV、QA and PROD on different DS cluster?

**Comment by ZhangchengHu0923** [comment]
What is the DS cluster you said, dolphinScheduler? I have planed to deploy different dolphinScheduler in DEV\QA\PRO,Is this the right way to use it?
if not, could u please tell me the best practice
if it is, how to publish the new job

**Comment by dailidong** [comment]
yes, I means different DolphinScheduler cluster

for now,  in different Cluster, you  can create the Job manually, or can try Process Definition export/import

**Comment by ZhangchengHu0923** [comment]
ok, thanks for ur advice

**Comment by chengshiwen** [comment]
Close the question since it has been replied
