### ISSUE TITLE
[BUG] The working flow direction between nodes is not in the direction specified by the arrow

### ISSUE THREAD

**Issue by 1445103710** [apache/incubator-dolphinscheduler#2513]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The working flow direction between nodes is not in the direction specified by the arrow
**To Reproduce**
Steps to reproduce the behavior, for example:

![image](https://user-images.githubusercontent.com/42244568/80182190-e8c90480-8638-11ea-9ac7-09f7987b880e.png)
![image](https://user-images.githubusercontent.com/42244568/80182223-00a08880-8639-11ea-9a59-abee105207ea.png)
![image](https://user-images.githubusercontent.com/42244568/80182288-29288280-8639-11ea-8907-922b9efa6072.png)
![image](https://user-images.githubusercontent.com/42244568/80182321-35144480-8639-11ea-8934-dfffe3fc71e0.png)

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
I'm sorry I can't understand the problem

**Comment by 1445103710** [comment]
> I'm sorry I can't understand the problem

![image](https://user-images.githubusercontent.com/42244568/80186856-406b6e00-8641-11ea-951b-5e1046268e59.png)
in dev
我想从第一个节点开始运行，向后执行，按照流程应该再执行后面2，3两个节点，但是在运行实例中可以看到，此次运行只运行了第一个节点。
I want to start from the first node and execute backward. According to the process, I should execute the next 2 or 3 nodes. However, in the running instance, we can see that this running only runs the first node.

**Comment by 1445103710** [comment]
look this dag
![image](https://user-images.githubusercontent.com/42244568/80187630-8aa11f00-8642-11ea-8048-708a8c0fd421.png)
Why mysql can be the first to execute？
![image](https://user-images.githubusercontent.com/42244568/80187869-f1263d00-8642-11ea-9880-4565a2ac2780.png)

**Comment by 1445103710** [comment]
@dailidong

**Comment by 1445103710** [comment]
```json
{
	"globalParams": [{
		"prop": "yaoyao",
		"direct": "IN",
		"type": "VARCHAR",
		"value": "111"
	}],
	"tasks": [{
		"type": "SHELL",
		"id": "tasks-79944",
		"name": "测试shell命令",
		"params": {
			"resourceList": [],
			"localParams": [],
			"rawScript": "echo 1111"
		},
		"description": "",
		"runFlag": "NORMAL",
		"conditionResult": {
			"successNode": [""],
			"failedNode": [""]
		},
		"dependence": {},
		"maxRetryTimes": "0",
		"retryInterval": "1",
		"timeout": {
			"strategy": "",
			"interval": null,
			"enable": false
		},
		"taskInstancePriority": "MEDIUM",
		"workerGroup": "default",
		"preTasks": []
	}, {
		"type": "PYTHON",
		"id": "tasks-20302",
		"name": "测试python",
		"params": {
			"resourceList": [],
			"localParams": [],
			"rawScript": "print(222)"
		},
		"description": "",
		"runFlag": "NORMAL",
		"conditionResult": {
			"successNode": [""],
			"failedNode": [""]
		},
		"dependence": {},
		"maxRetryTimes": "0",
		"retryInterval": "1",
		"timeout": {
			"strategy": "",
			"interval": null,
			"enable": false
		},
		"taskInstancePriority": "MEDIUM",
		"workerGroup": "default",
		"preTasks": ["测试shell命令"]
	}, {
		"type": "HTTP",
		"id": "tasks-23734",
		"name": "测试http",
		"params": {
			"localParams": [],
			"httpParams": [],
			"url": "http://www.baidu.com",
			"httpMethod": "GET",
			"httpCheckCondition": "STATUS_CODE_DEFAULT",
			"condition": ""
		},
		"description": "",
		"runFlag": "NORMAL",
		"conditionResult": {
			"successNode": [""],
			"failedNode": [""]
		},
		"dependence": {},
		"maxRetryTimes": "0",
		"retryInterval": "1",
		"timeout": {
			"strategy": "",
			"interval": null,
			"enable": false
		},
		"taskInstancePriority": "MEDIUM",
		"workerGroup": "default",
		"preTasks": ["测试python"]
	}, {
		"type": "SHELL",
		"id": "tasks-36312",
		"name": "打印图形",
		"params": {
			"resourceList": [{
				"id": 2,
				"name": "three.sh",
				"res": "test/three.sh"
			}],
			"localParams": [],
			"rawScript": "sh test/three.sh"
		},
		"description": "",
		"runFlag": "NORMAL",
		"conditionResult": {
			"successNode": [""],
			"failedNode": [""]
		},
		"dependence": {},
		"maxRetryTimes": "0",
		"retryInterval": "1",
		"timeout": {
			"strategy": "",
			"interval": null,
			"enable": false
		},
		"taskInstancePriority": "MEDIUM",
		"workerGroup": "default",
		"preTasks": ["测试http"]
	}, {
		"type": "SQL",
		"id": "tasks-90358",
		"name": "mysql",
		"params": {
			"type": "MYSQL",
			"datasource": 2,
			"sql": "select * from market_gold LIMIT 1",
			"udfs": "",
			"sqlType": "0",
			"title": "111",
			"receivers": "yaoyao@tydic.com",
			"receiversCc": "",
			"showType": "TABLE",
			"localParams": [],
			"connParams": "",
			"preStatements": [],
			"postStatements": []
		},
		"description": "",
		"runFlag": "NORMAL",
		"conditionResult": {
			"successNode": [""],
			"failedNode": [""]
		},
		"dependence": {},
		"maxRetryTimes": "0",
		"retryInterval": "1",
		"timeout": {
			"strategy": "",
			"interval": null,
			"enable": false
		},
		"taskInstancePriority": "MEDIUM",
		"workerGroup": "default",
		"preTasks": []
	}],
	"tenantId": 1,
	"timeout": 0
}
```

we can see ,when we save Dag the mysql  preTasks is empty.

**Comment by dailidong** [comment]
sorry for reply late
https://github.com/apache/incubator-dolphinscheduler/issues/3058 show the detail info 
and PR  https://github.com/apache/incubator-dolphinscheduler/pull/3484 solved this problem 

BTW ,   DolphinScheduler version >= 1.3.2 solved this issue
