### ISSUE TITLE
[BUG] When double-clicking two sql execution tasks alternately for editing, the sql statement will display an error

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2515]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
When double-clicking two sql execution tasks alternately for editing, the sql statement will display an error.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create workflow
2. Then create two sql scheduling tasks in succession（eq. one is create table sql, and other is insert sql）
3. Save&quit the workflow
4. Edit the two sql scheduling tasks alternately, this time you will find an error when displaying the statement

**Expected behavior**
no

**Screenshots**
1. Create the first sql task
![image](https://user-images.githubusercontent.com/10054719/80185982-de5e3900-863f-11ea-920a-5a5f25da0da5.png)
2. create the second sql task
![image](https://user-images.githubusercontent.com/10054719/80186081-051c6f80-8640-11ea-9ad3-84705b7f5225.png)
3. create connect
![image](https://user-images.githubusercontent.com/10054719/80186119-149bb880-8640-11ea-97f7-d0d1a08d3c8f.png)
4.Edit after saving
![image](https://user-images.githubusercontent.com/10054719/80186215-3b59ef00-8640-11ea-8a1f-926c750ccb8a.png)
5. Click two sql tasks alternately， then and look the error!
![image](https://user-images.githubusercontent.com/10054719/80186427-8e33a680-8640-11ea-86a6-b31e6a08644a.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Additional context**
no

**Requirement or improvement
- Should be a front-end bug

**Comment by dailidong** [comment]
good issue， thanks for your report

@break60

**Comment by break60** [comment]
#2366

**Comment by xingchun-chen** [comment]
it has been resolved in dev_1.3.0
