### ISSUE TITLE
[BUG] worker_group is not configurable in conf/config/install_config.conf

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2517]
Currently worker_group is not configurable in conf/config/install_config.conf，Need to be manually configured in worker.properties
![image](https://user-images.githubusercontent.com/55787491/80188331-97724280-8643-11ea-8293-e860d3782537.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
#2746 has solved
