### ISSUE TITLE
[Feature] Add static code test/code style to codebase

### ISSUE THREAD

**Issue by zhongjiajie** [apache/incubator-dolphinscheduler#2520]
**Is your feature request related to a problem? Please describe.**

In PR https://github.com/apache/incubator-dolphinscheduler/pull/2363#discussion_r415080037 I found out we do not had static code/code style check to our codebase, I think we should add some static test to avoid regression. WDYT

**Comment by zhongjiajie** [comment]
Related mail-list https://lists.apache.org/thread.html/r348ce4f6e11924defc11668b8799cd26a893f290890652888b4d33dc%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by dailidong** [comment]
good job
we will use the code style on dev branch when we merged  PR that has already submitted.

**Comment by dailidong** [comment]
for new PR，please configure the checkstyle.xml and codestyle plugin to your ide. It will help to format the code.
[1] https://github.com/apache/incubator-dolphinscheduler/blob/dev/style/checkstyle.xml
[2] https://github.com/apache/incubator-dolphinscheduler/blob/dev/style/intellij-java-code-style.xml
