### ISSUE TITLE
process instance cannot show after create a process definition

### ISSUE THREAD

**Issue by GSHF** [apache/incubator-dolphinscheduler#2521]
process instance cannot show after create a process definition

**Comment by GSHF** [comment]
![image](https://user-images.githubusercontent.com/38513540/80294865-08c70800-87a0-11ea-99bd-0b42bb6ce76c.png)
![image](https://user-images.githubusercontent.com/38513540/80294870-0ebce900-87a0-11ea-9c8a-4867a90cc6ae.png)

**Comment by GSHF** [comment]
![image](https://user-images.githubusercontent.com/38513540/80294886-2bf1b780-87a0-11ea-8a6f-d9b110cef242.png)
![image](https://user-images.githubusercontent.com/38513540/80294892-357b1f80-87a0-11ea-8d36-ea90eee91da2.png)

**Comment by GSHF** [comment]
![image](https://user-images.githubusercontent.com/38513540/80294923-8428b980-87a0-11ea-907c-6f6348aa2a31.png)

**Comment by GSHF** [comment]
please help me

**Comment by samz406** [comment]
It should be that you have not set the timing，
1) click here, set time
<img width="539" alt="WX20200426-100511@2x" src="https://user-images.githubusercontent.com/3055810/80295493-9bb67100-87a5-11ea-88b8-1082305784ed.png">
2) click here.  to schedule time page
<img width="613" alt="WX20200426-100535@2x" src="https://user-images.githubusercontent.com/3055810/80295509-bc7ec680-87a5-11ea-9562-5bac8ee95584.png">

3) click online

<img width="1570" alt="WX20200426-100603@2x" src="https://user-images.githubusercontent.com/3055810/80295521-dddfb280-87a5-11ea-83f1-0a43ab841e09.png">
