### ISSUE TITLE
[BUG] sql task node failed to run

### ISSUE THREAD

**Issue by break60** [apache/incubator-dolphinscheduler#2526]
![image](https://user-images.githubusercontent.com/55787491/80299661-b9e19880-87c8-11ea-8410-98d1b78a6944.png)
![image](https://user-images.githubusercontent.com/55787491/80299666-cb2aa500-87c8-11ea-8e43-1db209a8f0c1.png)

**Comment by lgcareer** [comment]
Hi,I can't open the image.

**Comment by lgcareer** [comment]
If you can give more detail message,Such as the sql task node config,I run the sql task node the status is success

**Comment by tlhhup** [comment]
I think this problem is cause by AlertService, maybe it will be change future. FYI：[[QUESTION] whether sql task state need to bind mail sending result？](https://github.com/apache/incubator-dolphinscheduler/issues/2590.)
