### ISSUE TITLE
no workflow instance create,when run a workflow manually

### ISSUE THREAD

**Issue by ZhangchengHu0923** [apache/incubator-dolphinscheduler#2528]
I deployed a DS Cluster minuts before, I ran a workflow manually and got a "Success" message, but I can't find anything in WorkFlow instace Tab,and the report showed no task had been submitted.
what's the problem could be

**Which version of DolphinScheduler:**
1.2.0

**Additional context**

The simplest workflow I defined
![image](https://user-images.githubusercontent.com/10529123/80301282-cf10f400-87d5-11ea-869b-55a1bfd26523.png)

set the task online and run it, I got "success" msg
![image](https://user-images.githubusercontent.com/10529123/80301271-bf91ab00-87d5-11ea-9667-a3f12c129a48.png)

but there is nothing in workflow instance Tab
![image](https://user-images.githubusercontent.com/10529123/80301347-3af35c80-87d6-11ea-91c1-7195d373a29b.png)

and I haved checked the log,I got these Errors,dose it mater
![image](https://user-images.githubusercontent.com/10529123/80301482-0c29b600-87d7-11ea-9449-a2936435bc20.png)

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ZhangchengHu0923** [comment]
the repoort shows that no task has been submitted
![image](https://user-images.githubusercontent.com/10529123/80301578-7d696900-87d7-11ea-9201-582e7d75ad1f.png)

**Comment by break60** [comment]
Please check the master service and worker service logs

**Comment by samz406** [comment]
1 use command jps ，check if there are 5 processes
```
10517 MasterServer
10550 WorkerServer
10583 LoggerServer
10616 AlertServer
10649 ApiApplicationServer
```
2 if exist , please check Master and  Worker log，does it contain the following logs?

`[WARN] 2020-04-19 22:45:53.462 org.apache.dolphinscheduler.common.utils.OSUtils:[295] - load or availablePhysicalMemorySize(G) is too high, it's availablePhysicalMemorySize(G):0.98,loadAvg:0.05`

3 if contains the log, that is server not enough memory or CPU,you can modify configuration
the file dir  bin/dolphinscheduler-daemon.sh
modify param  -Xmx and -Xms

`export DOLPHINSCHEDULER_OPTS="-server -Xmx300m -Xms100m -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"`

**Comment by ZhangchengHu0923** [comment]
thank u guys,
the problem is solved after I reconfig DOLPHINSCHEDULER_OPTS as:
export DOLPHINSCHEDULER_OPTS="-server -Xmx300m -Xms100m -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"

**Comment by samz406** [comment]
> thank u guys,
> the problem is solved after I reconfig DOLPHINSCHEDULER_OPTS as:
> export DOLPHINSCHEDULER_OPTS="-server -Xmx300m -Xms100m -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"

the param  -server -Xmx300m -Xms100m is my local test environment configuration, you need to allocate memory according to the actual situation
