### ISSUE TITLE
why task instance is null

### ISSUE THREAD

**Issue by liucf915** [apache/incubator-dolphinscheduler#2529]
**Describe the question**
I have a workflow that is executed once every hour. Some tasks started at the time node cannot be completed normally and have been running all the time. The worker log finds errors:【[ERROR] 2020-04-26 13:10:03.627 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 245 】

**version1.2.0 of DolphinScheduler:**

**dolphinscheduler-master.log**
[INFO] 2020-04-26 13:10:03.269 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerThread:[114] - find one command: id: 68, type: SCHEDULER
[INFO] 2020-04-26 13:10:03.461 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerThread:[119] - start master exec thread , split DAG ...
[INFO] 2020-04-26 13:10:03.465 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[296] - prepare process :158 end
[INFO] 2020-04-26 13:10:03.468 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[792] - add task to stand by list: sparkPi
[INFO] 2020-04-26 13:10:03.468 org.apache.dolphinscheduler.common.queue.TaskQueueFactory:[45] - task queue impl use zookeeper 
[INFO] 2020-04-26 13:10:03.468 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[801] - remove task from stand by list: sparkPi
[INFO] 2020-04-26 13:10:03.470 org.apache.dolphinscheduler.dao.ProcessDao:[769] - start submit task : sparkPi, instance id:158, state: RUNNING_EXEUTION, 
[INFO] 2020-04-26 13:10:03.474 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[99] - check task:2_158_2_0_-1 not exist in task queue
[INFO] 2020-04-26 13:10:03.628 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[99] - check task:2_158_2_245_-1 not exist in task queue
[INFO] 2020-04-26 13:10:03.628 org.apache.dolphinscheduler.dao.ProcessDao:[973] - task ready to queue: TaskInstance{id=245, name='sparkPi', taskType='SHELL', processDefinitionId=9, processInstanceId=158, processInstanceName='null', taskJson='{"depList":[],"dependence":"{}","forbidden":false,"id":"tasks-36923","maxRetryTimes":0,"name":"sparkPi","params":"{\"rawScript\":\"sshpass -p  hadoop ssh -o StrictHostKeyChecking=no hadoop@192.168.12.59 \\\"sh /data/hadoop/liucf/dsTest/sparkPi.sh\\\"\",\"localParams\":[],\"resourceList\":[]}","preTasks":"[]","retryInterval":1,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":false,"interval":0},"timeout":"{\"enable\":false,\"strategy\":\"\"}","type":"SHELL","workerGroupId":-1}', state=SUBMITTED_SUCCESS, submitTime=Sun Apr 26 13:10:03 CST 2020, startTime=Sun Apr 26 13:10:03 CST 2020, endTime=null, host='null', executePath='null', logPath='null', retryTimes=0, alertFlag=NO, flag=YES, processInstance=null, processDefine=null, pid=0, appLink='null', flag=YES, dependency=null, duration=null, maxRetryTimes=0, retryInterval=1, taskInstancePriority=MEDIUM, processInstancePriority=MEDIUM, workGroupId=-1}
[INFO] 2020-04-26 13:10:03.628 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[126] - add task : /dolphinscheduler/tasks_queue/2_158_2_245_-1 to tasks queue , result success
[INFO] 2020-04-26 13:10:03.628 org.apache.dolphinscheduler.dao.ProcessDao:[975] - master insert into queue success, task : sparkPi
[INFO] 2020-04-26 13:10:03.629 org.apache.dolphinscheduler.dao.ProcessDao:[786] - submit task :sparkPi state:SUBMITTED_SUCCESS complete, instance id:158 state: RUNNING_EXEUTION 

**dolphinscheduler-worker.log**
[INFO] 2020-04-26 13:10:03.607 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[211] - consume tasks: [2_158_2_245_-1],there still have 0 tasks need to be executed
[ERROR] 2020-04-26 13:10:03.627 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 245 
[WARN] 2020-04-26 13:10:03.627 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[188] - remove task queue : 2_158_2_245_-1 due to taskInstance is null
[INFO] 2020-04-26 13:10:03.627 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[278] - consume task /dolphinscheduler/tasks_queue/2_158_2_245_-1

**Workflow instance screenshot**

![1587890842(1)](https://user-images.githubusercontent.com/51871547/80302626-b1478d00-87dd-11ea-97d4-08aa2244a6d0.jpg)
What is the cause of this? How to avoid it?

**Comment by dailidong** [comment]
@lenboo ，please answer  this issue

**Comment by lenboo** [comment]
It may be similar to this problem
#1477

**Comment by liucf915** [comment]
After reading it, I think so

**Comment by lenboo** [comment]
some tips for this situation：
1. clear the task queue in zk for path: /dolphinscheduler/task_queue
2. change the state of the task to failed( integer value: 6).
3.  run the work flow by recover from failed

**Comment by liucf915** [comment]
Thank you very much.

**Comment by glz-java** [comment]
If you solve this problem manually, it is not ideal, because it is not applicable to solve the problem manually through timed tasks

**Comment by samz406** [comment]
> If you solve this problem manually, it is not ideal, because it is not applicable to solve the problem manually through timed tasks

1.2.1 solved this problem，you can upgrade to latest

**Comment by glz-java** [comment]
> > If you solve this problem manually, it is not ideal, because it is not applicable to solve the problem manually through timed tasks
> 
> 1.2.1 solved this problem，you can upgrade to latest

OK, thank you
