### ISSUE TITLE
[BUG] WorkFlow can be changed when it is Online

### ISSUE THREAD

**Issue by ZhangchengHu0923** [apache/incubator-dolphinscheduler#2532]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
when the workflow is online, I can edit it in "Workflow Instance" Tab

**To Reproduce**
Steps to reproduce the behavior, for example:
1. create a workflow and set it online

2. run the workflow manually

3. open the workflow instance, and edit the task of which
![image](https://user-images.githubusercontent.com/10529123/80305029-c841ab80-87ec-11ea-8c4e-00264d22e49c.png)

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
1.2.0

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by qiaozhanwei** [comment]
1，Process Definition is onlie , can't modify
2，Process Definition according to Process Instance can modify ,Note，save  Process Instance modify have a check button， default modify Process Instance can modify Process Definition JSON，

**Comment by ZhangchengHu0923** [comment]
got it, thx

**Comment by ZhangchengHu0923** [comment]
but why can't I modify it in "Workflow Definition" Tab, what it is online

![image](https://user-images.githubusercontent.com/10529123/80305554-f674ba80-87ef-11ea-93db-bad6af667c13.png)

**Comment by ZhangchengHu0923** [comment]
if the modification is legal, I think it should be allowed in "Workflow definition" Tab, but not “Workflow intance” Tab.

**Comment by qiaozhanwei** [comment]
1，online represents a kind of lock. For example, if a process definition is online, he can add a timer. If it is online, you can modify the process definition at will, do you think it is good?

2.  process instance, you run the process instance, for example, if the process instance has a problem, you can modify it. It can be synchronized to the process or not synchronized to the process definition.

1，上线就是代表了一种锁，比如说一个流程定义处于上线状态，他才能加定时，如果要是上线状态，你随意对流程定义修改，你觉得好么？
2，对于流程实例，你跑完的流程实例，比如说你流程实例跑的有问题，你可以修改哈，他可以同步到流程定，也可以不同步到流程定义

**Comment by ZhangchengHu0923** [comment]
got it, the designment is good, thanks 4 ur explaination, and I have an advice,
the Save button here is confusing, new users won't know meaning of it, we can provide a clearer info here, just like "sync modification to workflow Definition"
![image](https://user-images.githubusercontent.com/10529123/80329227-3d0bf880-8874-11ea-81a3-fda4bc0820b8.png)

懂了，这个设计挺棒的，多谢您的解释。我有个建议，这里的 “保存” 按钮意思容易混淆，新用户估计不会知道它的作用，我们可以在这里提供更清晰的信息，比如“将修改同步到工作流定义”，甚至可以加个alert弹窗提确认一下，毕竟这个修改影响还是挺大的。
