### ISSUE TITLE
[dev branch]   Use docker-compose for deployment .   Failed to execute python script(使用docker-compose部署，执行python脚本错误,所使用的docker-compose文件在swarm目录下)

### ISSUE THREAD

**Issue by gumupaier** [apache/incubator-dolphinscheduler#2533]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
start command:
docker-compose up -d

description:

Failed to execute python script

the log show 

 sudo: /opt/soft/python: command not found

However, I have changed the dolphinscheduler_env.sh file

`export HADOOP_HOME=/opt/soft/hadoop
export HADOOP_CONF_DIR=/opt/soft/hadoop/etc/hadoop
export SPARK_HOME1=/opt/soft/spark1
export SPARK_HOME2=/opt/soft/spark2
export PYTHON_HOME=/usr/bin/python
export JAVA_HOME=/opt/soft/java
export HIVE_HOME=/opt/soft/hive
export FLINK_HOME=/opt/soft/flink
export PATH=$HADOOP_HOME/bin:$SPARK_HOME1/bin:$SPARK_HOME2/bin:$PYTHON_HOME:$JAVA_HOME/bin:$HIVE_HOME/bin:$FLINK_HOME/bin:$PATH`

*Screenshots**
![image](https://user-images.githubusercontent.com/37896380/80326017-05984e80-886a-11ea-8015-b843c7979584.png)

**Requirement or improvement
Even better, the built-in python version of the container is python3

Hard you

**Comment by gumupaier** [comment]
![image](https://user-images.githubusercontent.com/37896380/80326171-79d2f200-886a-11ea-8aa1-a14b70bf5df2.png)

**Comment by gumupaier** [comment]
@liwenhe1993

**Comment by liwenhe1993** [comment]
I will fix it

**Comment by gumupaier** [comment]
> I will fix it
thank you

**Comment by liwenhe1993** [comment]
I fixed it up
