### ISSUE TITLE
[Feature] Suggest to change the interface of the datasource creation

### ISSUE THREAD

**Issue by JoshuaZhuCN** [apache/incubator-dolphinscheduler#2535]
>Currently, there are two data source creation portals:
>1. Admin user create and authorize
>2. User created

>There is a problem. 
The data source created by the user can't be viewed by admin. 
As a result, the data source can't be authorized to other users.
It is recommended that the creation of data source should be completed and authorized by admin. 
The creation of data source for ordinary users only calls the creation interface of admin to complete the creation and automatically authorize it for their own use. 
In this way, no matter who creates the data source (actually it is created by admin), it can be authorized to other users.

>目前数据源创建入口有两个：
1、admin用户创建并授权
2、用户自己创建

>出现的问题，用户自己创建的数据源admin无法查看到，造成该数据源无法授权给其他用户使用。
建议数据源创建都由admin来完成并授权，普通用户的数据源创建仅只是调用admin的创建接口来完成创建并自动授权给自己使用，这样该数据源无论是谁创建的（实际都是admin创建的）都能授权给其他用户使用。

**Comment by xingchun-chen** [comment]
Which version are you, under normal circumstances admin can view the data source created by ordinary users, can also be authorized to other users

**Comment by JoshuaZhuCN** [comment]
……sorry, i'm wrong. Two environments……
