### ISSUE TITLE
Zookeeper management interface in monitoring center displays abnormal

### ISSUE THREAD

**Issue by lishuaiyan** [apache/incubator-dolphinscheduler#2547]
**Describe the bug**
Zookeeper management interface in monitoring center displays abnormal。In fact, zookeepeer is running normally, both master and worker are successfully registered in zookeeper

**To Reproduce**
1、After normal installation and deployment, log in to the dolphinscheduler web interface
2、Check the zookeeper management interface of the monitoring center, you can find this problem

**Expected behavior**
It can display various monitoring indicators of zookeeper normally

**Screenshots**
![image](https://user-images.githubusercontent.com/42579056/80374318-13c98780-88c9-11ea-8d5f-53448b957f02.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Comment by qiaozhanwei** [comment]
please see api server log

**Comment by samz406** [comment]
hello ,maybe is  zk FourLetterWord problem,
you can try try command as follow

echo ruok|nc localhost 2181
if has the words, maybe you modify zoo.cfg

`ruok is not executed because it is not in the whitelist.`

add  config in zoo.cfg
`4lw.commands.whitelist=*`

restart zk

tips : if has not nc,you can yum install nc

**Comment by tlhhup** [comment]
I find some documentations, FYI:
https://issues.apache.org/jira/browse/ZOOKEEPER-2764

**Comment by dailidong** [comment]
> hello ,maybe is zk FourLetterWord problem,
> you can try try command as follow
> 
> echo ruok|nc localhost 2181
> if has the words, maybe you modify zoo.cfg
> 
> `ruok is not executed because it is not in the whitelist.`
> 
> add config in zoo.cfg
> `4lw.commands.whitelist=*`
> 
> restart zk
> 
> tips : if has not nc,you can yum install nc

very good job， this solve the problem

**Comment by databoyliu** [comment]
![2020-05-06 11-39-45屏幕截图](https://user-images.githubusercontent.com/31722412/81137261-c87e3b80-8f90-11ea-89a8-8901764c6cf1.png)
![2020-05-06 11-39-54屏幕截图](https://user-images.githubusercontent.com/31722412/81137278-d207a380-8f90-11ea-8809-7a14e5f084c5.png)
Solve as above, but there are new problems，Please refer to the pictures

**Comment by dailidong** [comment]
> ![2020-05-06 11-39-45屏幕截图](https://user-images.githubusercontent.com/31722412/81137261-c87e3b80-8f90-11ea-89a8-8901764c6cf1.png)
> ![2020-05-06 11-39-54屏幕截图](https://user-images.githubusercontent.com/31722412/81137278-d207a380-8f90-11ea-8809-7a14e5f084c5.png)
> Solve as above, but there are new problems，Please refer to the pictures

which zookeeper version do you use？

**Comment by dailidong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/2595  I think this PR will solve your problem

**Comment by databoyliu** [comment]
> > ![2020-05-06 11-39-45屏幕截图](https://user-images.githubusercontent.com/31722412/81137261-c87e3b80-8f90-11ea-89a8-8901764c6cf1.png)
> > ![2020-05-06 11-39-54屏幕截图](https://user-images.githubusercontent.com/31722412/81137278-d207a380-8f90-11ea-8809-7a14e5f084c5.png)
> > Solve as above, but there are new problems，Please refer to the pictures
> 
> which zookeeper version do you use？

3.6.1

**Comment by tlhhup** [comment]
> > > ![2020-05-06 11-39-45屏幕截图](https://user-images.githubusercontent.com/31722412/81137261-c87e3b80-8f90-11ea-89a8-8901764c6cf1.png)
> > > ![2020-05-06 11-39-54屏幕截图](https://user-images.githubusercontent.com/31722412/81137278-d207a380-8f90-11ea-8809-7a14e5f084c5.png)
> > > Solve as above, but there are new problems，Please refer to the pictures
> > 
> > 
> > which zookeeper version do you use？
> 
> 3.6.1

[#2595](https://github.com/apache/incubator-dolphinscheduler/pull/2595)  PR has resolve this problem.
