### ISSUE TITLE
How to take effect after modifying the environment variable of .dolphinscheduler_env.sh

### ISSUE THREAD

**Issue by wxg0103** [apache/incubator-dolphinscheduler#2548]
修改了.dolphinscheduler_env.sh的PYTHON_HOME的环境路径后   无法生效，  查看日志后  仍然是使用原来的路径  这是怎么回事

**Comment by dailidong** [comment]
could you provide the detail log info and the python file header?

**Comment by wxg0103** [comment]
![1588039263(1)](https://user-images.githubusercontent.com/46886316/80438646-414d1a00-8937-11ea-8bd4-83f93d40bb13.jpg)
![1588039194(1)](https://user-images.githubusercontent.com/46886316/80438648-4316dd80-8937-11ea-8a75-a90aab78f0d3.jpg)

**Comment by wxg0103** [comment]
![1588039194(1)](https://user-images.githubusercontent.com/46886316/80438863-c6d0ca00-8937-11ea-8ac2-b6e8f70192a3.jpg)

**Comment by wxg0103** [comment]
[INFO] 2020-04-28 09:16:55.708 org.apache.dolphinscheduler.api.service.LoggerService:[71] - [INFO] 2020-04-27 17:02:17.276  - [taskAppId=TASK-1-23-43]:[106] -  -> sudo：/opt/soft/python：找不到命令

export PYTHON_HOME=/usr/bin

**Comment by wxg0103** [comment]
我已经将python_home的路径改了   但是日志报错   还是报的原来的路径找不到

**Comment by dailidong** [comment]
why exists "/opt/soft/python"?  I don't see where have configed this location

**Comment by wxg0103** [comment]
原来  按着官方文档那么配置的  我以为暂时用不到python  就没去找它的路径   就那么配置完了   也部署好了  但是使用python功能的时候  找不到路径   然后我就改了路径  但是没有生效

**Comment by xingchun-chen** [comment]
After modifying the configuration, have you restarted all services?

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by wxg0103** [comment]
重启了  但是不起作用

**Comment by xingchun-chen** [comment]
Check if the "dolphinscheduler.env.path" path in conf/common/common.properties is the same as the .dolphinscheduler_env.sh path

**Comment by wxg0103** [comment]
我修改过了   路径一致

**Comment by xingchun-chen** [comment]
You change the python path to ‘export PYTHON_HOME = /usr/bin/python’, then restart the service using sh install.sh

**Comment by wxg0103** [comment]
那我使用  sh install.sh 重启服务  会对我已经已经存在的数据库  和一些文件会有影响吗？

**Comment by xingchun-chen** [comment]
If your configuration is configured through install.sh or is the same, restarting the service will have no effect

**Comment by wxg0103** [comment]
那就是只要是通过inatall.sh配置后  就不能更改环境变量了？

**Comment by dailidong** [comment]
do you check the PYTHON_HOME in .dolphinscheduler_env.sh on all worker server ?

**Comment by xingchun-chen** [comment]
Every time you change the environment variables and configuration, it is best to use sh install.sh to restart all services

**Comment by wxg0103** [comment]
检查过了   PYTHON_HOME 的路径没有问题

**Comment by wxg0103** [comment]
我服务已经部署好了   也进行一些测试使用了    如果使用sh install.sh 重启服务   会不会对我已经测试过的东西会进行清除

**Comment by samz406** [comment]
wait , are master and work on the same computer or are they deployed separately? 
 Did you modify the environment configuration on the work server?

**Comment by dailidong** [comment]
does the .dolphinscheduler_env.sh take effect?

**Comment by wxg0103** [comment]
同一台机器部署的  我部署的单机的

**Comment by samz406** [comment]
> 我修改过了 路径一致


You mean, have you just modified the environment path configuration of commp.properts, it is the following configuration.
If you update the path, then you need to restart the service.
At the same time, you need to confirm whether the environment variable of .dolphinscheduler_env.sh is configured successfully.
After all operations are completed, execute the next task to see if it still reports an error.

你的意思是是，你刚刚修改过commp.properts的环境路径配置吗，就是下面这个配置。

```
# system env path. self configuration, please make sure the directory and file exists and have read write execute permissions
dolphinscheduler.env.path=/data/app/dolphinscheduler/conf/env/.dolphinscheduler_env.sh
```

如果你更新了路径，那么你就需要重启下服务哦。
同时你要再确认下.dolphinscheduler_env.sh的环境变量是否配置成功了哦。
都操作完成后，再执运行下任务，看是不是还是报错。

**Comment by wxg0103** [comment]
重启服务是   sh stop-all.sh       还是使用 sh install.sh     如果使用sh install.sh会不会对我原来的部署的测试会有影响吗？

**Comment by samz406** [comment]
stop-all.sh  stop all server
start-al.sh start all server
you need first stop all server and start all server 

not use install ,unless reinstall server

**Comment by wxg0103** [comment]
我使用stop-all.sh停止服务后发现   服务还在后台启动，然后我把进程全删了，  重新启动了  但是还是不行  PYTHON_HOME仍然是原来的路径

**Comment by dailidong** [comment]
you should carefully check .dolphinscheduler_env.sh on the intall path dir,  when execute intall.sh ， it will deploy the DolphinScheduler to the install path(not the same as install.sh dir)
![image](https://user-images.githubusercontent.com/15833811/80447881-461cc880-894d-11ea-9c50-a35d0af351b8.png)

**Comment by dailidong** [comment]
if your .dolphinscheduler_env.sh config right , and take effect, `/opt/soft/python` should not happened on the worker server log

**Comment by wxg0103** [comment]
配置正确  我也用了echo $PYTHON_HOME  配置也生效了    但是就是会出现 /opt/soft/pytho

**Comment by wxg0103** [comment]
如果我改完配置环境    然后用install.sh   我原来设置的一些东西是不是就都没有了

**Comment by xingchun-chen** [comment]
I suggest you look at what install.sh did, so you know whether it will affect the previous configuration, because it is not clear which configuration you changed locally

**Comment by wxg0103** [comment]
我的install.sh的修改完全按照官方文档修改的        只是修改了数据库的地址，用户名，密码

**Comment by xingchun-chen** [comment]
execute sh install.sh will not affect the historical data

**Comment by wxg0103** [comment]
好的   多谢

**Comment by wxg0103** [comment]
我使用  install.sh  后直接退出了   jps查看服务也没有启动

**Comment by wxg0103** [comment]
我使用install.sh 重新部署了   但是还是显示/opt/soft/python找不到

**Comment by samz406** [comment]
Say your WeChat if it ’s convenient, chat alone

**Comment by wxg0103** [comment]
wxg19960103

**Comment by dailidong** [comment]
when you sovled this issue, please tell us how to solve ,thx

**Comment by samz406** [comment]
> when you sovled this issue, please tell us how to solve ,thx

After communicating with the user, it was found that the user started the service. Start the installation package path start-all.sh first, followed by the help of several small partners, the user updated the installation path dolphinscheduler_env.sh, the user restarts and starts the installation package path start-all.sh.
So let the user stop killing all services first, then start start-all.sh in the installation path and run python ok;
A problem exposed here is that the documentation is not comprehensive enough. Can also be optimized



和用户交流后发现是用户启动服务的问题。最先启动**安装包路径**start-all.sh,后续几个小伙伴的帮助，用户更新了**部署路径**下dolphinscheduler_env.sh，用户重启还是启动安装包路径下start-all.sh。
所以让用户先停了kill所有服务，然后启动部署路径下start-all.sh，运行python ok 了；
这里暴露一个问题是文档写的还不够全面。还可以优化
