### ISSUE TITLE
Data source center configuration problems（数据源中心配置问题）

### ISSUE THREAD

**Issue by wanghongwei9538** [apache/incubator-dolphinscheduler#2550]
After the spark is configured in the data source center, the spark engine should be used in theory. However, I use spark to run SQL. The execution engine is Mr, and I can't find the document. How to configure this（在数据源中心配置spark之后，理论上应该走spark引擎，但是我使用spark运行sql，执行引擎还是mr，没找到文档，这个需要怎么配置）

**Comment by dailidong** [comment]
do you start spark ThriftServer?
