### ISSUE TITLE
Problems in executing SQL nodes（执行sql节点问题）

### ISSUE THREAD

**Issue by wanghongwei9538** [apache/incubator-dolphinscheduler#2551]
How to set the parameter information of hive / spark when the SQL node is configured to be non query? No relevant document is found（执行sql节点配置成非查询的，怎么set hive/spark的参数信息，没有找到相关的文档说明）

**Comment by dailidong** [comment]
which paramters do you want to set?

**Comment by wanghongwei9538** [comment]
I want to set up：
set mapred.max.split.size= 536870912;
set mapred.min.split.size.per.node= 536870912;
set mapred.min.split.size.per.rack= 536870912;
set hive.input.format=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat;
set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nostrick;
set hive.exec.max.dynamic.partitions.pernode=2000;
set hive.exec.reducers.max=200;
set spark.sql.adaptive.enabled=true; 
set spark.sql.adaptive.shuffle.targetPostShuffleInputSize=128000000;
Before executing SQL

**Comment by liukunyuan** [comment]
set parameters before SQL.for example
set mapred.max.split.size= 536870912;set mapred.min.split.size.per.node= 536870912;select '1';

**Comment by liukunyuan** [comment]
you can execute it with a shell node
你可以把你sql写到一个文件中，通过hive -f执行这个sql文件

**Comment by chengshiwen** [comment]
Close the issue since it has been solved
