### ISSUE TITLE
[Feature] Support plugin in Alert service

### ISSUE THREAD

**Issue by hgaol** [apache/incubator-dolphinscheduler#2553]
I think the plugin feature is needed by the customers, because different user may have different environment. For example, I want to use SMS to send alert information, but the SMS API is provided by some system we don't know before, and our DS has already deployed. In this case, I just want to implement the plugin code, and don't change the source code.

Another benefits are developers can implement different plugin, like slack, wechat, telegram, github issue, and etc...

**Describe the solution you'd like**

A better way is that user do not need to change the source code to support new alert method. Instead, they just need to implement some interface, and compliance with the convention, then package all(include dependencies) in a single jar file, and put the jar file in some specific place, such as `$DS_HOME/plugins`. After that, when start Alert service, the plugins can be recognized and loaded. So user can choose the alert method in the portal.

Currently, I've done some investigations, and if this feature is accepted, I think maybe I can implement it.

Firstly, I'd better to adapt the current function, which is send mail and something like that.

Then, we can add some more features, such as Alert handler instance, which is created to describe the alert information(email/slack/wechat/..., to whom, the title, content, and etc...).

**Comment by hgaol** [comment]
BTW, email and webhook is used frequently. I think they can be the default plugin, and write in the source code, instead of a jar file.

**Comment by dailidong** [comment]
good idea，it's good news to hear that you will to implement it 
BTW , the deep disscussion should happened on the mailing list: dev@dolphinscheduler.apache.org

**Comment by hgaol** [comment]
> good idea，it's good news to hear that you will to implement it
> BTW , the deep disscussion should happened on the mailing list: [dev@dolphinscheduler.apache.org](mailto:dev@dolphinscheduler.apache.org)

Sure

**Comment by dailidong** [comment]
BTW, If it is convenient, please register the usage information: #57

**Comment by dailidong** [comment]
mail list: https://lists.apache.org/thread.html/r4c7c5118fe84adef53791232e1d55495e1d6355580e2d7b3704e4670%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by hgaol** [comment]
> BTW, If it is convenient, please register the usage information: #57

Currently, I just use and learn DS in a developer view, if there is any use case from me or my friends for future, then will register the information. :)
