### ISSUE TITLE
[BUG] The options overlap. It is recommended to add a scroll bar

### ISSUE THREAD

**Issue by muzhongjiang** [apache/incubator-dolphinscheduler#2554]
**Describe the bug**
The options overlap. It is recommended to add a scroll bar

**Screenshots**
![image](https://user-images.githubusercontent.com/7700151/80467330-3cf12300-8970-11ea-9ac0-85e7150a55d7.png)

**Which version of Dolphin Scheduler:**
 -[dev branch]

**Comment by break60** [comment]
Okay, part of the list increases scrolling

**Comment by xingchun-chen** [comment]
dev_1.3.0 has changed
