### ISSUE TITLE
[Feature]unique processdefinition name in the same project

### ISSUE THREAD

**Issue by wuzhipeng7cc** [apache/incubator-dolphinscheduler#2559]
**branch**
dev
**Is your feature request related to a problem? Please describe.**
if the same name in one project ,im hard to recognize any one . And its usually caused by mistake

**Describe the solution you'd like**
unique processDifinition name in one project

**Additional context**
name suffix is also good

**Comment by dailidong** [comment]
I don't test dev branch for now, 
as I know, version 1.2.0 1.2.1 not exists this situation,  when save Process Definition, it will check the name aleady exists or not

@xingchun-chen please verify this issue

**Comment by wuzhipeng7cc** [comment]
@dailidong  i'd found that checked by ProcessDefinitionController.verifyProcessDefinitionName
and i didn't see the unique constraint on t_ds_process_definition's ddl with the name and project_id column. i think it maybe cause some problem In concurrent mode

**Comment by xingchun-chen** [comment]
1.If the workflow definition is verified to be unique through the normal operation of the dag page, as shown in the following figure
如果通过dag页面正常操作校验了工作流定义名称唯一，如下图所示
![image](https://user-images.githubusercontent.com/55787491/80553327-fc3eeb80-89fb-11ea-8549-9cd8e58615a8.png)

2.If you create workflow definitions concurrently through tools, you can create multiple workflow definitions with the same name. Import workflows also have this problem. Same as # 2538
如果通过工具并发创建工作流定义，可以创建多个同名的工作流定义，导入工作流也有该问题同#2538
![image](https://user-images.githubusercontent.com/55787491/80553754-80de3980-89fd-11ea-91a8-428c776746fc.png)

**Comment by xingchun-chen** [comment]
who can fix it

**Comment by simon824** [comment]
i will fix it
