### ISSUE TITLE
Can I use code to automatically create a process definition

### ISSUE THREAD

**Issue by liucf915** [apache/incubator-dolphinscheduler#2562]
**Can I call the dolphinscheduler API with postman to query a process definition or to create a new process definition?**

I have a lot of DAG to migrate from the airflow on dolphinscheduler .These DAG's have a lot in common, so you would like to use code to auto-create DAG's. Dolphinscheduler supports this

**DolphinScheduler1.2.0**

**Comment by dailidong** [comment]
version 1.2.1 can support create DAG through open API 
relate PR :  [#1497] DAG automatic layout when use api call process definition create

1.2.0 not support DAG automatic layout

**Comment by liucf915** [comment]
I have now upgraded to version 1.2.1, and I haven't found the use method of "open API "after looking through the network documents. Can you give me an example?Or provide usage documentation

**Comment by chengshiwen** [comment]
http://106.75.43.194:8888/dolphinscheduler/doc.html
