### ISSUE TITLE
[QUESTION] Does DS support  supplementary data by hour or minute?

### ISSUE THREAD

**Issue by sudddenly** [apache/incubator-dolphinscheduler#2564]
**Describe the question**
Does ds support  supplementary data by hour or minute?
I  find nothing in relase notes , bug list and feature list  but this pr https://github.com/apache/incubator-dolphinscheduler/pull/1811, but I don't know which version I can use this feature.

**Comment by dailidong** [comment]
@zixi0825 , could you answer this issue?

**Comment by zixi0825** [comment]
In the dev branch, if you do not have a scheduled task online, the complement will only be based on the date. For example, if you choose the range from 2020-04-01 to 2020-04-10 to complement, then the complement will be from 2020-04 -01 00:00:00 starts to 2020-04-10 00:00:00 ends. If you have a scheduled task online, the cron expression of your scheduled task will be parsed, and the corresponding execution time will be generated. For example, your cron is 5 6 * * *? *, And the date selection range is 2020-04-01 to 2020-04-10, then the execution time is 2020-04-01 01:06:05. 2020-04-01 02:06:05, 2020-04-01 03:06:05. . . Until the end
---------------------------------------------------------------
在dev分支，如果你没有上线定时任务的话，那么补数只会根据日期来，例如你选择了2020-04-01到2020-04-10这个范围来补数，那么补数会从2020-04-01 00:00:00开始到2020-04-10 00:00:00结束。如果你上线了定时任务，那么会解析你的定时任务的cron表达式，然后生成相应的执行时间，例如你的cron是5 6 * * * ? *，，日期选择范围为2020-04-01到2020-04-10，那么执行时间就是2020-04-01 01:06:05。2020-04-01 02:06:05，2020-04-01 03:06:05。。。直到结束

**Comment by sudddenly** [comment]
Thanks, dev branch can't use in product enviorment, expecting the next release

**Comment by xingchun-chen** [comment]
version 1.3.2 had solved the problem
