### ISSUE TITLE
[BUG] 配置了告警策略，没有收到告警邮件和查到相关输出日志

### ISSUE THREAD

**Issue by chenghm** [apache/incubator-dolphinscheduler#2565]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
任务流配置了通知策略：成功或失败都发，执行任务流没有告警邮件收到和相关日志输出
**To Reproduce**
点击运行任务流，在弹出的窗口中配置通知策略:成功或失败都发，选择通知组，点击运行按钮
**Expected behavior**
收到告警邮件和后台查看到告警日志输出
**Screenshots**
[](url)

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by chenghm** [comment]
[

1. 

- 

- 

](url)

**Comment by JsonGuo-coder** [comment]
Hi， I also encountered a similar problem, do you have a solution
