### ISSUE TITLE
安装docker版本没有HTTP节点

### ISSUE THREAD

**Issue by longshang** [apache/incubator-dolphinscheduler#2566]
安装了docker版本，在工作流定义界面没有HTTP节点与Flink节点

**Comment by dailidong** [comment]
for now docker version is not sync with DolphinScheduler release version

**Comment by dailidong** [comment]
dev branch is willing to change this situation, BTW, dev branch just prepare for the next version and a lot of test need to done

**Comment by qiaozhanwei** [comment]
please use english to desc your problem，thx
