### ISSUE TITLE
After the sub process ends, the main process task status is not updated.

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2568]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
After the sub process ends, the main process task status is not updated.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create the main process and sub-process as shown in the figure
2. Then make up data two days

**Expected behavior**
1. After 12 hours of execution there is still no update.
2. After the service restarts, the task will be automatically re-executed（In fact, I just want to end this task, and later modify the database table to temporarily end the task.）
3. This problem does not always appear.(This step was successful again just after I executed)

**Which version of Dolphin Scheduler:**
 -[1.2.1]
- Stand-alone deployment

**Additional context**

![image](https://user-images.githubusercontent.com/10054719/80553181-7d49b300-89fb-11ea-905e-42ff3650978d.png)

![image](https://user-images.githubusercontent.com/10054719/80553200-86d31b00-89fb-11ea-86d5-3eb34fb15776.png)

![image](https://user-images.githubusercontent.com/10054719/80553208-8dfa2900-89fb-11ea-93c5-0d994346658c.png)

**Comment by arlanhon** [comment]
Accidentally resubmitted the question

**Comment by dailidong** [comment]
did you see master or  worker server runtime log ?

**Comment by arlanhon** [comment]
I forgot to read it, just read the process is normal

**Comment by arlanhon** [comment]
> did you see master or worker server runtime log ?
Maybe I found the reason. When executing the main process, the task status of the sub-process must be online. If it is offline, there will be problems. But is there any problem with this mechanism? This means that my task cannot be modified while it is running, otherwise there may be problems.

**Comment by xingchun-chen** [comment]
The dev branch did not reproduce the problem, you can verify it in the dev branch
