### ISSUE TITLE
[Feature]Configurable registration  ipaddress

### ISSUE THREAD

**Issue by wuzhipeng7cc** [apache/incubator-dolphinscheduler#2574]
**Is your feature request related to a problem? Please describe.**
on macos,OSUtils.getHost() returns diffrent ip in running time. Also,the method OSUtils.getHost() didn't
perform well in container situation like docker ,some error may happen
**Describe the solution you'd like**
provide a param like register-ip to specific the ip which will be registried on zk
**Describe alternatives you've considered**
provide a param like networkinterface to specific the networkinterface  which will be registried on zk
**Additional context**
<img width="1467" alt="8C1E5A5B-CC64-40FE-9049-5FC6154E72FE" src="https://user-images.githubusercontent.com/42403258/80572245-80ab6180-8a30-11ea-9525-73b33f1bf49e.png">
<img width="1481" alt="25DECE0A-2A92-479F-A76F-7DAEB8F691FF" src="https://user-images.githubusercontent.com/42403258/80572256-8608ac00-8a30-11ea-8784-eeb88c0fb7ea.png">
英文不好,简单的说就是可以指定注册到zk上的ip或可选的网卡配置

**Comment by CalvinKirs** [comment]
I will finish it later

**Comment by CalvinKirs** [comment]
At present, I have submitted an option to provide usable IPs under multiple network cards, and I will complete it after waiting for the pr to merge @wuzhipeng7cc

**Comment by gabrywu** [comment]
> At present, I have submitted an option to provide usable IPs under multiple network cards, and I will complete it after waiting for the pr to merge @wuzhipeng7cc

@CalvinKirs Please paste your PR number here

**Comment by CalvinKirs** [comment]
> > At present, I have submitted an option to provide usable IPs under multiple network cards, and I will complete it after waiting for the pr to merge @wuzhipeng7cc
> 
> @CalvinKirs Please paste your PR number here

#2924  This PR provides the return of the first available address in the case of multiple network cards. After waiting for the PR merge, I will implement the host configuration
