### ISSUE TITLE
  DS deployed in the cluster environment,but  found  all tasks are running on one machine. Is there any problem in  configuration? 

### ISSUE THREAD

**Issue by zhangdehai** [apache/incubator-dolphinscheduler#2576]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**

When deploying DS in cluster environment, but i found that task instance all runs on one of the machines. Only when other servers are stopped, can run on the other machine. Is there any problem with the configuration? Thank you!

**Which version of DolphinScheduler:**
 -[1.2.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by lenboo** [comment]
@zhangdehai english is official language, please change the title and content to english.

**Comment by zhangdehai** [comment]
thanks

**Comment by chengshiwen** [comment]
Please try to use and check 1.3.x. Close this since no updates for long time
