### ISSUE TITLE
[BUG]wrong description of work flow copy tips

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2578]
![image](https://user-images.githubusercontent.com/29528966/80588031-28815900-8a4a-11ea-8c41-595890f0c529.png)

version:
dev

i think the tips should be "work flow copy"

**Comment by dailidong** [comment]
if anybody who want to fix this issue ,please leave message, thx

**Comment by zixi0825** [comment]
I wiil fix it
