### ISSUE TITLE
Code directory structure - recommended by module（代码目录结构-建议按模块分开）

### ISSUE THREAD

**Issue by coding-now** [apache/incubator-dolphinscheduler#258]
Esceduler-server package
Integrated three services: master, worker, and logger. Why not be independent into three modules.
1. Deployment aspect The coupling is high, the startup parameters are written in the script, and the development phase is inconvenient.
2, windows environment development test is not convenient
3, the resource center function is strongly dependent on hadoop.
4. Parameter configuration is recommended to be set separately according to the function module, separated from the code: configuration external shift.
It is only a suggestion that the place may be changed.

---
escheduler-server包
集成了 master,worker，logger三个服务。为什么不独立成三个module呢。
1、部署方面 耦合性高，启动参数写在脚本中，开发阶段不方便。
2、windows环境开发测试不方便
3、资源中心功能  强依赖hadoop.
4、参数配置建议按功能模块 分开设置，与代码分离：配置外移。
只是建议，可能改动地方比较大。

**Comment by dailidong** [comment]
your suggestion is very good , for now ,  we are going to split more detail modules, and dev branch has supported running DolphinScheduler on windows

**Comment by dailidong** [comment]
and resources support local file sysytem, hdfs  and minIo

**Comment by CalvinKirs** [comment]
done
