### ISSUE TITLE
[BUG] When the process involves sub-processes, the complement operation will only take the start time, and will repeat the number of days to perform the complement

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2581]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
When the process involves sub-processes, the complement operation will only take the start time, and will repeat the number of days to perform the complement.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a simple sub-process, such as a shell
2. Create another main process and associate sub-processes
3. For complement operation, you can also make up only two days

The specific operation is as follows：
1. Create subprocess， 
![image](https://user-images.githubusercontent.com/10054719/80662237-5e165880-8ac3-11ea-9e47-ea97af1179ab.png)
2. Save subprocess and setting variables
![image](https://user-images.githubusercontent.com/10054719/80662384-b6e5f100-8ac3-11ea-84f5-a307acc79f88.png)
3. Create the main process and create sub node as in main process
![image](https://user-images.githubusercontent.com/10054719/80662453-d715b000-8ac3-11ea-8186-b7a92a709c79.png)
![image](https://user-images.githubusercontent.com/10054719/80662492-f0b6f780-8ac3-11ea-9c0c-ed628b82772c.png)
4. Save main process and setting variables
![image](https://user-images.githubusercontent.com/10054719/80662523-07f5e500-8ac4-11ea-8b15-8df097cc5c76.png)
5. As follow.
![image](https://user-images.githubusercontent.com/10054719/80662545-193ef180-8ac4-11ea-8343-802808ad278f.png)
6. Then complement
![image](https://user-images.githubusercontent.com/10054719/80662594-3b387400-8ac4-11ea-96b1-75fa364ca167.png)
7. The result is as follows, the date printed is only the start date
![image](https://user-images.githubusercontent.com/10054719/80662665-67ec8b80-8ac4-11ea-9ae2-d082087efe6b.png)
![image](https://user-images.githubusercontent.com/10054719/80662670-6d49d600-8ac4-11ea-8487-608327a30654.png)
![image](https://user-images.githubusercontent.com/10054719/80662674-70dd5d00-8ac4-11ea-914d-096c12cbfb9c.png)

8. The timing of the main process is correct
![image](https://user-images.githubusercontent.com/10054719/80662741-9bc7b100-8ac4-11ea-9d4d-e05c54ca5a86.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]
- Stand-alone deployment

**Comment by xingchun-chen** [comment]
At present, serial complement is a problem, it is recommended to use parallel complement

**Comment by xingchun-chen** [comment]
@lenboo

**Comment by arlanhon** [comment]
> At present, serial complement is a problem, it is recommended to use parallel complement

Yes, some scenarios are currently not suitable for parallelism. For example, if my example above is parallel, some intermediate operations will be added or deleted.
