### ISSUE TITLE
[QUESTION] whether sql task state need to bind mail sending result？

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2590]
now we binding the mail send result in sql task, 
sql task would failed if mail send failed.
I wonder if it's necessary？

**Comment by lgcareer** [comment]
Good question,Wish more people discuss about it.In the beginning if mail send failed don't result in the task failed.

**Comment by chengshiwen** [comment]
Close by #5104

The switch to send mail has supported in next 1.3.6

![image](https://user-images.githubusercontent.com/4902714/114265730-07303780-9a25-11eb-8d2a-7d75a591d222.png)
