### ISSUE TITLE
[Feature]one worker can belong to different workergroups

### ISSUE THREAD

**Issue by banpeiyong** [apache/incubator-dolphinscheduler#2591]
one worker only belongs to one worker group，it will waste the server resources。

For example， worker A which belongs Group A will busy in 9 - 10 pm but  be free in the other time，it's better to supprt worker A belongs to many groups to make the server be used fully。

In the last version, it can be configured in the Web . it's very usability。So I hope it can be reserved and off course considered the normal situation and the Dorker situation。

**Comment by lenboo** [comment]
+1 
i agree 
1.  one worker belongs to different woker groups.
2. visualization of worker group page

**Comment by yangyichao-mango** [comment]
I will do it.

**Comment by chengshiwen** [comment]
Close by ##2934 #5122
