### ISSUE TITLE
[QUESTION]  WorkServer  exec   Task  on  localhost    report   NPE

### ISSUE THREAD

**Issue by HQTB123** [apache/incubator-dolphinscheduler#2592]
![image](https://user-images.githubusercontent.com/50647068/80706239-8d0be900-8b1a-11ea-873b-fe1e515df703.png)

WorkerServer  exec task  on localhost   the  getLogPath  method   report  NPE

**Comment by liwenhe1993** [comment]
Please add logback-xx.xml in vm options when you run ds on localhost

**Comment by itbasketplayer** [comment]
+1

**Comment by jianghuzai** [comment]
@liwenhe1993 could you tell me the key?

**Comment by jianghuzai** [comment]
@liwenhe1993 thanks,I found the key

**Comment by liwenhe1993** [comment]
> @liwenhe1993 thanks,I found the key
> 
> I am use idea.
> master vm option:
> 
> ```
> -Dspring.profiles.active=master -Dlogging.config="dolphinscheduler-server/src/main/resources/master_logback.xml"
> ```
> 
> worker vm option:
> 
> ```
> -Dspring.profiles.active=worker -Dlogging.config="dolphinscheduler-server/src/main/resources/worker_logback.xml"
> ```
> 
> CombinedApplicationServer vm option
> 
> ```
> -Dlogging.config="dolphinscheduler-api/src/main/resources/apiserver_logback.xml"
> ```
> 
> CombinedApplicationServer active profiles:
> 
> ```
> api
> ```

good job
