### ISSUE TITLE
[BUG] the file name is not correct after rename the HDFS resource file

### ISSUE THREAD

**Issue by gavinjp** [apache/incubator-dolphinscheduler#2596]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The file name is not correct after rename the HDFS resource file via [Resources -> File Manager -> [pick a item and click]"Rename" Button]

**To Reproduce**
Steps to reproduce the behavior, for example:
1. prepare a log file
![0](https://user-images.githubusercontent.com/22143753/80987937-5bba5280-8e65-11ea-91a0-273eb7ba5e99.png)

2. upload the file test.log
![image](https://user-images.githubusercontent.com/22143753/80987814-31689500-8e65-11ea-8997-e6247f9d4936.png)

3. rename test.log to test.txt
![2](https://user-images.githubusercontent.com/22143753/80988066-89070080-8e65-11ea-93e0-4e40165f1ef7.png)

4. See error: the file name is not change to test.txt, and can not open in file details
![3](https://user-images.githubusercontent.com/22143753/80988104-958b5900-8e65-11ea-96b8-18425ba527d6.png)

![3_2](https://user-images.githubusercontent.com/22143753/80988379-03d01b80-8e66-11ea-81f9-c8d008ec00a0.png)

**Expected behavior**
The file name should be change to test.txt, and can open it in file detail page

**Which version of Dolphin Scheduler:**
 -[1.2.1-realease]

**Comment by xingchun-chen** [comment]
@lgcareer  At present, resource renaming can only change the name, not the file type

**Comment by xingchun-chen** [comment]
The problem has been solved in dev_1.3.0,Same as #2598
