### ISSUE TITLE
[BUG] After renaming the file, downloading the file gives an error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2598]
1. create file is test_1.sh
2. The file is renamed to test_1.txt, and the file name displayed on the page is "test_1.txt.sh"
3. Download file, prompt "error downloading resource file"
4. Check the hdfs resource file is "test_1.txt"
![image](https://user-images.githubusercontent.com/55787491/81133105-3d4a7900-8f83-11ea-9ce6-d36fa2f38a43.png)

![image](https://user-images.githubusercontent.com/55787491/81132928-a7aee980-8f82-11ea-8b0a-e3ed7231e560.png)
![image](https://user-images.githubusercontent.com/55787491/81133119-48050e00-8f83-11ea-84a5-83bc3f9f84d3.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by simon824** [comment]
i will fix it

**Comment by lgcareer** [comment]
> i will fix it
Great,you can do it.If have any question about it,can discuss with me.

**Comment by lgcareer** [comment]
> i will fix it
@simon824 Could you leave your eamil?If you still want to resove this issue.we can discuss this issue in the dev mail list.

**Comment by lgcareer** [comment]
@simon824 I send a email to discuss this issue,the email thread is https://lists.apache.org/thread.html/rb435e6aaea8d0e38d1261aa57c4afaf7a7b6e6a56d638814f3403f8d%40%3Cdev.dolphinscheduler.apache.org%3E

you can use pony eamil to visit it or you can search the title that is `[DISCUSSION] Is it allowed to change the resource file suffix when update resource name?`

**Comment by simon824** [comment]
How is this problem going, can I help?

**Comment by lgcareer** [comment]
I will fix it in dev-1.3.0.

**Comment by lgcareer** [comment]
> How is this problem going, can I help?
If you want to fix it,you can fix it in dev branch.

**Comment by simon824** [comment]
Is the modification logic of the dev branch the same as dev-1.3.0?
why not merge it to dev directly?
