### ISSUE TITLE
[QUESTION] CONDITIONS task node usability issues

### ISSUE THREAD

**Issue by ywywn** [apache/incubator-dolphinscheduler#2599]
**Describe the question**
    CONDITIONS is a pretty useful node, but there are some usability issues when I add additional condition with custom parameters. Logical judgment will appear even single condition, it make me confuse when use CONDITIONS firstly. Under a single condition, changing the logical judgment will not affect this part of the judgment.
![image](https://user-images.githubusercontent.com/26102201/81134447-6240eb00-8f87-11ea-8c9c-58f57a079d39.png)

**Which version of DolphinScheduler:**
 -[dev]

**Requirement or improvement**
Logical judgment should be hidden when user just have single condition.

**Comment by dailidong** [comment]
@xingchun-chen , please review this issue, thx

**Comment by xingchun-chen** [comment]
I don't quite understand what the problem is, can you describe it in detail

**Comment by ywywn** [comment]
Sorry about describe unclearly. No matter which judgment (and / or) I choose in custom parameters, the workflow always turns to test-4, the judgment(red mark) does not affect the workflow when custom parameters contain single condition. Is it possible to consider hiding judgment (and / or)  when custom parameters contain single condition? I think this is a problem about ease of use, the priority of modification will not be very high.
![image](https://user-images.githubusercontent.com/26102201/81389880-1f307480-914d-11ea-922e-1020868e7370.png)
![image](https://user-images.githubusercontent.com/26102201/81389920-32434480-914d-11ea-83f8-4f5149042c40.png)

**Comment by misinong** [comment]
How are conditional nodes used? When judging the task execution return code, whether 0 or 1, it will execute to the successful branch!

**Comment by xingchun-chen** [comment]
Use condition refer to #2652
