### ISSUE TITLE
[BUG] code annotation error

### ISSUE THREAD

**Issue by 743294668** [apache/incubator-dolphinscheduler#2603]
incubator-dolphinscheduler-dev/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/WorkerServer.java
Source code：
/**
     * master server startup
     *
     * master server not use web service
     * @param args arguments
     */
    public static void main(String[] args) {
        Thread.currentThread().setName(Constants.THREAD_NAME_WORKER_SERVER);
        new SpringApplicationBuilder(WorkerServer.class).web(WebApplicationType.NONE).run(args);
    }

The master in the annotation on lines 74 and 76 should be changed to worker.

**Comment by dailidong** [comment]
anybody who want to solve this issue, it's easy to fix,  haha

**Comment by ywywn** [comment]
I will fix it :)
