### ISSUE TITLE
[QUESTION] ProcessorLoop

### ISSUE THREAD

**Issue by tlhhup** [apache/incubator-dolphinscheduler#2605]
**Describe the question**
Could you please explain below code in `TaskResponseProcessor` or `TaskAckProcessor`? What's the propose? Can it be removed?
` while (Stopper.isRunning()){
            TaskInstance taskInstance = processService.findTaskInstanceById(taskResponseEvent.getTaskInstanceId());

            if (taskInstance != null && responseStatus.typeIsFinished()){
                break;
            }
            ThreadUtils.sleep(SLEEP_TIME_MILLIS);
        }
`
**Which version of DolphinScheduler:**
 -[dev]

**Comment by qiaozhanwei** [comment]
please refer [DISCUSS] fault-tolerant on dev mail 
master synchronous wait asynchronous queue data flush to db prevent master down，then worker retry

**Comment by tlhhup** [comment]
can you give me a link?

**Comment by qiaozhanwei** [comment]
1. Use your own mailbox to send an email to dev-subscribe@dolphinscheduler.apache.org with arbitrary subject and content.

2. Receive confirmation email and reply. After completing step 1, you will receive a confirmation email from dev-help@dolphinscheduler.apache.org (if not received, please confirm whether the email is automatically included in the folder of spam, promotion mail, subscription mail, etc.) . Then reply directly to the email, or click the link in the email to reply quickly, the subject and content are arbitrary.

3. Receive a welcome email. After completing the above steps, you will receive a welcome email with the theme WELCOME to dev@dolphinscheduler.apache.org, and you have successfully subscribed to the Apache DolphinScheduler (Incubating) mailing list

**Comment by tlhhup** [comment]
ok,thx.
