### ISSUE TITLE
Update  DolphinScheduler

### ISSUE THREAD

**Issue by wxg0103** [apache/incubator-dolphinscheduler#2607]
I currently install the stand-alone version of 1.20, but I now want to deploy the DolphinScheduler cluster. Do I need to uninstall 1.20 and then deploy the cluster version of 1.21.

**Comment by dailidong** [comment]
if your ip on Standalone mode shows not localhost or 127.0.0.1， you can use the same database when update, otherwise I suggest you re-intall 1.2.0 cluster

**Comment by dailidong** [comment]
you also can try what you think, if meet some problems,  you can paster the exception info

**Comment by dailidong** [comment]
I will close this issue, if you meet some problems, you can reopen it
