### ISSUE TITLE
Sqoop import data into hive succeeded,but task instance shows failed!

### ISSUE THREAD

**Issue by dukeshiny** [apache/incubator-dolphinscheduler#2611]
When I use sqoop import data into hive,the dolphinscheduler log shows success,but the task instance shows failed!
![image](https://user-images.githubusercontent.com/21135052/81167072-275ea780-8fc7-11ea-8dac-000a51108f41.png)

![image](https://user-images.githubusercontent.com/21135052/81166991-09914280-8fc7-11ea-82fb-d0203af30cc8.png)

**Comment by 743294668** [comment]
Fellow Worker log.
/dolphinscheduler/install/logs

**Comment by dukeshiny** [comment]
> Fellow Worker log.
> /dolphinscheduler/install/logs

It seems that has a error log in dolphinscheduler-worker.log
![image](https://user-images.githubusercontent.com/21135052/81169188-fe401600-8fca-11ea-8660-3207cce1a340.png)

**Comment by dukeshiny** [comment]
# if it is a single resourcemanager, you only need to configure one host name. If it is resourcemanager HA, the default configuration is fine.
singleYarnIp="ark1"

I find this config in install.sh ,my yarn is HA,so is this right?

**Comment by 743294668** [comment]
It is best to configure both

**Comment by dukeshiny** [comment]
> It is best to configure both

OK,by the way ,if I change this singleYarnIp="cdh201",should I execute the install.sh shell？Or I just need to restart dolphinscheduler?Thank you!

**Comment by 743294668** [comment]
Only restart worker-server.

**Comment by 743294668** [comment]
Modify the yarn.application.status.address of the /opt/dolphinscheduler/conf/common.properties file so that you can just restart the worker.

**Comment by dukeshiny** [comment]
> Modify the yarn.application.status.address of the /opt/dolphinscheduler/conf/common.properties file so that you can just restart the worker.

Now my common.properties has “yarn.application.status.address=http://ark1:8088/ws/v1/cluster/apps/%s
” ，my resourcemanager is HA,I think should change yarn.resourcemanager.ha.rm.ids=cdh201,cdh202,
am I right?

**Comment by dukeshiny** [comment]
I found this issue can solve this error
https://github.com/apache/incubator-dolphinscheduler/issues/2491

**Comment by dukeshiny** [comment]
> Modify the yarn.application.status.address of the /opt/dolphinscheduler/conf/common.properties file so that you can just restart the worker.
After I set yarn.resourcemanager.ha.rm.ids=cdh201,cdh202,another error happens,even if the sqoop task succeeded!
![image](https://user-images.githubusercontent.com/21135052/81178322-9c87a800-8fda-11ea-964a-9ae631ca629c.png)

**Comment by 743294668** [comment]
The worker log ? 
It doesn't look like a yarn problem. At present, Sqoop's support does not seem to be very good. It is recommended that you try using a shell to see if the error is reported.

**Comment by dukeshiny** [comment]
> The worker log ?
> It doesn't look like a yarn problem. At present, Sqoop's support does not seem to be very good. It is recommended that you try using a shell to see if the error is reported.
The dolphinscheduler-worker.log shows this log.
![image](https://user-images.githubusercontent.com/21135052/81180394-892a0c00-8fdd-11ea-931e-e8c70c5a5040.png)

**Comment by 743294668** [comment]
This seems to be a problem with your sqoop command. It is recommended that you go to the full log of your sqoop command on MAPREDUCE. Generally there will be a complete sqoop execution log.

**Comment by dukeshiny** [comment]
> This seems to be a problem with your sqoop command. It is recommended that you go to the full log of your sqoop command on MAPREDUCE. Generally there will be a complete sqoop execution log.

I have checked the mr sqoop execution log,there is no error.The result of the sqoop task succeeded,but the dolphinscheduler web task instance shows failed!How can I solve this problem?
Thanks a lot!

**Comment by 743294668** [comment]
If you are sure that it is not a sqoop problem but a DS problem, you can try to change the log level of the DS worker to debug. If not, you can only look at the source code.

**Comment by itbasketplayer** [comment]
please check the config of your cloudera-manager
'yarn.resourcemanager.max-completed-applications'
if too small, the appIds's state will not return 'SUCCESS'
then shell task's state is FAILURE.

you can add a checking use historyserver,but you have to check the config:mapreduce.jobhistory.max-age-ms first

**Comment by dukeshiny** [comment]
> please check the config of your cloudera-manager
> 'yarn.resourcemanager.max-completed-applications'
> if too small, the appIds's state will not return 'SUCCESS'
> then shell task's state is FAILURE.
> 
> you can add a checking use historyserver,but you have to check the config:mapreduce.jobhistory.max-age-ms first
The 'yarn.resourcemanager.max-completed-applications' is 10000.
![image](https://user-images.githubusercontent.com/21135052/81463354-9a486800-91eb-11ea-9e50-d1fae6d12f2b.png)
![image](https://user-images.githubusercontent.com/21135052/81463368-b77d3680-91eb-11ea-8977-0abc1aa0dc0e.png)

**Comment by jzmq** [comment]
I met the same error , here the error message
` [taskAppId=TASK-14-45-114]:[189] - Conversion = ';'
java.util.UnknownFormatConversionException: Conversion = ';'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:410)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.updateState(AbstractCommandExecutor.java:241)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:170)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-05-21 16:13:40.973  - [taskAppId=TASK-14-45-114]:[107] - shell task failure
java.lang.RuntimeException: process error . exitCode is :  -1
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:190)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-05-21 16:13:40.973 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[153] - task scheduler failure
java.lang.RuntimeException: process error . exitCode is :  -1
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:190)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-05-21 16:13:40.974  - [taskAppId=TASK-14-45-114]:[262] - cancel process: 28845
[INFO] 2020-05-21 16:13:40.986 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[161] - task instance id : 114,task final status : FAILURE`

**Comment by 743294668** [comment]
> I met the same error , here the error message
> ` [taskAppId=TASK-14-45-114]:[189] - Conversion = ';' java.util.UnknownFormatConversionException: Conversion = ';' at java.util.Formatter.checkText(Formatter.java:2579) at java.util.Formatter.parse(Formatter.java:2565) at java.util.Formatter.format(Formatter.java:2501) at java.util.Formatter.format(Formatter.java:2455) at java.lang.String.format(String.java:2940) at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:410) at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.updateState(AbstractCommandExecutor.java:241) at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:170) at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105) at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [ERROR] 2020-05-21 16:13:40.973 - [taskAppId=TASK-14-45-114]:[107] - shell task failure java.lang.RuntimeException: process error . exitCode is : -1 at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:190) at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105) at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [ERROR] 2020-05-21 16:13:40.973 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[153] - task scheduler failure java.lang.RuntimeException: process error . exitCode is : -1 at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:190) at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:105) at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) [INFO] 2020-05-21 16:13:40.974 - [taskAppId=TASK-14-45-114]:[262] - cancel process: 28845 [INFO] 2020-05-21 16:13:40.986 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[161] - task instance id : 114,task final status : FAILURE`



Which version do you use? It's better to take a screenshot of some more logs

**Comment by jzmq** [comment]
DS version : 1.2.1
Hadoop version: hdp 2.7.3 installed with ambari
maybe yarn resources web analysis error

**Comment by Eights-Li** [comment]
please check worker logs for this sqoop job. when sqoop job finished, ds-worker will check the yarn app status through yarn apis. So you should check the yarn conf in dolphinscheduler. single yarn ip or yarn HA ips in dolphinscheduler/conf
