### ISSUE TITLE
[BUG] version1.1 When a large text is modified (>300KB), click Submit and find that the document is truncated to upload

### ISSUE THREAD

**Issue by VENSCC** [apache/incubator-dolphinscheduler#2616]
BUG位置：资源中心>>文件管理>>修改文件
BUG复现：
1、创建原始文档300kb
2、展示没有问题
3、修改其中一行，点击提交
4、发现文档被截断了，只剩（100kb）

初步判断是资源文件更新接口问题

**Comment by xingchun-chen** [comment]
I did not reproduce in the dev branch, what kind of file did you create?

**Comment by xingchun-chen** [comment]
please update the title in english

**Comment by break60** [comment]
The dev branch has been repaired, and it can only transfer up to 3000 lines. If it exceeds 3000 lines, it will not be uploaded. It is recommended to upload files in the form of more than 3000 lines.

**Comment by VENSCC** [comment]
> I did not reproduce in the dev branch, what kind of file did you create?

I tried the sh/sql file. it's Repetition

**Comment by VENSCC** [comment]
> The dev branch has been repaired, and it can only transfer up to 3000 lines. If it exceeds 3000 lines, it will not be uploaded. It is recommended to upload files in the form of more than 3000 lines.

no，i tried again, I've found that only that part of the line is truncated more than 2000 lines.

**Comment by break60** [comment]
> > The dev branch has been repaired, and it can only transfer up to 3000 lines. If it exceeds 3000 lines, it will not be uploaded. It is recommended to upload files in the form of more than 3000 lines.
> 
> no，i tried again, I've found that only that part of the line is truncated more than 2000 lines.

Are you sure that your current version is a dev branch?

**Comment by VENSCC** [comment]
> > > The dev branch has been repaired, and it can only transfer up to 3000 lines. If it exceeds 3000 lines, it will not be uploaded. It is recommended to upload files in the form of more than 3000 lines.
> > 
> > 
> > no，i tried again, I've found that only that part of the line is truncated more than 2000 lines.
> 
> Are you sure that your current version is a dev branch?

MysqlTable   t_escheduler_version     ：version=1.1.0

**Comment by break60** [comment]
> > > > The dev branch has been repaired, and it can only transfer up to 3000 lines. If it exceeds 3000 lines, it will not be uploaded. It is recommended to upload files in the form of more than 3000 lines.
> > > 
> > > 
> > > no，i tried again, I've found that only that part of the line is truncated more than 2000 lines.
> > 
> > 
> > Are you sure that your current version is a dev branch?
> 
> MysqlTable t_escheduler_version ：version=1.1.0

We fixed this problem in the upcoming 1.3.0 version. We can only enter 3000 lines at most. We will not let him save more than 3000 lines.
