### ISSUE TITLE
[BUG]  /dolphinscheduler/projects/create doesn't return project ID when create successfuly

### ISSUE THREAD

**Issue by GabrielWithTina** [apache/incubator-dolphinscheduler#2619]
**Describe the bug**
V1.2.0, when  invoke /dolphinscheduler/projects/create, it doesn't return project ID when create successfuly just return
 {
    "code": 0,
    "msg": "success",
    "data": null
}

**Expected behavior**
it should return project ID, otherwise, how can I build relationship between dolphin and my system.

**Which version of Dolphin Scheduler:**
 -[1.2.0]

**Additional context**

**Requirement or improvement
- Please fix this or tell me how to get project ID for newly created project.

**Comment by dailidong** [comment]
would you like to submit a PR to solve this problem?

**Comment by CalvinKirs** [comment]
What puzzles me is, why do you need to return all the project information?

**Comment by zhuangchong** [comment]
I think just return the project ID.

**Comment by CalvinKirs** [comment]
> I think just return the project ID.

I think so too

**Comment by gabry-lab** [comment]
I think we'd better don't return all the infos of the created project,however, ID is the only field we need.
