### ISSUE TITLE
[BUG] run shell task error in worker server use idea

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#2623]
*For better global communication, please give priority to using English description, thx! *

i use apple as startup user, hdfs as tenant
when  running a shell task, there are  some permission error:

```
[root@node2 dev]#  sudo -u hdfs sh /tmp/dolphinscheduler/exec/process/1/1/111/206/1_111_206.command
/tmp/dolphinscheduler/exec/process/1/1/111/206/1_111_206.command: line 4: /home/apple/.bash_profile: Permission denied
```

version：dev

**Comment by lenboo** [comment]
find out something here:

![image](https://user-images.githubusercontent.com/29528966/81281143-07dd8280-908c-11ea-8b7d-e5cec07411c7.png)

the configuration of env path in common.properties is not opened default.
i think we should open the configuration in common.properties and cannot find 'envpath' from 'user.home'

**Comment by ywywn** [comment]
It means execute command using user 'hdfs' when you use 'sudo -u hdfs', but this file owner is 'apple ', example, I use 'dolphinscheduler' as startup user, like this 
![image](https://user-images.githubusercontent.com/26102201/81360014-449d8e00-910d-11ea-81cc-2ce19afb8cc5.png)
the tenant you set is actual command execution user, but 'hdfs' is usually a special user about authority, try another user and it work fine？

**Comment by lenboo** [comment]
i find the problem:
the logic of this code is when the default 'env/dolphinscheduler.env' not exists, system would use the startup user home profile, because of the startup user is not same as the tenant, that can cause permissions problems.
if we start worker server from command line normally, there is no problem, because 'env/dolphinsheduler.env' exists in the 'conf' folder.
but i start worker server from idea, the 'env/dolphinscheduler.env' is not exists in 'common' moudle, so the permission problem arise.

**Comment by liukunyuan** [comment]
This closed .#3137
https://github.com/apache/incubator-dolphinscheduler/pull/3137

**Comment by CycloneBoy** [comment]
This bug has been fixed.
[source code of branch dev: CommonUtils.java](https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/CommonUtils.java)

```java
 /**
   * @return get the path of system environment variables
   */
  public static String getSystemEnvPath() {
    String envPath = PropertyUtils.getString(Constants.DOLPHINSCHEDULER_ENV_PATH);
    if (StringUtils.isEmpty(envPath)) {
      URL envDefaultPath = CommonUtils.class.getClassLoader().getResource(Constants.ENV_PATH);

      if (envDefaultPath != null){
        envPath = envDefaultPath.getPath();
        logger.debug("env path :{}", envPath);
      }else{
        envPath =  "/etc/profile";
      }
    }

    return envPath;
  }
```
