### ISSUE TITLE
[BUG] allways fail when a task instance submit multiple yarn application

### ISSUE THREAD

**Issue by LinkSe7en** [apache/incubator-dolphinscheduler#2624]
ds will write all yarn app_ids at table **t_ds_task_instance**, **app_link** column. 
If is over 255 charters(limit of this varchar column) , mysql driver will throw com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'app_link' at row 1
And treat this task instance as a failure
![image](https://user-images.githubusercontent.com/16174111/81312485-476e9380-90b9-11ea-9aad-ed009db899b1.png)
![image](https://user-images.githubusercontent.com/16174111/81312517-4ccbde00-90b9-11ea-8c07-e9bdb878a0c3.png)

**Comment by LinkSe7en** [comment]
and shell task return code is 0, not -1 in log
![image](https://user-images.githubusercontent.com/16174111/81313390-64579680-90ba-11ea-9339-577609282a2d.png)

![image](https://user-images.githubusercontent.com/16174111/81313322-530e8a00-90ba-11ea-96ef-e144ed952d6f.png)

**Comment by itbasketplayer** [comment]
You should alter app_link's type to longtext，then work well

**Comment by Eights-Li** [comment]
this bug have fix in dev. 
pr: https://github.com/apache/incubator-dolphinscheduler/commit/91ecc549a1d7cfae2ead6eb16b5e5559d13f54e0
