### ISSUE TITLE
add a checking about yarn appIds'state using historyserver,when 'yarn.resourcemanager.max-completed-applications' too small

### ISSUE THREAD

**Issue by itbasketplayer** [apache/incubator-dolphinscheduler#2625]
**Is your feature request related to a problem? Please describe.**
SHELL,SPARK,MR,HIVE tasks happend because they creates yarn applications!
when 'yarn.resourcemanager.max-completed-applications' is too small,for example 1000.
DS can't get the yarn appIds's  state successfully

**Describe the solution you'd like**
add a checking about yarn appIds'state using historyserver,when 'yarn.resourcemanager.max-completed-applications' too small

**Describe alternatives you've considered**
HadoopUtils#getApplicationStatus add a query using historyserver restapi when the code not 200 using resourcemanager restapi

**Additional context**

**Comment by dailidong** [comment]
good idea, could you submit a PR to solve this problem?

**Comment by itbasketplayer** [comment]
yeah,I will submit a PR

**Comment by chengshiwen** [comment]
Close by #2848
