### ISSUE TITLE
The current 1.3.0 branch alarm module has no message entry

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2628]
The upcoming 1.3.0 branch, alarm module without SMS alarm entrance, users want to integrate themselves up very troublesome, no entrance.

**Comment by feiyalun** [comment]
即将上线的1.3.0分支，告警模块没有短信告警入口，用户自己想集成上去很麻烦，没有入口。

**Comment by chengshiwen** [comment]
Close since the dev branch has integrated alert plugins
