### ISSUE TITLE
Is there a stand-alone version for debugging on windows?（请问有没有单机版方便在windows上调测）

### ISSUE THREAD

**Issue by itheima-cby** [apache/incubator-dolphinscheduler#263]
Excuse me, the author has this stand-alone version of the project or the stand-alone version of the deployment document, you can use the compiler to run directly on windows, convenient for secondary development and debugging, each time you put the server on the package takes a long time, sometimes Thank you for your hard work!

---
请问作者，这个项目有没有单机版的该项目或者单机版的部署文档，可以在windows上使用编译器直接运行，方便二次开发和调试，每次 打包放上服务器需要比较长的时间，有时候光打日志难以看出问题，十分感谢！

**Comment by lgcareer** [comment]
Stand-alone deployment is currently supported only on the Linux operating system.

**Comment by itheima-cby** [comment]
那请问有相关的部署文档吗？然后之后会有windows单机版吗？
------------------ 原始邮件 ------------------
发件人: "lgcareer"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 晚上6:55
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "小小先生"<821555203@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] 请问有没有单机版方便在windows上调测 (#263)




Stand-alone deployment is currently supported only on the Linux operating system.

**Comment by itheima-cby** [comment]
好的，十分感谢，将会继续关注最新动向




------------------ 原始邮件 ------------------
发件人: "escheduler"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 晚上9:32
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "小小先生"<821555203@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] 请问有没有单机版方便在windows上调测 (#263)




hi, deployment docs please refer to link : https://analysys.github.io/easyscheduler_docs_cn/
 you can debug EasyScheduler on Ubuntu or Mac for now.
 we will support windows in the future!
 thx!

**Comment by xiaoyou0254** [comment]
希望能出一个可以在windows系统中调测的版本，谢谢！

**Comment by dailidong** [comment]
dev branch has supported Running on Windows

**Comment by dailidong** [comment]
#2023

**Comment by dailidong** [comment]
dev branch now support run on Windows   #2023
