### ISSUE TITLE
Improve the security of datasource management

### ISSUE THREAD

**Issue by ChunMengLu** [apache/incubator-dolphinscheduler#2638]
**Is your feature request related to a problem? Please describe.**

Company database account management is relatively strict. We found that when the data source management is updated, the original password is actually brought out.

（公司数据库账号管理比较严格，我们发现目前数据源管理更新得时候实际上是把原始密码给带出来了。）

**Describe the solution you'd like**

The datasources / update-ui interface should not take out the password. The datasources / updateDataSource interface does not update this field without passing the password. You can call the query one more time when the server is updated.

（datasources/update-ui 接口不要将密码带出去，datasources/updateDataSource 接口不传 密码就不更新该字段，服务端更新时可以先多调用一次查询。）

**Comment by xingchun-chen** [comment]
+1  who can fix it
