### ISSUE TITLE
Is there a comparison with the oozie scheduling tool?（是否有和oozie调度工具的比对？）

### ISSUE THREAD

**Issue by vkingnew** [apache/incubator-dolphinscheduler#264]
Is there a comparison with the oozie scheduling tool? What are the advantages and disadvantages of EasyScheduler and oozie, azkanba and airflow? More neutral opinion

---
是否有和oozie调度工具的比对？目前EasyScheduler 和oozie、azkanba和airflow比较有什么优点缺点 ？比较中立的意见

**Comment by dailidong** [comment]
There are some comparisons on the Internet that you can search
