### ISSUE TITLE
[BUG] Permission issues arise with the dev branch using the docker-compose deployment（dev 分支使用docker-compose部署出现权限问题）

### ISSUE THREAD

**Issue by gumupaier** [apache/incubator-dolphinscheduler#2641]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The screenshot below
![image](https://user-images.githubusercontent.com/37896380/81396121-658ad100-9157-11ea-9d76-b66db982eac2.png)

![image](https://user-images.githubusercontent.com/37896380/81396127-67ed2b00-9157-11ea-8a82-37cf6b449d2f.png)

**Comment by zhengrongGG** [comment]
I find hub.docker.com  did not have apache/dolphinscheduler image

**Comment by dailidong** [comment]
We published the first official docker image some days ago, you can install it following the doc: https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html
