### ISSUE TITLE
[QUESTION] 报错提醒不明显

### ISSUE THREAD

**Issue by listenLearning** [apache/incubator-dolphinscheduler#2643]
您好，我是刚搭建的ds，然后我将租户，资源中心等等都创建完成了，按照文档，应该是创建一个工作流，然后我创建了一个脚本类型的工作流，运行了一个echo "hello world"，运行失败了，去看日志，只显示了我失败了，但是没有具体说为什么失败
![image](https://user-images.githubusercontent.com/25893114/81404327-c7533700-9167-11ea-8176-c129ea70031d.png)

**Comment by listenLearning** [comment]
我尽到instance 6这个文件夹里面，看到的日志是"sudo: Sorry, you must have a tty to run sudo"这样的提示

**Comment by samz406** [comment]
Hi ! Please first confirm whether the [deployment manual](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/standalone-deployment.html) 1.3 
 section has been executed，
by the way ,please give priority to using English description, thx!

**Comment by dailidong** [comment]
comment this line "#Default requiretty"  in  the /etc/sudoers  file

**Comment by listenLearning** [comment]
I didn't find anything related to this in the file you mentioned, I found that when I made it password free, I wrote "user ALL=(root) NOPASSWD:ALL", then I changed it to "user ALL=(ALL) NOPASSWD:ALL", but it's still wrong.

**Comment by listenLearning** [comment]
This order "sed -i 's/Defaults    requirett/#Defaults    requirett/g' /etc/sudoers" was executed.
