### ISSUE TITLE
[BUG]Unrecognized VM option 'UseFastAccessorMethods'

### ISSUE THREAD

**Issue by hanfengcan** [apache/incubator-dolphinscheduler#2644]
**Describe the bug**
When do `sh create-dolphinscheduler.sh` in openjdk 11.0.7, Program will exit. 

```
[dolphinscheduler@root script]$ sh create-dolphinscheduler.sh 
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.  

Unrecognized VM option 'UseFastAccessorMethods'  

Error: Could not create the Java Virtual Machine.  

Error: A fatal exception has occurred. Program will exit.  

```

**To Reproduce**
Steps to reproduce the behavior, for example:
run `sh script/create-dolphinscheduler.sh`

**Which version of Dolphin Scheduler:**
 1.2.1

**Comment by hanfengcan** [comment]
openjdk没有相关参数

**Comment by hsupu** [comment]
+1 on 1.3.1, does DS going to fix this in the future?

**Comment by FangyangJz** [comment]
+1 on 2.0.5. On 3.0.0 beta, there is no problem, but api-server, master-server, worker-server cannot connect zookeeper lead to sprintboot start fail. I don't know if it related with openjdk and oracle jdk. Deployment is really a hard obstacle

**Comment by EricGao888** [comment]
Will be fixed by https://github.com/apache/dolphinscheduler/pull/10789
