### ISSUE TITLE
[BUG] dev 1.3.0 branch log to dolphinscheduler-alert-server-xx.out is not split ??

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2648]
Log output file, found no redirection to the specified file，dolphinscheduler-alert.log file is empty。 ？？
![图片](https://user-images.githubusercontent.com/37201886/81461259-2dc66c80-91dd-11ea-8b68-6241bcbf67e2.png)

**Comment by feiyalun** [comment]
日志输出文件，未找到指向指定文件的重定向

**Comment by xingchun-chen** [comment]
Who can solve it, and the gaps in the email content in the picture below
![image](https://user-images.githubusercontent.com/55787491/81462450-31f68800-91e5-11ea-8922-db4ed09f1361.png)

**Comment by liwenhe1993** [comment]
This problem has solved.
