### ISSUE TITLE
[BUG] After deleting the condition node, the save workflow prompts an error

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2649]
![image](https://user-images.githubusercontent.com/55787491/81461307-741bcb80-91dd-11ea-8037-69f257c3f8e8.png)

**Which version of Dolphin Scheduler:**
 -[dev-1.3.0]

**Comment by xingchun-chen** [comment]
@break60

**Comment by break60** [comment]
already fixed
