### ISSUE TITLE
[BUG] Workflow definition cannot be deleted  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2650]
![image](https://user-images.githubusercontent.com/55787491/81461406-0fad3c00-91de-11ea-8df6-63481f7a4e6e.png)

**Which version of Dolphin Scheduler:**
 -[dev-1.3.0]

**Comment by xingchun-chen** [comment]
@break60

**Comment by break60** [comment]
already fixed

**Comment by qiaozhanwei** [comment]
fix bug , please closed in time
