### ISSUE TITLE
sudo: sorry, you must have a tty to run sudo

### ISSUE THREAD

**Issue by listenLearning** [apache/incubator-dolphinscheduler#2651]
I followed the tips on the official website, but I didn't find anything related to "defaults requiretty" under /etc/sudoers, then I looked for another way to solve the problem, I added something like "defaults !thx

**Comment by listenLearning** [comment]
I have already licensed the folder to the installer, and the shell script I created in the installation directory will not have this problem.

**Comment by gaojun2048** [comment]
Great, can I close this issue now?

**Comment by listenLearning** [comment]
I mean I don't have this problem with scripts I create myself, but DS does have this problem all the time

**Comment by listenLearning** [comment]
![image](https://user-images.githubusercontent.com/25893114/81461896-797b1500-91e1-11ea-99c2-602c16561aaa.png)

**Comment by gaojun2048** [comment]
> I mean I don't have this problem with scripts I create myself, but DS does have this problem all the time

Sorry , what`s the os and os version?

**Comment by listenLearning** [comment]
Tencent provides cloud hosting.
The server version is. centos 7.2 64bit
dolphinschedler version is : 1.2.0

**Comment by listenLearning** [comment]
![image](https://user-images.githubusercontent.com/25893114/81461999-2b1a4600-91e2-11ea-9ae2-3ff15c157a29.png)
This is my executive order.

**Comment by listenLearning** [comment]
> > I mean I don't have this problem with scripts I create myself, but DS does have this problem all the time
> 
> Sorry , what`s the os and os version?

Tencent provides cloud hosting.
The server version is. centos 7.2 64bit
dolphinschedler version is : 1.2.0

**Comment by gaojun2048** [comment]
Can you edit the /etc/sudoers file and comment out the `Defaults   !visiblepw` ?  Then you should restart the DS worker server.

**Comment by listenLearning** [comment]
> Can you edit the /etc/sudoers file and comment out the `Defaults !visiblepw` ? Then you should restart the DS worker server.
![image](https://user-images.githubusercontent.com/25893114/81462426-f6f45480-91e4-11ea-8e37-28e52a688030.png)
I annotated them all and rerun the ds cluster in the master node using the start-all.sh script, but it didn't seem to work!

**Comment by listenLearning** [comment]
> > Can you edit the /etc/sudoers file and comment out the `Defaults !visiblepw` ? Then you should restart the DS worker server.
> > ![image](https://user-images.githubusercontent.com/25893114/81462426-f6f45480-91e4-11ea-8e37-28e52a688030.png)
> > I annotated them all and rerun the ds cluster in the master node using the start-all.sh script, but it didn't seem to work!

![image](https://user-images.githubusercontent.com/25893114/81462475-581c2800-91e5-11ea-8a3e-c440257a08c8.png)
在集群里面创建的用户组是hdfs

**Comment by gaojun2048** [comment]
Try to add this line in /etc/sudoers file 
```
Defaults:%hdfs !requiretty
```

**Comment by listenLearning** [comment]
> Defaults:%hdfs !requiretty

Following your suggestion, I've added this paragraph, but it's still not working

**Comment by listenLearning** [comment]
> > Defaults:%hdfs !requiretty
> 
> Following your suggestion, I've added this paragraph, but it's still not working

Should I also add sudo-free for the user groups I create?

**Comment by gaojun2048** [comment]
> > Defaults:%hdfs !requiretty
> 
> Following your suggestion, I've added this paragraph, but it's still not working

This question is very strange, you can see if this blog can solve your problem, especially 
```
Defaults visiblepw
```
https://cloud.tencent.com/developer/article/1433543

**Comment by listenLearning** [comment]
> > > Defaults:%hdfs !requiretty
> > 
> > 
> > Following your suggestion, I've added this paragraph, but it's still not working
> 
> This question is very strange, you can see if this blog can solve your problem, especially
> 
> ```
> Defaults visiblepw
> ```
> 
> https://cloud.tencent.com/developer/article/1433543

I've also tried this method, doing the same operation on every machine and it still doesn't work, but I can execute it successfully when I take this command out of the log and run it, I'm not sure why I'm having this problem when it's executed inside the DS
![image](https://user-images.githubusercontent.com/25893114/81465449-d7692600-91fc-11ea-842b-0ec64e634d08.png)
![image](https://user-images.githubusercontent.com/25893114/81465466-ecde5000-91fc-11ea-91e5-f49093613aa3.png)
![image](https://user-images.githubusercontent.com/25893114/81465493-0e3f3c00-91fd-11ea-8919-3ddf6eac90c0.png)

**Comment by gaojun2048** [comment]
> > > > Defaults:%hdfs !requiretty
> > > 
> > > 
> > > Following your suggestion, I've added this paragraph, but it's still not working
> > 
> > 
> > This question is very strange, you can see if this blog can solve your problem, especially
> > ```
> > Defaults visiblepw
> > ```
> > 
> > 
> > https://cloud.tencent.com/developer/article/1433543
> 
> I've also tried this method, doing the same operation on every machine and it still doesn't work, but I can execute it successfully when I take this command out of the log and run it, I'm not sure why I'm having this problem when it's executed inside the DS
> ![image](https://user-images.githubusercontent.com/25893114/81465449-d7692600-91fc-11ea-842b-0ec64e634d08.png)
> ![image](https://user-images.githubusercontent.com/25893114/81465466-ecde5000-91fc-11ea-91e5-f49093613aa3.png)
> ![image](https://user-images.githubusercontent.com/25893114/81465493-0e3f3c00-91fd-11ea-8919-3ddf6eac90c0.png)

Because DS use java Runtime.exec to run the script , Is not the same as executing the script directly in the terminal

**Comment by listenLearning** [comment]
> > > > > Defaults:%hdfs !requiretty
> > > > 
> > > > 
> > > > Following your suggestion, I've added this paragraph, but it's still not working
> > > 
> > > 
> > > This question is very strange, you can see if this blog can solve your problem, especially
> > > ```
> > > Defaults visiblepw
> > > ```
> > > 
> > > 
> > > https://cloud.tencent.com/developer/article/1433543
> > 
> > 
> > I've also tried this method, doing the same operation on every machine and it still doesn't work, but I can execute it successfully when I take this command out of the log and run it, I'm not sure why I'm having this problem when it's executed inside the DS
> > ![image](https://user-images.githubusercontent.com/25893114/81465449-d7692600-91fc-11ea-842b-0ec64e634d08.png)
> > ![image](https://user-images.githubusercontent.com/25893114/81465466-ecde5000-91fc-11ea-91e5-f49093613aa3.png)
> > ![image](https://user-images.githubusercontent.com/25893114/81465493-0e3f3c00-91fd-11ea-8919-3ddf6eac90c0.png)
> 
> Because DS use java Runtime.exec to run the script , Is not the same as executing the script directly in the terminal

![image](https://user-images.githubusercontent.com/25893114/81466177-09c95200-9202-11ea-961b-ab8b97924c7f.png)
Well, I really don't know what to do with this problem, I just rebooted the server and I found that I can't get into the admin interface now, how can I uninstall this? I think I might need to try the installation again.

**Comment by gaojun2048** [comment]
this is my sudoers file:
```

Defaults    always_set_home
Defaults    match_group_by_gid

Defaults    always_query_group_plugin

Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"

Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin

root    ALL=(ALL)       ALL

%wheel  ALL=(ALL)       ALL
```
you can update your /etc/sudoers file and copy my content in the file. In my case, its ok.
Another thing you need to confirm is whether your sudo has been alisa. You can run `alias` command to show it.

**Comment by listenLearning** [comment]
> this is my sudoers file:
> 
> ```
> 
> Defaults    always_set_home
> Defaults    match_group_by_gid
> 
> Defaults    always_query_group_plugin
> 
> Defaults    env_reset
> Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"
> Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
> Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
> Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
> Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
> 
> Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
> 
> root    ALL=(ALL)       ALL
> 
> %wheel  ALL=(ALL)       ALL
> ```
> 
> you can update your /etc/sudoers file and copy my content in the file. In my case, its ok.
> Another thing you need to confirm is whether your sudo has been alisa. You can run `alias` command to show it.

![image](https://user-images.githubusercontent.com/25893114/81469238-85cd9500-9216-11ea-9885-b401bd1c729e.png)
I posted the file you sent to my own server and executed my script, but I found out that my service had been running, just not committing, I went to check my service status and all my services were running and not stopping!

**Comment by listenLearning** [comment]
> this is my sudoers file:
> 
> ```
> 
> Defaults    always_set_home
> Defaults    match_group_by_gid
> 
> Defaults    always_query_group_plugin
> 
> Defaults    env_reset
> Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"
> Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
> Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
> Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
> Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
> 
> Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
> 
> root    ALL=(ALL)       ALL
> 
> %wheel  ALL=(ALL)       ALL
> ```
> 
> you can update your /etc/sudoers file and copy my content in the file. In my case, its ok.
> Another thing you need to confirm is whether your sudo has been alisa. You can run `alias` command to show it.

运行结束了，失败了，还是同样的问题
![image](https://user-images.githubusercontent.com/25893114/81469275-caf1c700-9216-11ea-8dd4-fc95930da6ca.png)

**Comment by gaojun2048** [comment]
@qiaozhanwei  Can you help him ?

**Comment by listenLearning** [comment]
> @qiaozhanwei Can you help him ?

Or can you send me the installation documentation for the docker method?

**Comment by qiaozhanwei** [comment]
if  centos 6 , please

vi /etc/sudoers 

root ALL=(ALL)       NOPASSWD: NOPASSWD: ALL

# Comment out Default requiretty  row
#Default requiretty

**Comment by listenLearning** [comment]
> root ALL=(ALL) NOPASSWD: NOPASSWD: ALL

I don't have that line in my file.

**Comment by qiaozhanwei** [comment]
add me weixin qiao825193156，Private talk
