### ISSUE TITLE
dev 1.3.0 How to use the conditional branch node? Can you explain?

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2652]
How to use the conditional branch node? Can you explain?How to use conditional judgment node? Could you please introduce it?At present, I also found a bug, that is, after the conditional judgment node is successfully created in the front page, it is deleted, and then click save workflow to report an error.
![图片](https://user-images.githubusercontent.com/37201886/81461774-ada20600-91e0-11ea-94e6-90196d1e764b.png)

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/81461953-e1316000-91e1-11ea-80f2-71b876b8813f.png)
![image](https://user-images.githubusercontent.com/55787491/81461942-ceb72680-91e1-11ea-8773-0dd5fd2e0f70.png)

**Comment by wAlec1102** [comment]
It's better to put the part of "custom parameters" into the document or something else
