### ISSUE TITLE
[BUG] the log file size rise rapidly when start DS service

### ISSUE THREAD

**Issue by swordspoet** [apache/incubator-dolphinscheduler#2653]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
When I start the DS service, the logs size in logs directory rises rapidly to almost 20G, so I can't start DS, because this must not be normal.

The error info shows that there is a JDBC Connection exception with druid, as I know so far, the druid setting in DS is default, I don't know the reason result in this problem. Thanks!

**To Reproduce**
Steps to reproduce the behavior, for example:

`sh ./bin/start-all.sh`

**Screenshots**

![image](https://user-images.githubusercontent.com/14816130/81462121-cd3a2e00-91e2-11ea-884c-1191262785c6.png)

**Which version of Dolphin Scheduler:**
 -[1.2]

**Comment by xingchun-chen** [comment]
@lgcareer

**Comment by lgcareer** [comment]
You can check whether your datasource connection information is ok?

**Comment by swordspoet** [comment]
> You can check whether your datasource connection information is ok?

You are right, my datasource is set wrong.
