### ISSUE TITLE
[BUG]  When I modify the workflow definition, the flowchart can pull multiple lines

### ISSUE THREAD

**Issue by 1445103710** [apache/incubator-dolphinscheduler#2663]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42244568/81468920-f1166780-9214-11ea-9147-4af546e74e3d.png)

When I modify the workflow definition, the flowchart can pull multiple lines

**Which version of Dolphin Scheduler:**
 -[1.3.0-dev]

**Comment by 1445103710** [comment]
@dailidong

**Comment by break60** [comment]
May I ask what browser you are using, we did not appear this kind of situation you said
