### ISSUE TITLE
1.3.0 Fault tolerance is identified as yes,  dolphinscheduler how should the logic be controlled

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2667]
1.3.0 Fault tolerance is identified as yes,  dolphinscheduler how should the logic be controlled
![图片](https://user-images.githubusercontent.com/37201886/81472566-8d4b6900-922b-11ea-8022-c802837b95f6.png)
When I restarted all the services, it was the same,

**Comment by xingchun-chen** [comment]
When the workflow status is submitted successfully, executing, ready to pause, or ready to stop, if the master hangs up,  when the master restarts, the workflow is fault-tolerant, the fault-tolerant flag is YES
