### ISSUE TITLE
process instance stop cannot support all the of task type 

### ISSUE THREAD

**Issue by jiakai908** [apache/incubator-dolphinscheduler#2670]
when we stop the process instance,case when task type is SQLTask. this way is not access.

**Comment by break60** [comment]
Are you a process instance stopped, sql task is not accessible or does not support other task types?
Can you describe it in detail

**Comment by xingchun-chen** [comment]
I don't understand what the problem is, can you describe it in detail

**Comment by break60** [comment]
https://jingyan.baidu.com/article/870c6fc3466434b03fe4beea.html

**Comment by gabrywu** [comment]
@jiakai908 Is your problem resolved? If you don't reply for a long time, I will close this issue firstly
