### ISSUE TITLE
[Feature] Hourly dependency configuration

### ISSUE THREAD

**Issue by xuchangqun** [apache/incubator-dolphinscheduler#2680]
1.现在有一种任务配置场景为 任务A 依赖 任务B,并且依赖的时间为'当前小时',
现有的小时维度的依赖配置为'小时':'前1小时,前2小时,前3小时'
请问是否可以增加一个依赖项为 '小时','当前小时';

2.第二种场景,有一个任务A是天任务,每天10:00执行;
任务B是小时任务,执行时间为每小时的01分执行,那么一天就会有24条执行记录;
从01点开始,到第二天00点结束,共24个小时
请问是否可以支持配置依赖项 任务A(2020-05-11 10:00) 依赖 任务B [2020-05-10(01,02,03-23,) + 2020-05-11 00]

1. Now there is a task configuration scenario where task A depends on task B and the dependent time is 'current hour'.
Existing hour dimension dependencies are configured as 'hours':'1 hour before, 2 hours before, 3 hours before'
Is it possible to add a dependency to 'hour','current hour';

2. In the second scenario, A task 'A' is a daily task, which is executed at 10:00 every day;
Task B is an hourly task, and the execution time is 01 minutes per hour, so there will be 24 execution records in one day.(From 01 o'clock to the end of 00 o'clock the next day, a total of 24 hours)
Can you support configuring dependency task A(2020-05-11 10:00) dependency task B [2020-05-10(01,02,03-23,) + 2020-05-11 00]
Thanks.

**Comment by dailidong** [comment]
good job
