### ISSUE TITLE
[Feature]add mysql jdbc connector to docker image

### ISSUE THREAD

**Issue by mkdym** [apache/incubator-dolphinscheduler#2685]
**Is your feature request related to a problem? Please describe.**
Docker image do not include mysql jdbc connector, as a newer to ds, I always need to copy mysql jdbc connector lib to the docker container and restart it.
Mysql is the more popular database(I think) than ck, mssql which are packaged in docker image, so I think, ds should package it in docker image.

**Comment by dailidong** [comment]
the license of mysql jdbc connector not compitable with apache v2 license, so it can't be included by us
