### ISSUE TITLE
[Feature]use supervisor(or other) to manage the daemon processes in docker

### ISSUE THREAD

**Issue by mkdym** [apache/incubator-dolphinscheduler#2687]
**Is your feature request related to a problem? Please describe.**
DS docker should use `supervisor`(or other) to control the daemon processes, rather then start it with `&`  which can not restart when exited abnormally.

And DS can manage the logs of master or worker, if use `supervisor`, rather than
```shell
cd /opt/dolphinscheduler/logs
tail -f xx.out -f xx.log
```

**Comment by dailidong** [comment]
good idea

**Comment by chengshiwen** [comment]
@mkdym `supervisor` is a good way to manage multiple processes. But for logs, there are something to do, because supervisor logs will be printed in `docker logs` or `kubectl logs` instead of logs of master or worker
