### ISSUE TITLE
[Feature]config local resource manager as default instead of upsupported in docker

### ISSUE THREAD

**Issue by mkdym** [apache/incubator-dolphinscheduler#2689]
**Is your feature request related to a problem? Please describe.**
By default, DS docker image set `resource.storage.type=NONE`, so we can not use the feature `resource manager`.
But I think, we should set local storage type as default for the new people, like me, only want to try all features in the first `meet`. Instead of finding a solution in the issues, by himself/herself, and re-config to use resource manager. 
This will be friendly to the new one if set local resource manager as default.

**Comment by mkdym** [comment]
I set local resource manager as the following issue mentioned:
https://github.com/apache/incubator-dolphinscheduler/pull/267

**Comment by dailidong** [comment]
good job
We published the first official docker image some days ago, you can install it following the doc: https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html

**Comment by dailidong** [comment]
> good job
> We published the first official docker image some days ago, you can install it following the doc: https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html

by the way, this image can upload files to resource center
