### ISSUE TITLE
[QUESTION] can conditional task type add some content on the line？ 

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#2695]
can conditional task type add some content on the line:

"success" go which task 
"failure" go which task
 
**Which version of DolphinScheduler:**
 -[dev-1.3.0]

and expect the result like this:
![image](https://user-images.githubusercontent.com/15833811/81666730-ff62be80-9474-11ea-99b8-f38a9010f97c.png)

**Comment by dailidong** [comment]
@break60  if you are free , please consider this problem, thx

**Comment by break60** [comment]
👌

**Comment by xingchun-chen** [comment]
version 1.3.2 had add
