### ISSUE TITLE
NettyRemotingServer bind fail Address already in use,  exit？？？

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2703]
![图片](https://user-images.githubusercontent.com/37201886/81780125-90df3880-9528-11ea-985b-5a6178ada7ee.png)
![图片](https://user-images.githubusercontent.com/37201886/81780618-680b7300-9529-11ea-9194-d5e427adc5e6.png)
![图片](https://user-images.githubusercontent.com/37201886/81780627-6b9efa00-9529-11ea-9e0b-48648be5d768.png)
I packaged the dev1.3.0 branch on a new server and reported an error，
![图片](https://user-images.githubusercontent.com/37201886/81780832-c0427500-9529-11ea-87f1-2663a9bf438a.png)
Check that the port is not occupied

**Comment by feiyalun** [comment]
重启我也试了 不行，  有人怀疑是masterserver自己占用自己的端口号了。 我master启动日志报错，但是master服务启动成功了

**Comment by dailidong** [comment]
which version do you use?

**Comment by DingPengfei** [comment]
I have the same issue in my local pc env, how did you solve that?

**Comment by tangyungteng** [comment]
If you are sure that the port is not occupied by another program, please check whether the address here in the two configuration files is the same, if it is the same, this will cause this error(dolphinscheduler-3.1.8/alert-server/conf)
<img width="712" alt="f430c20445b2a95c99cbbf0e8c8772a" src="https://github.com/user-attachments/assets/71b9ac89-5978-4da9-8c96-5807a068bedd">
<img width="751" alt="926c46cf17997c81759526475f98eea" src="https://github.com/user-attachments/assets/00b00bbf-4efa-4ead-acf8-f72e408873ff">
