### ISSUE TITLE
[BUG] MasterExecThread frequently create/destroy thread pool.

### ISSUE THREAD

**Issue by buildupchao** [apache/incubator-dolphinscheduler#2711]
**Describe the bug**
In branch dev-1.3.0, MasterExecThread frequently create and destroy thread pool. Furthermore, you only use the thread pool once each time, why do you frequently create and destroy thread pool?  it's a misuse!

在 dev-1.3.0分支中，MasterExecThread 线程中频繁的进行线程池的创建和销毁。更进一步来说，既然每次只使用一次线程池，为啥要频繁的创建和销毁呢？这显然是一种线程池的错误使用方式！

**Screenshots**
![1](https://user-images.githubusercontent.com/25910406/81890726-3ce05c80-95d9-11ea-9bc0-28f9b45e38bd.png)
![1 2](https://user-images.githubusercontent.com/25910406/81890728-3e118980-95d9-11ea-8612-42342fe063e3.png)
![1 3](https://user-images.githubusercontent.com/25910406/81890732-3f42b680-95d9-11ea-88b8-3194ddb3a055.png)

**Comment by dailidong** [comment]
good idea， thread is a heavy resource in the Operating System
we will update policy in use Thread

**Comment by xingchun-chen** [comment]
@qiaozhanwei  Please confirm the issue

**Comment by hermeshephaestus** [comment]
OK, I will fix this issue.  @qiaozhanwei @xingchun-chen

**Comment by CalvinKirs** [comment]
We will focus on discussing and optimizing these issues in the near future. You can read this and follow this issue #4983. You are very welcome to participate.
