### ISSUE TITLE
[BUG] [Worker group manage]  No buttons added

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#2714]
Worker group manage 
No buttons added

![image](https://user-images.githubusercontent.com/39816903/81903776-d8cb9180-95f4-11ea-98cb-94ca1e6a1db5.png)

**Comment by dailidong** [comment]
which version ? 

if 1.3.0 , we want to support k8s, while the ip always will be changed, so can't config on the UI ,  worker can config group name in the worker.properties

**Comment by BoYiZhang** [comment]
ok
