### ISSUE TITLE
compile error on UsersServiceTest

### ISSUE THREAD

**Issue by oceanos** [apache/incubator-dolphinscheduler#2715]
**Describe the bug**

compile error on UsersServiceTest.java

**To Reproduce**

mvn package

**Expected behavior**
remove unused import

**Screenshots**
![image](https://user-images.githubusercontent.com/11856424/81902918-80e05b00-95f3-11ea-854b-f16cf271177b.png)

**Which version of Dolphin Scheduler:**
 -[dev-1.3.0]
 -[dev]

**Comment by gabrywu** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/2718 will be closed , this issue can be closed

**Comment by gabrywu** [comment]
By the way ,this is not error ,just warning
