### ISSUE TITLE
[QUESTION] ssh2.channel message out

### ISSUE THREAD

**Issue by mqq8685** [apache/incubator-dolphinscheduler#2716]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**

When using SSH to connect to a server, the information from the standard output stream is written to the error output stream and all the standard output stream is empty.  How to solve this problem？thanks.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved?
