### ISSUE TITLE
[QUESTION] How to hold current flow instance to waiting for something ready

### ISSUE THREAD

**Issue by xiashao1980** [apache/incubator-dolphinscheduler#2727]
I want to write some Python scripts in a node to implement the following function:
1.  Send a message to a queue
2.  Waiting for another program to finish processing this message 
3. Then go to the next step or return fault message.

There are more than 10000 instances in my list, all of them need to hold the flow instance and wait for some resource released or unlocked.

How to implement this function?
------------------------------------------------------------------
如何在节点的Python脚本中实现任务的等待？ 可能的任务实例上万，需要考虑上万个任务同时等待的情况。 谢谢！

**Comment by xiashao1980** [comment]
I need to call a service to do something async and wait for the 3rd system callback(in seconds or days). And if there are 10000 instances, I should send them all to the 3rd system and wait for the callback. If the result is ok, then go to the next step. If it is not ok, then change the status of the current instance to error.
----
我其实想要异步调用第三方系统的服务，并等待第三方系统的异步回调。 并根据回调的结果，确定当前流程是继续，还是报错。

这个异步调用可能会耗时时一两天，或者几秒，也都可能出错，我需要根据回调反馈来决定实例的具体状态。

**Comment by dailidong** [comment]
does python task can solve this problem, you business logical code could write in the python task?  OK ?

**Comment by gabrywu** [comment]
@xiashao1980 Yes I think @dailidong is right. You can output the 3rd system's result to somewhere , then python task waiting for the result.
