### ISSUE TITLE
[BUG]The IP and process pid of the master and worker in the monitoring center are not displayed  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2735]
![image](https://user-images.githubusercontent.com/55787491/82179785-c06bb780-9911-11ea-996a-ec3aad68bf41.png)

![image](https://user-images.githubusercontent.com/55787491/82179769-b5188c00-9911-11ea-8e31-699b85b3a304.png)

**Which version of Dolphin Scheduler:**
 -[dev_1.3.0]

**Comment by tlhhup** [comment]
i will fix it.

**Comment by lenboo** [comment]
> i will fix it.

very good!
