### ISSUE TITLE
[BUG] TaskExecutionContextCacheManagerImpl Do not execute removeByTaskInstanceId

### ISSUE THREAD

**Issue by 1445103710** [apache/incubator-dolphinscheduler#2745]
**Describe the bug**
worker

TaskExecutionContextCacheManagerImpl Do not execute removeByTaskInstanceId

Causing the map to gradually become larger

![image](https://user-images.githubusercontent.com/42244568/82195487-f1a4b180-992a-11ea-8855-7bce03b5839a.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by 1445103710** [comment]
@dailidong

**Comment by dailidong** [comment]
very good job, 
would you like to submit a PR to solve this problem?

**Comment by 1445103710** [comment]
Thanks，
I haven't experienced PR submission. I'm glad to do something about it. Let me see again. I'll try to submit PR tomorrow




 原始邮件 
发件人: dailidong<notifications@github.com>
收件人: apache/incubator-dolphinscheduler<incubator-dolphinscheduler@noreply.github.com>
抄送: yaoyao<15656009880@163.com>; Author<author@noreply.github.com>
发送时间: 2020年5月18日(周一) 20:05
主题: Re: [apache/incubator-dolphinscheduler] [BUG]TaskExecutionContextCacheManagerImpl Do not execute removeByTaskInstanceId(#2745)


very good job,
 would you like to submit a PR to solve this problem?
