### ISSUE TITLE
[Feature]Add directory functionality in file management

### ISSUE THREAD

**Issue by ly2325yj** [apache/incubator-dolphinscheduler#2755]
Can you add folders in file management to realize file categorization by folder
With the increase of files, management is not convenient
是否可以在文件管理中添加文件夹，实现文件按文件夹归类
随着文件的增加，管理起来不方便

**Comment by break60** [comment]
May I ask which version of the code you are using, the dev-1.3.0 version implements multiple resource directories

**Comment by chengshiwen** [comment]
Close since 1.3.x has been supported
