### ISSUE TITLE
T_ds_process_definition table, some fields are not long enough to cause an error

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2758]
t_ds_task_instance table fields is app_link  ，The field is too short and I recommend changing varchar (255) to longtext， or  varchar（2550）
![图片](https://user-images.githubusercontent.com/37201886/82307584-24b27800-99f3-11ea-86c4-6596a97cedd7.png)
![图片](https://user-images.githubusercontent.com/37201886/82307634-34ca5780-99f3-11ea-975d-645851f24f20.png)

**Comment by feiyalun** [comment]
varchar is  make it bigger

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/82623702-5a35ac00-9c13-11ea-8808-b2d03813a259.png)
 app_link is varchar (255) in V1.3.0

**Comment by Eights-Li** [comment]
in dev-1.3.0 this field has been modified to text type, will support multi-stage hql task
