### ISSUE TITLE
branch 1.3.0 The front-end log output is inconsistent

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2759]
![图片](https://user-images.githubusercontent.com/37201886/82313114-80ccca80-99fa-11ea-8845-7d835f44707a.png)
![图片](https://user-images.githubusercontent.com/37201886/82313127-84f8e800-99fa-11ea-87fb-adc7ef71265f.png)
My task ran for about 20 minutes. In the last time, I found that the front-end log was inconsistent with the output log of the background log. May I ask what happened?No error was reported in the log. Finally, the program was executed successfully, but the foreground still shows that it is running.

**Comment by feiyalun** [comment]
我的任务跑了大概20分钟，在最后的时间里发现，前端日志，和后台日志输出的日志不一致， 请问这是怎么回事。日志也没报错，最后程序执行成功了，但是前台，还是显示正在运行中。

**Comment by feiyalun** [comment]
肯定是执行刷新了， 发现跟后端日志差的太多了。

**Comment by break60** [comment]
I see that there are hadoop errors reported on the front end

**Comment by feiyalun** [comment]
但是我发现这个前端日志打印最多1000行日志， 我有的日志比这个多 打印不出来， 在哪设置这个1000行限制参数

**Comment by break60** [comment]
You can click to download the log

**Comment by feiyalun** [comment]
我后来是找到可以下载来看， 但是能在线看不是更好么。 就是显示的不全

**Comment by break60** [comment]
He displays a maximum of 1,000 entries per page. There is a split-screen loading. You can see the next 1,000 entries by pulling down

**Comment by feiyalun** [comment]
在哪点选的，我怎么没找到呢
![图片](https://user-images.githubusercontent.com/37201886/82416547-cba71a80-9aac-11ea-9796-4fbeac0b526f.png)

**Comment by break60** [comment]
Does your mouse have a scroll wheel? Place the cursor in the middle of the screen, and then scroll the mouse wheel down

**Comment by feiyalun** [comment]
怎么往下分页 日志  这块  有人回复我 用鼠标滚轮滑动，我都滑动到最底下了。 怎么分页 这个最多展示1000行
