### ISSUE TITLE
master server logs error

### ISSUE THREAD

**Issue by JohnBarrowman65** [apache/incubator-dolphinscheduler#2771]
**Describe the question**
![image](https://user-images.githubusercontent.com/30208746/82440960-c0191b00-9acf-11ea-9801-5fe1d8bc63f9.png)
![image](https://user-images.githubusercontent.com/30208746/82440971-c5766580-9acf-11ea-9682-90e19ea7bd51.png)

error is :nested exception is com.alibaba.druid.pool.DataSourceClosedException:datasource aleady closed
ps:我本地开发环境是正常跑的，线上测试环境这个问题导致无法生成工作流实例，其他功能都正常使用

**Which version of DolphinScheduler:**
1.2.0

please help me

**Comment by gabrywu** [comment]
@JohnBarrowman65 Maybe your config about jdbc is wrong, so please check your config again carefully. I will close this issue firstly, feel free to reopen it
