### ISSUE TITLE
The RPM package made under the dev-1.3.0 branch will have dependency detection exceptions during installation

### ISSUE THREAD

**Issue by zhangchunyang1024** [apache/incubator-dolphinscheduler#2788]
The RPM package made under the dev-1.3.0 branch will have dependency detection exceptions during installation。
Like that:
$ rpm -ivh apache-dolphinscheduler-incubating-1.2.1-1.noarch.rpm
错误：依赖检测失败：
 osgi(org.eclipse.core.resources) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
 osgi(org.eclipse.core.runtime) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
 osgi(org.eclipse.text) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要

**Comment by gaojun2048** [comment]
Can I close this issue?

**Comment by zhangchunyang1024** [comment]
yeah，it has been resolved
