### ISSUE TITLE
[BUG] The data source center reported an error when creating an Oracle data source:Invalid connection string format

### ISSUE THREAD

**Issue by 743294668** [apache/incubator-dolphinscheduler#2791]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The data source center reported an error when creating an Oracle data source:
org.apache.dolphinscheduler.api.service.DataSourceService:[421] - Invalid connection string format, a valid format is: "//host[:port][/service_name]"

The original question is here:#2632

**To Reproduce**
When creating an Oracle data source in the data source center, according to the API logs, you can see the error, whether it is using the service name or SID.

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement
- The data source center normally adds Oracle data sources

**Comment by dailidong** [comment]
who are interesting in fix it ？ I think it's not difficult

**Comment by 743294668** [comment]
Let me solve it. The development has been completed, and now we need to solve the problem of code coverage

**Comment by 743294668** [comment]
The latest revised code has been submitted for merger application and has passed the code inspection and review. Based on the changes made by # 2812PR, I modified my code. If there are any problems or conflicts, questions or comments are welcome. Thanks.

**Comment by 743294668** [comment]
> who are interesting in fix it ？ I think it's not difficult

The latest patch on this issue has been submitted, can you help review it? Thank you. Please explain if there is any problem.
In addition, I sent an error in the API document that needs to be corrected. I would like to ask how to contribute, or just ask a question. Thanks.

**Comment by 743294668** [comment]
Merged #2970
