### ISSUE TITLE
[BUG] ${map[${host}]} run error using host ip

### ISSUE THREAD

**Issue by brightfox** [apache/incubator-dolphinscheduler#2797]
scp-hosts.sh

# if worker in workersGroup
    if [[ "${map[${host}]}" ]] && [[ "${dsDir}" -eq "conf" ]]; then
      sed -i ${txt} "s#worker.group.*#worker.group=${map[${host}]}#g" $workDir/../conf/worker.properties
    fi

**Comment by nickbaba2012** [comment]
I'm using the latest dev branch, seems the issue has not been fixed, why closed it ?
