### ISSUE TITLE
[BUG] Execute multiple statements in a sql node

### ISSUE THREAD

**Issue by dairui2** [apache/incubator-dolphinscheduler#2805]
Execute multiple statements in a sql node, I use a semicolon to separate, the execution reports a syntax error

**Comment by zixi0825** [comment]
This is not bug ,because sql task is not support the multiple statements separate by semicolon now 
If you need this feature, I can implement it.

**Comment by gabrywu** [comment]
Executing multiple sql is not so easy , so I suggest not support it . If you want to run multiple sql , one-sql-one-task in same DAG is an alternative solution.
I will close this PR firstly ,feel free to reopen it
Refer to https://github.com/apache/incubator-dolphinscheduler/pull/2816
