### ISSUE TITLE
[Feature]Execute multiple statements in a sql node

### ISSUE THREAD

**Issue by dairui2** [apache/incubator-dolphinscheduler#2807]
Execute multiple statements in a sql node, I use a semicolon to separate, the execution reports a syntax error

**Comment by zixi0825** [comment]
I will implement this feature
The implementation logic is as follows:
1. If it is a query type statement, only the first query statement is executed
2. If it is a non-query type statement, it will be divided according to a semicolon and executed sequentially
what do you think about?
-------------------------------------------------------------------------------------------------------
我将会实现这个feature
实现逻辑如下：
1. 如果是查询类型的语句，只执行第一条查询语句
2. 如果是非查询类型的语句，将会根据分号进行划分，依次执行

你有什么想法？

**Comment by dairui2** [comment]
I replace the demands put forward by netizens, your solution is very good, thank u.
