### ISSUE TITLE
[BUG] 工作流启动，界面上无法看到工作流实例和任务实例

### ISSUE THREAD

**Issue by GabrielWithTina** [apache/incubator-dolphinscheduler#2828]
**Describe the bug**
工作流启动，界面上无法看到工作流实例和任务实例，重启所有服务可以看到。

**To Reproduce**
引起的原因是我重启了ZOOKPER服务，WORK自动恢复链接，我看日志WORK是自动重启了，就没有管；这个时候启动的工作流，界面上无法看到工作流实例和任务实例，之后重启DS所有服务可以看到了

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by dailidong** [comment]
have you seen the runtime log of worker/master server? usually you will find some warn/exception info if no instance could be seen

**Comment by dailidong** [comment]
by the way, please update/add title and description in English

**Comment by itbasketplayer** [comment]
This looks like master did not work, not execute split DAG and submit task

**Comment by xingchun-chen** [comment]
After restarting the zookeeper service, you need to restart the master and worker services
