### ISSUE TITLE
[BUG] bug title Use escheduler-1.1.0 to schedule the hive task. Stopping the workflow will lock the table

### ISSUE THREAD

**Issue by jetaime-chen** [apache/incubator-dolphinscheduler#2830]
Use escheduler-1.1.0 to schedule the hive task. Stopping the workflow will lock the table. You need to manually delete the record of the lock table in hive metadata. Is there any way to avoid this problem? Thank you.

使用escheduler-1.1.0版本调度hive任务，停止工作流会锁表

**Comment by dailidong** [comment]
is there some exception info ? or how to reproduce this situation?

**Comment by dailidong** [comment]
By the way, 1.1.0 is not apache version, maybe you can consider update the version

**Comment by jetaime-chen** [comment]
Run the instance on easysscheduler version 1.1.0. The instance is still running. Click Cancel to lock the table without obvious error

**Comment by jetaime-chen** [comment]
Please let me know how to smoothly upgrade easysscheduler scheduling system and switch without affecting existing tasks. Thank you.

**Comment by dailidong** [comment]
you can backup your database first, when there is no job running, you can update.

please refer: https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/upgrade.html

do more test on the test/dev environment before  updating the production
