### ISSUE TITLE
How to use Windows system to debug code ? version1.3.0

### ISSUE THREAD

**Issue by SunHao1234** [apache/incubator-dolphinscheduler#2834]
Using version 1.3.0, debugging with idea under windows can never succeed, but can 1.3.0 be debugged on windows? Ask how to implement, what should be paid attention to or modified? Thanks！

--使用1.3.0版本，在window下idea调试，始终不能成功，但是1.3.0不是可以在windows上调试吗？请教如何实现，需要注意那些东西或者修改那些东西？

**Comment by dailidong** [comment]
you can pull the newest code from dev-1.3.0, if meet some problem , please show the exception info

**Comment by liwenhe1993** [comment]
please refer to #2592
