### ISSUE TITLE
[QUESTION] How to make current process stop in Python script?

### ISSUE THREAD

**Issue by xiashao1980** [apache/incubator-dolphinscheduler#2867]
In my Python script. I want to stop the current process if some condition was true. So how to stop it and report some error message to the UI list?

**Describe the question**
我想在Python节点中当检查到某些条件满足的情况下，我需要停止当前工作流实例并报错。请问是否支持？ 如果用Python脚本实现？

**Which version of DolphinScheduler:**
 -[1.2.0]

Thanks.

**Comment by Rubik-W** [comment]
You can try, when some condition was true, throw exception, and failure strategy set to "end".
the node will set to fail.

**Comment by xiashao1980** [comment]
Sometimes, I need to stop the current instance and ask the user to fix some problems, then resume this flow from the latest step.
I just want to know if there is some existing way to implement this function. Just like return a false result to the worker process. Or use sys.exit(ExitStatus.failure)?

**Comment by dailidong** [comment]
use exit will be OK, if exit result is not 0, the task will be judged as failure, at the same time the workflow will stop if you choose stop when you started the workflow definition,  then you can do some things, and then resume failure from the workflow instance list page
![image](https://user-images.githubusercontent.com/15833811/84459944-38bc6300-ac9b-11ea-9492-4f47eeef3560.png)

**Comment by Rubik-W** [comment]
In process instance list page, you can stop instance or continue instance.

**Comment by gabrywu** [comment]
> use exit will be OK, if exit result is not 0, the task will be judged as failure, at the same time the workflow will stop if you choose stop when you started the workflow definition, then you can do some things, and then resume failure from the workflow instance list page
> ![image](https://user-images.githubusercontent.com/15833811/84459944-38bc6300-ac9b-11ea-9492-4f47eeef3560.png)

@xiashao1980  you can try this way. Feel free to reopen issue if necessary
