### ISSUE TITLE
[QUESTION] python path and version different

### ISSUE THREAD

**Issue by hei-wei** [apache/incubator-dolphinscheduler#2868]
**Which version of DolphinScheduler:**
 -[1.2.0-preview]

export HADOOP_HOME=/opt/cloudera/parcels/CDH-5.11.0-1.cdh5.11.0.p0.34
export HADOOP_CONF_DIR=/opt/soft/hadoop/etc/hadoop
#export SPARK_HOME1=/opt/soft/spark1
#export SPARK_HOME2=/opt/soft/spark2
export PYTHON_HOME=/usr/local/bin/python2
export JAVA_HOME=/usr/java/jdk1.8.0_172
#export HIVE_HOME=/opt/soft/hive
#export FLINK_HOME=/opt/soft/flink
export EDW_HOME="/BIG_DATA/EDW/ZYXF_EDW/PYTHON_APP"
export EDW_PACKAGE_HOME="$EDW_HOME/package"
export EDW_CONFIG_HOME="$EDW_HOME"

export PATH=$HADOOP_HOME/bin:$PYTHON_HOME:$JAVA_HOME/bin:$PATH:$FLINK_HOME/bin:$EDW_HOME:$EDW_PACKAGE_HOME:$EDW_CONFIG_HOME:$PATH

export PYTHON_HOME=/usr/local/bin/python2
python2 --> 2.7.3
but   run python -V
![image](https://user-images.githubusercontent.com/57801501/83478380-4702c600-a4c8-11ea-98d2-5e5a3656ce2b.png)

**Comment by dailidong** [comment]
you only set python2 path, so python2 will show 2.7.3.
 

you can try "which python" to see python's execute path

**Comment by Jave-Chen** [comment]
how about `/usr/local/bin/python2 -v` ?

**Comment by dailidong** [comment]
no reponse from user, temporarily close

**Comment by chinaboyll** [comment]
update properties。
1、update common.properties file, dolphinscheduler.env.path=/data/dolphinscheduler/conf/env/dolphinscheduler_env.sh
2、update /data/dolphinscheduler/conf/env/dolphinscheduler_env.sh 
更新配置文件。
1、更新common.properties 文件下的 dolphinscheduler.env.path= /dolphinscheduler/conf/env/dolphinscheduler_env.sh。
2、更新conf/env/dolphinscheduler_env.sh 文件中环境变量，PYTHON_HOME指向所在版本的Python文件。
