### ISSUE TITLE
[Feature]improve the code coverage of the annotation

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-dolphinscheduler#2871]
We need to improve the annotation coverage of the code, so that it is more friendly to users who contributed for the first time. In addition, it is recommended that the website open a directory to do source code interpretation, which will help us develop contributors .

**Comment by dailidong** [comment]
good idea

**Comment by gabrywu** [comment]
@CalvinKirs  you can refer to this issue: https://github.com/apache/incubator-dolphinscheduler/issues/1123
We can't add too many annotation which will make the code dirty. If you are familiar with java or a  senior java engineer, the source code is not so hard to understand.
