### ISSUE TITLE
[QUESTION] After the task is executed, the log cannot be viewed under the worker group

### ISSUE THREAD

**Issue by wuqingzhi128** [apache/incubator-dolphinscheduler#2874]
After the small dolphin scheduler worker is grouped, the task is executed and the log cannot be viewed. What's the reason and how can I solve it

**Comment by dailidong** [comment]
is logger server started up on the worker machine?

**Comment by CycloneBoy** [comment]
If you are running in idea, you should start the methon of LoggerServer.java#main    in the source code. 

```java
dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerServer.java#main
```
If you start from the command line, you should start logger server  use commond line on the worker's machine 

```shell
sh   bin/dolphinscheduler-daemon.sh start logger-server
```
