### ISSUE TITLE
[BUG] After the workers group, specify a group. The task cannot view the log, but can only download and view it

### ISSUE THREAD

**Issue by wuqingzhi128** [apache/incubator-dolphinscheduler#2875]
**Describe the bug**
After grouping, the task cannot view the log, but if the default grouping is used, the log will be displayed

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Create a workers group
2. Create a test project
3. run the project
4. after look the log is '暂无更多'

**Expected behavior**
i think the log is show the background

**Screenshots**

![image](https://user-images.githubusercontent.com/66063598/83507902-c1990900-a4fb-11ea-839f-b264c4648136.png)

**Which version of Dolphin Scheduler:**
 -1.2.1

**Additional context**

**Requirement or improvement
- i want look the log

**Comment by dailidong** [comment]
is logger server started up ?

**Comment by dailidong** [comment]
could other workflow see the log or not?

**Comment by xingchun-chen** [comment]
Do not reply for a long time, temporarily close the issue
