### ISSUE TITLE
[Feature] Add detail in user_doc/development-environment-setup.html's [搭建后端] section

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#2878]
**Is your feature request related to a problem? Please describe.**
I'm confused when I follow the section to build the db, because there is no description about MySQL db.
When I use the MySQL db, I need to specify the mysql scope as compile in pom.xml to avoid the exception of ClassNotFound for `com.mysql.jdbc.Driver`(5.x)  or `com.mysql.cj.jdbc.Driver`(8.x).

**Describe the solution you'd like**
We need to add specific MySQL description in this section.

**Additional context**
There is the description in [搭建后端] section:
`创建表和初始化数据： 修改dao模块resource目录下application.properties文件中的数据库配置信息，然后执行org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler的类，运行完，刷新数据库，表和数据都有了。`

There is the [link](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/development-environment-setup.html).

**Comment by dailidong** [comment]
thanks for your feedback.

you can submit a PR to dolphinscheduler website github repository:

 https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.2.0/user_doc/development-environment-setup.md
