### ISSUE TITLE
[QUESTION] http task 60s timeout（请问http类型的task60秒超时怎么配置）

### ISSUE THREAD

**Issue by boying52** [apache/incubator-dolphinscheduler#2882]
http task  60's  timeout，how can i setting？request timeout

**Comment by BoYiZhang** [comment]
It can't be set, because the code contains fixed values. You can raise a PR

![image](https://user-images.githubusercontent.com/39816903/83594771-aaf1c100-a592-11ea-9a52-b9bb366725cd.png)

**Comment by gabrywu** [comment]
front end should add one parameter to config the timeout value

**Comment by dailidong** [comment]
> front end should add one parameter to config the timeout value

+1, I think it's easy to implement it, who want to try? please leave a message

**Comment by BoYiZhang** [comment]
hi:


I'll do it




--------------------------------------
BoYi ZhangE-mail : zhangboyi_mx@163.com
在2020年06月4日 17:46，gabry.wu<notifications@github.com> 写道：

front end should add one parameter to config the timeout value
