### ISSUE TITLE
CONDITIONS task is not work 

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#2883]
version dev-1.3.0

![image](https://user-images.githubusercontent.com/39816903/83594162-19358400-a591-11ea-85c0-71540d44fffc.png)

**Comment by break60** [comment]
We don’t have this situation on our side. Can you describe your operation or see if the console reports an error?

**Comment by BoYiZhang** [comment]
As shown in the figure, subsequent tasks that can be selected are not displayed in the drop-down bar

![image](https://user-images.githubusercontent.com/39816903/83600567-6e799180-a5a1-11ea-9642-aabce5981a8b.png)

**Comment by break60** [comment]
Did the console report an error?

**Comment by BoYiZhang** [comment]
No error message

**Comment by break60** [comment]
I didn't reproduce your problem, you are sure that your code is up-to-date

**Comment by BoYiZhang** [comment]
My code is the latest, version dev-1.3.0
If it's OK with someone else, I'll check it out
