### ISSUE TITLE
The Python script is run through the shell and executed successfully, but the return status is failure

### ISSUE THREAD

**Issue by hei-wei** [apache/incubator-dolphinscheduler#2887]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.
![image](https://user-images.githubusercontent.com/57801501/83606763-b520b900-a5ac-11ea-8b74-2d56b7e05929.png)

![image](https://user-images.githubusercontent.com/57801501/83606830-c8338900-a5ac-11ea-8319-e47ffe21ebb1.png)

**Comment by hei-wei** [comment]
Last logs :
	S001_LC_APPL抽取数执行成功！
	
	##################################################
	S001_LC_APPL抽取数执行成功！

but  the return status is failure

**Comment by gabrywu** [comment]
@hei-wei  Can you paste all the logs?

**Comment by gabrywu** [comment]
@hei-wei If you already resolve this error, I will close this issue firstly. Feel free to reopen it. And welcome to tell up how you resolve
