### ISSUE TITLE
Why the task was judged error

### ISSUE THREAD

**Issue by databoyliu** [apache/incubator-dolphinscheduler#2889]
1.2.0
![2020-06-03 16-14-02屏幕截图](https://user-images.githubusercontent.com/31722412/83612922-a4c10c00-a5b5-11ea-8ef4-d45e24a8b7ad.png)
q:
There is no error in running shell task. Why DS thinks the task is error

**Comment by dailidong** [comment]
did you see worker server runtime log about this task?

**Comment by databoyliu** [comment]
> did you see worker server runtime log about this task?

yes,

**Comment by dailidong** [comment]
does all shell task failure? there is no special handle. if it's a yarn task, it also will get the final running result of the yarn, if yarn give failure, the shell task will also failure. you can see the exit code of this shell task in the worker server runtime log, the normal exit code is 0

by the way,  could you paste some script content if it's convenient for you

**Comment by databoyliu** [comment]
1、Same type of task
![2020-06-03 16-14-02屏幕截图](https://user-images.githubusercontent.com/31722412/83619674-c96db180-a5be-11ea-998d-94b3b9ae4f03.png)
２、code
![2020-06-03 17-17-39屏幕截图](https://user-images.githubusercontent.com/31722412/83619934-28332b00-a5bf-11ea-9551-5a1655bd91c3.png)
3、api log
![2020-06-03 17-19-10屏幕截图](https://user-images.githubusercontent.com/31722412/83619982-3ed98200-a5bf-11ea-8f4b-03b995c39b71.png)

**Comment by itbasketplayer** [comment]
The most important is worker log, may be it has ERROR or Exception

**Comment by dailidong** [comment]
> The most important is worker log, may be it has ERROR or Exception

yes, worker log about this task instance is very importent

**Comment by databoyliu** [comment]
> > The most important is worker log, may be it has ERROR or Exception
> 
> yes, worker log about this task instance is very importent

Sure enough, I ignored it，Is it possible that there is something wrong with my configuratio

![2020-06-04 09-14-23屏幕截图](https://user-images.githubusercontent.com/31722412/83704431-a685e080-a644-11ea-9a19-b5f74c7029c4.png)
![2020-06-04 09-14-33屏幕截图](https://user-images.githubusercontent.com/31722412/83704456-b7365680-a644-11ea-8f0f-4820c84cf332.png)

**Comment by databoyliu** [comment]
> > The most important is worker log, may be it has ERROR or Exception
> 
> yes, worker log about this task instance is very importent

What's the problem with this error message

**Comment by 743294668** [comment]
> > > The most important is worker log, may be it has ERROR or Exception
> > 
> > 
> > yes, worker log about this task instance is very importent
> 
> What's the problem with this error message

#2491

**Comment by dailidong** [comment]
have you solved this problem, if solved , please close the issue, thx

**Comment by gabrywu** [comment]
yarn.application.status.address  this parameter already set ?
