### ISSUE TITLE
[BUG] When editing user information, clear the phone number, the database table t_ds_user.phone is not cleared

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2892]
![image](https://user-images.githubusercontent.com/55787491/83727354-7f94d200-a677-11ea-9937-70d96123137e.png)
![image](https://user-images.githubusercontent.com/55787491/83727493-ba970580-a677-11ea-8dd4-6e1a40201d05.png)

**Which version of Dolphin Scheduler:**
 -[dev-1.3.0]

**Comment by 597365581** [comment]
I will fix this bug ，phone is not must need。but code is

**Comment by 597365581** [comment]
this bug has been fixed.

**Comment by 597365581** [comment]
@xingchun-chen  if bug has fixed,please check and closed.

**Comment by xingchun-chen** [comment]
OK，thanks
