### ISSUE TITLE
[Feature] [Minor] Make the logger server listening port configurable

### ISSUE THREAD

**Issue by xuchangqun** [apache/incubator-dolphinscheduler#2904]
**Is your feature request related to a problem? Please describe.**
Sometimes, other services have the same listening port as the DS logger server and cannot be modified.

**Describe the solution you'd like**
I want to change it according to 'WorkerConfig.java'

**Describe alternatives you've considered**
Normally,the worker server and logger server will exits at same time,and I will put the configuration into worker.properties

**Additional context**
Is there any other impact about port modification.

**Comment by dailidong** [comment]
good idea,  glad to hear that you will implement it

**Comment by xuchangqun** [comment]
I will implement it based on branch dev.
@dailidong

**Comment by dailidong** [comment]
+1 ， and as Tboy said, 
`On ZK, there is a port of worker. If loggerserver is designed well, it is the worker's port + 1
Then, the API gets the worker's port + 1 from ZK. This is normal operation.`

**Comment by chengshiwen** [comment]
Duplicated issue: #5229
So close
