### ISSUE TITLE
[QUESTION] sudo权限申请不到，如何安装使用DS

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#2905]
**Describe the question**
基础设施部门不给开通sudo权限，有什么更好的方法去使用DS,实现多组户

**Comment by dailidong** [comment]
for now,  if not use sudo，can't implement multi tenant

**Comment by dailidong** [comment]
if you don't use multi tenant, you can change source code through search "sudo" in all entire project,then recompile the code

**Comment by gabrywu** [comment]
@zhuangchong Currently DolphinScheduler can't implement multi tenant without sudo permission. So this issue can be closed, feel free to reopen it
