### ISSUE TITLE
[BUG] Start master or worker can not load logback-xx.xml

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#2919]
**Describe the bug**
When I set `System.setProperty("spring.profiles.active", "worker")` and `System.setProperty("spring.profiles.active", "master")` configuration and start master and worker in MacOS, the spring container can not load logback-master.xml or logback-worker.xml automatically.

I've to set `System.setProperty("logging.config", "classpath:logback-worker.xml")` to load the logback-worker.xml.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to 'org.apache.dolphinscheduler.server.worker.WorkerServer' and set `System.setProperty("spring.profiles.active", "worker")` in `main()` function , run the `main()` function.
1. Go to 'org.apache.dolphinscheduler.server.master.MasterServer' and set `System.setProperty("spring.profiles.active", "master")` in `main()` function, run the `main()` function.
2. Submit a Shell task and run it manually.
3. There is a `NPE`.

**Expected behavior**
There is a `NPE` when the `org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.getTaskLogPath()` try to get `TASKLOGFILE`, but it can not get `TASKLOGFILE` defined in `logback-worker.xml` in this function, because the Spring container does not load the `logback-worker.xml`.

**Screenshots**
![image](https://user-images.githubusercontent.com/29545877/83962637-920a4800-a8d1-11ea-9199-ad56073a3d0f.png)

**Which version of Dolphin Scheduler:**
 -[1.3.0]

**Requirement or improvement
- We need to set System.setProperty("logging.config", "classpath:logback-worker.xml") in worker main function and set System.setProperty("logging.config", "classpath:logback-master.xml") in master main function.

**Comment by torysuper** [comment]
Refer to the following website。
https://www.baidu.com/link?url=MmuiFZtNBtE8Uzda4JlYwfTcugNyf4IveZe08N2pMcv3LYukvEzTlE9mJ-hUYT_cT6_JmeBDHoSdUGoXFAw0-q&wd=&eqid=aa2e0b6a00019370000000025edca36e

**Comment by yangyichao-mango** [comment]
> Refer to the following website。
> https://www.baidu.com/link?url=MmuiFZtNBtE8Uzda4JlYwfTcugNyf4IveZe08N2pMcv3LYukvEzTlE9mJ-hUYT_cT6_JmeBDHoSdUGoXFAw0-q&wd=&eqid=aa2e0b6a00019370000000025edca36e

Thx for you answer.

I've checked the xx.sh that do has the `-Dlogging.config=classpath:logback-worker.xml`.

We maybe need to supplement the documents for a starter like me, because there is no 1.3.0 released website doc and I follow the 1.2.0 version website doc to deploy the dev environment.

I will change this issue description to a doc issue.
