### ISSUE TITLE
[BUG] Jackson UDSerde error

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#2922]
**Describe the bug**

There is a Serde Exception in `TaskNode`, because we use Jackson UDSerde `JSONUtils.JsonDataSerializer` and `JSONUtils.JsonDataDeserializer` in `TaskNode` fields.

The UDSerde can convert "[]" to ""[]"" because the `JsonDataDeserializer` node.toString() implement.

**To Reproduce**
Steps to reproduce the behavior, for example:

`public static void main(String[] args) {
        String a = "{\"conditionResult\":\"{\\\"successNode\\\":[\\\"\\\"],\\\"failedNode\\\":[\\\"\\\"]}\","
                + "\"conditionsTask\":false,\"depList\":[],\"dependence\":\"{}\",\"forbidden\":false,"
                + "\"id\":\"tasks-86823\",\"maxRetryTimes\":1,\"name\":\"shell test\","
                + "\"params\":\"{\\\"resourceList\\\":[],\\\"localParams\\\":[],\\\"rawScript\\\":\\\"echo "
                + "'yyc'\\\"}\",\"preTasks\":\"[]\",\"retryInterval\":1,\"runFlag\":\"NORMAL\","
                + "\"taskInstancePriority\":\"HIGHEST\",\"taskTimeoutParameter\":{\"enable\":false,\"interval\":0},"
                + "\"timeout\":\"{}\",\"type\":\"SHELL\",\"workerGroup\":\"default\"}";
        TaskNode taskNode = JSONUtils.parseObject(a, TaskNode.class);
    }`

**Expected behavior**
`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_STRING token
 at [Source: (String)""[]""; line: 1, column: 1]`

**Screenshots**
![image](https://user-images.githubusercontent.com/29545877/83968921-f98abc80-a8fe-11ea-8765-94829ce5dedd.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement
- We can remove the UDSerde `JSONUtils.JsonDataSerializer` and `JSONUtils.JsonDataDeserializer` in JSONUtils.

**Comment by lgcareer** [comment]
Hi,I didn't fid the exception occurs,whether give a whole picture

**Comment by yangyichao-mango** [comment]
> Hi,I didn't find the exception occurs,whether give a whole picture

You can test this rest api below.
![image](https://user-images.githubusercontent.com/29545877/83991428-4ada9080-a97f-11ea-8c42-4ee82770bc7b.png)

**Comment by lgcareer** [comment]
Whether do gou give a whole step,such as how to create a process definition? and how to run? I visit the task instance list is normal.

**Comment by yangyichao-mango** [comment]
> Whether do gou give a whole step,such as how to create a process definition? and how to run? I visit the task instance list is normal.

1.Create a Shell task.
![image](https://user-images.githubusercontent.com/29545877/83999011-74ea7d80-a994-11ea-9fde-9ffffcaf8341.png)

2.Deploy the work flow and run it manually.
![image](https://user-images.githubusercontent.com/29545877/83999103-a2cfc200-a994-11ea-8570-9d124917bea8.png)

3.It will cause an exception when I visit this page.
![image](https://user-images.githubusercontent.com/29545877/83999174-ca268f00-a994-11ea-89f8-9a4e86deb1b7.png)

4.The exception is below.
![image](https://user-images.githubusercontent.com/29545877/83999238-eaeee480-a994-11ea-9366-9edc7c1431f7.png)

Thx for your answer.

**Comment by lgcareer** [comment]
Hi,I test it on dev-1.3.0 is ok,You can test it on dev-1.3.0 branch.

**Comment by yangyichao-mango** [comment]
> Hi,I test it on dev-1.3.0 is ok,You can test it on dev-1.3.0 branch.

I run it in dev branch.

**Comment by lgcareer** [comment]
Hi,Thanks.The branch is out develop branch,If you want tu use ds,don't suggest use dev branch.If you want to coutribute,you can test dev and commit pr.

**Comment by yangyichao-mango** [comment]
> Hi,Thanks.The branch is the develop branch,If you want tu use ds,don't suggest use dev branch.If you want to coutribute,you can test dev and commit pr.

Thx for your answer.
I'm a starter and use dev branch in my local env. I will fix it and commit a PR.
