### ISSUE TITLE
[BUG] Hive JDBC connection parameter ignored

### ISSUE THREAD

**Issue by KEN-LJQ** [apache/incubator-dolphinscheduler#2923]
**Describe the bug**
The jdbc connection parameter of Hive datasource, should append after the question mark when building jdbc url, like `jdbc:hive2://host:port/default?mapred.job.queue.name=root.users.a`. But actually, it append after the semicolon, so the result is `jdbc:hive2://host:port/default;mapred.job.queue.name=root.users.a`, which make the parameter being ignored

![image](https://user-images.githubusercontent.com/16650282/83969066-3efbb980-a900-11ea-8c83-ffa899d7a65b.png)

For testing, I set the parameter in this way `{"?mapred.job.queue.name":"root.user.a"}`, and now it can be set correctly

**Which version of Dolphin Scheduler:**
 - [1.2.1-release]

**Comment by dailidong** [comment]
I think it's easy to fix, if you are interesting in implementing it, please leave a message, then submit a PR.

please consider the principal is also optional, so Unit Test is also needed

**Comment by KEN-LJQ** [comment]
OK, I will fix it
