### ISSUE TITLE
[BUG] There is no exitVal judge in OSUtils.exeCmd function

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#2925]
**Describe the bug**
There is no exitVal judge in OSUtils.exeCmd function. So when I run cmd in this function in MacOS and this cmd fail, there is no log or exception thrown.

**To Reproduce**
1.Make sure `sudo sysadminctl -addUser 1 -password 1` will produce error when you execute in your shell.
2. Run OSUtils.exeCmd with `sudo sysadminctl -addUser 1 -password 1` params.
3. Judge the `p.waitFor()`'s result, it will be `1` that means failed.

**Expected behavior**
Judge the `p.waitFor()`'s result, it will be `1` that means failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/29545877/84001665-ad408a80-a999-11ea-9e1a-d9f57232e9fa.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement
- Judge the result of `Process.waitFor()` or record the creating working dir and user detail log by `TaskLogger`
- Remove the exeCmd from OSUtils, and use the `ShellExecutor.execCommand(command)` function.

**Comment by dailidong** [comment]
good job

could you submit a PR to solve this problem? I think it's not difficult, you can try.  if you meet problems, please leave message

**Comment by yangyichao-mango** [comment]
> good job
> 
> 
> 
> could you submit a PR to solve this problem? I think it's not difficult, you can try.  if you meet problems, please leave message

I will do it.

**Comment by yangyichao-mango** [comment]
> good job
> 
> could you submit a PR to solve this problem? I think it's not difficult, you can try. if you meet problems, please leave message

Hi @dailidong @gabrywu . I've commit the PR for this issue. Can you help to review this PR? Thx a lot.
