### ISSUE TITLE
Working instance log, can the name be named after the instance name?

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2930]
Working instance log, can the name be named after the instance name?, I can't fast query log in the background of time, sometimes the front-end logs: no, just want to go to the backend to check the log, but the logs directory are physical id folder, once more I don't know what's the name of, if not to open the page in the task instance, workflow definition, workflow instance page list page increase physical id show, so it is more convenient to check log directly, alone the mysql table path is not convenient, also have to query the mysql data fields, sometimes read log nor convenient page directly.I want to quickly retrieve the location problem.
![图片](https://user-images.githubusercontent.com/37201886/84102246-796d6f80-aa42-11ea-9a1a-ac26d3b6dfd9.png)

**Comment by feiyalun** [comment]
工作实例日志，命名能否以实例名称命名？，我在后台查询日志的时候没法快速查，有时候前端日志没有，就想去后端查日志，但是logs目录下都是物理id文件夹，一旦多了不知道叫什么名字，如果不给开通，那在任务实例页面、工作流实例页面、工作流定义列表页增加增加物理id展示，这样更方便去直接查日志，单独靠mysql表中路径查不方便，还得查询mysql数据中的字段，有时候页面直接看日志也不方便。我想快速的去检索定位问题。

**Comment by break60** [comment]
Did not understand you，“工作实例日志，命名能否以实例名称命名？”

**Comment by feiyalun** [comment]
> 
> 
> Did not understand you，“工作实例日志，命名能否以实例名称命名？”

![图片](https://user-images.githubusercontent.com/37201886/84112591-9e221100-aa5b-11ea-9ab4-008de03090db.png)
就是这个这个意思，这些都是id命名的日志，我不知道是我自己哪个task产生的日志。如果是认为实力名称我就知道了，比如我的叫test-python。 进入这个日志目录下我就很快能找到对应的日志文件。

**Comment by feiyalun** [comment]
![图片](https://user-images.githubusercontent.com/37201886/84112817-0c66d380-aa5c-11ea-9164-1be752aa1bb0.png)

**Comment by break60** [comment]
@lgcareer  Have time to read this issue

**Comment by feiyalun** [comment]
我认为最好的任务目录应该是这样的：/logs/工作流名称/工作流实例名称/任务实例名称.log
例子：/logs/验证stg整体工作/验证stg整体工作流-0-1591671112509/stg-demo.log，就是全取name进行记录。

**Comment by feiyalun** [comment]
> 
> 
> @lgcareer Have time to read this issue

我认为最好的任务目录应该是这样的：/logs/工作流名称/工作流实例名称/任务实例名称.log
例子：/logs/验证stg整体工作/验证stg整体工作流-0-1591671112509/stg-demo.log，就是全取name进行记录。

**Comment by dailidong** [comment]
there is a field `log_path` in the t_ds_task_instance table, you can show it in the UI, but I want to know whether this is needed by the most people?  anybody who need this feature, please leave a message.

by the way, English is needed

**Comment by feiyalun** [comment]
> 
> 
> there is a field `log_path` in the t_ds_task_instance table, you can show it in the UI, but I want to know whether this is needed by the most people? anybody who need this feature, please leave a message.
> 
> by the way, English is needed

i think most people need this function

**Comment by yh2388** [comment]
+1 
And I will implement it.

**Comment by gabrywu** [comment]
@feiyalun I will close this issue , @yh2388 will implement it .We will look forward to good news from @feiyalun

**Comment by yh2388** [comment]
> +1
> I will implement it.
> And I think the log path should be placed on the first line of the log on UI, still keep id log path.

this is the new effect @yangyichao-mango 
UI:
![image](https://user-images.githubusercontent.com/20351485/87272531-18393000-c509-11ea-8289-b2871ca38c51.png)
Download log:
![image](https://user-images.githubusercontent.com/20351485/87272833-f8eed280-c509-11ea-9fa3-049e9ef70b19.png)

**Comment by yangyichao-mango** [comment]
Hi,


Please add this screenshot in github comment.
Thx a lot for your contribution.


Best,
Yichao Yang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 中午1:11
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"Yichao Yang"<1048262223@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] Working instance log, can the name be named after the instance name? (#2930)





  
+1
 I will implement it.
 And I think the log path should be placed on the first line of the log on UI, still keep id log path.
  
this is the new effect @yangyichao-mango
 UI:
 
 Download log:

**Comment by yh2388** [comment]
> Hi, Please add this screenshot in github comment. Thx a lot for your contribution. Best, Yichao Yang
> […](#)

It already exists in the github comment. #2930

**Comment by yangyichao-mango** [comment]
> > Hi, Please add this screenshot in github comment. Thx a lot for your contribution. Best, Yichao Yang
> > […](#)
> 
> It already exists in the github comment. #2930

Sorry, I didn't read the issue. I thought you sent a picture in PR.

**Comment by yh2388** [comment]
> > > Hi, Please add this screenshot in github comment. Thx a lot for your contribution. Best, Yichao Yang
> > > […](#)
> > 
> > 
> > It already exists in the github comment. #2930
> 
> Sorry, I didn't read the issue. I thought you sent a picture in PR.

Haha, that's ok, thank you for review
