### ISSUE TITLE
[QUESTION] some question when I use the ds

### ISSUE THREAD

**Issue by hanfengcan** [apache/incubator-dolphinscheduler#2946]
Q1：[1.3-dev] Why I create a tenant, such as test, the group of test is root ?
为什么我创建的租户test，为什么这个租户所属的组是root呢？不是 ds所属的组.

Q2：[1.3-dev] I create a new tenant, such as wechat, I can found the user of Linux. 
我创建一个新的租户, 发现新建的租户不像其他租户一样有一个Linux的用户.

Q3: [1.3-dev] the user of resources dir is root group?
为什么租户的资源文件夹是root组
![image](https://user-images.githubusercontent.com/4559753/84222336-ee57ac80-ab09-11ea-9039-39329999942f.png)

Q4: [1.3-dev] when I stop the shell task. the task is running.
我把shell任务停止了, 但是, 页面显示任务还在运行
![image](https://user-images.githubusercontent.com/4559753/84223648-0846be80-ab0d-11ea-80e7-7ac40c6d03cc.png)
![image](https://user-images.githubusercontent.com/4559753/84223686-23193300-ab0d-11ea-8d75-db7f9d65331c.png)

**Comment by dailidong** [comment]
> Q1：[1.3-dev] Why I create a tenant, such as test, the group of test is root ?
I think you deployed DS use root ?

**Comment by dailidong** [comment]
> Q2：[1.3-dev] I create a new tenant, such as wechat, I can found the user of Linux.
我创建一个新的租户, 发现新建的租户不像其他租户一样有一个Linux的用户.

I don't know what do you want to say.  your English description is different with Chinese description

**Comment by dailidong** [comment]
>  Q4: [1.3-dev] when I stop the shell task. the task is running.

the final task state is ? usually it may task some time to stop the running task

**Comment by dailidong** [comment]
By the way , one issue describe one topic will be better for discussing
