### ISSUE TITLE
[QUESTION] Workflow template DAG, workflow instance, work task and what is the relationship between them

### ISSUE THREAD

**Issue by soulzhouxu** [apache/incubator-dolphinscheduler#2947]
各位好，请教一下：
1，一个dag支持最大并发100？是指产生100个工作流实例并发运行吗？
2，一个dag中的任务节点，也有并发数的配置，是指任务也可以并发多个线程运行吗？最大数100吗？
English:
1,A DAG supports a maximum concurrency of 100? Does it mean that 100 workflow instances are generated and run concurrently?
2,A task node in a DAG also has a concurrent number configuration. Does it mean that tasks can run concurrently with multiple threads? Is the maximum number 100?

**Comment by Rubik-W** [comment]
1.2.1 version

master.properties
Control the parallel number of master node workflows
master.exec.threads=100

Control the number of parallel tasks in each workflow
master.exec.task.number=20

Control the parallel number of worker node tasks
worker.exec.threads=100

**Comment by alex-wcf** [comment]
我使用docker运行的master和worker，发现如何修改都达不到效果，我创建了10工作流来测试，同时提交运行就马上被执行了，这几个配置再容器中应该如何有效修改并应用
