### ISSUE TITLE
[QUESTION] HDFS operation error using docker version 

### ISSUE THREAD

**Issue by BKHC** [apache/incubator-dolphinscheduler#2957]
I have installed and ran the docker version of the scheduler (https://hub.docker.com/r/ww1516123/incubator-dolphinscheduler) and hive docker (https://github.com/big-data-europe/docker-hive). I have connected the dockers networks, and then I connected the hive server as a datasource for the scheduler. 

However, I have not been able to upload or create file on File manage. 
![image](https://user-images.githubusercontent.com/16622469/84488064-3d503e00-acd2-11ea-89b2-3921d7f3bdbf.png)
![image](https://user-images.githubusercontent.com/16622469/84488093-46d9a600-acd2-11ea-928d-62d065f84ba6.png)

How can i solve this issue? Many thanks!

**Comment by dailidong** [comment]
please show the exception info on the api server runtime log

By the way, this docker image is not official docker image. for now we only provide docker file

**Comment by BKHC** [comment]
> please show the exception info on the api server runtime log
> 
> By the way, this docker image is not official docker image. for now we only provide docker file

Thank you for the reply. The error logs are as follows. 
![image](https://user-images.githubusercontent.com/16622469/84614574-217ab100-aef9-11ea-8ab4-6ac93678e825.png)
![image](https://user-images.githubusercontent.com/16622469/84614635-4cfd9b80-aef9-11ea-93d2-b0f819b36437.png)
![image](https://user-images.githubusercontent.com/16622469/84614695-7a4a4980-aef9-11ea-8dbf-0f45e69469a0.png)
Thanks!

**Comment by xingchun-chen** [comment]
version 1.3.3 will solve the problem,it is the same as #3238
