### ISSUE TITLE
[QUESTION] How to install DS in windows10

### ISSUE THREAD

**Issue by Galaxy-Hitchhiker** [apache/incubator-dolphinscheduler#2958]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
The environment is installed, but I won't build the front and back end.

**Comment by yangyichao-mango** [comment]
You can check this doc.

https://www.baidu.com/link?url=MmuiFZtNBtE8Uzda4JlYwfTcugNyf4IveZe08N2pMcv3LYukvEzTlE9mJ-hUYT_cT6_JmeBDHoSdUGoXFAw0-q&wd=&eqid=aa2e0b6a00019370000000025edca36e
