### ISSUE TITLE
[BUG] 1.3.0版本没有创建工作组按钮

### ISSUE THREAD

**Issue by QQhuxuhui** [apache/incubator-dolphinscheduler#2959]

**Comment by QQhuxuhui** [comment]
从1.2.0升级到1.3.0后，使用admin用户登录系统，在worker管理界面没有创建woker工作组的按钮

**Comment by BoYiZhang** [comment]
1.3.0 not support one worker configure multiple workgroups.
Considering that IP is not fixed to run on k8s, it was removed in version 1.3.0

**Comment by QQhuxuhui** [comment]
I haven't used k8s. I have two worker nodes in total. After upgrading, these two workers are added to the default group by default, and I can't edit the default group, so I can't add any more customized groups? thank you

**Comment by BoYiZhang** [comment]
You can edit[ worker.properties ].
[ worker.group=default ]Configure workgroup,
But a worker server can only belong to one work group

I have the same needs as you
It's just that I have implemented the work group function

**Comment by yangyichao-mango** [comment]
> You can edit[ worker.properties ].
> [ worker.group=default ]Configure workgroup,
> But a worker server can only belong to one work group
> 
> I have the same needs as you
> It's just that I have implemented the work group function

I've implement this issue in newest dev branch, I think you can help to review. Thx a lot.
[#2934 ]

**Comment by QQhuxuhui** [comment]
OK, I will, thank you
