### ISSUE TITLE
任务提交方式 cluster模式报错

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#2966]
![图片](https://user-images.githubusercontent.com/44901627/84568663-92b04c00-adb3-11ea-984a-ceb28ea0fe7a.png)

```

[INFO] 2020-06-13 19:39:27.493  - [taskAppId=TASK-13-394-516]:[106] -  -> /tmp/dolphinscheduler/exec/process/1/13/394/516/13_394_516.command: 4: /tmp/dolphinscheduler/exec/process/1/13/394/516/13_394_516.command: source: not found
	20/06/13 19:39:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[INFO] 2020-06-13 19:42:27.165  - [taskAppId=TASK-13-394-516]:[106] -  -> 20/06/13 19:39:28 WARN DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be `loaded.`
```

不用ds调度系统，在本地是可以执行的，
不知道为啥一直报这个错误

**Comment by gabrywu** [comment]
Can you execute the 'source' command successfully ?

**Comment by zengqinchris** [comment]
> Can you execute the 'source' command successfully ?
我在本地服务器执行source就可以的，在ds上执行是有问题的
![image](https://user-images.githubusercontent.com/44901627/84591546-d6698b00-ae71-11ea-832b-e754443e486c.png)
这是是什么问题？

**Comment by zengqinchris** [comment]
> Can you execute the 'source' command successfully ?

任务运行cluster模式和client模式，跟source命令执行不成功有关系吗？
我如果是单独执行 client模式是可以执行成功的，那就奇怪了，

**Comment by dailidong** [comment]
you can 

> > Can you execute the 'source' command successfully ?
> 
> 任务运行cluster模式和client模式，跟source命令执行不成功有关系吗？
> 我如果是单独执行 client模式是可以执行成功的，那就奇怪了，

of course， it's the root cause, 
you can switch to the tenant under your local shell , and then try this `souce ` command to see it exists or not?

**Comment by dailidong** [comment]
English is needed
