### ISSUE TITLE
在DS上如何查看任务提交方式 cluster的日志

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#2971]
在DS上如何查看任务提交方式 cluster的日志？
以cluster模式提交任务报错，但是不知道在 ds里能不能查看日志
![image](https://user-images.githubusercontent.com/44901627/84592352-ae7d2600-ae77-11ea-9364-a42aec1c9849.png)
cluster模式提交后，一直报错，不知道在哪里查看日志

**Comment by zengqinchris** [comment]
是不是只能从yarn上看日志

**Comment by dailidong** [comment]
you can see the runtime log of worker server, and the task execution log is seperate under logs directory

**Comment by dailidong** [comment]
I see your problem is `source: not found` , 
By the way, English is needed
