### ISSUE TITLE
无人为操作，调度任务进程被kill

### ISSUE THREAD

**Issue by Wf675721680** [apache/incubator-dolphinscheduler#2973]
连续两天离线调度任务莫名被kill，导致后续任务阻塞。
若是内存或者cpu不足，任务应该处于等待状态，而不应该被kill
![image](https://user-images.githubusercontent.com/57088544/84611496-a2817a80-aef0-11ea-840f-76f5412a543a.png)

**Comment by dailidong** [comment]
Please use English

**Comment by gabrywu** [comment]
@Wf675721680 You'd better create issues using English , DolphinScheduler is an Apache Project ,so we are asked to talk in English. If not in English , the issue might be closed.

**Comment by Wf675721680** [comment]
The task is killed in the middle of running.
For two consecutive days, the offline scheduling task was inexplicably killed, resulting in subsequent tasks blocking.
If there is not enough memory or CPU, the task should be in a waiting state and should not be kill.
![image](https://user-images.githubusercontent.com/57088544/84738347-57449600-afdc-11ea-9f5d-da1dded651a6.png)

**Comment by dailidong** [comment]
Are all worker servers working normally？is there any worker server shutdown or not work? 

usually,  if the worker server works fine, the task can't be killed,  the running task will be killed and then recover if worker server shutdown

**Comment by dailidong** [comment]
please update/add title in English, thx

**Comment by Wf675721680** [comment]
All servers are working

There are many tasks running at the same time, but only one task is killed

You can't find the reason of being killed by checking the log

**Comment by gabrywu** [comment]
@Wf675721680 another same issue created ,I will close this one.
