### ISSUE TITLE
1.3.0-release UI Can the running time be changed?

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#2977]
![图片](https://user-images.githubusercontent.com/37201886/84632595-b5f90980-af21-11ea-8f14-fcb72bd0a7c0.png)
Can the running time be changed? Since most tasks take minutes, the minutes display is better.So you don't have to convert

**Comment by feiyalun** [comment]
运行时长可否改成分，因为大部分的任务耗时都是分钟级别，分钟显示更好一下。免得自己再换算

**Comment by gabrywu** [comment]
@feiyalun Could create a PR to do this ? We don't know how long will the task run actually, so second is the default unit.

**Comment by chengshiwen** [comment]
Close by #5025 #5027
