### ISSUE TITLE
init ds database error in IDE,run main class org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler

### ISSUE THREAD

**Issue by lijufeng2016** [apache/incubator-dolphinscheduler#2978]
**Describe the bug**
I download release-1.3.0 source code,i want init db in IDE,then i config `pom.xml`  and `datasource.properties` as official website 
https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/development-environment-setup.html  ,and i run main class `org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler`,the exception follows:
![image](https://user-images.githubusercontent.com/17442507/84631744-7a117480-af20-11ea-87d0-d3cd6a7a7928.png)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. config `pom.xml` make mysql-connector-java scope as compile
2.config datasource.properties make datasource as mysql,config follows
![image](https://user-images.githubusercontent.com/17442507/84632714-e345b780-af21-11ea-80b6-1156489402f5.png)
3.run main class `org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler`

**Requirement or improvement**
please give me a sollution or handle this iisue

**Comment by Eights-Li** [comment]
it is not a bug, because of the license of mysql, ds use pg as defult metadata db. 
if you want use mysql, you can put the mysql-connect jar in ds /lib dir.
if just for develop ds, please remove the scope of mysql

**Comment by lijufeng2016** [comment]
> it is not a bug, because of the license of mysql, ds use pg as defult metadata db.
> if you want use mysql, you can put the mysql-connect jar in ds /lib dir.
> if just for develop ds, please remove the scope of mysql

I tryed put the mysql-connect jar in ds /lib dir,it not works,event i tryed put it in jdk /lib,still not work

**Comment by lijufeng2016** [comment]
this is not a problem,i config the wrong driver name
