### ISSUE TITLE
[Feature] Request to add field mapping on datax

### ISSUE THREAD

**Issue by arvin0810** [apache/incubator-dolphinscheduler#2979]
**description**
First of all, I donot know how DS extract the schema of a given sql statement, so consider this, there is a field whose data type is number/decimal/float/double, user want to map it to decimal(m,n) in target database, for example hive, is it doable in release 1.3.0???

**描述**
希望增加字段映射，针对用户期望修改目标字段的数据类型的情况。不知1.3.0是否支持。

**Comment by Rubik-W** [comment]
You can use custom json config, don't know if it meets you needs.

**Comment by arvin0810** [comment]
> You can use custom json config, don't know if it meets you needs.

you got me. close this issue.
