### ISSUE TITLE
[QUESTION] One click deploy error 

### ISSUE THREAD

**Issue by BKHC** [apache/incubator-dolphinscheduler#2982]
I am trying to deploy version 1.3.0-release on my vm. 

When I use the command "./mvnw clean install -Prelease" or "sh docker/build/hooks/build", I encounter the same error below. 
![image](https://user-images.githubusercontent.com/16622469/84648435-a2f13400-af37-11ea-9ad4-b3d442768be2.png)
![image](https://user-images.githubusercontent.com/16622469/84648566-c9af6a80-af37-11ea-81eb-e57139e265d1.png)

The command "sudo npm install node-sass --unsafe-perm" works, but it do not work if I dont use sudo. Hence, I have tried to use "sudo ./mvnw clean install -Prelease" instead of "./mvnw clean install -Prelease" but then another error came up "mvn: command not found", which it is not "not found" when I am not using sudo with the command "./mvnw clean install -Prelease". 

How should I solve this issue? Thanks

**Comment by xingchun-chen** [comment]
You need to install  node-sass first：sudo npm install --unsafe-perm -g node-sass
