### ISSUE TITLE
[QUESTION] question title

### ISSUE THREAD

**Issue by dairui2** [apache/incubator-dolphinscheduler#2984]
./conf/env/dolphinscheduler_env.sh
Environment variables "DATAX_HOME = / opt/soft/datax/bin/datax. Py", does not exist in fact installation package datax, and datax. Py

-[1.3.0-dev]

Plz put the Datax-related package in the DolphinScheduler installation package.

**Comment by BoYiZhang** [comment]
dolphinscheduler just executes the start command,
Services like datax need to be deployed by themselves.

**Comment by dairui2** [comment]
> dolphinscheduler just executes the start command,
> Services like datax need to be deployed by themselves.

not happy, 囧.

**Comment by dailidong** [comment]
> > dolphinscheduler just executes the start command,
> > Services like datax need to be deployed by themselves.
> 
> not happy, 囧.

datax has so many dependencies  which may not compitable with apache v2 license , so we can' t put datax installation package into DolphinScheduler
