### ISSUE TITLE
ds的API调用

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#2985]
有没有人使用过ds的API，在自己的大数据平台里调用dsAPI查看任务状态和控制任务执行的需求，分享一下整合的过程流程，感谢

**Comment by 743294668** [comment]
> 有没有人使用过ds的API，在自己的大数据平台里调用dsAPI查看任务状态和控制任务执行的需求，分享一下整合的过程流程，感谢

have never done it. 
But I think it should not be difficult, because DS has a log service on each worker, and most of the task status of DS will be stored in the database, which can be obtained from the database.

**Comment by yangyichao-mango** [comment]
> 有没有人使用过ds的API，在自己的大数据平台里调用dsAPI查看任务状态和控制任务执行的需求，分享一下整合的过程流程，感谢

I did not do this before, but there is the api doc I think that can help you.
[Api doc](http://106.75.43.194:8888/dolphinscheduler/doc.html?language=zh_CN&lang=zh)

**Comment by gabrywu** [comment]
@zengqinchris Yes , @yangyichao-mango has gave you a link about the api doc. I will close PR, feel free to reopen it if necessary

**Comment by zengqinchris** [comment]
![image](https://user-images.githubusercontent.com/44901627/84908617-45034e80-b0e7-11ea-9cb7-a161deee023c.png)
/dolphinscheduler/access-token/list-paging
有没有人知道前面是怎么拼接，加上ip地址好像不行

**Comment by yangyichao-mango** [comment]
Hi


You can try to combine the ip and port.


Best,
Yichao Yang



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chriszeng <notifications@github.com&gt;
发送时间: 2020年6月17日 22:10
收件人: apache/incubator-dolphinscheduler <incubator-dolphinscheduler@noreply.github.com&gt;
抄送: Yichao Yang <1048262223@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[apache/incubator-dolphinscheduler] ds的API调用 (#2985)

**Comment by zengqinchris** [comment]
![image](https://user-images.githubusercontent.com/44901627/84909460-4c772780-b0e8-11ea-8758-1a891b62fe88.png)
不行呀
![image](https://user-images.githubusercontent.com/44901627/84909507-5c8f0700-b0e8-11ea-9e55-d3ca671e8efa.png)
我就是调用的

**Comment by yangyichao-mango** [comment]
You can check this list:
1.ping ip to make sure you can access the ip
2.telnet ip port to make sure this port is providing service after you make sure the port is your apiserver port
3.check the ds api doc to make sure you give the right headers, params, get/post/put param

**Comment by dairui2** [comment]
> ![image](https://user-images.githubusercontent.com/44901627/84909460-4c772780-b0e8-11ea-8758-1a891b62fe88.png)
> 不行呀
> ![image](https://user-images.githubusercontent.com/44901627/84909507-5c8f0700-b0e8-11ea-9e55-d3ca671e8efa.png)
> 我就是调用的

Maybe you didn't log in.
![截屏2020-06-17 22 49 50](https://user-images.githubusercontent.com/31460898/84913580-48013d80-b0ed-11ea-980c-36d4963abfec.png)

**Comment by dairui2** [comment]
> ![image](https://user-images.githubusercontent.com/44901627/84909460-4c772780-b0e8-11ea-8758-1a891b62fe88.png)
> 不行呀
> ![image](https://user-images.githubusercontent.com/44901627/84909507-5c8f0700-b0e8-11ea-9e55-d3ca671e8efa.png)
> 我就是调用的

Maybe you didn't log in.
![1592405857251](https://user-images.githubusercontent.com/31460898/84914096-ceb61a80-b0ed-11ea-93af-e6779668e455.jpg)

**Comment by zengqinchris** [comment]
> > ![image](https://user-images.githubusercontent.com/44901627/84909460-4c772780-b0e8-11ea-8758-1a891b62fe88.png)
> > 不行呀
> > ![image](https://user-images.githubusercontent.com/44901627/84909507-5c8f0700-b0e8-11ea-9e55-d3ca671e8efa.png)
> > 我就是调用的
> 
> Maybe you didn't log in.
> ![1592405857251](https://user-images.githubusercontent.com/31460898/84914096-ceb61a80-b0ed-11ea-93af-e6779668e455.jpg)

老铁，你是怎么请求调用的，文档里也没有说要传入参数，能不能给一个样例全一点的

**Comment by zengqinchris** [comment]
https://blog.csdn.net/samz5906/article/details/106825655
感谢大佬的文档参考
