### ISSUE TITLE
[BUG] Can't see logs when performing tasks

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2988]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Can't see logs when performing tasks.
Then found that the server's logs are not synchronized, resulting in no logs.
I think the log is not synchronized.

# ui error info
![image](https://user-images.githubusercontent.com/10054719/84726339-3c175d80-afbf-11ea-9b74-f8b162e086d6.png)
# dc-ds-02 error info
![image](https://user-images.githubusercontent.com/10054719/84726349-43d70200-afbf-11ea-9f43-4c97368bf1bf.png)

# dc-ds-01， logs, 
![image](https://user-images.githubusercontent.com/10054719/84726237-05d9de00-afbf-11ea-81a8-940e904a87c4.png)

# dc-ds-02, logs:
![image](https://user-images.githubusercontent.com/10054719/84726302-273aca00-afbf-11ea-937a-44424a824e95.png)

**Which version of Dolphin Scheduler:**
 -1.3.0
- Use distributed deployment
- nodeis : dc-ds-01,  dc-ds-02
- dc-ds-01 process
16449 LoggerServer
16403 WorkerServer
16836 Jps
16357 MasterServer
16501 AlertServer
24344 SecondaryNameNode
22970 QuorumPeerMain
23805 NameNode
23934 DataNode

- dc-ds-02 process
13120 Jps
12851 ApiApplicationServer
12804 LoggerServer
12759 WorkerServer
493 QuorumPeerMain

**Comment by samz406** [comment]
hi ,You first open the table t_ds_task_instance, find the task you just checked the log, see if there is a log file in the log_path under host。

![image](https://user-images.githubusercontent.com/3055810/84727224-2efb6e00-afc1-11ea-94b6-ae900acd1d8e.png)

**Comment by arlanhon** [comment]
> 嗨，您首先打开表t_ds_task_instance，找到您刚刚检查日志的任务，查看host下log_path中是否有日志文件。
> 
> ![图片](https://user-images.githubusercontent.com/3055810/84727224-2efb6e00-afc1-11ea-94b6-ae900acd1d8e.png)

Why is my ip like this, different from yours, I commented 127.0.0.1 according to the requirements during deployment

![image](https://user-images.githubusercontent.com/10054719/84727893-a5e53680-afc2-11ea-9dc6-608037e457f4.png)

**Comment by samz406** [comment]
My version is 1.2, yours is version 1.3, the format is correct
You can find out which server this path is on.
I think the possible situation is:
The worker of the task you are performing should not be on the same server as the api server. It is executed on another worker server, and the ip obtained is the local 127.0.0.1, not the actual ip, you can see the hosts configuration mapping

At the same time, you can look at the IP of the monitoring center -> worker page


我的版本是1.2，你的是1.3版本，格式正确
你可以找下这个路径是在哪个服务器上。
我觉得有可能情况是：
你执行的任务的worker应该不是和api server在同一个服务器上。是在另一台worker服务器上执行，然后获取的ip是本地127.0.0.1，不是实际ip,你可以看下hosts配置映射

同时你可以看下监控中心->worker  页面的ip ，截图如下

![image](https://user-images.githubusercontent.com/3055810/84739029-7859b680-afdd-11ea-9775-18c4fb74b656.png)

**Comment by arlanhon** [comment]
Thanks for the reply, I checked my hosts configuration and there is no problem, then the monitoring page is as follows
![image](https://user-images.githubusercontent.com/10054719/84739850-f23e6f80-afde-11ea-8cc8-8534ef889fec.png)
![image](https://user-images.githubusercontent.com/10054719/84739881-fa96aa80-afde-11ea-9057-d40b00e21cc4.png)

hosts config is as follows:
![image](https://user-images.githubusercontent.com/10054719/84739764-d63ace00-afde-11ea-9ac2-03538c1d05b4.png)

**Comment by samz406** [comment]
you can see this issue ,#2409
 If there are changes, restart the service to see if the worker ip changes
如果有修改，需要重启下服务看worker ip 是否改变

**Comment by arlanhon** [comment]
感谢,问题解决了，分别在两台机器执行`sudo hostnamectl set-hostname dc-ds-01`，`sudo hostnamectl set-hostname dc-ds-02`，重启服务就ok了。
![image](https://user-images.githubusercontent.com/10054719/84744009-464c5280-afe5-11ea-8aab-5be7ac52777f.png)

**Comment by WaterAndBread** [comment]
赞，确实通过数据查询后得知 数据存的hostname 非IP ，在容器里面因为无法解析，在/etc/hosts 里面加入解析就可以了
