### ISSUE TITLE
The task is killed in the middle of running.

### ISSUE THREAD

**Issue by Wf675721680** [apache/incubator-dolphinscheduler#2989]
For two consecutive days, the offline scheduling task was inexplicably killed, resulting in subsequent tasks blocking.
If there is not enough memory or CPU, the task should be in a waiting state and should not be kill.
![image](https://user-images.githubusercontent.com/57088544/84738528-a4286c80-afdc-11ea-9590-8a6b9ad5b225.png)

**Comment by gabrywu** [comment]
@Wf675721680  I think DolphinScheduler will not kill the executing task, you'd better check your environment

**Comment by Wf675721680** [comment]
All servers are working

There are many tasks running at the same time, but only one task is killed

You can't find the reason of being killed by checking the log

**Comment by xingchun-chen** [comment]
which version? Can you provide more information

**Comment by chengshiwen** [comment]
Close the issue since no updates for long time
