### ISSUE TITLE
[QUESTION] [1.3.0] Select the file in the folder directory of the resource center, it will prompt that it does not exist, causing the process to fail

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2994]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Select the file in the folder directory of the resource center, it will prompt that it does not exist, causing the process to fail.

**To Reproduce**
![image](https://user-images.githubusercontent.com/10054719/84746220-3d10b500-afe8-11ea-81bc-9a2aaffdc266.png)
the error info
![image](https://user-images.githubusercontent.com/10054719/84746297-56196600-afe8-11ea-8d75-885cf90be2b5.png)

resources:
![image](https://user-images.githubusercontent.com/10054719/84746370-6fbaad80-afe8-11ea-8fa1-86bc2c656ac2.png)

**Which version of Dolphin Scheduler:**
 -1.3.0
- Distributed deployment
- hadoop is Stand-alone

**Other performance**
No problem with files in folders.

**Comment by Eights-Li** [comment]
this is not a bug, in ds-1.3.0, when exec task with resource file, the resoruce dir will be create in ds-worker exec path, so you should add the dir for the resoruce file. like : sh tcms/xxxxx.sh
