### ISSUE TITLE
contribution for adding e2e testcase

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#2995]
follow the root issue: #1460

e2e is an end-to-end test, that is  UI automated testing ,  an important means of black box testing, in order to avoid incorporating some defective code

e2e use framework: java+selenium+testng+maven
In order to reduce the maintenance cost in the later period, e2e adopts the design mode of POM, as shown below：
![image](https://user-images.githubusercontent.com/55787491/84748362-1e5fed80-afeb-11ea-8a42-f9ed2d02674c.png)
1. Add test data under the data module
2. Add element positioning under the locator module
3. Add page operation method under the page module
4. Add test cases under testcase module, testcase must start with test
5. New test cases need to be added to testng.xml
6. The common method of element operation in common/BrowserCommon

note:
1. Local run needs to modify LOGIN_URL, driver.chromeDriver (local browser drive address) in config.properties
2. Start the local browser to run the testcase, you can comment out chromeOptions.addArguments("--headless") in base/BaseDriver

**Comment by xingchun-chen** [comment]
Completed testcase:

-  Security Center:
1. create , delete tenants
2. create, delete users
3. create, edit, delete alarm groups
4. create ,edit queues
5. create, edit, delete token

- Project Management：
1. create , delete project
2. create, run, online/offline, delete workflow definition

**Comment by dailidong** [comment]
If anybody who would like to do some contributions,  you can add the module you want to write under the issue comment, looking forward to your participation

**Comment by chengshiwen** [comment]
Close by #3201 #3220 #3524
