### ISSUE TITLE
support datax hive to mysql

### ISSUE THREAD

**Issue by ttting** [apache/incubator-dolphinscheduler#2996]
Did support use datax to synchronize hive to mysql? I can find it in release-1.3.0

**Comment by jcfhj** [comment]
use python mode

**Comment by lijufeng2016** [comment]
yes of course you can, if only datax support the reader source or write r source, you can use it to synchronize data

**Comment by Rubik-W** [comment]
The Datax node is support custom json config (datax json), don't know if it meets you needs.

**Comment by BoYiZhang** [comment]
Use native dataX to customize the configuration.  hive(hdfs)->mysql

![image](https://user-images.githubusercontent.com/39816903/84850242-d17f2400-b089-11ea-820f-8094ca9df27b.png)
