### ISSUE TITLE
[QUESTION] flink task instance has been set as failed while task is still running

### ISSUE THREAD

**Issue by amy108** [apache/incubator-dolphinscheduler#2997]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
flink task instance has been set as failed in ds while task in yarn cluster is still running

**Which version of DolphinScheduler:**
1.3.0

**Additional context**
![image](https://user-images.githubusercontent.com/48902828/84770432-20857480-b00a-11ea-8396-d4938c94af2f.png)
![image](https://user-images.githubusercontent.com/48902828/84770450-267b5580-b00a-11ea-9362-bfe9e805c306.png)

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by amy108** [comment]
![image](https://user-images.githubusercontent.com/48902828/84775316-a658ee00-b011-11ea-86a4-f4e64e8745dd.png)

**error log**

**Comment by dailidong** [comment]
please show your yarn config in common.properties, may be your config is not right

`# if not use hadoop resourcemanager, please keep default value; if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=192.168.xx.xx,192.168.xx.xx

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s`

**Comment by amy108** [comment]
@dailidong here is my yarn config, resourcemanager is single
![image](https://user-images.githubusercontent.com/48902828/84984612-cb627380-b16d-11ea-918d-6ec69a46e8fa.png)
![image](https://user-images.githubusercontent.com/48902828/84984666-e46b2480-b16d-11ea-8bf2-7994d772c328.png)

**Comment by dailidong** [comment]
it's a bug, the PR https://github.com/apache/incubator-dolphinscheduler/pull/3013 solve this problem

**Comment by amy108** [comment]
@dailidong got it, thanks.
