### ISSUE TITLE
BUG:workServer-FetchTaskThread[261]:task instance is null. task id : ***

### ISSUE THREAD

**Issue by jcfhj** [apache/incubator-dolphinscheduler#2998]
The error log information is as follows：
[ERROR] 2020-06-15 14:34:26.623 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 112745 
[WARN] 2020-06-15 14:34:26.623 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[188] - remove task queue : 2_77350_2_112745_-1 due to taskInstance is null

The reasons are as follows：
When the task is executed, the master server will first report to the table t_ Ds_ task_ When an instance inserts a piece of data and the workserver consumes it from the task queue, it will judge "if (verify task instance is null (task instance)) {". In special scenarios, it will fail. I hope someone can solve this problem

**Comment by jcfhj** [comment]
任务执行时，masterServer会先向表t_ds_task_instance插入一条数据，workServer再从任务队列中消费，会进行“if (verifyTaskInstanceIsNull(taskInstance)) {”的判断，特殊场景下，这里会判断失败。大概原因就是t_ds_task_instance表的数据还未插入成功，但workserver已经启动了。希望有人能解决这个问题

**Comment by haotengteng** [comment]
I also encountered various problems. I hope to repair them as soon as possible

**Comment by yangyichao-mango** [comment]
Hi~,
Please describe what the `special scene` as you say here means?
What is the version?
Thx a lot.

**Comment by dailidong** [comment]
version >=1.2.1 solved this issue, detail info please refer : #1477
