### ISSUE TITLE
[BUG] After configuring a task, the subtasks of the task are all submitted at once to be executed in parallel

### ISSUE THREAD

**Issue by arlanhon** [apache/incubator-dolphinscheduler#2999]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
After configuring a task, the subtasks of the task are all submitted at once to be executed in parallel.

This question is very strange, but not every task will be like this, some tasks are normal, some tasks are abnormal

![image](https://user-images.githubusercontent.com/10054719/84797778-c6e27180-b02c-11ea-945a-75ab18f7c8b6.png)

![image](https://user-images.githubusercontent.com/10054719/84797624-9e5a7780-b02c-11ea-8bb9-32b65d2573c5.png)

![image](https://user-images.githubusercontent.com/10054719/84797576-90a4f200-b02c-11ea-9d9c-f1c0ad8c6c27.png)

![image](https://user-images.githubusercontent.com/10054719/84797855-de215f00-b02c-11ea-857a-49adf72dd19f.png)

**Which version of Dolphin Scheduler:**
 -1.3.0
- Distributed deployment

**Comment by xingchun-chen** [comment]
I did not reproduce your problem, can you take a screenshot of the running parameters of your workflow instance
![image](https://user-images.githubusercontent.com/55787491/84849055-0fc71400-b087-11ea-9f82-4b74bb5d67ca.png)
![image](https://user-images.githubusercontent.com/55787491/84849099-2bcab580-b087-11ea-995b-a6743648eb72.png)

**Comment by arlanhon** [comment]
![image](https://user-images.githubusercontent.com/10054719/85088063-bd662e80-b211-11ea-9822-1b5029d2c261.png)

This problem is not common, and by deleting all connections to reconnect the task and then save, there is a 90% probability that it will be executed in the normal way.
Seeing your example, I think it may be possible to build all tasks first, disconnect first, and then start at a certain point, such as: connect from [1]->[9] in turn without conventional thinking, It is [4->5], [6->7], [5->6]... do this, and save.

Chinese translation: 
这个问题并不常见，并且通过删除所有的连接重新连接task，然后保存，有90%的概率会按正常的方式执行。
看到你的例子，我想或许可以这样做，把所有的task先建好，先不连接，然后随便从某个点开始，如：不用常规思维从[1]->[9]依次连接，而是[4->5],[6->7],[5->6]......这样做，最后保存。

**Comment by xingchun-chen** [comment]
1.According to the above steps, there is still no reproduction
2. Can you send out the value of the database table t_ds_process_definition.process_definition_json

**Comment by arlanhon** [comment]
> 1.According to the above steps, there is still no reproduction
> 2. Please check the preTasks field value of the database table t_ds_process_definition.process_definition_json，If the preTasks are empty, it should be caused by not clearing the cache when creating the workflow definition. You can clear the browser cache and re-edit the workflow definition

well, Because the problem was fixed by me, when the problem reappears, I will verify the solution you provided, and I temporarily closed the problem.
