### ISSUE TITLE
[BUG] This may cause inconsistent behavior

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3000]
version 1.3.0
delpoy two master log:

'''
[WARN] 2020-06-17 01:30:48.985 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:30:53.988 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:30:58.991 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:03.992 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:08.996 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:13.998 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:19.000 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:24.004 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:29.006 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:34.009 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.
[WARN] 2020-06-17 01:31:39.012 org.quartz.impl.jdbcjobstore.JobStoreTX:[3350] - This scheduler instance (dataMiddle-801592328643959) is still active but was recovered by another instance in the cluster.  This may cause inconsistent behavior.

''''

**Comment by gabrywu** [comment]
@BoYiZhang  deploy two masters on the same machine ? could you give more infos about environment ?

**Comment by BoYiZhang** [comment]
Two physical machines

And the physical machine time is the same

**Comment by gabrywu** [comment]
@BoYiZhang  Do you set the org.quartz.jobStore.acquireTriggersWithinLock config?
