### ISSUE TITLE
[BUG] API interface return time exception ???

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3001]
API interface return time will be 8 hours later than normal time

However, the web page displays normally

Where do I need to set????

![image](https://user-images.githubusercontent.com/39816903/84846417-587bce80-b081-11ea-9e72-6b64b1b6ab23.png)

**Comment by xingchun-chen** [comment]
This problem is caused by  time zone,You can refer to this issue#2485

**Comment by BoYiZhang** [comment]
Solution:

update config file :   application-api.properties

add config:

spring.jackson.time-zone=GMT+8
