### ISSUE TITLE
Send the hive query result as an attachment or table, and report an error

### ISSUE THREAD

**Issue by Jops-data** [apache/incubator-dolphinscheduler#3004]
Configure the SQL node to use hive as the data source, and send the query results as attachments to report errors as follows.
![image](https://user-images.githubusercontent.com/63348491/84850553-9c270600-b08a-11ea-9400-ee2a3ee912f4.png)
Worker node log
![image](https://user-images.githubusercontent.com/63348491/84850644-d1cbef00-b08a-11ea-9fb2-4cdfeb1ff64e.png)
My dolphin scheduler version is 1.2.1.
I hope someone can help me solve this problem.

**Comment by xingchun-chen** [comment]
Maybe the mail configuration is wrong, can you take a screenshot of your mail configuration information?

**Comment by Jops-data** [comment]
Yes, here is my mailbox configuration information. I have no problem with my mailbox configuration, because he can send some warning emails.
![image](https://user-images.githubusercontent.com/63348491/84966378-fafc8600-b143-11ea-9908-9d8cd110263c.png)

**Comment by gabrywu** [comment]
@Jops-data I think you should check your email config again carefully, if no others report this issue, it's just because of your mailbox configuration
