### ISSUE TITLE
[Feature] DataX configures multiple readers and writers through web pages

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3005]
DataX configures multiple readers and writers through web pages

DataX can be configured with multiple readers and writers

**Comment by BoYiZhang** [comment]
I implemented a front-end dynamic generation of dataX configuration file to the background

In this way, the front end will be very complex. Is there a better way???

**Comment by nickbaba2012** [comment]
I want it, which branch has the feature?
