### ISSUE TITLE
 task instance not found

### ISSUE THREAD

**Issue by glz-java** [apache/incubator-dolphinscheduler#3011]
系统：
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

日志内容：出错节点位置已经加粗高亮

[INFO] 2020-06-17 21:39:05.329 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[211] - consume tasks: [2_229_2_496_-1],there still have 0 tasks need to be executed
[INFO] 2020-06-17 21:39:05.335 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[208] - worker fetch taskId : 496 from queue 
[INFO] 2020-06-17 21:39:05.336 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[218] - task instance  local execute path : /tmp/dolphinscheduler/exec/process/2/10/229/496 
[INFO] 2020-06-17 21:39:05.336 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[229] - task : 496 ready to submit to task scheduler thread
[INFO] 2020-06-17 21:39:05.336 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[278] - consume task /dolphinscheduler/tasks_queue/2_229_2_496_-1
[INFO] 2020-06-17 21:39:05.345 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[93] - script path : /tmp/dolphinscheduler/exec/process/2/10/229/496
[INFO] 2020-06-17 21:39:05.345  - [taskAppId=TASK-10-229-496]:[92] - shell task params {"rawScript":"/home/fuming/software/logstash-7.1.1/bin/logstash -f /home/fuming/software/logstash-7.1.1/config_db_indexer/sql.indexer_es.conf\n","localParams":[],"resourceList":[]}
[INFO] 2020-06-17 21:39:05.346  - [taskAppId=TASK-10-229-496]:[150] - raw script : /home/fuming/software/logstash-7.1.1/bin/logstash -f /home/fuming/software/logstash-7.1.1/config_db_indexer/sql.indexer_es.conf

[INFO] 2020-06-17 21:39:05.346  - [taskAppId=TASK-10-229-496]:[151] - task dir : /tmp/dolphinscheduler/exec/process/2/10/229/496
[INFO] 2020-06-17 21:39:05.347  - [taskAppId=TASK-10-229-496]:[99] - tenantCode user:jiawei, task dir:10_229_496
[INFO] 2020-06-17 21:39:05.347  - [taskAppId=TASK-10-229-496]:[103] - create command file:/tmp/dolphinscheduler/exec/process/2/10/229/496/10_229_496.command
[INFO] 2020-06-17 21:39:05.347  - [taskAppId=TASK-10-229-496]:[116] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/soft/dolphinscheduler/conf/env/.dolphinscheduler_env.sh

/tmp/dolphinscheduler/exec/process/2/10/229/496/10_229_496_node.sh
[INFO] 2020-06-17 21:39:05.349  - [taskAppId=TASK-10-229-496]:[329] - task run command:
sudo -u jiawei sh /tmp/dolphinscheduler/exec/process/2/10/229/496/10_229_496.command
[INFO] 2020-06-17 21:39:05.352  - [taskAppId=TASK-10-229-496]:[158] - process start, process id is: 40707
[INFO] 2020-06-17 22:47:25.934  - [taskAppId=TASK-10-229-496]:[168] - process has exited, work dir:/tmp/dolphinscheduler/exec/process/2/10/229/496, pid:40707 ,exitStatusCode:0
[INFO] 2020-06-17 22:47:25.937  - [taskAppId=TASK-10-229-496]:[231] - process id is 40707
[INFO] 2020-06-17 22:47:25.953 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[156] - task instance id : 496,task final status : SUCCESS

**#出错节点日志**
**[INFO] 2020-06-17 22:47:28.692 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[211] - consume tasks: [2_229_2_497_-1],there still have 0 tasks need to be executed
[ERROR] 2020-06-17 22:47:28.694 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 497 
[WARN] 2020-06-17 22:47:28.695 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[188] - remove task queue : 2_229_2_497_-1 due to taskInstance is null
[INFO] 2020-06-17 22:47:28.695 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[278] - consume task /dolphinscheduler/tasks_queue/2_229_2_497_-1**

**#进行手动停止日志**
**[INFO] 2020-06-18 09:15:38.201 org.apache.dolphinscheduler.server.worker.WorkerServer:[338] - get one kill command from tasks kill queue: NULL-497
[INFO] 2020-06-18 09:15:38.211 org.apache.dolphinscheduler.server.worker.WorkerServer:[378] - delete task from tasks queue: 497
[INFO] 2020-06-18 09:15:38.221 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[99] - check task:2_229_2_497_-1 not exist in task queue
[INFO] 2020-06-18 09:15:38.267 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[339] - delete task:NULL-497 from tasks set**

**Comment by samz406** [comment]
For the same issue, please refer to issue #2529

**Comment by samz406** [comment]
1.2.1 solved this problem，you can upgrade to latest,
