### ISSUE TITLE
Task Online  The master node log appears:  BeanCreationException

### ISSUE THREAD

**Issue by shitoubiao** [apache/incubator-dolphinscheduler#3016]
[INFO] 2036-06-19 09:45:04.886 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 1, type: START_PROCESS
[ERROR] 2036-06-19 09:45:04.918 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[144] - scan command error
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [org/apache/dolphinscheduler/dao/datasource/SpringConnectio
nFactory.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframewor
k.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named '
org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available

**Comment by xingchun-chen** [comment]
@lenboo Please look at this problem

**Comment by shitoubiao** [comment]
caused by my mistake,  I'm sorry!

**Comment by zxbing** [comment]
The bug solved ?

**Comment by dick318** [comment]
@shitoubiao How to solve this problem？

**Comment by imyoubo** [comment]
> caused by my mistake, I'm sorry!

How did you solve the problem?

**Comment by 1015zhc** [comment]
hello，how did you slove the problem？ I have the same error;

**Comment by imyoubo** [comment]
> hello，how did you slove the problem？ I have the same error;

Please check if your @Value("${xxxx.xxx:defaultValue}") has set the default Value
I had the same problem, but set the default and the problem was solved.
But I don't know why the problem was solved by setting the default

**Comment by Hxssssss** [comment]
> > hello，how did you slove the problem？ I have the same error;
> 
> Please check if your @value("${xxxx.xxx:defaultValue}") has set the default Value
> I had the same problem, but set the default and the problem was solved.
> But I don't know why the problem was solved by setting the default

Is there will be default configuration properties, configuration all let go? Please reply, thank you very much!!!

**Comment by 1015zhc** [comment]
> > > hello，how did you slove the problem？ I have the same error;
> > 
> > 
> > Please check if your @value("${xxxx.xxx:defaultValue}") has set the default Value
> > I had the same problem, but set the default and the problem was solved.
> > But I don't know why the problem was solved by setting the default
> 
> Is there will be default configuration properties, configuration all let go? Please reply, thank you very much!!!

I have slove my error. It's because of my database table. So I drop all tables,then excute the command of creating tables. It's ok!

**Comment by Hxssssss** [comment]
> > > > hello，how did you slove the problem？ I have the same error;
> > > 
> > > 
> > > Please check if your @value("${xxxx.xxx:defaultValue}") has set the default Value
> > > I had the same problem, but set the default and the problem was solved.
> > > But I don't know why the problem was solved by setting the default
> > 
> > 
> > Is there will be default configuration properties, configuration all let go? Please reply, thank you very much!!!
> 
> I have slove my error. It's because of my database table. So I drop all tables,then excute the command of creating tables. It's ok!

Me too. I commented out the alarm service configuration. I found that there was no default value in the source code
