### ISSUE TITLE
[BUG] Comment ERROR

### ISSUE THREAD

**Issue by xsbai** [apache/incubator-dolphinscheduler#3017]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The comment error in source code

**To Reproduce**
Steps to reproduce the behavior, for example:
1. In 'dolphinscheduler-api\src\main\java\org\apache\dolphinscheduler\api\controller\ResourcesController.java'
2. lines 66
3. the comment title ‘create resource’ should be 'create directory'

**Expected behavior**
pls correct this error

**Screenshots**
![image](https://user-images.githubusercontent.com/9511636/85093441-e0e3a600-b21e-11ea-8044-1265ae138a88.png)

**Which version of Dolphin Scheduler:**
 -[1.3.0]

**Additional context**
None

**Requirement or improvement
None

**Comment by dailidong** [comment]
@xsbai , please submit a PR to solve this problem, it's easy to fix
