### ISSUE TITLE
[BUG] i18n incomplete

### ISSUE THREAD

**Issue by xsbai** [apache/incubator-dolphinscheduler#3018]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
In User page, the user type is not in i18n;

**To Reproduce**
Steps to reproduce the behavior, for example:
1. In file '\dolphinscheduler-ui\src\js\conf\home\pages\security\pages\users\_source\list.vue'
2. In line 29 
3. the '用户类型' should be '{{$t('User Type')}}'
4. and the i18n file should be update

**Expected behavior**
modify the page without i18n

**Screenshots**
None

**Which version of Dolphin Scheduler:**
 -[1.3.0]

**Additional context**
None

**Requirement or improvement
None

**Comment by break60** [comment]
Welcome to mention a pr to repair
