### ISSUE TITLE
[Feature] need to collect FAQ issues to official website faq.md docs

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#3020]
there are some FAQ question on the issue list, and need to be collected to official website

the steps:
1、get the faq list:  https://github.com/apache/incubator-dolphinscheduler/issues?q=is%3Aissue+label%3AFAQ+

2、then tidying up the doc to faq.md on the website: https://github.com/apache/incubator-dolphinscheduler-website , last , submit a PR 

![image](https://user-images.githubusercontent.com/15833811/85113580-16ea4f80-b24a-11ea-9741-09c190983131.png)

**Comment by AhahaGe** [comment]
I will finish this.
