### ISSUE TITLE
[BUG] DS1.3 in docker, ApiApplicationServer can't listen to 12345 , but 9090

### ISSUE THREAD

**Issue by boomer001** [apache/incubator-dolphinscheduler#3023]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
 
I run  dolphinscheduler1.3  in docker, 
ApiApplicationServer can't listen to 12345 , but 9090
In application-api.properties, 
server.port=12345

I can 
 curl http://127.0.0.1:9090/dolphinscheduler/login -d 'userName=admin&userPassword=dolphinscheduler123'
success.
response is:
{"code":0,"msg":"login success","data":{"sessionId":"bff7e8dc-3266-45a2-801b-38b36f694342"}}

**Comment by boomer001** [comment]
my dockerfile is  docker/build/Dockerfile
I open  
RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories

**Comment by jilieryuyi** [comment]
got  the same problem

**Comment by dailidong** [comment]
we published the first official docker image,  please referer the doc: https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html
