### ISSUE TITLE
[BUG] 1.3.0 Document exception

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3026]
In version 1.3.0

The function of workgroup has changed. The current code does not support adding and modifying functions

So in 1.3.0, it also supports the new editing function of workgroup ??

![image](https://user-images.githubusercontent.com/39816903/85206551-90bb2f80-b355-11ea-81b8-0aca1ab4cce2.png)

**Comment by break60** [comment]
The current 1.3.0 document has not been updated yet, it is still the template of the previous 1.2.0

**Comment by BoYiZhang** [comment]
come on.
