### ISSUE TITLE
[BUG] Front-end post wrong `strategy` value in timeout params

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3028]
**Describe the bug**
Front-end post empty string `strategy` value in timeout params, and the master and worker will produce the `com.fasterxml.jackson.databind.exc.InvalidFormatException` because of the enum type of `strategy`.

**To Reproduce**
1. Create a new simple shell process definition in front-end.
2. I just fill the name and code of shell node, do not fill or select the other options.
3. Save the process definition and your will find out the front-end post the wrong empty string `strategy` in `timeout` of `processDefinitionJson`.
4.When you run the process definition, then master and worker will serde the processDefinitionJson to object, it will produce `com.fasterxml.jackson.databind.exc.InvalidFormatException` because of the enum type of `strategy`.

**Expected behavior**
Front-end post empty string `strategy` value in timeout params.

**Screenshots**
![image](https://user-images.githubusercontent.com/29545877/85226686-72177000-b40b-11ea-98df-d8c7ef23940d.png)
![image](https://user-images.githubusercontent.com/29545877/85226754-c3276400-b40b-11ea-882e-3b1b420c739f.png)
![image](https://user-images.githubusercontent.com/29545877/85226933-a17aac80-b40c-11ea-9665-bb18bac8b14c.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement
- Fix the timeout strategy value when front-end post to the back-end or change enum serde of `strategy`.

**Comment by break60** [comment]
Dev-1.3.0 pass-through can be run normally. When the dev-1.3.0 code is merged into dev, I will test your problem
