### ISSUE TITLE
[QUESTION] how to add a worker server

### ISSUE THREAD

**Issue by zhengnanzn** [apache/incubator-dolphinscheduler#3033]
I want to add a server as worker server
how many step I need to follow ?
thank you.
**Which version of DolphinScheduler:**
 -[1.2.0]

**Comment by dailidong** [comment]
1、Create deployment user and hosts mapping, please refer 1.3 part of [cluster deployment](https://dolphinscheduler.apache.org/en-us/docs/1.2.0/user_doc/cluster-deployment.html)

2、Configure hosts mapping and ssh access and modify directory permissions. please refer 1.4 part of  [cluster deployment](https://dolphinscheduler.apache.org/en-us/docs/1.2.0/user_doc/cluster-deployment.html)

3、copy the deployment directory from worker server that has already deployed

4、go to bin dir, then start worker server and logger server
./dolphinscheduler-daemon.sh start worker-server
./dolphinscheduler-daemon.sh start logger-server

---

1、参考官网[部署文档](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/cluster-deployment.html) 1.3 小节，创建部署用户和hosts映射

2、参考官网[部署文档](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.0/user_doc/cluster-deployment.html) 1.4 小节

3、复制正在运行的服务器上的部署目录到新机器的同样的部署目录下

4、到bin下，启动worker server 和 logger server
./dolphinscheduler-daemon.sh start worker-server
./dolphinscheduler-daemon.sh start logger-server

**Comment by dailidong** [comment]
to 1.3, please referer doc: https://github.com/apache/incubator-dolphinscheduler-website/blob/master/docs/zh-cn/1.3.3/user_doc/expansion-reduction.md
