### ISSUE TITLE
[QUESTION] how to acquire documents about import workflow to ds and export workflow from ds

### ISSUE THREAD

**Issue by yesiyuan007** [apache/incubator-dolphinscheduler#3034]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.
Workflow definition says we can export workflow from ds.I export much workflow that they run successfully.The JSON text like this
{"code":10000,
"msg":"Internal Server Error: Required Integer parameter 'processDefinitionId' is not present",
"data":null}
I import workflow to ds that I export workflow,ds shows like this.
"data processDefinitionName is null"

**Which version of DolphinScheduler:**
 -[1.2.0]

**Additional context**

**Requirement or improvement
- I want to receive document about import workflow and how to write json file about import workflow.

**Comment by yesiyuan007** [comment]
![image](https://user-images.githubusercontent.com/66993606/85261363-a0925b00-b49e-11ea-8ba4-cc3485fa81b9.png)

**Comment by dailidong** [comment]
> Internal Server Error: Required Integer parameter 'processDefinitionId' is not present"
please see api server runtime log to find the detail exception info, it's abnormal

**Comment by dailidong** [comment]
please add title

**Comment by yesiyuan007** [comment]
> > Internal Server Error: Required Integer parameter 'processDefinitionId' is not present"
> 
> please see api server runtime log to find the detail exception info, it's abnormal

I have seen the api server runtime log today morning.There is nothing about export workflow.No matter what the pattern of workflow(such as SHELL,DATAX,SPARK,SQL and so on) is,the json file of the workflow exported shows the same,like this:
 {"code":10000,
"msg":"Internal Server Error: Required Integer parameter 'processDefinitionId' is not present",
"data":null}
I want to know more about export workflow.Thank's very much.

**Comment by samz406** [comment]
Can you provide your json file? If convenient, you can add my WeChat samz406, private chat

**Comment by samz406** [comment]
`Internal Server Error: Required Integer parameter 'processDefinitionId' is not present"`

Reporting this error is the inconsistent data type of the previous value，Check if the previous request parameters are correct
