### ISSUE TITLE
ds在运行过程中，经常出现某个节点长时间呈现灰色状态，无法启动的问题

### ISSUE THREAD

**Issue by lemonche** [apache/incubator-dolphinscheduler#3039]
ds在运行过程中，经常出现某个工作节点无法启动，一直呈灰色圆圈状态。
![微信图片_20200622204951](https://user-images.githubusercontent.com/32675415/85289463-12cc6500-b4ca-11ea-84e3-ce4d1c8118ee.png)
![微信图片_20200622205323](https://user-images.githubusercontent.com/32675415/85289704-7060b180-b4ca-11ea-9172-be1e3a9a9293.png)
最后只能kill掉，并重新启动。

**Comment by xingchun-chen** [comment]
1. Which version
2. The gray circle of the task node refers to the "successful submission" status, check whether the worker group specified by the task is correct
3. Check the master log
1.哪个版本
2.任务节点灰色圆圈指的是“提交成功”状态，检查该任务指定的worker分组是否正确
3.检查master日志

please upstate the title in english

**Comment by xingchun-chen** [comment]
Do not reply for a long time, temporarily close the issue
