### ISSUE TITLE
[Bug][ui] Define the port or pid of webUI monitor

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3045]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29545877/85410356-91440800-b599-11ea-8836-407af5e0a47e.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by break60** [comment]
The name returned by the current backend is called port

**Comment by break60** [comment]
@qiaozhanwei Why is this pid named port

**Comment by tlhhup** [comment]
Please update code.
