### ISSUE TITLE
Spark任务提交的时候，后台日志显示节点参数无效

### ISSUE THREAD

**Issue by which520** [apache/incubator-dolphinscheduler#3048]
![{EA8F4B73-46E0-4E09-A00B-160019215474}_20200624093634](https://user-images.githubusercontent.com/44831650/85486953-3bee1200-b5fe-11ea-8dd3-4bce93e406d5.jpg)

**Comment by which520** [comment]
[INFO] 2020-06-23 12:18:28.859 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[159] - login user which, update process define, project name: test2, process define name: which_test, process_definition_json: {"globalParams":[],"tasks":[{"type":"SHELL","id":"tasks-56548","name":"wewe","params":{"resourceList":[],"localParams":[],"rawScript":"czczxcx"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"PYTHON","id":"tasks-65022","name":"test","params":{"resourceList":[{"res":"python_test122.py"}],"localParams":[],"rawScript":"dsds"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"FLINK","id":"tasks-31676","name":"dsds","params":{"mainClass":"","mainJar":{"res":"python_test122.py"},"deployMode":"cluster","resourceList":[],"localParams":[],"slot":1,"taskManager":"2","jobManagerMemory":"1G","taskManagerMemory":"2G","executorCores":2,"mainArgs":"","others":"","programType":"PYTHON"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"SPARK","id":"tasks-74978","name":"dcsc","params":{"mainClass":"","mainJar":{"res":"python_test122.py"},"deployMode":"cluster","resourceList":[],"localParams":[],"driverCores":1,"driverMemory":"512M","numExecutors":2,"executorMemory":"2G","executorCores":2,"mainArgs":"","others":"","programType":"PYTHON"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]}],"tenantId":-1,"timeout":"30"}, desc: dsfsdf, locations:{"tasks-56548":{"name":"wewe","targetarr":"","x":238,"y":104},"tasks-65022":{"name":"test","targetarr":"","x":457,"y":324},"tasks-31676":{"name":"dsds","targetarr":"","x":626,"y":219},"tasks-74978":{"name":"dcsc","targetarr":"","x":460,"y":161}}, connects:[]
[ERROR] 2020-06-23 12:18:28.864 org.apache.dolphinscheduler.api.service.ProcessDefinitionService:[799] - task node dcsc parameter invalid

**Comment by yangyichao-mango** [comment]
> [INFO] 2020-06-23 12:18:28.859 org.apache.dolphinscheduler.api.controller.ProcessDefinitionController:[159] - login user which, update process define, project name: test2, process define name: which_test, process_definition_json: {"globalParams":[],"tasks":[{"type":"SHELL","id":"tasks-56548","name":"wewe","params":{"resourceList":[],"localParams":[],"rawScript":"czczxcx"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"PYTHON","id":"tasks-65022","name":"test","params":{"resourceList":[{"res":"python_test122.py"}],"localParams":[],"rawScript":"dsds"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"FLINK","id":"tasks-31676","name":"dsds","params":{"mainClass":"","mainJar":{"res":"python_test122.py"},"deployMode":"cluster","resourceList":[],"localParams":[],"slot":1,"taskManager":"2","jobManagerMemory":"1G","taskManagerMemory":"2G","executorCores":2,"mainArgs":"","others":"","programType":"PYTHON"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]},{"type":"SPARK","id":"tasks-74978","name":"dcsc","params":{"mainClass":"","mainJar":{"res":"python_test122.py"},"deployMode":"cluster","resourceList":[],"localParams":[],"driverCores":1,"driverMemory":"512M","numExecutors":2,"executorMemory":"2G","executorCores":2,"mainArgs":"","others":"","programType":"PYTHON"},"description":"","runFlag":"NORMAL","dependence":{},"maxRetryTimes":"0","retryInterval":"1","timeout":{"strategy":"","interval":null,"enable":false},"taskInstancePriority":"MEDIUM","workerGroupId":-1,"preTasks":[]}],"tenantId":-1,"timeout":"30"}, desc: dsfsdf, locations:{"tasks-56548":{"name":"wewe","targetarr":"","x":238,"y":104},"tasks-65022":{"name":"test","targetarr":"","x":457,"y":324},"tasks-31676":{"name":"dsds","targetarr":"","x":626,"y":219},"tasks-74978":{"name":"dcsc","targetarr":"","x":460,"y":161}}, connects:[]
> [ERROR] 2020-06-23 12:18:28.864 org.apache.dolphinscheduler.api.service.ProcessDefinitionService:[799] - task node dcsc parameter invalid

Which version?

**Comment by which520** [comment]
1.2.1

**Comment by which520** [comment]
public boolean checkParameters() {
    return mainJar != null && programType != null && sparkVersion != null;
  }

我怀疑是我的sparkVersion没有获取到，但是我不知道这个sparkVersion是怎么获取的

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/85490526-7e1a5200-b604-11ea-8469-44451971ab3b.png)
Your spark node does not fill in the mainClass and mainArgs parameters, and there is no "sparkVersion" parameter

**Comment by xingchun-chen** [comment]
please update the title in english

**Comment by which520** [comment]
I lost an option for the Spark version of my UI,After the UI is reinstalled, it returns to normal
