### ISSUE TITLE
[QUESTION] question title 监控中心那边worker和marter那边的心跳时间比北京时间快5小时，检查了服务器时间，时区，数据库时间都是正确的，请问这个问题要怎么处理？

### ISSUE THREAD

**Issue by xiaoning123456** [apache/incubator-dolphinscheduler#3050]
[QUESTION] question title 监控中心那边worker和marter那边的心跳时间比北京时间快5小时，检查了服务器时间，时区，数据库时间都是正确的，请问这个问题要怎么处理？

**Comment by yangyichao-mango** [comment]
Hi~
Please change the title to English and describe your question follow the question line: 
1.which version of DS
2.screenshot of your worker, master, database time.

**Comment by xingchun-chen** [comment]
You can refer to this issue #2485

**Comment by samz406** [comment]
same issue #3060,i will close
