### ISSUE TITLE
[BUG] 1.20 branch docker build solution is not working. tar.gz file version is 1.21-SNAPSHOT.

### ISSUE THREAD

**Issue by caoyj1991** [apache/incubator-dolphinscheduler#3055]
as title.
need update the readme guide.

**Comment by lgcareer** [comment]
@caoyj1991 Suggest you use the 1.3.3 version,thx.

**Comment by lgcareer** [comment]
The 1.2 version will not be maintained,It's better to upgrade the latest version.
