### ISSUE TITLE
[BUG] 1.3.0 branch The task running order in the process instance does not follow the topological order in the process definition

### ISSUE THREAD

**Issue by hlzhu1983** [apache/incubator-dolphinscheduler#3058]
1. process definition
![1593309494(1)](https://user-images.githubusercontent.com/9334358/85935770-d9ab4f00-b926-11ea-9f69-52a9e11ad699.jpg)
2. task instance order in database
![72423ea1aafbee8b832e4798046dff7](https://user-images.githubusercontent.com/9334358/85935784-fa73a480-b926-11ea-93a2-aa89f2718f29.png)
3. task instance order in web ui
![image](https://user-images.githubusercontent.com/9334358/85935791-0b241a80-b927-11ea-9288-a61e66d0486b.png)
4.task instance order in process instance
![image](https://user-images.githubusercontent.com/9334358/85935795-1aa36380-b927-11ea-9532-99462048e24c.png)

The task running order in the process instance does not follow the topological order in the process definition, Why?

**Comment by xingchun-chen** [comment]
Please check the preTasks field value of the database table t_ds_process_definition.process_definition_json，If the preTasks are empty, it should be caused by not clearing the cache when creating the workflow definition. You can clear the browser cache and re-edit the workflow definition

**Comment by hlzhu1983** [comment]
that's right!
thanks!

**Comment by break60** [comment]
Regarding the front-end cache, the front-end currently adds a version number when compiling, and it is still being tested. This problem will not occur in versions after 1.3.0.

**Comment by break60** [comment]
#3030

**Comment by xingchun-chen** [comment]
1. Enter the dag of the workflow instance, double-click the node to open the node settings, and directly click the workflow instance to exit
1.进入工作流实例的dag页面，双击节点打开节点设置，直接点击工作流实例退出
![image](https://user-images.githubusercontent.com/55787491/89995049-90874280-dcbb-11ea-9831-37bec47b3815.png)
![image](https://user-images.githubusercontent.com/55787491/89994642-fd4e0d00-dcba-11ea-8eee-7101785c0832.png)
2. Enter the workflow definition page, create a workflow or edit the previously connected workflow, there is a problem with the connection
2.进入工作流定义页面，创建工作流或者编辑之前连线有问题的工作流,连线有问题
![image](https://user-images.githubusercontent.com/55787491/89995191-c5939500-dcbb-11ea-8c89-c7742cd47010.png)
