### ISSUE TITLE
[BUG] Workflow definition display exception

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3059]
![image](https://user-images.githubusercontent.com/39816903/85936097-cc439400-b929-11ea-86d8-5645cca34bcf.png)

**Comment by xingchun-chen** [comment]
This is because the arrow icon is clicked and the Bezier line is selected, which is caused by the component

**Comment by BoYiZhang** [comment]
What should I do to avoid it

**Comment by xingchun-chen** [comment]
Don't click the arrow icon if you don't need to delete the connection and node.
 If you have clicked the arrow icon, you can click the arrow icon again to deselect it
