### ISSUE TITLE
Abnormal situation of cluster time display

### ISSUE THREAD

**Issue by xiaoning123456** [apache/incubator-dolphinscheduler#3060]
dolphinscheduler版本：1.2.0版本
工作人员：技术人员；
问题：集群监控中心那边master服务那边显示的心跳时间比北京时间快了5个小时，集群是3节点的，其中一个节点的心跳时间显示的是正常，另外两个的心跳时间比北京时间快了5个小时
![微信图片_20200628102553](https://user-images.githubusercontent.com/67363330/85936116-ec735300-b929-11ea-94d5-36ab5ff35b13.png)
![微信图片_20200628102853](https://user-images.githubusercontent.com/67363330/85936145-407e3780-b92a-11ea-83c4-875c8b9e20d7.png)

，检查集群服务器时间及时区，数据库时间都是正常的，请问这是为什么

**Comment by samz406** [comment]
The worker master reports the heartbeat to obtain the current server time, so you need to check the time of the two servers 49,41
worker master上报心跳是取得当前服务器时间，所以需要你检查下49,41两台服务器时间

**Comment by samz406** [comment]
Please change the title to English and describe your question follow the question line

**Comment by dailidong** [comment]
use `timedatectl` command will show the following message:
![image](https://user-images.githubusercontent.com/15833811/85989869-bb774900-ba23-11ea-945c-2fa7f5b54fd9.png)

you will find that timezone is not right.
then, 
![image](https://user-images.githubusercontent.com/15833811/85990028-fb3e3080-ba23-11ea-8416-b7fc162f010b.png)
