### ISSUE TITLE
[QUESTION] task submit succuess but can't continue

### ISSUE THREAD

**Issue by hlzhu1983** [apache/incubator-dolphinscheduler#3061]
master log as follow
![image](https://user-images.githubusercontent.com/9334358/85936369-905dfe00-b92c-11ea-9774-d0aef3439b74.png)

**Comment by hlzhu1983** [comment]
[INFO] 2020-06-28 10:17:43.736 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 167, type: START_PROCESS
[INFO] 2020-06-28 10:17:43.748 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[140] - start master exec thread , split DAG ...
[INFO] 2020-06-28 10:17:43.757 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[331] - prepare process :166 end
[INFO] 2020-06-28 10:17:43.762 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[930] - add task to stand by list: pre
[INFO] 2020-06-28 10:17:43.763 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[939] - remove task from stand by list: pre
[INFO] 2020-06-28 10:17:43.770 org.apache.dolphinscheduler.service.process.ProcessService:[833] - start submit task : pre, instance id:166, state: RUNNING_EXEUTION
[INFO] 2020-06-28 10:17:43.772 org.apache.dolphinscheduler.service.process.ProcessService:[846] - end submit task to db successfully:pre state:SUBMITTED_SUCCESS complete, instance id:166 state: RUNNING_EXEUTION  
[INFO] 2020-06-28 10:17:43.775 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[179] - task ready to submit: TaskInstance{id=222, name='pre', taskType='SHELL', processDefinitionId=5, processInstanceId=166, processInstanceName='null', taskJson='{"conditionResult":"{\"successNode\":[\"\"],\"failedNode\":[\"\"]}","conditionsTask":false,"depList":[],"dependence":"{}","forbidden":false,"id":"tasks-43366","maxRetryTimes":0,"name":"pre","params":"{\"rawScript\":\"hive -f jkm/pre.hql\",\"localParams\":[],\"resourceList\":[{\"res\":\"jkm/pre.hql\",\"name\":\"pre.hql\",\"id\":35}]}","preTasks":"[]","retryInterval":1,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":false,"interval":0},"timeout":"{\"enable\":false,\"strategy\":\"\"}","type":"SHELL","workerGroup":"default"}', state=SUBMITTED_SUCCESS, submitTime=Sun Jun 28 10:17:43 CST 2020, startTime=Sun Jun 28 10:17:43 CST 2020, endTime=null, host='null', executePath='null', logPath='null', retryTimes=0, alertFlag=NO, processInstance=null, processDefine=null, pid=0, appLink='null', flag=YES, dependency='null', duration=null, maxRetryTimes=0, retryInterval=1, taskInstancePriority=MEDIUM, processInstancePriority=MEDIUM, dependentResult='null', workerGroup='default', executorId=2, executorName='null'}
[INFO] 2020-06-28 10:17:43.776 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[190] - master submit success, task : pre
[INFO] 2020-06-28 10:17:43.779 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[123] - wait task: process id: 166, task id:222, task name:pre complete
[ERROR] 2020-06-28 10:33:16.456 org.apache.dolphinscheduler.remote.handler.NettyClientHandler:[173] - exceptionCaught : {}
java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yangyichao-mango** [comment]
Hi,
Can you describe which version and how to reproduce this.

**Comment by yangyichao-mango** [comment]
Hi,

Has this problem been solved?

Tag: could be closed. @yangyichao-mango

**Comment by Slowfever-star** [comment]
Hi , any ideas on how to solve this problem? I have the same problem

**Comment by xingchun-chen** [comment]
the problem had been resolved in version 1.3.3 ,  you can refer to #3789
