### ISSUE TITLE
It is recommended to modify some of the 1.3.0 table field types

### ISSUE THREAD

**Issue by feiyalun** [apache/incubator-dolphinscheduler#3062]
Some of the field length types are not sufficient, and I recommend that they be modified, because once there are 500+ tasks in the workflow, the maintenance of table relationships will report an error

ALTER TABLE t_ds_task_instance CHANGE app_link app_link text COMMENT 'yarn app id';
ALTER TABLE t_ds_process_definition CHANGE connects connects  longtext COMMENT 'Node connection information';
ALTER TABLE t_ds_process_definition CHANGE locations locations  longtext COMMENT 'Node location information';

ALTER TABLE t_ds_process_instance CHANGE connects connects  longtext COMMENT 'Node connection information';
ALTER TABLE t_ds_process_instance CHANGE locations locations  longtext COMMENT 'Node location information';

**Comment by feiyalun** [comment]
部分字段长度类型不够，我建议修改一下，因为工作流中一旦有500+task，维护表关系就会报错

**Comment by yangyichao-mango** [comment]
> 部分字段长度类型不够，我建议修改一下，因为工作流中一旦有500+task，维护表关系就会报错

Hi~
Will 500+ task appear in a workflow in your current scenario?
In my opinion, if one workflow has 500+ task, it should be split to small task first, because it will be clearer and easier to manage.

**Comment by feiyalun** [comment]
It will definitely be dismantled in the future. At present, I want to use it for overall testing. If it can run, subtraction will be done in the future.I'd love to, but I can't make it


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yichao Yang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上8:36
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"飞亚伦"<874320724@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] It is recommended to modify some of the 1.3.0 table field types (#3062)





  
部分字段长度类型不够，我建议修改一下，因为工作流中一旦有500+task，维护表关系就会报错
  
Hi~
 Will 500+ task appear in a workflow in your current scenario?
 In my opinion, if one workflow has 500+ task, it should be split to small task first, because it will be clearer and easier to manage.

**Comment by yangyichao-mango** [comment]
Tag:could be closed.
@yangyichao-mango
