### ISSUE TITLE
[QUESTION] worker get yarn application status failed

### ISSUE THREAD

**Issue by hlzhu1983** [apache/incubator-dolphinscheduler#3063]
1.worker log
![image](https://user-images.githubusercontent.com/9334358/85938206-ad4efd00-b93d-11ea-9454-7384ffdfdf97.png)
2.worker conf 
![image](https://user-images.githubusercontent.com/9334358/85938218-ce175280-b93d-11ea-8e5b-4057c01f7dd4.png)
3.yarn app stauts
![image](https://user-images.githubusercontent.com/9334358/85938227-e5564000-b93d-11ea-806b-e4a0e550081a.png)

How can I solve this problem?

**Comment by super-sponge** [comment]
HadoopUtils.Java   207 lines  
       } else {
            //single resourcemanager enabled
            appUrl = appAddress;
            yarnEnabled = true;
        }

**Comment by wa-ooo** [comment]
We have made changes to support multiple yarn clusters, using YARN CLI to obtain the state of the application

**Comment by hlzhu1983** [comment]
> it occured when not enable HA. you should change HadoopUtils.Java code add appUrl = appAddress;
> 
> ```
>  } else {
>         //single resourcemanager enabled
>         appUrl = appAddress;
>         yarnEnabled = true;
>     }
> ```

It's a bug. If not fit that bug, single resourcemanager application status url is blank String, will lead to error as above.

**Comment by super-sponge** [comment]
> > it occured when not enable HA. you should change HadoopUtils.Java code add appUrl = appAddress;
> > ```
> >  } else {
> >         //single resourcemanager enabled
> >         appUrl = appAddress;
> >         yarnEnabled = true;
> >     }
> > ```
> 
> It's a bug. If not fit that bug, single resourcemanager application status url is blank String, will lead to error as above.

yes!

**Comment by super-sponge** [comment]
> We have made changes to support multiple yarn clusters, using YARN CLI to obtain the state of the application

does single yarn runing normal?
