### ISSUE TITLE
[BUG] com.sun.jna.platform.win32.Win32Exception: 占位程序接收到错误数据。when the WorkerServer work in the Windows

### ISSUE THREAD

**Issue by whitelowrie** [apache/incubator-dolphinscheduler#3064]
When I'm running the workerServer in Windows 10 System，I schedule a simple program like
`dir`
![image](https://user-images.githubusercontent.com/13913085/85939847-3f113700-b94b-11ea-967e-801608187ce9.png)

then the task run fail，and get some exception
![image](https://user-images.githubusercontent.com/13913085/85939830-138e4c80-b94b-11ea-99df-0b8cd63ad863.png)

**Comment by CalvinKirs** [comment]
Hello, workerServer recommends deploying linux or mac os. Currently, the overall deployment of ds does not support windows. Debugging under windows may encounter many problems.
