### ISSUE TITLE
why use the tenant configuration of the workflow in the downloadResource method of taskExecuteThread

### ISSUE THREAD

**Issue by wa-ooo** [apache/incubator-dolphinscheduler#3065]
version:1.3.0
Why use the tenant configuration of the workflow in the downloadResource method of TaskExecuteThread. If a user is given resource permissions in user management, but the tenant of the running workflow is not a tenant of the resource, an error is reported that the resource file is not retrieved
==============================
TaskExecuteThread的downloadResource 方法中使用工作流的租户配置。如果在用户管理中给用户分配了资源权限，但是运行的工作流的租户并不是资源上传用户的租户，那么就会报获取不到资源文件的错误

**Comment by xingchun-chen** [comment]
Yes, the tenant running the workflow needs to be the same as the tenant who created the resource file

**Comment by wa-ooo** [comment]
那为什么要在工作流中使用选择租户而不是用户绑定的租户。既然可以选择那么可以认为用户和租户是1-N的关系

**Comment by wa-ooo** [comment]
用户管理中可以对资源赋权，如果用户选择了其他租户运行任务就会报错
==============
Resources can be weighted in user management and an error will be reported if the user selects another tenant to run the task

**Comment by xingchun-chen** [comment]
yes,This problem has been mentioned in #2975, but it has not been resolved. At present, the save workflow can only be selected to be the same as the tenant of the authorization file without error.

**Comment by xingchun-chen** [comment]
This issue has been fixed  in #2975 ，you can be verified after the release of version 1.3.1. The issue is temporarily closed
