### ISSUE TITLE
[BUG]  DEPENDENT node type is not supported since version 1.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by adadfa2** [apache/incubator-dolphinscheduler#3067]
version 【1.2.1 】

When choosing to use the dependent node task, an error is reported during execution 
`[ERROR] 2020-06-28 15:27:22.118-[taskAppId=TASK-341-240188-431977]:[75]-unsupport task type: DEPENDENT`

See below

<img width="687" alt="微信图片_20200628175138" src="https://user-images.githubusercontent.com/38177161/85944264-0fbcf300-b968-11ea-89db-010d44850418.png">

code show as below

<img width="647" alt="微信图片_20200628174034" src="https://user-images.githubusercontent.com/38177161/85944027-7fca7980-b966-11ea-8d13-e60f4cd3d5c0.png">

==》https://github.com/apache/incubator-dolphinscheduler/blob/4946e88872ef943b5d0a739f213831daca3facd8/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java

**Comment by yangyichao-mango** [comment]
Hi,
What you mean is in the version 1.2.0 or bigger than version 1.2.0
Can you describe the detail how to reproduce this bug?
Thx a lot.

**Comment by BoYiZhang** [comment]
Your code version is wrong 

version: 1.2.0

![image](https://user-images.githubusercontent.com/39816903/85964044-c3ff5d80-b9ea-11ea-82f6-685114b70116.png)



https://github.com/apache/incubator-dolphinscheduler/blob/1.2.0-release/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java

**Comment by adadfa2** [comment]
In version 1.2.1, I got it wrong


Remove the version submitted by DEPENDENT here
==》

https://github.com/apache/incubator-dolphinscheduler/commit/7f94122f6eb201375b11e4e681849a66e6c572e4#diff-b75d01d2ea0e1cbee19329bfd4f9d78a

**Comment by BoYiZhang** [comment]
If using 1.2.1, use 1.2.1-release version

https://github.com/apache/incubator-dolphinscheduler/blob/1.2.1-release/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java

![image](https://user-images.githubusercontent.com/39816903/85966772-53a90a00-b9f3-11ea-9d7c-d1e7d5b6273f.png)

**Comment by BoYiZhang** [comment]
now dev branch 
 dependent and conditions  has moved to master server

**Comment by adadfa2** [comment]
> If using 1.2.1, use 1.2.1-release version
> 
> https://github.com/apache/incubator-dolphinscheduler/blob/1.2.1-release/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
> 
> ![image](https://user-images.githubusercontent.com/39816903/85966772-53a90a00-b9f3-11ea-9d7c-d1e7d5b6273f.png)

 1.2.1-release version is ok ，But I see that the 1.3 tag still has the same problem ==》https://github.com/apache/incubator-dolphinscheduler/blob/1.3.0/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java

**Comment by yangyichao-mango** [comment]
> > If using 1.2.1, use 1.2.1-release version
> > https://github.com/apache/incubator-dolphinscheduler/blob/1.2.1-release/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
> > ![image](https://user-images.githubusercontent.com/39816903/85966772-53a90a00-b9f3-11ea-9d7c-d1e7d5b6273f.png)
> 
> 1.2.1-release version is ok ，But I see that the 1.3 tag still has the same problem ==》https://github.com/apache/incubator-dolphinscheduler/blob/1.3.0/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java

Hi,
Because we move the dependent task to master server, you can check this commit [1].

[1]https://github.com/apache/incubator-dolphinscheduler/commit/4946e88872ef943b5d0a739f213831daca3facd8

**Comment by adadfa2** [comment]
> > > If using 1.2.1, use 1.2.1-release version
> > > https://github.com/apache/incubator-dolphinscheduler/blob/1.2.1-release/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
> > > ![image](https://user-images.githubusercontent.com/39816903/85966772-53a90a00-b9f3-11ea-9d7c-d1e7d5b6273f.png)
> > 
> > 
> > 1.2.1-release version is ok ，But I see that the 1.3 tag still has the same problem ==》https://github.com/apache/incubator-dolphinscheduler/blob/1.3.0/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/TaskManager.java
> 
> Hi,
> Because we move the dependent task to master server, you can check this commit [1].
> 
> [1][4946e88](https://github.com/apache/incubator-dolphinscheduler/commit/4946e88872ef943b5d0a739f213831daca3facd8)

Oh, thanks, we tested the latest version and 1.2.1-release version
