### ISSUE TITLE
[Feature] locate the specified task in a workflow

### ISSUE THREAD

**Issue by frankYu001** [apache/incubator-dolphinscheduler#3071]
when there are 20+ tasks in the workflow, we can not find the specified task easily. so I recommend add an function which can search the specified task ,like  locate the task node or show task list ,something etc. That is a usual case 20+ tasks in one 
flow and we sometime really need to locate the specified task.

**Comment by frankYu001** [comment]
在一个流中多于20个任务节点时，查询指定节点就比较困难，所以建议添加一个查询指定节点的功能，从使用场景上讲，一个流中task数量多是一般情况，有时候我们也确实需要定位到某个指定的task node

**Comment by Rubik-W** [comment]
You can use ctrl + F search text on browser.

**Comment by yangyichao-mango** [comment]
Hi,

What is the way you want to locate one task node? By name or by some other means?
If you want to locate by name, I think `Ctrl + F` from @Rubik-W will be a better way.

If you have any suggestion or idea, please put forward. Thx a lot.

**Comment by yangyichao-mango** [comment]
Tag: could be closed. @yangyichao-mango

**Comment by chengshiwen** [comment]
Close the issue since it has been replied
