### ISSUE TITLE
[BUG] repeated task name in one flow

### ISSUE THREAD

**Issue by frankYu001** [apache/incubator-dolphinscheduler#3077]
first add two different tasks,then rename one and keep both has a some name ,you will find you can save the flow with same name tasks.

**Comment by frankYu001** [comment]
先添加两个不重名的任务节点，然后修改任务名称相同，能正常保存；正常一个个添加时，就会提示名称重复，行为不一致，应该是前端校验的bug

**Comment by xingchun-chen** [comment]
which version?

**Comment by frankYu001** [comment]
1.3.0

**Comment by yangyichao-mango** [comment]
> which version?

Hi,
I reproduce this bug in `1.3.1-release` as the figure[1].
@fancyChuan Are you interested to submit a PR to solve this problem?

[1] ![image](https://user-images.githubusercontent.com/29545877/87425611-887ea900-c610-11ea-8ccf-ece1a19de7aa.png)

**Comment by yangyichao-mango** [comment]
Hi~,
This bug is easy to fix, anyone who are interested about fixing this bug, please leave a message.
