### ISSUE TITLE
[BUG] after zoom or drag the dag view, cant plcae node correctly and may be disappear

### ISSUE THREAD

**Issue by satcblue** [apache/incubator-dolphinscheduler#3085]
**Describe the bug**
After zoom or drag the dag view, cant plcae node correctly and may be disappear

**To Reproduce**
1. Go to 'project detail dag'
2. Scroll middle mouse button, zoom nodes
3. Drag new node into contaiment. (close to sidebar )
4. See error, the new node diappear, or it cant place what we want.

**Expected behavior**
When we drag new node into contaiment, it should not disappear. Because we do the correct thing, but something wrong happen.

**Screenshots**

![no zoom](https://user-images.githubusercontent.com/40662353/86087052-d0acb000-bad5-11ea-827e-de9316d989a1.png)
![after zoom](https://user-images.githubusercontent.com/40662353/86087169-1a959600-bad6-11ea-858a-b9fc00cc74f0.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0 to latest version ]

**Additional context**
After zooming (or drag #canvas element), the area of ​​the canvas and the outer area do not fit, causing the drag to fail.
I try to fix this problem. There has two ways.
1. use jsplumb nativie method to support zoom.
2. modify dragZoom.js code, change the zoom beahavior.

I choose 2, I think this way lead to increased code complexity. Any suggetions? Should I create a PR?

**Comment by break60** [comment]
good job, this is zoom in and zoom out without considering the zoom of the canvas, can you mention a pr to fix it

**Comment by satcblue** [comment]
> good job, this is zoom in and zoom out without considering the zoom of the canvas, can you mention a pr to fix it

ye, i will fix it these days.
