### ISSUE TITLE
[BUG] spark.vue 前端无法传到后台 主jar包 参数的名字

### ISSUE THREAD

**Issue by yeyudefeng** [apache/incubator-dolphinscheduler#3086]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
使用spark task组件，主jar包名称在后台无法获取值

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 使用spark task 组件，输入各种参数，包括选择主jar包
2. 点击提交，前端发现只有id，没有jar包名称
3. 后台无法接收到主jar包名称，会在TaskScheduleThread类的copyHdfsToLocal()方法里面的File resFile = new File(execLocalPath, res);该出代码报空指针，res为null，res为主jar包的名称，前端传不过来，因此报空指针

**Screenshots**
![image](https://user-images.githubusercontent.com/52660126/86090008-e45b1500-badb-11ea-985b-a002430b12f6.png)

![image](https://user-images.githubusercontent.com/52660126/86090341-7a8f3b00-badc-11ea-875a-19fa0b4fc248.png)

![image](https://user-images.githubusercontent.com/52660126/86090752-436d5980-badd-11ea-9dcc-a4cbe865bacd.png)

**Which version of Dolphin Scheduler:**
 -[1.3.0-preview]
我们的dolphinscheduler1.2.0的代码也有，1.3.0的代码也有，但是spark.vue用的是1.3.0的

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/86091543-a7dce880-bade-11ea-89ad-d93a5388be96.png)
Add command line parameters and run

**Comment by yeyudefeng** [comment]
这个错误还没有到执行spark-submit命令那一步，还只是在生成命令。因为报错，所以还没有生成命令的文件。而且该jar包没有其他参数需要输入

**Comment by yeyudefeng** [comment]
@xingchun-chen 这个错误还没有到执行spark-submit命令那一步，还只是在生成命令。因为报错，所以还没有生成命令的文件。而且该jar包没有其他参数需要输入

**Comment by lgcareer** [comment]
hi,please use english. The class `TaskScheduleThread` doesn't exist in the version of 1.3.0
please check your version.

**Comment by lgcareer** [comment]
If the backend you use 1.2.0 and the frontend you use 1.3.0, it will not scuccess because the frontend send resource name to backend on the version 1.2.0 but changed to resource id on the version 1.3.0

**Comment by yeyudefeng** [comment]
yes, the backend is 1.2.0 and  the frontend is 1.3.0, so it has some bugs in the frontend , you are great. I will try  to use the frontend on the version 1.2.0 , thank you . I think I find the problem .

**Comment by yeyudefeng** [comment]
@lgcareer Yes ,you are great . The frontend is 1.2.0, the backend is 1.3.0,  so the backend can not get the right parameters, it causes some bung . Maybe I find the key of this problem,  I will try to use the frontend on the version 1.2.0 , thanks.

**Comment by samz406** [comment]
good ,i closed.
