### ISSUE TITLE
失败告警推送增加微信或者QQ，钉钉等

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#3097]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/44901627/86106935-c8636d80-baf3-11ea-9154-7185b2891ab7.png)

**Comment by CalvinKirs** [comment]
Currently supports email, WeChat, DingTalk, DingTalk will be released in subsequent versions. Also, https://github.com/apache/incubator-dolphinscheduler/issues/2869
You can take a look at this issue. When this function is completed, you can complete your personalized early warning needs in the form of spi

**Comment by lenboo** [comment]
please change the title to english, after that , you can reopen this issue.

**Comment by doublezsx** [comment]
> Currently supports email, WeChat, DingTalk, DingTalk will be released in subsequent versions. Also, #2869
> You can take a look at this issue. When this function is completed, you can complete your personalized early warning needs in the form of spi
那个版本支持钉钉？
