### ISSUE TITLE
[QUESTION] auto pull latest code/jar from hdfs or target node

### ISSUE THREAD

**Issue by msmoving** [apache/incubator-dolphinscheduler#3098]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.
i use jenkins auto build and put latest jar to hdfs, can dolphinscheduler auto pull latest jar from hdfs before every run?

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
you can try, as I know, it's supported, worker server will pull the related content( e.g. jar files) from hdfs when executing the task instance

**Comment by dailidong** [comment]
I will close this issue, if  not supported, please reopen it
