### ISSUE TITLE
[Discuss]RIP DolphinScheduler Community 

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-dolphinscheduler#3110]
I read RIP-14 RocketMQ Community Operation Conventions, I think we also need to make such a specification, as follows

1:Test

Standardized testing can reduce the cost of review and quickly find problems to confirm the problem, so the test code link is more important than the code itself to a certain extent. When new code is submitted, we should also care about the quality of the test code.

2:Commit Message

Good commit messages should contain some contextual information. We can get the specific work of the commit from the commit messages, and we can use git instructions to quickly track related issues.

3:Isuess 

Good issues labeling and naming can help us organize existing problems in the community, and can also effectively avoid repeated problems

Label Conventions

ISSUE Label Conventions

Each issue needs to be labeled. Generally, an issue needs to have two types of labels, including

Type
  new feature
  bug
  enhancement
  test
  code style
  doc
  question
  discuss
  wontfix
  duplicate
  	...
Module
   server
   remote
   service
   spi
   ...	
Help
  help wanted
  good first issue
Priority
  blocker
  high
  low
  normal
Status
  need-triage
  do-not-merge
  ready-to-merge
  invalid
  wontfix

4:Pull Request

A good pull request can help the reviewer quickly understand the purpose of the request and improve the efficiency of the reviewer. We should make format requirements for the relevant requests and organize the standard documents.

Related documentation reference：
https://docs.google.com/document/d/1fo_Z4_nUOyykkmQOE2kEmxcLwhhFiQENQwQiy852XUM/edit#heading=h.nwczedg8v2na

**Comment by dailidong** [comment]
good job, looking forward to your DolphinScheduler draft

**Comment by yangyichao-mango** [comment]
https://lists.apache.org/thread.html/r589b62b9cdb8ddcb875b6af8486101c99ff40524638b0d5e6b710ab3%40%3Cdev.dolphinscheduler.apache.org%3E
