### ISSUE TITLE
[QUESTION] 安装完成后，如何将资源中心改为本地路径？

### ISSUE THREAD

**Issue by AlexSeven77** [apache/incubator-dolphinscheduler#3113]
请教一下，之前已经安装完成三节点的dolphinscheduler，当时没有配置资源中心路径，后面想把资源路径改为机器本地的路径，要在哪个文件里进行如何配置，谢谢。

**Comment by felix-thinkingdata** [comment]
Try this configuration   


resource.upload.path=file:///dolphinscheduler

**Comment by lenboo** [comment]
official english,  please change title and content to english. then reopen this issue.
