### ISSUE TITLE
Database does not exist

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#3117]
below error occurred when exec script， but the script work well on worker server

[INFO] 2020-07-02 19:36:32.149  - [taskAppId=TASK-4-46-104]:[106] -  -> 
[INFO] 2020-07-02 19:36:42.183  - [taskAppId=TASK-4-46-104]:[106] -  -> Logging initialized using configuration in jar:file:/opt/cloudera/parcels/CDH-5.11.2-1.cdh5.11.2.p0.4/jars/hive-common-1.1.0-cdh5.11.2.jar!/hive-log4j.properties
	FAILED: SemanticException [Error 10072]: Database does not exist: abc_db
[INFO] 2020-07-02 19:36:42.668  - [taskAppId=TASK-4-46-104]:[106] -  -> WARN: The method class org.apache.commons.logging.impl.SLF4JLogFactory#release() was invoked.
	WARN: Please see http://www.slf4j.org/codes.html#release for an explanation.

**Comment by samz406** [comment]
It may be that the error reported by the log did not exit abnormally, which caused the scheduling to fail to determine whether it exited abnormally. You first solved the problem according to the prompt.
有可能是日志报的错误没有异常退出，导致调度不能判断是否异常退出，你先按照日志提示把这个问题解决了吧

**Comment by JunjianS** [comment]
> It may be that the error reported by the log did not exit abnormally, which caused the scheduling to fail to determine whether it exited abnormally. You first solved the problem according to the prompt.
> 有可能是日志报的错误没有异常退出，导致调度不能判断是否异常退出，你先按照日志提示把这个问题解决了吧

thanks，because hive conf dir isn't set up correctly , dolphin can not read hive meta
