### ISSUE TITLE
[BUG] Format DAG bug [ the connection line disappears ]

### ISSUE THREAD

**Issue by muzhongjiang** [apache/incubator-dolphinscheduler#3120]
Format DAG bug [ the connection line disappears ]

1、click：
![image](https://user-images.githubusercontent.com/7700151/86439291-e373ee80-bd3a-11ea-9a5b-b178818e988a.png)

2、copy：
![image](https://user-images.githubusercontent.com/7700151/86439940-18cd0c00-bd3c-11ea-9324-566c609a7e36.png)

3、connect、format：
![image](https://user-images.githubusercontent.com/7700151/86440052-647fb580-bd3c-11ea-9b19-d29db13cfe9b.png)

4、line is gone：
![image](https://user-images.githubusercontent.com/7700151/86440078-6e091d80-bd3c-11ea-897c-912ff5d59875.png)

**Comment by xingchun-chen** [comment]
Formatting needs to save the workflow first, then click the format button to format
