### ISSUE TITLE
Can you change the ResourceManager HTTP port to a configuration file,thank you

### ISSUE THREAD

**Issue by databoyliu** [apache/incubator-dolphinscheduler#3122]
int activeResourceManagerPort = PropertyUtils.getInt(Constants.HADOOP_RESOURCE_MANAGER_HTTPADDRESS_PORT, 8088);

**Comment by felix-thinkingdata** [comment]
修改这个
common.properties配置文件
增加如下配置即可：
 resource.manager.httpaddress.port=xxxx

**Comment by databoyliu** [comment]
> 修改这个
> common.properties配置文件
> 增加如下配置即可：
> resource.manager.httpaddress.port=xxxx

Which version supports？

**Comment by samz406** [comment]
1.2+, common.properties is not available by default and needs to be added manually
