### ISSUE TITLE
[BUG] Permission denied if not found dolphinscheder-env.sh

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#3125]
when worker server execute the task , if not found dolphinscheder-env.sh, will get `System.getProperty("user.home") + File.separator + ".bash_profile"` , and it will lead to Permission denied error, something like `
[INFO] 2020-07-04 12:43:12.640  - [taskAppId=TASK-3-58-65]:[121] -  -> /tmp/dolphinscheduler/exec/process/1/3/58/65/3_58_65.command: line 4: /Users/stone/.bash_profile: Permission denied`

the related code in CommonUtils.java
```
public static String getSystemEnvPath() {
    String envPath = PropertyUtils.getString(Constants.DOLPHINSCHEDULER_ENV_PATH);
    if (StringUtils.isEmpty(envPath)) {
      URL envDefaultPath = CommonUtils.class.getClassLoader().getResource(Constants.ENV_PATH);

      if (envDefaultPath != null){
        envPath = envDefaultPath.getPath();
        logger.debug("env path :{}", envPath);
      }else{
        envPath = System.getProperty("user.home") + File.separator + ".bash_profile";
      }
    }

    return envPath;
  }

```

**Comment by dailidong** [comment]
if not found dolphinscheduler-env.sh, change the variable envPath to /etc/profile will be fine  
```
envPath =  "/etc/profile";
```

**Comment by liukunyuan** [comment]
I'll fix it

**Comment by dailidong** [comment]
> I'll fix it

good job, please submit to dev branch
