### ISSUE TITLE
[BUG] When the new tenant already exists, the prompt is incorrect

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3131]
1. Tenant cxc exists
2. When adding a tenant, fill in the tenant code cxc, the prompt is incorrect, as shown in the figure
![image](https://user-images.githubusercontent.com/55787491/86510027-ffe95700-be1e-11ea-9f2a-c4308243202b.png)

It should be reminded that the tenant already exists

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]

**Comment by xingchun-chen** [comment]
It is easy to fix, who wants to fix it

**Comment by yangyichao-mango** [comment]
I will do it.
