### ISSUE TITLE
[PROPOSAL] Datasource selection changes from radio to select

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#3139]
I suggest changing the previous method of selecting data sources into drop-down ones. Otherwise, once more data sources are added, the whole page will look bloated.

Change the way you selected the data source before

![image](https://user-images.githubusercontent.com/29206593/86532393-2af5a880-befc-11ea-8e68-d542e59e332c.png)

Change the way you selected the data source after

![image](https://user-images.githubusercontent.com/29206593/86532404-39dc5b00-befc-11ea-81e8-f5cf8888e380.png)

**Comment by wuchunfu** [comment]
I have implemented this function.

**Comment by dailidong** [comment]
good suggestion， glad to see you will implement it

**Comment by dailidong** [comment]
good job,  could you submit a PR ?

**Comment by wuchunfu** [comment]
I will submit a pull request later. Do I submit it to the dev branch?




Best Regards


wuchunfu
2020-07-05





------------------&nbsp;Original&nbsp;------------------

**Comment by dailidong** [comment]
yes，please submit PR to dev branch
