### ISSUE TITLE
[QUESTION]TaskExecuteThread killed, the MasterExecThread and MasterTaskExecThread keep running and can not be stopped

### ISSUE THREAD

**Issue by frankYu001** [apache/incubator-dolphinscheduler#3145]

**Comment by frankYu001** [comment]
当TaskExecuteThread因为一些原因执行失败中断掉，worker服务未中断，因为TaskExecuteProcessor提前doAck到master，流程状态为running，会导致master的MasterExecThread和MasterTaskExecThread一直执行，无法释放线程资源和改变任务状态了。

**Comment by yangyichao-mango** [comment]
> 当TaskExecuteThread因为一些原因执行失败中断掉，worker服务未中断，因为TaskExecuteProcessor提前doAck到master，流程状态为running，会导致master的MasterExecThread和MasterTaskExecThread一直执行，无法释放线程资源和改变任务状态了。

Hi,
Please update the description to English, and describe which version, how to reproduce this bug.

**Comment by samz406** [comment]
You mean that in a process, you manually kill one of the tasks. After killing the task, the status of the task has not changed, and it has been running all the time? do you mean this
你意思是在一个流程中，你手动kill掉其中一个任务，kill掉任务后任务的状态没有变，一直都是运行中？是这个意思吗

**Comment by taoyunuo** [comment]
> You mean that in a process, you manually kill one of the tasks. After killing the task, the status of the task has not changed, and it has been running all the time? do you mean this
> 你意思是在一个流程中，你手动kill掉其中一个任务，kill掉任务后任务的状态没有变，一直都是运行中？是这个意思吗

我的就是这样，请问该怎么解决呢
（你手动kill掉其中一个任务，kill掉任务后任务的状态没有变，一直都是运行中？是这个意思吗）

**Comment by xingchun-chen** [comment]
version 1.3.2 had solved
