### ISSUE TITLE
如何控制单台Worker的并发执行任务的数量

### ISSUE THREAD

**Issue by wxm245** [apache/incubator-dolphinscheduler#3149]
由于我们Spark任务太多，同一时间可能会提交多个任务。
但是我们单台机器最多支持20多个spark-submit任务进程，所以需要限制worker的任务提交数量，请问如何能控制

**Comment by lenboo** [comment]
official english,  please change title and content to english.

**Comment by hutiefang76** [comment]
这问题有结论了么?
