### ISSUE TITLE
version in pom.xml is diffent from branch

### ISSUE THREAD

**Issue by rockxsj** [apache/incubator-dolphinscheduler#3155]
Hi,I found the `1.3.1-release` branch has the diffent version in pom.xml, and the version in pom.xml is `1.3.2-SNAPSHOT`, is this a bug?

**Comment by BoYiZhang** [comment]
+1

![image](https://user-images.githubusercontent.com/39816903/87248513-60fed380-c48c-11ea-9389-de1eafc85e66.png)

**Comment by dailidong** [comment]
@lgcareer , please answer this question

**Comment by lgcareer** [comment]
Hi,this is correct.The branch is 1.3.1-release and it has released,it need to be 1.3.2-SNAPSHOT.
