### ISSUE TITLE
[BUG] rename origin task name and dependent type node perform not as expect

### ISSUE THREAD

**Issue by frankYu001** [apache/incubator-dolphinscheduler#3160]
As for depend task node, rename origin task name ,or remove origin task node , dependent task node name keep as before and the dependent task always goes wrong, no warning or other tips.

**Comment by wuchunfu** [comment]
Please describe the problem in detail, if there is a screenshot, it will be more expressive.

**Comment by yangyichao-mango** [comment]
Hi,
The same issue with #3214 , this issue will be closed.

If you have any question or suggestion, welcome to put forward~
