### ISSUE TITLE
创建租户的时候报错/create tenant error

### ISSUE THREAD

**Issue by 1findyou** [apache/incubator-dolphinscheduler#3162]
> **when i create a tenant, it shows "create tenant error"**  i just set up the environment

**Comment by samz406** [comment]
To create a tenant, you need to configure hdfs. Please check if the hdfs configuration is set.
Error details can be viewed in api logs

**Comment by 1findyou** [comment]
Thanks.  I have settled it


| |
chn_cjw
|
|
邮箱：chn_cjw@163.com
|

Signature is customized by Netease Mail Master

在2020年07月07日 22:17，samz406 写道：

To create a tenant, you need to configure hdfs. Please check if the hdfs configuration is set.
Error details can be viewed in api logs

**Comment by samz406** [comment]
ok ,i closed
