### ISSUE TITLE
[QUESTION] 有没有api获取任务在yarn上运行的 任务id

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#3164]
有没有api获取任务在yarn上运行的 任务id

因为ds如果是cluster模式运行的话，日志是看不全的，只能在yarn上看，这样不方便，有没有api获取当前的任务在yarn上运行的id，这样可以直接去yarn是上根据id查看，现在只能用名称来判断

![image](https://user-images.githubusercontent.com/44901627/86863119-1fbd9b00-c0fd-11ea-8685-f546c0b459a3.png)

或者在ds上有没有对应的接口可以看对应日志（cluster模式，client和local是可以通过接口看日志的）

**Comment by lenboo** [comment]
official english,  please change title and content to english.
