### ISSUE TITLE
config resource.storage.type=hdfs throw exception need config  resource.storage.type=HDFS

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3165]
when i config common.properties ,
resource.storage.type=hdfs

will throw exception 

![image](https://user-images.githubusercontent.com/59079269/86872565-3cfb6500-c10f-11ea-802b-21fdf1003db7.png)

because Enumerated type comparisons do not ignore case。

**Comment by lgcareer** [comment]
![image](https://user-images.githubusercontent.com/15651066/86991081-be66fc00-c1d0-11ea-8b03-f7156f049add.png)

hi,The `resourceStorageType` parameter of install_config.conf must be ont of the values of HDFS,S3,NONE.

**Comment by felix-thinkingdata** [comment]
> ![image](https://user-images.githubusercontent.com/15651066/86991081-be66fc00-c1d0-11ea-8b03-f7156f049add.png)
> 
> hi,The `resourceStorageType` parameter of install_config.conf must be one of the values of HDFS,S3,NONE.

My expectation is to make mistakes less likely.
