### ISSUE TITLE
How to control workflow control concurrent submission task node

### ISSUE THREAD

**Issue by Jops-data** [apache/incubator-dolphinscheduler#3168]
*For better global communication, please give priority to using English description, thx! *
**Describe the question**
If a workflow does not provide up-down dependency to connect task nodes, all tasks will be submitted at one time when the workflow is executed, which will cause the CPU of the machine to burst. Now I'd like to ask and then control the number of node submissions for the workflow.

**Which version of DolphinScheduler:**
1.2.1

**Requirement or improvement
I hope that the maximum number of submission nodes can be set in a workflow to control the number of submitted tasks, rather than through the dependency relationship between nodes.

**Comment by BoYiZhang** [comment]
You can configure [ master.properties ]
such as:

# master execute thread num
#master.exec.threads=100

# master execute task number in parallel
#master.exec.task.num=20


# master dispatch task number
#master.dispatch.task.num = 3


# only less than cpu avg load, master server can work.  default value -1 : the number of cpu cores * 2
#master.max.cpuload.avg=-1

# only larger than reserved memory, master server can work. default value : physical memory * 1/10, unit is G.
#master.reserved.memory=0.3

**Comment by dailidong** [comment]
did you mean this feature idea? https://github.com/apache/incubator-dolphinscheduler/issues/268

**Comment by Jops-data** [comment]
Yes, this idea can be solved！
