### ISSUE TITLE
[QUESTION] 1.3.1-release page display disorder after compilation

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3173]
*1.3.1-release page display disorder after compilation *

**Describe the question**
Using 1.3.1-release to compile, 1. The graphic scale of the front page is disordered; 2. Each time the component is pushed in the canvas in the workflow definition, the prompt text of the component name does not disappear and always exists.

**Which version of DolphinScheduler:**
 -[1.3.1-release]

---
*[QUESTION] 1.3.1-release 编译之后页面显示错乱问题*

**Describe the question**
使用1.3.1-release编译，1.首页图形比例展示错乱 2.工作流定义中画布里每次推动组件，组件名提示文字不消失，一直存在。

**Which version of DolphinScheduler:**
 -[1.3.1-release]

**Comment by zhuangchong** [comment]
![画布](https://user-images.githubusercontent.com/37063904/87031436-baa99880-c215-11ea-9edc-3c42b7721e79.png)
![首页](https://user-images.githubusercontent.com/37063904/87031468-c4330080-c215-11ea-9bbd-eccaa7d24e0a.png)

**Comment by dailidong** [comment]
@break60

**Comment by break60** [comment]
1. What browser do you use, it is recommended to use Google
2. Does the console report an error?

**Comment by yoreyuan** [comment]
> 1. What browser do you use, it is recommended to use Google
> 2. Does the console report an error?

When using Safari, there will be a problem with the date being displayed abnormally. And then Google Chrome will be normal.

![Invalid Date](https://cdn.nlark.com/yuque/0/2020/png/649951/1594351663327-cf5ab290-7941-45eb-82c6-40364fa517c2.png)

**Comment by break60** [comment]
What you answered is inconsistent with the issue you mentioned, what happened to your page mess, and your dag display problem

**Comment by yoreyuan** [comment]
> What you answered is inconsistent with the issue you mentioned, what happened to your page mess, and your dag display problem

This problem was encountered by Author , and I did not meet the problem in Issue.
If it's a browser problem, the date of this version is not normal in safari.

**Comment by zhuangchong** [comment]
> 1. What browser do you use, it is recommended to use Google
> 2. Does the console report an error?

1.I'm using the Google browser
2.he console did not report an error
![首页-无报错](https://user-images.githubusercontent.com/37063904/87116388-423fe780-c2a8-11ea-9204-86f279991b45.png)
![画布-无报错](https://user-images.githubusercontent.com/37063904/87116394-479d3200-c2a8-11ea-9c84-e2c4b7ee3d73.png)

**Comment by break60** [comment]
> > What you answered is inconsistent with the issue you mentioned, what happened to your page mess, and your dag display problem
> 
> This problem was encountered by Author , and I did not meet the problem in Issue.
> If it's a browser problem, the date of this version is not normal in safari.

Only Google compatibility is currently considered

**Comment by break60** [comment]
> > 1. What browser do you use, it is recommended to use Google
> > 2. Does the console report an error?
> 
> @break60
> 1.I'm using the Google browser
> 2.The console did not report an error
> ![首页-无报错](https://user-images.githubusercontent.com/37063904/87116388-423fe780-c2a8-11ea-9204-86f279991b45.png)
> ![画布-无报错](https://user-images.githubusercontent.com/37063904/87116394-479d3200-c2a8-11ea-9c84-e2c4b7ee3d73.png)

Let me take a look at your screenshot, you seem to have made a second transformation of it yourself

**Comment by yoreyuan** [comment]
> > > What you answered is inconsistent with the issue you mentioned, what happened to your page mess, and your dag display problem
> > 
> > 
> > This problem was encountered by Author , and I did not meet the problem in Issue.
> > If it's a browser problem, the date of this version is not normal in safari.
> 
> Only Google compatibility is currently considered

I got the answer. This is my solution now also. thanks!

**Comment by zhuangchong** [comment]
> > > 1. What browser do you use, it is recommended to use Google
> > > 2. Does the console report an error?
> > 
> > 
> > @break60
> > 1.I'm using the Google browser
> > 2.The console did not report an error
> > ![首页-无报错](https://user-images.githubusercontent.com/37063904/87116388-423fe780-c2a8-11ea-9204-86f279991b45.png)
> > ![画布-无报错](https://user-images.githubusercontent.com/37063904/87116394-479d3200-c2a8-11ea-9c84-e2c4b7ee3d73.png)
> 
> Let me take a look at your screenshot, you seem to have made a second transformation of it yourself

Just a new plug-in, I don't think it will affect the home page

**Comment by break60** [comment]
I also don’t know what code you changed, you can restore it and take a look, or pull a new dev code to try

**Comment by zhuangchong** [comment]
Pull on a new branch, same problem，

1.3.1-release

![image](https://user-images.githubusercontent.com/37063904/87118821-f2185380-c2ae-11ea-895b-fce500ee834e.png)

![image](https://user-images.githubusercontent.com/37063904/87118855-0b210480-c2af-11ea-823e-d75004129f9d.png)

**Comment by yangyichao-mango** [comment]
> Pull on a new branch, same problem，
> 
> 
> 
> 1.3.1-release
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37063904/87118821-f2185380-c2ae-11ea-895b-fce500ee834e.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37063904/87118855-0b210480-c2af-11ea-823e-d75004129f9d.png)
> 
> 

Hi,
There is http response code 304 in your http request in screenshot. Can you try to clear you Chrome cache and refresh this page ？

**Comment by break60** [comment]
> > Pull on a new branch, same problem，
> > 1.3.1-release
> > ![image](https://user-images.githubusercontent.com/37063904/87118821-f2185380-c2ae-11ea-895b-fce500ee834e.png)
> > ![image](https://user-images.githubusercontent.com/37063904/87118855-0b210480-c2af-11ea-823e-d75004129f9d.png)
> 
> Hi,
> There is http response code 304 in your http request in screenshot. Can you try to clear you Chrome cache and refresh this page ？

This is not a caching problem for him. It must be no problem at the beginning, and then he corrected the problem himself
