### ISSUE TITLE
master server stopped

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#3175]
version：1.2.1

master server stopped， but there is no error, below is master server log 

[INFO] 2020-07-10 08:17:58.940 org.apache.zookeeper.ClientCnxn:[1156] - Client session timed out, have not heard from server in 2668ms for sessionid 0x46bb5fd0abd39ac, closing socket connection and attempting reconnect
[INFO] 2020-07-10 08:17:59.040 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: SUSPENDED
[INFO] 2020-07-10 08:17:59.041 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: SUSPENDED
[INFO] 2020-07-10 08:17:59.041 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: SUSPENDED
[INFO] 2020-07-10 08:17:59.041 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: SUSPENDED
[INFO] 2020-07-10 08:17:59.370 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server hadoop06/172.xxx.xxx.xxx:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-07-10 08:17:59.371 org.apache.zookeeper.ClientCnxn:[879] - Socket connection established to hadoop06/172.xxx.xxx.xxx:2181, initiating session
....

[INFO] 2020-07-10 08:18:00.141 org.apache.zookeeper.ClientCnxn:[522] - EventThread shut down for session: 0x46bb5fd0abd39aa
[INFO] 2020-07-10 08:18:00.142 org.apache.zookeeper.ClientCnxn:[522] - EventThread shut down for session: 0x46bb5fd0abd39ab
[WARN] 2020-07-10 08:18:00.303 org.apache.curator.retry.ExponentialBackoffRetry:[74] - Sleep extension too large (300). Pinning to 100
[INFO] 2020-07-10 08:18:04.013 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerThread:[143] - master server stopped...

**Comment by BoYiZhang** [comment]
Look up the mistakes:   Will not attempt to authenticate using SAS
ZK configuration file directory:  {dolphinscheduler home}/conf/zookeeper.properties

**Comment by dailidong** [comment]
> Master and worker cannot connect to ZK, so it will fail to start
> Look up the mistakes: Will not attempt to authenticate using SAS
> ZK configuration file directory: {dolphinscheduler home}/conf/zookeeper.properties

and did you config max session timeout for zookeeper, you can set it to 60000, the default value is too small

**Comment by liangpingliu** [comment]
> > Master and worker cannot connect to ZK, so it will fail to start
> > Look up the mistakes: Will not attempt to authenticate using SAS
> > ZK configuration file directory: {dolphinscheduler home}/conf/zookeeper.properties
> 
> and did you config max session timeout for zookeeper, you can set it to 60000, the default value is too small

The default is 60000
