### ISSUE TITLE
[BUG] optimize #3165  Gets the value of this property “resource.storage.type”， Comparison with enumerated types 

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3176]
By looking at the ResourcesService  code, I found a potential problem.

Enumeration type comparisons are used in both classes ：HadoopUtils.java ,CommonUtils.java

I don't think this [submission](https://github.com/apache/incubator-dolphinscheduler/pull/3166)  is perfect

All comparisons of ResUploadType need to be optimized.

I'm going to modify this part

中文：

通过阅读ResourcesService代码，发现了潜在隐患。

在HadoopUtils和CommonUtils,资源中心类型，都是通过枚举类型比较。

所以感觉到[submission](https://github.com/apache/incubator-dolphinscheduler/pull/3166) 这个提交是不完备的。

需要优化所有的ResUploadType类型比较部分的代码。

**Comment by yangyichao-mango** [comment]
Hi,
Please modify the issue content according to the template specification when creating the issue, it can help us locate the problem more quickly. 

And can you describe
1.what kind of bug will it lead to at present 
2.what kind of potential problem exist

Issue content template as follow: 

```
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**
Add any other context about the problem here.

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

```
