### ISSUE TITLE
[BUG] The shellTask scheduler reruns the date expression in the script to the current system time

### ISSUE THREAD

**Issue by wa-ooo** [apache/incubator-dolphinscheduler#3177]
**Describe the bug**
look at the code shows that parameter parsing is done internally twice, the first parsing takes the time expression into the current running time because there is no schedule.time in paramsMap

查看代码可以知道在内部做了两次的参数解析，第一次的解析会把时间表达式处理成运行的当前时间，因为paramsMap中并没有schedule.time

**To Reproduce**
1.new process
2.add shell task with script：echo "$[yyyy-MM-dd HH:mm:ss]"
3.Configure scheduling task with cron : 0 * * * * ? *
4.Wait for a scheduling task to complete （ workflow instance run in 2020-01-02 12:01:00）
5.Rerun the workflow instance (workflow instance rerun in 2020-01-02 12:10:01)
6.View the log data, will see that the output is the time the workflow was rerun ;(log prints "2020-01-02 12:10:01")

**Expected behavior**
The log prints the scheduled time (log output ”2020-01-02 12:01:00“ instead of ”2020-01-02 12:10:01“ )

```
/**
     *  combining local and global parameters
     */
    Map<String, Property> paramsMap = ParamUtils.convert(ParamUtils.getUserDefParamsMap(taskExecutionContext.getDefinedParams()),
            taskExecutionContext.getDefinedParams(),
            shellParameters.getLocalParametersMap(),
            CommandType.of(taskExecutionContext.getCmdTypeIfComplement()),
            taskExecutionContext.getScheduleTime());
    if (paramsMap != null){
      //paramsMap可能为空，并且ParameterUtils.convertParameterPlaceholders方法使用了system.datetime解析[yyyyMM],第二次的schedule.time总是用不到
      script = ParameterUtils.convertParameterPlaceholders(script, ParamUtils.convert(paramsMap));
    }
    // new
    // replace variable TIME with $[YYYYmmddd...] in shell file when history run job and batch complement job
    if (paramsMap != null) {
      if (taskExecutionContext.getScheduleTime() != null) {
        String dateTime = DateUtils.format(taskExecutionContext.getScheduleTime(), Constants.PARAMETER_FORMAT_TIME);
        Property p = new Property();
        p.setValue(dateTime);
        p.setProp(Constants.PARAMETER_SHECDULE_TIME);
        paramsMap.put(Constants.PARAMETER_SHECDULE_TIME, p);
      }
      script = ParameterUtils.convertParameterPlaceholders2(script, ParamUtils.convert(paramsMap));
    }
```

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]

**Requirement or improvement**
remove the code
```
if (paramsMap != null){
      script = ParameterUtils.convertParameterPlaceholders(script, ParamUtils.convert(paramsMap));
    }
```

**Comment by yangyichao-mango** [comment]
Hi,
Please modify the issue content according to the template specification when creating the issue, it can help us locate the problem more quickly, issue content template as follow:

*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**
Add any other context about the problem here.

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wa-ooo** [comment]
> Hi,
> Please modify the issue content according to the template specification when creating the issue, it can help us locate the problem more quickly, issue content template as follow:
> 
> ```
> *For better global communication, please give priority to using English description, thx! *
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior, for example:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> 
> **Which version of Dolphin Scheduler:**
>  -[1.1.0-preview]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> **Requirement or improvement
> - Please describe about your requirements or improvement suggestions.
> ```

ok ,I updated it

**Comment by yangyichao-mango** [comment]
Hi,
I do not reproduce this bug int `1.3.1-release` branch with script `echo "${yyyy-MM-dd HH:mm:ss}"`. The screenshot can refer to [1].
And the result of `echo "${schedule.time}"` refer to [2], [3]. 

And I think it is the right when shellTask scheduler reruns the date expression in the script to the current system time.
If you have any question or suggestion, please put forward.

[1] ![image](https://user-images.githubusercontent.com/29545877/87245503-7bc74d00-c478-11ea-90f4-434afbb611f8.png)
[2] ![image](https://user-images.githubusercontent.com/29545877/87245644-a8c82f80-c479-11ea-9190-e5a2056120dc.png)
[3] ![image](https://user-images.githubusercontent.com/29545877/87245658-bda4c300-c479-11ea-84ea-49cf117cac07.png)

**Comment by wa-ooo** [comment]
> Hi,
> I do not reproduce this bug int `1.3.1-release` branch with script `echo "${yyyy-MM-dd HH:mm:ss}"`. The screenshot can refer to [1].
> And the result of `echo "${schedule.time}"` refer to [2], [3].
> 
> And I think it is the right when shellTask scheduler reruns the date expression in the script to the current system time.
> If you have any question or suggestion, please put forward.
> 
> [1] ![image](https://user-images.githubusercontent.com/29545877/87245503-7bc74d00-c478-11ea-90f4-434afbb611f8.png)
> [2] ![image](https://user-images.githubusercontent.com/29545877/87245644-a8c82f80-c479-11ea-9190-e5a2056120dc.png)
> [3] ![image](https://user-images.githubusercontent.com/29545877/87245658-bda4c300-c479-11ea-84ea-49cf117cac07.png)

sorry,the error I described,script is `echo $[yyyy-MM-dd HH:mm:ss]`;

if that's right，the scheduling time will never take effect. from source code and actual usage ,that's not the real purpose

**Comment by yangyichao-mango** [comment]
This parameter will only return the current timestamp. What you said should be the function of `supplementing data`.

For example, when a user needs to rerun the task of the previous day or supplement data of the previous day , the user just wants this parameter to return to the previous day's time. Is this the scene you are referring to?

**Comment by wa-ooo** [comment]
> This parameter will only return the current timestamp. What you said should be the function of `supplementing data`.
> 
> For example, when a user needs to rerun the task of the previous day or supplement data of the previous day , the user just wants this parameter of the previous day's time. Is this the scene you are referring to?

Yes, it is easier to use if you rerun the working instance directly without modifying the script

**Comment by yangyichao-mango** [comment]
> > This parameter will only return the current timestamp. What you said should be the function of `supplementing data`.
> > For example, when a user needs to rerun the task of the previous day or supplement data of the previous day , the user just wants this parameter of the previous day's time. Is this the scene you are referring to?
> 
> Yes, it is easier to use if you rerun the working instance directly without modifying the script

![image](https://user-images.githubusercontent.com/29545877/88475457-872f7380-cf62-11ea-91e3-8d8047c65896.png)

**Comment by wa-ooo** [comment]
> > > This parameter will only return the current timestamp. What you said should be the function of `supplementing data`.
> > > For example, when a user needs to rerun the task of the previous day or supplement data of the previous day , the user just wants this parameter of the previous day's time. Is this the scene you are referring to?
> > 
> > 
> > Yes, it is easier to use if you rerun the working instance directly without modifying the script
> 
> We can use this params.
> ![image](https://user-images.githubusercontent.com/29545877/88475457-872f7380-cf62-11ea-91e3-8d8047c65896.png)

 Yes, `Fix - 3177` make `ParameterUtils.convertParameterPlaceholders ()` method of using ${system.datetime} to parse the time expressions in the script (`$[yyyyMMdd]`),it can solve the problem. But I have a question, In `shelltask.java` in 151 lines at the same time use the `ParameterUtils. ConvertParameterPlaceholders2()` method to parse time expression ($[yyyyMMdd]), the code is always not be performed, because `ParameterUtils.ConvertParameterPlaceholders ()` method has been parsed.I think that in `ParameterUtils ConvertParameterPlaceholders2 ()` method is used the `schedule.time` to parse time expression is more reasonable
