### ISSUE TITLE
[BUG] cache  bug

### ISSUE THREAD

**Issue by muzhongjiang** [apache/incubator-dolphinscheduler#3179]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7700151/87138506-1a18ae80-c2d1-11ea-8a75-98af77b07589.png)

When I go to use it

![image](https://user-images.githubusercontent.com/7700151/87138427-fd7c7680-c2d0-11ea-971d-02800505ba9b.png)

**Comment by dailidong** [comment]
could you submit a PR to solve this problem?

**Comment by muzhongjiang** [comment]
OK, I will fix it

**Comment by muzhongjiang** [comment]
> could you submit a PR to solve this problem?

OK, I will fix it
