### ISSUE TITLE
[QUESTION] how to get the YARN task id from DS api

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#3183]
we find the task on YARN must by task name ,this way is not conveniencet. so I want to know if there has any way to get YARN taks ID.
![image](https://user-images.githubusercontent.com/44901627/87160548-b6ed4300-c2f5-11ea-988b-9de36932b196.png)

**Comment by dailidong** [comment]
for now, this is not open.  DS get yarn application id from task instance runtime log, you can referer the following code:  
![image](https://user-images.githubusercontent.com/15833811/87210578-ab773780-c348-11ea-9c1b-873465ebdff8.png)

Why do you want to get yarn application id?

**Comment by gabrywu** [comment]
I think @dailidong gave enough infos. Ticket closed, feel free to reopen it
