### ISSUE TITLE
[Feature] DAG need to add a close button ?

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3190]
The current version will not jump to the list page after the process definition is saved

Do you have any special needs?

In addition, there is no close button on the details page of the process instance

It is very inconvenient in operation

If there is no special requirement, I will add a close button

As shown in the figure below:

![image](https://user-images.githubusercontent.com/39816903/87220192-6aa51000-c394-11ea-8c12-746d335849bb.png)

**Comment by yangyichao-mango** [comment]
Good feature.
