### ISSUE TITLE
[Feature] add query top n process instance order by running duration

### ISSUE THREAD

**Issue by RedemptionC** [apache/incubator-dolphinscheduler#3191]
add query top n process instance (only SUCCESS) order by running duration which started in a specified time range

**Comment by yangyichao-mango** [comment]
> add query top n process instance (only SUCCESS) order by running duration which started in a specified time range

Good feature.
Will this feature be displayed on the front end?

**Comment by RedemptionC** [comment]
> > add query top n process instance (only SUCCESS) order by running duration which started in a specified time range
> 
> Good feature.
> Will this feature be displayed on the front end?

I consulted my mentor and he said that's not my task
actually I am participating open summer 2020,I am trying to accomplish project 2002415
and I believe this feature will be used somehow ,but probably someone else will write the code

**Comment by yangyichao-mango** [comment]
> > > add query top n process instance (only SUCCESS) order by running duration which started in a specified time range
> > 
> > 
> > Good feature.
> > Will this feature be displayed on the front end?
> 
> I consulted my mentor and he said that's not my task
> actually I am participating open summer 2020,I am trying to accomplish project 2002415
> and I believe this feature will be used somehow ,but probably someone else will write the code

Hi,
I got your point, thx a lot for your contribution.

**Comment by lenboo** [comment]
does this feature have any detail description or document?

**Comment by RedemptionC** [comment]
> does this feature have any detail description or document?

https://cwiki.apache.org/confluence/display/DOLPHINSCHEDULER/Open+Source+Promotion+Plan+-+Summer+2020+Tasks

**Comment by dailidong** [comment]
PR #3315 implemented this feature
