### ISSUE TITLE
[QUESTION] Does DS support telnet or Spring Boot Endpoint?

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dolphinscheduler#3192]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
Does ds support telnet command or Spring Boot Endpoint? For example, close the DS server elegantly by telnet.

**Which version of DolphinScheduler:**
 - all

**Comment by yangyichao-mango** [comment]
Hi,
Can you describe the benefits of introducing this feature? And can you put forward some kind of technology selection can be used for implement this feature.
Thx a lot.

**Comment by gabrywu** [comment]
not supported yet. I think there's no benefits with this feature
