### ISSUE TITLE
[Question] What is the use of E2E ???

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3197]
What is the use of E2E? What is its use?

Is there any documentation?

![image](https://user-images.githubusercontent.com/39816903/87243427-8d085d80-c468-11ea-9785-13297df5ea99.png)

**Comment by gabrywu** [comment]
@chenxingchun might help

**Comment by BoYiZhang** [comment]
E2E is used for web automation testing.
