### ISSUE TITLE
[Question] Question title

### ISSUE THREAD

**Issue by ldboyghg** [apache/incubator-dolphinscheduler#3202]
1,replace file
sed: -e expression #1, char 37: unknown option to `s'
2,create directory
3,stop server
localhost
sh: bin/dolphinscheduler-daemon.sh: No such file or directory
localhost
sh: bin/dolphinscheduler-daemon.sh: No such file or directory
sh: bin/dolphinscheduler-daemon.sh: No such file or directory
sh: bin/dolphinscheduler-daemon.sh: No such file or directory
localhost
sh: bin/dolphinscheduler-daemon.sh: No such file or directory
4,delete zk node
deleted success
5,scp resources
scp: /opt/dolphinscheduler/bin: Permission denied
scp: /opt/dolphinscheduler/conf: Permission denied
scp: /opt/dolphinscheduler/lib: Permission denied
scp: /opt/dolphinscheduler/script: Permission denied
scp: /opt/dolphinscheduler/sql: Permission denied
scp: /opt/dolphinscheduler/install.sh: Permission denied
scp copy failed to exit

what the scp the purpose ?  why not got permission? pelease help~

**Comment by BoYiZhang** [comment]
The SCP command is used to send installation files to other nodes

Please refer to the documentation for installation : 

https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/cluster-deployment.html

**Comment by dailidong** [comment]
no title?
