### ISSUE TITLE
大佬们是否可以添加通过一个调度任务动态添加多个一次性的调度任务的功能啊

### ISSUE THREAD

**Issue by shenqicheng100** [apache/incubator-dolphinscheduler#3203]
比如我现在有一个每天9点的定时查询需要会议通知的数据，然后通过这些数据动态的创建一次性定时任务，
如果现有存在支持的话那应该怎么实现了，
或者是否有一个接口提供我来创建呢

**Comment by liukunyuan** [comment]
you can use shell task(java) or python task to do it.
你可以使用java或者python任务实现它，只需要在你java或者python代码中查询数据库，然后执行逻辑就行了

**Comment by shenqicheng100** [comment]
我现在使用的是java ,您的意思是说 通过dolphinscheduler 执行9点的调度 然后再java 端使用quartz来添加添加多个一次性的定时任务吗？

**Comment by shenqicheng100** [comment]
> 我现在使用的是java，您的意思是说通过dolphinscheduler执行9点的调度然后再java端使用quartz来添加多个一次性的定时任务吗？

**Comment by wuchunfu** [comment]
please upstate the title in english.

**Comment by liukunyuan** [comment]
> 我现在使用的是java ,您的意思是说 通过dolphinscheduler 执行9点的调度 然后在java 端使用quartz来添加多个一次性的定时任务吗？
You can schedule it every hour.
你的意思是，9点钟查询今天有哪些会议，然后到了时间给用户发会议通知？那你可以每30分钟或者每小时调度，而不是9点钟进行调度。

**Comment by shenqicheng100** [comment]
> > 我现在使用的是java的，您的意思是说通过dolphinscheduler执行9点的调度然后在的Java端使用石英来添加多个一次性的定时任务吗？
> > 你可以安排它每隔一小时。
> > 你的意思是，9点钟查询今天有一些会议，然后到时间给用户发会议通知？那你可以每30分钟或者每小时调度，而不是9点钟进行调度。

是的 现在是使用quartz来实现的，时间的话是需求定的我也不好更改， 因为想使用dolphinscheduler来替换现有平台调度工具，但是遇到了现在这个问题， 如果可以解决的话 就可以全部替换掉了

**Comment by lenboo** [comment]
please change the title and content to english, then reopen it.
