### ISSUE TITLE
[Bug][api] Error enMsg zhMsg in Status.PROCESS_NODE_S_PARAMETER_INVALID

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3211]
**Describe the bug**
When build the error message, it will show `流程节点[%s]参数无效` or `process node %s parameter invalid`, do not fill the `%s` parameter.

**Screenshots**
1.3.1-release
![image](https://user-images.githubusercontent.com/29545877/87495265-84d83a00-c683-11ea-8332-81ed4760e29d.png)
1.2.1-release
![image](https://user-images.githubusercontent.com/29545877/87523102-09917b00-c6b9-11ea-9245-e5052c7404ed.png)
1.2.0-release
![image](https://user-images.githubusercontent.com/29545877/87523355-6a20b800-c6b9-11ea-9543-96058b07dbac.png)

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]
 -[1.2.1-release]
 -[1.2.0-release]

**Requirement or improvement**
- Change `%s` to `{0}`

**Comment by gabrywu** [comment]
@yangyichao-mango You can create a PR to fix it

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango You can create a PR to fix it

Ok, I will fix it.
