### ISSUE TITLE
[Question] dependent task renamed

### ISSUE THREAD

**Issue by yeyudefeng** [apache/incubator-dolphinscheduler#3214]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

I create a process_definition, and it insert a record into the table named t_ds_process_definition, one field  named process_definition_json in this table .If tihis process_definition include a task type of dependent named aa and from another process , then process_definition_json will include aa, now , once I change aa to bb, this name has changed , but  this process_definition_json will not be changed , so this question comming,  when this process_definition exec, this task type of dependent will not be find , it maybe make some error.

**Which version of DolphinScheduler:**
both 1.2.0 and 1.3.0 mixed
**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
If the task from another process has renamed , can we make the process_definition_json changed ?

![image](https://user-images.githubusercontent.com/52660126/87499441-df29c880-c68c-11ea-998b-8822a3cdeb48.png)
![image](https://user-images.githubusercontent.com/52660126/87499588-3f206f00-c68d-11ea-9a52-c13160eb65b9.png)

**Comment by dailidong** [comment]
please add title，thx

**Comment by yangyichao-mango** [comment]
Hi,

1.3.x version do not have this problem, we set the `process definition id` in `process_definition_json` of `dependent task`.[1]
Version 1.2 to be viewed later.

[1] ![image](https://user-images.githubusercontent.com/29545877/88354606-0ae73580-cd94-11ea-93ef-c9432197ed37.png)

**Comment by yangyichao-mango** [comment]
> Hi,
> 
> 1.3.x version do not have this problem, we set the `process definition id` in `process_definition_json` of `dependent task`.[1]
> Version 1.2 to be viewed later.
> 
> [1] ![image](https://user-images.githubusercontent.com/29545877/88354606-0ae73580-cd94-11ea-93ef-c9432197ed37.png)



> Hi,
> 
> 1.3.x version do not have this problem, we set the `process definition id` in `process_definition_json` of `dependent task`.[1]
> Version 1.2 to be viewed later.
> 
> [1] ![image](https://user-images.githubusercontent.com/29545877/88354606-0ae73580-cd94-11ea-93ef-c9432197ed37.png)

1.2.x also do not have this bug after reviewed the source code.
If you have any question or suggestion, please leave a message.
This issue could be closed.

**Comment by yangyichao-mango** [comment]
Tag: Could be closed. @yangyichao-mango

**Comment by yeyudefeng** [comment]
thanks@yangyichao-mango
