### ISSUE TITLE
[Question]The hive data source page shows whether Kerberos can be connected

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3216]
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
At present: whether the hive data source page displays the principal [connect Kerberos] depends on the configuration file resource.storage.type & & hadoop.security.authentication . startup.state In which resource.storage.type The resource file storage location should be specified if resource.storage.type=NONE Can't I connect Kerberos with the hive data source?
code:
 /**
   * if upload resource is HDFS and kerberos startup is true , else false
   * @return true if upload resource is HDFS and kerberos startup
   */
  public static boolean getKerberosStartupState(){
    String resUploadStartupType = PropertyUtils.getUpperCaseString(Constants.RESOURCE_STORAGE_TYPE);
    ResUploadType resUploadType = ResUploadType.valueOf(resUploadStartupType);
    Boolean kerberosStartupState = PropertyUtils.getBoolean(Constants.HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE,false);
    return resUploadType == ResUploadType.HDFS && kerberosStartupState;
  }

**Which version of DolphinScheduler:**
 -[1.3.1-release]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

---
**Describe the question**
目前：HIVE数据源页面是否展示Principal【连接Kerberos】取决于配置文件上resource.storage.type && hadoop.security.authentication.startup.state ，其中resource.storage.type指定的应该是资源文件存储地方，如果为resource.storage.type=NONE就不能用HIVE数据源连接Kerberos？
以下是源码：
 /**
   * if upload resource is HDFS and kerberos startup is true , else false
   * @return true if upload resource is HDFS and kerberos startup
   */
  public static boolean getKerberosStartupState(){
    String resUploadStartupType = PropertyUtils.getUpperCaseString(Constants.RESOURCE_STORAGE_TYPE);
    ResUploadType resUploadType = ResUploadType.valueOf(resUploadStartupType);
    Boolean kerberosStartupState = PropertyUtils.getBoolean(Constants.HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE,false);
    return resUploadType == ResUploadType.HDFS && kerberosStartupState;
  }

**Which version of DolphinScheduler:**
版本- -[1.3.1-release]

**Comment by xingchun-chen** [comment]
whether your problem has solved?
