### ISSUE TITLE
[Bug][worker] There are no worker groups generated in zk, and task instances are not executed

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3217]
1. Configure worker group cxc, execute sh install.sh, check the worker group in zk, no cxc group is generated
![image](https://user-images.githubusercontent.com/55787491/87510643-86ffc000-c6a6-11ea-93eb-72cf6a98ac66.png)
![image](https://user-images.githubusercontent.com/55787491/87510656-8d8e3780-c6a6-11ea-9790-09440583bccc.png)

2. Run the workflow, the task is not executed
![image](https://user-images.githubusercontent.com/55787491/87510696-9ed74400-c6a6-11ea-9db7-b94243f0ee96.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by yangyichao-mango** [comment]
Worker group now should be configurated in worker.properties. #2815
