### ISSUE TITLE
[Feature][datasource] Store password in ciphertext instead

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3222]
At present, the password in data source is stored in plaintext
It's not safe

t_ds_datasource:
![image](https://user-images.githubusercontent.com/39816903/87625123-f1bf0300-c75b-11ea-8b4a-b505ed2eb327.png)

I want to use symmetric encryption, change it into ciphertext

According to the configured seed, the secret key is generated

**Comment by zhuangchong** [comment]
+1

**Comment by yangyichao-mango** [comment]
+1

**Comment by CalvinKirs** [comment]
+1

**Comment by rockxsj** [comment]
+1
