### ISSUE TITLE
[Question] 1.3.1 api-server error ,session info is null

### ISSUE THREAD

**Issue by zhangmy163** [apache/incubator-dolphinscheduler#3225]
**Describe the question**
When accessing the page, dolphinscheduler-api-server.log prompts the error message as follows
```
[INFO] 2020-07-16 06:57:09.590 org.apache.dolphinscheduler.api.security.PasswordAuthenticator:[70] - session info is null 
[INFO] 2020-07-16 06:57:09.590 org.apache.dolphinscheduler.api.security.PasswordAuthenticator:[70] - session info is null 
[INFO] 2020-07-16 06:57:09.590 org.apache.dolphinscheduler.api.interceptor.LoginHandlerInterceptor:[67] - user does not exist
[INFO] 2020-07-16 06:57:09.591 org.apache.dolphinscheduler.api.interceptor.LoginHandlerInterceptor:[67] - user does not exist
```
Page loading

![image](https://user-images.githubusercontent.com/6898029/87637647-23909380-c775-11ea-9cfb-8ba1757c5f18.png)

**Which version of DolphinScheduler:**
 -[1.3.1]

I am not sure if the configuration file has errors

my application-api.properties 
```
# server.port=12345
server.port=12345

# session config
server.servlet.session.timeout=7200

server.servlet.context-path=/dolphinscheduler/

# file size limit for upload
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

#post content
server.jetty.max-http-post-size=5000000

spring.messages.encoding=UTF-8

#i18n classpath folder , file prefix messages， if have many files, use "," seperator
spring.messages.basename=i18n/messages

# Authentication types (supported types: PASSWORD)
security.authentication.type=PASSWORD
```

**Comment by yangyichao-mango** [comment]
Hi,

This error will produce when you visit a page without log-in. Please try to log in by username and password.
If you have any question or suggestion, please put forward~

**Comment by zhangmy163** [comment]
Does the front-end configuration point nginx to `apache-dolphinscheduler-incubating-1.3.1-dolphinscheduler-bin/ui` dir index.html?
I configured it this way, opening the page is loading

**Comment by ja3per** [comment]
I have similar issue. after deploy front with nginx. can't login with admin/dolphinscheduler123. and the log is 
```
[INFO] 2020-07-17 11:40:31.689 org.apache.dolphinscheduler.api.security.PasswordAuthenticator:[70] - session info is null
[INFO] 2020-07-17 11:40:31.690 org.apache.dolphinscheduler.api.interceptor.LoginHandlerInterceptor:[67] - user does not exist
```

following is the nginx.conf
` server {
        listen       8888;
        server_name  localhost;
        #charset koi8-r;
        #access_log /opt/dolphinscheduler/nginx/logs/host.access.log  main;
        
        location / {
            root   /opt/dolphinscheduler/dist;
            index  index.html index.html;
        }

        location /dolphinscheduler {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header        Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header x_real_ipP $remote_addr;
            proxy_set_header remote_addr $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_connect_timeout 4s;
            proxy_read_timeout 30s;
            proxy_send_timeout 12s;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        #error_page  404              /404.html;
        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }`

**Comment by zhangmy163** [comment]
I found the reason, because the front-end version of 1.3.1 has adjusted the path, basically all the jumps (index.html or the js it calls) have increased the path `/dolphinscheduler/ui`

following is my nginx.conf,Hope to help friends who encounter the same problem.

```
location / {
        return 301 /dolphinscheduler/ui/;
    }
    location /dolphinscheduler/ui/ {
        alias  /opt/DolphinScheduler/dolphinScheduler-ui/;      # ui path
        index  index.html;
    }
    location /dolphinscheduler{
        proxy_pass http://127.0.0.1:12345;            # api port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header x_real_ipP $remote_addr;
        proxy_set_header remote_addr $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
