### ISSUE TITLE
[package 最终是怎么把配置文件都打包到conf下面的?]

### ISSUE THREAD

**Issue by lizu18xz** [apache/incubator-dolphinscheduler#3227]
想了解一下最终是怎么把配置文件都打包到conf下面的?

**Comment by kevinsun2010** [comment]
dolphinscheduler-dist 模块下 POM.xml --> maven-assembly-plugin   负责打包，了解下。

**Comment by zhuangchong** [comment]
使用的是  maven-assembly-plugin 自定义规则打包，配置在incubator-dolphinscheduler/dolphinscheduler-dist/src/main/assembly/dolphinscheduler-binary.xml
