### ISSUE TITLE
日志跳转

### ISSUE THREAD

**Issue by shaobo99** [apache/incubator-dolphinscheduler#3228]
用了一段时间dolphinscheduler之后发现当工作流数量数上去了，如果在工作流实例中失败的数量多了之后很难在任务实例中找到相应的日志，建议在工作流实例中可以直接链接到任务实例

**Comment by yangyichao-mango** [comment]
Hi,
Please change the title and description to English. Thx a lot~
This is a good feature. We are planing to do this.

**Comment by dailidong** [comment]
good idea, anyone who want to implement it , please leave a message

BTW, English is needed

**Comment by yx91490** [comment]
> good idea, anyone who want to implement it , please leave a message
> 
> BTW, English is needed

I'm a newer to dolphinscheduler, I want to try it this weekend.

**Comment by dailidong** [comment]
> > good idea, anyone who want to implement it , please leave a message
> > BTW, English is needed
> 
> I'm a newer to dolphinscheduler, I want to try it this weekend.

glad to see this message, if you need help, please contact my wechat(510570367), when added, please tell my your github id,thx
