### ISSUE TITLE
[Improvement]接口文档

### ISSUE THREAD

**Issue by Anyzm** [apache/incubator-dolphinscheduler#3231]
请问有没有API对接文档？我们项目想从后台利用API对接接入jds，有没有完整的后台接入文档呢？

**Comment by yangyichao-mango** [comment]
HI,
You can get api doc from offical website.


http://106.75.43.194:8888/dolphinscheduler/doc.html?language=zh_CN&lang=zh

**Comment by kevinsun2010** [comment]
官网上面API有文档入口，有问题先看官方文档哈：
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.1/user_doc/quick-start.html
