### ISSUE TITLE
[Question] How to configure impala data source with Kerberos authentication on data source page

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3232]
**Describe the question**
How to configure impala data source with Kerberos authentication on data source page? At present, it is possible to configure hive data source with Kerberos authentication.

**Which version of DolphinScheduler:**
 -[1.3.1-release]

---
**描述问题**
数据源页面如何配置带kerberos认证的Impala数据源，目前配置带kerberos认证的hive数据源是可以的。

**版本**
 -[1.3.1-release]

**Comment by xingchun-chen** [comment]
version 1.3.2  has resolved
