### ISSUE TITLE
[Bug][DagHelper] Time complexity is O(N^N)

### ISSUE THREAD

**Issue by wangyanphp** [apache/incubator-dolphinscheduler#3236]
function  getFlowNodeListPost's  time complexity is O(N^N)

**Comment by CalvinKirs** [comment]
If you have a better solution, contributions are welcome,

**Comment by yangyichao-mango** [comment]
Hi,
This actually is not a bug, you can change the title to `[Improvement][api] DagHelper time complexity is O(N^N)`.

**Comment by dailidong** [comment]
PR #3249 solved this
