### ISSUE TITLE
[Bug][docker] the file requirements.yaml in helm mode has error flag

### ISSUE THREAD

**Issue by lookhua** [apache/incubator-dolphinscheduler#3237]
incubator-dolphinscheduler/docker/kubernetes/dolphinscheduler/requirements.yaml
line 25 , "  condition: redis.enabled" change to "  condition: zookeeper.enabled"

**Comment by AlleriaWindrunner** [comment]
hello, lookhua ! I want to resolve this bug, please assign it to me! thks!
