### ISSUE TITLE
[Bug][Resource Center] Can not create folder in docker with standalone mode

### ISSUE THREAD

**Issue by noirmxj** [apache/incubator-dolphinscheduler#3238]
Creating a folder in the Resource Center failed.

1. build docker images by default Dockerfile
2. run docker with args ALL
3. open resource center, and create a folder

**Which version of Dolphin Scheduler:**
 -[1.3.1]

**Additional context**
The error info in logs is :  NulPointer Error in createDirecortry(ResourceService.java:484)
It seems to be a HDFS error. but in DOC, the local fs is supported.

And then，I modify the common config file, change the storage.type from NONE to HDFS, but still failed.

i want to evaluate dolphinscheduler quickly, but it's not very easy -_-b
Please consider being able to quickly evaluate the software through docker.

**Comment by xingchun-chen** [comment]
Reference resources in the workflow, a null pointer is reported when the workflow is running
![image](https://user-images.githubusercontent.com/55787491/93585734-cfef3000-f9d9-11ea-9eff-fb8ad2a3cc95.png)
