### ISSUE TITLE
[Feature][alert plugin] Upgrade tool for upgrade to alert plugin version from the old version

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3248]
A sub task of https://github.com/apache/incubator-dolphinscheduler/issues/3049

We know that before upgrade to the alert plugin version, user use alert by config email, wehcat, dingtalk throuth the alert.properties file. 

After upgrading to the alert plugin version, users can configure email, wehcat, dingtalk information by creating an alert group on the page and then creating an instance of the alert plugin. 

So, should we provide a tool to automatically scan the user's alert configuration in the alert.properties file when the user upgrade to the alert plugin version, and then automatically create the default alert group and alert plugin instance and associate the alert group with the workflow define ？

**Comment by yangyichao-mango** [comment]
+1

**Comment by zhangchunyang1024** [comment]
+1

**Comment by felix-thinkingdata** [comment]
Let me see ，haha

**Comment by gaojun2048** [comment]
This issue is delete. I will close it.
