### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by q411914616** [apache/incubator-dolphinscheduler#3250]
1、增加类似kettle转换的表对表,文件对表，表对文件之间的数据ETL
2、资源中心不应该只针对于数据源，也应该针对于服务器，例如linux服务的登录配置信息也可以保存在其中，后面使用的时候直接调用。

**Comment by q411914616** [comment]
配置文件中的信息过多，有没有考虑放到数据库中进行集中配置管理

**Comment by dailidong** [comment]
> 配置文件中的信息过多，有没有考虑放到数据库中进行集中配置管理

how to make the cofiguration more simple？do you have some ideas?  I always want to make config easy.
btw, English is needed

**Comment by gabrywu** [comment]
@q411914616 could you give some more use case to explain your two suggestions?
