### ISSUE TITLE
[Question] Whether SqlTask should send notifications or not through the alert server

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3251]
This is a sub task of https://github.com/apache/incubator-dolphinscheduler/issues/3049

In this feature, we will put the function of sending email into the alert email plugin. But I found that SqlTask directly calls the code for sending emails. As a result, after the email function was moved to the dolphinscheduler-alert-email module, SqlTask could no longer call the email code. 

How should we deal with this situation? 

Should SqlTask send emails directly instead of through alert services? If SqlTask should send notifications through the alert server, then the alert server should provide something for SqlTask to call.

If you think that SqlTask should send notifications through the alert service, then I have a few ideas. You can discuss which is more appropriate:

1. Alert server provides grpc interface or http interface, SqlTask calls these interfaces to send notifications.

2. SqlTask directly inserts an alert data into the table t_ds_alert, and then the alert server will automatically send a notification asynchronously.

Do you have any suggestions?

**Comment by yangyichao-mango** [comment]
2

**Comment by gabrywu** [comment]
I think the first solution is better
If SqlTask just inserts an alert data to table, what's the status of this task should be? succeed or running?
After all, sending email is the main logic of SqlTask, right ? if email sent by alert server, how to guarantee emails send successfully ?

**Comment by zhangchunyang1024** [comment]
I also think the first solution is better 
In this way, tasks can be synchronized to know whether the message was sent successfully or not, and can be fault-tolerant based on the results

**Comment by gaojun2048** [comment]
> I also think the first solution is better
> In this way, tasks can be synchronized to know whether the message was sent successfully or not, and can be fault-tolerant based on the results

Can you send a email to the dev email list ? If there is no objection . You can do it.

**Comment by gaojun2048** [comment]
In the mailing list, we reached an agreement that sqltask uses alert api to send notifications
