### ISSUE TITLE
[Feature][build] Update maven build, the alert plugins need put in plugins dir when install

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3252]
This is a sub task of https://github.com/apache/incubator-dolphinscheduler/issues/3049

Update maven build, put the alert plugins in the ${install_dir}/lib/plugin/alert/${plugin_module_name} directory (assembly build and rpm build).

**Comment by zhangchunyang1024** [comment]
Let me implement this

**Comment by zhangchunyang1024** [comment]
Sorry, I'm busy recently. I don't have time to do this task. I hope other partners can continue

**Comment by CalvinKirs** [comment]
close by #4259
