### ISSUE TITLE
admin账号修改报错的问题，目前查询是由于手机的信息影响的

### ISSUE THREAD

**Issue by wjf989** [apache/incubator-dolphinscheduler#3256]
> 
> 
> 我安装1.2.1也不能修改管理员密码，提示request parameter xx is not valid

我这边安装的版本是1.3.1，在进行修改管理原密码的时候，也是提示跟你同样的问题；后面通过F12，查询相应信息，发现这个错误是‘手机’这个信息产生影响的，你必须将该‘手机’参数修改为正确的格式，否则无法正常修改密码，如
![图片](https://user-images.githubusercontent.com/49484750/88007828-62da2e00-cb41-11ea-8804-9ebaacc690e2.png)

_Originally posted by @wjf989 in https://github.com/apache/incubator-dolphinscheduler/issues/219#issuecomment-661597078_

建议：将“手机”的参数变量，同其他地方的变量信息进行脱钩；

**Comment by yangyichao-mango** [comment]
I reproduced this error in dev branch, actually it is the `state` info error, not the phone error.
![image](https://user-images.githubusercontent.com/29545877/88137676-a3f44000-cc1e-11ea-9e13-79f210d21ec2.png)

**Comment by yangyichao-mango** [comment]
Anyone who want to implement it , please leave a message.

BTW, English issue title is needed~

**Comment by wuchunfu** [comment]
I'll fix it.

**Comment by xingchun-chen** [comment]
The upgrade script does not remove the admin mobile phone number xx, which will cause the version below 1.3.1 to be upgraded to 1.3.2, and the admin user will still be reported that the parameters are invalid.
![image](https://user-images.githubusercontent.com/55787491/89511879-09425680-d805-11ea-9f8a-9d5c3c4d5866.png)

**Comment by lenboo** [comment]
@wjf989  please change the title and content to english. thx.
