### ISSUE TITLE
[Bug] [Server]when the worker and master are configured with different data.basedir.path, it will cause the task to fail

### ISSUE THREAD

**Issue by wa-ooo** [apache/incubator-dolphinscheduler#3257]
**Describe the bug**
If the basedir of the master configuration is /data/master; The basedir configured by Woker is /data/worker;Shelltask will report NoSuchFileException when it runs

**Screenshots**
![image](https://user-images.githubusercontent.com/17908119/88023485-b1002900-cb63-11ea-98d1-3484bdd92cf4.png)

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]

**Comment by xingchun-chen** [comment]
master need to be configured the same

**Comment by wa-ooo** [comment]
> master need to be configured the same

This requirement is unreasonable. Master and worker should be fully independent to facilitate the expansion of worker nodes

**Comment by chengshiwen** [comment]
Close this issue, since it has been resolved in 1.3.4 and `data.basedir.path` in master will no longer be used
