### ISSUE TITLE
[Bug][dolphinscheduler-common]  When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3262]
When you request the URL through applicationID to get the application status, you cannot get it if Kerberos authentication is enabled
eg:
![image](https://user-images.githubusercontent.com/59079269/88059613-b0818580-cb97-11ea-892b-3c3f94c32652.png)

yarn.application.status.address=http://ark1:8088/ws/v1/cluster/apps/%s

**Comment by felix-thinkingdata** [comment]
this is my test log
![image](https://user-images.githubusercontent.com/59079269/88068561-f1cb6280-cba2-11ea-88bf-ead87d8b9c3a.png)

**Comment by break60** [comment]
3264 this pr, did you fix your problem?

**Comment by felix-thinkingdata** [comment]
> 3264 this pr, did you fix your problem?

 3264 Have to repair，I've just made some changes
