### ISSUE TITLE
[Bug][User Login] Lower version chrome can't access login page 

### ISSUE THREAD

**Issue by whitelowrie** [apache/incubator-dolphinscheduler#3266]
If you access dophin index use chrome which version is less than 40.x，you will can't access the log page, always loading!
![image](https://user-images.githubusercontent.com/13913085/88068063-4a4e3000-cba2-11ea-8f08-43a99518ef4f.png)
througth the linux  background log，you can get the message :"user does not exist" and "session info is null"
![image](https://user-images.githubusercontent.com/13913085/88068265-8e413500-cba2-11ea-82d8-f6f19ddd9a6d.png)

for solving the problem，you can use upgrade the chrome to 70.x , or use firefox. but you can't use IE，becuase It still have some problem.

so think if dolphinscheduler check the browser version，and tip user，It will  save lots of time to debug!

**Comment by yangyichao-mango** [comment]
Hi,
Which DolphinScheduler version?
And if the back-end server has the log about user, it maybe not the error chrome version caused.
