### ISSUE TITLE
Can the processDefinition id and schedule id be returned after the process instance is successfully created

### ISSUE THREAD

**Issue by shenqicheng100** [apache/incubator-dolphinscheduler#3268]
Can the processDefinition id and schedule id be returned after the process instance is successfully created

**Comment by shenqicheng100** [comment]
I want to create a process instance through api, but after the creation is completed, I need to query all of them before it can be dynamically launched and run.

**Comment by yangyichao-mango** [comment]
> I want to create a process instance through api, but after the creation is completed, I need to query all of them before it can be dynamically launched and run.

Hi,
Do you mean you want the `process instance` id, not the `process definition` id?

**Comment by shenqicheng100** [comment]
> > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> 
> 嗨，
> 您是说要`process instance`身份证，而不是`process definition`身份证吗？

是 process definition

**Comment by shenqicheng100** [comment]
> > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> 
> 嗨，
> 您是说要`process instance`身份证，而不是`process definition`身份证吗？

Sorry, I typed the wrong word

**Comment by yangyichao-mango** [comment]
> > > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> > 
> > 
> > 嗨，
> > 您是说要`process instance`身份证，而不是`process definition`身份证吗？
> 
> Sorry, I typed the wrong word

In 1.3.x and 1.2.x version, the `process definition` id will be returned when you create a process definition.
![image](https://user-images.githubusercontent.com/29545877/88137051-4ad7dc80-cc1d-11ea-8bd6-605f796166d3.png)

**Comment by shenqicheng100** [comment]
> > > > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> > > 
> > > 
> > > 嗨，
> > > 您是说要`process instance`身份证，而不是`process definition`身份证吗？
> > 
> > 
> > Sorry, I typed the wrong word
> 
> In 1.3.x and 1.2.x version, the `process definition` id will be returned when you create a process definition.
> ![image](https://user-images.githubusercontent.com/29545877/88137051-4ad7dc80-cc1d-11ea-8bd6-605f796166d3.png)

Can it also return schedule id when creating schedule? Thank you

**Comment by yangyichao-mango** [comment]
> > > > > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> > > > 
> > > > 
> > > > 嗨，
> > > > 您是说要`process instance`身份证，而不是`process definition`身份证吗？
> > > 
> > > 
> > > Sorry, I typed the wrong word
> > 
> > 
> > In 1.3.x and 1.2.x version, the `process definition` id will be returned when you create a process definition.
> > ![image](https://user-images.githubusercontent.com/29545877/88137051-4ad7dc80-cc1d-11ea-8bd6-605f796166d3.png)
> 
> Can it also return schedule id when creating schedule?
> This http://192.168.1.194:8888/dolphinscheduler/projects/bim-qd/schedule/create api
> Thank you

This http://192.168.1.194:8888/dolphinscheduler/projects/bim-qd/schedule/create api will return all the schedule info, include the `process definition` id and `schedule` id.

**Comment by shenqicheng100** [comment]
> Thank you



> > > > > > 我想通过api创建流程实例，但是创建完成后，我需要先查询所有实例，然后才能动态启动和运行它。
> > > > > 
> > > > > 
> > > > > 嗨，
> > > > > 您是说要`process instance`身份证，而不是`process definition`身份证吗？
> > > > 
> > > > 
> > > > Sorry, I typed the wrong word
> > > 
> > > 
> > > In 1.3.x and 1.2.x version, the `process definition` id will be returned when you create a process definition.
> > > ![image](https://user-images.githubusercontent.com/29545877/88137051-4ad7dc80-cc1d-11ea-8bd6-605f796166d3.png)
> > 
> > 
> > Can it also return schedule id when creating schedule?
> > This http://192.168.1.194:8888/dolphinscheduler/projects/bim-qd/schedule/create api
> > Thank you
> 
> This http://192.168.1.194:8888/dolphinscheduler/projects/bim-qd/schedule/create api will return all the schedule info, include the `process definition` id and `schedule` id.

Thank you

**Comment by yangyichao-mango** [comment]
Hi,
In 1.3.x, the process definition id will be returned when you create a process definition.
In 1.2.x version, because the error using of utils, it will not return the process definition id.

**Comment by shenqicheng100** [comment]
> 嗨，
> 在1.3.x中，当您创建流程定义时，将返回流程定义ID。
> 在1.2.x版本中，由于错误使用utils，因此不会返回进程定义ID。

Ok

**Comment by ngsin** [comment]
> > I want to create a process instance through api, but after the creation is completed, I need to query all of them before it can be dynamically launched and run.
> 
> Hi, Do you mean you want the `process instance` id, not the `process definition` id?

so how can i get the `process instance` id after start a new process instance? 
/dolphinscheduler/projects/{projectCode}/executors/start-process-instance
i use this api to create, but it return just look like  
`{"code":0,"msg":"success","data":null,"failed":false,"success":true}`
@yangyichao-mango
