### ISSUE TITLE
[Question] 就是cluster模式提交Kerberos无法认证，client模式就可以，

### ISSUE THREAD

**Issue by zengqinchris** [apache/incubator-dolphinscheduler#3287]
https://github.com/apache/incubator-dolphinscheduler/issues/3271，
大佬们帮忙看看这个问题怎么解决，没有人搭理
搞了好久没有解决这个问题，是不是cluster模式有问题，如果携带了 配置文件

**Comment by zhuangchong** [comment]
如果cluster不可以，client可以，那应该是别的节点不读到这个文件，把文件放到hdfs上那，启动指定hdfs路径

**Comment by zengqinchris** [comment]
> 如果cluster不可以，client可以，那应该是别的节点读不到这个文件，把文件放到hdfs上那，启动指定hdfs路径

老铁，不对吧，我的配置文件是在资源文件里上传的，难道ds不会分发配置文件吗，还是ds要分布式部署才可以分发到不同的节点上？
