### ISSUE TITLE
[Improvement][JUNIT TEST] Improvement UT  OutOfMemory GC overhead limit 

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3288]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
During the process of pr submission, the UT section often has the following problems.

 OutOfMemory GC overhead limit 

![image](https://user-images.githubusercontent.com/59079269/88269251-3facab80-cd06-11ea-85dc-2f94a510652f.png)
![image](https://user-images.githubusercontent.com/59079269/88269326-679c0f00-cd06-11ea-9a47-f41f1641d963.png)

[org.apache.dolphinscheduler.server.master.DependentTaskTest.txt](https://github.com/apache/incubator-dolphinscheduler/files/4964829/org.apache.dolphinscheduler.server.master.DependentTaskTest.txt)
[org.apache.dolphinscheduler.server.master.MasterExecThreadTest.txt](https://github.com/apache/incubator-dolphinscheduler/files/4964830/org.apache.dolphinscheduler.server.master.MasterExecThreadTest.txt)
[org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryTest.txt](https://github.com/apache/incubator-dolphinscheduler/files/4964831/org.apache.dolphinscheduler.server.worker.registry.WorkerRegistryTest.txt)
[org.apache.dolphinscheduler.server.worker.task.sqoop.SqoopTaskTest.txt](https://github.com/apache/incubator-dolphinscheduler/files/4964832/org.apache.dolphinscheduler.server.worker.task.sqoop.SqoopTaskTest.txt)

**What are the current deficiencies and the benefits of improvement**

- Take a look at these test classes. What causes the problems

**Which version of DolphinScheduler:**
 -[dev]

**Comment by yangyichao-mango** [comment]
+1,
Welcome to optimize the ut.
