### ISSUE TITLE
datasource already close

### ISSUE THREAD

**Issue by nsnmlgba** [apache/incubator-dolphinscheduler#3294]
i  download the code and package with  idea
 version1.2.0
if start master-server in idea  is no problem
 but when i run it in linux  centos7   the exception is  datasource already closed
when start in linux the first  query with commandMapper from db no problem  
 but from the second query  the exception is datasource aready close

**Comment by gabrywu** [comment]
@nsnmlgba Could you paste some logs here?

**Comment by nsnmlgba** [comment]
thanks , I've solved it,   becase i user @Vlaue  in module api-server SessionService.class,      There are method used annotations   @Transactional  in this class.    this class will proxy by spring AOP.   so when i start api-server is no problem ,  There was a problem when I started Master-server.   
感谢，我已经解决了，因为我在api-server 中SessionService.class 使用了@value注解  但是这个类有的方法用了@Transacional 注解   导致这个类被AOP代理了， 当我启动api-server的时候是没有问题的，但是启动master-server的时候就出现了这个问题。
