### ISSUE TITLE
When I create a scheduler directly through the api, a NullPointerException will appear when the processInstancePriority field is not passed. he is @RequestParam(value = "processInstancePriority", required = false)

### ISSUE THREAD

**Issue by shenqicheng100** [apache/incubator-dolphinscheduler#3295]
![image](https://user-images.githubusercontent.com/34977303/88355113-e1c7a480-cd95-11ea-8cfa-9d34d866cb08.png)

error line

![image](https://user-images.githubusercontent.com/34977303/88355156-10457f80-cd96-11ea-8e3f-31170d6fdff6.png)

Do you need to modify it to @RequestParam(value = "processInstancePriority", required = true)

**Comment by gabrywu** [comment]
@shenqicheng100 which versin?

**Comment by shenqicheng100** [comment]
> @ shenqicheng100哪个版本？

1.3.2-release

**Comment by yangyichao-mango** [comment]
> > @ shenqicheng100哪个版本？
> 
> 1.3.2-release

Hi, @shenqicheng100 
I reproduce this error in 1.3.1-release.[1]
If you are interested in fixing this bug, please leave a message.

[1]
![image](https://user-images.githubusercontent.com/29545877/88447230-6fbd9100-ce63-11ea-844e-11c2a2902f3c.png)

**Comment by shenqicheng100** [comment]
> > > @ shenqicheng100哪个版本？
> > 
> > 
> > 1.3.2发布
> 
> 嗨，@ shenqicheng100，
> 我在1.3.1版本中重现此错误。[1]
> 如果您有兴趣修复此错误，请留言。
> 
> [1]
> ![图片](https://user-images.githubusercontent.com/29545877/88447230-6fbd9100-ce63-11ea-844e-11c2a2902f3c.png)

Sorry for the late reply, the company has a lot of things these days.
Code submitted !!!
