### ISSUE TITLE
[Bug][k8s]when recreate or upgrade helm release, the host ip changed

### ISSUE THREAD

**Issue by rockxsj** [apache/incubator-dolphinscheduler#3298]
**Describe the bug**
When DS was deployed to k8s by helm, if you upgrade the release or recreate the release, the ip of worker server and other server will be changed, so when you try to query the log of history task, you will get empty log.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. deploy the cluster use helm
2. recreate the deployed release or just upgrade
3. query a task which runned before upgrade/recreate
4. no log will show

**Expected behavior**
log should be show

**Screenshots**

![image](https://user-images.githubusercontent.com/3021207/88361996-915c4100-cdad-11ea-8e45-1c46b69109ce.png)

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]

**Additional context**

**Requirement or improvement**

**Comment by luohy15** [comment]
There are 2 solutions to this problem:

1. At the end of the task, the log is sent to distributed storage such as S3/HDFS and stored according to taskInstance id. A new LoggerService is added to obtain logs of completed tasks from distributed storage.
2. Added worker.id configuration in worker.properties, and added workerId field in taskInstance. When getting the log, get the corresponding worker according to the workerId and then get the log.

Which solution is better?

---

这个问题有2种解决方案：

1. 任务结束时将日志发送至S3/HDFS等分布式存储，按taskInstance id存储。新增一个LoggerService实现从分布式存储获取已完成任务的日志。
2. worker.properties增加worker.id配置，taskInstance新增workerId字段。获取日志时根据workerId得到对应的worker再获取日志。

哪一种方案更好？
