### ISSUE TITLE
[Feature][del_zk] Use zookeeper own delete method.

### ISSUE THREAD

**Issue by feloxx** [apache/incubator-dolphinscheduler#3309]
**Describe the feature**

Use zookeeper own delete method to replace the existing method.

**Is your feature request related to a problem? Please describe.**

Do not consider py, do not consider using java, it is too cumbersome.

**Describe the solution you'd like**

zookeeper comes with it, we just call it in the shell.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by wuchunfu** [comment]
+1
