### ISSUE TITLE
[Feature][alert] Improvement of the plugin-able alert group function

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3311]
**Describe the feature**
Improvement of the alert group function to support plugin-able alert group, in the alert group, an alert instance can be created based on the existing alert plug-in.

A sub task of #3049

**Comment by yangyichao-mango** [comment]
I'm working on it.

**Comment by gaojun2048** [comment]
Is this pr https://github.com/apache/incubator-dolphinscheduler/pull/3666 solve your problem?

**Comment by CalvinKirs** [comment]
close by #3666
