### ISSUE TITLE
[Question]   Can the workflow exported from dolphinscheduler 1.2 be imported into dolphinscheduler 1.3

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3319]
我从1.2.0版本导出的json文件，导入到1.3.1的ds里报错
I exported the workflow JSON file from DS 1.2.0 , import to DS 1.3.1 but occurred an error.

从api日志看不出具体报错的原因
From the API log, I can not know the reason for the error.
![image](https://user-images.githubusercontent.com/57620584/88527291-a47e4380-d02f-11ea-9964-f1fdf2a9f759.png)
![image](https://user-images.githubusercontent.com/57620584/88527368-be1f8b00-d02f-11ea-9283-ba6688f745e5.png)
![image](https://user-images.githubusercontent.com/57620584/88527411-cd063d80-d02f-11ea-9828-2af491011395.png)

**Comment by xingchun-chen** [comment]
1.3.1 does not support importing the workflow of version 1.2.0, you can upgrade version 1.2.0 to 1.3.1
