### ISSUE TITLE
Improve test cases(完善测试用例)

### ISSUE THREAD

**Issue by rongyingjie** [apache/incubator-dolphinscheduler#332]
1, escheduler-server test case, query from the database and then execute, I hope to be able to construct the job, the task is reflected by the use case
2, it is recommended to integrate mockito and other test frameworks, write use cases, design scenarios, verify that the execution process is correct, and ensure that each branch can be covered
3. Improve related design documents, architecture design, flow charts, deployment maps, etc.
4. The above three parts are the basis for understanding the source code, and also the core thing that can solve the online problem after going online;

---
1、escheduler-server 测试用例，从数据库查询然后执行，希望能把如何构造job,task通过用例体现出来
2、建议整合 mockito 等测试框架，编写用例，设计场景，验证执行流程是否正确，同时确保每个分支都能覆盖到
3、完善相关的设计文档，架构设计，流程图，部署图等
4、上述三个部分的，是看懂源码的基础，同时也是上线后能解决线上问题的，最核心的东西；

**Comment by dailidong** [comment]
Great advice！thx！
We will gradually improve the test cases and welcome to participate. could you submit a pull request as test case demo?

**Comment by dailidong** [comment]
CI/CD,  is implementing test cases #1465
