### ISSUE TITLE
有没有直接上传一个文件夹的功能,因为脚本比较多,一个个文件上传太多了

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3320]

**Comment by yangyichao-mango** [comment]
Hi~,
The same with #3092 , if anyone interested in implementing this feature, welcome leave a message.

Tag: Could be closed, @yangyichao-mango

**Comment by breeze0812** [comment]
I  have the same problem

**Comment by nerverbe** [comment]
你可以上传一个zip包，然后在dolphinscheduler加一个shell节点，unzip和cd一下。
每个任务执行前，dolphinscheduler都会拷贝引入的资源到tmp目录下的一个随机目录，并且为这个任务重刷环境变量，不用担心资源冲突的问题

**Comment by nerverbe** [comment]
如果你用spark on yarn，你把资源依赖放到hdfs上就行，dolphinscheduler上写spark-commit或者调用launch脚本
