### ISSUE TITLE
[Question] Fix the bugs analyzed by sonar

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-dolphinscheduler#3321]
At present, our project has some historical issues. Some members who submitted the code will encounter these issues. This makes their submissions always not smooth. Therefore, I fixed some of them, and I will fix the remaining part in the near future. carry out. In addition, there are some front-ends. Interested front-ends can be claimed below.

**Comment by CalvinKirs** [comment]
The specific error report can be viewed here https://sonarcloud.io/dashboard?id=apache-dolphinscheduler.
I will complete the related bugs on the server in the near future.

**Comment by CalvinKirs** [comment]
If you are interested in fixing some of the front-end bugs, please claim them below

**Comment by yangyichao-mango** [comment]
Hi~
Very good job,

We can also create a new ISSUE to repair the `code smile`, `VULNERABILITY` of sonar. #3325
