### ISSUE TITLE
如何调用shell脚本文件,phoenix脚本文件,presto脚本文件

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3326]
操作方式:
1.将需要操作的文件上传到资源文件中心
2.创建项目,进入项目
3.工作流定义中拖拽shell图标到工作流中,点击开始编辑,资源中选择需要操作的脚本
问题:
资源中选择了需要操作的文件,脚本中不能为空,是需要填写怎么操作这个文件的命令吗?
如果我的资源中上传的文件为aaa.sh,那我脚本中应该如何填写,才能正确调用aaa.sh的shell脚本成功运行呢.
同样想问,dolphinscheduler支持操作phoenix文件和presto文件吗

**Comment by lenboo** [comment]
please change the title and content to english, thx.
you can use 'sh xx.sh' in the shell task content if you upload the xx.sh in the resource and select it in the shell task.
