### ISSUE TITLE
[Bug][ui] Success add an empty configured node

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3336]
**Describe the bug**
When I create an flink node, it can not be successed add when I do not configure it right, but when I add another node(python node), it will cover the flink node, but it successfully be left in canvas and can be saved as a new process definition.

**To Reproduce**
1. Add an flink node and do not configure the flink node. Screenshots [1]
2. Add an python node. Screenshots [2]
3. Cancel configure python node and the configuration drawler will disappear. Screenshots [3]
4. But the flink node will be left in the canvas

**Expected behavior**
The flink node will be left in the canvas

**Screenshots**
[1] ![image](https://user-images.githubusercontent.com/29545877/88680611-46328d00-d123-11ea-8b4d-a643f8f88467.png)
[2] ![image](https://user-images.githubusercontent.com/29545877/88680424-12effe00-d123-11ea-98e7-fcc59e2ab0ba.png)
[3] ![image](https://user-images.githubusercontent.com/29545877/88680547-3024cc80-d123-11ea-9711-81270d817c1c.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by break60** [comment]
This should not be considered a bug. You added a new node and did not do any operation. Although it is displayed on the canvas, the node is not saved when saving.
