### ISSUE TITLE
执行任务 ssh Host key verification failed   出个大佬远程解决一哈。compensation

### ISSUE THREAD

**Issue by One-fengshuai** [apache/incubator-dolphinscheduler#3339]
![image](https://user-images.githubusercontent.com/58324759/88748532-d56f8d00-d183-11ea-81a8-de59a524b482.png)
如果用ds部署用户创建一个租户 就会一直在执行

**Comment by yangyichao-mango** [comment]
This is ssh error, not DolphinScheduler. You can google about this error and fix it.

Tag: Could be closed. @yangyichao-mango
