### ISSUE TITLE
dolphinscheduler 1.3.1版本部署 登录不上

### ISSUE THREAD

**Issue by beepupa** [apache/incubator-dolphinscheduler#3340]
我按照官方文档，部署出来，在登录页面输入用户名密码点击登录，闪了一下，又出现了登录页面，有没有遇到过得，该怎么解决呢

**Comment by zhuangchong** [comment]
在浏览器控制台看一下接口返回信息和API模块日志。应该是API模块接口没有连上

**Comment by lenboo** [comment]
please change the title and content to english, then reopen it if any question.
