### ISSUE TITLE
怎么创建租户呢

### ISSUE THREAD

**Issue by beepupa** [apache/incubator-dolphinscheduler#3342]
租户编码该怎么填写，为什么我创建不了租户呢
![image](https://user-images.githubusercontent.com/36186038/88761916-a9afcf80-d1a2-11ea-825e-e43cc8786c9a.png)

**Comment by zhuangchong** [comment]
租户编码是linux os 用户，不能创建看一下api模块日志

**Comment by hsupu** [comment]
"tenant" is a real linux user.

you can find detailed error in api-server log (in the logs folder).
