### ISSUE TITLE
工作流定义中创建工作流的时候固定编号

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3343]
工作流定义中目前来看是根据创建时间,是否设置定时,定时是否上线,动态排序的.这样有时候设置完一保存就更换了位置,感觉不是很方便
希望可以改成创建或者导入工作流的时候就按编号固定了位置,无论后续做如何操作都不更改

**Comment by yangyichao-mango** [comment]
The same with #3170 .

Tag: could be closed. @yangyichao-mango

**Comment by lenboo** [comment]
thx for your contribution.
