### ISSUE TITLE
我在部署单机版ds执行install.sh的时候，报错操作系统unknown

### ISSUE THREAD

**Issue by xiangyu67373** [apache/incubator-dolphinscheduler#3345]
我在部署单机版ds执行install.sh的时候，报错操作系统unknown。
install.sh: 24: install.sh: [[: not found
install.sh: 27: install.sh: [[: not found
install.sh: 30: install.sh: [[: not found
install.sh: 34: install.sh: [[: not found
install.sh: 38: install.sh: [[: not found
install.sh: 41: install.sh: [[: not found
Operating system unknown, please tell us(submit issue) for better service

**Comment by xiangyu67373** [comment]
1.3.1
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dailidong"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 下午5:08
收件人: "apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;; 
抄送: "李家心"<752242046@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/incubator-dolphinscheduler] 我在部署单机版ds执行install.sh的时候，报错操作系统unknown (#3345)





 
which version？

**Comment by dailidong** [comment]
there is no [[ in line 24 .  
![image](https://user-images.githubusercontent.com/15833811/88789310-2e154900-d1c9-11ea-9571-f937989c06f2.png)

you can download 1.3.1 version from here: https://www.apache.org/dyn/closer.cgi/incubator/dolphinscheduler/1.3.1/apache-dolphinscheduler-incubating-1.3.1-dolphinscheduler-bin.tar.gz

**Comment by CalvinKirs** [comment]
When you run echo $OSTYPE on the command line, what is its output?

**Comment by xiangyu67373** [comment]
linux-gnu，ubuntu16.04------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CalvinKirs&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月29日(星期三) 晚上6:30
收件人:&nbsp;&quot;apache/incubator-dolphinscheduler&quot;<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;&quot;李小八&quot;<752242046@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 我在部署单机版ds执行install.sh的时候，报错操作系统unknown (#3345)

**Comment by CalvinKirs** [comment]
@dailidong 
According to user feedback, the download is the official package, and the system is determined to be no problem, but the strange thing is that it outputs "Operating system unknown, please tell us(submit issue) for better service" but does not output Welcome to the dolphinscheduler front-end deployment script, which is currently only supported by front-end deployment scripts: CentOS and Ubuntu
I will continue to follow up on this issue

**Comment by CalvinKirs** [comment]
When the user operating system was switched to ubuntu18.04, this problem was solved. I will continue to follow up and find time to see if this problem can recur.

**Comment by hsupu** [comment]
you got a "[[: not found", for this case, you should use `bash` instead of `dash` first to make the script work normally.
