### ISSUE TITLE
[Improvement][Process definition] process_definition_json contains definitionList，but this definitionList is not use

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/incubator-dolphinscheduler#3351]
I found that the 1.3.x version of DEPENDENT is configured with a definitionlist, which contains the IDS and names of all process. In the DEPENDENT, a dependency contains a definitionlist. When you have many workflows, the generated JSON will be very large. When this JSON is in use, but this field is not used, I suggest that this field be removed from this JSON。
![image](https://user-images.githubusercontent.com/42576980/88814939-4eef9580-d1ed-11ea-9537-92dcc74f7be0.png)
![image](https://user-images.githubusercontent.com/42576980/88814980-5c0c8480-d1ed-11ea-84cc-75dd1fc324e4.png)

**Comment by dailidong** [comment]
@lenboo ， please check

**Comment by lenboo** [comment]
@JinyLeeChina  you are right, i think this is a cache in the web site, and it need not to store in the process definiton.
