### ISSUE TITLE
Modify the application.properties What service do I need to restart to make it work

### ISSUE THREAD

**Issue by Jops-data** [apache/incubator-dolphinscheduler#3353]
**Describe the question**
I have created a new workflow, and I have been waiting for the state of the thread when it is executed. I now put the configuration file in application.properties The maximum number of master and worker threads is increased. What services do I need to restart for this configuration to take effect. What will happen if you turn it too high.

**Which version of DolphinScheduler:**
1.2.1

**Additional context**
The previous configuration was:

master.exec.threads=100

worker.exec.threads=100

The modified configuration is as follows:

master.exec.threads=150

worker.exec.threads=150

Other configurations have not been modified. Will this have other effects

**Requirement or improvement**
I hope someone can tell me what service to restart to make the modified configuration take effect, and then tell me about the impact of the reduction meeting

**Comment by zhuangchong** [comment]
Look inside the source code

1. master.exec.threads Configuration is called in MasterSchedulerService class.

2. worker.exec.threads Configuration is called in TaskExecuteProcessor class.

Both master and worker servers need to be restarted to take effect
---
看源码里面
1.master.exec.threads 配置在MasterSchedulerService类中调用
2.worker.exec.threads 配置在TaskExecuteProcessor类中调用

Master 和Worker server 都需要重启才能生效

**Comment by Jops-data** [comment]
That's OK. Thank you very much!
