### ISSUE TITLE
资源的使用

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3354]
想问下"资源"这个功能是怎么用的呢
比如我使用的是shell,脚本中编写的是一个spark2-submit的语句,这时候我需要调用一个jar包,我把jar包放在资源中心中,但是我还是要在spark2-submit语句中指定全路径,那这个资源应该怎么用呢.

**Comment by lenboo** [comment]
please change the title and content to english, thx.
about this question, i suggest you to read the documents in the ds website.(https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/system-manual.html)
