### ISSUE TITLE
shell、sql运行问题

### ISSUE THREAD

**Issue by 673981652** [apache/incubator-dolphinscheduler#3360]
调度一个错误的sql或shell，返回却是成功

**Comment by hsupu** [comment]
any detailed information? version? DAG?

**Comment by 673981652** [comment]
![image](https://user-images.githubusercontent.com/40028141/88998882-9e38e180-d325-11ea-81f5-3bb2ae888c09.png)
这个sql应该是会执行失败 但是调用却返回成功了
![image](https://user-images.githubusercontent.com/40028141/88998965-d2140700-d325-11ea-8fa7-5e3f10a5985f.png)
版本是1.2.0

**Comment by 673981652** [comment]
![1981596168593_ pic_hd](https://user-images.githubusercontent.com/40028141/88999316-c07f2f00-d326-11ea-9fb0-0349e73c30c1.jpg)
这个sql应该是执行失败的，但是调用却返回成功了
![image](https://user-images.githubusercontent.com/40028141/88999370-f6bcae80-d326-11ea-915f-ebe4bf1c8330.png)

**Comment by yangyichao-mango** [comment]
> ![1981596168593_ pic_hd](https://user-images.githubusercontent.com/40028141/88999436-25d32000-d327-11ea-9848-a4fb70215b9e.jpg)
> 
> 
> 
> 这个sql应该是执行失败的，但是调用却返回成功了
> 
> ![1991596168685_ pic_hd](https://user-images.githubusercontent.com/40028141/88999471-4602df00-d327-11ea-81ca-dcc11cbab89f.jpg)
> 
> 

Hi,
This is process deifinition， just for creating an process definition，not to run an process instance，you can refer to ds official website to find the lessones about how to use ds.

Tag： could be closed. @yangyichao-mango
