### ISSUE TITLE
dolphin scheduler-1.3.1，delete the task instance and apI-Server handles explode

### ISSUE THREAD

**Issue by liangpingliu** [apache/incubator-dolphinscheduler#3363]
dolphin scheduler-1.3.1版本存在问题：当手动批量或者api调用方式批量删除任务实例时，会出现api-server句柄暴增且不close问题。就算单个删除，api-server服务句柄也会增加。

**Comment by yangyichao-mango** [comment]
Please describe more detail about it to to help locate the bug.Thx a lot~

**Comment by dream009** [comment]
直接的报错是api server log日志报错：too many files，页面上无法手动删除任务实例。

**Comment by dailidong** [comment]
please use `lsof -p {api server pid} | wc -l ` count the open files number for Api Server

**Comment by dream009** [comment]
> please use `lsof -p {api server pid} | wc -l ` count the open files number for Api Server

是通过该命令进行验证的，每批量删除任务实例，该值都会增加不少，并且永不减少。并且让其他用户验证了，一样存在该情况。

**Comment by lenboo** [comment]
please change the title and content to english, thx.

**Comment by xingchun-chen** [comment]
The issue is the same as #3618

**Comment by dailidong** [comment]
Duplicate of #3618
