### ISSUE TITLE
After update the version from 1.2.0 to 1.3.1,running the spark task fail because the can't find the jar

### ISSUE THREAD

**Issue by wang87612** [apache/incubator-dolphinscheduler#3364]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
1.2.0升级1.3.1 由于任务Json格式变更导致Spark任务找不到Jar包 任务报错 ClassNotFound
即便应用了升级Mysql脚本 Json格式也没有变成1.3可以识别的Json格式 升级脚本是否没有对Spark任务 做升级变更处理？？？

又或者是1.3.1没有兼容1.2.0的任务？？？？

导致我必须 把所有Spark类型的任务 都要重新编辑一下 保存 刷新成1.3.1的Json格式才可以执行。。。

**Which version of DolphinScheduler:**
 -[1.3.1-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by lgcareer** [comment]
First,the id field appeared after the branch 1.3.1,It was designed run the task success with the old version.But here is a bug need to fixed,I will fix it on the branch 1.3.2

**Comment by lgcareer** [comment]
By the way,please use english,thanks.
