### ISSUE TITLE
工作流实例中可以编辑上线的工作流

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3366]
![image](https://user-images.githubusercontent.com/61308609/89017904-9c831400-d34d-11ea-9a11-c4d8122f5a23.png)
上线了的工作流,从工作流实例中进入查看日志,可以进行工作流的编辑保存

**Comment by yangyichao-mango** [comment]
Hi,
Version?

**Comment by 13430647361** [comment]
1.3.1版本,当工作流正在运行的时候从"工作流实例"中进入"确认添加"为灰色,但当工作流已经运行完成,从"工作流实例"中进入"确认添加"为可操作状态

**Comment by lenboo** [comment]
english official, please change the title and content to english, then reopen this issue.
