### ISSUE TITLE
[Feature][API] Workflow definition add tag filter

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3387]
The current workflow definition has no filtering function based on classification

Whether this demand is necessary or not

--------------------------------------------

**Comment by zhuangchong** [comment]
+1

**Comment by yangyichao-mango** [comment]
Hi,
I think we can first to improvement the search, expand the search to more fields like `desc`. Search is more basic function.#3170 

![image](https://user-images.githubusercontent.com/29545877/89181521-892ead80-d5c6-11ea-9eb2-920bb3d72037.png)

**Comment by BoYiZhang** [comment]
> Hi,
> I think we can first to improvement the search, expand the search to more fields like `desc`. Search is more basic function.#3170
> 
> ![image](https://user-images.githubusercontent.com/29545877/89181521-892ead80-d5c6-11ea-9eb2-920bb3d72037.png)



I know what you mean. In fact, we are already using the query extension.

--------------------------------------------------------------------------


We're working on the middle platform

In data modeling, data should be divided into multiple layers

Each layer has a special meaning

In this way, the current scheduling can only display one level, not multiple levels

It's not intuitive enough

**Comment by yangyichao-mango** [comment]
> > Hi,
> > I think we can first to improvement the search, expand the search to more fields like `desc`. Search is more basic function.#3170
> > ![image](https://user-images.githubusercontent.com/29545877/89181521-892ead80-d5c6-11ea-9eb2-920bb3d72037.png)
> 
> I know what you mean. In fact, we are already using the query extension.
> 
> We're working on the middle platform
> 
> In data modeling, data should be divided into multiple layers
> 
> Each layer has a special meaning
> 
> In this way, the current scheduling can only display one level, not multiple levels
> 
> It's not intuitive enough

Yes, I think this feature is valuable. Maybe we can design it more functional, for example, using folder to manage workflow.

**Comment by BoYiZhang** [comment]
> Yes, I think this feature is valuable. Maybe we can design it more functional, for example, using folder to manage workflow.
> Or some companies have datamap, we can add the front-end url to locate the workflow.
> 
> 我觉得这个feature是很有价值的。我觉得可以集思广益多想一下把这个功能做的更强大一点，比如使用文件夹管理。
> 并且还有一个想法，有些公司是有xx地图类的应用的，我们也可以加一个前端locate url(比如直接通过名称)，通过xx地图直接能跳转到工作流页面。

Yes, our business department's requirement is to be able to build a folder for display.

**Comment by lenboo** [comment]
this feature is wonderful! 
i am not the business department, but i think the tag is enough, you can set the tag value 'a-b-c-d' to display the multilevel relationship.
