### ISSUE TITLE
怎么指定maste选择worker的策略？ How to set the strategy for master choose worker?

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3391]
1.3的更新日志里说maste选择worker有3种策略（Random，RoundRobin和基于cpu和内存加权），这个在哪里设置？

According to the changelog for version 1.3，when master choose worker，it has three choices(Random, RoundRobin, and linear weighted based on cpu and memory)，how to set it?

**Comment by yangyichao-mango** [comment]
Hi,
You can configure `master.host.selector:lowerWeight` in `master.properties`.

RANDOM,
ROUNDROBIN,
LOWERWEIGHT

**Comment by yangyichao-mango** [comment]
Tag: could be closed. @yangyichao-mango
