### ISSUE TITLE
[Feature][Api] Admin can activate user registerd by themselves

### ISSUE THREAD

**Issue by cpsky** [apache/incubator-dolphinscheduler#3392]
**Describe the feature**
Admin can activate user registerd by themselves，user-self register api has completed.
https://github.com/apache/incubator-dolphinscheduler/commit/d4d6aded1184b803557f444c42253d02887995b9

**Describe the solution you'd like**
https://lists.apache.org/thread.html/r285280835025aaac4d610c5614f89948de2d1938843c4b0bcb3fb7e3%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by yangyichao-mango** [comment]
+1,
I think you can add the user info in return data field and improve d4d6ade (add user info in return data field).

**Comment by cpsky** [comment]
ok
