### ISSUE TITLE
怎么让1个worker属于多个worker组？How to make a worker belong to multiple worker groups?

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3411]
我有2个大作业，N个小作业，2个worker节点
我的需求是把2个大作业分别固定到1个worder上执行，小作业随机分配worder
在1.3版本怎么实现呢？

I have two big jobs, many small jobs, and two worker nodes.
I want each worker to execute only one big job, and small jobs will be randomly assigned to worders.
How to set it in version 1.3?

**Comment by wang87612** [comment]
我也有这个需求 1.3貌似 只能1对1 感觉很不实用啊

**Comment by glxfeng** [comment]
> 我也有这个需求 1.3貌似 只能1对1 感觉很不实用啊

是的，1.2都可以实现

**Comment by yangyichao-mango** [comment]
We will release this in 1.3.2.

**Comment by glxfeng** [comment]
> We will release this in 1.3.2.

Good.I'm looking forward to it.
