### ISSUE TITLE
flink节点提交到yarn上执行，点停止，为什么flink节点还是正在运行状态？

### ISSUE THREAD

**Issue by gaodayu** [apache/incubator-dolphinscheduler#3412]
flink 节点cluster模式提交，在流程实例中点停止，成功后，流程实例一直是准备停止，任务实例一直是正在运行，实际yarn上的作业已经停止了

**Comment by yangyichao-mango** [comment]
Please add more detail log and version info. Thx a lot~

**Comment by roger68** [comment]
I got the same problem.

**Comment by roger68** [comment]
I got the same problem.

**Comment by roger68** [comment]
<img width="677" alt="61DDF718-084E-4ecb-A367-93E7C9337B5F" src="https://user-images.githubusercontent.com/4043193/91254006-cd5f3900-e793-11ea-92b2-1c891915a6da.png">
<img width="941" alt="3670CDCA-41C3-405f-87EC-05DA5CFAEDBD" src="https://user-images.githubusercontent.com/4043193/91254011-cf28fc80-e793-11ea-9d76-17446b12f13b.png">

**Comment by roger68** [comment]
@gaodayu  make sure your server support “pstree“ command

**Comment by xingchun-chen** [comment]
Don't reply for a long time, it will be close.
If you have a problem, please change the title in English and reopen it
