### ISSUE TITLE
[Feature][Queue] You can select any yarn queue

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3416]
At present, the queue is bound to the user.

When a user runs MR, spark and Flink tasks, only one queue can be used

You cannot select other queues randomly

Is this unreasonable??

It is recommended to remove the field queue from the user / tenant

When creating Mr / spark / link, it is specified according to the business

such as :

![image](https://user-images.githubusercontent.com/39816903/89388626-dc277280-d736-11ea-8d61-7707755ed5f8.png)

**Comment by yangyichao-mango** [comment]
Good idea,
I think the queues should be related with privilege according the LADP #736 , and use can select the user-group's queues. It can control the privilege of user.

**Comment by BoYiZhang** [comment]
I plan to deal with this problem in two PR's

1. Support Mr, spark and Flink, and select any queue

2. Use another PR to handle the problem of queue permission

**Comment by break60** [comment]
Is there an issue for the new yarn queue?

**Comment by BoYiZhang** [comment]
> Is there an issue for the new yarn queue?

pr  #3515

**Comment by break60** [comment]
> > Is there an issue for the new yarn queue?
> 
> pr #3515
I read it wrong

**Comment by BoYiZhang** [comment]
> > > Is there an issue for the new yarn queue?
> > 
> > 
> > pr #3515
> > I read it wrong

This is the implementation of PR

https://github.com/apache/incubator-dolphinscheduler/pull/3515

**Comment by gaojun2048** [comment]
Thank you for your pr.

Now, yarn queue can only be associate to tenant（租户），the tenant is a hadoop user in a hadoop cluster . 
The yarn queue must be real and the hadoop user must have permission to submit jobs to the yarn queue.
Therefore, I think, if possible, the yarn queue that can be selected when creating the mr task must be the yarn queue associated with the tenant corresponding to the user.

In addition, the current tenant and yarn queue have a one-to-one relationship. So, it is meaningless to let users choose yarn queue. If a tenant can associate multiple yarn queues, it is a good idea to let users choose yarn queue when creating mr tasks.

**Comment by BoYiZhang** [comment]
> Thank you for your pr.
> 
> Now, yarn queue can only be associate to tenant（租户），the tenant is a hadoop user in a hadoop cluster .
> The yarn queue must be real and the hadoop user must have permission to submit jobs to the yarn queue.
> Therefore, I think, if possible, the yarn queue that can be selected when creating the mr task must be the yarn queue associated with the tenant corresponding to the user.
> 
> In addition, the current tenant and yarn queue have a one-to-one relationship. So, it is meaningless to let users choose yarn queue. If a tenant can associate multiple yarn queues, it is a good idea to let users choose yarn queue when creating mr tasks.

----------------------------------

In most of the yarn clusters, multi queue is used

Now, a user can only use one queue, if you want to use other queues, there is no way

It is very common that a user can use multiple queues, so this pr .

**Comment by BoYiZhang** [comment]
If not, the PR will be turned off .

**Comment by gaojun2048** [comment]
> If not, the PR will be turned off .

No, I think this feature is good. But you should make the  tenant can associate multiple yarn queues first and the yarn queue that can be selected when creating the mr task must be the yarn queue associated with the tenant corresponding to the user.

**Comment by BoYiZhang** [comment]
> > If not, the PR will be turned off .
> 
> No, I think this feature is good. But you should make the tenant can associate multiple yarn queues first and the yarn queue that can be selected when creating the mr task must be the yarn queue associated with the tenant corresponding to the user.

--------------------------------------------------------

In my opinion, I want to weaken the concept of tenants

As a strategy, tenants choose when performing tasks

Resource files are no longer stored on tenants, but are stored by project

Therefore, tenants are no longer strongly associated with users



Tenant and yarn queue are the same, can be configured at the time of execution



Of course, you can use authority to control and divide it to users



A user can use multiple tenants

A user can use more than one yarn queue



What's your opinion?

**Comment by gaojun2048** [comment]
**Resource files are no longer stored on tenants, but are stored by project** 
Tenants is necessary . because every user run task, upload files to hdfs must use a hadoop user to do this. we know every file in hdfs must ower by a hadoop user(tenants). If one user can can multiple tenants, when he upload resource file to hdfs, which hadoop user(tenants) is the file ower? Do we need to select tenants when saving resource files?

**Comment by BoYiZhang** [comment]
> **Resource files are no longer stored on tenants, but are stored by project**
> Tenants is necessary . because every user run task, upload files to hdfs must use a hadoop user to do this. we know every file in hdfs must ower by a hadoop user(tenants). If one user can can multiple tenants, when he upload resource file to hdfs, which hadoop user(tenants) is the file ower? Do we need to select tenants when saving resource files?

---------------


I'm talking about weakening tenants, not deleting them

Now the files are stored in HDFS, which is divided by tenant

In fact, if divided by project, it can also meet the needs

Now the implementation of the middle platform system, resources storage by project is more in line with the needs of tenants



The tenant is only responsible for the execution rights of tasks, not for storage

**Comment by gaojun2048** [comment]
**The tenant is only responsible for the execution rights of tasks, not for storage**
It`s ok.

**Comment by gaojun2048** [comment]
> > **Resource files are no longer stored on tenants, but are stored by project**
> > Tenants is necessary . because every user run task, upload files to hdfs must use a hadoop user to do this. we know every file in hdfs must ower by a hadoop user(tenants). If one user can can multiple tenants, when he upload resource file to hdfs, which hadoop user(tenants) is the file ower? Do we need to select tenants when saving resource files?
> 
> I'm talking about weakening tenants, not deleting them
> 
> Now the files are stored in HDFS, which is divided by tenant
> 
> In fact, if divided by project, it can also meet the needs
> 
> Now the implementation of the middle platform system, resources storage by project is more in line with the needs of tenants
> 
> The tenant is only responsible for the execution rights of tasks, not for storage

If users and tenants are one-to-one, resource files can be organized by tenants and by projects. Of course, it is best to organize by projects.
If the user and the tenant are not one-to-one, the user must choose which tenant to upload when uploading files to hdfs.

So I think user and the tenant are not one-to-one is necessary. Based on this premise, the organization of resource files by project is the best.

**Comment by BoYiZhang** [comment]
> > > **Resource files are no longer stored on tenants, but are stored by project**
> > > Tenants is necessary . because every user run task, upload files to hdfs must use a hadoop user to do this. we know every file in hdfs must ower by a hadoop user(tenants). If one user can can multiple tenants, when he upload resource file to hdfs, which hadoop user(tenants) is the file ower? Do we need to select tenants when saving resource files?
> > 
> > 
> > I'm talking about weakening tenants, not deleting them
> > Now the files are stored in HDFS, which is divided by tenant
> > In fact, if divided by project, it can also meet the needs
> > Now the implementation of the middle platform system, resources storage by project is more in line with the needs of tenants
> > The tenant is only responsible for the execution rights of tasks, not for storage
> 
> If users and tenants are one-to-one, resource files can be organized by tenants and by projects. Of course, it is best to organize by projects.
> If the user and the tenant are not one-to-one, the user must choose which tenant to upload when uploading files to hdfs.
> 
> So I think user and the tenant are one-to-one is necessary. Based on this premise, the organization of resource files by project is the best.

------------------


What if a user wants to have the rights of multiple tenants??



For example, execute Spark Program with spark tenant

Execute hive program with hive user

The root user is required to execute the system program



Today's programs are stored on tenants

Cross tenant execution procedures, resource files have to be authorized separately

If there are 100 projects, resource files refer to each other

How to manage resource files?

If the executive authority of the management program is ＂???

Looking forward to the development of dispatching...

**Comment by gaojun2048** [comment]
> > > > **Resource files are no longer stored on tenants, but are stored by project**
> > > > Tenants is necessary . because every user run task, upload files to hdfs must use a hadoop user to do this. we know every file in hdfs must ower by a hadoop user(tenants). If one user can can multiple tenants, when he upload resource file to hdfs, which hadoop user(tenants) is the file ower? Do we need to select tenants when saving resource files?
> > > 
> > > 
> > > I'm talking about weakening tenants, not deleting them
> > > Now the files are stored in HDFS, which is divided by tenant
> > > In fact, if divided by project, it can also meet the needs
> > > Now the implementation of the middle platform system, resources storage by project is more in line with the needs of tenants
> > > The tenant is only responsible for the execution rights of tasks, not for storage
> > 
> > 
> > If users and tenants are one-to-one, resource files can be organized by tenants and by projects. Of course, it is best to organize by projects.
> > If the user and the tenant are not one-to-one, the user must choose which tenant to upload when uploading files to hdfs.
> > So I think user and the tenant are one-to-one is necessary. Based on this premise, the organization of resource files by project is the best.
> 
> What if a user wants to have the rights of multiple tenants??
> 
> For example, execute Spark Program with spark tenant
> 
> Execute hive program with hive user
> 
> The root user is required to execute the system program
> 
> Today's programs are stored on tenants
> 
> Cross tenant execution procedures, resource files have to be authorized separately
> 
> If there are 100 projects, resource files refer to each other
> 
> How to manage resource files?
> 
> If the executive authority of the management program is ＂???
> 
> Looking forward to the development of dispatching...

After talking, we found that the key question is whether the resource file needs to have permission, whether the resource file in a project is shared by all users, whether the resource file between different projects is shared, if so, then we can use a tenant (this tenant is not associated with any users and is only used by ds to manage resource files) to organize resource files by project, and all users have common permissions to these resource files. Then the tenant associated with the user is only used to execute the task, so that the user and the tenant can be many-to-many, and the user can select the tenant and the yarn queue in the tenant to run the task.

**Comment by BoYiZhang** [comment]
If Kerberos is enabled, the tenant is useless

**Comment by BoYiZhang** [comment]
> associated

If Kerberos is enabled, the tenant is useless

**Comment by gaojun2048** [comment]
I think in the first stage we can allow tenants to add multiple queues, and then when creating tasks, we can select those queues of the tenant corresponding to the user. Regarding the issue of resource file management, we can create a new issue to discuss.
