### ISSUE TITLE
[Bug][ui] 工作流定义时使用鼠标滚轮时显示不正确

### ISSUE THREAD

**Issue by diorw** [apache/incubator-dolphinscheduler#3446]
编辑工作流时，使用滚轮放大，相应的连接线位置不会移动，而节点会移动，造成错位

**Comment by xingchun-chen** [comment]
which version？

**Comment by diorw** [comment]
> which version？
> please update the title in English

1.2.1

**Comment by xingchun-chen** [comment]
This problem has been resolved in version 1.2.1
