### ISSUE TITLE
[Question] Datasource  Create user oracle  failed

### ISSUE THREAD

**Issue by Lwaitt** [apache/incubator-dolphinscheduler#3453]
Use  [Datasource]  create a new one use ORACLE ,BUT failed.
I find same may lose some jar  

dolphinscheduler
[1.3.1] 
Oracle 12c
[12.1.0.2]

I get api log under  this
[ERROR] org.apache.dolphinscheduler.api.service.DataService;[433] - oracle.jdbc.driver,OracleDriver
java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver

how to solve the problem.

**Comment by zhuangchong** [comment]
ojdbc.jar Put it in the Lib directory and restart dolphin scheduler

---

ojdbc.jar 放到lib目录下，重启dolphinscheduler

**Comment by Lwaitt** [comment]
> ojdbc.jar Put it in the Lib directory and restart dolphin scheduler
> 
> ojdbc.jar 放到lib目录下，重启dolphinscheduler

Tkssss! !! Its simple and effective
