### ISSUE TITLE
执行 Hive UDF 报错

### ISSUE THREAD

**Issue by lingxingzhang** [apache/incubator-dolphinscheduler#3455]
这个DS打印的日志 我在hive客户端测试 没有问题
add jar hdfs://172.16.10.153:8020/dolphinscheduler/zuhuytest/udfs/hiveudf/hiveudf-2.0-SNAPSHOT.jar
create temporary function HelloUDF as 'com.iwellmass.udf.HelloUDF'
insert overwrite directory "/var/hivesql/HelloUDF" select HelloUDF(zhlx) as zhlxs from graph.z_gl_account

但是我用DS提交的话 会报错！
![image](https://user-images.githubusercontent.com/64292411/89772018-e7faa680-db33-11ea-9bf9-d836918bec12.png)

**Comment by yangyichao-mango** [comment]
Which version?

**Comment by lingxingzhang** [comment]
@yangyichao-mango DS 1.3.1 CDH6.0.1 
是不是因为hive整合了Tez的原因呢？

**Comment by lingxingzhang** [comment]
@yangyichao-mango 
您好 DS版本1.3.1
CDH版本6.0.1
hive更换了执行引擎为Tez

**Comment by lingxingzhang** [comment]
@yangyichao-mango 您好，您有空帮我看一下问题呢 谢谢您

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango 您好，您有空帮我看一下问题呢 谢谢您

Sorry, I am not familiar with Tez. Anyone else who can resolve this?

**Comment by lgcareer** [comment]
@lingxingzhang  So sorry for reply late,When use tez,if only execute `insert overwrite directory '/tmp/udf_test' select hello(sname) from test.student` it will be successful. But use udf and execute `insert overwrite directory '/tmp/udf_test' select hello(sname) from test.student` weill be failure.

## Sugeest to change execute engine to mr
I changed the execute engine to mr,it will be successful.Suggest you do it.
