### ISSUE TITLE
dolphinscheduler server memory problems

### ISSUE THREAD

**Issue by liangpingliu** [apache/incubator-dolphinscheduler#3458]
在初始化脚本里服务启动内存设置xms=1g，是指Master Api Worker Logger Alert 每个服务1g，那就是最少5g，再考虑如果都整成分布式高可用，每台服务器占用就是5g，资源占用较大。因此xms 能够调多小，会有哪些影响。

**Comment by zhuangchong** [comment]
1.并不是所有的server都装到一个机器上，正常都会分发到多个节点部署，每个节点装2-3个server
2.如果量级小，也可以设置128m，256m去尝试启动，生产环境应该都不会设置这么小，毕竟它是一个java进程。
