### ISSUE TITLE
[Question] The program type of spark node is selected as PYTHON, how should the main jar package be selected?

### ISSUE THREAD

**Issue by 18668180370** [apache/incubator-dolphinscheduler#3469]
**Describe the question**
![image](https://user-images.githubusercontent.com/45786444/89966662-459d0900-dc82-11ea-9299-910c9b1745d0.png)

**Which version of DolphinScheduler:**
 -[1.3.0]

**Additional context**
The program type of spark node is selected as PYTHON, how should the main jar package be selected?
Because on a linux machine, this command "spark-sumbit *.py" can run spark to run python files.

**Requirement or improvement**
no

**Comment by dailidong** [comment]
if you choose python, main jar package choose your python file will be OK
sorry for misleading you, python should not use jar as package name, but it can work

**Comment by dailidong** [comment]
please update/add title in English

**Comment by 18668180370** [comment]
> if you choose python, main jar package choose your python file will be OK
> sorry for misleading you, python should not use jar as package name, but it can work

Okay thank you!
But the python file cannot be recognized in the "main jar package" column, and because there is no main jar file, the task cannot be saved, and the result is that python cannot operate the spark task. It is worth mentioning that the upload function should not upload jar files.

**Comment by liangriyu** [comment]
The same problem also appears in 1.3.1

**Comment by xingchun-chen** [comment]
The 1.3.0 and 1.3.1 versions filter the main jar package, only displaying the jar file , which will be fixed in version 1.3.2

**Comment by 18668180370** [comment]
OK，thanks发自我的华为手机-------- 原始邮件 --------主题：Re: [apache/incubator-dolphinscheduler] [Question] The program type of spark node is selected as PYTHON, how should the main jar package be selected? (#3469)发件人：xingchun-chen 收件人：apache/incubator-dolphinscheduler 抄送：18668180370 <18668180370@163.com>,Author 
The 1.3.0 and 1.3.1 versions filter the main jar package, only displaying the jar file , which will be fixed in version 1.3.2

**Comment by yangyichao-mango** [comment]
> The 1.3.0 and 1.3.1 versions filter the main jar package, only displaying the jar file , which will be fixed in version 1.3.2

Is there a contributor who are fixing this bug？
