### ISSUE TITLE
[Improvement][common] JSONUtils.toMap It is not necessary to check whether the JSON method is empty again.

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3471]
**Describe the question**
1.JSONUtils.toMap It is not necessary to check whether the JSON method is empty again.

2.processService.delCommandByid and processService.queryUdfFunListByids Method name checkstyle

**What are the current deficiencies and the benefits of improvement**
- The code is clear

**Which version of DolphinScheduler:**
 -[dev]

---

**描述问题**

对改进之处的清晰而简洁的描述。

1.JSONUtils.toMap（String json）方法内部已经对json校验空，没有必要再调用方法是再次校验参数是否为空。
2.  processService.delCommandByid processService.queryUdfFunListByids 方法名checkstyle

**目前的不足和改进的好处是什么**

1.代码清晰

**DolphinScheduler的哪个版本：**

-[dev]

**Comment by yangyichao-mango** [comment]
![image](https://user-images.githubusercontent.com/29545877/89975895-8eac8780-dc99-11ea-837e-9c4db486620a.png)

**Comment by yangyichao-mango** [comment]
1. For JsonUitls.toMap(), I think it is necessary to check whether the string is empty before use jsonUtils according to the fail-fast mode, and the null judge in jsonUtils is just the second protect from NPE. We can not just rely on the jsonUtils null check.

2.Method name checkstyle +1. If you want to improve it, welcome to leave a message.

**Comment by zhuangchong** [comment]
1.JsonUitls.toMap (string JSON) the parameter values are checked for null both inside and outside the method, and the code is repeated.

---
1. JsonUitls.toMap(String json) 针对参数值在方法内和方法外都进行校验空，进行了2遍校验，代码是重复的。

**Comment by yangyichao-mango** [comment]
> 1.JsonUitls.toMap (string JSON) the parameter values are checked for null both inside and outside the method, and the code is repeated.
> 
> 1. JsonUitls.toMap(String json) 针对参数值在方法内和方法外都进行校验空，进行了2遍校验，代码是重复的。

OK, I think double check is just an extra layer of protection. If it can guarantee that NPE will not occur, I think it is OK to remove the outer null check.

-------
Ok，我只是觉得double check只是多了一层防护，如果能保障不会出现npe的情况，我觉得去除外层check也是可以的。

**Comment by CalvinKirs** [comment]
close by #3481
