### ISSUE TITLE
[Question] email config  is  must？

### ISSUE THREAD

**Issue by liuzx8888** [apache/incubator-dolphinscheduler#3475]
question:
现在组件中邮件的设置是必须选项
![image](https://user-images.githubusercontent.com/10862577/89982816-f918f400-dca8-11ea-9493-47ccb804422f.png)

跟踪代码， 方法[sendAttachment]  在执行完sql结果后会立即执行，如果邮件发送不成功,项目就失败 ，不知道是我查的方向有问题，还是这里的设置就是如此，这样的设置是不是不太合理，有很多在内网运行的项目，并没有邮件服务器，也无法连接到互联网，这种的项目是不是就无法使用这个工具呢，或者有其他地方设置取消这个选项么?

![image](https://user-images.githubusercontent.com/10862577/89982985-4f863280-dca9-11ea-9428-51196e007785.png)

version 1.3.1

**Comment by dailidong** [comment]
yes, for now the mail cofig must be set,  if you have some suggestions,please leave message

**Comment by liuxuedongcn** [comment]
> yes, for now the mail cofig must be set, if you have some suggestions,please leave message
I hope there is an option to set whether to send or not, allowing users to choose whether to send under any circumstances or send only when it fails or not send at any time

**Comment by liuzx8888** [comment]
> yes, for now the mail cofig must be set, if you have some suggestions,please leave message
@dailidong @liuxuedongcn 

我想请教下，首先是否邮件如果不设置、sql语句正确的前提下也是无法正确完成任务的对么？

假如是这样的话，那是不是不太合理，有些场景是无法配置这些信息的，类似我们现在做的都是在局域网内的项目，无法设置这些信息，那这个工具是不是就无法使用呢？真心请教！！！

**Comment by Jops-data** [comment]
@liuzx8888  你有遇见这个SQL查询节点，失败的告警邮件可以发送但是查询结果的邮件发送失败的情况嘛？其实我有点搞不懂到底是执行SQL失败了还是发送消息失败啦。worker也没有具体日志。 这个是我的执行日志
![image](https://user-images.githubusercontent.com/63348491/90002567-6470bf00-dcc5-11ea-8e69-4d42cae5f8b5.png)

**Comment by liuzx8888** [comment]
@Jops-data  是的 我的跟你的一样的，我是再本地搭了一个开发环境，我把那个 发送的邮件的代码注释掉就好了。也不知道我查询的是否正确，还是又其他地方设置。

**Comment by yangyichao-mango** [comment]
> @Jops-data  是的 我的跟你的一样的，我是在本地搭了一个开发环境，我把那个 发送的邮件的代码注释掉就好了。我跟踪出来的情况是这样的。

Hi~
If you want the feature about just execute sql not to send mail, please create an issue about this feature.

**Comment by chengshiwen** [comment]
Close by #5104

The switch to send mail has supported in next 1.3.6

![image](https://user-images.githubusercontent.com/4902714/114265730-07303780-9a25-11eb-8d2a-7d75a591d222.png)
