### ISSUE TITLE
[Bug][Common] read the file garbled

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3478]
When reading the file, no encoding is specified, resulting in garbled code

![image](https://user-images.githubusercontent.com/39816903/90090148-e3153d00-dd55-11ea-9eef-0a60784a153f.png)

![image](https://user-images.githubusercontent.com/39816903/90090344-5919a400-dd56-11ea-8366-64690029847e.png)

**Comment by felix-thinkingdata** [comment]
The default should be unified UTF-8 encoding. What coding format do you use?

**Comment by BoYiZhang** [comment]
> The default should be unified UTF-8 encoding. What coding format do you use?

hadoop and system use utf-8

-------------------

However, it is deployed on Huawei cloud server, resulting in garbled code


---------------------
It is amended as follows: 



![image](https://user-images.githubusercontent.com/39816903/90090817-8dda2b00-dd57-11ea-981c-f44f6383c694.png)
