### ISSUE TITLE
How to use the resources in the shell node?

### ISSUE THREAD

**Issue by 18668180370** [apache/incubator-dolphinscheduler#3486]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
How to use the resources in the shell node?
![image](https://user-images.githubusercontent.com/45786444/90119934-c5af9580-dd8c-11ea-8743-42687c3a953a.png)

**Which version of DolphinScheduler:**
 -[1.3.0]

**Additional context**
After the resource is selected, the resource file cannot be used in the shell script. For example, "sh test.sh" will report an error and no log will be output. Please help me answer

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by lenboo** [comment]
what's the error log the '查看日志' display?

**Comment by xingchun-chen** [comment]
You need to execute: sh test/test.sh
