### ISSUE TITLE
[Bug][API] Creating folders with multiple threads will result in multiple identical folders

### ISSUE THREAD

**Issue by yy0812** [apache/incubator-dolphinscheduler#3487]
Multiple threads calling the API to create folders will result in multiple identical folders。

The API to create folders is expected to be thread-safe

dolphinScheduler version is 1.3.1

![image](https://user-images.githubusercontent.com/32183971/90121929-2cce4980-dd8f-11ea-86e5-bb133ce6a88e.png)
![image](https://user-images.githubusercontent.com/32183971/90122161-7159e500-dd8f-11ea-8ad3-88161044d26b.png)

**Comment by xingchun-chen** [comment]
Who wants to fix it？

**Comment by muzhongjiang** [comment]
> Who wants to fix it？

I will  fix it

**Comment by xingchun-chen** [comment]
How is the progress of this issues now

**Comment by muzhongjiang** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/3697

**Comment by IamMujuziMoses** [comment]
Is this Issue still Open?!!... wanted to work on it if it is still open

**Comment by xingchun-chen** [comment]
The problem has been resolved
