### ISSUE TITLE
[Question] What components should be used here

### ISSUE THREAD

**Issue by muzhongjiang** [apache/incubator-dolphinscheduler#3491]
**Describe the question**
![image](https://user-images.githubusercontent.com/7700151/90209511-2d61f100-de1e-11ea-846e-8da891f789aa.png)

After the execution of the tasks of the first level is completed, the second level tasks will be executed. 
What components should be used between the first and second levels to connect .

**Which version of DolphinScheduler:**
 -[1.3.1-preview]

**Comment by lenboo** [comment]
what's your purpose?

**Comment by xingchun-chen** [comment]
Do not reply for a long time, it will be close.
 if there is a problem, please reopen it
