### ISSUE TITLE
[Question] How many times should "task3" be executed

### ISSUE THREAD

**Issue by muzhongjiang** [apache/incubator-dolphinscheduler#3492]
**Describe the question**
![image](https://user-images.githubusercontent.com/7700151/90209765-ce50ac00-de1e-11ea-9101-5189d6bc72fc.png)

![image](https://user-images.githubusercontent.com/7700151/90209715-afeab080-de1e-11ea-83ae-1ffa7e0eed93.png)

**Which version of DolphinScheduler:**
 -[1.3.1]

**Comment by lenboo** [comment]
only one, do you have run the work flow already?
