### ISSUE TITLE
[Bug][api] worker group manage ui could not display createtime and updatetime

### ISSUE THREAD

**Issue by gaoyang-projects** [apache/incubator-dolphinscheduler#3493]
**Describe the bug**
worker group manage ui could not display createtime and updatetime

**To Reproduce**
1. Normal start and login
2. goto "security> worker group manage"

**Expected behavior**
createtime and updatetime is null

**Screenshots**
![WechatIMG56](https://user-images.githubusercontent.com/6829668/90211359-0528c100-de23-11ea-87e5-a9fc155d72c7.png)

**Which version of Dolphin Scheduler:**
 -[1.3.1-release]

**Additional context**
1.HeartBeatTask#run, send message to zk for report
2.zk property value format 
"cpuUsage,memoryUsage,loadAverage,availablePhysicalMemorySize,maxCpuloadAvg,reservedMemory,startTime,updatetime.status,processid"
`HeartBeatTask#run`
> ` 
            StringBuilder builder = new StringBuilder(100);
            builder.append(OSUtils.cpuUsage()).append(COMMA);  
            builder.append(OSUtils.memoryUsage()).append(COMMA); 
            builder.append(OSUtils.loadAverage()).append(COMMA);
            builder.append(OSUtils.availablePhysicalMemorySize()).append(Constants.COMMA);
            builder.append(maxCpuloadAvg).append(Constants.COMMA);
            builder.append(reservedMemory).append(Constants.COMMA);
            builder.append(startTime).append(Constants.COMMA); // index 6
            builder.append(DateUtils.dateToString(new Date())).append(Constants.COMMA); //index 7
            builder.append(status).append(COMMA);
            //save process id
            builder.append(OSUtils.getProcessID());`

3.WorkerGroupService#getWorkerGroups get zk path value and parse

> `  
                    String registeredIpValue = zookeeperCachedOperator.get(workerGroupPath + "/" + childrenNodes.get(0));
                    wg.setCreateTime(DateUtils.stringToDate(registeredIpValue.split(",")[3]));   // split twice and error
                    wg.setUpdateTime(DateUtils.stringToDate(registeredIpValue.split(",")[4]));`// split twice and error
`
4. update 

> `
                    String[] splitedRegisteredIpValue = registeredIpValue.split(",");
                    wg.setCreateTime(DateUtils.stringToDate(splitedRegisteredIpValue[splitedRegisteredIpValue.length-3]));
                    wg.setUpdateTime(DateUtils.stringToDate(splitedRegisteredIpValue[splitedRegisteredIpValue.length-4]));
`

**Comment by yangyichao-mango** [comment]
I will try to reproduce this bug later.

**Comment by xingchun-chen** [comment]
the issue is the same as #3258
