### ISSUE TITLE
[Bug][Master] The same scheduling task runs twice, causing data duplication

### ISSUE THREAD

**Issue by superxiaojie** [apache/incubator-dolphinscheduler#3495]
**Describe the bug**
The same scheduling task runs twice, causing data duplication
**To Reproduce**
1. The cluster has two workers and two masters
2. set up a scheduled task
3. run by time

**Expected behavior**
duplicate tasks

**Screenshots**
![image](https://user-images.githubusercontent.com/18513424/90220906-b5a2bf00-de3b-11ea-8794-d6d03b4b5da7.png)

**Which version of Dolphin Scheduler:**
 -[1.2.0-preview]

**Additional context**
![image](https://user-images.githubusercontent.com/18513424/90221838-7d03e500-de3d-11ea-8704-a711c234af88.png)

**improvement**
does this problem exist in 1.3.1 ?
  thx

**Comment by xu-zhijian** [comment]
add config
org.quartz.jobStore.acquireTriggersWithinLock=true

**Comment by superxiaojie** [comment]
> add config
> org.quartz.jobStore.acquireTriggersWithinLock=true

thx

添加参数之后解决了。
