### ISSUE TITLE
[Question] '/tmp/dolphinscheduler/exec/process' storage is very large

### ISSUE THREAD

**Issue by siaron** [apache/incubator-dolphinscheduler#3516]
## If the task jar package of mr is large and there are many tasks, it takes up more space
`17G     dolphinscheduler` 100 mr task jar package with 100m will generate a 17GB cache file. Is there a cleanup strategy for this? Or can it be cleaned up when the task ends?

**Comment by lenboo** [comment]
please change the title and content to english. thx.

**Comment by glxfeng** [comment]
保留多久取决你自己的需求，删掉以后DS里就看不到执行日志了，可以写个定时任务去清理该目录下X天前产生的.command和.sh的文件
