### ISSUE TITLE
[Bug][工作流] 编辑工作流，点进去以后，编辑页面经常空白。

### ISSUE THREAD

**Issue by gaoyu2016** [apache/incubator-dolphinscheduler#3528]
chrome浏览器版本 84.0.4147.125（正式版本），经测试，编辑工作流，点进去以后，编辑页面经常空白。
火狐浏览器没有这个问题。
![image](https://user-images.githubusercontent.com/29685418/90365868-1a0e8a00-e099-11ea-8f11-932f58389f30.png)

**Comment by break60** [comment]
You first go to the network to see these request interfaces, what causes the lack of response data

**Comment by gaoyu2016** [comment]
解决，网络限制的问题。
