### ISSUE TITLE
spark任务 程序获取命令行参数中文乱码

### ISSUE THREAD

**Issue by lingxingzhang** [apache/incubator-dolphinscheduler#3529]
**Describe the bug**
spark任务 命令行参数 在程序中获取到时乱码

**To Reproduce**
Steps to reproduce the behavior, for example:
1. 新建spark任务
2. 填写spark命令行参数
3. 程序打印main方法的args
4. 中文是乱码 数字可以正常显示

**Expected behavior**
中文正常显示

**Screenshots**
![image](https://user-images.githubusercontent.com/64292411/90375556-b049ac80-e0a7-11ea-84ac-3deecb7d770f.png)
![image](https://user-images.githubusercontent.com/64292411/90376246-bab87600-e0a8-11ea-918a-cfaf0c8733d7.png)
![image](https://user-images.githubusercontent.com/64292411/90376911-c7899980-e0a9-11ea-9864-dd7f1b12942d.png)

**Which version of Dolphin Scheduler:**
-[1.3.1-release]

**Comment by yangyichao-mango** [comment]
Hi,
I will try to reproduce it later.

**Comment by yangyichao-mango** [comment]
Hi,
You can check the task instance log what the Chinese params showing.
![image](https://user-images.githubusercontent.com/29545877/90481011-aa190600-e163-11ea-82e3-c72b164ac8be.png)

**Comment by yangyichao-mango** [comment]
BTW, English is need. Please change the title and description to English.

**Comment by lingxingzhang** [comment]
@yangyichao-mango 
Thank you. I checked the log. The Chinese version of the spark-submit log printed by DS is correct. It should be a spark-submit issue.
