### ISSUE TITLE
[Improvement][alert] email alert config

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3542]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
If **"mail.smtp.ssl.enable"** property is false, not configuring **"mail.smtp.ssl.trust"** will report an error

![image](https://user-images.githubusercontent.com/59079269/90495662-75af4500-e177-11ea-910a-58d8a1c4df76.png)

**Comment by yangyichao-mango** [comment]
+1

**Comment by felix-thinkingdata** [comment]
complete

**Comment by felix-thinkingdata** [comment]
complete
