### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apache/incubator-dolphinscheduler#3545]
https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-alert/src/main/java/org/apache/dolphinscheduler/alert/utils/PropertyUtils.java#L44

https://github.com/apache/incubator-dolphinscheduler/blob/00e0003aed207adc33d1c4068977b172fa21d3f0/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/PropertyUtils.java#L42

These fields are never used.

**Comment by dailidong** [comment]
it used by itself，you can see it call `init` method
    private static final PropertyUtils propertyUtils = new PropertyUtils();

    private PropertyUtils(){
        init();
    }

    /**
     * init
     */
    private void init(){
        String[] propertyFiles = new String[]{Constants.DATASOURCE_PROPERTIES};
        for (String fileName : propertyFiles) {
            InputStream fis = null;
            try {
                fis = PropertyUtils.class.getResourceAsStream(fileName);
                properties.load(fis);

            } catch (IOException e) {
                logger.error(e.getMessage(), e);
                if (fis != null) {
                    IOUtils.closeQuietly(fis);
                }
                System.exit(1);
            } finally {
                IOUtils.closeQuietly(fis);
            }
        }
    }
