### ISSUE TITLE
[Question] 1.21版本部署前端怎么部署

### ISSUE THREAD

**Issue by Heyw** [apache/incubator-dolphinscheduler#3547]

**Comment by zhuangchong** [comment]
The front end does not need to be deployed. After all services are started, it can be accessed directly http://192.168.xx.xx :12345/dolphinscheduler

If there are multiple API servers, consider adding a layer of nginx before it

https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/cluster-deployment.html

---

前端不需要部署，所有服务启动后，直接访问http://192.168.xx.xx:12345/dolphinscheduler
如果多个API Server 可以考虑前面加一层nginx

https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/cluster-deployment.html
