### ISSUE TITLE
[Bug][Server][sqlTask]The alias column in the query SQL does not take effect

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/incubator-dolphinscheduler#3549]
such as the sql: select id as aa from test_user
when send mail in sqlTask, the column name should be aa, not id. Actually the column name is id now.

**Comment by JinyLeeChina** [comment]
I will fix it

**Comment by xingchun-chen** [comment]
Has the issue been resolved? If pr is submitted, please associate pr with issue
