### ISSUE TITLE
[Bug][Module Name] Bug title Host key verification failed!!!

### ISSUE THREAD

**Issue by Fengt-en** [apache/incubator-dolphinscheduler#3551]
Problem description: SSH has a problem in UI interface
Test steps:
1. Log in to Linux and configure dolphinscheduler and TestUser to be dolphinscheduler confidential free
2. Test the result of non-secrecy.
2.1. Su dolphinscheduler
2.2. SSH to testuser@192.168.x.x
2.3. Successful
3. Log out
Verify that SSH between servers is no problem.Not suitable for the Internet said sSH-Keygen-R solution
4. Log into Dolphinscheduler UI
5. Configure workflow and write shell scripts
![image](https://user-images.githubusercontent.com/55683544/90603765-5b846e00-e22e-11ea-9339-f3ae46dcb7e0.png)
6. Execute error "Host Key Verification Failed"
![image](https://user-images.githubusercontent.com/55683544/90603808-70f99800-e22e-11ea-9aae-1ad90f65add4.png)
This problem occurs after 1.2, including 1.2
Version 1.1 has been tested and used normally, including executing the exact same program in the UI
Is this a BUG in version 1.2/1.3
Again, this version does not support this feature

**Comment by dailidong** [comment]
you can referer: https://blog.csdn.net/xqhrs232/article/details/73613414

**Comment by Fengt-en** [comment]
> 您可以参考：[https](https://blog.csdn.net/xqhrs232/article/details/73613414) : [//blog.csdn.net/xqhrs232/article/details/73613414](https://blog.csdn.net/xqhrs232/article/details/73613414)

First of all, thank you for your guidance.
After the above article, I tested it and the same error occurred, "Host Key Verification Failed."
"
![image](https://user-images.githubusercontent.com/55683544/90708135-b0c28d00-e2cb-11ea-99fa-2ad303c0e74a.png)
![image](https://user-images.githubusercontent.com/55683544/90708206-d485d300-e2cb-11ea-9667-e6ad0d945808.png)
Now I would like to ask if any other users have reported the same problem when using versions 1.2 and 1.3.
I will post worker.log and ma.log and api_server.log for reference
![image](https://user-images.githubusercontent.com/55683544/90708296-0303ae00-e2cc-11ea-93c8-3ce86ef5472e.png)
![image](https://user-images.githubusercontent.com/55683544/90708321-10b93380-e2cc-11ea-9e2c-4609a70de6c5.png)
![image](https://user-images.githubusercontent.com/55683544/90708351-23336d00-e2cc-11ea-8382-ee01672dba6e.png)

**Comment by Fengt-en** [comment]
> you can referer: https://blog.csdn.net/xqhrs232/article/details/73613414
I've tested a number of methods, and no matter what, it says "Host key Verification failed."
"
Even if I enter the clear text password it will say "Host Key Verification Failed"
![image](https://user-images.githubusercontent.com/55683544/90713471-fab17000-e2d7-11ea-890c-32715ed8a7f0.png)
No matter which IP to SSH, or even SSH native root, is successful in the linux, and fails in the UI

**Comment by Fengt-en** [comment]
I'm sorry to have taken up your valuable time.However, this error report needs to be resolved urgently and is indeed a version BUG.Thank you for
https://github.com/apache/incubator-dolphinscheduler/issues/3551


| |
Feng.t
|
|
f_t8888@163.com
|
签名由网易邮箱大师定制
On 8/19/2020 18:32，dailidong<notifications@github.com> wrote：

you can referer: https://blog.csdn.net/xqhrs232/article/details/73613414

**Comment by yangyichao-mango** [comment]
Tag: Could be closed. @yangyichao-mango
