### ISSUE TITLE
[Bug][ui] when edit the work flow,the selected connecting line has no style change,but the others have get bigger  (1.3.0版本工作流编辑时被选中的line样式不变，其他未被选中的line变粗)

### ISSUE THREAD

**Issue by zoulixun** [apache/incubator-dolphinscheduler#3553]
工作流定义的时候，通过‘’箭头选择器‘’选中line的时候，被选中的line样式不变，未被选中的其他line样式却变粗，而且当鼠标移入变粗了的未被选中的line时，变粗的line又恢复原样，这样的话当我想删除某一条线的时候，我不知道我选中了哪条line

**Comment by xingchun-chen** [comment]
Please update the title in English

**Comment by break60** [comment]
When the connection is changed to a Bezier line, when the connection is selected, the total connection path is selected. This is caused by the fill attribute in the svg path. Currently, the fill attribute is not added to the connection when the connection is selected, and it cannot be changed. Interested friends can also study this problem together
连线改成贝塞尔线时，选中连线时是选择的总个连线路径，这个是svg path里面有个fill属性导致，目前选中连线时不给连线增加fill属性，改不了，有兴趣的小伙伴也可以一起研究下这个问题

**Comment by zoulixun** [comment]
Solved Method:
First,you can remove all the 'HoverPaintStyle'attribute when the dag init in 'dag.vue'.
Secondly,you should remove all the 'fill' attribute in 'setSvgColor' function in 'dag/_source/plugin/util.js' and add a selected color that you want when '_.map($(e.canvas)[0].childNodes'.
Method End.
Additional remarks:although cancled the hover style of the connecting line,you can know which line you have selected clearly if you do this.
解决办法：
首先，当dag初始化的时候，你要删除所有的‘HoverPaintStyle’属性在‘dag.vue’文件中。
其次，你要删除‘setSvgColor‘函数中’的所有的’fill‘属性并且添加一个你想要的颜色在‘_.map($(e.canvas)[0].childNodes'的时候在dag/_source/plugin/util.js' 文件中。
方法结束。
补充说明：这样做的话虽然取消了连接线的鼠标悬停样式，但是你可以清楚地知道你选中的是哪条线。

**Comment by break60** [comment]
Did you try it locally?

**Comment by zoulixun** [comment]
> Did you try it locally?
> Is the shadow part resolved?

Yes，I did and you can try as my way.
By the way,I can not understand the 'shadow part' you said.

**Comment by zoulixun** [comment]
Maybe this is not the best way,but I think 

> Did you try it locally?
> Is the shadow part resolved?

@break60 maybe I know what you mean,the 'shadow part' means the hover style?I remove the hover style like I said above.

**Comment by break60** [comment]
> Maybe this is not the best way,but I think
> 
> > Did you try it locally?
> > Is the shadow part resolved?
> 
> @break60 maybe I know what you mean,the 'shadow part' means the hover style?I remove the hover style like I said above.

Try it locally according to your method, it's ok, but I didn't add the distinguishing color, can you pr up?

**Comment by zoulixun** [comment]
the current style of the connecting line that I have modified is the same as the 1.2.0 verion

**Comment by zoulixun** [comment]
> > Maybe this is not the best way,but I think
> > > Did you try it locally?
> > > Is the shadow part resolved?
> > 
> > 
> > @break60 maybe I know what you mean,the 'shadow part' means the hover style?I remove the hover style like I said above.
> 
> Try it locally according to your method, it's ok, but I didn't add the distinguishing color, can you pr up?

@break60

**Comment by zoulixun** [comment]
@break60 ok, wait a moment

**Comment by break60** [comment]
> @break60 ok, wait a moment

👌

**Comment by zoulixun** [comment]
> > @break60 ok, wait a moment
> 
> 👌

@break60 because there is trouble with my git,I cant not pr up. If it's convenient for you,you can pr up my way for our family.
