### ISSUE TITLE
[Test][api] Improvement `DataAnalysisServiceTest`

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3557]
**Describe the question**
Improvement the DataAnalysisServiceTest test case for DataAnalysisServiceImpl for full coverage **(100% method coverage)**.

**Test case example**
https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java

**Test case specifications**
https://dolphinscheduler.apache.org/zh-cn/docs/development/unit-test.html
**Important: Need to improvement the test case according to the specifications**

**Which version of DolphinScheduler**
-[dev]

**Comment by yangyichao-mango** [comment]
Anyone who want to take it, welcome to leave a message~

**Comment by SunJiFengPlus** [comment]
i am on it!

**Comment by SunJiFengPlus** [comment]
Current in ```DataAnalysisServiceImpl::countQueueState```, except for project check failure, it will only return all count are 0, can i delete redundant logic? 

---

目前```DataAnalysisServiceImpl::countQueueState```这个方法中除了project校验失败, 其他情况下返回的count全部为0, 我是否可以把多余的逻辑都删掉?

**Comment by SunJiFengPlus** [comment]
Change to this
``` java
    public Map<String, Object> countQueueState(User loginUser, int projectId) {
        Map<String, Object> result = new HashMap<>(5);

        boolean checkProject = checkProject(loginUser, projectId, result);
        if (!checkProject) {
            return result;
        }

        Map<String, Integer> dataMap = new HashMap<>();
        dataMap.put("taskQueue", 0);
        dataMap.put("taskKill", 0);

        result.put(Constants.DATA_LIST, dataMap);
        putMsg(result, Status.SUCCESS);
        return result;
    }
```

**Comment by SunJiFengPlus** [comment]
Hi, i'm having trouble, i delete try catch block, because it never throw exception.

replace
```java
        Date start = null;
        Date end = null;
        try {
            start = DateUtils.getScheduleDate(startDate);
            end = DateUtils.getScheduleDate(endDate);
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
            putErrorRequestParamsMsg(result);
            return result;
        }
```

with
```java
        Date start = null;
        Date end = null;
        if (StringUtils.isNotEmpty(startDate) && StringUtils.isNotEmpty(endDate)) {
            start = DateUtils.getScheduleDate(startDate);
            end = DateUtils.getScheduleDate(endDate);
            if (Objects.isNull(start) || Objects.isNull(end)) {
                putErrorRequestParamsMsg(result);
                return result;
            }
        }
```

I write the same code twice, cause 3.9% duplication, can't pass sonar analysis, but i don't know how to extract, because the process contains return.

**Comment by CalvinKirs** [comment]
close by #3605
