### ISSUE TITLE
[Test][api] Improvement `DataSourceServiceTest`

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3558]
**Describe the question**
Improvement the DataSourceServiceTest test case for DataSourceService for full coverage **(100% method coverage)**.

**Test case example**
https://github.com/apache/incubator-dolphinscheduler/blob/dev/dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessDefinitionServiceTest.java

**Test case specifications**
https://dolphinscheduler.apache.org/zh-cn/docs/development/unit-test.html
**Important: Need to improvement the test case according to the specifications**

**Which version of DolphinScheduler:**
-[dev]

**Comment by yangyichao-mango** [comment]
Anyone who want to take it, welcome to leave a message~

**Comment by breeze0812** [comment]
I will take [Test-3558] to write the unittest to full coverage.
