### ISSUE TITLE
[Feature][Docs] Improve the English version of the official community documentation

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-dolphinscheduler#3562]
At present, the Chinese and English of our official documents are not synchronized. We hope that friends who are interested in participating in community contributions will complete it. I will post some articles that need English translation here. Interested friends can leave a message below to choose articles of interest to participate.

Official document address: https://dolphinscheduler.apache.org/

Official document project address: https://github.com/apache/incubator-dolphinscheduler-website

**Comment by CalvinKirs** [comment]
- [ ] Docs: version-1.3.0 architecture design  (chinese version ：架构设计)

- [ ] Docs version 1.3.0 deployment parameter analysis(chinese version : 部署参数分析)

**Comment by Somaru-chan** [comment]
Hello. I'm interested in contributing to the English translation process. Is it from Chinese to English only? I'm not a Chinese speaker.

**Comment by CalvinKirs** [comment]
> Hello. I'm interested in contributing to the English translation process. Is it from Chinese to English only? I'm not a Chinese speaker.

This requires us to be able to read and understand Chinese means, can you read Chinese documents?

**Comment by Somaru-chan** [comment]
> > Hello. I'm interested in contributing to the English translation process. Is it from Chinese to English only? I'm not a Chinese speaker.
> 
> This requires us to be able to read and understand Chinese means, can you read Chinese documents?

Hi Calvin. Unfortunately, I can't. But I'd like to contribute in any other way, if possible. Thanks.

**Comment by CalvinKirs** [comment]
> > > Hello. I'm interested in contributing to the English translation process. Is it from Chinese to English only? I'm not a Chinese speaker.
> > 
> > 
> > This requires us to be able to read and understand Chinese means, can you read Chinese documents?
> 
> Hi Calvin. Unfortunately, I can't. But I'd like to contribute in any other way, if possible. Thanks.

hi,you can subscribe to our mailing list. Please refer to (https://dolphinscheduler.apache.org/en-us/docs/development/subscribe.html) for specific steps. We will post related tasks on the mailing list. At the same time, you can also follow Our issue list, find the task you are interested in to complete it

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, I'm an outreachy internship applicant. There's currently no system-manual documentation for version 1.3.2. I think I can translate from the Chinese version. Can I work on that?

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs, I'm an outreachy internship applicant. There's currently no system-manual documentation for version 1.3.2. I think I can translate from the Chinese version. Can I work on that?

Very welcome 👏, you can create a separate issue, and then associate the main issue.

**Comment by Segun-Ogundipe** [comment]
> > Hi @CalvinKirs, I'm an outreachy internship applicant. There's currently no system-manual documentation for version 1.3.2. I think I can translate from the Chinese version. Can I work on that?
> 
> Very welcome 👏, you can create a separate issue, and then associate the main issue.

Will do. Thanks

**Comment by Segun-Ogundipe** [comment]
@CalvinKirs, I have created the issue here #3883. Please Assign me to it. Thanks

**Comment by CalvinKirs** [comment]
> @CalvinKirs, I have created the issue here #3883. Please Assign me to it. Thanks

done

**Comment by dailidong** [comment]
> @CalvinKirs, I have created the issue here #3883. Please Assign me to it. Thanks

good job, it's a good beginning

**Comment by Segun-Ogundipe** [comment]
> > @CalvinKirs, I have created the issue here #3883. Please Assign me to it. Thanks
> 
> good job, it's a good beginning

Thanks

**Comment by CalvinKirs** [comment]
> I will do the Environment setup part

Very welcome and look forward to your contribution

**Comment by CalvinKirs** [comment]
> I will do the Environment setup part

welcome and look forward to your contribution.

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, I have created two PR for Java Micro BenchMark Test and Commit Message here apache/incubator-dolphinscheduler-website#196 and apache/incubator-dolphinscheduler-website#197

**Comment by CalvinKirs** [comment]
Hi, everyone, I have released a new document translation task, 1.3.2-user_doc-architecture-design (1.3.2 Architecture Design) Chinese version: link https://dolphinscheduler.apache.org/zh-cn/docs/ 1.3.2 / user_doc / architecture-design.html, interested friends can come and claim it.

**Comment by CalvinKirs** [comment]
Docs: fix Some articles cannot be accessed due to wrong path（easy to fix）
Any friends who are interested in this task?

**Comment by aNotBadCoder** [comment]
Hi @CalvinKirs 


> Docs: fix Some articles cannot be accessed due to wrong path（easy to fix）
whether the task has been solved ?
if not, i can resolved the question.

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs
> 
> > Docs: fix Some articles cannot be accessed due to wrong path（easy to fix）
> 
> whether the task has been solved ?
> if not, i can resolved the question.

Sorry, I am a bit late to update, this task has been completed. There is another task. We need to delete some information in the Readme file. Are you willing to complete it?

**Comment by CalvinKirs** [comment]
done
