### ISSUE TITLE
[Feature][api] admin batch activate users

### ISSUE THREAD

**Issue by cpsky** [apache/incubator-dolphinscheduler#3567]
**Describe the feature**
admin can batch activate users who registered by themselves.

**Describe the solution you'd like**
I will add a new api to api-server.
Here is solution link：
https://lists.apache.org/thread.html/r4ca8bbb60bffff08e01b6503b67564a261f398bd91b850d309dfd1d1%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by cpsky** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/3578

**Comment by dailidong** [comment]
Batch activate Users
request URL：
POST /users/batch/activate http1.0/1.1

Content-Type application/json
post parameters (input user names)
 [ "123",
 "124",
 "12345",
 "2345"
 ]


response
 {
 "code": 0,
 "data": {
 "success": [
 "123",
 "124",
 "1235"
 ],
 "failed": [
 "2345"
 ]
 },
 "msg":"activate success number is 3, failed number is 1"
 }
