### ISSUE TITLE
[Bug][API] The Spark task runs in Cluster mode, executes successfully but the status of the task is shown to fail

### ISSUE THREAD

**Issue by breeze0812** [apache/incubator-dolphinscheduler#3584]
use version 1.3.1 of Dolphinscheduler：

**Describe the bug**
The Spark task runs in Cluster mode, executes successfully but the status of the task is shown to fail.

**To Reproduce**
1. Run a Spark task in Cluster mode.
2. view the status fo the task,failed.
![image](https://user-images.githubusercontent.com/32183971/91116113-37a5aa00-e6be-11ea-9a71-ab9d6e6300b2.png)
3. View the task log and the end of the log shows that the Spark task executed successfully.
![image](https://user-images.githubusercontent.com/32183971/91116069-20ff5300-e6be-11ea-99dc-a1a4f37059f5.png)

**Expected behavior**
The Spark task runs in Cluster mode, executes successfully then the status of the task is shown to success.

**Comment by xingchun-chen** [comment]
You can check if there is an error in the worker log

**Comment by breeze0812** [comment]
I checked the log on yarn and found no errors, what are the criteria for determining the execution state of the current Spark task?

**Comment by shitoubiao** [comment]
The Spark task runs in Cluster mode, executes successfully then the status of the task is shown to submit success.

**Comment by dailidong** [comment]
please find exit code for this task in the worker server runtime log, if exit code is not 0, it will failure

**Comment by dailidong** [comment]
> I checked the log on yarn and found no errors, what are the criteria for determining the execution state of the current Spark task?

not yarn log, please find exit code for this task in the DolphinScheduelr worker server runtime log, if exit code is not 0, it will failure

**Comment by breeze0812** [comment]
> > I checked the log on yarn and found no errors, what are the criteria for determining the execution state of the current Spark task?
> 
> not yarn log, please find exit code for this task in the DolphinScheduelr worker server runtime log, if exit code is not 0, it will failure

Sorry, after check because my configuration parameters of the yarn. The `yarn.resourcemanager.ha.rm.ids` configuration errors caused by waste your time
