### ISSUE TITLE
[Question] sqoop task can't  configure parameter target-dir

### ISSUE THREAD

**Issue by chenghm** [apache/incubator-dolphinscheduler#3588]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
To import mysql data into hive database, I have created a sqoop task. After execution, an error is reported. The Log was  
'Must specify destination with --target-dir. Try --help for usage instructions.' I have tried to configure the parameter target-dir in the sqoop task ,but it didn't work. I want to know how to solve this problem，and look forward to your reply.Thanks

**Which version of DolphinScheduler:**
 -[1.3.1]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
could you have a look at this issue? @zixi0825 @Rubik-W @Eights-Li

**Comment by Eights-Li** [comment]
Please provide sqoop job configuration, 
--target-dir can be set through 'custom param'

**Comment by porkling** [comment]
have you solved it? I have this problem, too. custom parameters can only take effect in SQL. the - target dir parameter is not valid. version [1.3.2].

**Comment by zixi0825** [comment]
![image](https://user-images.githubusercontent.com/10829956/95648927-6f9d6b00-0b0d-11eb-96dc-d1b26578be80.png)
add in sqoop 參數 @porkling

**Comment by porkling** [comment]
There is no choice of parameters for sqoop and Hadoop
![image](https://user-images.githubusercontent.com/38812393/95650986-86e25580-0b19-11eb-88fe-a14fc13e0a20.png)
@zixi0825

**Comment by Eights-Li** [comment]
sqoop custom param and sqoop job hadoop custom param support in dev-branch.
