### ISSUE TITLE
[Bug][Authorize]  The authorize page cannot see the complete resource list

### ISSUE THREAD

**Issue by zhangweiwhim** [apache/incubator-dolphinscheduler#3589]
The authorize  page cannot see the  complete resource list when authorize more resources to the user 

1. Go to 'Security ->User Manage'
2. Click on 'Authorize'
3. authorize page was incomplete display
![image](https://user-images.githubusercontent.com/29200663/91162142-4449f280-e6fe-11ea-93b3-472818dae835.png)

**Which version of Dolphin Scheduler:**
incubator-dolphinscheduler-[1.3.1]

**Comment by CalvinKirs** [comment]
close by #3593
