### ISSUE TITLE
[Bug][server] Execution of the subprocess is very inefficient。（子流程的执行效率非常低）

### ISSUE THREAD

**Issue by pipiwukong** [apache/incubator-dolphinscheduler#3595]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
If a process has some subprocesses. These subprocesses can't be excuted in parallel efficiently. 
I have finished a test in two situations.
case1： Ten processes run together. Tasks of ten processes can be excuted in  parallel. The task concurrency can reach more the 80.
case2：Create a new processes to excute ten processes as subprocesses. Tasks of ten subprocesses can't be excuted in  parallel.  Just the tasks in one subprocess can be excuted in  parallel. The task concurrency is lower the 20. 

How to improve the performance of the subprocess？

**Which version of DolphinScheduler:**
 -[1.3.1]

**Additional context**

**Requirement or improvement**
Analysing the DAGs of the subprocesses together to find the tasks can be excuted. Then excute these tasks in parallel.

**Comment by KnightChess** [comment]
a process instance correspond a masterExecThread，a masterExecThread only can start up 20 taskExecThread to excute task in parallel，if you want improve it，modify parameter master.exec.task.num=20，80 or more in master.properties
