### ISSUE TITLE
[Bug][首页] 页面滚动遮挡顶部菜单

### ISSUE THREAD

**Issue by liuyungao** [apache/incubator-dolphinscheduler#3599]
首页页面向上滚动时遮挡了顶部菜单栏！
The top menu bar is obscured when the home page scrolls up！
![WX20200826-155559](https://user-images.githubusercontent.com/15725862/91277410-5b97e700-e7b5-11ea-887c-025851657218.png)

**Comment by break60** [comment]
Which version are you using

**Comment by liuyungao** [comment]
> Which version are you using

i don't know which version,it Found in demo system

**Comment by break60** [comment]
> > Which version are you using
> 
> i don't know which version,it Found in demo system

I did not have your problem, you open a private browser to try, is there a cache?

**Comment by liuyungao** [comment]
> > > Which version are you using
> > 
> > 
> > i don't know which version,it Found in demo system
> 
> I did not have your problem, you open a private browser to try, is there a cache?

after clear cache it's ok! tks!
