### ISSUE TITLE
一直让输入密码

### ISSUE THREAD

**Issue by d317356845** [apache/incubator-dolphinscheduler#3602]
![image](https://user-images.githubusercontent.com/7321756/91296712-a32b6c80-e7cf-11ea-82f9-72a4269e566d.png)
大神，为什么一直让输入密码呢？谢谢

**Comment by zhuangchong** [comment]
Check the sudo configuration. It should be that the password free is not set or the configuration is not successful

https://dolphinscheduler.apache.org/zh-cn/docs/1.3.1/user_doc/cluster-deployment.html

```
# 配置sudo免密
echo 'dolphinscheduler  ALL=(ALL)  NOPASSWD: NOPASSWD: ALL' >> /etc/sudoers
sed -i 's/Defaults    requirett/#Defaults    requirett/g' /etc/sudoers

```
---

查看一下sudo 配置，应该没有设置免密或者配置未成功
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.1/user_doc/cluster-deployment.html

```
# 配置sudo免密
echo 'dolphinscheduler  ALL=(ALL)  NOPASSWD: NOPASSWD: ALL' >> /etc/sudoers
sed -i 's/Defaults    requirett/#Defaults    requirett/g' /etc/sudoers

```
