### ISSUE TITLE
[Feature][Module Name] 创建流程定义后返回值里带上流程ID

### ISSUE THREAD

**Issue by xiaosongaa** [apache/incubator-dolphinscheduler#3604]
创建流程定义后返回值里希望能带上流程ID
当前通过API创建流程后，必须通过流程名称查找列表，才能知道自己创建的流程ID并发布，执行，很不方便

**Comment by kevinsun2010** [comment]
@xiaosongaa   流程定义是这个接口吗？接口地址 /dolphinscheduler/projects/{projectName}/process/save
代码里面看到是有id返回的，是不是版本问题呢？ 看到1.3.1版本 是有返回流程id的。你确认下
![2020-08-26_195935](https://user-images.githubusercontent.com/27861996/91301178-14bae900-e7d7-11ea-8528-f0d38d3923b9.jpg)

**Comment by xiaosongaa** [comment]
> @xiaosongaa 流程定义是这个接口吗？接口地址 /dolphinscheduler/projects/{projectName}/process/save
> 代码里面看到是有id返回的，是不是版本问题呢？ 看到1.3.1版本 是有返回流程id的。你确认下
> ![2020-08-26_195935](https://user-images.githubusercontent.com/27861996/91301178-14bae900-e7d7-11ea-8528-f0d38d3923b9.jpg)

是这个接口，1.3.1版本 返回值为：{"code":"0","msg":"success",“data”:null}

**Comment by kevinsun2010** [comment]
页面创建工作流返回值：
{"code":0,"msg":"成功","data":{"id":4,"name":"wf05","version":0,"releaseState":"OFFLINE","projectId":1,"processDefinitionJson":"{\"globalParams\":[],\"tasks\":[{\"type\":\"SHELL\",\"id\":\"tasks-4919\",\"name\":\"shell01\",\"params\":{\"resourceList\":[],\"localParams\":[],\"rawScript\":\"#!/bin/bash\\necho \\\"Hello World !\\\"\"},\"description\":\"\",\"runFlag\":\"NORMAL\",\"conditionResult\":{\"successNode\":[\"\"],\"failedNode\":[\"\"]},\"dependence\":{},\"maxRetryTimes\":\"0\",\"retryInterval\":\"1\",\"delayTime\":\"0\",\"timeout\":{\"strategy\":\"\",\"interval\":null,\"enable\":false},\"taskInstancePriority\":\"MEDIUM\",\"workerGroup\":\"default\",\"preTasks\":[]}],\"tenantId\":-1,\"timeout\":0}","description":"wf05","globalParams":null,"globalParamList":[],"globalParamMap":null,"createTime":"2020-08-27 08:17:28","updateTime":"2020-08-27 08:17:28","flag":"YES","userId":1,"userName":null,"projectName":null,"locations":"{\"tasks-4919\":{\"name\":\"shell01\",\"targetarr\":\"\",\"nodenumber\":\"0\",\"x\":394,\"y\":251}}","connects":"[]","receivers":null,"receiversCc":null,"scheduleReleaseState":null,"timeout":0,"tenantId":-1,"modifyBy":"admin","resourceIds":""}}

**Comment by kevinsun2010** [comment]
@xiaosongaa   我使用ui操作和api调用，都可以返回data数据，包含流程id（见截图）。 你看下后台日志是否正常。

![2020-08-27_082211](https://user-images.githubusercontent.com/27861996/91369477-75314100-e83e-11ea-9164-9d7a79143821.jpg)

**Comment by yangyichao-mango** [comment]
It can return the data in this procedure.
![image](https://user-images.githubusercontent.com/29545877/91375526-8a619c00-e84d-11ea-8583-9fd16f82bddf.png)

**Comment by WilliamChen-luckbob** [comment]
> @xiaosongaa 我使用ui操作和api调用，都可以返回data数据，包含流程id（见截图）。 你看下后台日志是否正常。
> 
> ![2020-08-27_082211](https://user-images.githubusercontent.com/27861996/91369477-75314100-e83e-11ea-9164-9d7a79143821.jpg)

1.3.4release这个接口的返回值确定是空的，UI上面直接操作，data也是null

**Comment by zhuangchong** [comment]
This issue has been resolved

![image](https://user-images.githubusercontent.com/37063904/114258986-40ed4800-99fd-11eb-985c-05f5788a3a67.png)
