### ISSUE TITLE
[Improvement][ui]The browser cannot maintain a session with multiple TAB logins open; need to log in for each TAB.

### ISSUE THREAD

**Issue by kevinsun2010** [apache/incubator-dolphinscheduler#3606]
**Describe the question**

one browser window cannot maintain a session with multiple TAB logins open; 
need to log in for each TAB, need keep session in all browser tab page.

**Which version of DolphinScheduler:**
1.3.1

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
Who can solve it

**Comment by CalvinKirs** [comment]
Sorry, this is determined by the browser session mechanism.
