### ISSUE TITLE
[Bug][Workflow version] ProcessDefinition version can delete and save with releaseState=ONLINE

### ISSUE THREAD

**Issue by geosmart** [apache/incubator-dolphinscheduler#3607]
**Describe the bug**
ProcessDefinition version can delete and save with releaseState=ONLINE

**To Reproduce**
Steps to reproduce the behavior, for example:
1. set processdefinition online
2. click processdefinition name
3. click save `[bug]should disabeld`
4. click version info,delete/switch version `[bug]shoudld disabeld`

**Which version of Dolphin Scheduler:**
 -[dev]
@yangyichao-mango

**Comment by yangyichao-mango** [comment]
I reproduce this in my local env, I will fix it.

**Comment by yangyichao-mango** [comment]
Could be closed.

**Comment by geosmart** [comment]
thanks @yangyichao-mango to fix this
