### ISSUE TITLE
[Improvement][ui] UI optimization for workflow version  

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3612]
1. The Chinese version "Version" is changed to "version number"
2. remove column  "#"
3. The content of the switch version pop-up box is changed to one line display
4. There isn't closed when the "Cancel" button of the switch version popup is clicked
5. When the description is too long, omit it.....display, move the mouse up and then float to display all descriptions
1.中文版Version改为“版本号”
2.去掉"#"列
3.切换版本弹框的内容改为一行显示
4.切换版本弹框的“取消”按钮点击没反应
5.描述太长时加省略.....显示，鼠标移上去再浮层显示所有描述
![image](https://user-images.githubusercontent.com/55787491/91388693-7710f980-e86a-11ea-8265-93260e43436e.png)
![image](https://user-images.githubusercontent.com/55787491/91388734-885a0600-e86a-11ea-9c58-43806f0c2ebb.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by xingchun-chen** [comment]
@yangyichao-mango Please solve the above problem，Thanks

**Comment by yangyichao-mango** [comment]
![image](https://user-images.githubusercontent.com/29545877/91443941-9cbbf400-e8a6-11ea-84a4-7972e7e616f1.png)

**Comment by yangyichao-mango** [comment]
Hi, 
@xingchun-chen I do not reproduce this error.
![image](https://user-images.githubusercontent.com/29545877/91444744-c32e5f00-e8a7-11ea-8d37-cddde5334169.png)

**Comment by yangyichao-mango** [comment]
`Process Definition` list page also has `5` problem.
![image](https://user-images.githubusercontent.com/29545877/91514235-d1689380-e918-11ea-8c95-7888ef667b08.png)

**Comment by yangyichao-mango** [comment]
There also have this problem when I zoom this page. Please confirm @chenxingchun 
![image](https://user-images.githubusercontent.com/29545877/91514702-f4e00e00-e919-11ea-8cb9-21c2df73c5ee.png)

**Comment by xingchun-chen** [comment]
@yangyichao-mango   Steps to reproduce 4 problems：
1. Switch the current version from 10 to 6
2. Click the "Switch version" button for version 10
3. Click the "Cancel" button in the popup, but the popup is not closed
![image](https://user-images.githubusercontent.com/55787491/91527352-38e20b80-e938-11ea-8947-60ec82843f28.png)

**Comment by xingchun-chen** [comment]
5 problem and Process Definition list page ,homepage zoom does have a problem

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango Steps to reproduce 4 problems：
> 
> 1. Switch the current version from 10 to 6
> 2. Click the "Switch version" button for version 10
> 3. Click the "Cancel" button in the popup, but the popup is not closed
>    ![image](https://user-images.githubusercontent.com/55787491/91527352-38e20b80-e938-11ea-8947-60ec82843f28.png)

Got it~

**Comment by yangyichao-mango** [comment]
I have fixed `1`, `2`, `3`, `4`, any suggestions about `5` for version info and process definition list page?
@chenxingchun

**Comment by xingchun-chen** [comment]
@yangyichao-mango  The 5 question suggests that the workflow definition list and version control more than 10 characters with..., move the mouse into the floating layer to display all descriptions

**Comment by yangyichao-mango** [comment]
> @yangyichao-mango The 5 question suggests that the workflow definition list and version control more than 10 characters with..., move the mouse into the floating layer to display all descriptions

I have followed your suggestions and change to this class.
![image](https://user-images.githubusercontent.com/29545877/91923831-e0c65300-ed03-11ea-9434-0df69802ae21.png)

**Comment by zhuangchong** [comment]
This issue has been resolved
