### ISSUE TITLE
[Bug][master-server]sometimes one command would be execute more than one times

### ISSUE THREAD

**Issue by rockxsj** [apache/incubator-dolphinscheduler#3613]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
I found sometimes one command would be execute twice,for example:
![image](https://user-images.githubusercontent.com/3021207/91393843-ebe53300-e86c-11ea-983e-2f56f5d1ed36.png)

**To Reproduce**
Steps to reproduce the behavior, for example:
I don't know how to reproduce.

**Expected behavior**
one command would be executed one times.

**Screenshots**
![image](https://user-images.githubusercontent.com/3021207/91393843-ebe53300-e86c-11ea-983e-2f56f5d1ed36.png)

**Which version of Dolphin Scheduler:**
 -[1.3.1-Release]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by rockxsj** [comment]
![image](https://user-images.githubusercontent.com/3021207/91400040-99f2dc00-e871-11ea-896f-2b9bb8750363.png)
![image](https://user-images.githubusercontent.com/3021207/91400059-a1b28080-e871-11ea-8c26-5f01dacd834b.png)

The log show that each master server execute this command one times, I think maybe some bug exists in ZK lock.

**Comment by xingchun-chen** [comment]
who can check the reason?

**Comment by rockxsj** [comment]
``` log

2020-08-26 19:03:23 | [INFO] 2020-08-26 19:03:23.593 org.apache.dolphinscheduler.server.master.processor.TaskAckProcessor:[81] - taskAckCommand : TaskExecuteAckCommand{taskInstanceId=22986, startTime=Wed Aug 26 19:03:23 CST 2020, host='10.122.84.6:1234', status=1, logPath='/opt/dolphinscheduler/logs/310/20580/22986.log', executePath='/tmp/dolphinscheduler/exec/process/4/310/20580/22986'}
-- | --
  |   | 2020-08-26 19:03:23 | [INFO] 2020-08-26 19:03:23.655 org.apache.dolphinscheduler.server.master.processor.TaskAckProcessor:[81] - taskAckCommand : TaskExecuteAckCommand{taskInstanceId=22987, startTime=Wed Aug 26 19:03:23 CST 2020, host='10.122.84.6:1234', status=1, logPath='/opt/dolphinscheduler/logs/310/20581/22987.log', executePath='/tmp/dolphinscheduler/exec/process/4/310/20581/22987'}
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.363 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[123] - wait task: process id: 20580, task id:22986, task name:load complete
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.289 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[190] - master submit success, task : load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.136 org.apache.dolphinscheduler.service.process.ProcessService:[833] - start submit task : load, instance id:20580, state: RUNNING_EXEUTION
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.987 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[939] - remove task from stand by list: load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.986 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[930] - add task to stand by list: load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.911 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[331] - prepare process :20580 end
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.835 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[140] - start master exec thread , split DAG ...
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.682 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[123] - wait task: process id: 20581, task id:22987, task name:load complete
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.609 org.apache.dolphinscheduler.server.master.runner.MasterTaskExecThread:[190] - master submit success, task : load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.457 org.apache.dolphinscheduler.service.process.ProcessService:[833] - start submit task : load, instance id:20581, state: RUNNING_EXEUTION
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.310 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[939] - remove task from stand by list: load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.309 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[930] - add task to stand by list: load
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.236 org.apache.dolphinscheduler.server.master.runner.MasterExecThread:[331] - prepare process :20581 end
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:22.162 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[140] - start master exec thread , split DAG ...
  |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.935 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 20748, type: START_PROCESS
  |   | 2020-08-26 19:03:21 | [INFO] 2020-08-26 19:03:21.631 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 20748, type: START_PROCESS


```


@dailidong more log here.

**Comment by dailidong** [comment]
>   |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.835 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[140] - start master exec thread , split DAG ...

could you paste the worker server original runtime log?

**Comment by geosmart** [comment]
> ```
>   |   | 2020-08-26 19:03:22 | [INFO] 2020-08-26 19:03:21.935 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 20748, type: START_PROCESS
>   |   | 2020-08-26 19:03:21 | [INFO] 2020-08-26 19:03:21.631 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 20748, type: START_PROCESS
> ```
> 
why the timeline is not in sequence?

**Comment by rockxsj** [comment]
The problem is DBA make the database proxy read & write separation...   I will close this issue now.

**Comment by dailidong** [comment]
good news, seems it not a bug of DolphinScheduler, the entire process as follows:

The insert command inserted into the master, but it may be read from the master or slave when reading. It may be that first time the master reads the data on the master , it will be executed, and then the command will be removed from the master, and the second loop will be read from the slave. However, due to the delay of master-slave synchronization, the command in the slave is not deleted, so it is executed again

---
就是插入command是插入到master了，但是读的时候可能会从master或者slave读，那可能第一次读了master发现有数据就执行了，然后从master中移除command，第二次循环就从slave读了，但是由于主从同步延时，所以这时候slave里面的这条command并没有被删除，所以又执行了一次

**Comment by dailidong** [comment]
if you meet this situation, to database, you can set force reading from master
