### ISSUE TITLE
[Bug][master] When the master receives the result from the worker, the master just stops. After the master restarts, the workflow status is always executing

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3616]
1.run workflow
2.When the master receives the feedback from the worker, the master just stops. After the master restarts, the workflow status is always executing，and the workflow can't be stop
当worker向master发送执行结果的时候，master刚好被挂掉，重启master后，工作流及任务状态一直为进行中，且工作流无法停止
The master log is as follows  （master日志如下）
![image](https://user-images.githubusercontent.com/55787491/91423948-c4ea2980-e88b-11ea-8a83-09eb3205c3fd.png)
The worker log is as follows  （worker日志如下）
![image](https://user-images.githubusercontent.com/55787491/91424138-ff53c680-e88b-11ea-9608-734c8a94e92b.png)
![image](https://user-images.githubusercontent.com/55787491/91424189-0da1e280-e88c-11ea-94a3-7186372a3031.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by qiaozhanwei** [comment]
OK，I will check and fix worker communicate for master with synchronize

**Comment by xingchun-chen** [comment]
Worker updates the master status synchronously

**Comment by qiaozhanwei** [comment]
![worker_retry_report_task_to_master](https://user-images.githubusercontent.com/23756105/93171572-f0aa5200-f75b-11ea-8c12-7d22715895bb.png)

**Comment by xingchun-chen** [comment]
1. first, run workflow A , workflow instance A is in execution, stop master service
2. Restart the master service , after successful execution of workflow instance A, delete workflow instance A 

3. second, run workflow A again, workflow instance B is in execution, stop master service
4. Restart the master service, the master service has been receiving the success message of deleted task 90, as shown in the figure below,  taskInstanceId=90 is the task of workflow instance A
![image](https://user-images.githubusercontent.com/55787491/93456858-d36ab480-f910-11ea-8c4f-9063f7bdd966.png)
![image](https://user-images.githubusercontent.com/55787491/93456896-de254980-f910-11ea-869b-bc05c7567c53.png)

**Comment by xingchun-chen** [comment]
1."子任务_shell_3" related task "shell_3", when "shell_3" is executed successfully, stop the master service,
2.After restarting the master service, "subtask_shell_3" is always running ，and the final status cannot be obtained
![image](https://user-images.githubusercontent.com/55787491/93560176-20539700-f9b4-11ea-8bfc-718c19d791d8.png)
