### ISSUE TITLE
[Improvement][install,start-all,stop-all] start- all.sh and stop- all.sh After execution, you can view the running status of each node and service.

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3619]
**Describe the question**
start- all.sh and stop- all.sh After execution, you can view the running status of each node and service.

**What are the current deficiencies and the benefits of improvement**
At present, the shortage is start- all.sh and stop- all.sh After execution, the status should be executed manually- all.sh To view the running status of each node and service.
After the improvement, the status will be changed- all.sh Join start- all.sh and stop- all.sh In this way, starting / stopping the service can immediately view the running status of the node.

**Which version of DolphinScheduler:**
 -[dev]

---

**描述问题**
start-all.sh and stop-all.sh 执行后可查看可查看各节点各服务运行状态

**目前的不足和改进的好处是什么**
目前不足是start-all.sh and stop-all.sh 执行后，要手动执行status-all.sh来查看各节点各服务运行状态.
改进后将status-all.sh 加入 start-all.sh and stop-all.sh ，这样启动/停止服务可立即查看节点运行状态。

**DolphinScheduler的哪个版本：**
-[dev]

**Comment by felix-thinkingdata** [comment]
Add a status check function after start and stop script execution. If status check fails, you will get feedback immediately.

在启动停止脚本执行后，加一个确认状态功能，如果状态确认失败，会立刻有反馈，是这个意思吧。

**Comment by zhuangchong** [comment]
> Add a status check function after start and stop script execution. If status check fails, you will get feedback immediately.
> 
> 在启动停止脚本执行后，加一个确认状态功能，如果状态确认失败，会立刻有反馈，是这个意思吧。

Yes, I will fix it
