### ISSUE TITLE
[Bug][master] After batch deleting the executing process instances, the master cannot get the worker feedback results

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3621]
1. Run more than 40 workflows in batches, and the status of the workflow instance and task instance is executing
2. Click the batch delete button on the process instance page
3. After the worker task is executed successfully, the master cannot get the result
4. Run the workflow, the master does not assign tasks to the workers

## Solution: After restarting the master service, all tasks run normally
1.批量运行40个以上工作流，工作流实例及任务实例状态都为执行中
2.流程实例页面点击批量删除按钮
3.worker任务执行成功后，master拿不到woker反馈的结果
4.运行工作流，master也没有向worker分配任务

## 解决方法：重启master服务后，所有任务正常运行

![image](https://user-images.githubusercontent.com/55787491/91513197-569e7900-e916-11ea-8907-1713e4f266b4.png)

![image](https://user-images.githubusercontent.com/55787491/91513168-47b7c680-e916-11ea-96b5-3a46ff77badf.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by yangyichao-mango** [comment]
I will try reproduce this bug later.

**Comment by xingchun-chen** [comment]
need to check whether the process instance exists after the worker returns, and then update if it exists. If it does not exist, throw the result away, and run a new workflow without issuing tasks.

**Comment by yangyichao-mango** [comment]
> need to check whether the process instance exists after the worker returns, and then update if it exists. If it does not exist, throw the result away, and run a new workflow without issuing tasks.

I do not reproduce 3,
I try it with 45 process instance, and batch delete 10 process instance, it still can return the wright result for the other 35 process instance.

I reproduced 4, when I batch delete process instance and new a process instance,  the log shows it is assigned to worker successfully and the worker run it successfully,  but master do not get the result response, and I will trace it later.

**Comment by break60** [comment]
If the workflow instance status is executing status, it is forbidden to select
