### ISSUE TITLE
[Bug]一个worker不能属于多个工作组 one worker can’t belong different worker groups

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3628]
1.3.2版本一个新的功能是一个worker能属于多个工作组
https://github.com/apache/incubator-dolphinscheduler/pull/3277
但我实际测试，在worker.properties里设置worker.groups=default,group1
在页面上还是只有default这个工作组

A new feature of version 1.3.2 is that a worker can belong to multiple working groups
https://github.com/apache/incubator-dolphinscheduler/pull/3277
But I actually tested that in config file worker.properties Setting in worker.groups=default,group1
On the UI, only default worder groups

worker.properties
![image](https://user-images.githubusercontent.com/57620584/91709265-1577c480-ebb5-11ea-8126-7897883de500.png)
install_config.conf
![image](https://user-images.githubusercontent.com/57620584/91709187-f842f600-ebb4-11ea-85d3-e86ac96c6991.png)
WEB UI
![image](https://user-images.githubusercontent.com/57620584/91708263-ad74ae80-ebb3-11ea-9a67-f8ab9230ca79.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by xingchun-chen** [comment]
My test is OK. After you change the worker configuration, did you restart the worker service?
 
![image](https://user-images.githubusercontent.com/55787491/91709229-0a249900-ebb5-11ea-91d4-5b1a26abd3bb.png)

**Comment by glxfeng** [comment]
> My different worker groups are OK, After you change the worker configuration, did you restart the worker service?
>  
> ![image](https://user-images.githubusercontent.com/55787491/91709229-0a249900-ebb5-11ea-91d4-5b1a26abd3bb.png)

Yes, all service are restarted. Can you take a screenshot of the work groups in worker.properties and install_config.conf

**Comment by xingchun-chen** [comment]
There is no problem with your configuration. Are you sure it is the latest code of 1.3.2-release? You can check whether the worker groups are the latest code through the pr:https://github.com/apache/incubator-dolphinscheduler/pull/3277

**Comment by glxfeng** [comment]
> There is no problem with your configuration. Are you sure it is the latest code of 1.3.2-release? You can check whether the worker groups are the latest code

Maybe it's what you said. The first time I use  script install.sh update the directory of 1.3.1-release. Just now I installed  in a new directory and modify the config file. As a result, the work groups are right. 

Thanks for your help.
