### ISSUE TITLE
[Bug]The date shows the problem on the safari browser

### ISSUE THREAD

**Issue by wuwentao515** [apache/incubator-dolphinscheduler#3637]
<img width="810" alt="屏幕快照 2020-09-01 下午4 56 02" src="https://user-images.githubusercontent.com/21189049/91829952-acf01c80-ec74-11ea-9627-2a0e428e2f66.png">
Time is displayed as Invalid Date in the safari browser.

**Comment by break60** [comment]
ds is currently only compatible with Google Chrome

**Comment by wuwentao515** [comment]
thanks
