### ISSUE TITLE
[Bug]单独执行工作流里的作业时默认工作组错误 Default workgroup error when executing a job

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3638]
在一个工作流(已上线)里单独执行某个作业时，默认的工作组不对，而且不能选择
When a job is executed separately in a workflow (online), the default working group is not correct and cannot be selected

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

![image](https://user-images.githubusercontent.com/57620584/91861607-9d39fd80-ec9f-11ea-8e3e-36981b41889f.png)
![image](https://user-images.githubusercontent.com/57620584/91861623-a1661b00-ec9f-11ea-9309-30bd4ce9d8e0.png)
![image](https://user-images.githubusercontent.com/57620584/91861639-a5923880-ec9f-11ea-99d1-52d31fd1e346.png)
![image](https://user-images.githubusercontent.com/57620584/91861825-d6726d80-ec9f-11ea-84a5-bc0846fdb2e2.png)

**Comment by xingchun-chen** [comment]
1.You need to offline the workflow before you can edit the workflow information
2.The worker group is the first one by default, you can create a new workflow to check whether the worker group default values are correct

**Comment by glxfeng** [comment]
> 1.You need to offline the workflow before you can edit the workflow information
> 2.The worker group is the first one by default, you can create a new workflow to check whether the worker group default values are correct
> 3.The console checks which is the first worker group returned by the /worker-group/all-groups interface


我不是要编辑作业，只是想手动执行作业。
但是执行作业时不能选择工作组，必须先下线工作流再执行才能选择工作组，这显然是不合理。
最重要的是，执行作业时默认的那个工作组，不是我为这个作业配置的那个。
I don‘t want to edit the job, I'm just want to execute it manually.
However, when executing a job, I can't select a workgroup. I must offline the workflow before I can select a workgroup. This is obviously unreasonable.
The most important thing is that the default workgroup when executing the job is not the one I configured for this job.

**Comment by xingchun-chen** [comment]
There can be multiple tasks under a workflow, and each task can be configured with different worker groups. In this case, how can the default worker grouping during workflow execution be consistent with the tasks?
一个工作流下面可以有多个任务，每个任务可以配置不同的worker分组，那这种情况下，工作流执行时的默认worker分组怎么保持和任务一致呢

**Comment by glxfeng** [comment]
> There can be multiple tasks under a workflow, and each task can be configured with different worker groups. In this case, how can the default worker grouping during workflow execution be consistent with the tasks?
> 一个工作流下面可以有多个任务，每个任务可以配置不同的worker分组，那这种情况下，工作流执行时的默认worker分组怎么保持和任务一致呢

我明白了，执行时候不管选择哪个工作组，最终都会被作业实际配置的那个工作组执行。谢谢您的解答。
 I understand, no matter which workgroup is selected when executing, it will be executed by the workgroup configured by the job.
Thank you for your answer.
