### ISSUE TITLE
[Improvement][ALL] Remove some un-used code and code-review

### ISSUE THREAD

**Issue by zwOvO** [apache/incubator-dolphinscheduler#3639]
**Describe the question**
remove some un-used code

**What are the current deficiencies and the benefits of improvement**
- Reduce project storage space.

**Which version of DolphinScheduler:**
 -[dev|1.3.2]

**Comment by dailidong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/3640 solved this issue
