### ISSUE TITLE
[VOTE]next version what to do

### ISSUE THREAD

**Issue by CalvinKirs** [apache/incubator-dolphinscheduler#3641]
Hi, everybody. In the email about what we need to do in the next version, we collected the following work. We hope that everyone can discuss the priority of related issues and the specific implementation of the plan. Each job is accompanied by related proposers and advisers. If you are interested, you can openly communicate with them. (You can communicate via email for a certain sub-item)

1:Api Server communicate for Master instand of scan command table( @qiaozhanwei  )

2:Alert module support service for other service invoke( @qiaozhanwei  @gaojun2048  )

3:SQL task support multiple sqls and parameter passing optimization(we should add a new task type, such as SqlScript @gabrywu  @qiaozhanwei  @yangyichao-mango  )[need discuss]

4:Support passing parameters between tasks ( @qiaozhanwei  )

5:Sort out and simplify the license process

6:Focus on fixing bugs base on the branch some new features can be released in 1.4.0_release base on branch 'dev'.(@gabrywu )

7:Expect dolphinScheduler to provide SSO to facilitate seamless integration with existing platforms.( @yangyichao-mango  )

8:SPI requirements are collected and developed. We need to have a discussion to find out the modules that currently need SPI most( @gaojun2048  @lenboo @CalvinKirs )

9:Worker Poll slot(@yangyichao-mango )

10:state machine processor of worker and master optimize( @yangyichao-mango )

11:How to do project migration.Including workflow definitions, resource files, and data sources.The development environment and the production environment are two sets of environments.(@BoYiZhang)

12:Adding a batch stop on the process instance page(@xingchun-chen )

13:Many new functions have been added in the dev branch and some issues have been solved. It is recommended to merge them into the next version(@all)

You can list the digital subscripts of the functions you expect, and then reply directly to the email. We will determine the main work content for the next issue based on your opinions. We look forward to your suggestions. thanks

Voting email address：https://lists.apache.org/thread.html/r931baa57099e6ddd639d1b8c7a33c3e3b8d03352fb0de82b45a7dfb3%40%3Cdev.dolphinscheduler.apache.org%3E

Best  wishes！
CalvinKirs

**Comment by CalvinKirs** [comment]
2:Alert module support service for other service invoke( @qiaozhanwei @gaojun2048 )

3:SQL task support multiple sqls and parameter passing optimization(we should add a new task type, such as SqlScript @gabrywu @qiaozhanwei @yangyichao-mango )[need discuss]

6:Focus on fixing bugs base on the branch some new features can be released in 1.4.0_release base on branch 'dev'.(@gabrywu )

5:Sort out and simplify the license process(@CalvinKirs )

8:SPI requirements are collected and developed. We need to have a discussion to find out the modules that currently need SPI most( @gaojun2048 @lenboo @CalvinKirs )

11:How to do project migration.Including workflow definitions, resource files, and data sources.The development environment and the production environment are two sets of environments.(@BoYiZhang)

**Comment by gaojun2048** [comment]
Is everyone doing the issue : **Alert module support service for other service invoke**  ? I don`t found the issue about it.
