### ISSUE TITLE
[Question] The failed strategy did not take effect

### ISSUE THREAD

**Issue by dykw** [apache/incubator-dolphinscheduler#3642]
**Describe the question**
一个工作流里面设置了三个shell节点 第一个节点可以执行不报错 后面两个节点必会报错，工作流执行是选择失败策略为继续，但是执行到第二个节点报错之后 ，第三个节点就没有继续执行了

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
The failure strategy is for parallel tasks，For example：
1. task A and task B are in parallel, task C and task A are in series, and task D and task B are in series.
2. After task A fails, task C will fail, but tasks B and D can continue to execute
失败策略是针对并行任务的，例如：
1.任务A和任务B是并行关系，任务C和任务A是串联，任务D和任务B是串联关系
2.任务A失败后，任务C会失败，但任务B、D可以继续执行

**Comment by dykw** [comment]
thx for your answer
