### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by pptfz** [apache/incubator-dolphinscheduler#3672]
[官方文档](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/standalone-deployment.html) 安装步骤中1.5 : 数据库初始化

有一个操作是如下
创建表和导入基础数据
修改 conf 目录下 application-dao.properties 中的下列配置
vi conf/application-dao.properties 

但是下载的包无论是源码还是二进制都没有这个文件，是安装文档有问题吗？

安装版本 1.2 1.3 都是这个问题

**Comment by zhuangchong** [comment]
vi conf/datasource.properties

**Comment by pptfz** [comment]
嗯嗯 多谢回复 我正好是自己刚找到这个文件 谢谢

**Comment by pptfz** [comment]
还是安装问题，第1.6 : 修改运行参数
修改一键部署脚本 install.sh中的各参数，特别注意以下参数的配置   这一步中第所有内容是全部粘贴进这个install.sh就可以了吧？

结果运行报错一堆
```
ssh: Could not resolve hostname ds4: Name or service not known
ssh: Could not resolve hostname ds4: Name or service not known
ds1 worker server is starting
ssh: Could not resolve hostname ds1: Name or service not known
ssh: Could not resolve hostname ds1: Name or service not known
ds3 worker server is starting
ssh: Could not resolve hostname ds3: Name or service not known
ssh: Could not resolve hostname ds3: Name or service not known
ds2 worker server is starting
ssh: Could not resolve hostname ds2: Name or service not known
ssh: Could not resolve hostname ds2: Name or service not known
ssh: Could not resolve hostname ds3: Name or service not known
ds1 worker server is starting
ssh: Could not resolve hostname ds1: Name or service not known
```

看了半天实在是搞不懂安装逻辑，麻烦指导一下，如果后续安装成功并且踩坑完成我可以分享一下安装踩坑过程方便其他安装者，谢谢

**Comment by zhuangchong** [comment]
hosts 是否配置？ssh 时候失败不到ds1/ds2/ds3/ds4域名，可以手动先ssh user@ds1 试试能连接么

**Comment by pptfz** [comment]
单机部署 手动修改了 hosts文件  IP:ds1 ds2 ds3 ds4 ds5 这个问题解决

下一个问题
前端部署中 2.1 自动化部署 
install-dolphinscheduler-ui.sh  没有这个脚本，执行的是install.sh，执行完成后并没有安装nginx，需要手动安装nginx
这个是新版修改了安装脚本吧？  这个最新文档貌似不是最新的啊

**Comment by pptfz** [comment]
再次遇到问题 文档中nginx配置文件问题

前端解压缩后并改名如下`dolphinscheduler-ui`，这个目录中内容如下，并没有官方文档中说的`前端解压的dist目录地址`，尝试改成`ui`目录也不行
```
drwxr-xr-x 2 root root    79 Sep  5 09:19 bin
drwxr-xr-x 6 root root  4096 Sep  5 10:19 conf
-rw-rw-r-- 1 1002 1002   563 Aug 18 14:41 DISCLAIMER
-rw-rw-r-- 1 1002 1002  4663 Aug 18 14:42 install.sh
drwxr-xr-x 2 root root 12288 Sep  5 09:19 lib
-rw-rw-r-- 1 1002 1002 38537 Aug 18 14:42 LICENSE
drwxrwxr-x 3 1002 1002 12288 Aug 18 14:42 licenses
-rw-rw-r-- 1 1002 1002 70942 Aug 18 14:42 NOTICE
drwxr-xr-x 2 root root   218 Sep  5 09:19 script
drwxr-xr-x 4 root root   125 Sep  5 09:19 sql
drwxr-xr-x 8 root root   113 Sep  5 09:19 ui
```
可否提供最新配置文件，目前按照 [官方文档](https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/standalone-deployment.html) 这个地址中的文档安装确认是无法安装成功的，能否提供最新版的安装文档，感觉文档和实际相差太多了，修改了太多内容，不是开发者应该很难搞清整个逻辑的

**Comment by pptfz** [comment]
安装遇到了太多问题，可否提供一下qq群或者其他联系方式，按照官方文档是无法完成安装的
| |
pptfzo
|
|
pptfzo@163.com
|
签名由网易邮箱大师定制


在2020年09月4日 18:55，zhuangchong<notifications@github.com> 写道：

hosts 是否配置？ssh 时候失败不到ds1/ds2/ds3/ds4域名，可以手动先ssh user@ds1 试试能连接么

**Comment by zhuangchong** [comment]
推荐使用1.3.1或1.3.2 版本，1.2.1版本文档存在很多未更新的地方。1.2.1版本之后可以不用安装nginx，直接访问，地址http:[api-server.ip]:12345/dolphinscheduler 

dolphinscheduler社区有微信群并也推荐关注‘海豚调度’公众号，第一时间了解DS的相关消息，请按此方式加群 
![image](https://user-images.githubusercontent.com/37063904/92341313-e222c180-f0ef-11ea-8423-6c72ddfd8c76.png)

**Comment by pptfz** [comment]
好的 谢谢回复


| |
pptfzo
|
|
pptfzo@163.com
|
签名由网易邮箱大师定制


在2020年09月7日 09:53，zhuangchong<notifications@github.com> 写道：

推荐使用1.3.1或1.3.2 版本，1.2.1版本文档存在很多未更新的地方。1.2.1版本之后可以不用安装nginx，直接访问，地址http:[api-server.ip]:12345/dolphinscheduler

dolphinscheduler社区有微信群并也推荐关注‘海豚调度’公众号，第一时间了解DS的相关消息，请按此方式加群

**Comment by marswon** [comment]
vi conf/datasource.properties

这个文件在哪啊？找不到呀 也没有conf这个目录呀，1.3.2

**Comment by marswon** [comment]
/home/escheduler/incubator-dolphinscheduler-1.3.2/conf/config/install_config.conf: 没有那个文件或目录

**Comment by lukairui** [comment]
《一分钟安装DolphinScheduler并上手体验》
https://mp.weixin.qq.com/s/X2Edda3CIUsALh5MNDFVSA
自己写的一篇文章，把自己的踩坑经验变成自动安装脚本了。
后边小伙伴推荐阅读一下。
附带视频操作。

**Comment by pptfz** [comment]
@lukairui 👍

**Comment by marswon** [comment]
> 《一分钟安装DolphinScheduler并上手体验》
> https://mp.weixin.qq.com/s/X2Edda3CIUsALh5MNDFVSA
> 自己写的一篇文章，把自己的踩坑经验变成自动安装脚本了。
> 后边小伙伴推荐阅读一下。
> 附带视频操作。

安装是成功了，貌似任务上线会报任务调度失败，是我操作有问题还是？

**Comment by dailidong** [comment]
Please check the runtime log under logs directory,  MasterServer/WorkerServer/ApiServer

for chinese user, we have user wechat group , please add wechat:
![龙飞](https://user-images.githubusercontent.com/15833811/95536223-1229f100-0a1d-11eb-947a-fc8e05cb04b1.jpeg)
 

By the way, As a global project, English is needed, please update/add title and desc in English, thx
