### ISSUE TITLE
create db2 connection error

### ISSUE THREAD

**Issue by ifeng2025** [apache/incubator-dolphinscheduler#3673]
Version : 1.3.1
i try to create a db2 connection ,  
whether to fill in the JDBC link parameters or not, it always fails
and i don't found the log ,  can't exclude the error

![image](https://user-images.githubusercontent.com/34772948/92229069-7b2cbf00-eedb-11ea-9c8c-567e99e221cc.png)

**Comment by zhuangchong** [comment]
1. Whether the db2 driver is placed in the lib directory, and restart the dolphinscheduler api/master/worker service
2. Test connection The log is generated in the api service, see if you can find it

---
1.db2 driver 是否放到lib 目录下，并重启dolphinscheduler api/master/worker 服务
2.测试连接 日志是在api 服务生成的，看能不能找到

**Comment by ifeng2025** [comment]
> 1. db2 驱动程序是否放置在 lib 目录中，并重新启动海豚计划 api/主/辅助服务
> 2. 测试连接 日志在 api 服务中生成，查看能否找到它
> 
> 1.db2 驱动程序 [利布]，]，]，\DOLPHinscheduler
> api /master/worker\ 2.\ api\，\，\


1) i  configured the DB2 driver in dolphinscheduler-bin/lib/db2jcc4.jar  and  restart-all , but it doesn't work.
2)  dolphinscheduler-api-server.2020-09-04_19.0.log do not show the problem , it was filled like this 
```
[INFO] 2020-09-04 19:59:52.683 org.apache.dolphinscheduler.api.controller.TaskInstanceController:[98] - query task instance list, project name:test,process instance:0, search value:,task name:null, executor name: ,state type:null, host:, start:, end:
```

**Comment by pptfz** [comment]
@ifeng2025  你好，你按照官方文档已经搭建好了吗？ 如果有自己的安装文档的话可否提供一下，官方文档中的坑太多了，现在按照文档确认是无法安装成功的

**Comment by ifeng2025** [comment]
> @ifeng2025 你好，你按照官方文档已经搭建好了吗？ 如果有自己的安装文档的话可否提供一下，官方文档中的坑太多了，现在按照文档确认是无法安装成功的

推荐一篇博客
[CDH集群部署Dolphinscheduler1.3.1](https://blog.csdn.net/weixin_39381833/article/details/107774268)

**Comment by pptfz** [comment]
谢谢回复，我遇到了一堆问题，官方文档真的是太坑了，完全不能用，百度解决的
安装完成后打开一直是 Loading ...   并且官方提供的源码包中dockerfile也不能正确构建 不知道为什么会有4.3K的star

**Comment by pptfz** [comment]
按照文档执行  最后根本就没有12345这个端口 这个文档同样的坑 根本无法访问

**Comment by xingchun-chen** [comment]
Check whether there is db2jcc4.jar in the lib directory of the installation directory

**Comment by dailidong** [comment]
> 按照文档执行 最后根本就没有12345这个端口 这个文档同样的坑 根本无法访问

could you submit an issue to describe the problem you meet？

**Comment by dailidong** [comment]
when you click connection test ， you will see the  runtime log through dolphinscheduler-api.log
