### ISSUE TITLE
[Question][api] zookeeper monitor displays abnormal state 

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#3674]
version 1.2.0

the monitor displays abnormal state ，but ds works fine， how to fix it?

![image](https://user-images.githubusercontent.com/7474234/92229408-03ab5f80-eedc-11ea-825a-13c450f34179.png)

**Comment by pptfz** [comment]
竟然能安装成功？？？ nginx是怎么配置的？可否提供一下配置文件，现在按照官方文档无法安装成功，官方文档中soft/dolphinscheduler-ui/dist;      # 前端解压的dist目录地址(自行修改)  这个目录是不存在的

**Comment by xingchun-chen** [comment]
you can refer to issue #2547

**Comment by CalvinKirs** [comment]
Duplicate question.you can refer to issue #2547.
