### ISSUE TITLE
[Bug][API] Zookeeper does not start, printed logs have no error messages, Api services can start but cannot be accessed.

### ISSUE THREAD

**Issue by wen-qiang001** [apache/incubator-dolphinscheduler#3680]
Zookeeper does not start, printed logs have no error messages, Api services can start but cannot be accessed.
Zookeeper没有启动，打印的日志没有错误信息，Api服务能启动但是不能访问。

**Comment by yangyichao-mango** [comment]
Hi
Are you using DS Integrated ZK? If ZK does not start normally, apiserver cannot start normally.
Which version ds?
Please describe the context in detail.

---------

你是用的是ds内置的zk吗？zk没有正常启动的情况下，apiserver是不能正常启动的。
ds版本是什么？
请详细描述一下上下文。

**Comment by xingchun-chen** [comment]
please add the title description

**Comment by felix-thinkingdata** [comment]
There is no error because it has not been initialized yet. Service launches need to ensure that ZooKeeper is normal. Maybe I haven't timed out yet. When you run out of time, you get an error.

没有报错，因为还没初始化成功。服务启动需要保证zookeeper是正常的。可能还没有超时。超时的时候就会报错了。
