### ISSUE TITLE
[Question] where config worker group on ui page?

### ISSUE THREAD

**Issue by wuliulw** [apache/incubator-dolphinscheduler#3681]
有两台worker，请问创建worker分组的UI按钮在哪儿配置在哪儿谢谢？
![image](https://user-images.githubusercontent.com/14256084/92345058-a5a89300-f0fa-11ea-833b-470309733f0c.png)

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
1. vi ./conf/config/install_config.conf ,change the configuration of the cluster worker machine
![image](https://user-images.githubusercontent.com/55787491/92345357-a4c43100-f0fb-11ea-9644-3af0e45f94f5.png)
2.  vi ./conf/worker.properties，directly change the configuration of the worker machine
![image](https://user-images.githubusercontent.com/55787491/92345387-b574a700-f0fb-11ea-8bf7-f9c98cfbbd86.png)

**Comment by wuliulw** [comment]
thanks
