### ISSUE TITLE
[Improvement][service] ProcessService  method name meets naming convention.

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3686]
**Describe the question**
1.ProcessService .delCommandByid Change to delCommandById
2.ProcessService .queryUdfFunListByids Change to queryUdfFunListByIds

**Which version of DolphinScheduler:**
 -[dev]

**Comment by yangyichao-mango** [comment]
+1

**Comment by dailidong** [comment]
#3687 solved this
