### ISSUE TITLE
[Improvement][SQL optimization] Optimization of table building statements

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/incubator-dolphinscheduler#3688]
1. When executing MySQL table creation statement, it will report that the index length is not enough.
this will happen: Index column size too large. The maximum column size is 767 bytes.
2. The length of the t_ds_task_instance.app_link is not enough. When hive SQL is complex and yarn will start multiple applications

**Comment by JinyLeeChina** [comment]
I will fix it

**Comment by yangyichao-mango** [comment]
Which version mysql?

**Comment by dailidong** [comment]
PR #3689 fix this issue
