### ISSUE TITLE
[Improvement][COMMON-netUtils] 获取本机ip策略问题 Get the native IP policy problem 

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#3690]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**

When acquiring the native IP, the policy is the first valid IP, and the recommendation is that the Intranet IP take precedence.
The situation I met was that I got the IP of the external network, but the external network was strictly controlled and no port was opened, resulting in abnormal communication.

获取本机ip时，策略为第一个有效ip，建议是内网ip优先。我遇到的情况是，获取的是外网ip但是，外网管控严格没有开放端口，导致通信异常。

**Comment by keepmeup** [comment]
is this has been fixed

**Comment by CalvinKirs** [comment]
> Has the problem been fixed?

yeah
