### ISSUE TITLE
[Question] In which DS release version will Fastjson be replaced with Jackson?

### ISSUE THREAD

**Issue by xloya** [apache/incubator-dolphinscheduler#3698]
**Describe the question**
This month our company completely bans the use of Fastjson,so I want to know how long will Fastjson be replaced with Jackson?

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Additional context**
nothing.

**Requirement or improvement**
nothing.

**Comment by zhuangchong** [comment]
The dev branch has removed fastjson, use Jackson.

**Comment by xloya** [comment]
Yeah,I know it has been replaced with Jackson in dev branch.But you know,I can only use release version in company.

**Comment by dailidong** [comment]
dev branch changed a lot, you can send mail to dev@dolphinscheduler.apache.org to disscuss this topic

**Comment by xingchun-chen** [comment]
Thank you very much for your question. The question is already under planning. Please pay attention to the email  dev@dolphinscheduler.apache.org for specific details. It will be closed
