### ISSUE TITLE
[Bug][api] Resource file reupload does not overwrite the original file. This button is an invalid one

### ISSUE THREAD

**Issue by blue0305** [apache/incubator-dolphinscheduler#3702]
The re-upload of the resource file cannot overwrite the original file. This button is an invalid one, because the update time of the re-upload file is always unchanged, and the new resource file can only be added after deletion

**Comment by yangyichao-mango** [comment]
Which verison ds?

**Comment by blue0305** [comment]
1.3.2

**Comment by blue0305** [comment]
> Which verison ds?

verison : 1.3.2

**Comment by xingchun-chen** [comment]
I haven't reproduced your question. Does the popup pop up when you click "Re-upload"
![image](https://user-images.githubusercontent.com/55787491/92560516-260af780-f2a5-11ea-9be6-a6d442f7921a.png)

**Comment by blue0305** [comment]
> I haven't reproduced your question. Does the popup pop up when you click "Re-upload"
> ![image](https://user-images.githubusercontent.com/55787491/92560516-260af780-f2a5-11ea-9be6-a6d442f7921a.png)

A dialog will pop up, but you'll notice that the update time has not changed, indicating that the JAR has not been updated

**Comment by xingchun-chen** [comment]
My update time here has changed, are you sure to upload the file again
![image](https://user-images.githubusercontent.com/55787491/92673358-835a8380-f34d-11ea-88fe-bd6ac15ceb60.png)

**Comment by blue0305** [comment]
> My update time here has changed, are you sure to upload the file again
> ![image](https://user-images.githubusercontent.com/55787491/92673358-835a8380-f34d-11ea-88fe-bd6ac15ceb60.png)

不知道重新上传文件是否跟工作流的状态有关，但是我点击上传是不能够重新上传的，没有新上传文件的进度条，也不能更新上传文件的时间，jar包的执行内容也是没有变化的，所以我得出的结论是上传的按钮无法上传jar包，

**Comment by blue0305** [comment]
![image](https://user-images.githubusercontent.com/47100369/92686624-99c40780-f36c-11ea-975c-c222ac194f70.png)
当前线上资源文件大小为115kb，我重新上传了一个0kb的jar包，也是无法覆盖的

**Comment by xingchun-chen** [comment]
@lgcareer  When re-uploading the same file name, the file resource is not updated
