### ISSUE TITLE
[Question] support multi-queries in single sql transformation task

### ISSUE THREAD

**Issue by dengc367** [apache/incubator-dolphinscheduler#3710]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
I think in sql transformation task, multi-queries separated by `;` need supported in single sql transformation task, regardless of any driver or any connection. 
the SQLs parsed in the sql task can be executed in order, and when one SQL in the task failed, this task need fails too.

**Comment by zhuangchong** [comment]
It feels that the function you mentioned is very similar to the implementation of presto. Presto can implement mixed query of multiple data sources. DS has integrated Presto, you can try this.

---
感觉你说的功能，跟presto实现很像，presto可以实现多数据源混合查询，DS已经集成Presto,可以试试这个。

**Comment by dengc367** [comment]
@zhuangchong  it’s not that meaning. I said one sql task can contain several independent sql segments separated by semicolon, which can be executed in order. It’s not the presto scenario to solve inter-instance query.

**Comment by chenghm** [comment]
这个问题困扰了很久，不然一段sql要分成几段去执行，不是很方便

**Comment by zhuangchong** [comment]
> @zhuangchong it’s not that meaning. I said one sql task can contain several independent sql segments separated by semicolon, which can be executed in order. It’s not the presto scenario to solve inter-instance query.

Then I got it wrong, what you said will be prepared in the next version, currently you can use shell/python to call sql files

---
那我理解错了，你说的这个在下个版本准备做了，目前可以使用shell/python 调用sql 文件的方式

**Comment by chenghm** [comment]
使用shell/python调用sql，如果中间执行出错不能更新到任务实例状态

**Comment by dengc367** [comment]
This feature or enhancement can be promoted the priority.

**Comment by dengc367** [comment]
BTW, who are developing this issue(case) now? @zhuangchong

**Comment by zhuangchong** [comment]
> BTW, who are developing this issue(case) now? @zhuangchong

https://github.com/apache/incubator-dolphinscheduler/issues/3641

**Comment by liuzx8888** [comment]
@zhuangchong   I also need this feature  I have modified this feature locally, but I'm not sure if my change is reasonable. How can I discuss my ideas or give some reasonable suggestions。

**Comment by zhuangchong** [comment]
> @zhuangchong I also need this feature I have modified this feature locally, but I'm not sure if my change is reasonable. How can I discuss my ideas or give some reasonable suggestions。

you can send mail to dev@dolphinscheduler.apache.org to disscuss this topic

https://dolphinscheduler.apache.org/zh-cn/docs/development/subscribe.html

**Comment by liuzx8888** [comment]
@zhuangchong  I sent an email but there seems to be no feedback  =。=

**Comment by dengc367** [comment]
support multi-queries like  [redash#5100](https://github.com/getredash/redash/pull/5100)

**Comment by xingchun-chen** [comment]
it is the same as #3799
