### ISSUE TITLE
[Bug][api] Web logging is incomplete

### ISSUE THREAD

**Issue by blue0305** [apache/incubator-dolphinscheduler#3711]
![image](https://user-images.githubusercontent.com/47100369/92689381-810a2080-f371-11ea-9179-54c587039686.png)
This is a web page log, not as complete as the log below,
![image](https://user-images.githubusercontent.com/47100369/92689606-de05d680-f371-11ea-9d09-01393dd898ad.png)

**Comment by xingchun-chen** [comment]
which version?

**Comment by blue0305** [comment]
> which version?

1.3.2     Is there a group to discuss？for example：vx

**Comment by xingchun-chen** [comment]
昵称:龙飞, 微信ID:@dailidong66

**Comment by xingchun-chen** [comment]
Because the log can only load 1000 lines at a time, the remaining logs need to be pulled down to see, can you try it?

**Comment by blue0305** [comment]
> Because the log can only load 1000 lines at a time, the remaining logs need to be pulled down to see, can you try it?

I pulled it down. I can't show it

**Comment by dailidong** [comment]
you has downloaded the log file to your local path, but can't open it ?

> > Because the log can only load 1000 lines at a time, the remaining logs need to be pulled down to see, can you try it?
> 
> I pulled it down. I can't show it

**Comment by roger68** [comment]
Got the same problem in 1.3.1

**Comment by roger68** [comment]
I got cause of the problem, my google chrome version is too low,upgrade higher verison or use mac safari  the problem  is solved。

**Comment by CalvinKirs** [comment]
Maybe you can try the above method, this does not seem to be a DS bug
