### ISSUE TITLE
[Bug][api] The task resource could not be deleted

### ISSUE THREAD

**Issue by blue0305** [apache/incubator-dolphinscheduler#3719]
![image](https://user-images.githubusercontent.com/47100369/92851473-2da2db80-f420-11ea-8958-3fe9eae522e5.png)
If a resource in the resource center has been deleted, the deleted resource cannot be deleted from the task, and the entire task can only be deleted without the task being created

**Comment by xingchun-chen** [comment]
@break60 please fix it

**Comment by break60** [comment]
Just delete the prohibited attribute

**Comment by AhahaGe** [comment]
I suggest we should not delete resource in resource center if it has been used in task as it will cause some task schedule error.

**Comment by xingchun-chen** [comment]
There are 2 solutions to this problem:
Method 1: Delete the resource id that does not exist in the resourceList in the database t_ds_process_definition.process_definition_json
![image](https://user-images.githubusercontent.com/55787491/93562738-36178b00-f9b9-11ea-9679-df96393c390e.png)
Method 2: According to the pr above, change the front-end source code and recompile, replace the ui in the installation directory with the compiled ui
