### ISSUE TITLE
[Question]  dolphinscheduler  [mailbox  input is  illegal]

### ISSUE THREAD

**Issue by liuxiaoxiong** [apache/incubator-dolphinscheduler#3720]
hello, I am a noob user for this tool,  I install and find this problem,this is my company mail site  ,how I can fix this ?
<img width="544" alt="image" src="https://user-images.githubusercontent.com/25683936/92854061-29c48880-f423-11ea-9a15-67602eaf09b6.png">

中文：各位巨佬，小海豚不识别公司的邮箱后缀地址，这个有解决的办法吗？

**Comment by zhuangchong** [comment]
js mailbox verification problem

Source location：dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/definition/pages/list/_source/util.js

```
 /^([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/ // eslint-disable-line

```

change
```
 /^([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\-|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,}$/ // eslint-disable-line

```

I will submit
