### ISSUE TITLE
[Feature][Server] one worker server should support setting multi worker groups through UI

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#3730]
**Describe the feature**
in version 1.3.2, it supported one worker set multi worker groups through worker.properties 
I suggest worker group set/update through web UI not through worker.properties,  it will be easy to use , change worker.properties is not friendly

**Comment by zhuangchong** [comment]
+1

**Comment by yangyichao-mango** [comment]
+1，it may need the communication between api server and worker or master， or it can use DB, zk to implement.

If anyone has any idea about this feature, welcome to leave a message.

**Comment by chengshiwen** [comment]
Close by #5122, since the feature has been supported in next 1.3.6
