### ISSUE TITLE
sql task, can you add a semicolon and write multiple statements?

### ISSUE THREAD

**Issue by lingxingzhang** [apache/incubator-dolphinscheduler#3738]
Describe the question
My sql tasks usually have multiple sql, so I want DS to support separated by semicolons and support multiple sql tasks at the same time

Which version of DolphinScheduler:
-[1.3.1]

Additional context
nothing.

Requirement or improvement
nothing.

**Comment by zhuangchong** [comment]
This feature will be supported in the next version.

**Comment by lingxingzhang** [comment]
thanks!
