### ISSUE TITLE
flink任务启动不了

### ISSUE THREAD

**Issue by eyesmoons** [apache/incubator-dolphinscheduler#3744]
在创建flink任务时，报了以下错误，麻烦大神们帮忙看一下：
[INFO] 2020-09-15 09:22:27.627  - [taskAppId=TASK-1202-2704-11751]:[106] -  -> /tmp/dolphinscheduler/exec/process/822/1202/2704/11751/1202_2704_11751.command: line 7: flink: command not found

**Comment by zhuangchong** [comment]
1. Please confirm whether there is a flink client on the worker node
2. Please check if the dolphinscheduler-env.sh FLINK_HOME environment variable is configured

---
1.请在worker节点确认是否有flink 客户端
2.请检查dolphinscheduler-env.sh FLINK_HOME 环境变量是否配置

**Comment by eyesmoons** [comment]
有呢，部署了两台dolphinscheduler，都有flink 客户端。dolphinscheduler-env.sh FLINK_HOME也有配置。但是配置文件最后没有这一句：export PATH=$HADOOP_HOME/bin:$SPARK_HOME1/bin:$SPARK_HOME2/bin:$PYTHON_HOME:$JAVA_HOME/bin:$HIVE_HOME/bin:$PATH:$FLINK_HOME/bin:$PATH。spark程序可以运行，目前就是flink起不来。

**Comment by zhuangchong** [comment]
目前报的问题就是Flink 环境变量找不到，可以把你说的没有的那一句加上，添加到PATH环境变量中，你说的spark程序可以运行有可能你的系统级别或用户级别是有配置spark的环境变量的

**Comment by eyesmoons** [comment]
好的，谢谢~

**Comment by xingchun-chen** [comment]
Whether the problem has been solved, if it has been solved, please close it
