### ISSUE TITLE
[Bug][server] server get tasktype NPE exception

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3745]
**Describe the bug**

```
switch (EnumUtils.getEnum(TaskType.class,taskExecutionContext.getTaskType()))
```
When the task type does not exist in the enumeration class TaskType, EnumUtils.getEnum() returns null, and switch will report a null pointer exception

**Expected behavior**
Null processing of parameter values in switch

**Which version of Dolphin Scheduler:**
 -[dev]

---

**描述错误**
```
switch (EnumUtils.getEnum(TaskType.class,taskExecutionContext.getTaskType()))
```
当任务类型在枚举类中TaskType不存在时，EnumUtils.getEnum()返回null,switch 会报空指针异常

**预期行为**
switch 内参数值判空处理

**哪个版本的Dolphin Scheduler：**
  -[dev]

**Comment by yangyichao-mango** [comment]
+1
