### ISSUE TITLE
[Feature][server]  SqlTask should send notifications by alert server api

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3749]
sub task of https://github.com/apache/incubator-dolphinscheduler/issues/3049

**Comment by zhuangchong** [comment]
+1

**Comment by gaojun2048** [comment]
> +1

what do you mean ? No people doing at the feature now, do you want to work for it?

**Comment by zhuangchong** [comment]
OK，I can complete this task.

**Comment by gaojun2048** [comment]
> OK，I can complete this task.

This feature involves two issues. Can you complete both issues?

https://github.com/apache/incubator-dolphinscheduler/issues/3754 Alert module support service for other service invoke
https://github.com/apache/incubator-dolphinscheduler/issues/3749 SqlTask should send notifications by alert server api

**Comment by zhuangchong** [comment]
> > OK，I can complete this task.
> 
> This feature involves two issues. Can you complete both issues?
> 
> #3754 Alert module support service for other service invoke
> #3749 SqlTask should send notifications by alert server api

ok,I can

**Comment by yangyichao-mango** [comment]
> > > OK，I can complete this task.
> 
> > 
> 
> > This feature involves two issues. Can you complete both issues?
> 
> > 
> 
> > #3754 Alert module support service for other service invoke
> 
> > #3749 SqlTask should send notifications by alert server api
> 
> 
> 
> ok,I can

You can link your design in this issue first.

**Comment by zhangchunyang1024** [comment]
Sorry, guys. I'm busy recently. I don't have time to pay attention to the community. The contribution I wanted to make has not been completed. In order to promote the plug-in module, I hope other partners will continue
