### ISSUE TITLE
[Feature] Check License tool update for plugin design

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3750]
In the feature https://github.com/apache/incubator-dolphinscheduler/issues/3049 alert plugin`s dependency jar will be placed in the ${dolphinscheduler_install_dir}/lib/plugin/alert/xxx-plugin directory  . 

But now the check-License.sh tool can only check the ${dolphinscheduler_install_dir}/lib/xxx.jar files . 

So we need to modify the check-License.sh tool so that it can support the inspection of jars in the sub directory of lib/ .

**Comment by hsupu** [comment]
I'm doing this.

**Comment by gaojun2048** [comment]
> I'm doing this.

ok!

**Comment by gaojun2048** [comment]
The pr is merged, and this issue can close.
