### ISSUE TITLE
[Bug][dolphinscheduler-server] Time custom parameters conver error

### ISSUE THREAD

**Issue by opcooc** [apache/incubator-dolphinscheduler#3751]
`current time : 2020-09-15 15:15:13`
`custom parameter : echo $[yyyy-MM-dd HH:mm:ss-1/24]`
`But the result is : 2020-09-15 15:15:13-54913523000000/24`
`The desired result is : 2020-09-15 14:15:13`

**Comment by opcooc** [comment]
It seems to appear directly in the shell task

**Comment by xingchun-chen** [comment]
Which version? 
can see the screenshot of your node settings, because my test is OK
![image](https://user-images.githubusercontent.com/55787491/93283072-594c0a00-f802-11ea-9e99-afb1c67022e4.png)
![image](https://user-images.githubusercontent.com/55787491/93283105-69fc8000-f802-11ea-862f-0b815b78ee6e.png)

**Comment by opcooc** [comment]
![image](https://user-images.githubusercontent.com/34977303/93283297-d8d9d900-f802-11ea-8599-2e0248553bbe.png)
![image](https://user-images.githubusercontent.com/34977303/93283305-dbd4c980-f802-11ea-8579-a4ecea75cf60.png)

**Comment by opcooc** [comment]
> Which version?
> can see the screenshot of your node settings, because my test is OK
> ![image](https://user-images.githubusercontent.com/55787491/93283072-594c0a00-f802-11ea-9e99-afb1c67022e4.png)
> ![image](https://user-images.githubusercontent.com/55787491/93283105-69fc8000-f802-11ea-862f-0b815b78ee6e.png)

I use it like this, no problem on datax ！！！

**Comment by opcooc** [comment]
> Which version?
> can see the screenshot of your node settings, because my test is OK
> ![image](https://user-images.githubusercontent.com/55787491/93283072-594c0a00-f802-11ea-9e99-afb1c67022e4.png)
> ![image](https://user-images.githubusercontent.com/55787491/93283105-69fc8000-f802-11ea-862f-0b815b78ee6e.png)

![image](https://user-images.githubusercontent.com/34977303/93283297-d8d9d900-f802-11ea-8599-2e0248553bbe.png)
![image](https://user-images.githubusercontent.com/34977303/93283305-dbd4c980-f802-11ea-8579-a4ecea75cf60.png)

**Comment by xingchun-chen** [comment]
'N' needs to be replaced with numbers 1, 2, 3......

![image](https://user-images.githubusercontent.com/55787491/93283624-7cc38480-f803-11ea-9c5c-9a04fe529cf3.png)

**Comment by opcooc** [comment]
Haha forgot to add it, sorry, dizzy
