### ISSUE TITLE
[Feature][Alert] Alert module support service for other service invoke

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3754]
This is a sub issue of https://github.com/apache/incubator-dolphinscheduler/issues/3049
In this feature , Alert server is a message notification service , email and wechat is a plugin of this service . If you want send email message you can create an instance of email plugin in the alert group and then you can select the alert group in SqlTask . SqlTask can call the alert server api with this alert group arrguement to send the message.

So we need alert api to support other service invoke. 

Now the alert service sends alarms abnormally by periodically scanning the records in table t_ds_alert. It is asynchronous. 

In the SqlTask task case, the task need send message synchronous and the final running status of this task depends on whether the message is sent successfully. So the alert api need send messages synchronously.

**the params of alert api :**

* **alert group id** : requied, One or more alert plugin instances are associated with an alert group, and these alert plugin instances will be called in turn when sending a message.
* **title** : requied, the title of this alert message.
* **content**: requied, the content of this alert message.

**Comment by hermeshephaestus** [comment]
OK, I have read dolphinscheduler-alert's code, i think it can reference dubbo's design, and the core class EmailAlertPlugin has serious coupling, it can be optimized. I can complete this future. @gaojun2048

**Comment by gaojun2048** [comment]
> OK, I have read dolphinscheduler-alert's code, i think it can reference dubbo's design, and the core class EmailAlertPlugin has serious coupling, it can be optimized. I can complete this future. @gaojun2048

That's great. Can you create an issue first? Describe your idea, and then you can start.

**Comment by hermeshephaestus** [comment]
OK, I will create an  issue soon and show my design ideas in the mail. @gaojun2048

**Comment by gaojun2048** [comment]
> OK, I will create an issue soon and show my design ideas in the mail. @gaojun2048

Hi, What branch are you read about the code of dolphinscheduler-alert?
We have redesigned the code of dolphinscheduler-alert, under this branch, you can look at it again.
https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design

**Comment by gaojun2048** [comment]
Hi All, I have created a branch https://github.com/apache/incubator-dolphinscheduler/tree/alert_plugin_design to work on this big feature.

**Comment by hermeshephaestus** [comment]
Good job! I will have a look at the branch /tree/alert_plugin_design.

**Comment by CalvinKirs** [comment]
close by #3754
