### ISSUE TITLE
datax节点数据源就支持四种吗？

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/incubator-dolphinscheduler#3755]
1.3.2版本datax节点就支持四种节点，是本来就是这样，还是我前端有问题，我看官网文档没有介绍
![image](https://user-images.githubusercontent.com/46189785/93296964-eacb7400-f822-11ea-92e4-a42a580a6724.png)

**Comment by sandun-zhang** [comment]
你可以尝试，勾选datax节点中的自定义模板，写json代码，它会根据你配置信息中的datax环境变量去找驱动jar包，执行代码

**Comment by zhanghaicheng1** [comment]
收到！谢谢你的回复，我去试一下

**Comment by zhanghaicheng1** [comment]
已经可以了，谢谢

**Comment by sandun-zhang** [comment]
客气





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 中午11:12
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"July"<1072785335@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] datax节点数据源就支持四种吗？ (#3755)





 
已经可以了，谢谢
