### ISSUE TITLE
[Improvement][Module Name] API server Mysql driver configuration

### ISSUE THREAD

**Issue by ly3too** [apache/incubator-dolphinscheduler#3756]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
1. spring-boot support mysql connection off the shelf. you don't need to install mysql driver mannually and specify the driver class.
2. spring-boot manages the dependencies' version automatically. No need to specify lots of dependency version, which may lead to version conflict

**What are the current deficiencies and the benefits of improvement**
1. if you use mysql driver, just configure datasoure.properities like so:
```
# spring.datasource.driver-class-name=com.mysql.jdbc.Driver No need to specify
spring.datasource.url=jdbc:mysql://host:3306/dolphinscheduler?characterEncoding=UTF-8&allowMultiQueries=true
spring.datasource.username=user
spring.datasource.password=pass
```
change the dependency config to 
```
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
```
2. import spring-boot dependencies to top pom, you can save lots of spring related depency management
```
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Describe alternatives you've considered**
No

**Comment by CalvinKirs** [comment]
Sorry, your idea sounds great. This is what we considered at the beginning, but the mysql license is limited, so we can't do this.
