### ISSUE TITLE
How to pass the body and authorization parameters when the HTTP node calls the interface through the post method?

### ISSUE THREAD

**Issue by sandun-zhang** [apache/incubator-dolphinscheduler#3757]

**Comment by zhuangchong** [comment]
1. The body is selected in the request parameters, the page is in the form of key and value, and the background will be processed into json
![image](https://user-images.githubusercontent.com/37063904/93423446-8ffc5000-f8e8-11ea-91eb-0028a350eaea.png)
2.Authorization parameter can try to see if it can be put in headers

---
1.body在请求参数里面选择，页面通过key,value形式，后台会处理成json
![image](https://user-images.githubusercontent.com/37063904/93423446-8ffc5000-f8e8-11ea-91eb-0028a350eaea.png)

2.Authorization 参数可以试一下是否可以放到headers里面

**Comment by sandun-zhang** [comment]
感谢您的回答，我尝试过这样写参数，任务可以成功运行，但获取到的返回信息是null，可能是功能不够完善

**Comment by xingchun-chen** [comment]
please update  the title in English

**Comment by xingchun-chen** [comment]
Need to add header：Content-Type: application/json;charset=utf-8
![image](https://user-images.githubusercontent.com/55787491/93545226-7e6f8280-f992-11ea-9bb9-9a5e8f1ce6de.png)
![image](https://user-images.githubusercontent.com/55787491/93545272-97783380-f992-11ea-9310-57aea3fb4411.png)

**Comment by sandun-zhang** [comment]
thanks,I've added this parameter, but the problem is that I don't know how to pass a body parameter in JSON format with an array





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 上午9:38
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"July"<1072785335@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] http节点通过post方法调用接口，怎么传body和Authorization参数？ (#3757)





 
Need to add header：Content-Type: application/json;charset=utf-8
