### ISSUE TITLE
The script uploaded by hdfs shows a null pointer when running！！！

### ISSUE THREAD

**Issue by zhanghaicheng1** [apache/incubator-dolphinscheduler#3758]
登录用户租户：hdfs；
Hadoop上面文件权限hdfs
脚本运行提示空指针
![image](https://user-images.githubusercontent.com/46189785/93415766-df398500-f8d6-11ea-9698-6920957ef392.png)
请教一下排查的思路

**Comment by zhuangchong** [comment]
Which version

**Comment by zhanghaicheng1** [comment]
1.3.2

**Comment by huanghaofan** [comment]
配置问题. 
如果单纯做上传|下载操作的话，你需要检查两个配置：
1，master端 是否已放置core-site.xml, hdfs-site.xml两个配置文件
2.   master端 检查common.properties文件的下方配置，指定HDFS
# resource upload startup type : HDFS,S3,NONE
resource.storage.type=HDFS

**Comment by zhanghaicheng1** [comment]
谢谢您的回复，这两个注意项这边我都检查了；
![image](https://user-images.githubusercontent.com/46189785/93440440-fe014100-f901-11ea-8e4b-c1912f7da3ce.png)
![image](https://user-images.githubusercontent.com/46189785/93442596-a3b4b000-f902-11ea-9033-6f27ebc54ca0.png)
不太清楚哪里配置的有没有问题。

**Comment by xingchun-chen** [comment]
please update title in English

**Comment by lgcareer** [comment]
I saw your configuration `fs.defaultFS=hdfs://192.168.201.83:8020`,If you expect to use the hadoop ha,please change this.You can check the value of `fs.defaultFS` in the core-site .xml and hdfs-site.xml

**Comment by zhanghaicheng1** [comment]
I checked and found that the fs.defaultFS configuration item is consistent with the configuration item in the core.site.xml file.

**Comment by zhanghaicheng1** [comment]
The null pointer problem has been resolved。。。tks！
