### ISSUE TITLE
[Improvement][Document] database initialize

### ISSUE THREAD

**Issue by switlen** [apache/incubator-dolphinscheduler#3766]
when i use  quick start to install dolphinscheduler at database initial phase,its better to sign the specifica or recommend mysql version,if mysql version is less than 5.7,some create table sql will not be executed correctly,and some funcations will not work, and  i should update mysql system variables(like innodb_large_prefix,innodb_file_format,innodb_file_format_max) to make it work, or i should to upgrade my mysql version,so its better to declare at quick start,TKS

 -[1.3.2-release]

**Comment by zhuangchong** [comment]
+1
Very good advice

**Comment by zhuangchong** [comment]
Welcome to submit PR changes on the document branch
https://github.com/apache/incubator-dolphinscheduler-website

**Comment by CalvinKirs** [comment]
If you are interested and want to complete it, please leave a message below

**Comment by c-f-cooper** [comment]
hi,I‘d like to fix this document,please assigen to me!

**Comment by CalvinKirs** [comment]
> hi,I‘d like to fix this document,please assigen to me!

Great, looking forward to your PR submission

**Comment by c-f-cooper** [comment]
> > hi,I‘d like to fix this document,please assigen to me!
> 
> Great, looking forward to your PR submission

https://github.com/apache/incubator-dolphinscheduler-website/pull/220

**Comment by c-f-cooper** [comment]
> > > hi,I‘d like to fix this document,please assigen to me!
> > 
> > 
> > Great, looking forward to your PR submission
> 
> [apache/incubator-dolphinscheduler-website#220](https://github.com/apache/incubator-dolphinscheduler-website/pull/220)


 New PR
[DS-3766][docs] Specify MySQL version when database initialize #222

**Comment by CalvinKirs** [comment]
close by apache/incubator-dolphinscheduler-website#222
