### ISSUE TITLE
[Improvement][api] Task instance supports query by workflow instance name

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3767]
**Describe the question**
Task instance supports query by workflow instance name

**What are the current deficiencies and the benefits of improvement**
At present, when there are many instances on the task instance page, it is not convenient to find a certain workflow instance

After improvement, you can query according to the workflow instance name on the task instance page

**Which version of DolphinScheduler:**
 -[dev]

I will fix this problem

---
**描述问题**
任务实例支持按工作流实例名查询

**目前的不足之处和改进的好处**
目前在任务实例页面存在很多实例的时候，查找某一个工作流实例很不方便

改进后可以在任务实例页面根据工作流实例名查询

**哪个版本的DolphinScheduler：**
  -[dev]

我将修复这个问题

**Comment by xingchun-chen** [comment]
good

**Comment by zhuangchong** [comment]
done.
