### ISSUE TITLE
[Question] can not login when first install

### ISSUE THREAD

**Issue by liuzx8888** [apache/incubator-dolphinscheduler#3777]
**Describe the question**
When I first execute install.sh and login to dolphinscheduler, the login page cannot be loaded normally; as shown in the figure:
![image](https://user-images.githubusercontent.com/10862577/93743621-f05dfb00-fc22-11ea-9f3b-f856a3acd82a.png)

After the source code is recompiled, visit the api ui and use login api
![image](https://user-images.githubusercontent.com/10862577/93743773-36b35a00-fc23-11ea-9b6a-edecdb61ae17.png)

then  login to dolphinscheduler  is  normal,

**Which version of DolphinScheduler:**
 -[1.3.2]

**Comment by switlen** [comment]
same problem,login success but is always redirect to login page!

**Comment by zhuangchong** [comment]
Take a look at the api log and see that the front-end error is that the back-end get-user-info method is not authorized.

---
看一下api 日志,看前端错误是后端get-user-info方法未授权

**Comment by liuzx8888** [comment]
@zhuangchong   i had upload the log ,you can anaysis it
[dolphinscheduler-api-server.2020-09-18_17.0.log](https://github.com/apache/incubator-dolphinscheduler/files/5259639/dolphinscheduler-api-server.2020-09-18_17.0.log)

**Comment by AhahaGe** [comment]
swagger 报错不影响啊，而且只是warn级别

**Comment by liuzx8888** [comment]
@AhahaGe 第一次部署登录页面怎么都出不来如上面的图那样，用swagger 测试下就是成功的，第一次登入要去检测 sessionid，空的就无法登陆？我用API 的测试了下生成了sessionid，才能正常的登陆。现在是第一次为什么出不来需要不知道怎么定位问题。

**Comment by switlen** [comment]
> @AhahaGe 第一次部署登录页面怎么都出不来如上面的图那样，用swagger 测试下就是成功的，第一次登入要去检测 sessionid，空的就无法登陆？我用API 的测试了下生成了sessionid，才能正常的登陆。现在是第一次为什么出不来需要不知道怎么定位问题。

i still login success but can't go to manage page,api log show me login success,and session generate and save in db success both,every login completed i should clear browser Local storage,Session storage,Cookies manually to go to manage page, so i think there has a problem!

**Comment by xingchun-chen** [comment]
Has the problem been resolved?
