### ISSUE TITLE
[Feature][Module Name] csrf protection

### ISSUE THREAD

**Issue by ly3too** [apache/incubator-dolphinscheduler#3779]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the feature**
csrf protection needed to protect sesitive requests !!!

**Is your feature request related to a problem? Please describe.**
ds has no csrf protection. a simple csrf attach can cause serious problem, e.g. deleting of user account.

**Describe the solution you'd like**
spring-security is a simple solution.

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by CalvinKirs** [comment]
In my opinion, we don’t seem to need such a complicated design (spring-security)

**Comment by CalvinKirs** [comment]
I will close it, if you have a better idea, you can reopen it
