### ISSUE TITLE
[Bug][API] save work group 

### ISSUE THREAD

**Issue by switlen** [apache/incubator-dolphinscheduler#3783]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
 save work group failure ,request 404 not found, cannot find /worker-group/save ,its the api is deleted in version of 1.3.2!

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Security/work group manage/create worker group
2. add new worker group
3. request 404 not found

**Expected behavior**
save worker group success!
**Screenshots**
![image](https://user-images.githubusercontent.com/31364496/93750553-3c626d00-fc2e-11ea-83da-e4944ac693ff.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Requirement or improvement**
- add save worker group api

**Comment by xingchun-chen** [comment]
The 1.3.2 version does not support the creation of worker groups, and the worker group is read from zk. you can refer to issue #3628

**Comment by AhahaGe** [comment]
Please clear browser cache and refresh this page to check that you should not see the create worker group button.

**Comment by AhahaGe** [comment]
![Uploading image.png…]()

**Comment by switlen** [comment]
> The 1.3.2 version does not create to worker groups in web page, and the worker group is read from zk. you can refer to issue #3628

tks，i will read doc carefully!

**Comment by AhahaGe** [comment]
Please close this issue after problem solved.

**Comment by switlen** [comment]
> Please clear browser cache and refresh this page to check that you should not see the create worker group button.

it doesn't work, i still see the create button!you can try it.

**Comment by switlen** [comment]
> The 1.3.2 version does not create to worker groups in web page, and the worker group is read from zk. you can refer to issue #3628

int the quick start of 1.3.2,why suggest user to create worker group in web page, whether it should be removed in next version!

**Comment by xingchun-chen** [comment]
creating worker groups  through web page that mentioned  in  the issue  #3730
