### ISSUE TITLE
dolphinscheduler调度spark和flink都无法正常找到 SPAKRK_HOME 和FLINK_HOME下的路径，而是去/bin目录下找

### ISSUE THREAD

**Issue by when520** [apache/incubator-dolphinscheduler#3785]
version:1.3.1
dolphinscheduler调度spark和flink都无法正常找到 SPAKRK_HOME 和FLINK_HOME下的路径，而是去/bin目录下找

执行报错：
/data/dolphinscheduler/exec/process/1/2/4/4/2_4_4.command: source: not found
/data/dolphinscheduler/exec/process/1/1/1/1/1_1_1.command: 5: /data/dolphinscheduler/exec/process/1/1/1/1/1_1_1.command: /bin/spark-submit: not found

本地的运行环境配置：
export HADOOP_HOME=/usr/hdp/current/hadoop-client
export HADOOP_CONF_DIR=/etc/hadoop/conf
#export SPARK_HOME1=/opt/soft/spark1
export SPARK_HOME2=/usr/hdp/current/spark2-client
#export PYTHON_HOME=/opt/soft/python
export JAVA_HOME=/usr/lib/jdk1.8
export HIVE_HOME=/usr/hdp/current/hive-client
export FLINK_HOME=/opt/flink1.11
#export DATAX_HOME=/opt/soft/datax/bin/datax.py

export PATH=$HADOOP_HOME/bin:$SPARK_HOME1/bin:$SPARK_HOME2/bin:$PYTHON_HOME:$JAVA_HOME/bin:$HIVE_HOME/bin:$PATH:$FLINK_HOME/bin:$DATAX_HOME:$PATH

**Comment by felix-thinkingdata** [comment]
You need to modify this file    /conf/env/dolphinscheduler_env.sh

**Comment by when520** [comment]
已解决，是因为部署dolphinscheduler的环境是ubuntu18.04
系统默认使用dash，而不是bash
需要修改dash 为bash 

sudo ln -sf /bin/bash /bin/sh
ls -l /bin/sh 检查修改之后的环境状态
