### ISSUE TITLE
Api-server could not be started

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#3793]
[INFO] 2020-09-23 10:53:13.361 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-09-23 10:53:13.362 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-09-23 10:53:13.363 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-09-23 10:53:13.364 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[43] - add listener to zk path: /dolphinscheduler
[INFO] 2020-09-23 10:53:14.384 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2020-09-23 10:53:14.399 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2020-09-23 10:53:14.478 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-09-23 10:53:14.524 org.apache.dolphinscheduler.remote.NettyRemotingClient:[376] - netty client closed
[INFO] 2020-09-23 10:53:14.525 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed
[INFO] 2020-09-23 10:53:14.531 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-09-23 10:53:14.533 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@4b87074a{application,/dolphinscheduler,[file:///tmp/jetty-docbase.7667266662126961927.9200/, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}

**Comment by dailidong** [comment]
is this entire log for api server ？

**Comment by shiliquan** [comment]
部分

**Comment by dailidong** [comment]
please show entire log, I can't find problems from the log

**Comment by dailidong** [comment]
By the way, zookeeper service is started already?

**Comment by dailidong** [comment]
long time no feedback from user, I will close this issue temporarily
