### ISSUE TITLE
[Question] A code question about getting yarn task state

### ISSUE THREAD

**Issue by xloya** [apache/incubator-dolphinscheduler#3796]
Recently, I looked at the code of the job status on YARN after the job was submitted and got the job status on the YARN.When I saw incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java , I found a method named isSuccessOfYarnState(List<String> appIds).Why here is a list of appid?I think through log file to get state is one-to-one with yarn app.I really hope to get the answer, thx!

最近我在看作业提交到yarn之后,获取yarn上作业状态的代码.当我看到incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java这个类时,有个方法叫isSuccessOfYarnState(List<String> appIds).为什么这里会是一个appid的列表?我理解的通过log文件获取当前app状态应该是一对一的关系.非常希望得到解答,谢谢!
![image](https://user-images.githubusercontent.com/26177232/94001875-b8de8280-fdcb-11ea-9e3a-30486ff67614.png)
![image](https://user-images.githubusercontent.com/26177232/94001919-c6940800-fdcb-11ea-866f-3e5cc640974a.png)
![image](https://user-images.githubusercontent.com/26177232/94001961-d6abe780-fdcb-11ea-9b14-3f26215d818a.png)
![image](https://user-images.githubusercontent.com/26177232/93999739-c47c7a00-fdc8-11ea-8d54-e06d7fc11ec5.png)

**Which version of DolphinScheduler:**
 -[dev-branch]

**Comment by dailidong** [comment]
because shell task can submit many yarn task，the task runtime log will return many application ids

---
因为 shell 任务类型可以写多个 MR 任务，这样的话，这个shell任务的运行日志里会返回多个 application id
