### ISSUE TITLE
The task instance is not running and is in suspended animation

### ISSUE THREAD

**Issue by xiaomi-box** [apache/incubator-dolphinscheduler#3802]
[ERROR] 2020-09-24 00:15:02.982 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 167471 
[WARN] 2020-09-24 00:15:02.983 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[188] - remove task queue : 2_33554_2_167471_-1 due to taskInstance is null

**Comment by xingchun-chen** [comment]
Please check whether the worker service selected by the worker group of the process definition task starts normally

**Comment by misinong** [comment]
The service is running normally. The version we are using now is 1.2.0. Is it a version bug

**Comment by dailidong** [comment]
> The service is running normally. The version we are using now is 1.2.0. Is it a version bug
yes
version >=1.2.1 solved this issue, detail info please refer : #1477
