### ISSUE TITLE
[Feature][DICUSSION] The implement of passing variables between tasks

### ISSUE THREAD

**Issue by simon824** [apache/incubator-dolphinscheduler#3805]
Discussion on the implement of passing variables between tasks

There are three possible solutions :

1. make global variables customizable, used to pass variables between tasks

2. increase the local variables in the taskflow. Someone has already implemented it, but it has not been merged. #3659

3. The first task is output to a specified path, and then the content in this path is read in the second step;The log is uniformly output to the standard error, the result of the task is output to the standard output, and the second task directly obtains the standard output content of the first task. @rockxsj 

----

关于Task之间的变量传递特性的讨论

目前有如下三个可能的方案

1. 将全局变量改为可自定义，用来传递Task之间的变量
2. 增加工作流内部的局部变量， @guyinyou 已经实现了，但是还未合并，具体实现细节见 #3659
3. @rockxsj  提出的方案：第一个task的输出指定输出到一个路径，然后第二步读取这个路径里面的内容；日志统一输出到标准错误，task的结果输出到标准输出，第二个task直接获取第一个task的标准输出内容。 

大家可以直接留言选出你觉得好的方案，如果有其他实现方案也欢迎交流

**Comment by wangxj3** [comment]
关于全局变量(节点间参数传递)实现方案的讨论：
目前我们已经实现了全局变量功能，具体为：
1.变量在流程实例内生效，每个节点可接受变量，sql和shell节点可修改变量值，后续节点在使用该变量时为修改后的值。
2.子流程节点传入变量，子流程可以接受到变量值
3.流程实例在某节点失败后，从失败节点重启，以前执行成功的节点对变量的修改依然生效。
实现方案为：
1.用户在保存DAG时会从globalParams中取出定义的全局变量，维护DAG与变量关系（表1）
2.在DAG被调起实例化的时候，新增属于processInstance的全局变量（表2）
3.关于入参：在创建taskInstance时，从localParam中取出变量，更新value值，存入taskInstance，后续将taskInstance保存数据库，分发给worker
4.关于出参：在sql节点和shell节点任务执行结束后，将任务执行的结果写入TaskExecuteResponseCommand，随worker执行结果信息一起返回master，master将出参更新至数据库。
5.关于子流程节点：生成子流程的command时判断是否有参数传递，如果有新增表2数据，返回id维护到command中，在子流程被实例化时，将processInstanceId修改到表2中。

**Comment by wangxj3** [comment]
关于全局变量(节点间参数传递)实现方案的讨论：
目前我们已经实现了全局变量功能，具体为：
1.变量在流程实例内生效，每个节点可接受变量，sql和shell节点可修改变量值，后续节点在使用该变量时为修改后的值。
2.子流程节点传入变量，子流程可以接受到变量值
3.流程实例在某节点失败后，从失败节点重启，以前执行成功的节点对变量的修改依然生效。
实现方案为：
1.用户在保存工作流时，会在点击保存按钮后的弹出框内添加全局变量定义（全局定义），将定义的变量名和初始值（如果有初始值的话）保存到t_ds_process_definition.global_params字段（沿用已有功能），保存时会校验节点所使用的的变量名全部来自【全局定义】。
2.在工作流被调起实例化的时候，将变量值初始化到t_ds_process_instance.global_params字段中。
3.关于入参：在创建taskInstance时，从localParam中取出变量，并将t_ds_process_instance.global_params中最新的值更新至localParam中。存入taskInstance，后续将taskInstance保存数据库，并分发给worker，后续参数处理沿用原有部分。
4.关于出参：在sql节点和shell节点任务执行结束后，将任务执行的结果写入TaskExecuteResponseCommand，随worker执行结果信息一起返回master，master将出参更新t_ds_process_instance.global_params，并将其更新至数据库。
5.关于子流程节点：生成子流程的command时判断是否有参数传递，如果有参数传递，会将参数写入到command表中。在工作流实例化时处理该部分数据。
以下为该方案流程图：
![图片](https://user-images.githubusercontent.com/26736756/103870167-4f7a4980-5106-11eb-9d2e-dbf9fbcd0716.png)
![图片](https://user-images.githubusercontent.com/26736756/103870190-56a15780-5106-11eb-93c2-cf7f653679e6.png)
![图片](https://user-images.githubusercontent.com/26736756/103870358-910af480-5106-11eb-93dc-74c09d055f76.png)
![图片](https://user-images.githubusercontent.com/26736756/103870382-98ca9900-5106-11eb-97ed-1beeafe41ac0.png)

**Comment by dailidong** [comment]
thanks for your great job, a  big and important feature !

**Comment by CalvinKirs** [comment]
this close #5077

**Comment by luojieio** [comment]
![image](https://user-images.githubusercontent.com/25678606/133917039-49503c75-2ced-4461-8376-7a40c4d7cf3c.png)

why lasest release version 1.3.8 no this ? please help me how to use it ?

**Comment by davidzollo** [comment]
@luojieio 

> ![image](https://user-images.githubusercontent.com/25678606/133917039-49503c75-2ced-4461-8376-7a40c4d7cf3c.png)
> 
> why lasest release version 1.3.8 no this ? please help me how to use it ?

![image](https://user-images.githubusercontent.com/15833811/134620737-ce5500c6-106e-4888-97e8-7cc6b952d599.png)

click the '+' , then the custom parameters will be shown on the UI
