### ISSUE TITLE
[Feature][API]导出工作流定义支持描述字段Export workflow definition support description

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#3808]
希望导出工作流定义时，能把描述字段一起导出
when export the workflow definition, I hope export the description of the workflow together

**Which version of DolphinScheduler:**
 -[1.3.2]

**Comment by AhahaGe** [comment]
I think it's possible, and I will add this feature.

**Comment by AhahaGe** [comment]
[
    {
        "processDefinitionConnects":"[]",
        "processDefinitionJson":"{"tenantId":2,"globalParams":[],"tasks":[{"conditionResult":{"successNode":[""],"failedNode":[""]},"description":"shell_ls_1","runFlag":"NORMAL","type":"SHELL","params":{"rawScript":"ls\npwd\necho 'hello'","localParams":[],"resourceList":[]},"timeout":{"enable":false,"strategy":""},"maxRetryTimes":"0","taskInstancePriority":"MEDIUM","name":"shell_ls_1","dependence":{},"retryInterval":"1","preTasks":[],"id":"tasks-48544","workerGroup":"default"}],"timeout":0}",
        "processDefinitionLocations":"{"tasks-48544":{"name":"shell_ls_1","targetarr":"","nodenumber":"0","x":431,"y":138}}",
        "processDefinitionName":"shell_dag",
        "projectName":"test_shell"
    }
]

**Comment by glxfeng** [comment]
> [
> {
> "processDefinitionConnects":"[]",
> "processDefinitionJson":"{"tenantId":2,"globalParams":[],"tasks":[{"conditionResult":{"successNode":[""],"failedNode":[""]},"description":"shell_ls_1","runFlag":"NORMAL","type":"SHELL","params":{"rawScript":"ls\npwd\necho 'hello'","localParams":[],"resourceList":[]},"timeout":{"enable":false,"strategy":""},"maxRetryTimes":"0","taskInstancePriority":"MEDIUM","name":"shell_ls_1","dependence":{},"retryInterval":"1","preTasks":[],"id":"tasks-48544","workerGroup":"default"}],"timeout":0}",
> "processDefinitionLocations":"{"tasks-48544":{"name":"shell_ls_1","targetarr":"","nodenumber":"0","x":431,"y":138}}",
> "processDefinitionName":"shell_dag",
> "projectName":"test_shell"
> }
> ]
> Add one column called processDescription.

 Thanks for your help.
 But I'm sorry, my requirement description is incomplete.
 If this column is added to the exported file, the import workflow should also support it.

**Comment by AhahaGe** [comment]
Got it.

**Comment by dailidong** [comment]
PR #3847 solved this issue
