### ISSUE TITLE
DS创建datax任务抽取oracle表提示插件加载失败

### ISSUE THREAD

**Issue by lavesin** [apache/incubator-dolphinscheduler#3809]
DS创建datax任务抽取oracle表数据提示插件加载失败，不知道是哪里配置错误，以下是通过ds配置的datax任务信息和报错信息：
-------------------------------------------------------------------------------------------------------------------
以下为配置datax任务json内容
-------------------------------------------------------------------------------------------------------------------
[{"processDefinitionConnects":"[]","processDefinitionJson":"{\"tenantId\":1,\"globalParams\":[],\"tasks\":[{\"conditionResult\":{\"successNode\":[\"\"],\"failedNode\":[\"\"]},\"description\":\"数据抽取\",\"runFlag\":\"NORMAL\",\"type\":\"DATAX\",\"params\":{\"targetTable\":\"ODS_ARCHIVES1\",\"postStatements\":[],\"jobSpeedRecord\":\"0\",\"customConfig\":0,\"dtType\":\"ORACLE\",\"dsType\":\"ORACLE\",\"jobSpeedByte\":0,\"dataSource\":1,\"dataTarget\":2,\"sql\":\"SELECT UUID FROM T_S_ARCHIVES\",\"preStatements\":[]},\"timeout\":{\"enable\":false,\"strategy\":\"\"},\"maxRetryTimes\":0,\"taskInstancePriority\":\"MEDIUM\",\"name\":\"DNM_ARCHIVES\",\"dependence\":{},\"retryInterval\":\"1\",\"preTasks\":[],\"id\":\"tasks-85653\",\"workerGroup\":\"default\"}],\"timeout\":0}","processDefinitionLocations":"{\"tasks-85653\":{\"name\":\"DNM_ARCHIVES\",\"targetarr\":\"\",\"nodenumber\":\"0\",\"x\":415,\"y\":179}}","processDefinitionName":"测试","projectName":"BCETL"}]
------------------------------------------------------------------------------------------------------------------
以下为报错
------------------------------------------------------------------------------------------------------------------

INFO] 2020-09-24 06:00:58.225  - [taskAppId=TASK-1-6-8]:[87] - tenantCode user:bczuhu, task dir:1_6_8
[INFO] 2020-09-24 06:00:58.231  - [taskAppId=TASK-1-6-8]:[92] - create command file:/tmp/dolphinscheduler/exec/process/1/1/6/8/1_6_8.command
[INFO] 2020-09-24 06:00:58.231  - [taskAppId=TASK-1-6-8]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/DolphinScheduler/ds-backend-run/conf/env/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/1/1/6/8/1_6_8_node.sh
[INFO] 2020-09-24 06:00:58.239  - [taskAppId=TASK-1-6-8]:[312] - task run command:
sudo -u bczuhu sh /tmp/dolphinscheduler/exec/process/1/1/6/8/1_6_8.command
[INFO] 2020-09-24 06:00:58.240  - [taskAppId=TASK-1-6-8]:[193] - process start, process id is: 1904
[INFO] 2020-09-24 06:00:59.314  - [taskAppId=TASK-1-6-8]:[121] -  -> 
	DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
	Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
	
	
	2020-09-24 06:00:59.310 [main] WARN  ConfigParser - 插件[oraclereader,oraclewriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[oraclereader, oraclewriter] 
[INFO] 2020-09-24 06:01:00.335  - [taskAppId=TASK-1-6-8]:[121] -  -> 2020-09-24 06:01:00.334 [main] ERROR Engine - 
[INFO] 2020-09-24 06:01:00.370  - [taskAppId=TASK-1-6-8]:[121] -  -> 
	经DataX智能分析,该任务最可能的错误原因是:
	com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[oraclereader, oraclewriter]
		at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
		at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
		at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
		at com.alibaba.datax.core.Engine.entry(Engine.java:137)
		at com.alibaba.datax.core.Engine.main(Engine.java:204)
	
[INFO] 2020-09-24 06:01:00.374  - [taskAppId=TASK-1-6-8]:[202] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/1/1/6/8, processId:1904 ,exitStatusCode:0

**Comment by felix-thinkingdata** [comment]
You post the datax run log

你把datax 的运行日志贴出来

**Comment by lavesin** [comment]
[INFO] 2020-09-24 06:33:14.716  - [taskAppId=TASK-1-7-9]:[87] - tenantCode user:bczuhu, task dir:1_7_9
[INFO] 2020-09-24 06:33:14.728  - [taskAppId=TASK-1-7-9]:[92] - create command file:/tmp/dolphinscheduler/exec/process/1/1/7/9/1_7_9.command
[INFO] 2020-09-24 06:33:14.729  - [taskAppId=TASK-1-7-9]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /opt/DolphinScheduler/ds-backend-run/conf/env/dolphinscheduler_env.sh
/tmp/dolphinscheduler/exec/process/1/1/7/9/1_7_9_node.sh
[INFO] 2020-09-24 06:33:14.736  - [taskAppId=TASK-1-7-9]:[312] - task run command:
sudo -u bczuhu sh /tmp/dolphinscheduler/exec/process/1/1/7/9/1_7_9.command
[INFO] 2020-09-24 06:33:14.737  - [taskAppId=TASK-1-7-9]:[193] - process start, process id is: 2040
[INFO] 2020-09-24 06:33:15.849  - [taskAppId=TASK-1-7-9]:[121] -  -> 
	DataX (DATAX-OPENSOURCE-3.0), From Alibaba !
	Copyright (C) 2010-2017, Alibaba Group. All Rights Reserved.
	
	
	2020-09-24 06:33:15.844 [main] WARN  ConfigParser - 插件[oraclereader,oraclewriter]加载失败，1s后重试... Exception:Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[oraclereader, oraclewriter] 
[INFO] 2020-09-24 06:33:16.870  - [taskAppId=TASK-1-7-9]:[121] -  -> 2020-09-24 06:33:16.869 [main] ERROR Engine - 
[INFO] 2020-09-24 06:33:16.904  - [taskAppId=TASK-1-7-9]:[121] -  -> 
	经DataX智能分析,该任务最可能的错误原因是:
	com.alibaba.datax.common.exception.DataXException: Code:[Framework-12], Description:[DataX插件初始化错误, 该问题通常是由于DataX安装错误引起，请联系您的运维解决 .].  - 插件加载失败，未完成指定插件加载:[oraclereader, oraclewriter]
		at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:26)
		at com.alibaba.datax.core.util.ConfigParser.parsePluginConfig(ConfigParser.java:142)
		at com.alibaba.datax.core.util.ConfigParser.parse(ConfigParser.java:63)
		at com.alibaba.datax.core.Engine.entry(Engine.java:137)
		at com.alibaba.datax.core.Engine.main(Engine.java:204)
	
[INFO] 2020-09-24 06:33:16.908  - [taskAppId=TASK-1-7-9]:[202] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/1/1/7/9, processId:2040 ,exitStatusCode:0

**Comment by lavesin** [comment]
/opt/datax/log/2020-09-24目录下没有日志信息

**Comment by zhuangchong** [comment]
The current error is thrown by datax, there is no [oraclereader, oraclewriter] plug-in in datax

---
目前报错是datax抛出来的，datax 里面没有 [oraclereader, oraclewriter] 插件

**Comment by lavesin** [comment]
最后搞定了，原因是一个很弱智的错误，datax解压出错，导致datax包不完整，还是感谢一路提点

**Comment by zhuangchong** [comment]
> 最后搞定了，原因是一个很弱智的错误，datax解压出错，导致datax包不完整，还是感谢一路提点

ok, the problem has been solved, please close this issue, thx.
