### ISSUE TITLE
 The log cannot be cleaned correctly in MasterExecThread

### ISSUE THREAD

**Issue by Slowfever-star** [apache/incubator-dolphinscheduler#3815]
MasterExecThread has functions related to cleaning and running programs, but it only satisfies the situation that worker and master execute on the same server
MasterExecThread中有清理运行程序相关的功能，但是只能满足worker和master在同一台服务器上执行的情况, 这个功能应该在task中处理吧
version:1.3.1

**Comment by weiyuanyong** [comment]
I found the same proplem:
[Bug][server] can not delete exce directory when run to postHandle() method when task IP is not same to the master IP.
class: org.apache.dolphinscheduler.server.master.runner.MasterExecThread
method: postHandle()
version: All version

**Comment by chengshiwen** [comment]
Close by #4149 #5123
