### ISSUE TITLE
The work node cannot create a task instance

### ISSUE THREAD

**Issue by 13476806803** [apache/incubator-dolphinscheduler#3816]
master log
![image](https://user-images.githubusercontent.com/40188761/94219375-4976a900-ff19-11ea-931d-fa7d37d08e62.png)
There is no master node Log here
UI show
![image](https://user-images.githubusercontent.com/40188761/94219519-9b1f3380-ff19-11ea-9488-932c13b7eef4.png)
The work node has no log

master 节点日志
master submit success, task : xxx
wait task: process id: 7864, task id:8158, task name:xxx complete
getChannel-->> host:19.89.112.72,port:1234,channel:-93546565
到这一步master就没有日志了然后界面上这个任务显示提交成功没有任务实例图标灰色的
work节点没有任何关于这个任务的日志信息

**Comment by xingchun-chen** [comment]
please check the worker group in the workflow task settings that matches the worker service
![image](https://user-images.githubusercontent.com/55787491/94221033-e38c2080-ff1c-11ea-952d-6caa44baa3e2.png)

**Comment by 13476806803** [comment]
yes 
![image](https://user-images.githubusercontent.com/40188761/94221539-e5a2af00-ff1d-11ea-8fe9-1ebc3bd80da3.png)
![image](https://user-images.githubusercontent.com/40188761/94221625-14208a00-ff1e-11ea-94a5-782fa59226dd.png)
There are two groups 'default' has two worker It's been fine,'local' has three workers often fail to start instances,After a restart, you can run again. After a period of time, you will have this problem again, all in the local group

**Comment by 13476806803** [comment]
Local and default are in different network segments, and the master is in the default network end

**Comment by chengshiwen** [comment]
Close the issue since it has been resolved
