### ISSUE TITLE
为啥sql查询的邮件必填，服务器是在内网，根本就没有邮件服务器，总提示邮件发送失败。

### ISSUE THREAD

**Issue by 939598604** [apache/incubator-dolphinscheduler#3818]

**Comment by zhuangchong** [comment]
sql query is query result data, which can be viewed by sending emails. What is your requirement here is to use sql query function. sql query is to query data for viewing. You can select non-query and perform operations such as sql insert update delete.

---
sql 查询是查询结果数据，通过邮件发送进行查看，您这边是用sql查询功能来实现什么需求。sql 查询是为了查询数据进行查看，可以选择非查询，进行sql insert update delete 等操作。

**Comment by gaojun2048** [comment]
Please change the issue title to english !

Thrank you !

**Comment by dailidong** [comment]
> sql query is query result data, which can be viewed by sending emails. What is your requirement here is to use sql query function. sql query is to query data for viewing. You can select non-query and perform operations such as sql insert update delete.
> 
> sql 查询是查询结果数据，通过邮件发送进行查看，您这边是用sql查询功能来实现什么需求。sql 查询是为了查询数据进行查看，可以选择非查询，进行sql insert update delete 等操作。

yes, select query will send mail , insert/update/delete will not send mail
