### ISSUE TITLE
为啥执行sql语句结果是成功的但是却没有显示执行结果

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#3819]
[INFO] 2020-09-25 12:04:32.853  - [taskAppId=TASK-9-38-46]:[104] - Full sql parameters: SqlParameters{type='MYSQL', datasource=1, sql='show databases;', sqlType=1, udfs='', showType='TABLE', connParams='', title='', receivers='', receiversCc='', preStatements=[], postStatements=[]}
[INFO] 2020-09-25 12:04:32.854  - [taskAppId=TASK-9-38-46]:[105] - sql type : MYSQL, datasource : 1, sql : show databases; , localParams : [],udfs : ,showType : TABLE,connParams : 
[INFO] 2020-09-25 12:04:32.895  - [taskAppId=TASK-9-38-46]:[499] - after replace sql , preparing : show databases;
[INFO] 2020-09-25 12:04:32.895  - [taskAppId=TASK-9-38-46]:[504] - Sql Params are replaced sql , parameters:
[INFO] 2020-09-25 12:04:32.896  - [taskAppId=TASK-9-38-46]:[52] - can't find udf function resource
[INFO] 2020-09-25 12:04:33.158  - [taskAppId=TASK-9-38-46]:[418] - prepare statement replace sql : com.mysql.jdbc.JDBC42PreparedStatement@7b56d3f2: show databases;

**Comment by dailidong** [comment]
please see the runtime log on worker server to find out  the exit code for this task, exit code = 0 means success, not 0 means failure

**Comment by dailidong** [comment]
by the way , please update/add title in English, thx

**Comment by xingchun-chen** [comment]
Don't reply for a long time ,it will be close.
If you have questions, please update the title in English and reopen it, thanks

**Comment by gaoyu2016** [comment]
1·3.4遇到了同样的问题
