### ISSUE TITLE
[Feature][Task Type] Can MQ nodes be supported？

### ISSUE THREAD

**Issue by chakench** [apache/incubator-dolphinscheduler#3821]
**Now the task node is one-time, can you consider adding MQ node, so that the node does not stop, as long as MQ listens to the message, it will process the subsequent nodes after this MQ node**

**Comment by yangyichao-mango** [comment]
Can you describe the scene of this feature?

**Comment by chakench** [comment]
> Can you describe the scene of this feature?
For example, the current process is that the MQ node is listening all the time, so as long as it listens for messages coming in, it can conduct subsequent process orchestration according to the monitored messages

**Comment by CalvinKirs** [comment]
see #4086
