### ISSUE TITLE
Fixing the param name of password

### ISSUE THREAD

**Issue by wat1r** [apache/incubator-dolphinscheduler#3822]
## BACKGROUND
![image](https://user-images.githubusercontent.com/20732599/94250310-a1320600-ff53-11ea-8394-1b9d839e59d4.png)

The screenshot is coming from the website , set the confiurations to  file  ` conf/config/install_config.conf`

## DESCRIPTION

When executing the `install.sh`  

```shell
source ${workDir}/conf/config/install_config.conf
//some code

sed -i ${txt} "s#spring.datasource.password.*#spring.datasource.password=${password}#g" conf/datasource.properties


```

cause of the param name is not unified one is  `passowrd`  another is  `password` ,as a result , the value of in the `data.properties` will be rewrited with empty value, will get error when starting 

---
## VERSION
```java
apache-dolphinscheduler-incubating-1.3.1-dolphinscheduler-bin.tar.gz
```

**Comment by zhuangchong** [comment]
Hi, where did you download this 1.3.1 tar? I downloaded the 1.3.1 binary package from the official website, and no passowrd was found in /config/install_config.conf

---
Hi, ,您说的这个1.3.1 tar 在哪下载的？我从官网下载1.3.1二进制包，/config/install_config.conf里面未发现passowrd

**Comment by wat1r** [comment]
the config  `password ` which located in  `/config/install_config.conf` is correct ,  I  copy it from the website  for quick deploy :

`https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/standalone-deployment.html`

which is also happening in `https://dolphinscheduler.apache.org/zh-cn/docs/1.2.1/user_doc/cluster-deployment.html`

there will be no problem with the original  `/config/install_config.conf`

**Comment by zhuangchong** [comment]
ok, it is a misspelling of the password word in the official website document version 1.2.
