### ISSUE TITLE
[Question] What happens when a worker or master goes down

### ISSUE THREAD

**Issue by wangliyucool** [apache/incubator-dolphinscheduler#3827]
how to listen for the Master Worker  running status when master and worker start?

What happens when a worker or master goes down?

I want to know how to solve it in the code! 
: )

**Comment by xloya** [comment]
You can look incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/registry/WorkerRegistry ,incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistry and 
 incubator-dolphinscheduler/dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/zk/ZKMaterClient,here is involved code logic.

**Comment by xingchun-chen** [comment]
Has your problem been resolved? If it is resolved, please close it
