### ISSUE TITLE
[Bug][ui] When the tenantName contains "<", the tenant drop-down list is blank

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3835]
When the tenant name contains "<", when creating/editing users and saving workflows, the tenant drop-down list data is blank
![image](https://user-images.githubusercontent.com/55787491/94386193-a2dd1300-0179-11eb-95df-80025156d4c8.png)
![image](https://user-images.githubusercontent.com/55787491/94386289-db7cec80-0179-11eb-8fdd-96839d769bed.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by xingchun-chen** [comment]
who want to fix it?

**Comment by DSExtension** [comment]
i think we should set the tenant name cannot contain special characters and letters.

**Comment by xingchun-chen** [comment]
I think the tenant name cannot contain special characters, but can be letters

**Comment by zhuangchong** [comment]
I fix it.

**Comment by lenboo** [comment]
i have reviewed the issue, the key '<script' matches the keywords on the front page, other places such as project names, workflow definition names, and so on have the same problem, so we should consider a more suitable solution.

**Comment by zhuangchong** [comment]
> i have reviewed the issue, the key '<script' matches the keywords on the front page, other places such as project names, workflow definition names, and so on have the same problem, so we should consider a more suitable solution.

OK, it’s better to solve it in a public way, shouldn’t all input names be restricted to special characters?

---
好的，最好是可以公共方法解决，是不是应该限制所有的输入名称都不应该是特殊字符?

**Comment by dailidong** [comment]
> > i have reviewed the issue, the key '<script' matches the keywords on the front page, other places such as project names, workflow definition names, and so on have the same problem, so we should consider a more suitable solution.
> 
> OK, it’s better to solve it in a public way, shouldn’t all input names be restricted to special characters?
> 
> 好的，最好是可以公共方法解决，是不是应该限制所有的输入名称都不应该是特殊字符?

I think all input names  been restricted are not good idea

**Comment by dailidong** [comment]
this PR #3870 has been merged, other input names also could be restricted if indeed needed
