### ISSUE TITLE
[Bug][ui] When the tenant code is a number, it should not be saved successfully

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3840]
1.When the tenant code is a number, click Submit, tenant saved successfully
![image](https://user-images.githubusercontent.com/55787491/94398686-974d1480-0198-11eb-8624-476177f157b4.png)
![image](https://user-images.githubusercontent.com/55787491/94398703-a0d67c80-0198-11eb-8dd6-19fe61375f7c.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Additional context**

**Requirement or improvement**
When the tenant code is a number, the tenant should not save successfully，A prompt should pop up: Please enter the English tenant code

**Comment by xingchun-chen** [comment]
who want to fix it?

**Comment by DSExtension** [comment]
why tenant code cannot be a number?

**Comment by hermeshephaestus** [comment]
ok, i wil fix the problem. @xingchun-chen

**Comment by xingchun-chen** [comment]
> why tenant code cannot be a number?
When the tenant code is a number, the following error will be reported when running the workflow 
![image](https://user-images.githubusercontent.com/55787491/94504622-cb2d4600-023b-11eb-9610-7dd2ceef3f85.png)

**Comment by hermeshephaestus** [comment]
[Fix-3840][server] Fix When the tenant code is a number, it should not be saved successfully #3867
