### ISSUE TITLE
[Bug][Resource] 资源文件无法更新

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#3842]
当通过HDFS存储，资源文件为jar时，通过资源界面重新上传文件，文件未更新
![image](https://user-images.githubusercontent.com/7664170/94400788-3e7f7b00-019c-11eb-988b-974af9e12299.png)
![image](https://user-images.githubusercontent.com/7664170/94400289-69b59a80-019b-11eb-9eb4-fd52645936b0.png)
![image](https://user-images.githubusercontent.com/7664170/94400898-6a9afc00-019c-11eb-80a1-5b967026664b.png)

**Comment by xingchun-chen** [comment]
1.When re-uploading, please modify one of the file name or description
2.This problem will be fixed in version 1.3.3

**Comment by baijun** [comment]
@xingchun-chen thanks!
