### ISSUE TITLE
[Bug][api] When the update workflow definition name already exists, the prompt is not friendly

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#3843]
1. Edit workflow
2. The  workflow definition name  already exists, saved workflow ，prompt: update workflow definition error
Prompt suggestion to change: workflow definition name already exists, please re-enter
![image](https://user-images.githubusercontent.com/55787491/94400098-22c7a500-019b-11eb-8f2b-b892e6d3f2c0.png)

**Which version of Dolphin Scheduler:**
 -[1.3.2-release]

**Comment by xingchun-chen** [comment]
who want to fix it?

**Comment by zhuangchong** [comment]
I fix it

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/96071859-9543bf00-0ed5-11eb-9d72-d86544403c8a.png)
Edit an existing workflow name, the prompt remains unchanged

**Comment by zhuangchong** [comment]
> ![image](https://user-images.githubusercontent.com/55787491/96071859-9543bf00-0ed5-11eb-9d72-d86544403c8a.png)
> Edit an existing workflow name, the prompt remains unchanged

![image](https://user-images.githubusercontent.com/37063904/96073417-fd47d480-0ed8-11eb-87e3-df5327101227.png)

Edit an existing workflow name,already changed

branch:dev
