### ISSUE TITLE
 Does python have version compatibility issues in its process definition, and why doesn't my Python 3 work?

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#3853]
Process definition settings：
![image](https://user-images.githubusercontent.com/42087586/94536305-321b2100-0275-11eb-9ed0-711007f6905a.png)

Script content：
![image](https://user-images.githubusercontent.com/42087586/94536834-61319280-0275-11eb-8fd7-d4b140966e59.png)

The error is reported as follows：
[INFO] 2020-09-29 14:52:28.244  - [taskAppId=TASK-11-64-84]:[121] -  ->   File "/tmp/dolphinscheduler/exec/process/2/11/64/84/py_11_64_84.command", line 4
	    python3 ninhao.py
	                 ^
	SyntaxError: invalid syntax

**Comment by xloya** [comment]
Have you configured PYTHON_HOME in conf/env/dolphinscheduler_env.sh?If you want to use python3,you should configure python3's home path

**Comment by xloya** [comment]
And if you use python node,you should write code like print("nihao") in script input box rather than "python3 ninhao.py".If you want to use cmd,you should create a shell node rather than python node

**Comment by shiliquan** [comment]
好的，知道了，谢谢！

**Comment by geosmart** [comment]
> 好的，知道了，谢谢！

please close the issue if your issue have already resolved
