### ISSUE TITLE
[Question] How to configure enterprise WeChat alarms in an intranet environment？

### ISSUE THREAD

**Issue by enoughwell** [apache/incubator-dolphinscheduler#3856]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by BoYiZhang** [comment]
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html
![image](https://user-images.githubusercontent.com/39816903/94580983-1e8bac80-02ad-11eb-9da7-54ca6e2a6ce4.png)

**Comment by enoughwell** [comment]
> https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html
> ![image](https://user-images.githubusercontent.com/39816903/94580983-1e8bac80-02ad-11eb-9da7-54ca6e2a6ce4.png)

3q

**Comment by enoughwell** [comment]
> https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html
> ![image](https://user-images.githubusercontent.com/39816903/94580983-1e8bac80-02ad-11eb-9da7-54ca6e2a6
