### ISSUE TITLE
about oraclewriter exception ORA-00936，用datax写入oracle数据库提示ORA-00936的错误，并回滚数据

### ISSUE THREAD

**Issue by lavesin** [apache/incubator-dolphinscheduler#3857]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**

部分报错内容如下：
2020-09-30 01:34:27.904 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:34:37.907  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:34:37.906 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:34:47.909  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:34:47.908 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:34:57.910  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:34:57.910 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:35:07.913  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:35:07.912 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:35:17.915  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:35:17.914 [job-0] INFO  StandAloneJobContainerCommunicator - Total 0 records, 0 bytes | Speed 0B/s, 0 records/s | Error 0 records, 0 bytes |  All Task WaitWriterTime 0.000s |  All Task WaitReaderTime 0.000s | Percentage 0.00%
[INFO] 2020-09-30 01:35:26.024  - [taskAppId=TASK-4-15-16]:[121] -  -> 2020-09-30 01:35:26.023 [0-0-0-reader] INFO  CommonRdbmsReader$Task - Finished read record by Sql: [select UUID,ORG_CODE,NAME,IDENTITY_TYPE,IDENTITY_CODE from TABLE1 where (identity_code = '370122197*******')
[INFO] 2020-09-30 01:35:27.917  - [taskAppId=TASK-4-15-16]:[121] -  -> ] jdbcUrl:[jdbc:oracle:thin:@//192.168.5.63:1521/mbsdb].
	2020-09-30 01:35:26.233 [0-0-0-writer] WARN  CommonRdbmsWriter$Task - 回滚此次写入, 采用每次写入一行方式提交. 因为:ORA-00936: missing expression
	
	2020-09-30 01:35:26.251 [0-0-0-writer] ERROR StdoutPluginCollector - 
	java.sql.SQLSyntaxErrorException: ORA-00936: missing expression

**Which version of DolphinScheduler:**
1.3.1

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by zhuangchong** [comment]
This problem is reported as an error when oracle executes the sql statement, please check the sql script

---
此问题报错是oracle 执行sql语句报错，请检查一下sql脚本

**Comment by xingchun-chen** [comment]
please update the title in English
