### ISSUE TITLE
Project should support sharing with others

### ISSUE THREAD

**Issue by zhanglistar** [apache/incubator-dolphinscheduler#387]
Share projects whth my team members.

**Comment by qiaozhanwei** [comment]
管理员登录，项目是支持授权给其他人的

**Comment by lianayu** [comment]
Do dolphinscheduler support project owners to share projects with others instead of administrators?
--------------
是否支持项目所有者分配项目给其他人看而不是管理员分配？

**Comment by dailidong** [comment]
> ## Do dolphinscheduler support project owners to share projects with others instead of administrators?
> 是否支持项目所有者分享项目给其他人看而不是管理员分配？

only by admin operate
