### ISSUE TITLE
update process definition error

### ISSUE THREAD

**Issue by jiuli** [apache/incubator-dolphinscheduler#3881]
![image](https://user-images.githubusercontent.com/4122723/95653154-f3188580-0b28-11eb-8461-abac77effc1e.png)

**Comment by xingchun-chen** [comment]
which version?

**Comment by jiuli** [comment]
1.3.2  postgresql change to msyql   workflow can be updated successful
The code is as follows：
https://github.com/jiuli/incubator-dolphinscheduler
![image](https://user-images.githubusercontent.com/4122723/95958643-003cb980-0e34-11eb-866d-31d42d860f2b.png)
