### ISSUE TITLE
[Feature][Docs] Add English documentation for "system-manual" in version 1.3.2

### ISSUE THREAD

**Issue by Segun-Ogundipe** [apache/incubator-dolphinscheduler#3883]
There is currently no English documentation for "system-manual" [here](https://dolphinscheduler.apache.org/en-us/docs/1.3.2/user_doc/system-manual.html), the link returns a 404 error. The fix is to translate the Chinese version at this [link](https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/system-manual.html)

More details can be found #3562

**Comment by dailidong** [comment]
I think you can referer the document about version 1.3.1 ,  there is not much change between version 1.3.2 and 1.3.1 

https://dolphinscheduler.apache.org/en-us/docs/1.3.1/user_doc/system-manual.html

**Comment by Segun-Ogundipe** [comment]
@dailidong, true, but the images need to be changed right? For instance, the connecting line between two nodes in the document of version 1.3.1 is different from the one in version 1.3.2.

**Comment by dailidong** [comment]
connecting line in version 1.3.1 is same with version 1.3.2.
![image](https://user-images.githubusercontent.com/15833811/95682183-8085d380-0c16-11eb-84e4-316bc465d329.png)
this is version 1.3.2


I think you saw the demo url : http://106.75.43.194:8888/,  demo is not the latest version ,it is version 1.2.0, an earlier version

**Comment by Segun-Ogundipe** [comment]
Oh, Okay. That's what confused me. I get it now

**Comment by Segun-Ogundipe** [comment]
Hi @CalvinKirs, @dailidong, I have opened a PR for this issue [here](https://github.com/apache/incubator-dolphinscheduler-website/pull/190). Kindly check.

Thank you.

**Comment by dailidong** [comment]
> Hi @CalvinKirs, @dailidong, I have opened a PR for this issue [here](https://github.com/apache/incubator-dolphinscheduler-website/pull/190). Kindly check.
> 
> Thank you.

good job

**Comment by lgcareer** [comment]
@Segun-Ogundipe 
Thanks for your contribution.
The spark task node page still used chinese.Here need change to the english.

![image](https://user-images.githubusercontent.com/15651066/95702674-9b406280-0c7f-11eb-8cc2-824e1d7864c7.png)

**Comment by Segun-Ogundipe** [comment]
> @Segun-Ogundipe
> Thanks for your contribution.
> The spark task node page still used chinese.Here need change to the english.
> 
> ![image](https://user-images.githubusercontent.com/15651066/95702674-9b406280-0c7f-11eb-8cc2-824e1d7864c7.png)

Will do

**Comment by dailidong** [comment]
@Segun-Ogundipe  use this pic:  https://dolphinscheduler.apache.org/img/spark-submit-en.png

**Comment by dailidong** [comment]
work done, this issue will close
