### ISSUE TITLE
[Question]  The current user is disabled

### ISSUE THREAD

**Issue by Heltman** [apache/incubator-dolphinscheduler#3897]
测试环境部署了dolphinscheduler，然后在idea中配置了测试环境的ds数据库，登录时显示当前用户已停用，请问怎么解决
![image](https://user-images.githubusercontent.com/44333070/95835556-f3a35d00-0d70-11eb-8f80-a1a8da45d7f4.png)

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
The dev branch adds the ”state“ field in the t_ds_user table, you can execute the upgrade script: sh script/upgrade-dolphinscheduler.sh

**Comment by Heltman** [comment]
> The dev branch adds the ”state“ field in the t_ds_user table, you can execute the upgrade script: sh script/upgrade-dolphinscheduler.sh

thanks，I got it
