### ISSUE TITLE
[Improvement][Document] Maybe changelog in docs?

### ISSUE THREAD

**Issue by erienniu** [apache/incubator-dolphinscheduler#3898]
a changelog may help a lot for me to keep up with some new features!

**Comment by KarenEfereyan** [comment]
@erienniu if I want to help with this, how can I go about it? I am a new contributor to Apache. Actually, I am an outreachy intern and I am looking to make some contributions

**Comment by erienniu** [comment]
@KarenEfereyan https://dolphinscheduler.apache.org/en-us/docs/development/become%20a%20committer.html you can follow this instruction.

**Comment by CalvinKirs** [comment]
> @erienniu if I want to help with this, how can I go about it? I am a new contributor to Apache. Actually, I am an outreachy intern and I am looking to make some contributions

Hi, you can look for some easy to fix tasks in our issue first. If you encounter any problems during this process, please contact me. My email is acmrabbit@gmail.com
