### ISSUE TITLE
[Bug] Kill YarnJob may be fail in cluster？

### ISSUE THREAD

**Issue by KnightChess** [apache/incubator-dolphinscheduler#3900]
Forgive my poor english
**Describe the question**
A clear and concise description of what the question is.
When kill yarn task, dolphinscheduler may shows the kill is successful, but the tasks may still running on the yarn cluster
* * *
当 kill yarn 类型的任务的时候，dolphinscheduler 上显示任务状态 kill 成功，但实际任务可能还在 yarn 集群上运行，没有 kill 掉

**Which version of DolphinScheduler:**
 -[1.3.3-release]

**Additional context**
code in org.apache.dolphinscheduler.server.utils.ProcessUtils.cancelApplication 
![image](https://user-images.githubusercontent.com/20125927/95886712-8368fb80-0db1-11eb-96e3-198938317382.png)
String appid = appIds.get(appIds.size() - 1); 
get the last appId，If the task has multiple stages，and hive.exec.parallel = true，stages will be executed in parallel if there is no dependency between them. If the last job for stage is successful(last appId), but other is running, the task will kill fail in yarn cluster, but dolphinscheduler show success.
* * *
上面的代码是获取 appId 列表中的最后一个进行 kill，如果这个任务有多个stage，并且stage之间没有依赖啊，hive.exec.parallel = true 设置可以并行执行，就会存在最后一个 appId 对应的 job 执行成功，但是中间或者还存在没有执行完的，如果这时候在 dolphinscheduler 将任务 kill 掉，那么 kill 最后一个 appId 没法在集群上 kill 掉任务的，因为最后一个 appId 对应的 job 已经成功，但是还存在其它并行执行的任务

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

I haven't tried it on dolphinscheduler，when study dolphinscheduler code, this killYarnJob code is similar to our self-developed scheduler，we meet this question in our system
* * *
我没有在 dolphinscheduler 上试过，但是我在看相关代码的时候，发现和我们自研的调度系统 killYarnJob 的方式是差不多一样得，都是获取最后一个 appId 进行 kill，就会产生这个问题

**Comment by xingchun-chen** [comment]
who can look the problem?

**Comment by Eights-Li** [comment]
i will fix it
