### ISSUE TITLE
sqoop sql import fail

### ISSUE THREAD

**Issue by riverzzz** [apache/incubator-dolphinscheduler#3902]
**Describe the question**
this is my config.
![image](https://user-images.githubusercontent.com/13781155/95940241-729ba280-0e10-11eb-91e6-c8afd075a457.png)

this is error.
[INFO] 2020-10-14 11:20:47.387  - [taskAppId=TASK-1-11-27]:[121] -  -> 错误: 找不到或无法加载主类 org.apache.hadoop.hbase.util.GetJavaProperty
	2020-10-14 11:20:47,342 INFO sqoop.Sqoop: Running Sqoop version: 1.4.7
	2020-10-14 11:20:47,366 WARN tool.BaseSqoopTool: Setting your password on the command-line is insecure. Consider using -P instead.
	Must specify destination with --target-dir. 
	Try --help for usage instructions.

**Which version of DolphinScheduler:**
 -[1.3.2]

**Comment by Eights-Li** [comment]
When query is used in sqoop, it is not possible to import hive tables directly. 
You can first import the mysql data into a directory in HDFS, and then import it into the hive table by means of hive: load data inpath. 
Use sqoop to import mysql into hive, 1 import the entire table | using --columns or where to deal with select data

**Comment by riverzzz** [comment]
> When query is used in sqoop, it is not possible to import hive tables directly.
> You can first import the mysql data into a directory in HDFS, and then import it into the hive table by means of hive: load data inpath.
> Use sqoop to import mysql into hive, 1 import the entire table | using --columns or where to deal with select data



> When query is used in sqoop, it is not possible to import hive tables directly.
> You can first import the mysql data into a directory in HDFS, and then import it into the hive table by means of hive: load data inpath.
> Use sqoop to import mysql into hive, 1 import the entire table | using --columns or where to deal with select data

can not add --target-dir to parameters?i think it can solve a problem.

**Comment by Eights-Li** [comment]
emmmm... if you want to add sqoop custom param， please add param in sqoop custom text input。
如果要使用sqoop的自定义参数，请在sqoop组件的sqoop参数中进行设置。

**Comment by riverzzz** [comment]
> emmmm... if you want to add sqoop custom param， please add param in sqoop custom text input。
> 如果要使用sqoop的自定义参数，请在sqoop组件的sqoop参数中进行设置。

emmm... I use dolphinScheduler 1.3.2，it can not set sqoop param。

**Comment by Eights-Li** [comment]
yes，sqoop job can add custom sqoop param like -direct and custom hadoop param like mapreduce memory in ds-1.3.3。

**Comment by riverzzz** [comment]
> yes，sqoop job can add custom sqoop param like -direct and custom hadoop param like mapreduce memory in ds-1.3.3。

yes，sqoop job can add custom sqoop param like -direct and custom hadoop param like mapreduce memory in ds-1.3.3。

thanks。

**Comment by SuperHeroBigData** [comment]
How to insert sqoop parameters like 'last-value'   in ds1.3.4?
