### ISSUE TITLE
The official website is wrong about calling Python file?

### ISSUE THREAD

**Issue by zhangfeng114** [apache/incubator-dolphinscheduler#3903]
Official website：https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/system-manual.html There is a problem with the compilation of information about python calls.
as follows:

![2](https://user-images.githubusercontent.com/20456459/95948512-42a9ca80-0e23-11eb-82c1-45bfb7ac9dd3.png)
Can be called in python script
`python test.py`?
Or is it the special processing done by the backend?
When I tried to call like this again without success,
This can easily be misleading.

**Comment by dailidong** [comment]
did you  upload your test.py to resource center？and did you notice that you should choose this test.py first. as follow:
![image](https://user-images.githubusercontent.com/15833811/95950313-daf57e80-0e26-11eb-9dc9-93573e22cf0d.png)

By the way, as a global project, please update/add title and desc in English, thx

**Comment by teacherZF** [comment]
Yes,I uploaded my script in the resource center，But it still did not execute successfully。
as follows:
![3](https://user-images.githubusercontent.com/20456459/95950983-2eb49780-0e28-11eb-8beb-3d8467777c90.png)
But keep getting wrong results
![4](https://user-images.githubusercontent.com/20456459/95951130-6b808e80-0e28-11eb-8625-10b7d9d72e84.png)
I can execute successfully in the background of the server
![5](https://user-images.githubusercontent.com/20456459/95951193-9834a600-0e28-11eb-9697-51ce38489be7.png)
This is my environment configuration
![7](https://user-images.githubusercontent.com/20456459/95951475-1133fd80-0e29-11eb-9ec5-ab893ecffb5f.png)
![8](https://user-images.githubusercontent.com/20456459/95951497-185b0b80-0e29-11eb-957d-b5349c308b48.png)
This is the log
![9](https://user-images.githubusercontent.com/20456459/95951695-7982df00-0e29-11eb-88c1-0b633705df51.png)
What is my possible mistake？？

**Comment by xingchun-chen** [comment]
You can refer to the figure below, to quote the py file in the directory, you need to quote __init__.py
![image](https://user-images.githubusercontent.com/55787491/95970422-83fda280-0e42-11eb-9210-87f8034c8f1c.png)
![image](https://user-images.githubusercontent.com/55787491/95970921-1aca5f00-0e43-11eb-9d3a-422fae0b876f.png)
