### ISSUE TITLE
[Bug][ui] log view in web ui limit 1000 line

### ISSUE THREAD

**Issue by hlzhu1983** [apache/incubator-dolphinscheduler#3904]
verison:1.3.0
log view in web ui limit 1000 line,click the refresh button, the log data cann't update.
![image](https://user-images.githubusercontent.com/9334358/95955851-10eb3080-0e30-11eb-8f2e-7712866d84fe.png)
the worker server log refresh normal
![image](https://user-images.githubusercontent.com/9334358/95955920-25c7c400-0e30-11eb-85b3-faa71d6bd950.png)

**Comment by break60** [comment]
With split screen loading, drag the mouse down the page, it will display the next 1000 data

**Comment by CalvinKirs** [comment]
As @break60 said, you can follow his and try.
