### ISSUE TITLE
任务中某一节点失败继续将任务跑完,如何配置

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3911]
版本1.3.2
比如任务为 :
test_1->test_2->test_3
当test_2失败的时候,想让任务跑到test_3直到跑完,应该如何设置啊

**Comment by dailidong** [comment]
please first English, then you can append description in Chinese

**Comment by dailidong** [comment]
please first English, then you can append description in Chinese

**Comment by xingchun-chen** [comment]
The title has not been updated for a long time in English , it will be closed.
If there is a problem, update the title in English and reopen it
