### ISSUE TITLE
worker分组管理:没有新建功能

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3912]
版本1.3.2
使用admin管理员用户登录,进入Worker分组管理中,没有新增分组的按钮,分组后面也没有修改,删除等按钮
![image](https://user-images.githubusercontent.com/61308609/95974945-253b2780-0e48-11eb-9c14-214c0dae046b.png)

**Comment by dailidong** [comment]
good，add this part on website  https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/system-manual.html
![image](https://user-images.githubusercontent.com/15833811/96005822-6c88de80-0e6f-11eb-8b53-bc99b55ead02.png)

By the way, as a global project, please add/update title and desc in English,thx

**Comment by 13430647361** [comment]
OK,已经测试过了,修改后重启可以使用,非常感谢!

**Comment by dailidong** [comment]
please first English, then you can append description in Chinese
