### ISSUE TITLE
Multiple task instances of the same node are started 启动了多个相同节点的实例

### ISSUE THREAD

**Issue by baihongbin** [apache/incubator-dolphinscheduler#3914]
version：1.3.2
![image](https://user-images.githubusercontent.com/48641663/96068371-7c83db00-0ece-11eb-88eb-05c149df6213.png)
After the workflow is started, multiple tasks with the same node appear in the task instance.The workflow instance is shown in the figure.
We export the workflow from one platform and import it from another.Both versions are 1.3.2, so I'm not sure if it was the reason for the export.
Generating multiple task instances is not a must, either.What is the cause of this problem?

工作流在启动之后，任务实例中出现了多个相同节点的任务。工作流实例如图所示。
我们是从一个平台导出工作流，然后导入另外一个平台的。版本都是1.3.2，不确定是不是导出的原因。
生成多个任务实例也不是必现的，时有时无。请问这个问题是什么原因导致的呢？

**Comment by dailidong** [comment]
please first English, then you can append description in Chinese

**Comment by baihongbin** [comment]
> please first English, then you can append description in Chinese

it has been modified

**Comment by baihongbin** [comment]
The reason has been found, Because ZooKeeper is unstable, it frequently disconnects.I am not aware of the specific implementation of Dolphinscheduler in this function.At this point, if ZooKeeper is unstable, you may have a bug where the same workflow node executes multiple times.I don't know what you think about that?Will you consider fixing the problem?
Thanks

原因找到了，是因为zookeeper不稳定，存在断连的情况。但是我不是很清楚dolphinscheduler在这一块的具体实现。目前来看，如果zookeeper不稳定，有可能会出现同一个工作流节点执行多次的bug。不知道大家对这个问题怎么看？是否会考虑修复这个问题？
谢谢。

**Comment by dailidong** [comment]
> The reason has been found, Because ZooKeeper is unstable, it frequently disconnects.I am not aware of the specific implementation of Dolphinscheduler in this function.At this point, if ZooKeeper is unstable, you may have a bug where the same workflow node executes multiple times.I don't know what you think about that?Will you consider fixing the problem?
> Thanks
> 
> 原因找到了，是因为zookeeper不稳定，存在断连的情况。但是我不是很清楚dolphinscheduler在这一块的具体实现。目前来看，如果zookeeper不稳定，有可能会出现同一个工作流节点执行多次的bug。不知道大家对这个问题怎么看？是否会考虑修复这个问题？
> 谢谢。

@xingchun-chen ，please check this issue

**Comment by xingchun-chen** [comment]
After waiting for the 1.3.3 release,  then verify this problem
