### ISSUE TITLE
超时告警如何查看,告警发送到哪里

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3928]
版本1.3.2
工作流定义里面对单个节点进行超时告警设置
![image](https://user-images.githubusercontent.com/61308609/96231016-314ef280-0fca-11eb-8198-f6601a3ea702.png)
工作流保存的时候设置的超时告警
![image](https://user-images.githubusercontent.com/61308609/96231359-488de000-0fca-11eb-996a-f2e0e878c5ed.png)

想问下这些超时告警信息是在哪里查看啊

**Comment by baihongbin** [comment]
Should be sent to the alarm receiving email/enterprise WeChat/SMS, the specific need to see your configuration to determine.Reference document [website deployment] (https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html) in **step 6** and **the appendix content** and settings related to the security center > alarm group in the dolphinscheduler platform.
In addition, tips: Please use English to ask questions, you can add Chinese description at the end.

应该是发送到告警接收邮箱/企业微信/短信，具体需要查看你的配置来确定。参考[官网部署文档](https://dolphinscheduler.apache.org/zh-cn/docs/1.3.2/user_doc/cluster-deployment.html)中的 **第6步** 和 **附录内容**，还有调度平台中的 安全中心>告警组 相关设置。
另外，友情提示：请使用英文提问，可以在后边添加中文描述。

**Comment by xingchun-chen** [comment]
The title has not been updated in English for a long time, it will be closed.
 If there is any problem, please use the English title and reopen it
