### ISSUE TITLE
[Improvement][db operation] mybatis mapper xml dynamic sql should not use too much "select *"

### ISSUE THREAD

**Issue by hermeshephaestus** [apache/incubator-dolphinscheduler#3933]
Now, DS use mybatis as orm framework. There's too much "select *", which will affect database query performance .

**Comment by hermeshephaestus** [comment]
I will optimize mybatis dynamic sql.

**Comment by hermeshephaestus** [comment]
please check the pr, https://github.com/apache/incubator-dolphinscheduler/pull/3940. @dailidong

**Comment by CalvinKirs** [comment]
close by #3940
