### ISSUE TITLE
[CodeClean][DAO]Remove redundant comments

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3938]
Remove redundant comments
ProcessInstanceMapper# queryProcessInstanceListPaging

![image](https://user-images.githubusercontent.com/39816903/96348654-f5f11880-10dc-11eb-8bec-7dfa637419f0.png)

**Comment by IamMujuziMoses** [comment]
@BoYiZhang @CalvinKirs I made some changes to this issue PR: [1], please review it

[1]: https://github.com/apache/incubator-dolphinscheduler/pull/3942
