### ISSUE TITLE
[Feature][ui] Remove tenant name

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3941]
**Describe the feature**
Remove tenant name

**Is your feature request related to a problem? Please describe.**
The tenant code corresponds to the Linux user code. The tenant code and the tenant name will give the user experience a narrow sense. I think only the tenant code is enough, and the tenant name is removed.

**Describe the solution you'd like**
Remove tenant name

**Additional context**
I will fix it

---
**描述功能**
移除租户名称

**您的功能请求与问题有关吗？ 请描述。**
租户编码对应linux用户编码，租户编码和租户名称会给用户体验有狭义，我认为只存在租户编码就行，去掉租户名称。

**描述您想要的解决方案**
移除租户名称

**其他内容**
我将修复它

**Comment by IamMujuziMoses** [comment]
@zhuangchong @dailidong @lgcareer I am Mujuzi Moses an outreachy application, I am interested in working on this issue

**Comment by zhuangchong** [comment]
> @zhuangchong @dailidong @lgcareer I am Mujuzi Moses an outreachy application, I am interested in working on this issue

This PR has already started, please take a look at other issus, you can also subscribe to the development mailing list to keep the latest information in sync with the community.
https://dolphinscheduler.apache.org/zh-cn/docs/development/contribute.html

**Comment by break60** [comment]
Hello, is this new feature discussed via email?

**Comment by zhuangchong** [comment]
> Hello, is this new feature discussed via email?

Just sent mail to dev mailing list

**Comment by break60** [comment]
> > Hello, is this new feature discussed via email?
> 
> Just sent mail to dev mailing list

ok

**Comment by lgcareer** [comment]
@zhuangchong Hi,Please paste the email thread.The tenant name only the description.I think It not need to remove it.

**Comment by zhuangchong** [comment]
> @zhuangchong Hi,Please paste the email thread.The tenant name only the description.I think It not need to remove it.

this email thread is '[Question][Alert-SPI] Discussion on the interface scheme of the alarm module support service'

The tenant code corresponds to the Linux user code. The tenant code and tenant name will give the user experience a narrow sense. I think there is only one tenant code.

**Comment by dailidong** [comment]
> @zhuangchong Hi,Please paste the email thread.The tenant name only the description.I think It not need to remove it.

so many users be misleaded, as you said, if it is description, it should written as the description, not name
