### ISSUE TITLE
[Improvement]helm does not support storage options

### ISSUE THREAD

**Issue by lose50281** [apache/incubator-dolphinscheduler#3943]
**Describe the question**
Currently installing dolphinscheduler through helm does not enable the HDFS enabling option, but using the resource center in dolphinscheduler requires HDFS to be mandatory

**What are the current deficiencies and the benefits of improvement**
Hope the helm installation method can add support for HDFS parameterization

**Which version of DolphinScheduler:**
 -[1.3.x]

**Comment by chengshiwen** [comment]
Close by #4693, since 1.3.5-release has supported
