### ISSUE TITLE
[improvement]Use binlog or cdc to monitor task completion

### ISSUE THREAD

**Issue by leehom** [apache/incubator-dolphinscheduler#3944]
现状：专门线程MasterTaskExecThread轮询数据库，
  建议：使用binlog 或者 cdc 事件驱动方式，有效减少线程使用，轮询对数据库压力

**Comment by CalvinKirs** [comment]
A good suggestion, but when we use the method of monitoring binlog to implement it, this will bring new technical complexity (we don’t want to rely too much on other components), on the contrary, using this method will also bring other Problems, such as user maintenance costs will also increase

**Comment by CalvinKirs** [comment]
In #4083, we will conduct detailed design discussions on issues and welcome discussions. It is also recommended to subscribe to the dev mailing list. The relevant design will be reflected in the mail.

How to subscribe to email link: https://dolphinscheduler.apache.org/zh-cn/docs/development/subscribe.html
