### ISSUE TITLE
AlertServer  进程多久时间连接不上mysql，就会down掉

### ISSUE THREAD

**Issue by zhangb0120** [apache/incubator-dolphinscheduler#3951]
mysql库有短暂的几分钟的down掉，但是之后就自动起来了，看了一下alert日志，好险是连接不到mysql就自动down掉了
[ERROR] 2020-10-19 18:25:30.601 com.alibaba.druid.pool.DruidPooledStatement:[362] - CommunicationsException, druid version 1.1.14, jdbcUrl : jdbc:mysql://*.*.*.*:3306/dolphinscheduler?characterEncoding=UTF-8&allowMultiQueries=true, testWhileIdle true, idle millis 5004, minIdle 5, poolingCount 4, timeBetweenEvictionRunsMillis 60000, lastValidIdleMillis 5004, driver com.mysql.jdbc.Driver, exceptionSorter com.alibaba.druid.pool.vendor.MySqlExceptionSorter
[ERROR] 2020-10-19 18:25:30.608 com.alibaba.druid.pool.DruidDataSource:[2572] - create connection SQLException, url: jdbc:mysql://172.18.102.53:3306/dolphinscheduler?characterEncoding=UTF-8&allowMultiQueries=true, errorCode 0, state 08S01
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

这个进程多久时间连接不上mysql，就会自动down掉，能否手动设置这个时间

**Comment by zhuangchong** [comment]
AlertServer 只是一个java project，数据库连接使用的是druid连接池，针对数据库连接超时，重试机制，请修改datasource.properties文件内druid相关参数，目前超时设置应该是60s

**Comment by zhuangchong** [comment]
please first English, then you can append description in Chinese

**Comment by zhangb0120** [comment]
> AlertServer is just a java project. The database connection uses the druid connection pool. For the database connection timeout and retry mechanism, please modify the druid related parameters in the datasource.properties file. The current timeout setting should be 60s
> 
> AlertServer 只是一个java project，数据库连接使用的是druid连接池，针对数据库连接超时，重试机制，请修改datasource.properties文件内druid相关参数，目前超时设置应该是60s

这个要如何配置，配置文件里面好像没有默认设置

**Comment by gaojun2048** [comment]
English title please.
