### ISSUE TITLE
新建工作流每个任务选择worker分组,运行的时候也选择worker分组,它们的区别是?

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3952]
新建工作流,选择worker分组:
![image](https://user-images.githubusercontent.com/61308609/96545910-e5f35780-12db-11eb-91ba-79a1b48192cd.png)
运行工作流选择worker分组:
![image](https://user-images.githubusercontent.com/61308609/96545954-facfeb00-12db-11eb-85ca-58ce0ca3fb16.png)
目前测试是使用的新建工作流任务的时候选择的worker分组,那启动的时候选择的worker分组主要功能是?

**Comment by zhuangchong** [comment]
please first English, then you can append description in Chinese

**Comment by KnightChess** [comment]
for example，suppose there are two queues, queue_one and default(Provided by default), and two task task_one, task_two
| task_one | task_two | run_workflow | task_one_exec | task_two_exec |
| --- | --- | --- | --- | --- |
| queue_one | default | default | queue_one | default |
| queue_one | default | queue_one | queue_one | queue_one |
| queue_one | queue_one | default | queue_one | queue_one |
| default | default | queue_one | queue_one | queue_one |

![image](https://user-images.githubusercontent.com/20125927/97083780-0ce7bb80-1645-11eb-85b7-6242ebd29c65.png)

**Comment by dailidong** [comment]
good issue，but English is needed，if no update exceed 2 days，this issue will be closed
