### ISSUE TITLE
[Bug] After the resource folder is authorized, the authorized user cannot create a folder in it

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#3953]
Resources by A user to create, through the use of the administrator user account resources authorization to B, B users access only to use its resources and cannot create folders and upload files in A directory, such as A user to create the TEST1 folder and upload the TEST. The JAR file, through the administrator account authorized users this folder and file permissions, B B to create TEST1 - > TEST1_1 directory and submit your own file prompt the user does not have operation permissions.

资源由A用户创建，通过使用管理员账号将资源授权给B用户，B用户只有使用其下资源的权限，无法在目录中创建文件夹以及上传文件，如A用户创建了TEST1文件夹并上传了TEST.JAR文件，通过管理员账号授权B用户此文件夹以及文件权限，B想在其中创建TEST1->TEST1_1目录并提交自己的文件提示当前用户没有操作权限。

**Comment by CalvinKirs** [comment]
Please provide your version

btw，Please use English for communication, thx

**Comment by baijun** [comment]
version 1.3.2

**Comment by xingchun-chen** [comment]
Are there other files in the TEST1 directory? If only one file in the directory is authorized, there is no directory authority. Only when the directory is authorized, will there be operation authority

**Comment by baijun** [comment]
@xingchun-chen You cannot directly authorize a directory without files in it. As you said, there is only one file in the directory, and the directory and files are created by the directory creator.
 
目录中如果没有文件是无法对目录直接授权的，如您所说目录中只有一个文件，目录以及文件都是由目录创建者创建。
![image](https://user-images.githubusercontent.com/7664170/96571998-e81add80-12fe-11eb-8200-b02920c83104.png)

**Comment by baijun** [comment]
@xingchun-chen And I found the authorization is in view of the files in the directory, and is not A directory, the user to create A after upload multiple files in A directory in the directory, through the admin account after this directory permissions awarded B users, is directed against the file directory, B directory is not able to in the user to create A directory to any folder to create and file upload。 

并且我发现授权其实是针对目录中的文件，并不是目录，A用户创建目录后上传多个文件在A目录后，通过admin账号授予B用户此目录权限后，也是针对目录中的文件，B目录是不能够在A用户创建的目录中进行任何文件夹创建以及文件上传的

**Comment by xingchun-chen** [comment]
I tried my local code , authorized the files in the directory to user B, user B can create files in the directory. Are you sure the code is up to date?

**Comment by baijun** [comment]
@xingchun-chen My version is 1.3.2 Release. After user A creates the directory, can you grant the directory permission to user B through the administrator?What is your version?

我的版本是1.3.2 release，A用户创建完目录后您是可以通过管理员给B用户授予目录的权限？您的版本是什么版本？

![image](https://user-images.githubusercontent.com/7664170/96574549-2e257080-1302-11eb-9141-a774027b5a25.png)

**Comment by xingchun-chen** [comment]
cannot authorize a directory, you can only authorize files in the directory, but you can create files after authorization. Creating a directory and uploading files do report an error of no permission

**Comment by lgcareer** [comment]
@baijun  It's not a bug,the design is that authorzie file only.
