### ISSUE TITLE
工作流实例->双击任务->查看历史

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3954]
1.从工作流实例-->双击任一任务-->查看历史
![image](https://user-images.githubusercontent.com/61308609/96556641-d419b080-12eb-11eb-9d11-aaf4f8a226fc.png)
2.点击查看历史,进入的只是当前这次执行的工作流实例任务实例
![image](https://user-images.githubusercontent.com/61308609/96556693-e398f980-12eb-11eb-8722-5f3f77f1268d.png)
3.再次点击  任务实例  才出现此任务的所有历史信息
![image](https://user-images.githubusercontent.com/61308609/96557252-949f9400-12ec-11eb-8375-b98fa83552e2.png)

**Comment by CalvinKirs** [comment]
hi, can you provide your version.
btw, please use English for communication, thx

**Comment by xingchun-chen** [comment]
The function design is like this, the task history viewed from the process instance is only the current task, but all task instances are queried through the task instance page

**Comment by 13430647361** [comment]
After testing, I found this design reasonable. First, I showed the task instance of this workflow instance, and then I showed all the running instances of this task by clicking on the task instance.
测试到后面,觉得这个设计挺合理的,先展示此工作流实例的任务实例,通过点击任务实例再显示此任务的所有运行过的实例.
