### ISSUE TITLE
工作流中引用了资源中心的文件,但是资源中心文件可删除,工作流定义中无法删除更改

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3955]
*For better global communication, please give priority to using English description, thx! *
版本1.3.2
资源中心删除文件
进入工作流定义查看更改,无法更改
![image](https://user-images.githubusercontent.com/61308609/96570011-6cb82c80-12fc-11eb-820f-dd468f59fbd3.png)

**Comment by xingchun-chen** [comment]
This issue has been resolved in the 1.3.3-release branch. For specific solutions, please refer to issue #3719 
please update the title in English, thanks

**Comment by dailidong** [comment]
English is needed， no update for 6 days， this issue will close
