### ISSUE TITLE
[Question][Alert-SPI] Discussion on the interface scheme of the alarm module support service

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3959]
#3754

**Describe the question**
Alert module support service for other service invoke，The interface implementation scheme is to use netty?grpc?restful?

The master/worker/logger in the project all use netty to communicate, and it is recommended to use netty for the alert module interface. Do you have any suggestions for this?

**Which version of DolphinScheduler:**
 -[alert_plugin_design]

---
**描述问题**
Alert模块支持服务用于其他服务调用，接口实现方案是使用netty？grpc？restful？

项目中master/worker/logger都是使用netty通信，alert模块接口建议也使用netty,您对此有什么建议吗？

**哪个版本的DolphinScheduler：**
  -[alert_plugin_design]

**Comment by gaojun2048** [comment]
netty +1

**Comment by zhuangchong** [comment]
After discussion,Have been implemented using netty.
