### ISSUE TITLE
sub_process The timeout warning does not take effect

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3964]
versions 1.3.2
设置子模块"超时告警"
![image](https://user-images.githubusercontent.com/61308609/96696020-e1eb3680-13bc-11eb-910f-28416e1ed748.png)
调用的子模块设置休眠100秒
![image](https://user-images.githubusercontent.com/61308609/96696127-00513200-13bd-11eb-8950-d7423380af36.png)
最终结果没有超时告警也没有超时失败.

并且查看工作流实例的时候,先点击别的子模块,再点击设置超时的子模块,超时告警不会显示被选中了
![image](https://user-images.githubusercontent.com/61308609/96696330-3989a200-13bd-11eb-8c1e-88c49cb1fa67.png)

**Comment by xingchun-chen** [comment]
Thank you for your feedback, it will be revised in the next version

**Comment by xingchun-chen** [comment]
### actual results:
After the timeout fails, the process instance is in the failed state, but the task instance is in the kill state
### expect  result:
After the timeout fails, both the task instance and the process instance are in a failed state
