### ISSUE TITLE
The judgment condition of dependence

### ISSUE THREAD

**Issue by 13430647361** [apache/incubator-dolphinscheduler#3970]
I would like to know how to judge this dependency condition. I ran the test_1 workflow three times yesterday, the first time was successful, and the second two times failed. However, I managed to run the test_1 workflow successfully on the selection day yesterday, and if I set the same condition today, I would fail
请问一下这个依赖条件是如何判断的,test_1工作流昨天我运行了三次,第一次成功,后两次失败,但是依赖条件选择日 昨天,却能运行成功,设置今天一样的情况,就会运行失败
I think it's the result of selecting the last run within the qualifying time frame
我认为应该是选择符合条件的时间范围内的最后一次运行的结果吧
![image](https://user-images.githubusercontent.com/61308609/96820457-9c7c4700-1458-11eb-9312-4dc3d5733d5b.png)
![image](https://user-images.githubusercontent.com/61308609/96820513-b74ebb80-1458-11eb-8e57-df0a2557145b.png)

**Comment by KnightChess** [comment]
code in org.apache.dolphinscheduler.server.utils.DependentExecute findLastProcessInterval
- 状态为 running, submit success, ready_pause, ready_stop 的流程实例
- 非上述状态，存在周期调度类型的，并且不存在手动触发的，判断周期调度的实例
- 非上述状态，存在用户手动触发的，并且不存在周期调度的，判断用户手动触发的实例
- 非上述状态，如果都存在，判断手动触发和周期调度最后更新状态的时间，最新的作为判断依据
应该是这个

**Comment by xingchun-chen** [comment]
Is your problem solved？
