### ISSUE TITLE
[Bug][API] Start a process definition, the scheduling time of the related process instance is null

### ISSUE THREAD

**Issue by hermeshephaestus** [apache/incubator-dolphinscheduler#3976]
<img width="1333" alt="WeChatWorkScreenshot_8982ea6c-f2dc-44b8-8d64-659ef0d82901" src="https://user-images.githubusercontent.com/42707541/96894309-2ad6e400-14be-11eb-9968-de002ebca85d.png">

<img width="1326" alt="WeChatWorkScreenshot_e04d738b-e360-4f38-b2ff-d489a808a165" src="https://user-images.githubusercontent.com/42707541/96894447-404c0e00-14be-11eb-841d-2b53134106a6.png">

**Which version of Dolphin Scheduler:**
 -[1.3.2-preview]

**Requirement or improvement**
- the scheduling time is nessarry!

**Comment by xingchun-chen** [comment]
Design like this，it isn't a bug.
The scheduling time is only available for  scheduled by timing. 
Manually running workflows do not display the scheduling time, but will display the start time

**Comment by hermeshephaestus** [comment]
OK, thanks! @xingchun-chen
