### ISSUE TITLE
[Bug][API] Creating a process definition without enabling timeout alarm! Starting it occurs an exception!

### ISSUE THREAD

**Issue by hermeshephaestus** [apache/incubator-dolphinscheduler#3977]
<img width="1331" alt="WeChatWorkScreenshot_3dfced81-1b57-48b6-bbb1-8ae8c7d6c5b1" src="https://user-images.githubusercontent.com/42707541/96898572-73909c00-14c2-11eb-8fa8-5a7d7858d05b.png">
<img width="1332" alt="WeChatWorkScreenshot_e75d86c4-23ef-483f-afb8-518e5a641548" src="https://user-images.githubusercontent.com/42707541/96898584-75f2f600-14c2-11eb-9b6d-47bff94adc27.png">
<img width="1355" alt="WeChatWorkScreenshot_7254d327-dbc4-4ae3-80dd-2a89afa2e080" src="https://user-images.githubusercontent.com/42707541/96898587-77242300-14c2-11eb-9976-973eb0bd53d0.png">

 -[1.3.2-preview]

**Requirement or improvement**
- The exception should not happen for this situation.

**Comment by hermeshephaestus** [comment]
I will fix it by myself as soon!

**Comment by xingchun-chen** [comment]
I did not reproduce your question. Are you using the latest source code of 1.3.2?

**Comment by hermeshephaestus** [comment]
Yeah, I will check the code! @xingchun-chen

**Comment by hermeshephaestus** [comment]
The latest branch code does not have this error. I will close this issue. @xingchun-chen .
