### ISSUE TITLE
[Question] How to transfer dag files from test environment to product environment quickly.

### ISSUE THREAD

**Issue by yangrong688** [apache/incubator-dolphinscheduler#3981]
**Describe the question**
How to transfer files from test environment to product quickly without copy & paste.

Does anyone has any idea, please share it, thanks.

**Which version of DolphinScheduler:**
 -[1.3.2]

**Comment by hermeshephaestus** [comment]
There is the function about exporting process definition and importing process definition.
<img width="1337" alt="WeChatWorkScreenshot_197cce0e-45bd-4074-a1fb-1aaa1f19bc5c" src="https://user-images.githubusercontent.com/42707541/96989502-58706b80-1558-11eb-9daf-c27df99747cc.png">
 @yangrong688

**Comment by yangrong688** [comment]
@hermeshephaestus OK, I got it. Thanks for your help.

**Comment by hermeshephaestus** [comment]
OK, you can close this issue, shortly after this. @yangrong688
