### ISSUE TITLE
[Improvement][UI] Enhance user experience, add close button to file details page

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#3988]
Enhance user experience, add close button to file details page

![image](https://user-images.githubusercontent.com/39816903/97111073-b39c8c80-1717-11eb-88ca-7d9e42a8a5d7.png)

**Comment by yangyichao-mango** [comment]
Good feature， if user click the closed button，what the page the browser will route to？

**Comment by BoYiZhang** [comment]
> Good feature， if user click the closed button，what the page the browser will route to？

Return to previous page
pr: 
https://github.com/apache/incubator-dolphinscheduler/issues/3988
