### ISSUE TITLE
删除用户时，没有校验该用户下面有相应的数据，导致用户删除会把相关任务逻辑删除

### ISSUE THREAD

**Issue by tianmingqin** [apache/incubator-dolphinscheduler#3992]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
English is needed，and please describe clearly，then submit new issue，thx
