### ISSUE TITLE
[Question][Alert-SPI] SqlTask should send notifications by alert server api,Alert server address configuration discussion

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#3997]
#3749

**Describe the question**
In the case of the SqlTask task, the task needs to send messages synchronously, and the final running status of this task depends on whether the message is sent successfully. Therefore, the alarm api needs to send messages synchronously.
Have a problem at this time? There are two ways to get the alert api for the SqlTask task: put the alertserver address into the configuration file of the worker or master; put the alertserver address into the zk registration center; it is recommended to use the first one, the first version is simple to implement, and there will be alertserver load later Related issues will also consider registry issues
Do you have any suggestions?
email discussion address:
https://lists.apache.org/thread.html/rc04ff46d15bfdc40463c68cc409de2f554ff6e9bfb82f62afc58f71a%40%3Cdev.dolphinscheduler.apache.org%3E

Welcome everyone to participate in the email discussion

**Which version of DolphinScheduler:**
 -[alert_plugin_design]

---
**描述问题**
在SqlTask任务情况下，任务需要同步发送消息，此任务的最终运行状态取决于消息是否发送成功。 因此，告警api需要同步发送消息。
此时有个问题？SqlTask 任务如何获取告警api，下面有两种方式：alertserver地址放入worker或master的配置文件；alertserver地址放入zk注册中心; 推荐使用第一种，第一版先简单实现，后期会有alertserver负载相关问题也会考虑注册中心问题。
大家有什么建议么？

**哪个版本的DolphinScheduler：**
  -[alert_plugin_design]

**Comment by gaojun2048** [comment]
I think put the alertserver address into the configuration file of the worker or master is better now.
