### ISSUE TITLE
The timed task execution itself terminates

### ISSUE THREAD

**Issue by lucky9322** [apache/incubator-dolphinscheduler#4001]
![image](https://user-images.githubusercontent.com/11935073/97380134-5b28e300-1901-11eb-84ff-48f976b559e3.png)
1.提示接下来五次的执行时间是 只执行五次嘛
2.执行开始时间为什么从整点开始的

**Comment by dailidong** [comment]
as a global project please first choose English， then you can append title or description in Chinese.

**Comment by samz406** [comment]
1 this is just test，The background will trigger tasks according to the time period you specify
2 The result of your cron expression is like this
1 这只是前端页面测试下cron表达式是否正确，只是展示最近5次执行时间。
2 你的表达式就是整点开始执行，是正确的，可以找个在线cron表达式验证下。

![image](https://user-images.githubusercontent.com/3055810/97382779-1b64fa00-1907-11eb-9645-56d308cc8819.png)

**Comment by lucky9322** [comment]
> 1 this is just test，The background will trigger tasks according to the time period you specify
> 2 The result of your cron expression is like this
> 1 这只是前端页面测试下cron表达式是否正确，只是展示最近5次执行时间。
> 2 你的表达式就是整点开始执行，是正确的，可以找个在线cron表达式验证下。
> 
> ![image](https://user-images.githubusercontent.com/3055810/97382779-1b64fa00-1907-11eb-9645-56d308cc8819.png)

还有一个问题就是，执行了十几次之后 停止了
