### ISSUE TITLE
[Improvement][common/remote] Json util code integration,remove the remote module json util

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#4012]
**Describe the question**
Json util code integration, remove the remote module json util.

**What are the current deficiencies and the benefits of improvement**
There are multiple versions of Json tool classes.

**Which version of DolphinScheduler:**
 -[dev]

I will fix it

---
**描述问题**
Json util代码集成，移除remote模块json util

**目前的不足之处和改进的好处**
存在多个版本Json 工具类

**哪个版本的DolphinScheduler：**
  -[开发]

我将修复它

**Comment by dailidong** [comment]
solved
