### ISSUE TITLE
Sometimes tasks cannot be assigned

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#4016]
**Describe the bug**
Sometimes tasks cannot be assigned，the state is still start successfully.
below error in master  log 

[ERROR] 2020-11-02 16:16:30.001 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=2175589, bodyLen=7686] due to no suitable worker , current task need to  172.xxx.xxx.xxx worker group execute
        at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueue
Consumer.java:145)
        at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.
java:114)
 

**To Reproduce**
don't konw how to reproduce, sometime and some tasks have this problem.

I don't think this is the same as issue #3480, 
zookeeper.dolphinscheduler.root is default in zookeeper.properties, not multi directories
zookeeper.dolphinscheduler.root=/dolphinscheduler

the version is 1.3.2

**Comment by xingchun-chen** [comment]
Design like this. You need to start the worker  172.xxx.xxx.xxx

**Comment by JunjianS** [comment]
> Design like this. You need to start the worker 172.xxx.xxx.xxx

thanks, the problem has been solved，because there is no worker 172.xxx after upgrading 1.3.2  , the process with worker 172.xxx was defined in version 1.2 . but i don'tknow why this process cause some other tasks cannot be designed.
