### ISSUE TITLE
Error: Error while compiling statement: FAILED: SemanticException Line 1:27 Table or database name may not contain dot(.) character 'dw_test.ods_user_user_douyin' (state=42000,code=40000)

### ISSUE THREAD

**Issue by ximengyun** [apache/incubator-dolphinscheduler#4019]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.
海豚调度使用sqoop导数据到hive3，因为hive3不支持'库名.表名',character 'dw_test.ods_user_user_douyin'，导致报错，
建议生成sqoop脚本的时候，把库名和表明分开

**Which version of DolphinScheduler:**
DolphinScheduler 1.3.2

**Comment by xingchun-chen** [comment]
who can fix it?

**Comment by Eights-Li** [comment]
I will fix it
