### ISSUE TITLE
1.Xupgrade1.3.2 报错  report errors

### ISSUE THREAD

**Issue by q443048756** [apache/incubator-dolphinscheduler#4022]
1.Scheduled tasks are not executed
2.Manual tasks can be performed
3.master log
[ERROR] 2020-11-04 11:21:51.172 org.quartz.impl.jdbcjobstore.JobStoreTX:[3956] - MisfireHandler: Error handling misfires: Couldn't store trigger 'jobgroup_5.job_608' for 'jobgroup_5.job_608' job:Couldn't retrieve job because a required class was not found: cn.escheduler.api.quartz.ProcessScheduleJob
org.quartz.JobPersistenceException: Couldn't store trigger 'jobgroup_5.job_608' for 'jobgroup_5.job_608' job:Couldn't retrieve job because a required class was not found: cn.escheduler.api.quartz.ProcessScheduleJob

**Comment by xingchun-chen** [comment]
Repeat with #4023, will close
