### ISSUE TITLE
1.X upgrade 1.3.2 报错  report errors

### ISSUE THREAD

**Issue by q443048756** [apache/incubator-dolphinscheduler#4023]
1.Scheduled tasks are not executed
2.Manual tasks can be performed
3.master log
[ERROR] 2020-11-04 11:21:51.172 org.quartz.impl.jdbcjobstore.JobStoreTX:[3956] - MisfireHandler: Error handling misfires: Couldn't store trigger 'jobgroup_5.job_608' for 'jobgroup_5.job_608' job:Couldn't retrieve job because a required class was not found: cn.escheduler.api.quartz.ProcessScheduleJob
org.quartz.JobPersistenceException: Couldn't store trigger 'jobgroup_5.job_608' for 'jobgroup_5.job_608' job:Couldn't retrieve job because a required class was not found: cn.escheduler.api.quartz.ProcessScheduleJob

**Comment by xingchun-chen** [comment]
Check if QRTZ_JOB_DETAILS.JOB_CLASS_NAME is org.apache.dolphinscheduler.service.quartz.ProcessScheduleJob
![image](https://user-images.githubusercontent.com/55787491/98082704-247c3b00-1eb4-11eb-9358-93666a9fe12b.png)

**Comment by q443048756** [comment]
> 检查QRTZ_JOB_DETAILS.JOB_CLASS_NAME是否为org.apache.dolphinscheduler.service.quartz.ProcessScheduleJob
> ![图片](https://user-images.githubusercontent.com/55787491/98082886-7329d500-1eb4-11eb-90c3-e909d81eadf9.png)

1.测试了 单独修改字段对新老任务都没有效果
2.quartz.properties文件中的instanceName参数要和1.X配置一致，否则quartz会创建新实例，之前版本创建的工作流都不会被调度
3.修复完改bug后新建定时任务没问题但是老任务报错
[ERROR] 2020-11-04 15:32:45.097 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=39802, bodyLen=5396] due to no suitable worker , current task need to default worker group execute
通过查询配置文件发现1.3.2的conf/worker.properties下worker.groups=localhost
排查问题过程中突然不管新老任务都开始报上述错误
将worker.groups=localhost修改为default    任务又报错current task need to localhost worker group execute
目前还未定位到问题 希望得到帮助

**Comment by xingchun-chen** [comment]
What is selected for worker grouping in workflow definition？

**Comment by dailidong** [comment]
any update?
