### ISSUE TITLE
worker分组有一个节点为改为其他，但是页面显示为default

### ISSUE THREAD

**Issue by zhangzhen768** [apache/incubator-dolphinscheduler#4024]
![image](https://user-images.githubusercontent.com/63232431/98082667-12020180-1eb4-11eb-89c0-f82badfad27a.png)
![image](https://user-images.githubusercontent.com/63232431/98082686-1c240000-1eb4-11eb-82fc-62d194e1ea18.png)

**Comment by xingchun-chen** [comment]
please update the title in English , Thanks

**Comment by dailidong** [comment]
no update from user
