### ISSUE TITLE
could SQL node show the HIVE MR progress logs

### ISSUE THREAD

**Issue by szsuyuji** [apache/incubator-dolphinscheduler#4026]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the improvement is.

could sql node show the MR progress  ,tks

**What are the current deficiencies and the benefits of improvement**
- A clear and concise description of the current deficiencies and the benefits of this improvement.

**Which version of DolphinScheduler:**
 -[1.3.2]

**Describe alternatives you've considered**
A clear and concise description of any alternative improvement solutions you've considered.

**Comment by dailidong** [comment]
show process log on the UI or something else?

**Comment by szsuyuji** [comment]
logs screen 
![image](https://user-images.githubusercontent.com/1931764/99332527-3352ec80-28bb-11eb-969e-14a9b9b24e5d.png)
does not the show MR logs
can we show the logs like 
![image](https://user-images.githubusercontent.com/1931764/99337840-094ef980-28be-11eb-999d-c625e0d5defa.png)

**Comment by xingchun-chen** [comment]
Everyone can discuss whether this requirement can be done ,or who is willing to realize it

**Comment by dailidong** [comment]
> logs page
> ![image](https://user-images.githubusercontent.com/1931764/99332527-3352ec80-28bb-11eb-969e-14a9b9b24e5d.png)
> it does not the show MR progress logs
> can we show the logs like
> ![image](https://user-images.githubusercontent.com/1931764/99337840-094ef980-28be-11eb-999d-c625e0d5defa.png)
> @dailidong

as far as I know, SQL node can not show the processing log, because the server side not return the process through jdbc interface.  please correct me if I am wrong
