### ISSUE TITLE
[Feature][SPI] Implement SMS Alert Plugin

### ISSUE THREAD

**Issue by samz406** [apache/incubator-dolphinscheduler#4027]
Implement SMS  Alert Plugin

#3049

I will finish it.

**Comment by CalvinKirs** [comment]
Hi, as far as I know, SMS vendors have not formed a set of standards. Can we provide implementation? If not, it can only be implemented by the user.

嗨，据我所知，目前短信厂商并没有形成一套标准，我们是否可以提供实现呢？如果不能的话，只能用户自己实现了。

**Comment by samz406** [comment]
Hi.You are right. We are using short message service from two suppliers in our current project. They are called through HTTP request, and the request parameters are different. What I want is to send through HTTP request. Request parameters are not dead written in the configuration. Load the required configuration at startup and try to make it universal. Do you think this is feasible. No, I'll close the issue


你说的有道理，我们目前项目中用的有两家供应商的短息服务。都是通过http请求方式调用，请求参数有差别。我想的是通过http请求方式实现发送功能。请求参数在配置中不写死。启动时加载所需配置,尽量做成通用。你们觉得这样是否可行。不行我就关闭issue

**Comment by gaojun2048** [comment]
If you are use http/https to send message . You need a http/https alert plugin. So you can implement a http/https plugin .

**Comment by CalvinKirs** [comment]
> Hi.You are right. We are using short message service from two suppliers in our current project. They are called through HTTP request, and the request parameters are different. What I want is to send through HTTP request. Request parameters are not dead written in the configuration. Load the required configuration at startup and try to make it universal. Do you think this is feasible. No, I'll close the issue
> 
> 你说的有道理，我们目前项目中用的有两家供应商的短息服务。都是通过http请求方式调用，请求参数有差别。我想的是通过http请求方式实现发送功能。请求参数在配置中不写死。启动时加载所需配置,尽量做成通用。你们觉得这样是否可行。不行我就关闭
> @gaojun2048

very good!

I checked it again today, and there is no difference in the process. They are all in the form of http. For the time being, there are no additional SMS vendors that need to dynamically obtain the token first. As you said, I think we can solve the difference in parameters.

very good！

我今天核查了一遍，流程上没有什么差异，都是通过http的形式，暂时没有那种额外的需要先动态获取token的短信厂商。正如你所说，参数上的差异我想我们是可以解决的。
