### ISSUE TITLE
[Feature]The memory of worker, master, and other services does not need to be the same.(worker、master和其他服务的内存不需要是一样的)

### ISSUE THREAD

**Issue by lenboo** [apache/incubator-dolphinscheduler#403]
The memory of worker, master, and other services does not need to be the same.

---
worker、master和其他服务的内存不需要是一样的

**Comment by chengshiwen** [comment]
Close by #5158 which introduced `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`
