### ISSUE TITLE
[Bug][Workflow instance] task instance loss

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#4032]
Sometimes the task cannot be executed correctly, it is shown that the task instance is killed, there is no obvious error when viewing the master log, and the task is not submitted to the worker. This problem does not often occur, and it runs normally after re-running. May I ask why this is caused?

![image](https://user-images.githubusercontent.com/7664170/98329440-30423b80-2033-11eb-85f9-5815c41bb2c5.png)
![image](https://user-images.githubusercontent.com/7664170/98329498-510a9100-2033-11eb-88c0-6734e90cbb20.png)
![image](https://user-images.githubusercontent.com/7664170/98329608-90d17880-2033-11eb-830c-728b03ba4de9.png)

任务有时候不能正确执行，查看任务实例显示被kill掉，查看master日志并没有什么明显错误，并且任务也没有被提交到worker里，这个问题不是经常出现，并且重跑后运行正常，请问下这是什么原因导致的。

**Comment by xingchun-chen** [comment]
which version?

**Comment by dailidong** [comment]
no response from user, I will close this issue temporarily,  please re-open it when issue update
