### ISSUE TITLE
When a task is executed, as long as the tenant of the task is not the root tenant, the execution will fail,

### ISSUE THREAD

**Issue by LINKPEF** [apache/incubator-dolphinscheduler#4040]
**Describe the question**
When a task is executed, as long as the tenant of the task is not the root tenant, the execution will fail,the logs as fallows:
[INFO] 2020-11-09 17:15:03.441  - [taskAppId=TASK-9-86-87]:[121] -  -> /tmp/dolphinscheduler/exec/process/2/9/86/87/9_86_87.command: line 4: /home/dolphinscheduler/dolphinscheduler/conf/env/dolphinscheduler_env.sh: Permission denied

![image](https://user-images.githubusercontent.com/43411309/98524220-eadf7180-22b1-11eb-8dcb-4ab3de162b16.png)

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Comment by xingchun-chen** [comment]
You need to change the permissions of the /tmp/dolphinscheduler directory to deploy user permissions

**Comment by LINKPEF** [comment]
> You need to change the permissions of the /tmp/dolphinscheduler directory to deploy user permissions

do you mean I should use the command ‘chown -R ’ to the deploy user ? I do as what I say but still fail

**Comment by xingchun-chen** [comment]
/home/dolphinscheduler also needs to change permissions to deploy user permissions

**Comment by LINKPEF** [comment]
OK，thank you very much!
