### ISSUE TITLE
[Question] i want to konw dolphinscheduler have docker image to use

### ISSUE THREAD

**Issue by lucky9322** [apache/incubator-dolphinscheduler#4041]
现在 dolphinscheduler 有没有 镜像服务去使用

**Comment by xingchun-chen** [comment]
The community partners provide a mirror: https://hub.docker.com/r/rockxsj/dolphinscheduler

**Comment by lucky9322** [comment]
> The community partners provide a mirror: https://hub.docker.com/r/rockxsj/dolphinscheduler

thanks   😄, i want to know whether this image supports mysql or not

**Comment by gabrywu** [comment]
> > The community partners provide a mirror: https://hub.docker.com/r/rockxsj/dolphinscheduler
> 
> thanks 😄, i want to know whether this image supports mysql or not

you can play with it, and get your answer
