### ISSUE TITLE
The shell script task cannot be executed, there is no log, but SQL can.

### ISSUE THREAD

**Issue by LINKPEF** [apache/incubator-dolphinscheduler#4043]
The shell script task cannot be executed, there is no log, but SQL can.
the log as fallows:
![image](https://user-images.githubusercontent.com/43411309/98636668-4a955580-2362-11eb-912f-b81839579fff.png)

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Comment by xingchun-chen** [comment]
You can check the worker log ,whether is error

**Comment by LINKPEF** [comment]
thanks,I reinstalled and no problems.
