### ISSUE TITLE
[Feature][api-dao] ciphertext for password in datasource.properties

### ISSUE THREAD

**Issue by zhangjingwei-gwi** [apache/incubator-dolphinscheduler#4045]
It's not security for putting real password in the configuration file.
So it's necessary to use ciphertext in configuration file.

**Comment by CalvinKirs** [comment]
This seems unnecessary. Even if we encrypt, the encryption method needs to be placed in our code. Or the relevant key also needs to be stored on the server, so the password is also an available state. This should be a problem of the safe work of operation and maintenance personnel, not what we should solve.
