### ISSUE TITLE
Is it necessary save definitionList when i add DEPENDENT type task.

### ISSUE THREAD

**Issue by jiakai908** [apache/incubator-dolphinscheduler#4047]
-[1.3.0]
when i add DEPENDENT task , i found it save the parameter definitionList that i have already done the dag list . i think it is not necessary. first,it lookss like too many  when my dag list is very high. second,when i update this task,it shows the dag list maybe is
not all. Maybe I don't understand everything，Please forgive me.

**Comment by xingchun-chen** [comment]
version 1.3.2+ had solved the problem,  you can refer to issue #3351
