### ISSUE TITLE
[Bug][qrtz_tirggers module] qrtz_ data Import export exception

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#4051]
1. I set up a new timed task and confirmed that it could run normally, which was executed every minute as follows.
1、我建立了一个新的定时任务，并且确认他可以正常运行，如下每一分钟都在执行。
![1](https://user-images.githubusercontent.com/7664170/98786865-b3033600-2439-11eb-8b04-f54f65bb76e8.jpg)

2. Then I tried to export the backup records in the database, such as exporting in SQL.
2、之后我尝试将数据库中记录备份导出，例如以sql的方式导出。
INSERT INTO "qrtz_triggers"("sched_name", "trigger_name", "trigger_group", "job_name", "job_group", "description", "next_fire_time", "prev_fire_time", "priority", "trigger_state", "trigger_type", "start_time", "end_time", "calendar_name", "misfire_instr", "job_data") VALUES ('DolphinScheduler', 'job_40', 'jobgroup_9', 'job_40', 'jobgroup_9', NULL, 1605079680000, 1605079620000, 5, 'ACQUIRED', 'CRON', 1605024000000, 4760697600000, NULL, 2, E'\\\\x'::bytea);

3. The reason why I do this is to simulate the process of database switch and then clear the data in the QRTZ_triggers table to simulate a new environment as follows:
3、我之所以这么做是在模拟切换数据库的过程，之后清空qrtz_triggers表中数据，模拟一个新的环境，如下：
![2](https://user-images.githubusercontent.com/7664170/98786956-d201c800-2439-11eb-9445-dc28a80d96d4.png)

4. Finally, I imported the exported record into Qrtz_TIRGGERS, as follows:
4、最后我将导出的记录导入到qrtz_tirggers,如下：
![3](https://user-images.githubusercontent.com/7664170/98787059-f493e100-2439-11eb-9b8e-4ba80dadaff7.png)

5. After that, the timer did not work, and an error occurred when editing the timer to go online, as follows:
5、之后定时不工作了，并且编辑定时器上线出错，如下：
![4](https://user-images.githubusercontent.com/7664170/98787190-25741600-243a-11eb-9c5d-979da0a09511.png)

**Comment by baijun** [comment]
Triggers job_data in qrtz_triggers? Why is \x saved????
qrtz_triggers中的job_data为什么存的是个\x？？？？
![image](https://user-images.githubusercontent.com/7664170/98802998-18155680-244f-11eb-87f0-8a093dd53245.png)

**Comment by xingchun-chen** [comment]
Who can look the problem?

**Comment by X-MerlinLee** [comment]
I think it is not a bug. at least, it has nothing to do with this project. As @baijun mentioned, 'job_data' should be the binary result of Java object serialization, the results of dumping blob data is not as expected.

**Comment by X-MerlinLee** [comment]
Maybe you should look for a better PostgreSQL synchronous replication tool.  @baijun

**Comment by CalvinKirs** [comment]
hi, as @X-MerlinLee said, this is not an error in this project, you should try other synchronization tools
