### ISSUE TITLE
[Bug][DAO] 1.3.2 upgrade to 1.3.3, cant't run a dag node alone ,NPE problem

### ISSUE THREAD

**Issue by szsuyuji** [apache/incubator-dolphinscheduler#4059]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
after update to 13.3 ,when run a dag task node  alone,a NPE problem throwed 

**Screenshots**
![image](https://user-images.githubusercontent.com/1931764/98904307-5022a500-24f4-11eb-82db-d503482ee725.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
who can look the problem?

**Comment by X-MerlinLee** [comment]
I would like to have a try if nobody.

**Comment by CalvinKirs** [comment]
This issue has been fixed in #4090

**Comment by CalvinKirs** [comment]
> I would like to have a try if nobody.

Hi,   very welcome, but this problem has been fixed, you can try to find an easy-to-fix tag in the issues to complete it.
