### ISSUE TITLE
条件分支节点bug

### ISSUE THREAD

**Issue by zhangb0120** [apache/incubator-dolphinscheduler#4066]
*For better global communication, please give priority to using English description, thx! *
1.3.3 Conditional branch has a bug where even if execution fails, the successful branch will be executed

![image](https://user-images.githubusercontent.com/34859368/99067042-f3eb7e00-25e4-11eb-9f3b-96f98aaa5cb6.png)
1.3.3 版本条件分支有一个bug，就算执行失败，也会执行成功的那一个分支

**Comment by xingchun-chen** [comment]
Take a screenshot to see the configuration of your DAG condition node, whether the custom parameter is configured with the pre-node state
Use condition node refer to #2652

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by CalvinKirs** [comment]
hi, is your problem solved?

**Comment by chengshiwen** [comment]
Close the question since it has been replied
