### ISSUE TITLE
User account multi-tenant association（用户账户多租户关联）

### ISSUE THREAD

**Issue by jyouAc** [apache/incubator-dolphinscheduler#407]
It is recommended to increase the user's multi-tenancy function. You can specify the tenant when writing the workflow.

---
建议增加用户多租户的功能，在编写工作流的时候可以指定租户

**Comment by dailidong** [comment]
good issue, thx!

Can you describe more in detail?  Is it a tenant for a workflow or a tenant for each task?

**Comment by jyouAc** [comment]
> good issue, thx!
> 
> Can you describe more in detail? Is it a tenant for a workflow or a tenant for each task?

同一个流程比较长的工作流的时候因为涉及到离线和线上服务器以及不同项目之间的切换，该用户在不同服务器之间的权限不一定一致，特别是离线跟线上。这样编写工作流的时候就涉及到租户切换的问题了。

**Comment by dailidong** [comment]
We are planning to implement a workflow for a tenant. If there are multiple tenants that need to switch, you can use a sub-workflow. Can such an implementation meet your needs?
---
我们正打算实现一个工作流对应一个租户，如果有多个租户需要切换使用，可以使用子工作流，这样的实现是否可以满足你的需求呢？

**Comment by jyouAc** [comment]
> We are planning to implement a workflow for a tenant. If there are multiple tenants that need to switch, you can use a sub-workflow. Can such an implementation meet your needs?
> 
> 我们正打算实现一个工作流对应一个租户，如果有多个租户需要切换使用，可以使用子工作流，这样的实现是否可以满足您的需求呢？

能，期待中

**Comment by lidongdai** [comment]
en , we will implement this feature in version 1.1.0!

**Comment by lenboo** [comment]
每个流程定义可以绑定一个租户，默认是创建者所属的租户，也可以选择其他租户。
任何一个用户在执行这个工作流的时候，worker会使用这个绑定租户执行工作流里面的任务。
一个工作流里面可以添加多个子工作流，子工作流执行的时候，会使用子工作流绑定的租户执行任务。

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
