### ISSUE TITLE
dolphinsheduler1.2.0,任务显示提交成功，不运行(多次出现，严重bug)

### ISSUE THREAD

**Issue by supperchild123** [apache/incubator-dolphinscheduler#4070]
dolphinsheduler1.2.0,任务显示提交成功，不运行(多次出现，严重bug) ，平均一周出现一次；每天晚上还需要人员监控，发现此问题手动重跑，严重影响工作效率，运维成本。
下面是 d_par_branch_info任务提交成功不运行的master日志，和worker分组没关系，worker分组服务器配置正确。

[d_par_branch_info提交成功,不运行.log](https://github.com/apache/incubator-dolphinscheduler/files/5544491/d_par_branch_info.log)

[INFO]11:38:34.174 MasterExecThread:[296] - prepare process :506 end
[INFO]11:38:34.180 MasterExecThread:[792] - add task to stand by list: oas_hrmsubcompany
[INFO]11:38:34.180 ocommon.queue.TaskQueueFactory:[45] - task queue impl use zookeeper 
[INFO]11:38:34.182 MasterExecThread:[801] - remove task from stand by list: oas_hrmsubcompany
[INFO]11:38:34.206 odao.ProcessDao:[769] - start submit task : oas_hrmsubcompany, instance id:506, state: RUNNING_EXEUTION, 
[INFO]11:38:34.217 ocommon.queue.TaskQueueZkImpl:[99] - check task:2_506_2_0_-1 not exist in task queue
[INFO]11:38:34.228 ocommon.queue.TaskQueueZkImpl:[99] - check task:2_506_2_831_-1 not exist in task queue
[INFO]11:38:34.229 odao.ProcessDao:[973] - task ready to queue: TaskInstance{id=831, name='oas_hrmsubcompany', taskType='SHELL', processDefinitionId=120, processInstanceId=506, processInstanceName='null', taskJson='{"depList":[],"dependence":"{}","forbidden":false,"id":"tasks-67877","maxRetryTimes":2,"name":"oas_hrmsubcompany","params":"{\"rawScript\":\"sh /home/infa/dolphin_task/ods_import_new_etl.sh sdata_full OAS SHFW.hrmsubcompany \\\"\\\" ID full \\\\\\\\001 \\\"\\\" \\\"ID,SUBCOMPANYNAME,SUBCOMPANYDESC,COMPANYID,SUPSUBCOMID,URL,SHOWORDER,CANCELED,SUBCOMPANYCODE,OUTKEY,BUDGETATUOMOVEORDER,ECOLOGY_PINYIN_SEARCH,LIMITUSERS,TLEVEL\\\" 20200525\",\"localParams\":[],\"resourceList\":[]}","preTasks":"[]","retryInterval":5,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":false,"interval":0},"timeout":"{\"enable\":false,\"strategy\":\"\"}","type":"SHELL","workerGroupId":-1}', state=SUBMITTED_SUCCESS, submitTime=Sun Jun 14 11:38:34 CST 2020, startTime=Sun Jun 14 11:38:34 CST 2020, endTime=null, host='null', executePath='null', logPath='null', retryTimes=0, alertFlag=NO, flag=YES, processInstance=null, processDefine=null, pid=0, appLink='null', flag=YES, dependency=null, duration=null, maxRetryTimes=2, retryInterval=5, taskInstancePriority=MEDIUM, processInstancePriority=MEDIUM, workGroupId=-1}
[INFO]11:38:34.233 ocommon.queue.TaskQueueZkImpl:[126] - add task : /dolphinscheduler/tasks_queue/2_506_2_831_-1 to tasks queue , result success
[INFO]11:38:34.233 odao.ProcessDao:[975] - master insert into queue success, task : oas_hrmsubcompany
[INFO]11:38:34.233 odao.ProcessDao:[786] - submit task :oas_hrmsubcompany state:SUBMITTED_SUCCESS complete, instance id:506 state: RUNNING_EXEUTION  

[INFO]11:48:17.800 MasterTaskExecThread:[82] - task :oas_hrmsubcompany id:831, process id:506, exec thread completed 
[INFO]11:48:18.252 MasterExecThread:[846] - task :oas_hrmsubcompany, id:831 complete, state is SUCCESS 

[INFO]11:48:18.272 MasterExecThread:[792] - add task to stand by list: d_par_branch_info
[INFO]11:48:18.273 MasterExecThread:[584] - taskName: d_par_branch_info completeDependTaskList: [oas_hrmsubcompany]
[INFO]11:48:18.273 ocommon.queue.TaskQueueFactory:[45] - task queue impl use zookeeper 
[INFO]11:48:18.280 MasterExecThread:[801] - remove task from stand by list: d_par_branch_info
[INFO]11:48:18.296 odao.ProcessDao:[769] - start submit task : d_par_branch_info, instance id:506, state: RUNNING_EXEUTION, 
[INFO]11:48:18.341 ocommon.queue.TaskQueueZkImpl:[99] - check task:2_506_2_0_-1 not exist in task queue

[INFO]11:48:18.372 ocommon.queue.TaskQueueZkImpl:[99] - check task:2_506_2_863_-1 not exist in task queue
[INFO]11:48:18.374 odao.ProcessDao:[973] - task ready to queue: TaskInstance{id=863, name='d_par_branch_info', taskType='SHELL', processDefinitionId=120, processInstanceId=506, processInstanceName='null', taskJson='{"depList":["oas_hrmsubcompany"],"dependence":"{}","forbidden":false,"id":"tasks-6-7j27u","maxRetryTimes":2,"name":"d_par_branch_info","params":"{\"rawScript\":\"sh /home/infa/dolphin_task/dw_running_everyday.sh workflow_d_par_branch_info_full oas_hrmsubcompany d_par_branch_info 20200525\",\"localParams\":[],\"resourceList\":[]}","preTasks":"[\"oas_hrmsubcompany\"]","retryInterval":5,"runFlag":"NORMAL","taskInstancePriority":"MEDIUM","taskTimeoutParameter":{"enable":false,"interval":0},"timeout":"{\"enable\":false,\"strategy\":\"\"}","type":"SHELL","workerGroupId":-1}', state=SUBMITTED_SUCCESS, submitTime=Sun Jun 14 11:48:18 CST 2020, startTime=Sun Jun 14 11:48:18 CST 2020, endTime=null, host='null', executePath='null', logPath='null', retryTimes=0, alertFlag=NO, flag=YES, processInstance=null, processDefine=null, pid=0, appLink='null', flag=YES, dependency=null, duration=null, maxRetryTimes=2, retryInterval=5, taskInstancePriority=MEDIUM, processInstancePriority=MEDIUM, workGroupId=-1}

[INFO]11:48:18.399 ocommon.queue.TaskQueueZkImpl:[126] - add task : /dolphinscheduler/tasks_queue/2_506_2_863_-1 to tasks queue , result success
[INFO]11:48:18.404 odao.ProcessDao:[975] - master insert into queue success, task : d_par_branch_info
[INFO]11:48:18.405 odao.ProcessDao:[786] - submit task :d_par_branch_info state:SUBMITTED_SUCCESS complete, instance id:506 state: RUNNING_EXEUTION

**Comment by dailidong** [comment]
detail info please refer #4071
