### ISSUE TITLE
[Bug][提交成功，但是任务不执行，偶发一周平均出现一次]

### ISSUE THREAD

**Issue by supperchild123** [apache/incubator-dolphinscheduler#4071]
dolphinsheduler1.2.0,任务显示提交成功，不运行。偶发一周平均出现一次，某一两个任务提交成功不运行，其它任务正常执行完成。。
整理报错日志和正常完成任务对比日志如下： 
其中 233510d_par_action表master提交成功不运行，
233511d_par_action_full表master执行成功日志，进行比较。 详情可查看附件日志，谢谢。
主要报错信息如下：
####233510d_par_action表worker提交不运行的日志
  C:\Users\XuJing\Desktop\ds-log\dolphinscheduler-worker.2020-11-03_00.0.log (4 hits)
	Line 9135: [INFO] 2020-11-03 00:22:57.655 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[211] - consume tasks: [2_106884_2_233510_176226831,176226829,176226830, 2_106884_2_233511_176226831,176226829,176226830, 2_107020_2_233508_176226831,176226829,176226830],there still have 2 tasks need to be executed
	Line 9136: [ERROR] 2020-11-03 00:22:57.657 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[261] - task instance is null. task id : 233510 
	Line 9137: [WARN] 2020-11-03 00:22:57.657 org.apache.dolphinscheduler.server.worker.runner.FetchTaskThread:[188] - remove task queue : 2_106884_2_233510_176226831,176226829,176226830 due to taskInstance is null
	Line 9138: [INFO] 2020-11-03 00:22:57.657 org.apache.dolphinscheduler.common.queue.TaskQueueZkImpl:[278] - consume task /dolphinscheduler/tasks_queue/2_106884_2_233510_176226831,176226829,176226830
 	
ds配置任务流程图：
<img width="397" alt="1605511243(1)" src="https://user-images.githubusercontent.com/74525943/99223434-72cbfb00-281f-11eb-93bc-336be3e1e935.png">

详情请查看附件日志，谢谢。
![image](https://user-images.githubusercontent.com/74525943/99223131-ea4d5a80-281e-11eb-993d-1d6dd7cf80e8.png)

[dolphinscheduler-worker.2020-11-03_00.0.log](https://github.com/apache/incubator-dolphinscheduler/files/5544639/dolphinscheduler-worker.2020-11-03_00.0.log)

[510&511对比.txt](https://github.com/apache/incubator-dolphinscheduler/files/5544637/510.511.txt)
[dolphinscheduler-master.2020-11-03_00.0.log](https://github.com/apache/incubator-dolphinscheduler/files/5544638/dolphinscheduler-master.2020-11-03_00.0.log)

**Comment by dailidong** [comment]
version >=1.2.1 solved this issue, detail info please refer : https://github.com/apache/incubator-dolphinscheduler/issues/1477

**Comment by dailidong** [comment]
please pay attention to WARN OR ERROR runtime info , By the way, please change/add title and description in English,thx
