### ISSUE TITLE
[Bug][项目管理] The name of the spark task is set, and it is no problem to submit through the shell. The main function class is always used as the name when submitted through the dolphinscheduler and cannot be changed.（spark任务设置了name，通过shell提交没问题，通过dolphinscheduler提交一直以主函数class为name，不可更改）

### ISSUE THREAD

**Issue by zhmingyong** [apache/incubator-dolphinscheduler#4072]
The name of the spark task is set, and it is no problem to submit through the shell. The main function class is always used as the name when submitted through the dolphinscheduler and cannot be changed.（spark任务设置了name，通过shell提交没问题，通过dolphinscheduler提交一直以主函数class为name，不可更改）

**Comment by zhuangchong** [comment]
Should I use shell task node or Spark task node to submit Spark task via Dolphin? Fill in the input box for other parameters on the Spark task node interface  --name XXXX and see if you can achieve the result you want.

---
通过Dolphin提交spark任务，是使用shell任务节点还是spark任务节点？spark任务节点界面其他参数输入框内填入 --name xxxx 试一下是否可实现你想要的结果

**Comment by zhmingyong** [comment]
I submitted it through the spark node and it has been verified. It is possible to add --name xxx to other parameters, thank you very much

我是通过spark节点提交的，现在已经验证了，在其他参数中添加 --name xxx是可行，非常感谢您的解答

**Comment by zhmingyong** [comment]
I submitted it through the spark node and it has been verified. It is possible to add --name xxx to other parameters, thank you very much

我是通过spark节点提交的，现在已经验证了，在其他参数中添加 --name xxx是可行，非常感谢您的解答
