### ISSUE TITLE
[Improvement][Scheduler] SchedulerService.deleteScheduleById can be improved

### ISSUE THREAD

**Issue by RunAsOnehhb** [apache/incubator-dolphinscheduler#4076]
# **Before**

​        `if (delete > 0) {`
​            `putMsg(result, Status.SUCCESS);`
​        `} else {`
​            `putMsg(result, Status.DELETE_SCHEDULE_CRON_BY_ID_ERROR);`
​        }

# **After**

`putMsg(result, delete > 0 ? Status.SUCCESS : Status.DELETE_SCHEDULE_CRON_BY_ID_ERROR);`

**Comment by CalvinKirs** [comment]
This question has been created, you can refer to #3435. Are you interested in improving it?
