### ISSUE TITLE
[Improvement][website] replace good quality pictures for system manual

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#4077]
the pictures are not clear enough on the  https://dolphinscheduler.apache.org/zh-cn/docs/1.3.3/user_doc/system-manual.html , could you give some help to replace good quality picture, if you are interesting in this thing, please leave message

the official website github url: https://github.com/apache/incubator-dolphinscheduler-website

and you could update the pictures under img under incubator-dolphinscheduler-website root directory.

the corresponding markdown file about the system-manal.html is system-manual.md , its location under docs/zh-cn/1.3.3/system-manual.md

**Which version of DolphinScheduler:**
 -[all versions]

**Comment by dailidong** [comment]
if you are interesting in this work, please leave message

**Comment by kevinsun2010** [comment]
i will fix it，In the latest week。

**Comment by kevinsun2010** [comment]
we need to discuss how to improvement good quality picture？ 
if picture is small not full screen，it is clear [enough.]([url](url
![login](https://user-images.githubusercontent.com/27861996/101565322-c5a46700-3a07-11eb-86a0-344981902caa.png)
))
 

![create-queue](https://user-images.githubusercontent.com/27861996/101565339-cccb7500-3a07-11eb-9740-e789178d3c22.jpg)

**Comment by kevinsun2010** [comment]
Is there a better way？

**Comment by kevinsun2010** [comment]
1.after replace  pictures ， the pictures are not clearer.
2.by way of modify the display wide of css. the pictures is clearer. eg:
![test01](https://user-images.githubusercontent.com/27861996/101709119-d3babc00-3ac9-11eb-914c-7aa47227edf6.jpg)

so，Let's do it this way. Until there's a better way
