### ISSUE TITLE
[Bug][Sqoop] Password contain special character，can't execute 

### ISSUE THREAD

**Issue by zhiyuan192shine** [apache/incubator-dolphinscheduler#4085]
**Describe the bug**
if sqoop --password contain special character，then sqoop can not execute.

**To Reproduce**
for example:
![image](https://user-images.githubusercontent.com/13871686/99661142-5c7fa280-2a9e-11eb-9d7c-18a9c65ead1e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/13871686/99661571-fe06f400-2a9e-11eb-9f37-2b6978518b74.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Comment by xingchun-chen** [comment]
who can fix it?

**Comment by Eights-Li** [comment]
I will fixed this bug in pr #4036

**Comment by Eights-Li** [comment]
fixed in pr #4036
