### ISSUE TITLE
[Feature][Node Type]   Can MQ nodes be supported

### ISSUE THREAD

**Issue by chakench** [apache/incubator-dolphinscheduler#4086]
On our project, we want to use DS to support nodes like MQ.

For example,  There are three nodes, A-> B -> C,  A is MQ consumption node, B,C is processing node (maybe HTTP business logic processing node), as long as A listens to the message, B,C will run once.

For MQ, it can be any type of MQ, but **Spring Cloud Stream** is better. MQ messages will be around **10,000 to 20,000 a da**y, so support a bit more concurrency

**Comment by CalvinKirs** [comment]
Hi, this doesn't look like a scheduler task, I think what you should think about is whether it is placed in DS?

**Comment by chakench** [comment]
> Hi, this doesn't look like a scheduler task, I think what you should think about is whether it is placed in DS?

This should be a Scheduler Task and is used in a lot of situations. In the business process, there is an MQ node, and the subsequent nodes are the corresponding HTTP processing nodes. In this way, the business process can be dynamically choreographed in the way of DAG, without the need for hard coding。

**Comment by CalvinKirs** [comment]
> > Hi, this doesn't look like a scheduler task, I think what you should think about is whether it is placed in DS?
> 
> This should be a Scheduler Task and is used in a lot of situations. In the business process, there is an MQ node, and the subsequent nodes are the corresponding HTTP processing nodes. In this way, the business process can be dynamically choreographed in the way of DAG, without the need for hard coding。

hi, maybe I didn't understand what you mean. My question is: Since it can pass http, why use mq? There is no benefit in adding a layer of links, but the overall maintenance cost will increase, and the predictability of scheduling will be reduced. As for concurrency, I think this is not what DS needs to consider. DS calls A. If A cannot guarantee his throughput, then A should consider expansion or other methods. MQ is definitely not the best solution.

**Comment by gabrywu** [comment]
Wellcome to create a PR to add the new feature if you really want it @chakench

**Comment by chakench** [comment]
> > > Hi, this doesn't look like a scheduler task, I think what you should think about is whether it is placed in DS?
> > 
> > 
> > This should be a Scheduler Task and is used in a lot of situations. In the business process, there is an MQ node, and the subsequent nodes are the corresponding HTTP processing nodes. In this way, the business process can be dynamically choreographed in the way of DAG, without the need for hard coding。
> 
> hi, maybe I didn't understand what you mean. My question is: Since it can pass http, why use mq? There is no benefit in adding a layer of links, but the overall maintenance cost will increase, and the predictability of scheduling will be reduced. As for concurrency, I think this is not what DS needs to consider. DS calls A. If A cannot guarantee his throughput, then A should consider expansion or other methods. MQ is definitely not the best solution.


The reason for using MQ is to act as an event trigger and then trigger subsequent HTTP nodes to take MQ messages for business processing, which is quite normal for scheduling

**Comment by gabrywu** [comment]
@chakench No, I think it's not so normal for a scheduling system.

**Comment by CalvinKirs** [comment]
hi, if you really need this, I suggest you expand it yourself. Or you can submit a PR. The discussion will be closed and you can reopen it when you have a good design. Thank you very much for the discussion. Thx
