### ISSUE TITLE
logger host cannot be modified

### ISSUE THREAD

**Issue by xiahejun** [apache/incubator-dolphinscheduler#4095]
**Describe the feature**
logger host can be modified

![image](https://user-images.githubusercontent.com/54968493/99926744-ad80e680-2d7d-11eb-8b51-8cdb948d2a5f.png)

**Comment by CalvinKirs** [comment]
Hi, can you describe some similar scenarios where you need this feature.
In my opinion, there is no problem with the host being fixed during operation, and dynamic changes will become uncontrollable between communications.

**Comment by xiahejun** [comment]
During the deployment of LOGGER service, the default port 50051 has been used by other services, so I want to provide the modifiable function of this port

**Comment by CalvinKirs** [comment]
Sorry，I misunderstood what you mean, you are right.I will confirm this issue later

**Comment by BoYiZhang** [comment]
![image](https://user-images.githubusercontent.com/39816903/99935098-dbc0ef00-2d9a-11eb-88a2-2b0c2c6abed1.png)

50051 port code written dead, with the production environment port conflict

It needs to be changed to a configurable way

**Comment by xiahejun** [comment]
I'll fix it

**Comment by CalvinKirs** [comment]
See #2904
