### ISSUE TITLE
一键部署丢失配置密码

### ISSUE THREAD

**Issue by yangzichuang** [apache/incubator-dolphinscheduler#4096]
一键部署时，conf/datasource.properties 的 spring.datasource.password 的值会丢失

**Comment by zhuangchong** [comment]
One-click deployment sh install.sh, the password attribute value in the conf/config/install_config.conf file will override the spring.datasource.password value in conf/datasource.properties

---
一键部署 sh install.sh,conf/config/install_config.conf文件内的password属性值会覆盖conf/datasource.properties的spring.datasource.password 的值

**Comment by CalvinKirs** [comment]
Overwrite, not lose

BTW，Please use English
