### ISSUE TITLE
[Bug][common] StringUtils replaceNRTtoUnderline Method needs to determine if it is null, otherwise an exception will be reported

### ISSUE THREAD

**Issue by felix-thinkingdata** [apache/incubator-dolphinscheduler#4098]
Method needs to determine if it is null, otherwise an exception will be reported

org.apache.dolphinscheduler.common.utils.StringUtils.replaceNRTtoUnderline

![image](https://user-images.githubusercontent.com/59079269/100074753-19487980-2e7a-11eb-9797-3c49cafab718.png)

**Comment by CalvinKirs** [comment]
close by #4100
