### ISSUE TITLE
[Bug][dolphinscheduler-api] When I went online and offline, I found that the "`t_ds_process_definition`.`update_time` was not updated

### ISSUE THREAD

**Issue by Squidyu** [apache/incubator-dolphinscheduler#4101]
**Describe the bug**
When I went online and offline process definition, I found that the `t_ds_process_definition`.`update_time` was not updated
When I went online and offline process schedules, I found that the `t_ds_schedules`.`update_time` was not updated too
**Which version of Dolphin Scheduler:**
 -[1.2.0 and 1.3.3]
and some others version
**Requirement or improvement**
 I think where change online status ,`t_ds_process_definition`.`update_time` and `t_ds_schedules`.`update_time` should be update!

**Comment by xingchun-chen** [comment]
The design is such that only the editing workflow will update the time
