### ISSUE TITLE
[Good News] DolphinScheduler awarded as the Top 10 Outstanding projects to Open Source 2020

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#4106]
Congrats to DolphinScheduler community awarded as the Top 10 Outstanding projects to Open Source 2020

![开源新锐项目单独海报·Apache DolphinScheduler](https://user-images.githubusercontent.com/15833811/100300371-da790780-2fd0-11eb-9a13-cb358fae8bcb.jpg)

**Comment by zhuangchong** [comment]
+1
good

**Comment by Rubik-W** [comment]
good


--------------------
DolphinScheduler(Incubator) Commtter
Hemin Wen  温合民
wenhemin@apache.org
--------------------


dailidong <notifications@github.com> 于2020年11月26日周四 上午10:20写道：

**Comment by c-f-cooper** [comment]
goot

**Comment by dailidong** [comment]
![infoq奖项](https://user-images.githubusercontent.com/15833811/102297724-ba62b580-3f8a-11eb-8bdc-e7fb6ef5960e.jpeg)

**Comment by dailidong** [comment]
![Uploading infoq奖项1.jpeg…]()

**Comment by dailidong** [comment]
![infoq奖项1](https://user-images.githubusercontent.com/15833811/102297963-3a891b00-3f8b-11eb-9358-12a26d313007.jpeg)
Most Popular Award
