### ISSUE TITLE
unable to find resource file upload on worker node

### ISSUE THREAD

**Issue by gaolv123tyu** [apache/incubator-dolphinscheduler#4107]
My worker and master is on different machine。When after upload a resource file, I found that file only appear in the master node，and unable to find resource file upload on worker node。 This led to I can not run application because of missing file on the worker node。Is there something wrong ？

**Comment by xingchun-chen** [comment]
If the file is deployed locally, the file storage needs to be the same machine as the worker machine. If it is a cluster deployment, it is best to use hadoop

**Comment by lgcareer** [comment]
@gaolv123tyu Please verify your configuration of `resource.storage.type`  and `resourceUploadPath` in common.properties.
