### ISSUE TITLE
[Bug][api] When the zk path is not generated, an error is reported when creating a workflow

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4109]
1. Do not start master and worker services，So there is no generated path /dolphinscheduler/nodes/worker in zookeeper

2. Create a workflow, the node setting popup box appears blank, because the api service queries the worker group and reports an error

![image](https://user-images.githubusercontent.com/55787491/100319628-e8dc1900-2ffa-11eb-8e32-24c1cbc3120e.png)

![image](https://user-images.githubusercontent.com/55787491/100319332-618ea580-2ffa-11eb-93be-b596e42c2f0f.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Comment by xingchun-chen** [comment]
Who want to fix it?

**Comment by felix-thinkingdata** [comment]
> Who want to fix it?

how to fix ?What kind of effect does it make?

**Comment by xingchun-chen** [comment]
If the path cannot be found, the interface /worker-group/all-groups  can return default to the front end
Currently the front-end task node will be blank，can't create the task
![image](https://user-images.githubusercontent.com/55787491/100334800-36628100-300f-11eb-8cf2-cf299b0d1b78.png)

**Comment by felix-thinkingdata** [comment]
> If the path cannot be found, the interface /worker-group/all-groups can return default to the front end
> Currently the front-end task node will be blank，can't create the task
> ![image](https://user-images.githubusercontent.com/55787491/100334800-36628100-300f-11eb-8cf2-cf299b0d1b78.png)


It replicates. Let me fix it
![image](https://user-images.githubusercontent.com/59079269/100340634-74af6e80-3016-11eb-8752-ff4e27342f1b.png)

**Comment by felix-thinkingdata** [comment]
> If the path cannot be found, the interface /worker-group/all-groups can return default to the front end
> Currently the front-end task node will be blank，can't create the task
> ![image](https://user-images.githubusercontent.com/55787491/100334800-36628100-300f-11eb-8cf2-cf299b0d1b78.png)

Is dev branch repair ok

**Comment by felix-thinkingdata** [comment]
> Who want to fix it?

return /dolphinscheduler/nodes/worker/default  ok ?

**Comment by xingchun-chen** [comment]
> return /dolphinscheduler/nodes/worker/default ok ?

I think it is ok

**Comment by felix-thinkingdata** [comment]
> > return /dolphinscheduler/nodes/worker/default ok ?
> 
> I think it is ok

If  return "default" ,Does this affect users who do not use the "Default" queue？

**Comment by lenboo** [comment]
> > > return /dolphinscheduler/nodes/worker/default ok ?
> > 
> > 
> > I think it is ok
> 
> If return "default" ,Does this affect users who do not use the "Default" queue？

maybe, but "default" is better than blank.

**Comment by felix-thinkingdata** [comment]
I don't think it seems to be a problem.
This problem will only occur if the worker process has never been started.
It is a rare case that the worker never starts.

**Comment by CalvinKirs** [comment]
> I don't think it seems to be a problem.
> This problem will only occur if the worker process has never been started.
> It is a rare case that the worker never starts.

I agree with you, returning to default will affect the logic of normal default
