### ISSUE TITLE
[Improvement][API] about two tenant are same name question。

### ISSUE THREAD

**Issue by kevinsun2010** [apache/incubator-dolphinscheduler#4112]
**Describe the question**
if two tenant are same name，Unable to distinguish  when workflow select tenant list。

suggestion：
1 add check not allow two tenant are same name。
2 display tenant name and tenant id when workflow select tenant list。

![2020-11-26_191920](https://user-images.githubusercontent.com/27861996/100344855-6e23f580-301c-11eb-9573-0e1e7a85d684.jpg)
![2020-11-26_191951](https://user-images.githubusercontent.com/27861996/100344860-6f552280-301c-11eb-8fef-9429dc9b99a4.jpg)

**Comment by CalvinKirs** [comment]
Good suggestion, are you willing to complete it?

**Comment by xingchun-chen** [comment]
which version？ 
When creating a tenant, the tenant should be unique

**Comment by kevinsun2010** [comment]
> Good suggestion, are you willing to complete it?

i can fix it .Both two ways support： 1 add check not allow two tenant are same name。
2 display tenant name and tenant id when workflow select tenant list。i will fix api ,   but  the front page need other contributors  contributors to fix it.

**Comment by kevinsun2010** [comment]
> which version？
> When creating a tenant, the tenant should be unique
> ![image](https://user-images.githubusercontent.com/55787491/100575980-2355f680-3318-11eb-8888-094d08347662.png)

not same tenant  number but same tenant name。

**Comment by dailidong** [comment]
this question has been solved through deleting tenant name

**Comment by dailidong** [comment]
this question has been solved through deleting tenant name
