### ISSUE TITLE
[Question] data.basedir.path  cleanup problem.

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#4114]
1, I have modified the data. The basedir. Path from/tmp/dolphinscheduler to /mydata/dolphinscheduler/tmp/.
2. Developer mode is false.
3, /mydata/dolphinscheduler/tmp folder read and write access to normal, ds is perfectly normal.
4, after running for a period of time only, find/data/dolphinscheduler files in the/tmp directory cannot be automatically deleted, lead to disk pile up.
Q: Can temporary files in this directory only be removed manually?Cannot automatically delete??

1、我修改了data.basedir.path从/tmp/dolphinscheduler/ 到数据盘/data/dolphinscheduler/tmp.
2、开发者模式为false.
3、/data/dolphinscheduler/tmp文件夹读写权限正常，ds工作完全正常.
4、在运行了一段时间只有，发现/data/dolphinscheduler/tmp目录中的文件不能自动删除，导致磁盘被占满.

问题：这个目录中的临时文件只能手动删除么？不能自动删除？？？

**Comment by xingchun-chen** [comment]
I did not reproduce your question. the authority of the directory and file, that  is the deployment user?

**Comment by baijun** [comment]
@xingchun-chen 
目录所属用户就是dolphinscheduler账户，目录中的文件并不会被自动清除。
![image](https://user-images.githubusercontent.com/7664170/100576486-30271a00-3319-11eb-8b23-a77540008cf8.png)

**Comment by xingchun-chen** [comment]
I am using version 1.3.3, which version is yours？

**Comment by baijun** [comment]
@xingchun-chen 1.3.3 release

**Comment by xingchun-chen** [comment]
Is the service restarted after the developer mode is changed to false

**Comment by baijun** [comment]
This configuration has not been changed, the default is false, and the cluster has not been changed since sh install.
这个配置并没有动过，默认就是false, sh install之后就没在动过集群.

**Comment by xingchun-chen** [comment]
Found the reason, because the assigned worker and master are not on the same node, the files in the directory  are not deleted
Thank you very much for your feedback, this problem will be fixed in version 1.3.4

**Comment by baijun** [comment]
thx

**Comment by pigzhuzhu** [comment]
你好，我也是，在运行了一段时间后，发现/data/dolphinscheduler/tmp的文件不能自动删除，导致磁盘被占满，里面的文件能手动删除吗？
