### ISSUE TITLE
[Bug][工作流] 1.3.3版本工作流无法限制选择租户

### ISSUE THREAD

**Issue by fengbuyu** [apache/incubator-dolphinscheduler#4117]
![image](https://user-images.githubusercontent.com/12424520/100422550-7b48ef00-30c5-11eb-96e8-5df9fc901de5.png)

**Comment by xingchun-chen** [comment]
please update the title in English，thanks

**Comment by xingchun-chen** [comment]
I don’t understand what you mean, how to restrict the selected tenants

**Comment by xloya** [comment]
I think he meant that the tenant was configured when the user was created, but another tenant can be selected here

**Comment by CalvinKirs** [comment]
I will close it, if you still have questions, you can reopen it
