### ISSUE TITLE
datax log not stored in datax_home

### ISSUE THREAD

**Issue by shiyuexieyi** [apache/incubator-dolphinscheduler#4122]
I have make a datax job in dolphinscheduler.However,the logs were only stored in dolphinscheduler-worker.log.I hope the log to be stored in datax home.So that I can parse it easily.

I want to know how can I make th logs be stored both in dolphinscheduler home an datax home?

**Comment by Rubik-W** [comment]
Datax outputs the log to stdout by default.
DS gets the log from stdout.

So, This requirement requires modification of the datax.py script.

**Comment by shiyuexieyi** [comment]
@Rubik-W Thanks.I found that because dolphinscheduler don't have the priviledge of reading the log of datax.
