### ISSUE TITLE
[Improvement][API] update web ui user admin default password easy

### ISSUE THREAD

**Issue by kevinsun2010** [apache/incubator-dolphinscheduler#4129]
**Describe the question**
web ui  user admin default password  is  dolphinscheduler123，the password is difficult to input.

**What are the current deficiencies and the benefits of improvement**
update user admin default password easy, eg: admin ,123456 ...

let's user easy to start, Just a little bit。

**Comment by zhuangchong** [comment]
web ui user admin default password is dolphinscheduler123 ,This is just an initial password, you can change a password you want through the password change function.
