### ISSUE TITLE
[Question] 如何支持flink session集群任务

### ISSUE THREAD

**Issue by usretyn** [apache/incubator-dolphinscheduler#4132]
已搭建flink 集群,  如何将JAR任务发送至现有集群，并获取对应的任务状态，目前是否支持，如果不支持有没有扩展方案
结束任务时有没有回调函数删除对应的任务

**Comment by hermeshephaestus** [comment]
ok, ds has supported flink jar! Do you mean whether it supports flink task status query? @usretyn

**Comment by usretyn** [comment]
> ok, ds has supported flink jar! Do you mean whether it supports flink task status query? @usretyn

yes

**Comment by chengshiwen** [comment]
Close the question since it has been replied
