### ISSUE TITLE
selected  Single node  in workflow can not be run

### ISSUE THREAD

**Issue by xiahejun** [apache/incubator-dolphinscheduler#4133]
**Describe the question**
selected  Single node  in workflow can not be run,master logger show NullPointerException

**Which version of DolphinScheduler:**
 -[1.3.3]

![image](https://user-images.githubusercontent.com/54968493/100687007-75e7ef00-33ba-11eb-8834-dbbe14c88d12.png)
![image](https://user-images.githubusercontent.com/54968493/100687010-77b1b280-33ba-11eb-9377-d5949cdddcf9.png)
![image](https://user-images.githubusercontent.com/54968493/100687018-81d3b100-33ba-11eb-9421-ee57b377087c.png)

**Comment by kevinsun2010** [comment]
> **Describe the question**
> selected Single node in workflow can not be run,master logger show NullPointerException
> 
> **Which version of DolphinScheduler:**
> -[1.3.3]
> 
> ![image](https://user-images.githubusercontent.com/54968493/100687007-75e7ef00-33ba-11eb-8834-dbbe14c88d12.png)
> ![image](https://user-images.githubusercontent.com/54968493/100687010-77b1b280-33ba-11eb-9377-d5949cdddcf9.png)
> ![image](https://user-images.githubusercontent.com/54968493/100687018-81d3b100-33ba-11eb-9421-ee57b377087c.png)

This question how to repeat. i cant repeat error.

**Comment by kevinsun2010** [comment]
This question how to repeat. i cant repeat error.

**Comment by zhuangchong** [comment]
This issue has been resolved, please refer to Issue #4090
