### ISSUE TITLE
datax组件需要支持大数据环境能力(hive/hdfs)

### ISSUE THREAD

**Issue by snycc15** [apache/incubator-dolphinscheduler#4136]
版本1.3.3对于datax目标端支持只有MYSQL/ORACLE类，未支持hdfs/hive这类基本的大数据环境能力支撑。

**Comment by Rubik-W** [comment]
Please English.

Non-RDBMS database, You can use custom json options.


--------------------
DolphinScheduler(Incubator) Commtter
Hemin Wen  温合民
wenhemin@apache.org
--------------------


snycc15 <notifications@github.com> 于2020年12月1日周二 上午10:19写道：
