### ISSUE TITLE
[Improvement][master] TaskPriorityQueueConsumer No need to sleep for one second

### ISSUE THREAD

**Issue by GitFireMan** [apache/incubator-dolphinscheduler#4137]
**Describe the question**
TaskPriorityQueueConsumer.run() call taskPriorityQueue.size() and if size is 0,then thread will b sleep for 1 second.
I think there is no need to do this, code is show here:

![image](https://user-images.githubusercontent.com/18112654/100697718-b7d05f80-33d1-11eb-8d50-1aa42266b51a.png)

I think these three lines removed will be better，because  taskPriorityQueue.take() is a blocking method.
Removed sleep... will improve the performance of scheduler.

`  if (taskPriorityQueue.size() <= 0) {
                        Thread.sleep(Constants.SLEEP_TIME_MILLIS);
                        continue;
   }`

**Comment by GitFireMan** [comment]
TaskPriorityQueueConsumer's logic is very easy. just cosume the task waiting to run in  priority queue. I think that there is no need a determine statement `if(queue.size() <= 0) Thread.sleep(1 second)`. because code below is `queue.take()` which is a blocking method if queue is empty.

**Comment by CalvinKirs** [comment]
See for specific reasons #4140

**Comment by dailidong** [comment]
> See for specific reasons #4140

anybody who want to do this feature please refer the PR #4140, then re-submit a new PR

**Comment by AlleriaWindrunner** [comment]
I can solve this problem, assign it to me!

**Comment by davidzollo** [comment]
> I can solve this problem, assign it to me!

good, happy new year,  I have assigned this issue to you, looking forward to your PR

**Comment by woshiwuxiaofei** [comment]
I can try it, assign it to me!

**Comment by davidzollo** [comment]
> I can try it, assign it to me!

done
