### ISSUE TITLE
For Windows, use Dolphinscheduler？

### ISSUE THREAD

**Issue by yaojianannan** [apache/incubator-dolphinscheduler#4147]
How do I schedule the workflow for Dolphinscheduler on the Windows operating system？

**Comment by CalvinKirs** [comment]
only Worker needs to run on Linux, and other services can run on Windows. But it is still recommended to deploy and use on linux

**Comment by CalvinKirs** [comment]
Related documents:https://dolphinscheduler.apache.org/zh-cn/docs/1.3.3/user_doc/standalone-deployment.html
