### ISSUE TITLE
The data source of sqoop component only supports mysql, not Oracle and other RDBMS

### ISSUE THREAD

**Issue by snycc15** [apache/incubator-dolphinscheduler#4157]
The data source of sqoop component only supports mysql, not Oracle and other RDBMS

**Comment by CalvinKirs** [comment]
Hi, we used mybatis, you can manually add the Oracle driver to complete the work. btw, we cannot implement Oracle db in the project, it is not an open source product.

**Comment by xyzhh** [comment]
> Hi, we used mybatis, you can manually add the Oracle driver to complete the work. btw, we cannot implement Oracle db in the project, it is not an open source product.

I think it is not just a "question”,why sqoop do not support postgresql or oracle?There is no options on UI,even I have already add oracle drive.
