### ISSUE TITLE
TaskKillProcessor throw NullPointException

### ISSUE THREAD

**Issue by wangxj3** [apache/incubator-dolphinscheduler#4172]
1.when worker runing more than 100 tasks , there are some tasks in queue.
with that ,master send a kill commad to this worker,TaskKillProcessor receive ,and get processId in cache(TaskExecutionContext).
But the taskInstance isn't running in this worker ,it is in queue.so the TaskKillProcessor  throw NullPointException.
2.This exception will be catched in this method.The TaskKillProcessor will continue run to build command .In method "buildKillTaskResponseCommand" , get TaskInstanceId in cache(TaskExecutionContext),but this cache is null,so the command send to master with a null taskInstanceId.

**Comment by CalvinKirs** [comment]
How to verify: Add a sleep before the cache code, and execute the kill operation during sleep.
