### ISSUE TITLE
[Improvement][Worker] Suggest to load tenant private environment to execute private script

### ISSUE THREAD

**Issue by whitelowrie** [apache/incubator-dolphinscheduler#4174]
each tenant maybe have it private environment variable，example，use the tenant local anaconda will config the .bashrc，
but dolphinscheduler will not load the .bashrc so anaconda can't be used.

so suggest load tenant private environment to execute private script

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Describe alternatives you've considered**
so if the system os is linux , .bashrc will be loaded otherwise

**Comment by BoYiZhang** [comment]
You can modify the configuration to load the specified configuration file

common.properties : 
```
dolphinscheduler.env.path=/etc/profile
```

**Comment by whitelowrie** [comment]
> You can modify the configuration to load the specified configuration file
> 
> common.properties :
> 
> ```
> dolphinscheduler.env.path=/etc/profile
> ```

I means tenant environment, not golbal environment.

**Comment by BoYiZhang** [comment]
You can try to modify the operating system configuration file

Reference link: http://ghoulich.xninja.org/2017/05/09/how-to-find-env-variables-when-exec-sudo-commands/

**Comment by CalvinKirs** [comment]
Has your problem been solved?

**Comment by chengshiwen** [comment]
Close the question since it has been replied
