### ISSUE TITLE
[Question] 能否在shell中获取工作流实例ID

### ISSUE THREAD

**Issue by cnstevenwang** [apache/incubator-dolphinscheduler#4177]
如题，能否获取当前工作流实例的ID

**Comment by BoYiZhang** [comment]
There is no way at present

In addition, please describe it in English

**Comment by whitelowrie** [comment]
Is task id or processDefinitionId? Do you mean log it out?
At present the  log is no way， Bug, you can add it by you self.

org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
![image](https://user-images.githubusercontent.com/13913085/101563973-36964f80-3a05-11eb-9bc5-2eb00403fe6f.png)

**Comment by whitelowrie** [comment]
Is it processInstanceId? as BoYiZhang said it not way at present auto get.
but if you need, can add it by you self.

at org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java you can get the processInstanceId
![image](https://user-images.githubusercontent.com/13913085/101564274-cf2ccf80-3a05-11eb-8cdb-bfd4fe260783.png)

**Comment by cnstevenwang** [comment]
> There is no way at present
> 
> In addition, please describe it in English

InstanceID is useful for developer to organize their workflow and data logic.

**Comment by chengshiwen** [comment]
Close the question since it has been replied
