### ISSUE TITLE
[Bug][api] Start the workflow, the prompt is incorrect

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4178]
It should be reminded: check workflow definition errors
![image](https://user-images.githubusercontent.com/55787491/101456461-0ac88a80-396f-11eb-8bc5-c690f182ab54.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Comment by zacheung** [comment]
前置工作流定义没有问题，可以正常跑通，后置工作流设置denpendent，无法触发后置工作流，不能生成工作流实例
![Uploading IMG20201208161607.jpg…]()

**Comment by BoYiZhang** [comment]
+1

**Comment by zt-1997** [comment]
i will fix it.
