### ISSUE TITLE
Problems of workflow dependency(工作流依赖的问题)

### ISSUE THREAD

**Issue by zacheung** [apache/incubator-dolphinscheduler#4180]
版本是`1.3.3`，前置工作流定义没有问题，定时后可以正常跑通，后置工作流设置`dependent`，没有设置开始时间，前置跑完无法触发后置工作流，不能生成工作流实例。难道是不能自动触发后续工作流自动启动吗？这个功能还没有开发吗？

**Comment by xingchun-chen** [comment]
please update the title in English, thanks

**Comment by xingchun-chen** [comment]
Whether the task you depend on is executed successfully within the dependent time？

**Comment by zacheung** [comment]
> Whether the task you depend on is executed successfully within the dependent time？

I didn't set the run time of the post-workflow. Must a post-workflow start time be set? Can't the follow-up workflow be triggered automatically after the front workflow is completed?

**Comment by zacheung** [comment]
> Whether the task you depend on is executed successfully within the dependent time？



> Whether the task you depend on is executed successfully within the dependent time？

The front workflow is completed normally.

**Comment by zacheung** [comment]
> Whether the task you depend on is executed successfully within the dependent time？

The front workflow is completed normally.

**Comment by xingchun-chen** [comment]
After the pre task is executed, the post task will be executed normally. Can you take a screenshot of your post task, or check the master / worker log for errors

**Comment by zacheung** [comment]
> After the pre task is executed, the post task will be executed normally. Can you take a screenshot of your post task, or check the master / worker log for errors

Thanks. I already know how to use it.
