### ISSUE TITLE
[Bug][Alert] Alert进程重连数据库次数太少 Alert process reconnects database too few times

### ISSUE THREAD

**Issue by glxfeng** [apache/incubator-dolphinscheduler#4183]
**Which version of Dolphin Scheduler:**
 -[1.3.3]

当ds的配置库无法连接的时候，alert进程只会自动重试2次，还连不上就服务就挂掉了，应该增加重试次数
When the DS config DB cannot be connected, the alert process will automatically try again only twice. If it fails to connect, the service will fail. Therefore, the number of retries should be increased

**Comment by glxfeng** [comment]
![Uploading 企业微信截图_67252ebf-501f-4ca7-9204-b42a3af32bc0.png…]()

**Comment by zhuangchong** [comment]
Dolphin reference data source connection pool of druid, you can modify the conf/datasource. The properties files related to the attribute value to achieve the results you want. Do you have any better ideas, please leave a comment.

---
dolphin数据源连接池引用的alibaba druid，你可以通过修改conf/datasource.properties文件内相关属性值来达到你想要的结果。你有什么更好的想法，欢迎留言。

**Comment by CalvinKirs** [comment]
The redundant reconnection is meaningless and you should check for other reasons. If you need, you can modify the conf to meet your expectations.

**Comment by glxfeng** [comment]
> Dolphin reference data source connection pool of druid, you can modify the conf/datasource. The properties files related to the attribute value to achieve the results you want. Do you have any better ideas, please leave a comment.
> 
> dolphin数据源连接池引用的alibaba druid，你可以通过修改conf/datasource.properties文件内相关属性值来达到你想要的结果。你有什么更好的想法，欢迎留言。

但是当ds配置库网络故障恢复之后，alert进程退出了，其他服务都能正常重连。如您所说所有服务都用同一个连接池，那应该都能恢复才对。
