### ISSUE TITLE
[Bug][Api] When the amount of json data is large, the access process instance is slow

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4190]
![image](https://user-images.githubusercontent.com/55787491/101614739-471be980-3a48-11eb-81ee-03fbb2b365f9.png)

![image](https://user-images.githubusercontent.com/55787491/101614985-919d6600-3a48-11eb-8d4d-54b2c580366e.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Comment by lenboo** [comment]
we can query the information that only  needed by the web.
