### ISSUE TITLE
[Question]When I run spark on Yarn job, unread the log.

### ISSUE THREAD

**Issue by isLiuXinxin** [apache/incubator-dolphinscheduler#4199]
**Describe the question**
When I run spark on Yarn job, unread the log. The job was succeed.But I can't see the log with the ERROR:
[ERROR] 2020-12-10 15:35:03.650 org.apache.dolphinscheduler.remote.NettyRemotingServer:[167] - NettyRemotingServer bind fail bind(..) failed: 地址已在使用, exit
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: 地址已在使用
![Snipaste_2020-12-10_15-51-36](https://user-images.githubusercontent.com/68263094/101737314-a8eb5a80-3aff-11eb-801c-2c946f292955.png)

**Which version of DolphinScheduler:**
 -[1.3.3]
![Snipaste_2020-12-10_15-53-32](https://user-images.githubusercontent.com/68263094/101737480-e5b75180-3aff-11eb-8cde-4e5e16b8f6cf.png)

**Comment by xloya** [comment]
If you didn't change master's or worker's default listen port,check the port 1234 and 5678 whether were used by other application before master or worker started,the problem looks like the port occupation

**Comment by isLiuXinxin** [comment]
> If you didn't change master's or worker's default listen port,check the port 1234 and 5678 whether were used by other application before master or worker started,the problem looks like the port occupation


Thank you. It could be this problem,  after I restart the cluster, the problem was solved.
