### ISSUE TITLE
sql parse error!!!

### ISSUE THREAD

**Issue by CrazyBeeline** [apache/incubator-dolphinscheduler#4207]
I want to load some data into hive,DAY is a parmars

![image](https://user-images.githubusercontent.com/25030234/101866014-c4636d80-3bb2-11eb-8357-3d8838e6fec7.png)

load data inpath '/flow/flume/${DAY}/flow-*.json'  into table ods_flow_source partition (day='${DAY}')

but parse error log as follow：
![image](https://user-images.githubusercontent.com/25030234/101866165-14423480-3bb3-11eb-8a9f-a6a6fbc669f4.png)
![image](https://user-images.githubusercontent.com/25030234/101866178-1a381580-3bb3-11eb-81ef-8cf944c6b4aa.png)
how can i load data into hive by sql

**Comment by CalvinKirs** [comment]
Please provide your version and steps on how to reproduce it.

**Comment by CrazyBeeline** [comment]
版本:1.3.3
os:centos7.6
java:1.8.0_181


![image](https://user-images.githubusercontent.com/25030234/101867745-da732d00-3bb6-11eb-8a55-20ec1818aed1.png)
load data inpath '/flow/flume/${DAY}/flow-*.json'  into table ods_flow_source partition (day='${DAY}')
![image](https://user-images.githubusercontent.com/25030234/101867771-e828b280-3bb6-11eb-88f7-dbc829a91859.png)
![image](https://user-images.githubusercontent.com/25030234/101867785-f24ab100-3bb6-11eb-8d55-c437a3765f0d.png)

If I run with sql  no parameter it with run correct like this:
load data inpath '/flow/flume/2020-12-11/flow-*.json'  into table ods_flow_source partition (day='${DAY}')

**Comment by CrazyBeeline** [comment]
dear  @CalvinKirs  I find the reason
ds code:
![image](https://user-images.githubusercontent.com/25030234/101870857-67b98000-3bbd-11eb-93c3-0de7191d4e2b.png)
in my test code:
![image](https://user-images.githubusercontent.com/25030234/101870948-96375b00-3bbd-11eb-8a1d-315b732b0c58.png)

resutl is :load data inpath '/flow/flume/?/flow-*.json' into table ods_flow_source partition (day=2020-12-11)

hive can not replace '?' which in \' or  \\'
hear is the hive code：
![image](https://user-images.githubusercontent.com/25030234/101871137-00500000-3bbe-11eb-8e0b-b41d8dbe8d19.png)

I  have to run sql :load data inpath '/flow/flume/?/flow-*.json' into table ods_flow_source partition (day=?)
in this sql make the program more flexible.
if ds can help me solve the probwlem?
what sense sql parameter ？
![image](https://user-images.githubusercontent.com/25030234/101871508-a56ad880-3bbe-11eb-812c-732113efb863.png)

**Comment by zhengshubin** [comment]
问题解决了吗，我也是这个问题
