### ISSUE TITLE
[improvement] ProcessService invalid code removal

### ISSUE THREAD

**Issue by keepmeup** [apache/incubator-dolphinscheduler#4215]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.
org.apache.dolphinscheduler.service.process.ProcessService#checkTaskExistsInTaskQueue方法恒返回false

**Which version of DolphinScheduler:**
1.1.3

**Additional context**
![image](https://user-images.githubusercontent.com/41229600/101970917-6002e580-3c68-11eb-84c1-135b943ec38b.png)

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
如果返回恒定值，业务逻辑是否完备

**Comment by CalvinKirs** [comment]
I'm grateful for your feedback, I noticed that this is indeed a problem, I will follow up on this issue

**Comment by CalvinKirs** [comment]
I have confirmed, org.apache.dolphinscheduler.service.process.ProcessService#checkTaskExistsInTaskQueue
org.apache.dolphinscheduler.service.process.ProcessService#taskZkInfo
The code in these two places can be deleted without any impact. It belongs to history question.

Can you complete this task? Others interested can also leave a message below.

**Comment by drunkenlegend** [comment]
Hey @CalvinKirs can i do the task mentioned?

**Comment by CalvinKirs** [comment]
> Hey @CalvinKirs can i do the task mentioned?

Looking forward to your PR submission

**Comment by keepmeup** [comment]
抱歉，我没有想到会如此快的收到回复，错过了这条消息。。。 @CalvinKirs 
![image](https://user-images.githubusercontent.com/41229600/102155436-81591100-3eb6-11eb-87a5-c4b19cf5ccf5.png)
