### ISSUE TITLE
Some suggestions about mail service on DS

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#4234]
![image](https://user-images.githubusercontent.com/42087586/102202570-74620f00-3f02-11eb-8d16-b5be7092315c.png)

建议一：取消sql查询必须绑定邮件才能使用的限制，把必须绑定邮件改为可选项，并且对数据库的操作结果可以通过日志体现
理由：在生产环境中，许多公司把ds都是部署在内网环境中的，有些公司没有搭建内部邮件服务器的话就无法使用这一功能，很不人性化。
![image](https://user-images.githubusercontent.com/42087586/102202956-efc3c080-3f02-11eb-91a4-7b91ec2c263f.png)
建议二：建议在邮件告警组里增加邮件告警服务的内部接口转发配置
理由：在生产环境中，许多公司把ds都是部署在内网环境中的，需要对邮件内容进行转发到接口机才能使用，增加邮件接口转发功能后配置起来更加人性化。

**Comment by CalvinKirs** [comment]
We are working on Alert SPI, you can refer to #3049

Btw，please use English to describe your problem.Thx

**Comment by shiliquan** [comment]
Do not seem to see on the sql task mail alarm optimization, suggested to the optional, thank you!

**Comment by CalvinKirs** [comment]
> Do not seem to see on the sql task mail alarm optimization, suggested to the optional, thank you!

I don't understand the historical background at that time, this issue may need to be discussed.

**Comment by chengshiwen** [comment]
Close by #5104

The switch to send mail has supported in next 1.3.6

![image](https://user-images.githubusercontent.com/4902714/114265730-07303780-9a25-11eb-8d2a-7d75a591d222.png)
