### ISSUE TITLE
[Improvement][solution] Document Dolphin schemes for ordinary users on Linux OS and run with ordinary permissions

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#4235]
**Describe the question**
Document Dolphin schemes for ordinary users on Linux OS and run with ordinary permissions
Cluster deployment - The third step is to create the sudo non-secret configuration in the deployment users and hosts mapping step

```
echo 'dolphinscheduler  ALL=(userA,userB,userC)  NOPASSWD: NOPASSWD: ALL' >> /etc/sudoers
```

Where the userA,userB, and userC representatives are Linux OS users, they are used for multi-tenancy to submit jobs to the big data cluster.

With the addition of new tenants, it added sudo configuration permission control to the machine where dolphin Worker node submitted the operation application, which also realized the use permission control of machine OS users.

Resolving the Sudo issue, Dolphin is fully capable of running with normal Linux OS users and normal permissions.

For more information, see:
https://mp.weixin.qq.com/s/vpFCordtJE0G9bCNYg-Qgw

---

**描述问题**
记录Dolphin在Linux OS普通用户并使用普通权限运行的方案
官网文档集群部署-第三步创建部署用户和hosts映射步骤中sudo免密配置

```
echo 'dolphinscheduler  ALL=(userA,userB,userC)  NOPASSWD: NOPASSWD: ALL' >> /etc/sudoers
```

其中userA,userB,userC代表是linux OS用户，用于多租户向大数据集群提交作业。
后面有新增租户，提交运营申请dolphin worker节点所在机器新增sudo配置权限控制，也实现了机器OS用户使用权限控制。
解决了sudo问题，dolphin完全可以使用Linux OS普通用户和普通权限运行。

详细信息可以看：
https://mp.weixin.qq.com/s/vpFCordtJE0G9bCNYg-Qgw

**Comment by CalvinKirs** [comment]
hi, chong, great suggestion, can you send it to the dev mailing list, I think it is better to discuss this matter in the mail

**Comment by zhuangchong** [comment]
> hi, chong, great suggestion, can you send it to the dev mailing list, I think it is better to discuss this matter in the mail

https://lists.apache.org/thread.html/r69e990bf41bc651477c69031638af2ff211d0ecab6871c0f8b3f7d5d%40%3Cdev.dolphinscheduler.apache.org%3E
