### ISSUE TITLE
zookeeper version [Question] Question title

### ISSUE THREAD

**Issue by zfq314** [apache/incubator-dolphinscheduler#4239]
zookeeper-3.4.10
 这个版本的zookeeper可以吗

**Comment by felix-thinkingdata** [comment]
> zookeeper-3.4.10
> 这个版本的zookeeper可以吗

I have no problem with ZooKeeper version 3.4.6.

**Comment by zfq314** [comment]
Yes I know ,but i want to know ZooKeeper version 3.4.10 ,can you tell me ?thanks

**Comment by felix-thinkingdata** [comment]
> Yes I know ,but i want to know ZooKeeper version 3.4.10 ,can you tell me ?thanks
I don't think there will be any problem。You can test it with the ZooKeeper Docker environment
docker pull zookeeper:3.4.10
docker run --privileged=true -d --name zookeeper --publish 2181:2181  -d zookeeper:3.4.10

**Comment by zfq314** [comment]
ok,thanks
