### ISSUE TITLE
用户权限问题

### ISSUE THREAD

**Issue by zfq314** [apache/incubator-dolphinscheduler#4242]
先删除了用户，然后资源忘了删除 ，结果上传的文件无法删除
![image](https://user-images.githubusercontent.com/33599707/102309822-a461ee80-3fa4-11eb-8d38-04f5d4c4f531.png)
如图所示，希望回复。

**Comment by dailidong** [comment]
please update/add title and desc in English, thx

**Comment by zfq314** [comment]
what ?can you speak chinese?

**Comment by zfq314** [comment]
please speak chinese

**Comment by CalvinKirs** [comment]
Please use English. We need to consider all contributors around the world. Currently, English is more common.
I will close it, and when you change to English, you can reopen it.

**Comment by zfq314** [comment]
First delete the user, then forget to delete the resource, as a result, the uploaded file cannot be deleted
![image](https://user-images.githubusercontent.com/33599707/102436653-03327100-4054-11eb-83be-7db2d4c8d03e.png)
How to deal with this?
