### ISSUE TITLE
[Bug][Api] When schedulertime is empty, rerun the workflow, the time of the global parameter is not the latest

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4247]
1. When schedulertime is empty
2. Rerun the workflow, the time of the global parameter is still the time of the last workflow execution

![image](https://user-images.githubusercontent.com/55787491/102322845-ae8ee780-3fba-11eb-9cd0-4dd779c9505b.png)
![image](https://user-images.githubusercontent.com/55787491/102322881-b8b0e600-3fba-11eb-909a-3c4d9484fb09.png)
![image](https://user-images.githubusercontent.com/55787491/102322983-daaa6880-3fba-11eb-9dde-e44726be1ad3.png)
Expired result
When schedulertime is empty, The time of the global parameter should be the time of the rerun

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Comment by zt-1997** [comment]
I will fix it.
