### ISSUE TITLE
[Bug][Module Name] Bug title 

### ISSUE THREAD

**Issue by mumuCode** [apache/incubator-dolphinscheduler#4248]
*数据源功能下，测试连接IMPALA，页面无响应，然后一会页面就自动退出用户登陆了，相关截图如下
1.页面截图
![image](https://user-images.githubusercontent.com/19399826/102323712-d03c9e80-3fbb-11eb-8a54-aeb834605f7b.png)
2.日志截图
![image](https://user-images.githubusercontent.com/19399826/102323799-eba7a980-3fbb-11eb-9c5d-ba59d6a67444.png)
3.添加jar包截图
![image](https://user-images.githubusercontent.com/19399826/102323849-f9f5c580-3fbb-11eb-9132-de683199125b.png)

*辛苦看下我所描述的问题，谢谢了！

**Comment by zhuangchong** [comment]
我这网络有问题，看不到图片，你先看一下 下面的issues，是否可以解决你的问题，这是我在dolphin里面配置impala数据源使用的方法
https://github.com/apache/incubator-dolphinscheduler/issues/3407

**Comment by zhuangchong** [comment]
There are two JDBC connections, impala-JDBC and Hive-JDBC, and the Hive-JDBC connection is also used in the Cloudera test case (dolphin is currently using the same method). It is planned that the latter two can be supported.

---
impala 是有两种jdbc连接方式,使用impala-jdbc和hive-jdbc，在Cloudera 测试用例中也是使用hive-jdbc方式连接impala（dolphin目前也是这种）,规划是后面两种都可以支持

**Comment by CalvinKirs** [comment]
Has your problem been solved?

**Comment by mumuCode** [comment]
解决了，修改源码，在数据源添加的位置将Impala跟Hive区分开了，然后加载对应的Impala JDBC驱动
