### ISSUE TITLE
[Question]about org.apache.dolphinscheduler.server.master.dispatch.host.assign.RoundRobinSelector.java

### ISSUE THREAD

**Issue by hu-asc** [apache/incubator-dolphinscheduler#4258]
git branch: 1.3.4
My English is limited. Sorry.
I was confused about this class.
`@Service
public class RoundRobinSelector<T> implements Selector<T> {

    private final AtomicInteger index = new AtomicInteger(0);

    @Override
    public T select(Collection<T> source) {
        if (source == null || source.size() == 0) {
            throw new IllegalArgumentException("Empty source.");
        }

        /**
         * if only one , return directly
         */
        if (source.size() == 1) {
            return (T)source.toArray()[0];
        }

        int size = source.size();
        /**
         * round robin
         */
        return (T) source.toArray()[index.getAndIncrement() % size];
    }
}
`

When ths AtomicInteger'value is larger than Integer.MAX_VALUE,  the method of 'select' can also work right?

Thanks!

**Comment by CalvinKirs** [comment]
You are right, but the probability of this kind of problem is very low. In addition, in the dev version, we have made changes. You can have a look.

**Comment by hu-hongtao** [comment]
Thanks for your reply. I will take a loot at the dev version.

**Comment by chengshiwen** [comment]
Close the question since it has been replied
