### ISSUE TITLE
Stand-alone deployment, restart msyql server, whether it causes task scheduling problem（单机部署，重启msyql服务器，是否导致任务调度问题）

### ISSUE THREAD

**Issue by sunnyingit** [apache/incubator-dolphinscheduler#426]
Excuse me, stand-alone deployment service (work master on the same machine), if restarting the database service (not restarting the es service) will cause the previously scheduled tasks to be no longer scheduled?

---
请问一下，单机部署服务(work master 在同一台机器)，如果重启数据库服务(不是重启es服务) 会导致之前调度的任务不再调度么？

**Comment by qiaozhanwei** [comment]
db服务掉了，肯定会引起调度的失败的，但是怎么失败方式，我们这还没有测试过，需要测试一下

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
