### ISSUE TITLE
[Question]Why does the request all workflow definitions open the workflow definition list?

### ISSUE THREAD

**Issue by Hxssssss** [apache/incubator-dolphinscheduler#4261]
![image](https://user-images.githubusercontent.com/25795286/102601028-8c33d000-415a-11eb-888f-3f6b81df6c6d.png)
When the workflow is hundreds of times, the loading becomes slower.

**Comment by BoYiZhang** [comment]
Workflow definition and workflow instance share a set of code about DAG

I think task may be used for workflow instance. Workflow definition function is not used

**Comment by Hxssssss** [comment]
查看工作流实例详情的时候,会有需要用到全部的工作流定义信息嘛?

Do you need to use all workflow definition information when viewing workflow instance details?
