### ISSUE TITLE
[Question] what's the relationship between jvm memory configuration & business volume

### ISSUE THREAD

**Issue by set-daemon** [apache/incubator-dolphinscheduler#4277]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
I'm trying the DS, get some launching configurations  from  file bin/dolphinscheduler-daemon.sh like that:
```
if [ "$command" = "api-server" ]; then
  HEAP_INITIAL_SIZE=1g
  HEAP_MAX_SIZE=1g
  HEAP_NEW_GENERATION__SIZE=500m
  LOG_FILE="-Dlogging.config=classpath:logback-api.xml -Dspring.profiles.active=api"
  CLASS=org.apache.dolphinscheduler.api.ApiApplicationServer
elif [ "$command" = "master-server" ]; then
  HEAP_INITIAL_SIZE=4g
  HEAP_MAX_SIZE=4g
  HEAP_NEW_GENERATION__SIZE=2g
  LOG_FILE="-Dlogging.config=classpath:logback-master.xml -Ddruid.mysql.usePingMethod=false"
  CLASS=org.apache.dolphinscheduler.server.master.MasterServer
elif [ "$command" = "worker-server" ]; then
  HEAP_INITIAL_SIZE=2g
  HEAP_MAX_SIZE=2g
  HEAP_NEW_GENERATION__SIZE=1g
  LOG_FILE="-Dlogging.config=classpath:logback-worker.xml -Ddruid.mysql.usePingMethod=false"
  CLASS=org.apache.dolphinscheduler.server.worker.WorkerServer
elif [ "$command" = "alert-server" ]; then
  HEAP_INITIAL_SIZE=1g
  HEAP_MAX_SIZE=1g
  HEAP_NEW_GENERATION__SIZE=500m
  LOG_FILE="-Dlogback.configurationFile=conf/logback-alert.xml"
  CLASS=org.apache.dolphinscheduler.alert.AlertServer
elif [ "$command" = "logger-server" ]; then
  HEAP_INITIAL_SIZE=1g
  HEAP_MAX_SIZE=1g
  HEAP_NEW_GENERATION__SIZE=500m
  CLASS=org.apache.dolphinscheduler.server.log.LoggerServer
else
  echo "Error: No command named \`$command' was found."
  exit 1
fi
```
wondering about:
1) what's the minimal  memory for launching the entire system.
2) what's the relationship between the business volume & the memory configured above.
3)any relationships between the tasks & the memory required by DS?  for example,  one task  may exhaust 1G Bits memory, the other one exhausts 2G Bits memory ,   will it effect the  memory used by  DS ?

THX!

**Which version of DolphinScheduler:**
 -[1.3.3 ]

**Additional context**
 
**Requirement or improvement**

**Comment by dailidong** [comment]
the minimal memory has written in the file bin/dolphinscheduler-daemon.sh, but you can try set much smaller, and the stability base on your business, so you'd better have a try to get the fit
