### ISSUE TITLE
[Bug][dolphinscheduler-ui] mvn  package

### ISSUE THREAD

**Issue by lingya** [apache/incubator-dolphinscheduler#4279]
i  exec    mvn -U clean package -Prelease -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
in  win10  idea 2018.3

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install node-sass --unsafe-perm) on project dolphinscheduler-ui: Failed to run task: 'npm install node-sass --unsafe-perm' failed. java.io.IOException: Cannot run program "D:\code\dolphinscheduler\incubator-dolphinscheduler-1.3.4\dolphinscheduler-ui\node\node.exe" (in directory "D:\code\dolphinscheduler\incubator-dolphinscheduler-1.3.4\dolphinscheduler-ui"): CreateProcess error=193, %1 不是有效的 Win32 应用程序。 -> [Help 1]
[ERROR] 
 
 

**Which version of Dolphin Scheduler:**
 -[1.3.4]

**Comment by xingchun-chen** [comment]
1.You need to execute the  installation command of node-sass:
sudo npm install --unsafe-perm -g node-sass
2.Execute the packaging command:
mvn clean install -Prelease  -Dmaven.test.skip=true

**Comment by lingya** [comment]
@xingchun-chen     In Windows10  idea ，is the same error,  
![image](https://user-images.githubusercontent.com/8186398/102843985-60a83280-4445-11eb-86b1-77d5e68105a7.png)

![image](https://user-images.githubusercontent.com/8186398/102843999-6a319a80-4445-11eb-9b62-f1f1317e8f8e.png)

**Comment by xingchun-chen** [comment]
Sorry， DS currently does not support windows

**Comment by lingya** [comment]
ok，i got it ,thanks!
