### ISSUE TITLE
Consulting - Workflow Dependency（咨询 - 工作流依赖）

### ISSUE THREAD

**Issue by lzy305** [apache/incubator-dolphinscheduler#428]
Big guys:
   Under consultation, the workflow dependency is based on the table t_escheduler_process_instance field end_time to determine whether the parent task is completed. For example, workflow B 2019-06-03 06:00:00 run
 If parent workflow A,
   Hypothesis 1: Dependency (month -> early month) is the judgment workflow A end_time >= '2019-05-01' and end_time <
      '2019-05-02' Is it complete?

   Hypothesis 2: Dependency (month -> last month) is the judgment workflow A end_time >= '2019-05-31' and end_time <
      '2019-06-01' Completed

  Hypothesis 3: Dependency (month -> last month) is the judgment workflow A end_time >= '2019-05-01' and end_time <
      '2019-05-31' 31 days should have

  Hypothesis 4: Dependency (Day -> Today) is the judgment Workflow A end_time >= '2019-06-03' and end_time <
      '2019-06-04' Completed

  Hypothesis 5: Dependency (Day -> Yesterday) Yes Judgment Workflow A end_time >= '2019-06-02' and end_time <
      '2019-06-03'

  Hypothesis 5: Dependency (day -> two days ago) is the judgment workflow A end_time >= '2019-06-02' and end_time <
      '2019-06-04' This is completed in 2 days.

 Hypothesis 6: Dependency (day -> first three days) is the judgment workflow A end_time >= '2019-06-01' and end_time <
      '2019-06-04' This is completed in 3 days

And so on.

---
大佬们:
   咨询下, 工作流依赖是不是根据表t_escheduler_process_instance字段 end_time来判断父任务的是否完成. 比如工作流B 2019-06-03 06:00:00跑
 若父工作流A, 
   假设1: 依赖关系(月-> 上月初)  是判断 工作流A end_time >= '2019-05-01' and  end_time < 
      '2019-05-02' 是否完成。

   假设2: 依赖关系(月-> 上月末) 是判断 工作流A end_time >= '2019-05-31' and  end_time < 
      '2019-06-01' 是否完成

  假设3: 依赖关系(月-> 上月) 是判断 工作流A end_time >= '2019-05-01' and  end_time < 
      '2019-05-31'  31天都应该有

  假设4: 依赖关系(日-> 今天) 是判断 工作流A end_time >= '2019-06-03' and  end_time < 
      '2019-06-04' 是否完成

  假设5: 依赖关系(日-> 昨天) 是判断 工作流A end_time >= '2019-06-02' and  end_time < 
      '2019-06-03' 

  假设5: 依赖关系(日->  前两天) 是判断 工作流A end_time >= '2019-06-02' and  end_time < 
      '2019-06-04' 这2天都有完成。

 假设6: 依赖关系(日->  前三天) 是判断 工作流A end_time >= '2019-06-01' and  end_time < 
      '2019-06-04' 这3天都有完成

依次类推。

**Comment by lenboo** [comment]
目前是按照自然天来判断，上月末：判断时间是工作流A start_time/scheduler_time  between '2019-05-31 00:00:00' and '2019-05-31 23:59:59'

上月：是判断上个月从1号到月末每天都要有完成的A实例

上周： 上周7天都要有完成的A实例。

前两天： 判断昨天和前天，两天都要有完成的A实例。

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
