### ISSUE TITLE
 line 5: sqoop: command not found

### ISSUE THREAD

**Issue by masterable** [apache/incubator-dolphinscheduler#4281]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

I got the following error when creating sqoop workflow。
This is the running log of my workflow：
`[INFO] 2020-12-21 16:50:48.495  - [taskAppId=TASK-3-5-5]:[127] -  -> /tmp/dolphinscheduler/exec/process/1/3/5/5/3_5_5.command: line 5: sqoop: command not found`

This is my workflow instance configuration：
![image](https://user-images.githubusercontent.com/41288492/102759728-7c60f980-43af-11eb-9a47-2f467c71e822.png)

**Which version of DolphinScheduler:**
 -[1.3.3-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by zhuangchong** [comment]
1. Check whether there are SQOOP clients on the Worker machine
2. Check if there are configured SQOOP environment variables in the dolphinscheduler-envn.sh file

**Comment by masterable** [comment]
> 1. 检查辅助计算机上是否有SQOOP客户端
> 2. 检查dolphinscheduler-envn.sh文件中是否配置了SQOOP环境变量

I think it should be my own problem，

**Comment by masterable** [comment]
> 1. Check whether there are SQOOP clients on the Worker machine
> 2. Check if there are configured SQOOP environment variables in the dolphinscheduler-envn.sh file
I think it may be a bit misunderstanding for novices, because it has two installation directories, so the dolphinscheduler-env.sh in its two paths needs to be configured with environment variables. My problem is that the other path is not configured... So ,the error ...
