### ISSUE TITLE
[Bug][DAG Editor]  the dag node data loss by switch browser tab

### ISSUE THREAD

**Issue by geosmart** [apache/incubator-dolphinscheduler#4293]
[#4162](https://github.com/apache/incubator-dolphinscheduler/pull/4162)
[Fix][UI]: fix re-login problem in new tab and state synchronization problem in multiple tabs 

this pr  make a new problem, when you are editing  dag:
eg:
1. update a sql node and click ok(not save the dag)
2. switch tab to copy something;
3. switch to ds dag edit tab;
4. open the node param ,found that the sql change is lost!

that means,i have to save the dag with any small change! that will make the dag version boom...

**Comment by chengshiwen** [comment]
@geosmart @break60 
This is a problem caused by state synchronization in new tab. For state synchronization, we will refresh page in new opened page.
If we don't do this, the issue **the task of a certain tab is changed, and the task of another tab will not be updated synchronously** referenced by @break60 will occur.

**Comment by chengshiwen** [comment]
This is the trade-off

**Comment by geosmart** [comment]
the designing dag data will loss when:
1. switch browser to another app
2. switch browser tab

this means: 
you must design a complex dag without refer anything, that's impossibe!
or you have to save the uncomplete dag version(it's a garbage dag version, not real working when scheduled)

**Comment by chengshiwen** [comment]
Maybe I filter some scenario to resolve this issue

**Comment by geosmart** [comment]
visibility change is a good feature, if you add some filter may be better :
1. some scenario no need to refresh: **create,update**
2. some scenario need to refresh: **detail,list**
