### ISSUE TITLE
[Question] dolphinscheduler cannot get the YARN address

### ISSUE THREAD

**Issue by kamisangk** [apache/incubator-dolphinscheduler#4314]
The task is submitted and run successfully, but dolphinscheduler reports that the task status failed
After querying the log, it is found that the obtained yarn address is null, but the hosts and common are configured normally, and the yarn node is normally accessed

任务提交并运行成功，但dolphinscheduler报告任务状态失败
查询日志后发现获取到的yarn地址为null，但hosts与common均配置正常,且yarn节点正常访问

hosts
```properties
192.169.199.105 hdnn01
192.168.199.106 hdnn02
192.168.199.107 hdnn03
```

common.properties
```properties
# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://yarnIp1:8088/ws/v1/cluster/apps/%s
```

dolphinscheduler-worker.log
```
[INFO] 2020-12-25 18:17:30.759  - [taskAppId=TASK-3-4-17]:[193] - process start, process id is: 107032
[INFO] 2020-12-25 18:18:52.502  - [taskAppId=TASK-3-4-17]:[202] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/1/3/4/17, processId:107032 ,exitStatusCode:0
[INFO] 2020-12-25 18:18:52.504  - [taskAppId=TASK-3-4-17]:[419] - find app id: application_1608880603127_0014
[INFO] 2020-12-25 18:18:52.576 org.apache.dolphinscheduler.common.utils.HadoopUtils:[144] - get property:fs.defaultFS -> hdfs://hdcluster, from core-site.xml hdfs-site.xml 
[INFO] 2020-12-25 18:19:09.220 org.apache.dolphinscheduler.common.utils.HadoopUtils:[206] - application url : http://null:8088/ws/v1/cluster/apps/%s
[ERROR] 2020-12-25 18:19:24.259 org.apache.dolphinscheduler.common.utils.HttpUtils:[73] - null: Name or service not known
java.net.UnknownHostException: null: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.dolphinscheduler.common.utils.HttpUtils.get(HttpUtils.java:60)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getApplicationStatus(HadoopUtils.java:412)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:378)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.AbstractYarnTask.handle(AbstractYarnTask.java:57)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-12-25 18:19:24.260  - [taskAppId=TASK-3-4-17]:[392] - yarn applications: [application_1608880603127_0014]  status failed 
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getApplicationStatus(HadoopUtils.java:415)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:378)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.AbstractYarnTask.handle(AbstractYarnTask.java:57)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-12-25 18:19:24.261 org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread:[137] - task instance id : 17,task final status : FAILURE
```

**Comment by felix-thinkingdata** [comment]
which dolphinscheduler version ?

**Comment by kamisangk** [comment]
@felix-thinkingdata 1.3.3

**Comment by felix-thinkingdata** [comment]
> @felix-thinkingdata 1.3.3

http://hdnn01:8088/ws/v1/cluster/info


You try this link to return what, screenshot to me

**Comment by felix-thinkingdata** [comment]
> @felix-thinkingdata 1.3.3

Which WeChat group are you in

**Comment by kamisangk** [comment]
> > @felix-thinkingdata 1.3.3
> 
> http://hdnn01:8088/ws/v1/cluster/info
> 
> You try this link to return what, screenshot to me
> 
> ```
> curl http://hdnn01:8088/ws/v1/cluster/info
> ```
> 
> or run this cmd

`<clusterInfo>
<id>1608880599999</id>
<startedOn>1608880599999</startedOn>
<state>STARTED</state>
<haState>STANDBY</haState>
<rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName>
<resourceManagerVersion>3.2.1</resourceManagerVersion>
<resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion>
<resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn>
<hadoopVersion>3.2.1</hadoopVersion>
<hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion>
<hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn>
<haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState>
</clusterInfo>`




> > @felix-thinkingdata 1.3.3
> 
> Which WeChat group are you in

Apache DolphinScheduler Group 7

**Comment by kamisangk** [comment]
> > @felix-thinkingdata 1.3.3
> 
> Which WeChat group are you in

Apache DolphinScheduler Group 7




> > @felix-thinkingdata 1.3.3
> 
> Which WeChat group are you in

`<clusterInfo>
<id>1607770533333</id>
<startedOn>1607770533333</startedOn>
<state>STARTED</state>
<haState>STANDBY</haState>
<rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName>
<resourceManagerVersion>3.2.1</resourceManagerVersion>
<resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion>
<resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn>
<hadoopVersion>3.2.1</hadoopVersion>
<hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion>
<hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn>
<haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState>
</clusterInfo>`

**Comment by kamisangk** [comment]
> > @felix-thinkingdata 1.3.3
> 
> Which WeChat group are you in

Apache DolphinScheduler Group 7


> > @felix-thinkingdata 1.3.3
> 
> http://hdnn01:8088/ws/v1/cluster/info
> 
> You try this link to return what, screenshot to me
> 
> ```
> curl http://hdnn01:8088/ws/v1/cluster/info
> ```
> 
> or run this cmd

`<clusterInfo>
<id>1607770533333</id>
<startedOn>1607770533333</startedOn>
<state>STARTED</state>
<haState>STANDBY</haState>
<rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName>
<resourceManagerVersion>3.2.1</resourceManagerVersion>
<resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion>
<resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn>
<hadoopVersion>3.2.1</hadoopVersion>
<hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion>
<hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn>
<haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState>
</clusterInfo>`

**Comment by felix-thinkingdata** [comment]
> > > @felix-thinkingdata 1.3.3
> > 
> > 
> > Which WeChat group are you in
> 
> Apache DolphinScheduler Group 7
> 
> > > @felix-thinkingdata 1.3.3
> > 
> > 
> > http://hdnn01:8088/ws/v1/cluster/info
> > You try this link to return what, screenshot to me
> > ```
> > curl http://hdnn01:8088/ws/v1/cluster/info
> > ```
> > 
> > 
> > or run this cmd
> 
> `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`

Isn't the return in JSON format?

**Comment by kamisangk** [comment]
> > > > @felix-thinkingdata 1.3.3
> > > 
> > > 
> > > Which WeChat group are you in
> > 
> > 
> > Apache DolphinScheduler Group 7
> > > > @felix-thinkingdata 1.3.3
> > > 
> > > 
> > > http://hdnn01:8088/ws/v1/cluster/info
> > > You try this link to return what, screenshot to me
> > > ```
> > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > ```
> > > 
> > > 
> > > or run this cmd
> > 
> > 
> > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> 
> Isn't the return in JSON format?

emmm, no, XML

**Comment by felix-thinkingdata** [comment]
> > > > @felix-thinkingdata 1.3.3
> > > 
> > > 
> > > Which WeChat group are you in
> > 
> > 
> > Apache DolphinScheduler Group 7
> > > > @felix-thinkingdata 1.3.3
> > > 
> > > 
> > > http://hdnn01:8088/ws/v1/cluster/info
> > > You try this link to return what, screenshot to me
> > > ```
> > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > ```
> > > 
> > > 
> > > or run this cmd
> > 
> > 
> > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> 
> Isn't the return in JSON format?




You try this link to return what, screenshot to me
curl http://hdnn01:8088/ws/v1/cluster/info

> http://hdnn01:8088/ws/v1/cluster/info
> You try this link to return what, screenshot to me

http://hdnn02:8088/ws/v1/cluster/info  http://hdnn03:8088/ws/v1/cluster/info http://hdnn01:8088/ws/v1/cluster/info
You try this link to return what, screenshot to me

This is probably a bug, not considering three nodes    
**yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03**

**Comment by kamisangk** [comment]
> > > > > @felix-thinkingdata 1.3.3
> > > > 
> > > > 
> > > > Which WeChat group are you in
> > > 
> > > 
> > > Apache DolphinScheduler Group 7
> > > > > @felix-thinkingdata 1.3.3
> > > > 
> > > > 
> > > > http://hdnn01:8088/ws/v1/cluster/info
> > > > You try this link to return what, screenshot to me
> > > > ```
> > > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > > ```
> > > > 
> > > > 
> > > > or run this cmd
> > > 
> > > 
> > > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> > 
> > 
> > Isn't the return in JSON format?
> 
> You try this link to return what, screenshot to me
> curl http://hdnn01:8088/ws/v1/cluster/info
> 
> > http://hdnn01:8088/ws/v1/cluster/info
> > You try this link to return what, screenshot to me
> 
> http://hdnn02:8088/ws/v1/cluster/info http://hdnn03:8088/ws/v1/cluster/info http://hdnn01:8088/ws/v1/cluster/info
> You try this link to return what, screenshot to me
> 
> This is probably a bug, not considering three nodes
> **yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03**


![屏幕截图 2020-12-26 213832](https://user-images.githubusercontent.com/25461086/103152435-e966fb80-47c2-11eb-97f5-c96cd7328787.png)
The information returned is normal and consistent
After the problem occurred, I tried to modify common.properties, but still the same problem
`# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://hdnn01:8088/ws/v1/cluster/apps/%s`
This dolphinscheduler cluster was working normally before, but the correct working status cannot be obtained from Yarn after 
 24th.

**Comment by felix-thinkingdata** [comment]
> > > > > > @felix-thinkingdata 1.3.3
> > > > > 
> > > > > 
> > > > > Which WeChat group are you in
> > > > 
> > > > 
> > > > Apache DolphinScheduler Group 7
> > > > > > @felix-thinkingdata 1.3.3
> > > > > 
> > > > > 
> > > > > http://hdnn01:8088/ws/v1/cluster/info
> > > > > You try this link to return what, screenshot to me
> > > > > ```
> > > > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > > > ```
> > > > > 
> > > > > 
> > > > > or run this cmd
> > > > 
> > > > 
> > > > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> > > 
> > > 
> > > Isn't the return in JSON format?
> > 
> > 
> > You try this link to return what, screenshot to me
> > curl http://hdnn01:8088/ws/v1/cluster/info
> > > http://hdnn01:8088/ws/v1/cluster/info
> > > You try this link to return what, screenshot to me
> > 
> > 
> > http://hdnn02:8088/ws/v1/cluster/info http://hdnn03:8088/ws/v1/cluster/info http://hdnn01:8088/ws/v1/cluster/info
> > You try this link to return what, screenshot to me
> > This is probably a bug, not considering three nodes
> > **yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03**
> 
> ![屏幕截图 2020-12-26 213832](https://user-images.githubusercontent.com/25461086/103152435-e966fb80-47c2-11eb-97f5-c96cd7328787.png)
> The information returned is normal and consistent
> After the problem occurred, I tried to modify common.properties, but still the same problem
> `# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
> yarn.resourcemanager.ha.rm.ids=
> 
> # if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
> yarn.application.status.address=[http://hdnn01:8088/ws/v1/cluster/apps/%s`](http://hdnn01:8088/ws/v1/cluster/apps/%s%60)
> This dolphinscheduler cluster was working normally before, but the correct working status cannot be obtained from Yarn after
> 24th.

我在7群，看微信

**Comment by kamisangk** [comment]
> > > > > @felix-thinkingdata 1.3.3
> > > > 
> > > > 
> > > > Which WeChat group are you in
> > > 
> > > 
> > > Apache DolphinScheduler Group 7
> > > > > @felix-thinkingdata 1.3.3
> > > > 
> > > > 
> > > > http://hdnn01:8088/ws/v1/cluster/info
> > > > You try this link to return what, screenshot to me
> > > > ```
> > > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > > ```
> > > > 
> > > > 
> > > > or run this cmd
> > > 
> > > 
> > > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> > 
> > 
> > Isn't the return in JSON format?
> 
> You try this link to return what, screenshot to me
> curl http://hdnn01:8088/ws/v1/cluster/info
> 
> > http://hdnn01:8088/ws/v1/cluster/info
> > You try this link to return what, screenshot to me
> 
> http://hdnn02:8088/ws/v1/cluster/info http://hdnn03:8088/ws/v1/cluster/info http://hdnn01:8088/ws/v1/cluster/info
> You try this link to return what, screenshot to me
> 
> This is probably a bug, not considering three nodes
> **yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03**




![屏幕截图 2020-12-26 213832](https://user-images.githubusercontent.com/25461086/103152624-bde51080-47c4-11eb-9e92-e50821c4ae9b.png)
The information returned is normal and consistent
After trying to modify common.properties again, it can correctly obtain the job status of yarn
`yarn.resourcemanager.ha.rm.ids=
yarn.application.status.address=http://hdnn01:8088/ws/v1/cluster/apps/%s`
This dolphinscheduler cluster was working normally before, but the correct working status cannot be obtained from Yarn after
24th.

**Comment by felix-thinkingdata** [comment]
> > > > > > @felix-thinkingdata 1.3.3
> > > > > 
> > > > > 
> > > > > Which WeChat group are you in
> > > > 
> > > > 
> > > > Apache DolphinScheduler Group 7
> > > > > > @felix-thinkingdata 1.3.3
> > > > > 
> > > > > 
> > > > > http://hdnn01:8088/ws/v1/cluster/info
> > > > > You try this link to return what, screenshot to me
> > > > > ```
> > > > > curl http://hdnn01:8088/ws/v1/cluster/info
> > > > > ```
> > > > > 
> > > > > 
> > > > > or run this cmd
> > > > 
> > > > 
> > > > `<clusterInfo> <id>1607770533333</id> <startedOn>1607770533333</startedOn> <state>STARTED</state> <haState>STANDBY</haState> <rmStateStoreName>org.apache.hadoop.yarn.server.resourcemanager.recovery.NullRMStateStore</rmStateStoreName> <resourceManagerVersion>3.2.1</resourceManagerVersion> <resourceManagerBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum fc21ffe07c661eae8a1d4d9b5b07399</resourceManagerBuildVersion> <resourceManagerVersionBuiltOn>2019-09-10T16:07Z</resourceManagerVersionBuiltOn> <hadoopVersion>3.2.1</hadoopVersion> <hadoopBuildVersion>3.2.1 from b3cbbb467e22ea829b3808f4b7b01d07e0bf3842 by rohithsharmaks source checksum 776eaf9eee9c0ffc370bcbc1888737</hadoopBuildVersion> <hadoopVersionBuiltOn>2020-06-10T15:56Z</hadoopVersionBuiltOn> <haZooKeeperConnectionState>CONNECTED</haZooKeeperConnectionState> </clusterInfo>`
> > > 
> > > 
> > > Isn't the return in JSON format?
> > 
> > 
> > You try this link to return what, screenshot to me
> > curl http://hdnn01:8088/ws/v1/cluster/info
> > > http://hdnn01:8088/ws/v1/cluster/info
> > > You try this link to return what, screenshot to me
> > 
> > 
> > http://hdnn02:8088/ws/v1/cluster/info http://hdnn03:8088/ws/v1/cluster/info http://hdnn01:8088/ws/v1/cluster/info
> > You try this link to return what, screenshot to me
> > This is probably a bug, not considering three nodes
> > **yarn.resourcemanager.ha.rm.ids=hdnn01,hdnn02,hdnn03**
> 
> ![屏幕截图 2020-12-26 213832](https://user-images.githubusercontent.com/25461086/103152624-bde51080-47c4-11eb-9e92-e50821c4ae9b.png)
> The information returned is normal and consistent
> After trying to modify common.properties again, it can correctly obtain the job status of yarn
> `yarn.resourcemanager.ha.rm.ids= yarn.application.status.address=http://hdnn01:8088/ws/v1/cluster/apps/%s`
> This dolphinscheduler cluster was working normally before, but the correct working status cannot be obtained from Yarn after
> 24th.

can you fix this bug ,push to dev  branch?
