### ISSUE TITLE
[Feature][API] Rename tenant code

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#4318]
This'tenant code' is ambiguous and easily misleading.
As shown below:

![image](https://user-images.githubusercontent.com/39816903/103189254-b9287580-4906-11eb-8a69-687211e8f83e.png)

'Tenant Code' is actually'Operating System User'

It is recommended to rename to:'operating system tenant'

-------

这个'租户编码' 存在歧义啊, 容易产生误导.
如下图:

![image](https://user-images.githubusercontent.com/39816903/103189254-b9287580-4906-11eb-8a69-687211e8f83e.png)

'租户编码' 实际上是 '操作系统用户'

建议重命名为 :  '操作系统租户' .

**Comment by zhanguohao** [comment]
i will fix it

**Comment by chengshiwen** [comment]
Can we display the tenant name only? @BoYiZhang @CalvinKirs @dailidong 
And we can give some tip, like **The actual user to execute task**

**Comment by lenboo** [comment]
> Can we display the tenant name only? @BoYiZhang @CalvinKirs @dailidong

i am afraid that cannot find the tenant's information directly.

> And we can give some tip, like **The actual user to execute task**

good idea!

**Comment by BoYiZhang** [comment]
hi: 


I think so


But the amount of code changes may be a little more ...
On 03/25/2021 11:35，bao ***@***.***> wrote：

Can we display the tenant name only? @BoYiZhang@***@***.***

i am afraid that cannot find the tenant's information directly.

And we can give some tip, like The actual user to execute task

good idea!

**Comment by BoYiZhang** [comment]
hi:


There is already a pr, and merged


https://github.com/apache/incubator-dolphinscheduler/pull/3949
On 03/25/2021 11:35，bao ***@***.***> wrote：

Can we display the tenant name only? @BoYiZhang@***@***.***

i am afraid that cannot find the tenant's information directly.

And we can give some tip, like The actual user to execute task

good idea!
