### ISSUE TITLE
[Question] How to config alert for Dingtalk?  

### ISSUE THREAD

**Issue by zh0122** [apache/incubator-dolphinscheduler#4319]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
How to config alert for Dingtalk? 
**Which version of DolphinScheduler:**
 - [dev] 20201225 

**Additional context**
I have build DS from the latest code in dev branch, but can't find any interface to config Dingtalk. 
Is there any doc for config Dingtalk alter ? 

Thx

**Comment by dailidong** [comment]
you can referer PR : https://github.com/apache/incubator-dolphinscheduler/pull/2594

**Comment by dailidong** [comment]
![image](https://user-images.githubusercontent.com/15833811/103194410-8ab49580-491a-11eb-8e38-cdf862d38617.png)

**Comment by zh0122** [comment]
I have edited alert.properties according to #2594.  And the robot is working nomal with curl cmd or java project. 

But the robot is still not working in DS. 

Is there any UI in DS if the altert config is success? 

Thx

![image](https://user-images.githubusercontent.com/4396287/103196129-91450c00-491e-11eb-9af7-bcc2f6f6f178.png)

![image](https://user-images.githubusercontent.com/4396287/103196534-542d4980-491f-11eb-98b1-f81c9d853f8c.png)

**Comment by CalvinKirs** [comment]
This part of the function has not been fully completed. If you are not in a hurry, you can wait a moment. Our alarm group is developing SPI, and he is in alert_ plugin_ Design branch. After the subsequent development, the version will be released, and you can use it at that time.

**Comment by zh0122** [comment]
> This part of the function has not been fully completed. If you are not in a hurry, you can wait a moment. Our alarm group is developing SPI, and he is in alert_ plugin_ Design branch. After the subsequent development, the version will be released, and you can use it at that time.

I will build the alert_ plugin_ Design branch and try it. Thanks.
