### ISSUE TITLE
How to integrate DolphinScheduler to Ambari?

### ISSUE THREAD

**Issue by isLiuXinxin** [apache/incubator-dolphinscheduler#4321]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
It was mentioned in the sharing meeting the other day. How to integrate DolphinScheduler to Ambari?

**Which version of DolphinScheduler:**
 -[1.3.3]

**Comment by dailidong** [comment]
you can refer the README doc: https://github.com/apache/incubator-dolphinscheduler/tree/1.3.3-release/ambari_plugin

**Comment by CalvinKirs** [comment]
hi, has your problem been solved?

**Comment by zosimer** [comment]
> you can refer the README doc: https://github.com/apache/incubator-dolphinscheduler/tree/1.3.3-release/ambari_plugin

This document is based on version 2.5.2 of Ambari,I want to integrate ambari 2.7. I tried, but I couldn't integrate successfully

**Comment by isLiuXinxin** [comment]
> you can refer the README doc: https://github.com/apache/incubator-dolphinscheduler/tree/1.3.3-release/ambari_plugin

Thanks! It helps me a lot.

**Comment by isLiuXinxin** [comment]
> hi, has your problem been solved?

Because I didn't understand it at first, but Now I do. Thanks.

**Comment by CalvinKirs** [comment]
> > hi, has your problem been solved?
> 
> Because I didn't understand it at first, but Now I do. Thanks.

Thx, I will close it.

**Comment by zosimer** [comment]
> > you can refer the README doc: https://github.com/apache/incubator-dolphinscheduler/tree/1.3.3-release/ambari_plugin
> 
> Thanks! It helps me a lot.

can you tel me you used ambari version? I used ambari can't integrate dolphinscheduler1.3.3
