### ISSUE TITLE
[Improvement][UI] Add description field to data source list

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#4326]
**Describe the question**
 [UI] Add description field to data source list

**Which version of DolphinScheduler:**
 -[dev]

Anyone interested can claim this PR.

**Comment by xxjingcd** [comment]
I want to resolve this issue

**Comment by xxjingcd** [comment]
hi，this is my pr [#4362](https://github.com/apache/incubator-dolphinscheduler/pull/4362)  for this issue

**Comment by zhuangchong** [comment]
done. #4362
