### ISSUE TITLE
No log file was generated

### ISSUE THREAD

**Issue by DimeSnow** [apache/incubator-dolphinscheduler#4334]
**Which version of DolphinScheduler:**
 -[1.3.3]

Hello.I'm a beginner of DS.I have deployed DS(Standalone).However, after I execute the task, I am prompted to fail, but the log file is not generated.It generates a folder with a numeric name, but no log file with the suffix log.I noticed that the producer of the log folder is root and the permission is 755.Is this a matter of authority?In install.sh,deployUser="dolphinscheduler".Is there something wrong with my configuration?Thank you.

你好，我是一位ds的初学者。我单机部署了DS，但是当我执行了sqoop2hive的时候，我发现执行失败，当我查看日志了，发现没有生成日志文件，但是它生成了两个名字是数字的文件夹，文件夹里面没有任何文件，我注意到这两个文件夹的生成者是root，文件夹权限为755，这意味着除了root用户别的用户将不能在这里面生成文件，是我哪里配置出错了吗?谢谢

**Comment by dailidong** [comment]
did you use root to deploy DolphinScheduler? you should check the warn/exception message in the worker server runtime log 

------
你是不是使用root部署的DolphinScheduler？如果任务运行失败，你可以查看下worker server的运行日志，看看里面有异常信息么？

**Comment by DimeSnow** [comment]
I found port 50051 occupied by error.
When I use bash stop- all.sh After checking JPS, we found that five services were stopped, but port 1234,5678,50051 was not released sometimes. This means that the next time I restart the service, the port will be occupied. When I use the Kill Command, the service is normal.
你好，我发现这个问题是因为端口50051被占用。
我是通过使用 stop-all.sh来停止服务的，但是我发现并不是每一次1234 5678 50051都会被释放，我查看了JPS，的确是服务停止了。有时候他们似乎还在被使用着。这导致了下一次启动的时候，端口被占用。我现在每次重启都会先检查这几个端口的情况。现在DS是正常的。谢谢

**Comment by xingchun-chen** [comment]
The service is not stopped. Are you using the same user to start the service and stop the service?

**Comment by DimeSnow** [comment]
I think so. Could it be the operating system?I use ubantu 18.04LTS.
Do not rule out my improper operation, because later there was no such problem.

我觉得我是同一用户启动和停止服务，这可能是操作系统的原因吗，我使用的是乌班图18.04
当然我不排除这可能是我操作不当，因为后来这个问题就没有发生了。很感谢
