### ISSUE TITLE
Zk connection failed

### ISSUE THREAD

**Issue by lbjyuer** [apache/incubator-dolphinscheduler#4343]
![image](https://user-images.githubusercontent.com/29470339/103301846-381fca00-4a3d-11eb-83fb-866a2dee9f8c.png)

**Comment by lbjyuer** [comment]
[INFO] 2020-12-30 01:00:04.851 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:04.852 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:05.953 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:05.953 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:07.054 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:07.055 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:08.155 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:08.156 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:09.256 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:09.257 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:10.358 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:10.359 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:11.460 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:11.460 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:12.561 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:12.561 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:13.662 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:13.663 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:14.763 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:14.764 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:15.864 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:15.865 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:16.965 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:16.966 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:18.066 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:18.067 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/127.0.0.1:2181: 拒绝连接
[INFO] 2020-12-30 01:00:19.168 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-12-30 01:00:19.168 org.apache.zookeeper.ClientCnxn:[1162] - Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: 拒绝连接

**Comment by CalvinKirs** [comment]
Please check the zk status.
