### ISSUE TITLE
[Bug][Security] Component bug

### ISSUE THREAD

**Issue by iwasjoker** [apache/incubator-dolphinscheduler#4346]
Hello,
I installed dophinscheduler and found two errors in the security center interface,my version is 1.3.3:
1. There is no "Create Worker Group" button in the worker group management
2. In queue management, the created queue cannot be deleted

Looking forward to your reply

**Comment by iwasjoker** [comment]
Is there no worker grouping because my deployment method is standalone?

**Comment by zhanguohao** [comment]
1、1.3.3  does'n support "Create Worker Group" ， if you want to change worker group, mod config file : worker.properties
![image](https://user-images.githubusercontent.com/11975398/103339650-e7e84c80-4abc-11eb-9eef-484123931deb.png)

2、1.3.3 does'n support delete queue

**Comment by iwasjoker** [comment]
> 1、1.3.3 does'n support "Create Worker Group" ， if you want to change worker group, mod config file : worker.properties
> ![image](https://user-images.githubusercontent.com/11975398/103339650-e7e84c80-4abc-11eb-9eef-484123931deb.png)
> 
> 2、1.3.3 does'n support delete queue

Thanks for your answe, i know it。
