### ISSUE TITLE
change the front page address

### ISSUE THREAD

**Issue by gaozhenfeng1** [apache/incubator-dolphinscheduler#4347]
My system to run for a long time, now I want to the front page address dolphinscheduler change in the http://192.168.1.11:12345/dolphinscheduler for other, but I configure the conf/application-api.properties don't work, how should I configure??

**Comment by gaozhenfeng1** [comment]
> My system to run for a long time, now I want to the front page address dolphinscheduler change in the http://192.168.1.11:12345/dolphinscheduler for other, but I configure the conf/application-api.properties don't work, how should I configure??

**Comment by xingchun-chen** [comment]
Deploy the api service to 192.168.1.11, and stop the api service on the current server

**Comment by gaozhenfeng1** [comment]
> Deploy the api service to 192.168.1.11, and stop the api service on the current server

I know, but I configured conf/applition-api.properties after I stopped it, and it doesn't work properly in the login screen

**Comment by xingchun-chen** [comment]
Did the api log report something wrong?

**Comment by gaozhenfeng1** [comment]
> Did the api log report something wrong?
There is no problem. After changing the IP, the login screen becomes this

![image](https://user-images.githubusercontent.com/62798940/103391802-1a925380-4b56-11eb-9ca6-03a5f40514bc.png)

**Comment by gaozhenfeng1** [comment]
> Did the api log report something wrong?

Do you have to modify this in the source code and then package the replacement
![Uploading image.png…]()

**Comment by gaozhenfeng1** [comment]
> Did the api log report something wrong?

Do you have to modify this in the source code and then package the replacement
![image](https://user-images.githubusercontent.com/62798940/103391937-8b397000-4b56-11eb-953e-2eee33852ccc.png)

**Comment by xingchun-chen** [comment]
You need to check logs/dolphinscheduler-api-server.log. After 1.3.X, the front and back ends are deployed together

**Comment by gaozhenfeng1** [comment]
> You need to check logs/dolphinscheduler-api-server.log. After 1.3.X, the front and back ends are deployed together

Could you please tell me which front file I need to change to take effect?I can't fix it myself.
![image](https://user-images.githubusercontent.com/62798940/103397380-1aed1780-4b73-11eb-81da-2093b584e229.png)

**Comment by xingchun-chen** [comment]
You can refer to the front-end development documentation ：https://dolphinscheduler.apache.org/zh-cn/docs/development/frontend-development.html

**Comment by gaozhenfeng1** [comment]
> You can refer to the front-end development documentation ：https://dolphinscheduler.apache.org/zh-cn/docs/development/frontend-development.html

That's fine. Thanks a lot
