### ISSUE TITLE
[question] api-server can't startup(无法启动)

### ISSUE THREAD

**Issue by lbjyuer** [apache/incubator-dolphinscheduler#4348]
[INFO] 2020-12-31 03:00:41.429 org.eclipse.jetty.util.log:[193] - Logging initialized @6002ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2020-12-31 03:00:41.657 org.eclipse.jetty.server.Server:[370] - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_261-b12
[INFO] 2020-12-31 03:00:41.745 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-12-31 03:00:41.859 org.eclipse.jetty.server.session:[365] - DefaultSessionIdManager workerName=node0
[INFO] 2020-12-31 03:00:41.860 org.eclipse.jetty.server.session:[370] - No SessionScavenger set, using defaults
[INFO] 2020-12-31 03:00:41.863 org.eclipse.jetty.server.session:[149] - node0 Scavenging every 600000ms
[INFO] 2020-12-31 03:00:41.877 org.eclipse.jetty.server.handler.ContextHandler:[855] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@337a6d30{application,/dolphinscheduler,[file:///tmp/jetty-docbase.6957582241333663961.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],AVAILABLE}
[INFO] 2020-12-31 03:00:41.879 org.eclipse.jetty.server.Server:[407] - Started @6455ms
[INFO] 2020-12-31 03:00:44.176 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:00:44.246 org.apache.curator.utils.Compatibility:[48] - Running in ZooKeeper 3.4.x compatibility mode
[INFO] 2020-12-31 03:00:44.247 org.apache.curator.utils.Compatibility:[61] - Using emulated InjectSessionExpiration
[INFO] 2020-12-31 03:00:44.282 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:00:44.312 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:00:44.343 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:00:44.349 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:00:44.350 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:00:44.351 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:00:44.355 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:00:44.367 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:00:44.571 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:00:44.572 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:00:44.579 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:00:44.585 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:00:44.585 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:00:46.596 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2020-12-31 03:00:46.630 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2020-12-31 03:00:46.746 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-12-31 03:00:47.194 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2020-12-31 03:00:47.422 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:00:47.443 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[WARN] 2020-12-31 03:00:47.483 org.apache.jasper.EmbeddedServletOptions:[76] - PWC5963: The scratchDir you specified: /tmp/jsp is unusable.
[INFO] 2020-12-31 03:00:47.507 org.eclipse.jetty.server.AbstractConnector:[341] - Stopped ServerConnector@bc52a41{HTTP/1.1,[http/1.1]}{0.0.0.0:12345}
[INFO] 2020-12-31 03:00:47.507 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-12-31 03:00:47.509 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:00:47.511 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@337a6d30{application,/dolphinscheduler,[file:///tmp/jetty-docbase.6957582241333663961.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}
[INFO] 2020-12-31 03:00:47.542 org.apache.dolphinscheduler.remote.NettyRemotingClient:[403] - netty client closed
[INFO] 2020-12-31 03:00:47.543 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed
[INFO] 2020-12-31 03:05:07.820 org.eclipse.jetty.util.log:[193] - Logging initialized @7464ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2020-12-31 03:05:07.979 org.eclipse.jetty.server.Server:[370] - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_261-b12
[INFO] 2020-12-31 03:05:08.023 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-12-31 03:05:08.095 org.eclipse.jetty.server.session:[365] - DefaultSessionIdManager workerName=node0
[INFO] 2020-12-31 03:05:08.096 org.eclipse.jetty.server.session:[370] - No SessionScavenger set, using defaults
[INFO] 2020-12-31 03:05:08.098 org.eclipse.jetty.server.session:[149] - node0 Scavenging every 600000ms
[INFO] 2020-12-31 03:05:08.105 org.eclipse.jetty.server.handler.ContextHandler:[855] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@322e49ee{application,/dolphinscheduler,[file:///tmp/jetty-docbase.8129660052212598733.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],AVAILABLE}
[INFO] 2020-12-31 03:05:08.106 org.eclipse.jetty.server.Server:[407] - Started @7754ms
[INFO] 2020-12-31 03:05:09.836 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:05:09.900 org.apache.curator.utils.Compatibility:[48] - Running in ZooKeeper 3.4.x compatibility mode
[INFO] 2020-12-31 03:05:09.901 org.apache.curator.utils.Compatibility:[61] - Using emulated InjectSessionExpiration
[INFO] 2020-12-31 03:05:09.941 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:05:09.969 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:05:09.991 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:05:09.996 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:05:09.997 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:05:09.999 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:05:10.002 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:05:10.013 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:05:10.218 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:05:10.218 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:05:10.220 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:05:10.225 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:05:10.225 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:05:11.993 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2020-12-31 03:05:12.017 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2020-12-31 03:05:12.097 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-12-31 03:05:12.544 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2020-12-31 03:05:12.791 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:05:12.812 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[WARN] 2020-12-31 03:05:12.858 org.apache.jasper.EmbeddedServletOptions:[76] - PWC5963: The scratchDir you specified: /tmp/jsp is unusable.
[INFO] 2020-12-31 03:05:12.881 org.eclipse.jetty.server.AbstractConnector:[341] - Stopped ServerConnector@6c1bebca{HTTP/1.1,[http/1.1]}{0.0.0.0:12345}
[INFO] 2020-12-31 03:05:12.882 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-12-31 03:05:12.883 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:05:12.885 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@322e49ee{application,/dolphinscheduler,[file:///tmp/jetty-docbase.8129660052212598733.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}
[INFO] 2020-12-31 03:05:12.914 org.apache.dolphinscheduler.remote.NettyRemotingClient:[403] - netty client closed
[INFO] 2020-12-31 03:05:12.915 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed
[INFO] 2020-12-31 03:06:14.696 org.eclipse.jetty.util.log:[193] - Logging initialized @3870ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2020-12-31 03:06:14.814 org.eclipse.jetty.server.Server:[370] - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 1.8.0_261-b12
[INFO] 2020-12-31 03:06:14.853 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-12-31 03:06:14.913 org.eclipse.jetty.server.session:[365] - DefaultSessionIdManager workerName=node0
[INFO] 2020-12-31 03:06:14.914 org.eclipse.jetty.server.session:[370] - No SessionScavenger set, using defaults
[INFO] 2020-12-31 03:06:14.915 org.eclipse.jetty.server.session:[149] - node0 Scavenging every 600000ms
[INFO] 2020-12-31 03:06:14.922 org.eclipse.jetty.server.handler.ContextHandler:[855] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@3caafa67{application,/dolphinscheduler,[file:///tmp/jetty-docbase.1981037900090949060.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],AVAILABLE}
[INFO] 2020-12-31 03:06:14.923 org.eclipse.jetty.server.Server:[407] - Started @4099ms
[INFO] 2020-12-31 03:06:16.232 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:06:16.282 org.apache.curator.utils.Compatibility:[48] - Running in ZooKeeper 3.4.x compatibility mode
[INFO] 2020-12-31 03:06:16.283 org.apache.curator.utils.Compatibility:[61] - Using emulated InjectSessionExpiration
[INFO] 2020-12-31 03:06:16.314 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:06:16.341 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:06:16.367 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:06:16.371 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:06:16.372 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:06:16.373 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:06:16.376 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:06:16.385 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:06:16.521 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[84] - zookeeper registry center init, server lists is: localhost:2181.
[INFO] 2020-12-31 03:06:16.521 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-12-31 03:06:16.522 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-12-31 03:06:16.527 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-31 03:06:16.528 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[INFO] 2020-12-31 03:06:17.967 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2020-12-31 03:06:17.992 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2020-12-31 03:06:18.074 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-12-31 03:06:18.503 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2020-12-31 03:06:18.743 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:06:18.772 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[WARN] 2020-12-31 03:06:18.831 org.apache.jasper.EmbeddedServletOptions:[76] - PWC5963: The scratchDir you specified: /tmp/jsp is unusable.
[INFO] 2020-12-31 03:06:18.864 org.eclipse.jetty.server.AbstractConnector:[341] - Stopped ServerConnector@74619273{HTTP/1.1,[http/1.1]}{0.0.0.0:12345}
[INFO] 2020-12-31 03:06:18.865 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-12-31 03:06:18.867 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2020-12-31 03:06:18.869 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@3caafa67{application,/dolphinscheduler,[file:///tmp/jetty-docbase.1981037900090949060.12345/, jar:file:/opt/soft/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/soft/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}
[INFO] 2020-12-31 03:06:18.908 org.apache.dolphinscheduler.remote.NettyRemotingClient:[403] - netty client closed
[INFO] 2020-12-31 03:06:18.910 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed

**Comment by xingchun-chen** [comment]
Please check whether the /tmp/jsp directory exists and whether the directory permissions belong to the deployment user

**Comment by lbjyuer** [comment]
Thank
