### ISSUE TITLE
[Feature][Alert]support access to feishu

### ISSUE THREAD

**Issue by diozhang** [apache/incubator-dolphinscheduler#4350]
The current version (ver 1.3.2) only supports sending alarms via email and WeChat (for example: task failure, master or worker disconnection, etc.), we need to add an alarm for accessing Feishu

**Comment by CalvinKirs** [comment]
We'll be releasing alert-spi later, and you can SPI your way to it. you are welcome to donate to the community.

**Comment by gaojun2048** [comment]
Is this issue can be close?

**Comment by felix-thinkingdata** [comment]
> We'll be releasing alert-spi later, and you can SPI your way to it. you are welcome to donate to the community.

In which version will the "feishu" alert be supported?
