### ISSUE TITLE
[Improvement] Worker-groups page cannot be operated but can only be viewed

### ISSUE THREAD

**Issue by 570944242** [apache/incubator-dolphinscheduler#4354]
#### 问题：admin账号登录后，安全中心页面Worker分组管理中，没有管理（操作）功能，只有查看分组的功能。想要设置分组，必须通过配置文件的方式设置后再重新启动，导致如果有任务在运行的情况下要添加新的分组时候很不方便。
![image](https://user-images.githubusercontent.com/33422326/103398491-f0ea2400-4b77-11eb-831f-c221380d167f.png)

**Comment by dailidong** [comment]
as a global project, Please add title/desc in English, thx

**Comment by CalvinKirs** [comment]
In version 1.3.0, the worker ip has been changed to support k8s, so we can't configure it on the UI interface, the workgroup can configure the name on worker.properties.
