### ISSUE TITLE
[Question] Create workflow, two tasks are connected with arrow line, if the first task fails, how to let the second task continue to run

### ISSUE THREAD

**Issue by xqg1316** [apache/incubator-dolphinscheduler#4357]
Create workflow, two tasks are connected with arrow line, if the first task fails, how to let the second task continue to run.
创建工作流, 两个任务用箭头线连接, 假如第一个任务失败, 如何让第二个任务继续运行

**Comment by davidzollo** [comment]
is there anybody else also need this feature? please leave message

**Comment by chengshiwen** [comment]
@xqg1316 Maybe you can consider the `Force Task Success` feature #4267
