### ISSUE TITLE
[Question] After run a workflow, can not see workflow instance lists，and command number of waiting for running increases one time.

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4358]
After run a workflow, can not see workflow instance lists，and command number of waiting for running increases one time.
(运行一个工作流后，不能看到工作流实例列表内容，且待执行命令数增加了1。)

**Which version of DolphinScheduler:**
 -[1.3.3]

**Comment by xingchun-chen** [comment]
Please check whether the master is started, or check the master log for errors

**Comment by wssmao** [comment]
I think this question is a bug.  
And I think the log can support debug mode，so fix the bug.
