### ISSUE TITLE
[Question] How to configure the self-built server to integrate mail service function

### ISSUE THREAD

**Issue by zjw-zjw** [apache/incubator-dolphinscheduler#4363]
My company uses a **self-built mail server**, may I ask how to configure the mail sending function?
When I use a service like Mailbox 163, I can receive mail normally. But with a self-built server, it doesn't work

**Which version of DolphinScheduler:**
[1.3.3]

我公司使用的是自建的邮件服务器，请问该怎么配置邮件发送功能呢？
当我使用类似163邮箱的服务，是可以正常接收邮件的。但是使用了自建的服务器就不行了

**Comment by zjw-zjw** [comment]
Can anyone answer that？

**Comment by zjw-zjw** [comment]
![image](https://user-images.githubusercontent.com/48348786/103604182-4f821a00-4f4b-11eb-89a6-30c6b91efd52.png)
This is my configuration.

**Comment by zjw-zjw** [comment]
This is my configuration:
```
mail.protocol=SMTP
mail.server.host=mailx.xxx.cn
mail.server.port=465
mail.sender=alter@xxx.cn
mail.user=alter@xxx.cn
mail.passwd=xxxxx

mail.smtp.starttls.enable=false

mail.smtp.ssl.enable=true
mail.smtp.ssl.trust=mailx.xxx.cn
```

**Comment by CalvinKirs** [comment]
You need to ensure that the mail server and alert-server network can communicate normally

**Comment by zjw-zjw** [comment]
> You need to ensure that the mail server and alert-server network can communicate normally

I find the problem。because my mail.passwd has special characters like %$. but cannot be escaped by DS。
