### ISSUE TITLE
[Question] Can dolphinscheduler send alert information by http request? How to use it?

### ISSUE THREAD

**Issue by enoughwell** [apache/incubator-dolphinscheduler#4364]
My dolphinscheduler version is 1.3.2,it is deployed in the interval network,the engineer only provided the http interface,How do i use it?
我的ds的版本是1.3.2,目前是被部署在内网,要发企业微信告警,目前运维只提供了http请求的接口,我要如何使用它呢?

**Comment by CalvinKirs** [comment]
You can wait a little, we will probably release alert-spi in the next version, which can meet your needs, and you can check the documentation to finish it then.

**Comment by enoughwell** [comment]
> You can wait a little, we will probably release alert-spi in the next version, which can meet your needs, and you can check the documentation to finish it then.

OK,Thank you!

**Comment by CalvinKirs** [comment]
> > You can wait a little, we will probably release alert-spi in the next version, which can meet your needs, and you can check the documentation to finish it then.
> 
> OK,Thank you!

You can follow this ISSUE (#3049). I will close #3049 when finished
