### ISSUE TITLE
[Improvement][api] 编辑数据源时，接口返回了数据源的明文密码

### ISSUE THREAD

**Issue by zl2439** [apache/incubator-dolphinscheduler#4367]
**Describe the question**
在编辑数据源时，`/dolphinscheduler/datasources/update-ui`接口返回了数据源的明文密码
![图片](https://user-images.githubusercontent.com/56599784/103516543-b3ed9c80-4eab-11eb-82bf-00c92f65ab5f.png)

**What are the current deficiencies and the benefits of improvement**
- 返回明文密码，不安全

**Which version of DolphinScheduler:**
 - [1.2.2]

**Comment by CalvinKirs** [comment]
Very good suggestion, are you willing to complete it?

**Comment by zhuangchong** [comment]
This has been implemented in the Dev branch.

**Comment by CalvinKirs** [comment]
close by #3330
