### ISSUE TITLE
[Bug][alert] 短信告警问题

### ISSUE THREAD

**Issue by zl2439** [apache/incubator-dolphinscheduler#4368]
**Describe the question**
当前代码中短信告警，暂无具体的实现方法，因为短信告警不可用，后续官方是否要对此功能进行实现或者有无实现计划
```org.apache.dolphinscheduler.alert.manager.MsgManager```

**Screenshots**
![图片](https://user-images.githubusercontent.com/56599784/103525404-1d74a780-4eba-11eb-8d97-1753c984ff06.png)

**Which version of Dolphin Scheduler:**
 - [1.2.2]

**Comment by CalvinKirs** [comment]
You can look at this PR#4165.
We will release alert-spi as soon as possible.
BTW, please use english
