### ISSUE TITLE
[Question] How to use time custom parameters?

### ISSUE THREAD

**Issue by lbjyuer** [apache/incubator-dolphinscheduler#4369]
![image](https://user-images.githubusercontent.com/29470339/103537757-f2954e00-4ecf-11eb-8586-9435aa603561.png)

**Comment by lbjyuer** [comment]
How to use time custom parameters？

**Comment by CalvinKirs** [comment]
hi, please refer to this (https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/system-manual.html)

BTW, for better communication, please use English

**Comment by lbjyuer** [comment]
I've seen it, but I still don't know how to use it. As shown in the figure, how to set the front day?

**Comment by CalvinKirs** [comment]
> I've seen it, but I still don't know how to use it. As shown in the figure, how to set the front day?

Sorry, I can't display your picture, it may be due to network reasons. Can you describe it in words?

**Comment by lbjyuer** [comment]
$[yyyyMMdd-N]     I write as     $[yyyyMMdd-5]     not run successfully

**Comment by CalvinKirs** [comment]
> $[yyyyMMdd-N] I write as $[yyyyMMdd-5] not run successfully

hi, please provide your version, input, expected output and actual output

**Comment by lbjyuer** [comment]
version 1.3.4

today 20200105
input  $[yyyyMMdd - 5]     output  20210101

The template is  $[yyyyMMdd-N]   But I don't know how to write it

**Comment by lbjyuer** [comment]
@CalvinKirs Hello

**Comment by CalvinKirs** [comment]
> @CalvinKirs Hello

when the data is supplemented, the date is +1

**Comment by lbjyuer** [comment]
How should I write parameters?

$[yyyyMMdd - 5]  This is not recognized by the system

@CalvinKirs

**Comment by xingchun-chen** [comment]
@lbjyuer   Replace $[front_nday] with ${front_nday}
![image](https://user-images.githubusercontent.com/55787491/103618091-52d8ce00-4f6a-11eb-818b-2740f13a8d43.png)

**Comment by lbjyuer** [comment]
OK, thank you both
