### ISSUE TITLE
What is the listening port of the master node used for? The captured packets show that the port does not exchange data when the workflow is started.

### ISSUE THREAD

**Issue by keepmeup** [apache/incubator-dolphinscheduler#4370]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.
master监听的端口是做什么用的？我们抓包看工作流启动的时候该端口没有数据交互
What is the listening port of the master node used for? The captured packets show that the port does not exchange data when the workflow is started.

**Which version of DolphinScheduler:**
1.3.3

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@keepmeup The listening port of the master node used for netty port to communicate with workers
