### ISSUE TITLE
[Improvement][website] remove online demo table in the navigation bar of the official website.

### ISSUE THREAD

**Issue by aNotBadCoder** [apache/incubator-dolphinscheduler#4373]
> > > > hi
> > > > @CalvinKirs
> > > > The three issues have been closed, show
> > > > 
> > > > * [ ]     xx
> > > >   not
> > > > * [x]     xx
> > > > 
> > > > > * [ ]      [website]docs  Improve the English version of the official community documentation easy to fix #3562
> > > > > * [ ]      [website]docs  database initialize #3766
> > > > > * [ ]      [code][UI][Improvement][UI] Add description field to data source list #4326
> > > > 
> > > > 
> > > > If there is a new issue ,you can notify me.
> > > 
> > > 
> > > hi, there is an online demo table in the navigation bar of the official website. We need to remove it. It does not conform to the apache specification. Can you remove it?
> > 
> > 
> > where is address ? I can try it.
> 
> https://github.com/apache/incubator-dolphinscheduler-website
What do you want remove  ? Can you explain that? Which online demo table?

_Originally posted by @aNotBadCoder in https://github.com/apache/incubator-dolphinscheduler/issues/4124#issuecomment-754379365_

**Comment by aNotBadCoder** [comment]
@CalvinKirs  you can assign it to me.

**Comment by aNotBadCoder** [comment]
@CalvinKirs  request review ,then merge.

**Comment by CalvinKirs** [comment]
done
