### ISSUE TITLE
sudo useradd -g dolphinscheduler 1

### ISSUE THREAD

**Issue by WeiLinCool** [apache/incubator-dolphinscheduler#4379]
本地部署1.4.3版本，配置工作流后启动工作流，报错：
[ERROR] 2021-01-05 19:03:50.336  - [taskAppId=TASK-7-18-22]:[105] - useradd：无效的用户名“1”
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: useradd：无效的用户名“1”

 -[1.4.3-master]

**Comment by WeiLinCool** [comment]
创建的用户编码不能为数字1 ，应该为英文或者英文+数字，不然会出现上述 报错，报错主要原因是：
sudo useradd -g dolphinscheduler  ‘租户编码’;  如果租户编码为数字则会报错。

**Comment by CalvinKirs** [comment]
see #4383
