### ISSUE TITLE
Create a tenant encoding an error problem as a number

### ISSUE THREAD

**Issue by WeiLinCool** [apache/incubator-dolphinscheduler#4383]
在DS创建一个租户，租户编码设置为1，定义工作流，执行工作流报错
**To Reproduce**
Steps to reproduce the behavior, for example:
1. 租户管理创建租户
2. 租户编码设置为纯数字
3. 切换租户登陆，定义工作流，执行工作流
4. 工作流报错

**Expected behavior**

[INFO] 2021-01-05 19:03:50.303  - [taskAppId=TASK-7-18-22]:[115] - execute cmd : sudo useradd -g dolphinscheduler 1
[ERROR] 2021-01-05 19:03:50.336  - [taskAppId=TASK-7-18-22]:[105] - useradd：无效的用户名“1”
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: useradd：无效的用户名“1”

**Screenshots**
![image](https://user-images.githubusercontent.com/54050841/103716421-f7582000-4ffd-11eb-8c3a-74a2fd54dcd6.png)

**Which version of Dolphin Scheduler:**
 -[1.3.4-preview]

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
在添加租户的时候，对租户编码进行限制。

**Comment by CalvinKirs** [comment]
close by #5093
