### ISSUE TITLE
[Bug][Server] When ds stopped, the zk lock path didn't removed.

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4384]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
After run a workflow, can not see workflow instance lists，and command number of waiting for running increases one time.
When ds stopped, the zk lock path didn't removed.

ie:
[zk: localhost:2181(CONNECTED) 3] ls /dolphinscheduler/lock/masters
[_c_57cb3203-dc02-4199-9331-b0f69146ea30-lock-0000349762]

**To Reproduce**
Steps to reproduce the behavior, for example:
1. run a workflow
2. can not see workflow instance lists
3. command number of waiting for running increases one time
4. When ds stopped, the zk lock path didn't removed.
5. After manually remove the path and restart ds, can see workflow instance lists.

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Additional context**
standalone mode

**Requirement or improvement**
- Please add debug log，so help fix the similar bug.

**Comment by xingchun-chen** [comment]
Who wants to find out the specific reasons?

**Comment by chengshiwen** [comment]
Close by #4626
