### ISSUE TITLE
[Question] How does ds gets task logs and determine whether task failes or successed ?

### ISSUE THREAD

**Issue by nashcen** [apache/incubator-dolphinscheduler#4386]
**How does ds gets task logs and determine whether task failes or successed ?**

I have 3 type of tasks—— datax、impala、hive，all of them are sealed in shell scripts.
When ds call these scripts,datax and impala task successed,but hive task failed.
This phenomenon confuse me.
I have asked why this happend in ds groups,and someone thell me to config yarn parameter in the $dolphinscheduler_home/conf/common.properties,because ds determine whether **hive** task is failed or successed by yarn result.

1. Now, I'm wondering how does ds determine whether **datax** and **impala** task is failed or successed?

2. And, how does ds gets logs of different type tasks,such as **datax**、**impala**、**hive**?

**Which version of DolphinScheduler:**
 -[1.3.3]

**Comment by dailidong** [comment]
first, if the task self exit code == 0, it means this task runs successfully, at the same time ,if this task is also a yarn task, we will also get the yarn result through the yarn restful api which setting in the common.properties
```
# if resourcemanager HA enable, please type the HA ips ; if resourcemanager is single, make this value empty
yarn.resourcemanager.ha.rm.ids=192.168.xx.xx,192.168.xx.xx

# if resourcemanager HA enable or not use resourcemanager, please keep the default value; If resourcemanager is single, you only need to replace ds1 to actual resourcemanager hostname.
yarn.application.status.address=http://ds1:8088/ws/v1/cluster/apps/%s
# job history status url when application number threshold is reached(default 10000,maybe it was set to 1000)
yarn.job.history.status.address=http://ds1:19888/ws/v1/history/mapreduce/jobs/%s
```

so if the task is yarn task , these two result will determine the final result

**Comment by dailidong** [comment]
> 2. And, how does ds gets logs of different type tasks,such as **datax**、**impala**、**hive**?

to this question , Dolphin runs eash task as child process which is using java ProcessBuilder class, when calling this class, it will show the task runtime log

**Comment by chengshiwen** [comment]
Close this question since it has been resolved
