### ISSUE TITLE
[Bug][server] can not use hive udf

### ISSUE THREAD

**Issue by chuyang-zl** [apache/incubator-dolphinscheduler#4387]
**Describe the bug**
The DS version is 1.2.1. After the UDF function is created, the UDF function is used incorrectly in the task node. After the resource node selects the corresponding UDF function, the error is reported in the execution log.The error log is as follows:
ds版本是1.2.1，创建UDF函数后，在任务节点中使用时报错，资源节点选择对应UDF函数后，执行日志中报错，由于加载了错误的jar包路径导致无法正常创建对应的UDF函数，报错日志如下：
![图片](https://user-images.githubusercontent.com/56599784/103725822-663f7400-5012-11eb-81a4-00add8b71046.png)

As you can see from the error log, the UDF function cannot be created due to the inability to load the JAR at the specified path, and after the UDF resource is uploaded on the resource interface, the actual location of the JAR is not the location specified at the time of loading
从报错日志可以得知，由于无法加载指定路径的jar包而导致无法创建UDF函数，在资源界面上传UDF资源后，jar包真正的位置并不是加载时指定的位置
![图片](https://user-images.githubusercontent.com/56599784/103726277-77d54b80-5013-11eb-93cd-b81382972812.png)

从issue列表中，找到了相关问题[2888](https://github.com/apache/incubator-dolphinscheduler/issues/2888)，但是已经是1.2.1版本了

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by CalvinKirs** [comment]
#2435 Can it solve your problem?

**Comment by chuyang-zl** [comment]
> 
> 
> #2435 Can it solve your problem?

进一步排查后，不是源码的问题，是自己修改了源码导致。

请教一个问题，在资源中创建一个UDF函数后，会直接将函数保存在hive 函数库中，还是在使用时创建临时函数？

**Comment by chuyang-zl** [comment]
@CalvinKirs 
Hello, this problem can be closed, not source code problem, is our secondary development problem

---

您好，这个问题可以关闭了，不是源码问题，是我们二次开发的问题
