### ISSUE TITLE
[Question] Do you have a plan to support the kill and rerun features of task level tasks?有支持任务级别的停止重跑等功能的计划嘛?

### ISSUE THREAD

**Issue by Hxssssss** [apache/incubator-dolphinscheduler#4393]
If there is one, I want to participate in the development of this function!
如果有的话,有计划在哪个版本推出嘛?
没有的话,我想参与这块功能的开发!

**Comment by xingchun-chen** [comment]
No plan at the moment, looking forward to your contribution

**Comment by Hxssssss** [comment]
> No plan at the moment, looking forward to your contribution
OK, I'll be ready to start developing.

**Comment by lzz0225** [comment]
开始实现了嘛。进展如何，我目前也有这样的需求。
