### ISSUE TITLE
[Question] How to specify the checkpoint directory when setting up flink nodes and task restart

### ISSUE THREAD

**Issue by wuzhjian** [apache/incubator-dolphinscheduler#4397]
设置flink节点，处理实时数据的时候，如何设置checkpoint，当任务彻底挂掉需要人为干预启动的时候，通过指定的checkpoint目录重启。

当任务需要修改部分代码重启，在将任务下线的时候指定savepoint，flink on yarn 目前停止任务是直接通过yarn application -kill，并不能指定savepoint

**Which version of DolphinScheduler:**
 -[1.3.3-preview]

**Comment by xingchun-chen** [comment]
English is global and necessary, please update the title in English, thanks

**Comment by chengshiwen** [comment]
@wuzhjian 
Under `yarn cluster` deploy mode, you can
- set `-yD state.backend=filesystem -yD state.checkpoints.dir=hdfs://namenode:9000/flink/checkpoints -yD state.savepoints.dir=hdfs://namenode:9000/flink/savepoints` in `other parameters` (其它参数) to configure state options
- trigger a savepoint manually by `flink savepoint <jobId> [savepointDirectory] -yid <yarnAppId>`
- set `-s <savepointPath> -n` in `other parameters` to restore from the specific savepoint path

In other deploy mode such as `local` and `session`, you can only set `state.backend`, `state.checkpoints.dir` and `state.savepoints.dir` in the configuration file `flink-conf.yaml`.

**Comment by chengshiwen** [comment]
Close this question since it has been replied
