### ISSUE TITLE
how to clear mysql data

### ISSUE THREAD

**Issue by JerryBai0106** [apache/incubator-dolphinscheduler#4401]
**Describe the question**
 Due to our tasks are becoming more and more，and we find our mysql tables (t_ds_task_instance，t_ds_process_instance) is bigger， so i get two questions 
 1. Dose the dolphinscheduler has auto clear mechanism??
 2. t_ds_task_instance and t_ds_process_instance , those tables have relationship?? may i delete those tables directly ?

 looking forWord your replay

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Comment by xingchun-chen** [comment]
You can delete the tables t_ds_task_instance and t_ds_process_instance, and you can also delete the log file corresponding to the task /data1/dolphinscheduler/logs/4/26/66.log
![image](https://user-images.githubusercontent.com/55787491/103877208-b6e8c700-510f-11eb-99e9-69583584bdb8.png)

**Comment by JerryBai0106** [comment]
> You can delete the tables t_ds_task_instance and t_ds_process_instance, and you can also delete the log file corresponding to the task /data1/dolphinscheduler/logs/4/26/66.log
> ![image](https://user-images.githubusercontent.com/55787491/103877208-b6e8c700-510f-11eb-99e9-69583584bdb8.png)
@xingchun-chen okok，get it , thanks for your replay!
