### ISSUE TITLE
[Question/Bug] when set cron job then proccess instance keep creating every second

### ISSUE THREAD

**Issue by brucemen711** [apache/incubator-dolphinscheduler#4403]
Hi,

I'm very excited about this project, thanks you so much.
Currently i have a problem when set cron tab on a job: Assume i set job run every 1 seconds and job takes larger than 1 second to finish. What i expect is new proccess instance will created only if old proccess instance finish but it seems dolphin keep creating new proccess instance every second. 

Is this a epxect behaviour ? Thanks.

**Comment by brucemen711** [comment]
@dailidong any comment on this ?

**Comment by xingchun-chen** [comment]
your issue is the same as the #4388

**Comment by brucemen711** [comment]
Thanks, i will move on that issue to discuss more

**Comment by xingchun-chen** [comment]
Ok, I will close this issue , if there are any problems, reply directly to the issue above
