### ISSUE TITLE
[Bug][api] Added worker group without verifying that IP address is the correct worker node

### ISSUE THREAD

**Issue by chuyang-zl** [apache/incubator-dolphinscheduler#4404]
**Describe the bug**
1. In worker group management, worker nodes are added without verifying whether the IP address filled in is a valid worker node
1. After the worker group is created by filling in the IP of non-worker nodes, the execution workflow selects the wrong group, so the task instance will always be unable to execute
---
1. worker分组管理中，增加worker节点，并没有验证填入的ip地址是否是有效的worker节点
1. 填入非worker节点的IP创建worker分组后，执行工作流选择错误的分组，这样任务实例就会一直无法执行

![图片](https://user-images.githubusercontent.com/56599784/103865965-f14a6800-50ff-11eb-8483-7a53835b6b22.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by xingchun-chen** [comment]
The worker group is not verified, you need to fill in a started worker ip

**Comment by chuyang-zl** [comment]
> 
> 
> The worker group is not verified, you need to fill in a started worker ip

ok
