### ISSUE TITLE
[Question][Alert]  Why doesn't dingtalk use Taobao SDK to send alert message?

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4416]
**Describe the bug**
Why doesn't dingtalk use Taobao SDK to send alert message?

**To Reproduce**
Steps to reproduce the behavior, for example:
1. When I used branch dev code，DingTalk Message send failure. 
2. When I replace the CloseableHttpClient with Taobao SDK, DingTalk Message send success.

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by CalvinKirs** [comment]
The dingtalk alert code of dev is still under development. If you need it, you can check the code of alert_plugin_design branch. We will merge it into dev and release the official version as soon as possible.
In addition, dinngtalk msg is just a simple http interaction, in my opinion, there is no need to introduce a third-party SDK.If you encounter any problems, you can raise them, preferably with other information that helps troubleshoot the problem.

**Comment by wssmao** [comment]
OK，I close this issue.
