### ISSUE TITLE
[Improvement][login controller] Need password when open in new tab

### ISSUE THREAD

**Issue by raiden2012** [apache/incubator-dolphinscheduler#4418]
**Describe the question**
The verification is based on sessionId value stored in both cookie and sessionStorage. The new browser tab always has empty sessionStorage so we need to input password again and again. 

**What are the current deficiencies and the benefits of improvement**
- Login once and need no more password when open in new tabs.

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
Maybe we can use localStorage instead of sessionStorage to make sessionId available across tabs. (Less secure?)
It's a so itchy feature.

Full details see https://blog.guya.net/2015/06/12/sharing-sessionstorage-between-tabs-for-secure-multi-tab-authentication/

**Comment by chengshiwen** [comment]
In the latest dev branch, this issue has been fixed.
Please see #4162.

**Comment by CalvinKirs** [comment]
fix by #4162
