### ISSUE TITLE
[Question] the progress support k8s deployment

### ISSUE THREAD

**Issue by zhaorongsheng** [apache/incubator-dolphinscheduler#4419]
**Describe the question**
Hi, all.
Is there any progress  about the plan supporting k8s deployment?

**Comment by chengshiwen** [comment]
@zhaorongsheng 
In the latest dev branch, the kind types of all modules are as follows:

frontend: Deployment
api: Deployment
master: StatefulSet
worker: StatefulSet
alert: Deployment

Do you want the master and worker also use the Deployment type?

**Comment by zhaorongsheng** [comment]
Yes, we want to deploy master&worker on k8s. Is there any way to do this?

**Comment by chengshiwen** [comment]
@zhaorongsheng 
Yes, the conversion of StatefulSet to Deployment can usually be solved by mounting a PVC, but I will see specifically whether PVC is really needed.
I will finish this work and  notify you in the next period of time, so please keep attention

**Comment by zhaorongsheng** [comment]
@chengshiwen thanks~  would u mind providing some detail documents about the deployment on k8s?
Our company wants to replace oozie with ds this year and we are going to try using ds in a few days.

**Comment by dailidong** [comment]
> Our company wants to replace oozie with ds this year and we are going to try using ds in a few days.

Did you see the doc : https://github.com/apache/incubator-dolphinscheduler/blob/dev/docker/kubernetes/dolphinscheduler/README.md ?

**Comment by zhaorongsheng** [comment]
> > Our company wants to replace oozie with ds this year and we are going to try using ds in a few days.
> 
> Did you see the doc : https://github.com/apache/incubator-dolphinscheduler/blob/dev/docker/kubernetes/dolphinscheduler/README.md ?

thanks~ I will try this way later

**Comment by chengshiwen** [comment]
@zhaorongsheng Hi, let you wait for a long time.
In the next 1.3.5-release, we adjust k8s deployment (this deployment is not the official **Controller** `**Deployment**`: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/):
- Remove `frontend`
- Support resource storage for `file:///`
- Fix task log disappear after recreating or upgrading helm release from #3298
  - Fixing this bug requires a stable and unique network identifiers
  - Only **StatefulSets** meets the requirements from [Official Document](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets)
- Improve K8s a lot

```
api: Deployment
alert: Deployment
master: StatefulSet (contains logger)
worker: StatefulSet
```

Conclusion: K8s deployment is supported, but the **Controller Deployment** for master and worker will not be considering.

In the next few days, we will close this pr, if you have no questions.

Thanks!

**Comment by CalvinKirs** [comment]
close by #4529

**Comment by zhaorongsheng** [comment]
> @zhaorongsheng Hi, let you wait for a long time.
> In the next 1.3.5-release, we adjust k8s deployment (this deployment is not the official **Controller** `**Deployment**`: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/):
> 
> * Remove `frontend`
> * Support resource storage for `file:///`
> * Fix task log disappear after recreating or upgrading helm release from #3298
>   
>   * Fixing this bug requires a stable and unique network identifiers
>   * Only **StatefulSets** meets the requirements from [Official Document](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets)
> * Improve K8s a lot
> 
> ```
> api: Deployment
> alert: Deployment
> master: StatefulSet (contains logger)
> worker: StatefulSet
> ```
> 
> Conclusion: K8s deployment is supported, but the **Controller Deployment** for master and worker will not be considering.
> 
> In the next few days, we will close this pr, if you have no questions.
> 
> Thanks!

tks, we will try it later.
