### ISSUE TITLE
After the stand-alone deployment successful, the web page cannot run normally (单机部署成功后，web页面无法正常运作)

### ISSUE THREAD

**Issue by jinzhanqi** [apache/incubator-dolphinscheduler#4420]
单机部署后，workerserver，alertserver，apiapplicationserver，masterserver，loggerServer正常运行，局域网访问web页面无法正常运作。

**Comment by dailidong** [comment]
please show the page？did you check API server runtime log？

By the way, please add/update title and desc in English, thx

**Comment by jinzhanqi** [comment]
sorry, it has been resolved after reinstalled zookeeper.Thank you for your reply.

**Comment by dailidong** [comment]
ok, close this issue
