### ISSUE TITLE
[Improvement][Document] low version of Mysql jdbc driver may cause serious problem

### ISSUE THREAD

**Issue by ntupapaya** [apache/incubator-dolphinscheduler#4421]
**Describe the question**
Some low version of Mysql jdbc driver may cause serious problem. In my case 5.1.12 breaks the fundamental function of quartz and causes scheduler not working, though 5.1.47+ should promise work.  
For better searhing for this issue, basically quartz will throw an exception sth like syntax error around 'OPTION SQL_SELECT_LIMIT=1'   ....
After I changed to mysql driver 5.1.47, the error is gone. 

**What are the current deficiencies and the benefits of improvement**
- A clearer requirement on mysql jdbc driver version in document (like 5.1.47+) would save people from hitting such annoying serious problem.

**Which version of DolphinScheduler:**
1.3.4

**Describe alternatives you've considered**

**Comment by dailidong** [comment]
good suggestion

is there anybody could add some text on official github web : https://github.com/apache/incubator-dolphinscheduler-website

**Comment by Ylisen** [comment]
I want to add it

**Comment by CalvinKirs** [comment]
> I want to add it

Looking forward to your PR submission, please let me know when you are done and I will review it for you

**Comment by Ylisen** [comment]
> > I want to add it
> 
> Looking forward to your PR submission, please let me know when you are done and I will review it for you

https://github.com/apache/incubator-dolphinscheduler-website/pull/281

**Comment by CalvinKirs** [comment]
close by https://github.com/apache/incubator-dolphinscheduler-website/pull/281
