### ISSUE TITLE
A little idea and suggestion, hope to adopt!

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#4424]
Recommendation one: It is recommended to add an owner to the data source in the data source center so that it is easy to manage
![image](https://user-images.githubusercontent.com/42087586/104261006-8f06b400-54bf-11eb-9ec4-4b2c92906cab.png)

  
Recommendation 2: Add a loop to the definition flow judgment. 
Recommendation 3: Support Parameter passing in dependent task flows, such as multiple task flows operating on the same temporary table
![image](https://user-images.githubusercontent.com/42087586/104261827-536ce980-54c1-11eb-80a8-63e9ef0d58b0.png)

**Comment by dailidong** [comment]
Recommendation one is easy to implement, is there anybody who want to implement it?

**Comment by dailidong** [comment]
Recommendation 2 :  the task self can set retry and retry time , Is it necessary to retry the upstream task ?

**Comment by dailidong** [comment]
Recommendation 3: please referer:  https://github.com/apache/incubator-dolphinscheduler/issues/3805

**Comment by dailidong** [comment]
> Recommendation one is easy to implement, is there anybody who want to implement it?

Please re-submit a new issue for Recommendation one, then I will lable it "easy to implement" for first-time contributor

**Comment by shiliquan** [comment]
@dailidong On the first proposal, in addition to the data source center and Resource Center, if possible, it is better to add associated users, if possible, this I can make a single!
For recommendation # 2, here's what I need:
![image](https://user-images.githubusercontent.com/42087586/104287887-0fdea380-54f2-11eb-8545-194f258468a1.png)
![image](https://user-images.githubusercontent.com/42087586/104287967-284ebe00-54f2-11eb-8506-a73bc5ae3f88.png)

**Comment by dailidong** [comment]
> Recommendation one is easy to implement, is there anybody who want to implement it?

anybody who want to implement it, please leave a message, https://github.com/apache/incubator-dolphinscheduler/issues/4428

**Comment by dailidong** [comment]
> @dailidong On the first proposal, in addition to the data source center and Resource Center, if possible, it is better to add associated users, if possible, this I can make a single!
> For recommendation # 2, here's what I need:
> ![image](https://user-images.githubusercontent.com/42087586/104287887-0fdea380-54f2-11eb-8545-194f258468a1.png)
> ![image](https://user-images.githubusercontent.com/42087586/104287967-284ebe00-54f2-11eb-8506-a73bc5ae3f88.png)

does this idea could solve your issue? #3805  

by the way, please contact me(wechat:510570367 or mail: lidongdai@apache.org)

**Comment by dailidong** [comment]
is there still any suggestion?

**Comment by dailidong** [comment]
good suggestions.
I will close this issue.  if you have any more suggestions , please submit an new issue, one issue for one topic is much better, thx
