### ISSUE TITLE
It is recommended to add an owner in the data source center and the Resource Center to make it easier to manage

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#4428]
It is recommended to add an owner in the data source center and the Resource Center to make it easier to manage
![image](https://user-images.githubusercontent.com/42087586/104288645-0ace2400-54f3-11eb-9466-04cb435d5fd0.png)
![image](https://user-images.githubusercontent.com/42087586/104288766-3224f100-54f3-11eb-9a9f-82d082a45670.png)

**Comment by dailidong** [comment]
it’s easy to implement, is there anybody who want to implement it?

**Comment by qiubo369** [comment]
I can do it.

**Comment by shiliquan** [comment]
By the way, add an affiliate item to the workflow definition, or replace it directly
![image](https://user-images.githubusercontent.com/42087586/104414783-c81c5280-55ab-11eb-868c-3f14fbfe20a1.png)

**Comment by qiubo369** [comment]
@shiliquan This is not a good idea . per workflow definition has his owner project.
