### ISSUE TITLE
kerberos过期

### ISSUE THREAD

**Issue by zongqiren** [apache/incubator-dolphinscheduler#4429]
团队使用dolphinscheduler 调度spark2任务，因为集群的环境是开启了kerberos环境的，spark任务调度一段时间后会无法执行，在worker日志中发现是认证过期的问题，试过重启dolphinscheduler 就可以恢复正常执行，一直重启也不是解决办法，想问一下有什么办法可以解决吗？

**Comment by lenboo** [comment]
@zongqiren 
please change the title and content to english. then you can reopen it.

**Comment by shiliquan** [comment]
@ Zongqiren I have the same problem as you, this only happens if you refer to the Resource Center file, look at your KRB 5 quote. Update and the ticket settings in the conf file, make some adjustments, and then restart!

**Comment by zongqiren** [comment]
I've revised it common.properties , put kerberos.expire.time Parameter modification, restart, can unlimited modification is very big, because to find a way to solve the problem of expiration, always can't old restart to solve
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 晚上6:11
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"470096567"<470096567@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] kerberos过期 (#4429)





 
@ Zongqiren I have the same problem as you, this only happens if you refer to the Resource Center file, look at your KRB 5 quote. Update and the ticket settings in the conf file, make some adjustments, and then restart!
