### ISSUE TITLE
[Bug][Api] Cors inteceptor problems

### ISSUE THREAD

**Issue by dddyszy** [apache/incubator-dolphinscheduler#4439]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
When api-server and front-end services are deployed separately, some interfaces will report cross-domain issues

**To Reproduce**
Steps to reproduce the behavior, for example:
1. upload files
2. Log in to the same account on two different machines, then log out of one machine account

**Expected behavior**
The interface returns normally

**Screenshots**
![image](https://user-images.githubusercontent.com/20266837/104439917-a8495680-55cc-11eb-8d43-99b80ac3f82e.png)
![image](https://user-images.githubusercontent.com/20266837/104439944-b4cdaf00-55cc-11eb-87c5-b9a52360215c.png)
![image](https://user-images.githubusercontent.com/20266837/104440071-dcbd1280-55cc-11eb-9dd7-dba5002bd36b.png)
![image](https://user-images.githubusercontent.com/20266837/104440097-e47cb700-55cc-11eb-9201-ff7736d8abc3.png)

**Which version of Dolphin Scheduler:**
 -[1.3.4]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@dddyszy Let me check it and fix it if there is a problem.

**Comment by chengshiwen** [comment]
@dddyszy How did you deploy DS? It seems that `http://dolphinscheduler.paas.internal.mob.com` proxy passes the ui and `http://api.dolphinscheduler.paas.internal.mob.com` proxy passes the api. In the release 1.3.4, you can just access ui and api together in one domain.
