### ISSUE TITLE
The HSQL statement executed by the sql task node has a permission vulnerability

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#4446]
When Kerberos authentication is enabled and different tenants use the same sql task node to execute hsql statements, the DS calls the same DS component authentication ticket by default, if different tenants are using this sql to run HSQL, then there is no way to tell the difference. The users who submit tasks should be the ticket for the DS component. For example: I have two tenants, one of which has access to hive, a just need to use the basic shell running script, then for the DS basic note I am authorized or not authorized access to the HIVE, authorized to use the hive permission, yes, can be used, but if a user who doesn't have the rights to hive finds that he or she can still use the hsql feature of hive, he or she may not be able to control his or her risk. I think there's a loophole, don't you?
![image](https://user-images.githubusercontent.com/42087586/104538508-f7d46480-5656-11eb-886c-7f0825f138f1.png)

**Comment by zhuangchong** [comment]
#4450

**Comment by dailidong** [comment]
> #4450
> 
> Hive/Spark JDBC supports manual configuration of keytab parameters when using Kerberos authentication, and supports multi-tenancy when using Kerberos authentication for Hive/Spark data sources.

@shiliquan , good job,  and issue of #4450 also solve this problem, so I will close this issue
