### ISSUE TITLE
[Bug] After logging in to DolphinScheduler, open a new tab page, the new tab page also needs to log in again

### ISSUE THREAD

**Issue by gaoyu2016** [apache/incubator-dolphinscheduler#4447]
After logging in to DolphinScheduler, open a new tab page, the new tab page also needs to log in again

**Comment by gaoyu2016** [comment]
登录DolphinScheduler后打开一个新的标签页，新的标签页还需要再次登录.

**Comment by zhuangchong** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/4162
