### ISSUE TITLE
[Bug][api-server] Update workflow instance to report null point exception

### ISSUE THREAD

**Issue by Hxssssss** [apache/incubator-dolphinscheduler#4449]
If the workflow definition is created without adding global parameters, updating the workflow instance will report null pointer exception

创建工作流定义不添加全局参数的话,更新工作流实例会报空指针异常.

**Comment by zhuangchong** [comment]
Which version？

**Comment by Hxssssss** [comment]
> Which version？
I found it in 1.3.3, and later went to 1.3.4 branch. This bug was not fixed.
我在1.3.3发现的,后来去1.3.4分支这个bug也是没有修复的.

**Comment by zhuangchong** [comment]
Paste the context of the error message.

**Comment by Hxssssss** [comment]
> Paste the context of the error message.

I've located the problem and fixed it

![image](https://user-images.githubusercontent.com/25795286/104568402-050b4680-568b-11eb-9dc9-77e50b3ea23d.png)

**Comment by zhuangchong** [comment]
@Hxssssss 

You are most welcome to submit a PR.
