### ISSUE TITLE
[Feature][UI] add an option to the UI page for saving the workflow definition: whether to go online? online by default

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#4463]
Are there any intentions to implement the front-end https://github.com/apache/incubator-dolphinscheduler/issues/4451? 
The requirement is to add an option to the UI page for saving the workflow definition: whether to go online? online by default

---

有没有伙伴愿意实现一下 https://github.com/apache/incubator-dolphinscheduler/issues/4451 这个的前端呐？
需求是保存工作流定义的页面加个选项：是否上线？默认选中上线

![image](https://user-images.githubusercontent.com/15833811/104675529-aabcc500-5720-11eb-8404-4c5c5408ba6e.png)

![image](https://user-images.githubusercontent.com/15833811/104675075-b5c32580-571f-11eb-8b81-aa871eb6020d.png)

**Comment by linyanbin666** [comment]
I want to add it.

**Comment by linyanbin666** [comment]
@dailidong hi, I have submitted the pull request #4474, help to review please.
