### ISSUE TITLE
[Question] How to distinguish and identify the alarm content title of multiple sets of environmental e-mail

### ISSUE THREAD

**Issue by jetaime-chen** [apache/incubator-dolphinscheduler#4479]
Because there are multiple easyscheduler environments, the alarm e-mails sent by multiple easyschedulers can not be identified from the e-mail title, and the alarm content can only be identified from the host IP. Is there any place where the e-mail title can be configured or the e-mail content can be added to distinguish the environment.

Using easysscheduler 1.1.0 and dolphin scheduler 1.3.0.

**Comment by xingchun-chen** [comment]
At present, it is not supported to change the title of e-mail

**Comment by CalvinKirs** [comment]
hi, we will release alert-spi in version 1.4.0, but it will not support this function. You can modify the plug-in code to complete your needs at that time. This is very easy for you. The form of spi is also for consideration Various user needs.
