### ISSUE TITLE
The master/worker node is not distinguished. The master can be used as a worker for a single node, and the worker can also be used as a master. Otherwise, the actual operation and maintenance cost will be high.（master/worker节点不区分，单节点时master可作为worker使用，worker 也可以做为master ，不然实际生产上运维成本会很高）

### ISSUE THREAD

**Issue by mnloveyx** [apache/incubator-dolphinscheduler#448]
The master/worker node is not distinguished. The master can be used as a worker for a single node, and the worker can also be used as a master. Otherwise, the actual operation and maintenance cost will be high.

---
master/worker节点不区分，单节点时master可作为worker使用，worker 也可以做为master ，不然实际生产上运维成本会很高

**Comment by lidongdai** [comment]
There is no such implementation in distributed systems. Separation of duties is required for a large system. As you say, the maintenance cost will be higher once the amount of tasks is up.
---
分布式系统还没有这种实现的，职责分离是一个大型系统所需要的，如您所说，比较担心的是这种方式一旦任务量上来的话，维护成本会更高

**Comment by mnloveyx** [comment]
一但量上来，可以多启动几个节点，因为众生平等，只有一个master 存活其它都是worker ，

**Comment by lidongdai** [comment]
Do others have suggestions?

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
