### ISSUE TITLE
[Improvement][API] change method checkAdmin to isNotAdmin

### ISSUE THREAD

**Issue by qmengss** [apache/incubator-dolphinscheduler#4480]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
the method 'checkAdmin' in class 'BaseService' is to check user whether admin or not .
the comment of the method is 'true if administrator, otherwise false' , but the code logic means 'true if not administrator, otherwise false' , the comment and the code logic is not matching , change the method name and the comment helps to understand the function means.
  
![image](https://user-images.githubusercontent.com/9145185/104883502-d26d9080-599f-11eb-9fa5-c66e384c0040.png)

**What are the current deficiencies and the benefits of improvement**

- It can make developers better understand the method

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
change the method name from 'checkAdmin' to 'isNotAdmin' , also modify the usage.

**Comment by zhuangchong** [comment]
LGTM.

**Comment by CalvinKirs** [comment]
close by #4483
