### ISSUE TITLE
[Feature][dolphinscheduler-api] ProcessDefinitionController save API returns ProcessDefinitionId

### ISSUE THREAD

**Issue by z7658329** [apache/incubator-dolphinscheduler#4481]
current ProcessDefinitionController   save API didn't returns a new ProcessDefinition's ID,if use API to create ProcessDefinition ,the default release_state is  0(off_line) and no   ProcessDefinitionId returns, so if i want this ProcessDefinition online, i must call query Api to get the ProcessDefinition,then  call  release API to make the ProcessDefinition  online

**Comment by z7658329** [comment]
i have fork the git and fix the bug,lets contact in WeChat

**Comment by zhuangchong** [comment]
I found that the dev branch has fixed your requirement,It returns processdefinitionid after the workflow definition is saved successfully.

**Comment by z7658329** [comment]
> I found that the dev branch has fixed your requirement,It returns processdefinitionid after the workflow definition is saved successfully.

i see,
![image](https://user-images.githubusercontent.com/5474723/104886647-0d25f780-59a5-11eb-8a0a-c860350d45d3.png)

but is the implementation suitable? why not only return processDefineId? and  if so,why should query DB?and  if return the processDefine Entity,will Impact on Performance？
