### ISSUE TITLE
[Question] tenantCode: administrator does not exist

### ISSUE THREAD

**Issue by bingfeng2004** [apache/incubator-dolphinscheduler#4486]
I am debug in windows,but it's run failed.
TASK LOG DETAIL:

[INFO] 2021-01-18 22:28:17.805  - [taskAppId=TASK-2-19-21]:[121] - create dir success /tmp/dolphinscheduler/exec/process/1/2/19/21
[ERROR] 2021-01-18 22:28:18.014  - [taskAppId=TASK-2-19-21]:[119] - **tenantCode: administrator does not exist**

QUESTION:
How to configure tenantCode in Windows?

**Comment by xingchun-chen** [comment]
1.create tenant
![image](https://user-images.githubusercontent.com/55787491/105001374-a23ef400-5a6a-11eb-8483-aea7cc1dff1e.png)
2.User associated tenant
![image](https://user-images.githubusercontent.com/55787491/105001486-cbf81b00-5a6a-11eb-8c83-8bfc8109eed2.png)
