### ISSUE TITLE
[Improvement][Module Name] Improvement title

### ISSUE THREAD

**Issue by liweigu** [apache/incubator-dolphinscheduler#4488]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
The version in the pom.xml is wrong as "<version>1.3.5-SNAPSHOT</version>", which should be 1.3.4, see
https://github.com/apache/incubator-dolphinscheduler/blob/1.3.4-release/pom.xml or other pom.xml under each project.

**What are the current deficiencies and the benefits of improvement**
As the version is wrong, when building docker image and setting VERSION=1.3.4, the maven compiled jar is still named as 1.3.5-SNAPSHOT (which should be 1.3.4), causing error at "ADD ./apache-dolphinscheduler-incubating-${VERSION}-dolphinscheduler-bin.tar.gz /opt/" in the Dockerfile and preventing docker image building.

**Which version of DolphinScheduler:**
 -1.3.4-release

**Describe alternatives you've considered**
I suggest setting version's value corresponding to the branch's version like 1.3.4 (or 1.3.5), it should be fine to rectify this issue on the next release '1.3.5-release'.

**Comment by BoYiZhang** [comment]
Please download through 1.3.4 tag

![image](https://user-images.githubusercontent.com/39816903/105000663-8d159580-5a69-11eb-9f06-db2e86ab2460.png)

**Comment by liweigu** [comment]
I got it.
