### ISSUE TITLE
删除工作流定义报错

### ISSUE THREAD

**Issue by coingpaic** [apache/incubator-dolphinscheduler#4489]
各位大神好：

1.3.4-SNAPSHOT版本部署后,删除工作流定义报org.apache.ibatis.binding.BindingException:Invalid bound statement(not found): org.apache.dolphinscheduler.dao.mapper.ProcessInstanceMapper.queryByProcessDefineIdAndStatus；
新建工作流也会报类似的错误。

thanks

**Comment by z7658329** [comment]
贴一下详细堆栈？

**Comment by coingpaic** [comment]
> 贴一下详细堆栈？

堆栈信息在内网，不方便拿。我先直接取1.3.4版本看有没有问题吧。多谢！

**Comment by z7658329** [comment]
> > 贴一下详细堆栈？
> 
> 堆栈信息在内网，不方便拿。我先直接取1.3.4版本看有没有问题吧。多谢！

或者你去Tag里找一个稳定版本测试吧，不太建议拿snapshot版本来测试
