### ISSUE TITLE
[Question]connect oracle error 

### ISSUE THREAD

**Issue by githubzhulf** [apache/incubator-dolphinscheduler#4492]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.
![image](https://user-images.githubusercontent.com/23021463/105017675-0370c280-5a7f-11eb-9123-feb01459d00d.png)

**Comment by githubzhulf** [comment]
![Uploading image.png…]()

**Comment by zhuangchong** [comment]
the OJDBC jar is placed in the Dolphin installation directory lib folder, restart the dolphin api-server and worker-server.

**Comment by githubzhulf** [comment]
What is the version of OJDBC

**Comment by zhuangchong** [comment]
> What is the version of OJDBC

![image](https://user-images.githubusercontent.com/37063904/105019047-a0802b00-5a80-11eb-86c9-584daac4e26e.png)

**Comment by githubzhulf** [comment]
cannot open the picture

**Comment by CalvinKirs** [comment]
> cannot open the picture

oracle jdbc driver

**Comment by chengshiwen** [comment]
Close this question since it has been replied

**Comment by tangzhf** [comment]
where is the folder of driver??

**Comment by zhuangchong** [comment]
> where is the folder of driver??

the OJDBC jar is placed in the Dolphin installation directory lib folder, restart the dolphin api-server and worker-server.

**Comment by chengshiwen** [comment]
> where is the folder of driver??

`$DOLPHINSCHEDULER_HOME/lib` like `/opt/dolphinscheduler/lib`

**Comment by tangzhf** [comment]
I find it,It's works.  Thanks all.
