### ISSUE TITLE
[Improvement][ui] content compact when authorizing resources

### ISSUE THREAD

**Issue by arvin0810** [apache/incubator-dolphinscheduler#4504]
*low priority *

**Describe the question**
When authorizing resource to some user, if there are a lot of files within a folder, it's VERY hard to select other folders and the OK/CANCEL button are not reachable as well.

screenshot:
![image](https://user-images.githubusercontent.com/41656463/105122555-657a0800-5b11-11eb-9de5-f7167d921a2c.png)

**Which version of DolphinScheduler:**
 -[1.3.4]

**Describe alternatives you've considered**
Use transfer box instead.

**Comment by CalvinKirs** [comment]
close by #4504
