### ISSUE TITLE
[Feature][Tenant]Support users to choose whether to turn off multi-tenancy function

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#4515]
**Describe the feature**

Support users to choose whether to turn off multi-tenancy function, mainly to solve the problem of 1. Some users do not need multi-tenancy in real scenarios, and use one user to perform tasks; 2. Some users cannot apply for sudo permission

---
支持用户选择是否关闭多租户功能,主要是为解决1.部分用户真实场景不需要多租户，使用一个用户执行任务；2.部分用户申请不到sudo权限

**todo list**

- [ ]  Supports turning off multi-tenancy function. The page cannot select tenant related function, and the tenant code is default

- [x]  #4128 Complete the code sudo usage specification. All script tasks execute commands using sudo-u username command

**Comment by davidzollo** [comment]
excellect, I just add this feature in milestone 1.4.0 , I hope you can finish it soon

**Comment by CalvinKirs** [comment]
close by #4217 #5129
