### ISSUE TITLE
Database, zk and other operational recommendations plus retry mechanism, data deletion data is recommended to be marked as invalid state（数据库，zk等操作建议加上重试机制，数据删除数据建议改成标记为失效状态）

### ISSUE THREAD

**Issue by sunnyingit** [apache/incubator-dolphinscheduler#452]
In the es code, it is recommended to add a retry mechanism to the database, zk and other operational recommendations to maximize the stability of the operation, data deletion data is recommended to be marked as invalid state, easy to query related issues

---
在es代码中，建议给数据库，zk等操作建议加上重试机制，最大限度保证操作的稳定性，数据删除数据建议改成标记为失效状态，便于查询相关问题

**Comment by chengshiwen** [comment]
Close this issue since the retry mechanism has introduced in latest version
