### ISSUE TITLE
[Bug][WorkerServer] worker server doesn't work fine in K8s

### ISSUE THREAD

**Issue by crazycarry** [apache/incubator-dolphinscheduler#4526]
i  run a worker server in k8s,not change the worker server parms,sometime i run into the error in the picture,dispath do not find a suiteable worker to do the task.
<img width="964" alt="截屏2021-01-20 下午8 44 42" src="https://user-images.githubusercontent.com/3957251/105436336-ff6cbc80-5c99-11eb-993c-ac13193efd96.png">

**Comment by crazycarry** [comment]
what cause my problem is the worker max-cpuload is -1，that stand for 2* cpucores。 and my pod resource is 2cores，and the hosts load is between 3.7-4.3，so，sometime the worker server can be recognized load too high to receive task. in fact,it get the hosts load where the pod in.

**Comment by ralphgj** [comment]
Hi，I have also encountered this issue. Can we use `com.sun.management.OperatingSystemMXBean#getProcessCpuLoad` method instead of `java.lang.management.OperatingSystemMXBean#getSystemLoadAverage` to calculate the cpu load?
