### ISSUE TITLE
[doc]Some suggestions on documentation

### ISSUE THREAD

**Issue by 17161899817** [apache/incubator-dolphinscheduler#4528]
在单机上部署的时候，资源中心的文档部分写的再详细点

**Comment by CalvinKirs** [comment]
For better communication, please use English. Thx.

**Comment by dailidong** [comment]
which part？

**Comment by CalvinKirs** [comment]
Regarding the documentation, which part of the documentation you think is needed, or which documentation is not complete, you can reply here ISSUE. Your suggestions are welcome
