### ISSUE TITLE
[Bug][Doc] correct the wrong visit url 

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#4547]
**Describe the bug**
there is a bug on the official website, github repository: https://github.com/apache/incubator-dolphinscheduler-website

http://localhost:8888 is wrong, the right url is:  http://localhost:12345/dolphinscheduler

![image](https://user-images.githubusercontent.com/15833811/105632793-17a62c80-5e90-11eb-8fa8-f1274baddf64.png)

the related code please see the following picture:
![image](https://user-images.githubusercontent.com/15833811/105632917-b2067000-5e90-11eb-8a74-7c8d75ca7570.png)

**Comment by ThusithaDJ** [comment]
Hi, dailidong! I would like to resolve this bug, please assign it to me!

**Comment by CalvinKirs** [comment]
> Hi, @dailidong ! I would like to resolve this bug, please assign it to me!

Very welcome, looking forward to your PR submission

**Comment by zt-1997** [comment]
The port 12345 can't be accessed. 8888 works well. Why change it?

**Comment by zt-1997** [comment]
If the developer builds the environment, it cannot be accessed in the browser. Isn't that dizzy? It can be noted that 12345 is API service and 8888 is browser UI service.

**Comment by ThusithaDJ** [comment]
FYI:
While I'm cloning the repo, I got this error. 
![image](https://user-images.githubusercontent.com/20126399/105694416-f47a8c00-5f26-11eb-9e9d-246462fa4bd1.png)

Not sure whether this is an issue or not. But I was able to resolve this with `git config --global core.protectNTFS false` command. I'm using a Windows PC, by the way.

**Comment by ThusithaDJ** [comment]
Hi @CalvinKirs, is this bug only for the `en-us/development-environment-setup.md` file or both **_en-us_** and **_zh-cn_** versions?

**Comment by dailidong** [comment]
> Hi @CalvinKirs, is this bug only for the `en-us/development-environment-setup.md` file or both **_en-us_** and **_zh-cn_** versions?

you can update English version, but also welcome to update the chinese version if you can finish it.

**Comment by ThusithaDJ** [comment]
>you can update English version, but also welcome to update the chinese version if you can finish it.
Yes, I can do the relevant changes.

**Comment by ThusithaDJ** [comment]
Hi @dailidong, I have pushed the changes, could you please check and let me know your input on this.
https://github.com/apache/incubator-dolphinscheduler-website/pull/285

**Comment by dailidong** [comment]
> Hi @dailidong, I have pushed the changes, could you please check and let me know your input on this.
> [apache/incubator-dolphinscheduler-website#285](https://github.com/apache/incubator-dolphinscheduler-website/pull/285)

good job, I have merged this PR

thanks for your first contribution, looking forward to your deep participation.

for better instant communication, the slack workspace URL: http://asf-dolphinscheduler.slack.com/

please join our slack workspace through url: https://join.slack.com/t/asf-dolphinscheduler/shared_invite/zt-l8k90ceu-wwUfobaDkJxjzMfZp4y1Ag , this url expires after 30 days.

in one word , welcome to join Apache DolphinScheduler Community
