### ISSUE TITLE
 The log information is suggested to be omitted. . .（log信息建议省略一下。。。）

### ISSUE THREAD

**Issue by ronyang1985** [apache/incubator-dolphinscheduler#455]
https://github.com/analysys/EasyScheduler/blob/8eefa0e947ad8052485901801665833dabe17de0/escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java#L281

**Comment by lidongdai** [comment]
good idea, thx!

and if don't want to see too many log info , can set log level to warn or error !

**Comment by dailidong** [comment]
Duplicate of https://github.com/apache/incubator-dolphinscheduler/issues/226
