### ISSUE TITLE
[Question] How to use resources in process script

### ISSUE THREAD

**Issue by ruancheng77** [apache/incubator-dolphinscheduler#4553]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
![image](https://user-images.githubusercontent.com/55787491/105940527-7dfc9c00-6096-11eb-8b66-4d796955ebc3.png)

**Comment by ruancheng77** [comment]
I can't see your image!

**Comment by xingchun-chen** [comment]
In the shell script, use sh test.sh

**Comment by ruancheng77** [comment]
Can you give a simple demo?
Upload a resource file and create a process script to use it.

**Comment by xingchun-chen** [comment]
https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/system-manual.html  You can refer to user manual 3.2 resource upload and 2.3.1 shell parameter settings

**Comment by chengshiwen** [comment]
Close this question since it has been replied
