### ISSUE TITLE
Kettle mission（Kettle任务）

### ISSUE THREAD

**Issue by lzy305** [apache/incubator-dolphinscheduler#456]
Can be defined in the process definition. Add a task type (similar to shell, sql). Support JAVA to call kettle's job, transform.
Because it is found to be called with the shell /opt/data-integration/pan.sh -file='TEST_JNDI.ktr' -param:JNDI_NAME='oracle_dw' -level=Error will cause the CPU to suddenly increase. If you use java api instead.

---
可否 在流程定义详情. 增加一个任务类型(类似 shell, sql) . 支持JAVA调用kettle的job,transform。
因为发现用 用shell 调用的话 /opt/data-integration/pan.sh -file='TEST_JNDI.ktr' -param:JNDI_NAME='oracle_dw' -level=Error  会造成cpu突增.  而改用java api的话 .

**Comment by lidongdai** [comment]
good idea!  thx!
anybody  who like this feature please reply !

**Comment by lianjie1229** [comment]
+1

**Comment by gogo649** [comment]
+1！！

**Comment by Mryst** [comment]
How is the problem now

**Comment by zhangb0120** [comment]
这个任务怎么样了？

**Comment by lzy305** [comment]
@zhangb0120  
i find that this feature is in develop. https://github.com/apache/incubator-dolphinscheduler/issues/2032

**Comment by dailidong** [comment]
the same issue with #2032

**Comment by dailidong** [comment]
the develop progress please see #2032
