### ISSUE TITLE
[Question] Generate workflows using Excel

### ISSUE THREAD

**Issue by SuperHeroBigData** [apache/incubator-dolphinscheduler#4560]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the question**
Use Excel parsing to generate Work Flow and complete the creation of DS workflow.do you have the case how to make workflow?

**Which version of DolphinScheduler:**
1.3.4

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by xingchun-chen** [comment]
At present, there are people who use JSON, but have not used Excel

**Comment by chengshiwen** [comment]
Close this issue since the issue has been replied
