### ISSUE TITLE
[Improvement][API] When the workflow definition name validation API fails, the system prompts that the workflow definition name already exists

### ISSUE THREAD

**Issue by zhuangchong** [apache/incubator-dolphinscheduler#4568]
**Describe the question**
When the workflow definition name validation API fails, the system prompts that the workflow definition name already exists,
the system normally prompts workflow definition name validation error

**Which version of DolphinScheduler:**
 -[1.3.4-release,dev]

**Comment by xingchun-chen** [comment]
I think "workflow name already exists" is clearer, and I don't know where the error is when I prompt "workflow name verification error"

**Comment by zhuangchong** [comment]
> I think "workflow name already exists" is clearer, and I don't know where the error is when I prompt "workflow name verification error"

I didn't express myself clearly. I'm going to change it this way

VERIFY_PROCESS_DEFINITION_NAME_UNIQUE_ERROR state is used for prompt verifyProcessDefinitionName method throws an exception

```
@ApiException(VERIFY_PROCESS_DEFINITION_NAME_UNIQUE_ERROR)
    public Result verifyProcessDefinitionName(@ApiIgnore @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
                                              @ApiParam(name = "projectName", value = "PROJECT_NAME", required = true) @PathVariable String projectName,
                                              @RequestParam(value = "name", required = true) String name) {
        logger.info("verify process definition name unique, user:{}, project name:{}, process definition name:{}",
            loginUser.getUserName(), projectName, name);
        Map<String, Object> result = processDefinitionService.verifyProcessDefinitionName(loginUser, projectName, name);
        return returnDataList(result);
    }

```

PROCESS_DEFINITION_NAME_EXIST state is the prompt used to verify the existence of the workflow definition name

```
ProcessDefinition processDefinition = processDefineMapper.verifyByDefineName(project.getId(), name);
        if (processDefinition == null) {
            putMsg(result, Status.SUCCESS);
        } else {
            putMsg(result, Status.PROCESS_DEFINITION_NAME_EXIST, name);
        }

 ```

I think the VERIFY_PROCESS_DEFINITION_NAME_UNIQUE_ERROR and PROCESS_DEFINITION_NAME_EXIST states are both required.

**Comment by xingchun-chen** [comment]
ok, it's good

**Comment by zhuangchong** [comment]
> ok, it's good

help review PR
