### ISSUE TITLE
[Bug][Resource] After uploading a shell script file, only one node exists the file.

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4577]
**Describe the bug**
After uploading a shell script file, only one node exists the file.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Upload a shell script file on a DS Cluster which include two nodes.
2. Only one node exists the file.

**Which version of Dolphin Scheduler:**
 -[1.3.4-release]

**Comment by xingchun-chen** [comment]
I don't know what you mean. Can you take a screenshot

**Comment by chengshiwen** [comment]
Close this issue since it can't be reproduced due to no updates for long time
