### ISSUE TITLE
[Improvement][api] It takes 5 seconds to visit zookeeper page and needs to be optimized

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4591]
![image](https://user-images.githubusercontent.com/55787491/105974762-30e5ed80-60c9-11eb-98e3-fa6d13fa9163.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by xingchun-chen** [comment]
who can fix it?

**Comment by felix-thinkingdata** [comment]
1

**Comment by felix-thinkingdata** [comment]
> who can fix it?

Environmental problems, I don't see a recurrence in my environment

![image](https://user-images.githubusercontent.com/59079269/106113220-2ee36380-6189-11eb-80e3-02f2c3a49feb.png)
