### ISSUE TITLE
[Improvement][api] Worker group data returned incorrectly

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#4592]
![image](https://user-images.githubusercontent.com/55787491/105975589-16604400-60ca-11eb-91b8-83fd8568673e.png)
![image](https://user-images.githubusercontent.com/55787491/105975823-6212ed80-60ca-11eb-91a5-772c93a899bb.png)

**Which version of DolphinScheduler:**
 -[dev]

**Comment by xingchun-chen** [comment]
who can fix it?

**Comment by zt-1997** [comment]
i will fix it
