### ISSUE TITLE
[Feature][doc] Optimization tips[ common.properties ]

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#4596]
Ambiguities exist in environment variables, which easily mislead users

common.properties Parameters in configuration file dolphinscheduler.env.path Ambiguities exist in environment variables, which easily mislead users

```
# system env path
#dolphinscheduler.env.path=env/dolphinscheduler_env.sh

```
If the comment is opened without modifying the following path information, an error will be reported when executing the task

![image](https://user-images.githubusercontent.com/39816903/106087766-a3091180-615f-11eb-9161-deb0cf32c8ba.png)

reason:

In the code, the dolphinscheduler.env.path To load an environment variable, the environment variable must be an absolute path

Default "env/dolphinscheduler_env.sh"  Is the relative path, the execution of shell type tasks will directly report an error

Suggestions, improve the configuration prompt information

----

common.properties配置文件中参数 dolphinscheduler.env.path  环境变量存在歧义, 容易误导用户.
```
# system env path
#dolphinscheduler.env.path=env/dolphinscheduler_env.sh

```
如果将注释打开, 而不修改后面的路径信息, 执行任务的时候会报错.

![image](https://user-images.githubusercontent.com/39816903/106087766-a3091180-615f-11eb-9161-deb0cf32c8ba.png)

原因:
代码中会根据dolphinscheduler.env.path的配置, 去加载环境变量, 这个环境变量必须为绝对路径.
默认的env/dolphinscheduler_env.sh是相对路径, 执行shell类型的任务会直接报错.

建议, 完善配置提示信息.

**Comment by enoughwell** [comment]
I will fix it.Please assign it to me!
