### ISSUE TITLE
 java.io.IOException: Server is not trusted: mail.onething.net

### ISSUE THREAD

**Issue by Yanwenjingcn** [apache/incubator-dolphinscheduler#4610]
this is my alert config,but we can not send email

# mail server configuration
mail.protocol=SMTP
mail.server.host=mail.xxx.net
mail.server.port=xxxx
mail.sender=xxxxx
mail.user=xxxxx
mail.passwd=xxxx
# TLS
mail.smtp.starttls.enable=true
# SSL
mail.smtp.ssl.enable=false
mail.smtp.ssl.trust=mai.xxx.net

![image](https://user-images.githubusercontent.com/16257260/106137885-5694f480-61a6-11eb-9a44-d62735bbc9d4.png)

**Comment by CalvinKirs** [comment]
could not convert socket to TLS....

**Comment by Yanwenjingcn** [comment]
> could not convert socket to TLS....

so how can i slove this problem?

**Comment by Yanwenjingcn** [comment]
> could not convert socket to TLS....

i fix it，

mail.smtp.starttls.enable=false
mail.smtp.ssl.enable=false
