### ISSUE TITLE
[Bug][LoggerServer] task log can not refresh in time

### ISSUE THREAD

**Issue by 597365581** [apache/incubator-dolphinscheduler#4617]
for example ，if 1s produce log size can not teet the default conditions --Constants.DEFAULT_LOG_ROWS_NUM（64）， and need to wait a long time。
![image](https://user-images.githubusercontent.com/62982788/106221832-4f5afe80-6219-11eb-947c-23f5ed2ec822.png)

**Comment by 597365581** [comment]
例如，如果 1s 内产生的日志量不能满足代码中默认的64条，并且后续又需要等很久才有新的日志产生。 就会导致 日志很久都无法被刷新。

**Comment by felix-thinkingdata** [comment]
> for example ，if 1s produce log size can not teet the default conditions --Constants.DEFAULT_LOG_ROWS_NUM（64）， and need to wait a long time。
> ![image](https://user-images.githubusercontent.com/62982788/106221832-4f5afe80-6219-11eb-947c-23f5ed2ec822.png)

This is where the content that has not been written to the log is uniformly disposed of after the task has completed.

**Comment by 597365581** [comment]
https://github.com/apache/incubator-dolphinscheduler/pull/4618

**Comment by 597365581** [comment]
> > for example ，if 1s produce log size can not teet the default conditions --Constants.DEFAULT_LOG_ROWS_NUM（64）， and need to wait a long time。
> > ![image](https://user-images.githubusercontent.com/62982788/106221832-4f5afe80-6219-11eb-947c-23f5ed2ec822.png)
> 
> ![image](https://user-images.githubusercontent.com/59079269/106276728-f28c3200-6272-11eb-88f9-04368bd449f4.png)
> 
> This is where the content that has not been written to the log is uniformly disposed of after the task has completed.
> 
> Probably because of efficiency

so，  if this task exec need long time， log can not write in time， inconvenient problem positioning。

**Comment by 597365581** [comment]
for example

#!/bin/bash
echo "hello world"
sleep 10m
echo "hello world2"
