### ISSUE TITLE
[Improvement][Server] When the server exist in the dead server list of zk,need stop service byself

### ISSUE THREAD

**Issue by lgcareer** [apache/incubator-dolphinscheduler#4624]
**Describe the question**
When the server exist in the dead server list of zk,need stop service byself

**What are the current deficiencies and the benefits of improvement**
- A clear and concise description of the current deficiencies and the benefits of this improvement.

**Which version of DolphinScheduler:**
 -[1.3.5]

**Comment by AlleriaWindrunner** [comment]
i want to resolve this issue, assignt it to me.

**Comment by davidzollo** [comment]
> i want to resolve this issue, assignt it to me.

good job,  looking forward to your PR
