### ISSUE TITLE
[Questionn]Edit the set workflow again or open the previously set node is missing

### ISSUE THREAD

**Issue by caodaoxi** [apache/incubator-dolphinscheduler#4667]
设置的工作流重新编辑或打开之前设置的节点不见了
1.添加工作流
![image](https://user-images.githubusercontent.com/4454208/106719427-41ecac80-663d-11eb-85ce-13218b14139d.png)
![image](https://user-images.githubusercontent.com/4454208/106719642-85471b00-663d-11eb-87e2-906e7a8f7c1d.png)
2. 查看工作流
![image](https://user-images.githubusercontent.com/4454208/106719985-e2db6780-663d-11eb-955f-c0da9edb1b04.png)
![image](https://user-images.githubusercontent.com/4454208/106719818-b0ca0580-663d-11eb-9bb8-87fbf4db19c2.png)
之前设置的工作流节点不见了，该问题出现在dev分支

**Comment by CalvinKirs** [comment]
please use english.THx

**Comment by chengshiwen** [comment]
@caodaoxi Please give more deails, such as DevTools Console opened by `F12` or `Option+Command+I`, DolphinScheduler version

**Comment by chengshiwen** [comment]
Close by #5095
