### ISSUE TITLE
[Question] There is no response data after successfully saved a DAG

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [apache/incubator-dolphinscheduler#4668]
While I'm creating a new dag by api(/dolphinscheduler/projects/{projectName}/process/save), I have found that in response data there is only null while the request was seccessfully send and achieved code 201 created like this:
![image](https://user-images.githubusercontent.com/58684828/106719196-f9cd8a00-663c-11eb-9fa9-21af21573c69.png)
In official documentations I have found several ways to send this request. But I chose the way which UI did to save the dag.
For example, shown below: even in UI(opened by chrome ) , nothing will return from the response so I cannot achieve the new dag id after creating it.
![image](https://user-images.githubusercontent.com/58684828/106719832-b4f62300-663d-11eb-81b0-5e7a801b1e93.png)
![image](https://user-images.githubusercontent.com/58684828/106719852-ba536d80-663d-11eb-8d2e-6591d5ab9507.png)
![image](https://user-images.githubusercontent.com/58684828/106719877-c3dcd580-663d-11eb-83e9-dd440e9134d5.png)

I have no idea how to get that dag id, I've tried form-data, x-www-form-urlencoded, json, and also put all the parameters in path 
just like which was shown in issue[#3604](https://github.com/apache/incubator-dolphinscheduler/issues/3604)
I have also checked the source code to see if there is something wrong with feature 1.3.4 release, but obviously there is a feedback dag id in response .
So why I cannot get the response data? Please give me some help.

BTW,In general cases, I used to do a remote debug by adding phrase
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6666 
into a java -jar xxxxx.jar command.
It seems not working this time when I tried to debug and see whats going on with that returning map.  I have no idea how to do a remote debug with idea in this situation. 

**Which version of DolphinScheduler:**
 -[1.3.4-release]

**Here is my full request infomation while testing**
 
POST /dolphinscheduler/projects/william_%E6%B5%8B%E8%AF%95%E9%A1%B9%E7%9B%AE/process/save HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 1b81de0d-76e9-41ab-a6f7-eb8d858df5e9
Host: 192.168.18.60:8081
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------891566125788075838224945
Cookie: sessionId=88f4754c-7d2d-4edc-87a5-30f048eb6b48; session=.eJw1zjkOAjEMAMC_pKZIbCdO9jPI8SEoWKE9KsTfQULMC-aVrrH5fkvLsZ1-Sde7pSVBKUqkEX0AKxYGpcqsIjNX5dDKQqAtC3XjYClVcsbSAA1rZMawTJ3ADF2BbEZgs25Vc-4OPBRHMA4gdHOVytGYrWFM6VPTN_L07SGrr8e_du6-_XolvT8bQTXN.YBJXfg.QkC3-LRxhl8Nw9inYeQo465CtBg
Content-Length: 3684
----------------------------891566125788075838224945
Content-Disposition: form-data; name="processDefinitionJson"

{"globalParams":[],"tasks":[{"type":"HTTP","id":"tasks-80161","name":"company","params":{"localParams":[],"httpParams":[{"prop":"taskCode","httpParametersType":"HEADERS","value":"company"},{"prop":"runId","httpParametersType":"HEADERS","value":"test_202102011037"},{"prop":"reqForm","httpParametersType":"BODY","value":"{\"company\":\"company\"}"}],"url":"http://192.168.18.60:18001/test/resource/testCompany","httpMethod":"POST","httpCheckCondition":"STATUS_CODE_DEFAULT","condition":""},"description":"","timeout":{"strategy":"","interval":null,"enable":false},"runFlag":"NORMAL","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{},"maxRetryTimes":"0","retryInterval":"1","taskInstancePriority":"MEDIUM","workerGroup":"default","preTasks":["6666666666"]},{"type":"HTTP","id":"tasks-8-7je7ma","name":"user","params":{"localParams":[],"httpParams":[{"prop":"taskCode","httpParametersType":"HEADERS","value":"user"},{"prop":"runId","httpParametersType":"HEADERS","value":"test_202102011037"},{"prop":"reqForm","httpParametersType":"BODY","value":"{\"user\":\"user\"}"}],"url":"http://192.168.18.60:18001/test/resource/testUser","httpMethod":"POST","httpCheckCondition":"STATUS_CODE_DEFAULT","condition":""},"description":"","timeout":{"strategy":"","interval":null,"enable":false},"runFlag":"NORMAL","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{},"maxRetryTimes":"01","retryInterval":"1","taskInstancePriority":"MEDIUM","workerGroup":"default","preTasks":["6666666666"]},{"type":"HTTP","id":"tasks-36265","name":"6666666666","params":{"localParams":[],"httpParams":[],"url":"123","httpMethod":"GET","httpCheckCondition":"STATUS_CODE_DEFAULT","condition":""},"description":"","timeout":{"strategy":"","interval":null,"enable":false},"runFlag":"NORMAL","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{},"maxRetryTimes":"0","retryInterval":"1","taskInstancePriority":"MEDIUM","workerGroup":"default","preTasks":[]},{"type":"HTTP","id":"tasks-92172","name":"测试节点","params":{"localParams":[],"httpParams":[],"url":"123123123123","httpMethod":"GET","httpCheckCondition":"STATUS_CODE_DEFAULT","condition":""},"description":"","timeout":{"strategy":"","interval":null,"enable":false},"runFlag":"NORMAL","conditionResult":{"successNode":[""],"failedNode":[""]},"dependence":{},"maxRetryTimes":"0","retryInterval":"1","taskInstancePriority":"MEDIUM","workerGroup":"default","preTasks":["6666666666"]}],"tenantId":2,"timeout":"12"}
----------------------------891566125788075838224945
Content-Disposition: form-data; name="locations"

{"tasks-80161":{"name":"company","targetarr":"tasks-36265","nodenumber":"0","x":454,"y":381},"tasks-8-7je7ma":{"name":"user","targetarr":"tasks-36265","nodenumber":"0","x":482,"y":200},"tasks-36265":{"name":"6666666666","targetarr":"","nodenumber":"3","x":125,"y":33},"tasks-92172":{"name":"测试节点","targetarr":"tasks-36265","nodenumber":"0","x":519,"y":58}}
----------------------------891566125788075838224945
Content-Disposition: form-data; name="connects"

[{"endPointSourceId":"tasks-36265","endPointTargetId":"tasks-92172"},{"endPointSourceId":"tasks-36265","endPointTargetId":"tasks-8-7je7ma"},{"endPointSourceId":"tasks-36265","endPointTargetId":"tasks-80161"}]
----------------------------891566125788075838224945
Content-Disposition: form-data; name="name"

testda8
----------------------------891566125788075838224945
Content-Disposition: form-data; name="description"

desc
----------------------------891566125788075838224945--
HTTP/1.1 201 Created
Date: Wed, 03 Feb 2021 08:38:24 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
{"code":0,"msg":"success","data":null}

**Comment by CalvinKirs** [comment]
Can you troubleshoot by printing log? I checked the code and it seems there is no problem.

**Comment by WilliamChen-luckbob** [comment]
> Can you troubleshoot by printing log? I checked the code and it seems there is no problem.

Sure, butI have some trouble when I'm trying to do a debug by adding some printing codes to the source code,  I have no idea how do mvn -U clean package -Prelease -Dmaven.test.skip=true because that leads to some error. I have throw my question out in issue [#4394](https://github.com/apache/incubator-dolphinscheduler/issues/4394)

My DolphinScheduler server was deployed in a remote centOS server by directly downloading a tar.gz file of feature 1.3.4-release. All the movements are according to the official documentation, using MySQL 5.7 as DB.

**Comment by WilliamChen-luckbob** [comment]
I'm totally confuzed...All my succeeded post requests to dolphinscheduler receives {"code":0, "msg":"success", "data":null}

all my steps were following official documentation:
[documentation](https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/standalone-deployment.html)

the server was downloaded from here:
[download source](https://www.apache.org/dyn/closer.cgi/incubator/dolphinscheduler/1.3.4/apache-dolphinscheduler-incubating-1.3.4-dolphinscheduler-bin.tar.gz)

I'm using root privilege to deploy the dophinscheduler, nothing is going wrong except for the null response data.

**Comment by WilliamChen-luckbob** [comment]
I have found that bug. keywords wrong in 1.3.4release.
