### ISSUE TITLE
Task node dependencies across workflow（跨workflow的任务节点依赖）

### ISSUE THREAD

**Issue by carryskye** [apache/incubator-dolphinscheduler#467]
Support the dependencies of any two task nodes, breaking the barriers that task nodes cannot depend on across workflows!

---
支持任意两个任务节点的依赖关系，打破跨workflow之间任务节点无法依赖的壁垒！

**Comment by lidongdai** [comment]
great advice！ thx！
anybody who wanted to implement this feature?

**Comment by njnu-seafish** [comment]
是否可以添加两种特殊task类型：一是等外部workflow某个节点依赖的；还有一个虚拟节点，用来简化workflow内部依赖关系的（比如第二层的两个节点都依赖第一层的三个节点这种交叉依赖的情况）

**Comment by Yeleights** [comment]
dependent task can across workflow even project
