### ISSUE TITLE
[Bug][UI] The tips error when login with username and without password

### ISSUE THREAD

**Issue by banboosgithub** [apache/incubator-dolphinscheduler#4674]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

dolphinscheduler-ui\src\js\conf\login\App.vue
 isUserPassword may be  [ isUserName ]
 <p class="error" v-if="isUserPassword">
          {{userNameText}}
</p>

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@banboosgithub Thanks for your feedback!
@CalvinKirs @chenxingchun This issue can be added into `easy to fix`.

**Comment by CalvinKirs** [comment]
> @banboosgithub Thanks for your feedback! This problem does exist.
> @CalvinKirs @chenxingchun This issue can be added into `easy to fix`.

Thx, if anyone is interested in completing it, you can leave a message below.

**Comment by AlleriaWindrunner** [comment]
i want to solve this issue,  please assign it to me! @CalvinKirs

**Comment by CalvinKirs** [comment]
> i want to solve this issue, please assign it to me! @CalvinKirs

Looking forward to your PR submission

**Comment by chengshiwen** [comment]
@CalvinKirs This issue related with pr #4728 can be closed

**Comment by CalvinKirs** [comment]
duplicate(#4723) close by #4728
