### ISSUE TITLE
[Bug][UDF] udf jar path not exist when fs.defaultFS starts with file:///

### ISSUE THREAD

**Issue by chengshiwen** [apache/incubator-dolphinscheduler#4691]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Set `resource.storage.type=HDFS` and `fs.defaultFS=file:///`
2. Upload custom udf
3. Create hive task and use the custom udf

**Expected behavior**
Bug fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4902714/106994276-69678480-67b7-11eb-8333-ff5b209cfb68.png)
![image](https://user-images.githubusercontent.com/4902714/106994283-6c627500-67b7-11eb-84ba-d62095dea997.png)
![image](https://user-images.githubusercontent.com/4902714/106994285-6d93a200-67b7-11eb-9505-9893d96454a8.png)
![image](https://user-images.githubusercontent.com/4902714/106994309-74bab000-67b7-11eb-825f-e86e17858a9a.png)

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
This can be added into `1.3.5-release`
@CalvinKirs @chenxingchun

**Comment by iwongta** [comment]
docker 最新镜像好像还是有这个问题
