### ISSUE TITLE
[Bug][UI] View workflow version information，Click pagination error

### ISSUE THREAD

**Issue by MrSongYChina** [apache/incubator-dolphinscheduler#4695]
PageSize is undefind

**Comment by CalvinKirs** [comment]
hi, @break60  please make sure if this is a problem?

**Comment by break60** [comment]
Which version？

**Comment by JackIliffe** [comment]
version 1.3.4

**Comment by break60** [comment]
> version 1.3.4

Can you take a screenshot? This feature is only available in the dev branch. There should be no version information for 1.3.4

**Comment by JackIliffe** [comment]
I see.I'm using the dev branch
I was wrong haha
![9fe8050913aaf07ebadf58441793890](https://user-images.githubusercontent.com/43059333/107107039-a7bd7c00-6869-11eb-9003-9d9ff303b090.png)
