### ISSUE TITLE
mailServerPort does not take effect when sslEnable="true" in install.sh(install.sh中sslEnable="true"时mailServerPort不生效)

### ISSUE THREAD

**Issue by yzjzgr** [apache/incubator-dolphinscheduler#480]
I have the following configuration in install.sh:
# mail service port
mailServerPort="13338"
# SSL mail protocol support
# Note: The SSL protocol is enabled by default. Only one of TLS and SSL can be in the true state.
sslEnable="true"

When the service is started, it is found that port 13338 does not take effect. The program still uses the default port of 465, as follows:
org.apache.commons.mail.EmailException: Sending the email to the following server failed : dp-prod-dc3-web01:13338
        At org.apache.commons.mail.Email.sendMimeMessage(Email.java:1242)
        At org.apache.commons.mail.Email.send(Email.java:1267)
        At cn.escheduler.alert.utils.MailUtils.getStringObjectMap(MailUtils.java:389)
        At cn.escheduler.alert.utils.MailUtils.sendMails(MailUtils.java:148)
        At cn.escheduler.alert.manager.EmailManager.send(EmailManager.java:40)
        At cn.escheduler.alert.runner.AlertSender.run(AlertSender.java:100)
        At cn.escheduler.alert.AlertServer.start(AlertServer.java:69)
        At cn.escheduler.alert.AlertServer.main(AlertServer.java:77)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: dp-prod-dc3-web01, port: 465
        At com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972)
        At com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642)
        At javax.mail.Service.connect(Service.java:317)
        At javax.mail.Service.connect(Service.java:176)
        At javax.mail.Service.connect(Service.java:125)
        At javax.mail.Transport.send0(Transport.java:194)
        At javax.mail.Transport.send(Transport.java:124)
        At org.apache.commons.mail.Email.sendMimeMessage(Email.java:1232)
        ... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        At java.net.PlainSocketImpl.socketConnect(Native Method)
        At java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        At java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

After reading the code, I found the following code snippet in cn.escheduler.alert.utils.MailUtils.java (starting at line 125):
                email.setHostName(mailServerHost);
                email.setSmtpPort(mailServerPort);
                //set charset
                email.setCharset(Constants.UTF_8);
                // TLS verification
                email.setTLS(Boolean.valueOf(starttlsEnable));

SetSslSmtpPort is not called in MailUtils.java.
In org.apache.commons.mail.Email, there is the following code:
            If (this.ssl) {
                properties.setProperty("mail.smtp.port", this.sslSmtpPort);
                properties.setProperty("mail.smtp.socketFactory.port", this.sslSmtpPort);
                properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                properties.setProperty("mail.smtp.socketFactory.fallback", "false");
            }

When using ssl to send mail, it uses sslSmtpPort, because setSslSmtpPort is not called in MailUtils.java, so the program uses the default 465.
I made the following changes in MailUtils.sendMails.sendMails and will run correctly after our environment is re-released:
                email.setHostName(mailServerHost);
                //email.setSmtpPort(mailServerPort);
                //set charset
                email.setCharset(Constants.UTF_8);
                // TLS verification
                email.setTLS(Boolean.valueOf(starttlsEnable));

                // SSL verification
                email.setSSL(Boolean.valueOf(sslEnable));
                If (Boolean.valueOf(sslEnable)) {
                    email.setSslSmtpPort(mailServerPort.toString());
                }else {
                    email.setSmtpPort(mailServerPort);
                }

---
我在install.sh中,有如下配置：
# 邮件服务端口
mailServerPort="13338"
# SSL邮件协议支持
# 注意：默认开启的是SSL协议，TLS和SSL只能有一个处于true状态
sslEnable="true"

启动服务的时候，发现13338端口不生效，程序还是用了465默认端口，如下日志：
org.apache.commons.mail.EmailException: Sending the email to the following server failed : dp-prod-dc3-web01:13338
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1242)
        at org.apache.commons.mail.Email.send(Email.java:1267)
        at cn.escheduler.alert.utils.MailUtils.getStringObjectMap(MailUtils.java:389)
        at cn.escheduler.alert.utils.MailUtils.sendMails(MailUtils.java:148)
        at cn.escheduler.alert.manager.EmailManager.send(EmailManager.java:40)
        at cn.escheduler.alert.runner.AlertSender.run(AlertSender.java:100)
        at cn.escheduler.alert.AlertServer.start(AlertServer.java:69)
        at cn.escheduler.alert.AlertServer.main(AlertServer.java:77)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: dp-prod-dc3-web01, port: 465
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1232)
        ... 7 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

看了代码，发现cn.escheduler.alert.utils.MailUtils.java中如下代码片断（125行开始）：
                email.setHostName(mailServerHost);
                email.setSmtpPort(mailServerPort);
                //set charset
                email.setCharset(Constants.UTF_8);
                // TLS verification
                email.setTLS(Boolean.valueOf(starttlsEnable));

MailUtils.java中没有调用setSslSmtpPort, 
在org.apache.commons.mail.Email中，有如下代码：
            if (this.ssl) {
                properties.setProperty("mail.smtp.port", this.sslSmtpPort);
                properties.setProperty("mail.smtp.socketFactory.port", this.sslSmtpPort);
                properties.setProperty("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
                properties.setProperty("mail.smtp.socketFactory.fallback", "false");
            }

当使用ssl发邮件的时候，用的是sslSmtpPort， 因为在MailUtils.java中没有调用setSslSmtpPort, 所以程序用了默认的465, 
我在MailUtils.sendMails.sendMails做了如下更改，在我们环境重新发布后能正确运行:
                email.setHostName(mailServerHost);
                //email.setSmtpPort(mailServerPort);
                //set charset
                email.setCharset(Constants.UTF_8);
                // TLS verification
                email.setTLS(Boolean.valueOf(starttlsEnable));

                // SSL verification
                email.setSSL(Boolean.valueOf(sslEnable));
                if (Boolean.valueOf(sslEnable)) {
                    email.setSslSmtpPort(mailServerPort.toString());
                }else {
                    email.setSmtpPort(mailServerPort);
                }

**Comment by lidongdai** [comment]
very good!  thx!     
@qiaozhanwei  will review this issue!

**Comment by lynchlee** [comment]
+1
