### ISSUE TITLE
sh install.sh   in ubuntu ,show errors

### ISSUE THREAD

**Issue by pxfman** [apache/incubator-dolphinscheduler#510]
That s the system infomation :
Linux version 4.15.0-50-generic (buildd@lcy01-amd64-013) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))

When sh install.sh show errors 
317 line unexpected  "("
Maybe we need a new install.sh with ubuntu
Thanks~

**Comment by pxfman** [comment]
Thanks~

**Comment by boandai** [comment]
very good , thx!

**Comment by qiaozhanwei** [comment]
root@b82223e7377d:/opt/escheduler_deploy# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenia
root@b82223e7377d:/opt/escheduler_deploy# sh install.sh 
1,替换文件
。。。

ubuntu sh install.sh
sh default is  sh -> /bin/dash
you can modify
ln -s /bin/bash /bin/sh
