### ISSUE TITLE
Can you increase the support of flink?(能否增加flink的支持)

### ISSUE THREAD

**Issue by hhaiben123** [apache/incubator-dolphinscheduler#514]
Can you increase the support of flink?

---
希望增加下flink的支持

**Comment by boandai** [comment]
good idea, if anybody else also like this feature, please reply "+1" , it will be better to describe the business usage scenarios.

**Comment by Tianny** [comment]
+1

**Comment by qq389401879** [comment]
+1

**Comment by caicaimi** [comment]
+1

**Comment by gk0916** [comment]
+1

**Comment by LoveEvenWong** [comment]
+1

**Comment by dailidong** [comment]
pr #711

**Comment by thisnew** [comment]
+1

**Comment by LoveEvenWong** [comment]
> +1
> 有人实现这个功能吗？如果没有的话，我是愿意把我们的实现贡献进来。

已经实现了#711

**Comment by iamnotgay** [comment]
+1

**Comment by laudylcp** [comment]
+1

**Comment by dailidong** [comment]
flink has been supported in version 1.2.0

**Comment by dailidong** [comment]
1.2.0 add flink task type
