### ISSUE TITLE
The workflow instance is started, the task instance cannot start eating, and the positioning problem is in the successful submission status.(工作流实例启动，任务实例无法启动吃，处于提交成功状态的定位问题)

### ISSUE THREAD

**Issue by carryskye** [apache/incubator-dolphinscheduler#530]
Steps:
1, delete the workflow instance;
2, found existence ** task instance ** not deleted
3, the corresponding database table t_escheduler_command, t_escheduler_process_instance, t_escheduler_task_instance
![image](https://user-images.githubusercontent.com/51945224/60714297-635f5100-9f4d-11e9-9371-329d3fd22547.png)
4, start a new workflow instance;
5, found that the task instance has been in the state of successful submission

![image](https://user-images.githubusercontent.com/51945224/60714407-9acdfd80-9f4d-11e9-9d10-55feb979f0b0.png)

![image](https://user-images.githubusercontent.com/51945224/60714418-9f92b180-9f4d-11e9-9298-84d573ac8176.png)

---
操作步骤：
1，删除工作流实例；
2，发现存在**任务实例**没有删除
3，情况对应的数据库表t_escheduler_command、t_escheduler_process_instance、t_escheduler_task_instance
![image](https://user-images.githubusercontent.com/51945224/60714297-635f5100-9f4d-11e9-9371-329d3fd22547.png)
4，启动新的工作流实例；
5，发现任务实例一直处于提交成功的状态

![image](https://user-images.githubusercontent.com/51945224/60714407-9acdfd80-9f4d-11e9-9d10-55feb979f0b0.png)

![image](https://user-images.githubusercontent.com/51945224/60714418-9f92b180-9f4d-11e9-9298-84d573ac8176.png)

**Comment by qiaozhanwei** [comment]
Normal deletion is OK, I want to know how the operation causes the process instance to be deleted and the corresponding task instance is not deleted.

正常的删除都是可以的，我想知道怎么操作引起流程实例删除而相对应的任务实例没有删除

**Comment by RunchenSong** [comment]
the same issue in version 1.2.0 
1.shell detail 
![image](https://user-images.githubusercontent.com/25541501/71441195-66d4d780-273b-11ea-91c9-90e7127fcdf8.png)
2.online the workflow
![image](https://user-images.githubusercontent.com/25541501/71441225-8e2ba480-273b-11ea-9547-f34337de6109.png)
3. SUBMITTED_SUCCESS complete
![image](https://user-images.githubusercontent.com/25541501/71441318-fb3f3a00-273b-11ea-8c55-9ac250851b17.png)
![image](https://user-images.githubusercontent.com/25541501/71441350-190c9f00-273c-11ea-8f38-235360e818ed.png)
4.task instance not found
![image](https://user-images.githubusercontent.com/25541501/71441379-2fb2f600-273c-11ea-9281-e68c35626f11.png)

**Comment by QQhuxuhui** [comment]
I encountered the same issue

**Comment by gabrywu** [comment]
@carryskye Do you already resolve it?

**Comment by carryskye** [comment]
> @carryskye Do you already resolve it?

not really resolve it,truncate instance process table and then it not appear！

**Comment by chengshiwen** [comment]
Close this issue since no updates for long time
