### ISSUE TITLE
Sort out FAQ(FAQ整理)

### ISSUE THREAD

**Issue by Jave-Chen** [apache/incubator-dolphinscheduler#535]
## V1.0.4

**Q: Worker and master end automatically, what is the reason? **

A:

```shell
Unable to read additional data from server sessionid 0x16a2
Ecfc248014e, likely server has closed socket, closing socket connection and attempting reconnect
org.apache.zookeeper.ClientCnxn:[1162] - Session 0x16a2ecfc2480151 for server null, unexpected error
Closing socket connection and attempting reconnect
```
If worker and master fail to connect zk, the master and worker will automatically exit and report the error as above.

---

**Q: How do I modify the zk configuration after installation? **

A: Modify the corresponding value in the corresponding node `conf/zookeeper.properties` file and restart master/worker.

---

**Q: Installation error under ubuntu, how to solve? **

A: ubuntu uses `sudo bash install.sh`

------

**Q: After closing the alert service, why is there still an alarm error in the sql task log? **

A: sql task, process alarm, fault tolerance will take the mail.

------

**Q: Does the sql node support hive 1.1? **

A: Support hive 1.1 You need to modify the hive-jdbc version value in the source pom, and then recompile and copy the obtained file to the lib directory.

------

**Q: Does it support LDAP authentication? **

A: It is planned to add kerboers authentication in 1.1.0, and LDAP support has no plan.

---

**Q: Can I use HQL's hive variable in the sql node, such as ${hiveconf:test} ? **

A: No. ${var} in the sql node will be replaced.

------

**Q: The service starts with an error, prompting `nohup: Unable to run the command "/bin/java": No such file or directory `How to deal with **? **

A: Modify the **escheduler-daemon.sh** file in the bin directory and change `export JAVA_HOME=$JAVA_HOME` to an absolute path, such as `export JAVA_HOME=“/usr/local/java”`.

------

**Q: Master and worker stop automatically, is there a way to restart automatically? **

A: The monitoring script is automatically started after you execute install.sh. The script is as follows:

```shell
Nohup python -u ${workDir}/script/monitor_server.py $installPath $zkQuorum $zkMasters $zkWorkers > ${workDir}/monitor_server.log 2>&1 &
```

It can also be executed separately after being replaced according to the configuration, such as:

```shell
Nohup python -u /escheduler/script/monitor_server.py "/escheduler" "192.168.XXX.XXX:2181,192.168.XXX.XXX:2181,192.168.XXX.XXX:2181" "/escheduler/masters" "/escheduler /workers" > /escheduler/logs/monitor_server.log 2>&1 &
```

------

**Q: The service is reporting an error, prompting `There is insufficient memory ...` How to deal with **? **

A: Modify the **bin/escheduler-daemon.sh** file and modify the -Xmx value in ESCHEDULER_OPTS according to the actual situation.

```shell
Export ESCHEDULER_OPTS="-server -Xmx16g -Xms4g -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
```

---
## V1.0.4

**Q: worker 和 master 自动结束，会有什么原因？**

A:

```shell
Unable to read additional data from server sessionid 0x16a2
ecfc248014e, likely server has closed socket, closing socket connection and attempting reconnect
org.apache.zookeeper.ClientCnxn:[1162] - Session 0x16a2ecfc2480151 for server null, unexpected error
, closing socket connection and attempting reconnect
```
如 worker 和 master 连接 zk 失败，master 和 worker 就会自动退出，报错如上。

---

**Q: 安装以后，如何修改 zk 配置？**

A: 修改对应节点 `conf/zookeeper.properties` 文件中对应的值，重启 master/worker 即可。

---

**Q:ubuntu 下安装报错，如何解决？**

A: ubuntu 用 `sudo bash install.sh`

------

**Q: 关闭  alert 服务后，为什么 sql 任务日志还是有告警错误？**

A: sql 任务，流程告警，容错都会走邮件。

------

**Q: sql 节点是否支持 hive 1.1 ？**

A: 支持 hive 1.1 需在源码 pom 中修改 hive-jdbc version 值，然后重新进行编译将得到的文件复制到 lib 目录下。

------

**Q: 是否支持 LDAP 认证 ？**

A: 计划在 1.1.0 中加入 kerboers 认证，LDAP 支持暂无计划。

---

**Q: sql 节点中能否使用 HQL 的 hive 变量，如 ${hiveconf:test} ？**

A: 不能。sql 节点中的 ${var}  都会被替换。

------

**Q: 服务启动时报错，提示 `nohup： 无法运行命令“/bin/java”: 没有那个文件或目录` 如何处理**？**

A: 修改 bin 目录下**escheduler-daemon.sh** 文件，将 `export JAVA_HOME=$JAVA_HOME` 修改为绝对路径，如 `export JAVA_HOME=“/usr/local/java”`。

------

**Q: master 和 worker 自动停止，是否有办法自动重启？**

A: 执行 install.sh 后，会自动启动监控脚本。脚本如下：

```shell
nohup python -u ${workDir}/script/monitor_server.py $installPath $zkQuorum $zkMasters $zkWorkers > ${workDir}/monitor_server.log 2>&1 &
```

也可以根据配置进行替换后单独执行，如：

```shell
nohup python -u /escheduler/script/monitor_server.py "/escheduler" "192.168.XXX.XXX:2181,192.168.XXX.XXX:2181,192.168.XXX.XXX:2181" "/escheduler/masters" "/escheduler/workers" > /escheduler/logs/monitor_server.log 2>&1 &
```

------

**Q: 服务启动时报错，提示 `There is insufficient memory ...` 如何处理**？**

A: 修改 **bin/escheduler-daemon.sh** 文件，根据实际情况修改 ESCHEDULER_OPTS 中 -Xmx  值。

```shell
export ESCHEDULER_OPTS="-server -Xmx16g -Xms4g -Xss512k -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
```

**Comment by dailidong** [comment]
very great job！
All contributions will be greatly appreciated
