### ISSUE TITLE
sql task alarm configuration, it is recommended to be configurable, optional or not selected(sql任务的告警配置，建议做成可配置的，可选可不选)

### ISSUE THREAD

**Issue by xubin8558** [apache/incubator-dolphinscheduler#547]
The current log alarm policy is that when the alarm fails, the task is reported incorrectly. In fact, the task is executed OK. Only the email alarm needs to be blocked.

---
目前的日志告警策略是告警失败就会任务报错，其实任务是执行OK了的，只需要屏蔽邮件告警，就OK

**Comment by boandai** [comment]
good idea! thx!

**Comment by chengshiwen** [comment]
Close by #5104
![image](https://user-images.githubusercontent.com/4902714/114262243-700db480-9a11-11eb-9413-15e0a03906b9.png)
