### ISSUE TITLE
How to extend the worker node（如何扩展worker节点）

### ISSUE THREAD

**Issue by Slash-Wong** [apache/incubator-dolphinscheduler#583]
![173035_3f8b751e_876654](https://user-images.githubusercontent.com/38338543/61346330-df7d6100-a88a-11e9-81b0-6b08705460df.png)

**Comment by qiaozhanwei** [comment]
The conf file on the deployed machine is directly overwritten to the root directory of the worker machine to be extended, and the corresponding Master and Worker can be started. Refer to the backend deployment documentation for the basic configuration.


将部署好机器上的conf文件直接覆盖到要扩展的Worker机器调度的根目录下，启动相应的Master和Worker即可。基础配置请参考后端部署文档。

**Comment by Slash-Wong** [comment]
说的不够具体，有点模糊

**Comment by Slash-Wong** [comment]
* 启停Master

```启动master
sh ./bin/escheduler-daemon.sh start master-server
sh ./bin/escheduler-daemon.sh stop master-server
```

* 启停Worker

```
sh ./bin/escheduler-daemon.sh start worker-server
sh ./bin/escheduler-daemon.sh stop worker-server
```

* 启停Api

```
sh ./bin/escheduler-daemon.sh start api-server
sh ./bin/escheduler-daemon.sh stop api-server
```
* 启停Logger

```
sh ./bin/escheduler-daemon.sh start logger-server
sh ./bin/escheduler-daemon.sh stop logger-server
```
* 启停Alert

```
sh ./bin/escheduler-daemon.sh start alert-server
sh ./bin/escheduler-daemon.sh stop alert-server
```
