### ISSUE TITLE
User password plain text display problem（用户密码明文显示问题）

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#586]
When I create a user in `User Management`, I think that the password should not be displayed in plain text on the page. I hope to change the plain text display to cipher text display, for example: `******`

current version:

`1.0.4 release`

The desired effect:

The password is displayed as cipher text

---
`用户管理` 中当我创建用户的时候，我认为密码在页面上不应该是明文显示，希望能将明文显示修改为密文显示，例如: `******`

当前版本：

`1.0.4 release`

希望达到的效果：

密码显示为密文显示

**Comment by boandai** [comment]
very good issue, and would you like to fix this issue?

**Comment by coding-now** [comment]
用户登录部分，前端也是密码明文传输
