### ISSUE TITLE
Get normal user information error（获取普通用户信息错误）

### ISSUE THREAD

**Issue by tianchenglong** [apache/incubator-dolphinscheduler#588]
esceduler/users/get-user-info?_t=0.8241656444608905
There is a problem with the mapper layer sql written by this interface.

---
escheduler/users/get-user-info?_t=0.8241656444608905
这个接口的mapper层sql写的有问题

**Comment by qiaozhanwei** [comment]
Which version? what is the problem?

哪个版本？什么问题？
