### ISSUE TITLE
The worker_logback.xml configuration file has a small bug? The following is a comparison of the folders generated before and after the modification.（worker_logback.xml配置文件有一个小bug?如下是修改前后，logs下生成的文件夹对比）

### ISSUE THREAD

**Issue by gk0916** [apache/incubator-dolphinscheduler#604]
![image](https://user-images.githubusercontent.com/29849547/61456574-0629bd80-a999-11e9-94ec-851457b3f11c.png)

![image](https://user-images.githubusercontent.com/29849547/61457016-0b3b3c80-a99a-11e9-9011-6afc267f1bcd.png)

![image](https://user-images.githubusercontent.com/29849547/61457067-2312c080-a99a-11e9-8f40-0cd19f41c81d.png)

**Comment by qiaozhanwei** [comment]
![QQ截图20190719144212](https://user-images.githubusercontent.com/23756105/61514937-ccf25b80-aa33-11e9-9ede-e07ed3d84d62.png)

cn.escheduler.server.worker.log.TaskLogAppender

**Comment by nielifeng** [comment]
赞
