### ISSUE TITLE
Enterprise WeChat message failed to push（企业微信消息推送失败）

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#621]
We are now experiencing a problem. When we configure dozens of jobs in a workflow, if these dozens of jobs fail, I find that `mail` can receive the message push normally, but

I found that `Enterprise WeChat` did not receive the message push normally. When I checked the log, I found an error message. The following is the error message:

```
Resp:{"errcode":45002,"errmsg":"content size out of limit, hint: [1563869667_1_f6b18ca536f2925269b2b36e95aa4dd1], from ip: 111.202.110.196, more info at https://open.work.weixin.qq.com/ Devtool/query?e=45002"}
```

It is possible that there are too many jobs in a single workflow. If all the jobs fail, because the WeChat has a limit on the length of a single piece of content, too much content of a single message causes the WeChat to fail to be sent.

If you adjust the sending policy of the message content, it may be better. The current sending strategy is to send all the failed jobs in a workflow to a message.

**current version:**

`1.1.0-preview`

** Expected results: **

Enterprise WeChat can receive all message pushes normally

---
我们现在遇到一个问题，当我们在一个工作流里面配置几十个作业时，如果这几十个作业都失败了，我发现 `邮件` 是可以正常接收到消息推送的，但是

我发现 `企业微信` 没有正常接收到消息推送，当我查看日志的时候发现有报错信息，以下是报错信息：

```
resp:{"errcode":45002,"errmsg":"content size out of limit, hint: [1563869667_1_f6b18ca536f2925269b2b36e95aa4dd1], from ip: 111.202.110.196, more info at https://open.work.weixin.qq.com/devtool/query?e=45002"}
```

有可能是单个工作流里面的作业太多，如果所有作业都失败了，由于企业微信对单条内容长度有限制，单条消息的内容太多导致企业微信发送失败。

如果调整一下消息内容的发送策略可能会好些，现在的发送策略是把一个工作流里面所有失败的作业都集中都一条消息里面发送了。

**当前版本：**

`1.1.0-preview`

**期望达到的效果：**

企业微信可以正常接收到所有消息推送

**Comment by boandai** [comment]
Very detailed description！ very good!

@lgcareer please fix this issue!
