### ISSUE TITLE
Consultation: Scheduled scheduled tasks cannot be online（咨询：调度定时任务不能上线）

### ISSUE THREAD

**Issue by butingzhuanquanquan** [apache/incubator-dolphinscheduler#624]
You can create a new scheduled task but click on the line and there is no response and no log.

---
可以创建新的定时任务但是点击上线没反应也没日志

**Comment by boandai** [comment]
1、please open debug mode in the brower and see the response from the api server!
2、also can see api server runtime log to see if there  are some exceptions

**Comment by butingzhuanquanquan** [comment]
你好~按照您的方法打开了debug模式但是没有日志打印，我测试发现当我创建一个定时任务是没有问题的数据库中t_escheduler_schedules表会添加一条定时数据进去，但当我点击上线后，前端页面无反应且会把t_escheduler_schedules这张表锁定，我测试过将t_escheduler_schedules中的RELEASE_state字段手动更新为1 这样前端会显示为上线状态
所以可能是程序那块提交请求到mysql出了问题

**Comment by butingzhuanquanquan** [comment]
> 1、please open debug mode in the brower and see the response from the api server!
> 2、also can see api server runtime log to see if there are some exceptions

你好~按照您的方法打开了debug模式但是没有日志打印，我测试发现当我创建一个定时任务是没有问题的数据库中t_escheduler_schedules表会添加一条定时数据进去，但当我点击上线后，前端页面无反应且会把t_escheduler_schedules这张表锁定，我测试过将t_escheduler_schedules中的RELEASE_state字段手动更新为1 这样前端会显示为上线状态
所以可能是程序那块提交请求到mysql出了问题

**Comment by dailidong** [comment]
Has the issue been resolved already?

**Comment by dailidong** [comment]
no response , close the issue temporarily
