### ISSUE TITLE
In the workflow instance click to stop the operation can not really stop（在工作流实例 点击 停止 操作作业无法真正停止）

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#633]
I am having a problem now. I have several tasks that I have been unable to submit to `yarn`. After a while I clicked the `Stop` button in the `Workflow Instance`. After I clicked, the `status` always shows `Ready to stop. `, but it has not stopped. When I view the task in the 'task instance', `state` always shows `prepare to submit`. It seems that the task is not stopped or killed. The following is a screenshot of the task:

**Workflow example: **

![image](https://user-images.githubusercontent.com/29206593/61931447-3386f480-afb3-11e9-9ec4-e138c412a779.png)

**Task instance: **

![image](https://user-images.githubusercontent.com/29206593/61931583-95475e80-afb3-11e9-87d6-04de03b07567.png)

**current version:**

`1.1.0-preview`

**Desired result:**

`Prepare to submit status`, `committed status` and `running status` can be stopped automatically.

---
我现在遇到一个问题，我有几个任务一直无法提交到 `yarn` 上去，我过了一会儿在 `工作流实例` 那里点击 `停止` 按钮，我点击完后 `状态` 一直显示 `准备停止`，但一直都没有停止，我在 `任务实例` 那里查看任务的时候， `状态` 一直显示 `准备提交` ，好像是没有将任务真正停止掉或 `kill` 掉，以下是任务运行截图：

**工作流实例：**

![image](https://user-images.githubusercontent.com/29206593/61931447-3386f480-afb3-11e9-9ec4-e138c412a779.png)

**任务实例：**

![image](https://user-images.githubusercontent.com/29206593/61931583-95475e80-afb3-11e9-87d6-04de03b07567.png)

**当前版本：**

`1.1.0-preview`

**期望结果：**

`准备提交状态`、`已提交状态` 以及 `正在运行状态` 的任务都可以真正停止掉

**Comment by boandai** [comment]
`stop button` is not to stop the currently running task, it will stop the next pending task
---
目前停止按钮是不会停当前正在运行的任务的，停的是下一个待执行任务

**Comment by wuchunfu** [comment]
那我该如何停止 `准备提交状态` 的任务和 `已提交状态` 的任务呢？

**Comment by boandai** [comment]
I'm sorry I didn't give you the right information.
now, stop button will kill the job， your situation probably because workerserver not work normally，you can see worker server runtime log to find more information

**Comment by zhangzhipeng621** [comment]
the same problem with me, when i use default worker group that no problem, but use custom worker group that got the follow problem, hope to solve the problem of positioning

![step-1](https://user-images.githubusercontent.com/14704224/62934511-5446ab00-bdf7-11e9-9f87-e5e4a7883bc8.png)
![step-2](https://user-images.githubusercontent.com/14704224/62934518-590b5f00-bdf7-11e9-8b8f-8563c3037fe9.png)
![step-3](https://user-images.githubusercontent.com/14704224/62934524-5b6db900-bdf7-11e9-9a6a-2394f5cb64b4.png)

**Comment by lenboo** [comment]
that situation is normal for now. 
tasks would not be stop when it is not running.
the stop process would be optimized in the next version.

**Comment by zhangzhipeng621** [comment]
> that situation is normal for now.
> tasks would not be stop when it is not running.
> the stop process would be optimized in the next version.

sorry, this is not same to @wuchunfu  , i do not click stop button in the Workflow Instance ,i just click the run button with my custom worker group, and dispear that problem

对不起，@boandai , 这个错误和@wuchunfu不一样，我这个没有点击停止按钮操作，我这个是执行运行流程操作，指定了我配置的worker group组，错误就是我上面那3张截图；当我使用默认的worker分组时候就没什么问题，所以我这边怀疑是使用自定义worker分组有问题，我这边3个节点，使用的是esz-1.1.0版本

**Comment by dailidong** [comment]
@lenboo ，please confirm the issue of custom worker group？

**Comment by roger68** [comment]
@wuchunfu  make sure your server support “pstree“ command

**Comment by dailidong** [comment]
This issue has been opened for a long time，if still not sovled, please reopen it, I will close it temporarily
