### ISSUE TITLE
Can I add a column in the workflow instance/task instance list (committed parameter system.biz.date)（在工作流实例/任务实例列表中，能否增加一列（提交的参数 system.biz.date））

### ISSUE THREAD

**Issue by billwang828** [apache/incubator-dolphinscheduler#635]
In the workflow instance/task instance list, whether you can add a column (submitted parameter system.biz.date), it is not intuitive enough to feel the number of workflows/tasks that have been running (what day/timestamp). Especially when making up the number, it is not clear enough.

![image](https://user-images.githubusercontent.com/25118991/61940137-61763400-afc7-11e9-865e-1c6396552582.png)
Two complements, it is not clear which number of days to fill, halo

---
在工作流实例/任务实例列表中，能否增加一列（提交的参数 system.biz.date），感觉曾经跑的工作流/任务到底在跑（哪天/时间戳）的数，不够直观。尤其是在补数时，不够明确。

![image](https://user-images.githubusercontent.com/25118991/61940137-61763400-afc7-11e9-865e-1c6396552582.png)

两次补数，都不清楚补的哪天的数，晕

**Comment by boandai** [comment]
very good! could you submit a pull request to implement this feature!

**Comment by chengshiwen** [comment]
Close this issue since `system.biz.date` has been supported
