### ISSUE TITLE
[BUG] "Statistics" menu, there are not datas display on the page

### ISSUE THREAD

**Issue by zhangzhipeng621** [apache/incubator-dolphinscheduler#636]
**Describe the bug**
when i click the "Statistics" menu, there are not datas display on the page, the blackgroud of escheduler-api-server.log Exception is: 

![image](https://user-images.githubusercontent.com/14704224/62016383-6401a500-b1e4-11e9-8cb8-270e122547c9.png)

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Comment by dailidong** [comment]
has this problem been solved?
