### ISSUE TITLE
[DISCUSSION] Are we all hoping to move to Apache incubator?

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-dolphinscheduler#638]
This is a discussion thread, I hope all project maintainer/contributor/user(s) join this. If you agree and want us to move forward Apache Foundation, starting at Incubator, please leave your feedback.

Very appreciated.

**Comment by qiaozhanwei** [comment]
Escheduler has more than 1,400 stars in just four months. The community is relatively active and I hope to enter apache.

**Comment by samz406** [comment]
simple to use.

**Comment by feloxx** [comment]
Unit testing and ci are not enough.

**Comment by boandai** [comment]
> Unit testing and ci are not enough.

yes, we have already discovered this very early and we will improve it !  thanks!

**Comment by lgcareer** [comment]
I believe that every programmer has own dream of open source! Now there is an opportunity to turn dreams into reality, I am willing to join, also hope more and more programmer to join.

**Comment by wu-sheng** [comment]
Hi, everyone

I knew and noticed that the project has a long of spaces to improve. Also, that is why it should be an Apache incubator project as a start. I think if everyone in this community is willing to build a wide and diverse community, that is good enough for now.

This is a young open-source project, it has time :)

**Comment by lenboo** [comment]
If we want help more engineers use Easy Scheduler for saving their time, we should move forward Apache Foundation.

**Comment by wuchunfu** [comment]
I come here with a passion for open source. I want to turn my dream into reality.I am willing to join the world's top open source community. I am willing to contribute with contributors from all over the world.

**Comment by William-GuoWei** [comment]
Fully agreed to join Apache incubator.
Let more people know this useful ETL tool. 
One of my former colleague in Teradata is adopted this tool with Teradata. He highly recommended other people to use it.

**Comment by William-GuoWei** [comment]
I also make a vote on Tencent Questionnaire for better spreading.
 https://wj.qq.com/s2/4190958/5588/

**Comment by billwang828** [comment]
Easy Scheduler is very useful, the concept of "instance of process" and "instance of job" are very good, it is easy maintenance/monitor than ETLA tool of Teradata.

**Comment by dailidong** [comment]
For a much longer-term development and community prosperity, I am in favor of contributing EasyScheduler to apache.

**Comment by William-GuoWei** [comment]
Here is the result from Tencent Questionnaire, 31 people from a different company who are using Easy Scheduler.
100% agree with that Easy Scheduler move to Apache incubator.
74.2 % want to be users.
38.7% want to be committers.
12.9% want to be core developers.
Please see the attachment.

[stat_4190958.TXT](https://github.com/analysys/EasyScheduler/files/3471108/stat_4190958.TXT)

**Comment by boandai** [comment]
Can we consider closing this discussion，for now all of us agree with that EasyScheduler move to apache incubator !

**Comment by wu-sheng** [comment]
Good for me. Let's make the proposal ready. 

Just keep this open, more people may show their interests.

**Comment by boandai** [comment]
Uh-huh.
