### ISSUE TITLE
A Single Problem for deplay

### ISSUE THREAD

**Issue by BigDataQiChao** [apache/incubator-dolphinscheduler#647]
When I deployed the front-end UI, 404 appeared, as if Nginx could not find the API interface service.
So, I would like to ask, how to configure the API service.
Need two server IP addresses? OR,What is the reason why Nginx is not agentable?

**Comment by boandai** [comment]
please add title for this issue！thx

**Comment by BigDataQiChao** [comment]
No Problem, please hold on !




------------------ 原始邮件 ------------------
发件人: "easyscheduler"<notifications@github.com>; 
发送时间: 2019年7月30日(星期二) 中午11:38
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>; 
抄送: "JavaWeb-赵起超"<1416537683@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] [BUG]  (#647)




please add title for this issue！thx

**Comment by boandai** [comment]
check   param in install-escheduler-ui.sh: 
`esc_proxy_port="http://192.168.xx.xx:12345"`
does it match api server ip and port

then , you can check api server has already been started or not? please start api server first, its ip and port should match  config in install-escheduler-ui.sh

last, you'd better to open debug on brower to see `the response content from api server`

**Comment by boandai** [comment]
this is not a  bug, just label it as `question`

**Comment by BigDataQiChao** [comment]
Very kind of you 
I will try my best to do 




------------------ 原始邮件 ------------------
发件人: "easyscheduler"<notifications@github.com>; 
发送时间: 2019年7月30日(星期二) 下午3:27
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>; 
抄送: "JavaWeb-赵起超"<1416537683@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [analysys/EasyScheduler] A Single Problem for deplay (#647)




check   param in install-escheduler-ui.sh:
 esc_proxy_port="http://192.168.xx.xx:12345"
 does it match api server ip and port
 
then , you can check api server has already been started or not? please start api server first, its ip and port should match  config in install-escheduler-ui.sh
 
last, you'd better to open debug on brower to see the response content from api server
