### ISSUE TITLE
[Feature]Send to message queue request after reading data（读取数据后发送到消息队列需求）

### ISSUE THREAD

**Issue by huanzui** [apache/incubator-dolphinscheduler#657]
**Describe the solution you'd like**
Each time you read 100 data in the database, it is sent to the message queue. The message queue is a place where big data is used. You don't have to write a jar package to send it.

---
**Describe the solution you'd like**
每次读取数据库100条数据后发送到消息队列，消息队列是大数据用的比较多的地方，不用自己再写个jar包程序发送

**Comment by boandai** [comment]
very good, thx!

if anybody else also need this feature please reply some words!

**Comment by gabrywu** [comment]
read what data and output what message queue? I think users can do it by themself, not DolphinScheduler's scope
