### ISSUE TITLE
Confusion about an application scenario

### ISSUE THREAD

**Issue by BigDataQiChao** [apache/incubator-dolphinscheduler#658]
Now, I want to use this platform to realize batch loop processing of data in the database.And insert the processed normalized data into the new data table.
Is there such a scenario?
To put it simply, I only need two steps: first, query tens of thousands of pieces of data from the database, and then perform loop processing to delete the data that does not meet the requirements;The second step is to store the processed data into another new data table

**Comment by boandai** [comment]
shell task can do this?

**Comment by William-GuoWei** [comment]
please add detail title description, `A Question` is not very suitable， thx！

**Comment by BigDataQiChao** [comment]
All right then, I'll change it right away







------------------ 原始邮件 ------------------
发件人: "Guo Wei (William)"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午5:31
收件人: "analysys/EasyScheduler"<EasyScheduler@noreply.github.com>;
抄送: "JavaWeb-赵起超"<1416537683@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [analysys/EasyScheduler] A Question (#658)




please add detail title description, A Question is not very suitable， thx！

**Comment by dailidong** [comment]
program will be needed!
another way may be considered: use task self-dependency

---
像这种需求，最好自己用程序来实现，然后放在调度里。或者可以考虑使用自依赖，一个依赖于上一次批处理的完成
