### ISSUE TITLE
[Feature] task instance overlap （任务实例重叠,策略问题）

### ISSUE THREAD

**Issue by hujiang75277381** [apache/incubator-dolphinscheduler#681]
When the execution period of the process task A is 1 minute, but the actual execution time is 2 minutes, the first task instance and the second task instance overlap.

I recommend adding strategies such as serial, parallel, pre-schedule, and subsequent scheduling.

Reason: In actual production, there is a problem that the task cannot be repeatedly executed and the task cannot be judged for the specific running time.

---
当流程任务A 的执行周期是1分钟1次,但是实际的执行时长是2分钟,那么第一次的任务实例和第二次的任务实例重叠。

我建议,添加 串行、并行、覆盖之前调度、丢弃后续调度 等策略

原因：在实际生产中,存在任务不能重复执行和无法判断任务具体运行时长的问题。

**Comment by hujiang75277381** [comment]
我想到的解决方案,是这样的。
在zk队列中添加策略标识(流程优先级_流程实例id_任务优先级_任务id_任务执行的机器id1,任务执行的机器id2_策略)，情况如下：
串行:丢回队列
并行:立即执行
覆盖之前调度:杀死之前的调度,然后开始新的执行
丢弃后续调度:不投递到zk队列,直接失败处理

**Comment by gabrywu** [comment]
Yes, good suggestion,similar with https://github.com/apache/incubator-dolphinscheduler/issues/694
Even the latest version not support this feature, @hujiang75277381 could you create a PR to implement it?
