### ISSUE TITLE
[DICUSSION] EasyScheduler Roadmap discussion

### ISSUE THREAD

**Issue by boandai** [apache/incubator-dolphinscheduler#690]
# EasyScheduler Roadmap 

EasyScheduler has a lot of community users (>1000), they come from various companies, and of course there are some individuals. Our current development tasks come from the community, Overall priority of function implementation based on community needs and attention

Most of the main PR described here are fairly rough and will require non-trivial time commitment to design, implement, and test. If you are interested in helping out, Please leave a message under the corresponding issue!  If you are interested in features that are not on this roadmap, please propose them in the github issues and we will try to include them. 

## Plug-in Task Types

Considering that there are many task types that need support, there are also third-party plugins that need to be integrated, and are being designed and discussed to ensure this.

The main PR behind this change is:

https://github.com/analysys/EasyScheduler/issues/201

## Authorized resources use the directory tree

The resource file is modified to the directory mode, and the authorization resources are also modified accordingly.

The main PR behind this change is:

https://github.com/analysys/EasyScheduler/issues/404

## Parameter passing

the output parameter of the previous node can be used as the input of the next node.

The main PR behind this change is:

https://github.com/analysys/EasyScheduler/issues/116

 

## DAG graph supports copying, exporting, and importing

Implement one-time configuration for everywhere use and backup the key information

the detail description is ：

https://github.com/analysys/EasyScheduler/issues/233

## Removing Dependencies

for now EasyScheduler has many external dependencies that prevent it from being able to be easily embedded in other projects and also introduce additional complexity and operational considerations.

this issue address：
https://github.com/analysys/EasyScheduler/issues/697

## Easy to use

We plan to implement some more detailed design documents to help users understand the design principle and implementation of EasyScheduler.

**Comment by boandai** [comment]
### multi database support
we will support postgresql as default db becase of license

**Comment by boandai** [comment]
## refacting code

**Comment by wangshu-zhouyunfan** [comment]
Support task customization scheduling cycle

this pr address：
[#938](https://github.com/apache/incubator-dolphinscheduler/issues/938)
