### ISSUE TITLE
[Feature]Docker image optimization（Docker镜像优化)

### ISSUE THREAD

**Issue by songdi676** [apache/incubator-dolphinscheduler#703]
The current Dockerfile is bloated and deeper: it has zk, maven, and node installed. Each module should have its own separate image.
Like zk I can use the official image directly without having to hit the image.
And EasyScheduler's own module, after compiling and generating the Jar package, "FROM openjdk:8-jre-slim" directly copies the Jar based on the jdk image.

---
当前Dockerfile,臃肿且层级较深：里面安装了zk,maven,node。 各模块应该有自己单独的镜像。
像zk我可以直接使用官方镜像不需要打到镜像里面。
而EasyScheduler自己的模块，编译生成Jar包后，“FROM openjdk:8-jre-slim” 直接基于jdk镜像把Jar拷贝进去。

**Comment by dailidong** [comment]
good idea！

Welcome to contribute pull request！

**Comment by francis-du** [comment]
@dailidong Can you assign this issue to me？

**Comment by dailidong** [comment]
PR #4529 solved this issue
