### ISSUE TITLE
[BUG]DEPENDENT task problem(DEPENDENT任务依赖问题)

### ISSUE THREAD

**Issue by victoryjames** [apache/incubator-dolphinscheduler#717]
Under a workflow, I configured the DEPENDENT task to rely on other workflow tasks under the same project, setting the number of failed retries, but it did not take effect.
Phenomenon: Once the upstream workflow is not completed, the test is completed once, and the failed task ends.
Expectations: The number of failed retries function works

---
一个工作流下我配置了DEPENDENT组件，用来依赖同一个项目下其他工作流的任务，设置了失败重试次数，但是并没有生效
现象： 一旦上游工作流未完成，检测一次，失败了任务就结束了
期望：失败重试次数功能起作用

**Which version of Easy Scheduler:**
 1.1.0

**Comment by dailidong** [comment]
Has this problem been resolved already?

**Comment by lenboo** [comment]
i think this question already resolved in the new release.
so i will close it.
