### ISSUE TITLE
[BUG] the first task checkWorkerGroup error then others task cant execute in task queen

### ISSUE THREAD

**Issue by mnloveyx** [apache/incubator-dolphinscheduler#719]
[BUG] the first task checkWorkerGroup error then others task cant execute in task queen,and then cycle execute first task then and then

**Comment by dailidong** [comment]
I‘m sorry , I can't understand what you said!  you can desc issue in chinese, then  translate it to english by using baidu or google!  thanks!

**Comment by mnloveyx** [comment]
在任务队列中，如果第一个任务在流程组中定义了实现任务的流程组，但又在流程组中找不到执行任务的主机，此时所有任务都会被第一个任务阻塞在队列中。
![image](https://user-images.githubusercontent.com/20296448/63480752-9fcb1a00-c4c5-11e9-8d9e-281f21029f3d.png)

**Comment by dailidong** [comment]
If worker group has been defined previously，but no worker is found in the worker group that could execute the task, should the worker working group be changed?

---
如果先前定义了实现任务的工作组，在执行时发现没有worker在这个任务的工作组中，那应该改worker工作组吧？

**Comment by dailidong** [comment]
Duplicate of #352, has been resolved in version 1.1.0
