### ISSUE TITLE
mail issue

### ISSUE THREAD

**Issue by LiemLin** [apache/incubator-dolphinscheduler#728]
There are three questions：
1. The parameter mail.smtp.ssl.trust is not supported
2. The mailSender in PasswordAuthentication() and setFrom() may not be the same in actual use, and it's best to set it up separately
3. Cannot have "-" in email account name

**Comment by dailidong** [comment]
very good! thanks!

and are you interested in submitting a pull request to resolve this issue?

**Comment by LiemLin** [comment]
Ok, I'll research the source code and try to improve it

**Comment by dailidong** [comment]
good！
please refer to [How to contribute](https://github.com/analysys/EasyScheduler/issues/310)
Look forward to your good news！

**Comment by LiemLin** [comment]
Ok，thanks!

**Comment by LiemLin** [comment]
Issue repair results：
1. The parameter mail.smtp.ssl.trust is not supported --Fixed and tested
2. The mailSender in PasswordAuthentication() and setFrom() may not be the same in actual use, and it's best to set it up separately  --Fixed and tested
3. Cannot have "-" in email account name  --It has been fixed in 1.1.0

Help grant permissions for push request @dailidong

**Comment by LiemLin** [comment]
An improvement to this issue has been submitted to pull request #746
