### ISSUE TITLE
[BUG] API Document error(swagger html)[swagger文档错误]

### ISSUE THREAD

**Issue by hujiang75277381** [apache/incubator-dolphinscheduler#731]
An error was found.
Interface path:/escheduler/projects/{projectName}/process/batch-delete
Problem Description: there is no  swagger annotation at the corresponding code

---
发现了1个错误
接口路径:/escheduler/projects/{projectName}/process/batch-delete
问题描述：我查看了对应代码并没有swagger 注解

**Comment by dailidong** [comment]
could you submit a pull request to fix this problem? thanks!

**Comment by dailidong** [comment]
done
