### ISSUE TITLE
[Feature]User management integrated with LDAP(集成LDAP的用户管理)

### ISSUE THREAD

**Issue by phoenixhadoop** [apache/incubator-dolphinscheduler#736]
We hope that dolphin scheduler can integrate LDAP user management and divide administrators and ordinary users according to group. Thank you

----

希望DolphinScheduler能够集成LDAP的用户管理，可以根据group来划分管理员和普通用户，谢谢

**Comment by dailidong** [comment]
good，we will consider this feature！

**Comment by data-yangmengfei** [comment]
Hello, I want to implements this feature, and will complete it next week

**Comment by dailidong** [comment]
> Hello, I want to implements this feature, and will complete it next week
How is it going？haha

**Comment by phoenixhadoop** [comment]
Thanks. 
You are great !

**Comment by dailidong** [comment]
> Hello, I want to implements this feature, and will complete it next week

How is it going？

**Comment by geosmart** [comment]
> Hello, I want to implements this feature, and will complete it next week

How is it going？

**Comment by geosmart** [comment]
I will finish ldap feature in this week (deadline:20200906)
