### ISSUE TITLE
权限管理

### ISSUE THREAD

**Issue by lihongyu666** [apache/incubator-dolphinscheduler#745]
**Describe the solution you'd like**
目前 我们的想法：
1、实现基于角色的权限控制（RBAC）
2、增加资源版本控制
![image](https://user-images.githubusercontent.com/41414514/64500120-7a744380-d2ee-11e9-8c8d-f3c8224492ae.png)

**Comment by dailidong** [comment]
very good！ thx！
and If anybody else also interesting in this issue，please leave a message！

**Comment by CalvinKirs** [comment]
please see #1333
