### ISSUE TITLE
Log desensitization(日志脱敏)

### ISSUE THREAD

**Issue by lihongyu666** [apache/incubator-dolphinscheduler#747]
Version: Version 1.1.0
Run a hive sql task. View the log. Found at the log of the print data source information. The password is also printed in clear text.
Because our company hive data source is open ldap certification. So if this password is leaked, it can be used in various places. Feeling not particularly safe
Whether to consider the log for desensitization. Avoid authorized projects but data sources are not authorized. Others see sensitive information such as passwords from the logs

---
版本：1.1.0版本
跑一个hive sql任务。查看log。发现在打印数据源信息的log处。密码也随之明文打印。
因我们公司hive数据源是打通ldap认证的。所以此密码如果一旦泄漏 就可使用各种地方了。感觉不是特别安全
是否考虑日志做脱敏处理。避免授权项目但数据源未授权情况下。他人从日志看到密码等敏感信息

**Comment by dailidong** [comment]
very good, we will fix it later!
or maybe you can fix it ,then contribute!

**Comment by Yeleights** [comment]
i will fix it
