### ISSUE TITLE
[Feature] database adaptation

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#756]
supports postgresql by default, while supporting other dbs

**Comment by qiaozhanwei** [comment]
#691

**Comment by qiaozhanwei** [comment]
this issue also includes database upgrade script adaptation

**Comment by dudiao** [comment]
这个是指元数据存放的数据库吗？我看现在是MySQL，支持其他的数据库都是有哪些啊？现在进度如何

**Comment by dailidong** [comment]
yes，the first apache verison 1.2.0 will support multi database, like Postgre、Mysql and so on.

**Comment by dailidong** [comment]
@dudiao , and the process you can subscribe developer mail list, please refer: #1278
