### ISSUE TITLE
[Feature]can deploy by war mode?(是否支持war方式部署)

### ISSUE THREAD

**Issue by wangwenjia1981** [apache/incubator-dolphinscheduler#758]
Excuse me, does it support war mode deployment? My current client method requires deployment to IBM's was server and needs to be deployed in war mode.

---
请问，是否支持war方式部署，我现在的客户方式要求部署到IBM的was服务器上的，需要以war方式部署。

**Comment by dailidong** [comment]
not support！ 
maybe you can update MasterServer.java、ApiApplicationServer.java to war！ 
but other service like WorkerServer、AlertServer、LoggerServer are only java program, so I can't confirm  this will work fine!
