### ISSUE TITLE
Change contact channel to mail list and github issue.

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-dolphinscheduler#767]
We need to change the contact channels(https://github.com/apache/incubator-dolphinscheduler#get-help) to Apache preferred ways.
1. GitHub
1. Mail list(dev)
1. Apache Slack, dolphinscheduler channel if you want.
1. Chinese, wechat or other you prefer.

**Comment by dailidong** [comment]
good idea！thx！
I see this idea has been done，we close this issue，haha
