### ISSUE TITLE
[Feature]能否听一下hive客户端版本的配置

### ISSUE THREAD

**Issue by hujian219** [apache/incubator-dolphinscheduler#772]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
我们现有的大数据平台已经稳定运行一段时间了，目前的hive版本是1.1  而dolphinscheduler 是2.1  这样就不能很好的进行兼容，如果单个替换jar包 可能会引起其他问题，所以能否提供一个 可配置hive版本项，以平滑的接入各个生产环境

**Comment by dailidong** [comment]
we will consider this feature in the future! thx! 
for now ,we don't have enough time to do this!

**Comment by dailidong** [comment]
please udpate/add title and description in English for better global communication!

**Comment by JunjianS** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 我们现有的大数据平台已经稳定运行一段时间了，目前的hive版本是1.1 而dolphinscheduler 是2.1 这样就不能很好的进行兼容，如果单个替换jar包 可能会引起其他问题，所以能否提供一个 可配置hive版本项，以平滑的接入各个生产环境

i replaced hive2.0 jars with 1.0，it works 

hive-common-1.1.0-cdh5.15.2.jar
hive-exec-1.1.0-cdh5.15.2.jar
hive-jdbc-1.1.0-cdh5.15.2.jar
hive-metastore-1.1.0-cdh5.15.2.jar
hive-serde-1.1.0-cdh5.15.2.jar
hive-service-1.1.0-cdh5.15.2.jar
