### ISSUE TITLE
[Feature] table name modify

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#776]
Because the project name was modified by EasyScheduler to DolphinScheduler, the original table name was preceded by t_escheduler, and now the table name is modified for comments.

因为项目名由EasyScheduler修改为了DolphinScheduler，原先表名之前都是t_escheduler开头，现在表名修改征求大家意见

**Comment by khadgarmage** [comment]
https://github.com/alibaba/p3c/blob/master/p3c-gitbook/MySQL%E6%95%B0%E6%8D%AE%E5%BA%93/%E5%BB%BA%E8%A1%A8%E8%A7%84%E7%BA%A6.md

**Comment by lyf198972** [comment]
t_ds开头就挺好的

**Comment by leow3811** [comment]
t_ds sounds good , d means  dolphin  and s means scheduler
