### ISSUE TITLE
add the port function when automating the deployment, because ssh may not use the default port number 22, it should be used as a configurable item.

### ISSUE THREAD

**Issue by 865357384** [apache/incubator-dolphinscheduler#780]
add the port function when automating the deployment, because ssh may not use the default port number 22, it should be used as a configurable item

**Comment by dailidong** [comment]
good idea!
could you submit a pr to implement this feature?

**Comment by chengshiwen** [comment]
Close the issue since `sshPort` has been supported in 1.3.x
