### ISSUE TITLE
[BUG] When a task is executed through an API call, the result returns MSG :success, but the task is not actually executed.

### ISSUE THREAD

**Issue by chenyuan9028** [apache/incubator-dolphinscheduler#781]
version：1.1.0
problem：When a task is executed through an API call, the result returns MSG :success, but the task is not actually executed.
![image](https://user-images.githubusercontent.com/30412237/64586679-a9161b00-d3cf-11e9-8e92-98d2cdd275c1.png)

In this case, by calling the API to execute the task, it is not known whether the task is actually executed or not, and it is not known which instance you just ran by looking for the task instance, because the same task can have multiple instances running at the same time.
So how exactly do you get an instance of an execution?

这情情况下，通过调用api去执行任务就不知道任务是否真的被执行了，及时通过任务实例去找也不知道哪个实例才是你刚才跑的，因为同一任务可以有多个实例同时处于运行的状态。
那怎么能够准确的获取某次执行的的实例呢？

**Comment by wu-sheng** [comment]
Please begin to use English as the only language in the mail list and GitHub.

**Comment by qiaozhanwei** [comment]
This interface is the startup process instance interface, just insert a command into the Command table, indicating that the startup is successful. Not the process execution was successful. Process execution successfully monitors process status

这个接口是启动流程实例接口，只是将插入到Command表中一条命令，说明启动成功了。不是流程执行成功了。流程执行成功得监控流程状态

**Comment by chenyuan9028** [comment]
So how I can know which processInstance is what I just run？ because there may be more than one 
processInstance running at the same time in a same processDef.
@qiaozhanwei 
那我怎么知道哪个运行的任务实例才是我刚才执行的呢。因为同一个任务同一时间可能有多个正在运行的实例
