### ISSUE TITLE
[DISCUSSION] About the impact of the escheduler database rename on existing users(关于escheduler数据库改名对已有使用者造成的影响)

### ISSUE THREAD

**Issue by chenyuan9028** [apache/incubator-dolphinscheduler#782]
Congratulations to easyscheduler for becoming an Apache incubator and officially changing its name to Dolphinscheduler.
Recently, in the community WeChat group, the name of the database needs to be replaced due to the name change. In view of the current use of Dolphinscheduler, list the points that may be affected, so that the Dolphinscheduler development team can consider the compatibility of such usages in the future. .
(1) For the interaction with the escheduler database in the program, the renaming of the database and the table will directly affect the operation of the program;
(2) The path given by the official interface document before escheduler is the beginning of /escheduler. If the path prefix is ​​also changed, if the change is made, the previous api operation will be affected.
(3) Some constants in the source code use ESCHEDULER/escheduler as a prefix. Will this department change? If you change it, the programs that rely on these sources will also have an impact.

The above is just thought of the situation that the individual is currently using. There must be some omissions. Perhaps the official team in these places has already considered it. I hope that after the name change, I can try to upgrade as easily as I can now.

Thank you for the contribution of the Dolphinscheduler team, I wish Dolphinscheduler to become an official Apache project soon!

---

恭喜easyscheduler成为Apache孵化项目，并正式更名为Dolphinscheduler.
最近在社区微信群里看到由于更名导致数据库名称也需要更换，鉴于目前对于Dolphinscheduler的使用，列一下可能会影响的点，以便Dolphinscheduler开发团队在以后发板时能考虑这类些用法的兼容性。
(1) 对于在程序里面已经和escheduler数据库做了交互的，数据库及表的改名会直接影响到程序的运行；
(2) escheduler之前的官方接口文档给出的路径中都是/escheduler开头的，这个路径前缀是不是也需要更改，如果改了的话，之前的api操作都会受影响；
(3) 源码里有些常量使用ESCHEDULER/escheduler作为前缀，这部门会更改么？如果更改的话，已经使用了依赖了这些源码的程序也会造成影响。

以上只是就个人目前所用的情况想到的，肯定还有遗漏的地方，也许这些地方官方团队也已经考虑到了，那希望在改名后的发版，能够尽量做到像现在一样方便升级。

谢谢Dolphinscheduler团队的贡献，祝Dolphinscheduler早日成为Apache正式项目！

**Comment by wu-sheng** [comment]
> The above is just thought of the situation that the individual is currently using. There must be some omissions. Perhaps the official team in these places has already considered it. I hope that after the name change, I can try to upgrade as easily as I can now.

All these discussions are very project related, please move to dev@ mail list.

> Thank you for the contribution of the Dolphinscheduler team, I wish Dolphinscheduler to become an official Apache project soon!

It is an official Apache incubator project, just not a top level project. It will be a long journey for the whole community.

**Comment by gaojun2048** [comment]
very very good advice!  thanks for a lot!

and as our champion said,  please use english describe the issue!   thanks again!

**Comment by chenyuan9028** [comment]
> > The above is just thought of the situation that the individual is currently using. There must be some omissions. Perhaps the official team in these places has already considered it. I hope that after the name change, I can try to upgrade as easily as I can now.
> 
> All these discussions are very project related, please move to dev@ mail list.
> 
> > Thank you for the contribution of the Dolphinscheduler team, I wish Dolphinscheduler to become an official Apache project soon!
> 
> It is an official Apache incubator project, just not a top level project. It will be a long journey for the whole community.

where is dev@mail list?

**Comment by gaojun2048** [comment]
you can send email to `dev-subscribe@dolphinscheduler.apache.org ` to subscribe the development information about dolphinscheduler!

**Comment by gaojun2048** [comment]
#776    
@lgcareer  when update easyscheduler(include table name) to dolphinscheduelr,  please consider `backward compatibility ` and this advice, thanks!

**Comment by Yeleights** [comment]
lgcareer fix it
