### ISSUE TITLE
[Feature] non-final process instances cannot be deleted

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#784]
Non-final process instances cannot be deleted. Only process instances that are successful, failed, stopped, or suspended can be deleted. If you want to delete a running instance, convert the process instance to the final state

非终态的流程实例不可以删除，只能对成功，失败，停止，暂停的流程实例进行删除。如果要对正在运行的实例进行删除，请将流程实例转换为终态

**Comment by gaojun2048** [comment]
good feature!

**Comment by qiaozhanwei** [comment]
@break60
