### ISSUE TITLE
正常运行的工作流的定时按钮就不能点击了，原先的定时管理任务也看不到任何已设置任务

### ISSUE THREAD

**Issue by LeonTing** [apache/incubator-dolphinscheduler#785]
v1.1.0版本上正常运行的工作流的定时按钮就不能点击了，原先的定时管理任务也看不到任何已设置任务

**Comment by qiaozhanwei** [comment]
Is it the scheduling that is deployed under the docker?
If this is the problem, first locate it to see if the table in the database is enough. Is it 38 tables?
About timing:
First, the process definition can only be in the online state to set a timing.
Secondly, if the t_escheduler_scheduler table is not associated with the current process definition, it will not be displayed.
If I still can't solve your problem, you can take a screenshot to illustrate the situation.


是在群里提的哪个docker下部署的调度吗？
如果是这个问题，先定位一下看看数据库中的表是不是够，是38张表吗？
关于定时：
首先流程定义只能是处于上线状态才能设置一个定时
其次如果t_escheduler_scheduler表如果和当前的流程定义关联不起来也显示不出来
如果我说的还是不能解决你的问题，可以截图说明情况

**Comment by dailidong** [comment]
long long time no update, I will close this issue
