### ISSUE TITLE
[需求] 组件之间传递参数

### ISSUE THREAD

**Issue by zhucl1986** [apache/incubator-dolphinscheduler#786]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by qiaozhanwei** [comment]
We have included this feature in our project requirements confirmation, and we hope that the brother contribution code will implement this feature.

我们已经将此功能列入我们的项目需求确认中，也希望兄弟贡献代码实现此功能

**Comment by jxauwxj** [comment]
需求：A执行完后，执行B，如果要将A的参数传给B。
方案：A执行完后，需要传递保存到运行参数表中，B在执行之前，从运行参数表中取到参数，通过context传给B

**Comment by yangjiajun2014** [comment]
我们的DAG调度系统传参也是通过保存到context的方式，所有后面的节点可以依赖引用所有前面节点的输出

**Comment by jxauwxj** [comment]
> 我们的DAG调度系统传参也是通过保存到context的方式，所有后面的节点可以依赖引用所有前面节点的输出

思路都是一样的，先把参数保存起来，要用的时候取出来传进去

**Comment by lingfei87** [comment]
> We have included this feature in our project requirements confirmation, and we hope that the brother contribution code will implement this feature.
> 
> 我们已经将此功能列入我们的项目需求确认中，也希望兄弟贡献代码实现此功能

您好，冒昧的问下，这个功能实现了吗？

**Comment by 1445103710** [comment]
例如直接使用${节点名}获取其他组件的参数？每个组件设置可保留其获取的参数。这样可以自主选择要不要保留组件参数

**Comment by dailidong** [comment]
Duplicate of https://github.com/apache/incubator-dolphinscheduler/issues/116
