### ISSUE TITLE
[BUG] many System.exit(1) in code, use exception instead or any other friendly actions? 

### ISSUE THREAD

**Issue by coding-now** [apache/incubator-dolphinscheduler#788]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
  many System.exit(1) in code, use exception instead or other any other friendly actions? 
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26567069/64750760-8cebb880-d54c-11e9-9e7e-6fdbb7b6c2d1.png)
**Which version of Easy Scheduler:**
 -[1.0.4]

**Additional context**

**Requirement or improvement
many System.exit(1) in code, use **exception** instead or any other friendly actions to proceed? 

项目代码中，多处使用System.exit(1），能不能用异常替代或者其他更好的处理方式，
进程默默的退出了，日志中发现不了异常日志，可用性不友好。

**Comment by qiaozhanwei** [comment]
We will reconsider this issue, and of course we hope that the brothers will submit the pr solution.

我们将会重新考虑这个问题，当然也希望兄弟提交pr解决

**Comment by wangshu-zhouyunfan** [comment]
Can you assign this issue to me？

**Comment by wangshu-zhouyunfan** [comment]
I want to implement this feature

**Comment by qiaozhanwei** [comment]
OK，thx
