### ISSUE TITLE
[Feature] Can we add support for Datax components to better transform data？

### ISSUE THREAD

**Issue by wangshu-niguang** [apache/incubator-dolphinscheduler#790]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dailidong** [comment]
good idea!  
datax has so many dependencies, datax maybe supported through task plugin, we will implement task plugin feature later!

**Comment by jxauwxj** [comment]
需求是无尽的，每个公司都有自己的业务，有不同的组件，dolphinsheduler 应该提供一种插件扩展机制，让用户能自己编写、上传插件。dolphinsheduler 框架只要做好对插件的生命周期管理即可。比如：启动任务、停止任务等等。

**Comment by Yeleights** [comment]
wenhemin add the datax task
