### ISSUE TITLE
能不能建个微信群？

### ISSUE THREAD

**Issue by tswstarplanet** [apache/incubator-dolphinscheduler#794]
能不能建个微信群啊？有些问题感觉提issue也不太合适，微信群里讨论可能更合适点

**Comment by William-GuoWei** [comment]
Apache 要求使用邮件或者git讨论，有微信群，但是逐步在引导到邮件列表里，你可以发任意邮件去订阅dev-subscribe@dolphinscheduler.apache.org和notifications-subscribe@ dolphinscheduler.apache.org，就可以参与讨论，我们开发者都在积极回复的。

We did have a Wechat group, but we are transferring users to mail group: dev-subscribe@dolphinscheduler.apache.org和notifications-subscribe@ dolphinscheduler.apache.org,
our team member is answering the question in the mail group.
