### ISSUE TITLE
[Feature]Can add support for alpine linux

### ISSUE THREAD

**Issue by hanxirui** [apache/incubator-dolphinscheduler#795]
alpine linux是在Docker中使用较多的系统, 而Docker是系统部署的未来,希望能增加对alpine linux的支持.

**Comment by dailidong** [comment]
good idea, please update description to English, thank you!

**Comment by chengshiwen** [comment]
@hanxirui 
We published the first official docker image based on alpine linux some days ago, you can install it following the doc: [https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html](https://dolphinscheduler.apache.org/zh-cn/docs/1.3.4/user_doc/docker-deployment.html)

@dailidong Please close this pr
