### ISSUE TITLE
[Feature] support etcd v3 as an alternative to zookeeper

### ISSUE THREAD

**Issue by Baoqi** [apache/incubator-dolphinscheduler#797]
**Is your feature request related to a problem? Please describe.**

Since kubernetes is very popular those days, and k8s cluster all have an etcd cluster. So, it will be very convenient if we also support use ETCD, so use can choose either zookeeper or etcd. Only support ETCD v3 will be fine (no need to support v2).

And manage a distributed zookeeper or etcd are very hard, so in k8s, it will be hard to maintaince both zookeeper and etcd.

**Describe the solution you'd like**

**Describe alternatives you've considered**
zetcd may works as it simulates zookeeper API over etcd, but it need to start an additional server.

**Additional context**
Currently, I'm not familiar with etcd, so first log this issue, and check whether there are similary demands from other people

**Comment by dailidong** [comment]
good idea!

**Comment by CalvinKirs** [comment]
We have started related work #3961
