### ISSUE TITLE
[Feature] Parameters between nodes

### ISSUE THREAD

**Issue by pbadeager** [apache/incubator-dolphinscheduler#800]
**Is your feature request related to a problem? Please describe.**
when i define a workflow of a lot of nodes, and these nodes need the parameters as input data, and will push some data as output for other nodes.
now , i get the parameters from filesystem. and i put the data to filesystem when i want to send something to other nodes.

**Describe the solution you'd like**
1. Set the data parameters passed between whole workflow.
2. there are need Two types.  One is protected and cannot be modified in the whole workflow after setting.
    and another type is read-write for every nodes in whole workflow, any node can modify , and other nodes can sync data quickly.

**Comment by qiaozhanwei** [comment]
#786
