### ISSUE TITLE
在线文档中 码云下载链接更新

### ISSUE THREAD

**Issue by lyonggee** [apache/incubator-dolphinscheduler#805]
码云的easyscheduler改成了 dolphin scheduler ，需要同步更新github的码云下载链接

**Comment by dailidong** [comment]
thank you！
please update this issue to English!

**Comment by qiaozhanwei** [comment]
Please visit this address https://github.com/apache/incubator-dolphinscheduler/releases，Please visit this address,

**Comment by qiaozhanwei** [comment]
Please visit this address https://github.com/apache/incubator-dolphinscheduler/releases，Future Apache version, apache will give us the warehouse
