### ISSUE TITLE
[BUG] dev 1.1.0 数据库脚本不同步.

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#807]
执行初始化脚本:
 sh ./script/create_escheduler.sh

报错:   t_escheduler_version 表找不到.

手动创建一个t_escheduler_version表之后,  里面版本设置为 1.1.0

创建用户界面报错:

![image](https://user-images.githubusercontent.com/39816903/65123140-363b1e80-da25-11e9-886e-96c3cb97d4d4.png)

添加任务时报错

![image](https://user-images.githubusercontent.com/39816903/65123159-405d1d00-da25-11e9-9f47-7dd4bd98e8dd.png)

需要一份完整可用的数据库初始化脚本.

**Comment by ww1516123** [comment]
目前我测试的 直接Build 执行的没问题
