### ISSUE TITLE
Web server failed to start. Port 8080 was already in use.

### ISSUE THREAD

**Issue by barntt77** [apache/incubator-dolphinscheduler#809]
![image](https://user-images.githubusercontent.com/54257101/65126137-40f7b280-da29-11e9-9208-43c6b9ce1206.png)
![image](https://user-images.githubusercontent.com/54257101/65126209-49e88400-da29-11e9-8876-11cbcc1e0d37.png)
Master server was died after started the server
I used .tar profile to install escheduler1.1.0 ,Not source code compilation
How to slove this question

**Comment by mchcz** [comment]
1.请确认application.properties中8181端口是否被占用，如果没有请看第二点。
2.请确认nginx配置文件中，和调度系统映射的端口是否被占用，如下图所示：
![image](https://user-images.githubusercontent.com/18095523/65129910-dfd2dd80-da2e-11e9-9b65-12d7bdf1c79d.png)
If the error is still reported, please provide more error information.

**Comment by barntt77** [comment]
![image](https://user-images.githubusercontent.com/54257101/65134335-b6b64b00-da36-11e9-8019-0628f60de5af.png)
![image](https://user-images.githubusercontent.com/54257101/65134379-c9c91b00-da36-11e9-8a88-bceca546a7cd.png)
![image](https://user-images.githubusercontent.com/54257101/65134462-e9604380-da36-11e9-9638-a91a4e1cd5c3.png)
port 8181 is in application,but is not be occupied. I can sign in Escheduler and run tasks
but this node’s master server will die
![image](https://user-images.githubusercontent.com/54257101/65135819-275e6700-da39-11e9-8875-a247df5c4c24.png)

I set master server in 2 nodes，but now i could see 1 alived

**Comment by iamnotgay** [comment]
ui 端口占用可以在启动的时候 指定端口

**Comment by barntt77** [comment]
> ui端口占用可以在启动的时候指定端口
> 后端服务端口专业可以在conf下配置对应服务，server.port = 8081

ui端 nginx已重新设置端口，且可以正常启动
后端在conf下重新设置端口server.port = 7171，
但是问题在于 一个节点的master服务启动完后 半分钟就自动挂，日志显示8080端口被占用。
监控中心master只显示一台，我配了两台
![image](https://user-images.githubusercontent.com/54257101/65294756-c302eb00-db91-11e9-983e-384275b02604.png)
