### ISSUE TITLE
关于部署上的问题

### ISSUE THREAD

**Issue by AmourST** [apache/incubator-dolphinscheduler#814]
大数据集群环境：hadoop+hive+spark
需求：可以实现执行hive sql任务进行ETL
疑问：是不是需要与大数据集群部署在一块？还是要独立部署？

**Comment by jxauwxj** [comment]
> 大数据集群环境：hadoop+hive+spark
> 需求：可以实现执行hive sql任务进行ETL
> 疑问：是不是需要与大数据集群部署在一块？还是要独立部署？

如果你用jdbc执行hive sql，啥也不需要。
如果你用hive的客户端来执行hive sql，在hive所在机器，安装worker就ok了。

**Comment by AmourST** [comment]
> > 大数据集群环境：hadoop+hive+spark
> > 需求：可以实现执行hive sql任务进行ETL
> > 疑问：是不是需要与大数据集群部署在一块？还是要独立部署？
> 
> 如果你用jdbc执行hive sql，啥也不需要。
> 如果你用hive的客户端来执行hive sql，在hive所在机器，安装worker就ok了。

工具栏的【SQL图标】代表的任务是jdbc执行hive sql，还是hive客户端执行sql，怎么区别？
