### ISSUE TITLE
[BUG]   Database initialization error

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#822]
run  CreateDolphinScheduler error

Reason:

/sql/create/release-1.0.0_schema/mysql/dolphinscheduler_ddl.sql 
miss  table `t_escheduler_version`

![image](https://user-images.githubusercontent.com/39816903/65212670-b28d3a80-dad5-11e9-8135-baa19cfc8c53.png)

**Comment by iamnotgay** [comment]
建议使用  脚本初始化
