### ISSUE TITLE
[BUG]  CreateDolphinScheduler upgrade database error

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#823]
![image](https://user-images.githubusercontent.com/39816903/65213322-4e1faa80-dad8-11e9-9b6f-73570f51ae85.png)

**Comment by qiaozhanwei** [comment]
Please do not use dev sql upgrade, but also under development
For normal use, please use release1.1.0

请不要使用dev的sql升级，还正在开发中
正常使用请使用release1.1.0
