### ISSUE TITLE
dolphin如何避免巨量节点任务导致DAG图过于复杂的问题

### ISSUE THREAD

**Issue by AmourST** [apache/incubator-dolphinscheduler#825]
如题，更具体可以到，工作流A用到了任务节点a，工作流B也用到了任务节点a，那任务节点a会不会被执行2次？

**Comment by iamnotgay** [comment]
节点重复计算，会耗费多余的资源与时间，如果业务允许的话，可以进行逻辑拆分，如节点A进行数据落地，其他工作流中的节点直接读取，  仍然存在重复读取，但是避免了重复计算

**Comment by AmourST** [comment]
> 节点重复计算，会耗费多余的资源与时间，如果业务允许的话，可以进行逻辑拆分，如节点A进行数据落地，其他工作流中的节点直接读取， 仍然存在重复读取，但是避免了重复计算

那相当于节点a的下游节点必须在一个工作流中，可以这么理解吗？
节点a下有20个节点，这20个节点又各有自己的子节点，那不就节点膨胀，DAG图变得庞大无比，给运维和可视来说，都造成巨大的障碍

**Comment by iamnotgay** [comment]
对是这个样子，从我理解来看，不同的工作流 节点执行时间节点也不同，节点执行 状态复用  时间界限也不好界定，或许 从多个维度去实现一个 执行策略 会好一些

**Comment by AmourST** [comment]
> 对是这个样子，从我理解来看，不同的工作流 节点执行时间节点也不同，节点执行 状态复用 时间界限也不好界定，或许 从多个维度去实现一个 执行策略 会好一些

那也太差了，单个节点只需要关注自己的上游就好了，一个工作流包含上千个节点，高效运维都不现实了
