### ISSUE TITLE
[DISCUSSION]Add CI/CD to the pull request process

### ISSUE THREAD

**Issue by khadgarmage** [apache/incubator-dolphinscheduler#826]
**Is your feature request related to a problem? Please describe.**
Our project has no ci process to guarantee quality. The following problems may occur, the compilation fails, the deployment fails, the test cases are not enough, the code is not standardized, the code hides some bugs, and so on.

**Describe the solution you'd like**

I referred to other open source projects, summarized them, and drew a sketch, as follows:
![image](https://user-images.githubusercontent.com/19790273/65220338-20912c00-daed-11e9-8d6a-2c41c5dfdcf4.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by dailidong** [comment]
good job!

does anyone else have suggestions about this?

**Comment by BiStarTechnology** [comment]
Hello,

Could we have a demo for a pr?

**Comment by khadgarmage** [comment]
i want to implentment this feature. @dailidong

**Comment by khadgarmage** [comment]
close it and create a root issue
