### ISSUE TITLE
[question] ./script/create_escheduler.sh: line 21: /bin/java: No such file or directory

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#827]
./script/create_escheduler.sh: line 21: /bin/java: No such file or directory

是需要配置环境变量  配置 classpath吗

**Comment by ww1516123** [comment]
cd $ESCHEDULER_HOME
$JAVA_HOME/bin/java $exec_command
you just set JAVA_HOME.

**Comment by iamnotgay** [comment]
谢谢 找到问题了，没设置 JAVA_HOME
