### ISSUE TITLE
建议增加可以访问指定linux 服务器上的脚本并配置定时任务的功能。[Feature]

### ISSUE THREAD

**Issue by liumingning** [apache/incubator-dolphinscheduler#828]
有些场景下，我们写的shell 脚本就在指定的服务器上，希望通过一个web访问这些服务器的脚本，然后把这些脚本文件形成DAG 任务，然后定时调度这些DAG 任务。

**Comment by dailidong** [comment]
for now , you already can do this, because we have supported executing task on the special machine(you can set up worker group) from version 1.1.0, then set task executed by this worker group which includes your machines!

by the way, please update/add title and description in English , thx!
