### ISSUE TITLE
如何把项目拉取到本地，并且运行起来 

### ISSUE THREAD

**Issue by fcyongji163com** [apache/incubator-dolphinscheduler#833]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by BoYiZhang** [comment]
you can checkout  version dev1.1.0

Follow 

https://analysys.github.io/easyscheduler_docs_cn/


![image](https://user-images.githubusercontent.com/39816903/65289854-0869ed00-db7f-11e9-8c69-afbb2c44df1e.png)

**Comment by fcyongji163com** [comment]
谢谢，我想从git上把代码拉取到本地，并修改代码从新提交，这个流程是怎么弄呢

**Comment by qiaozhanwei** [comment]
please read https://github.com/apache/incubator-dolphinscheduler/blob/dev/CONTRIBUTING.md doc
