### ISSUE TITLE
[Feature]  ADD new message queue components

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#836]
建议新增消息队列组件，方便与其他业务系统交互

It is recommended that new message queue components be added to facilitate interaction with other business systems.

**Comment by dailidong** [comment]
good idea,
please update or add description in English for global users！
thank you！

**Comment by lynchlee** [comment]
+1 mark

**Comment by gabrywu** [comment]
@iamnotgay Could you give more descriptions?
