### ISSUE TITLE
[BUG] start_all.sh execute failed

### ISSUE THREAD

**Issue by zhoushuoqi22** [apache/incubator-dolphinscheduler#838]
**Describe the bug**
在使用start_all.sh时，因为是ssh调用escheduler-daemon.sh，所以无法获取系统变量，导致服务无法启动

**Requirement or improvement**
希望在escheduler-daemon.sh中，source一下配置文件。比如`. /etc/profile`

**Comment by dailidong** [comment]
please add description(title) in english! thank you!

**Comment by qiaozhanwei** [comment]
Is export JAVA_HOME=$JAVA_HOME Can't find JAVA_HOME?

是 export JAVA_HOME=$JAVA_HOME 找不到JAVA_HOME吗？

**Comment by zhoushuoqi22** [comment]
> Is export JAVA_HOME=$JAVA_HOME Can't find JAVA_HOME?
> 
> 是 export JAVA_HOME=$JAVA_HOME 找不到JAVA_HOME吗？

是的,这里获取不到ssh机器的环境变量。需要在使用JAVA_HOME前面，source一下

**Comment by chengshiwen** [comment]
Close since it has been resolved in latest version
