### ISSUE TITLE
Spark task component only support spark1.X using sprak-submit, not suitable for spark2

### ISSUE THREAD

**Issue by Yeleights** [apache/incubator-dolphinscheduler#839]
**Spark task submit can specify the spark version**
Spark task component only support spark1.X using sprak-submit, not suitable for spark2

**add the spark version selector to specify the spark version**
In 1.1.0, shell component can submit spark2  job

**Comment by dailidong** [comment]
add a picture or add some log info for us to see what the problem?

**Comment by qiaozhanwei** [comment]
OK, we will consider the Spark and MR task multi-version problem solution, and we are very welcome to contribute this feature.

我们会考虑Spark和MR任务多版本问题解决方案，也非常欢迎能贡献此功能

**Comment by Yeleights** [comment]
i will do this job, through env file to get spark exec path

**Comment by Yeleights** [comment]
merge to dev~
