### ISSUE TITLE
[BUG] 中文文档中看到，创建租户会自动在worker上创建linux用户，但在实际的使用中，并没有创建 

### ISSUE THREAD

**Issue by AmourST** [apache/incubator-dolphinscheduler#844]
如题

**Comment by dailidong** [comment]
good job,
please update or add description in English for global users！
thank you！

**Comment by qiaozhanwei** [comment]
When the worker executes, it checks whether there is this tenant on Linux, that is, the corresponding user on linux, whether it exists, if it does not exist, it is created, and the tenant (the corresponding user on linux) exists with sudo -u tenant sh xxx .command for task submission

会在worker执行的时候，检查linux上是否存在此租户，也就是对应的linux上的用户，是否存在，不存在则创建，存在则用此租户（linux上对应的用户）sudo -u 租户 sh xxx.command进行任务提交
