### ISSUE TITLE
[BUG] 启动异常后存在、启动日志不完善的情况

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#846]
![image](https://user-images.githubusercontent.com/19225068/65371332-393c4600-dc95-11e9-8982-b9cdd646e8dd.png)
![image](https://user-images.githubusercontent.com/19225068/65371357-6688f400-dc95-11e9-96a9-34c2f308cb6a.png)

**Comment by dailidong** [comment]
very good ,
please first update or add description in English for global users！
thank you！

**Comment by qiaozhanwei** [comment]
May be occupied by the port
Remove nohup, then open the master_logback.xml STDOUT console output, take a look at the log output

可能是端口占用了
去掉nohup，然后打开master_logback.xml STDOUT控制台输出，执行一下看看日志输出

**Comment by iamnotgay** [comment]
When I switch to script and start is OK by script
