### ISSUE TITLE
[BUG] fastjson版本过低，存在安全漏洞

### ISSUE THREAD

**Issue by iture123** [apache/incubator-dolphinscheduler#847]
ds目前使用较低版本fastjson 1.2.29。fastjson历史上多次暴露了安全问题，存在远程代码执行漏洞，建议替换为gson或者升级到最新版本。

**Comment by dailidong** [comment]
good idea, 
please update or add description in English for global users！
thank you！

**Comment by qiaozhanwei** [comment]
#854 fix this bug
