### ISSUE TITLE
[Feature]项目授权过粗，结合问题#848查看

### ISSUE THREAD

**Issue by AmourST** [apache/incubator-dolphinscheduler#849]
绝大多数的情况下，项目只是依赖另一个项目的某个工作流，全项目的赋权，失去了对项目其他工作流的保护；
同时，应该加入【操作权限概念】，工作流授权后，应新增｛读/写/｝权限分别，避免他人修改工作流

**Comment by dailidong** [comment]
update or add description in English！thank you！

**Comment by qiaozhanwei** [comment]
Our permission granularity is really thick
For the authorization of resources, data sources, projects, and UDFs, even if they are granted to others, other people currently have only read and write permissions and no delete permissions. Delete permissions can only be deleted by the owner and administrator

我们的权限粒度确实比较粗
对于资源、数据源、项目和UDF的授权，就算授予给的其它人，其它人目前也只有读、写权限，没有删除权限。删除权限只有所有者和管理员才可以删除

**Comment by CalvinKirs** [comment]
please see #1333 
Focus on #1333 discussion
