### ISSUE TITLE
[Bug]当两个人同时登陆admin账户的时候，其中一个人退出账户之后，另一个也会被迫退出

### ISSUE THREAD

**Issue by AmourST** [apache/incubator-dolphinscheduler#850]
如题

**Comment by AmourST** [comment]
测试了，其他普通用户也是一样

**Comment by dailidong** [comment]
add description in English！thank you！

**Comment by qiaozhanwei** [comment]
Which version?
In theory, there is no such problem, support the same user to log in multiple places, if there are still problems, you can take a screenshot

哪个版本？
理论上是没有这个问题的，支持同一个用户多处登录，如果还有问题，可以截图

**Comment by qiaozhanwei** [comment]
Exiting the account means clicking the "Exit" button on the user?
If this is the case, the session is invalidated and deleted. The login of the same user elsewhere will also exit. This is no problem.

退出账号，是指点击了用户上的“退出”按钮了吗？
如果是这样，是将session失效，删除了，同一个用户其它地方的登录也会退出，这是没有问题的

**Comment by AmourST** [comment]
> Exiting the account means clicking the "Exit" button on the user?
> If this is the case, the session is invalidated and deleted. The login of the same user elsewhere will also exit. This is no problem.
> 
> 退出账号，是指点击了用户上的“退出”按钮了吗？
> 如果是这样，是将session失效，删除了，同一个用户其它地方的登录也会退出，这是没有问题的
version 1.1.0
yes ,i click the "Exit" button
i think this strategy is not reasonable which will bring inconvenience to account-sharing

是1.1.0版本
是点击“退出”
这种策略，我觉得是不合理的。会对帐号共享开发造成不便

**Comment by lynchlee** [comment]
Is account-sharing a feature or a bug, should we diss about this first ?
那么是不是需要讨论一下 账号共享是一个feature还是一个bug？

**Comment by KEN-LJQ** [comment]
Is there any progress of this issue? We meet this problem too. Because current pool permission management, we have to develop by account-sharing

**Comment by gabrywu** [comment]
why not open enough account? After all account is not scarce resources. And I think there is no problems to current mechanism
