### ISSUE TITLE
[BUG] HDFS-HA connect fail 

### ISSUE THREAD

**Issue by Yeleights** [apache/incubator-dolphinscheduler#852]
**When configuration HDFS-HA, connect to hdfs fail**
hdfs-site.xml and core-site.xml have been added in /conf, when i create tenant , the message show that create tenant error!
log:
java.net.ConnectException: Call From gw1.changan.com/XX.XX.XX.XX to nameservice1:8020 failed on connection exception: java.net.ConnectException: 拒绝连接;

HDFS-HA conf need the cluster hdfs-site.xml and core-site.xml, when use the namespace to connect hdfs only namespace/filepath not namespace:8020/filepath,???

Ps: How to configure the dolphinscheduler HDFS-HA~~

**Comment by qiaozhanwei** [comment]
Is configured like this
If the connection is not available, please test the HadoopUtilsTest under cn.escheduler.common.utils under the separate commons module in IDEA, and put the configuration file under resources.

是这样配置的
如果连接不上，请单独在IDEA中单独commons模块下cn.escheduler.common.utils下的HadoopUtilsTest测试，配置文件放到resources下
