### ISSUE TITLE
How to reduce incubator-dolphin scheduler front-end Vue framework base dependency packages（如何减少incubator-dolphinscheduler前端vue框架基础依赖包）

### ISSUE THREAD

**Issue by break60** [apache/incubator-dolphinscheduler#859]
At present, there are more than 850 dependency packages in the node_modules folder, among which more than 700 dependency packages are vue-based packages. We want to reduce the number of vue-based packages. We hope to have a small partner for vue-based packages and provide some solutions and suggestions.

       目前node_modules文件夹共有850多个依赖包，其中有700多个依赖包是vue自带基础包，我们想减少vue自带基础包，希望有过对vue底层基础包的小伙伴，提供一些解决方法和建议

**Comment by dailidong** [comment]
if anybody have idea about this issue，please leave a message,thx!

**Comment by khadgarmage** [comment]
vue3 在速度，体积上有优化，好像公布源码了，是不是可以参考下~~https://github.com/vuejs/vue-next

**Comment by break60** [comment]
Thank you for your feedback. We will follow up on the progress of vue3.0. At present, vue3.0 has just released the source code and is still in pre-alpha state.

**Comment by break60** [comment]
> vue3 is faster and smaller，
> Is it possible to refer to https://github.com/vuejs/vue-next

Thank you for your feedback. We will follow up on the progress of vue3.0. At present, vue3.0 has just released the source code and is still in pre-alpha state.

**Comment by break60** [comment]
solved

**Comment by break60** [comment]
solved
