### ISSUE TITLE
[BUG] jar包冲突Correct the classpath of your application so that it contains a single, compatible version of javax.servlet.ServletContext

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#860]
![image](https://user-images.githubusercontent.com/19225068/65402961-69eebd80-de04-11e9-97a9-51b9f9ec844b.png)

解决： pom排除依赖或者移除lib目录下的
lib/servlet-api-2.5-6.1.14.jar

**Comment by dailidong** [comment]
good job！ @lgcareer
