### ISSUE TITLE
[question] fail to change email receiver in SQL node

### ISSUE THREAD

**Issue by xiej23** [apache/incubator-dolphinscheduler#863]
i can't change the email receiver, where SQL result sends to.
when i type any email other than ### test@analysys.com, i find the email won't be saved.
my version is 1.0.5 both upfront and backend.
is this really a bug? or i just don't get the way to use it.

**Comment by dailidong** [comment]
which browser do you use?

**Comment by xiej23** [comment]
edge, win10

**Comment by xiej23** [comment]
> which browser do you use?

edge, win10

**Comment by xingchun-chen** [comment]
If you still have problems, please upgrade to the latest version 1.3.2
