### ISSUE TITLE
[BUG] flink stream job  yarn status is Wrong

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#865]
when i submit a flink-stream job , then kill zhe yarn job

the job  yarn status is killed  ,but scheduler is success

![image](https://user-images.githubusercontent.com/19225068/65415846-28bcd480-de29-11e9-9215-e0e1e4d04cdd.png)

![image](https://user-images.githubusercontent.com/19225068/65415775-fc08bd00-de28-11e9-8f71-882752b96d2d.png)
![image](https://user-images.githubusercontent.com/19225068/65415819-180c5e80-de29-11e9-854e-079f535ad27a.png)

**Comment by iamnotgay** [comment]
@LoveEvenWong

**Comment by LoveEvenWong** [comment]
> @LoveEvenWong

This means that you can kill a process with "yarn application - kill" instead of killing a process

**Comment by iamnotgay** [comment]
soga   thank u
