### ISSUE TITLE
project can't create log file(在本地运行项目时，做完作业，项目目录下没有相关日志文件)

### ISSUE THREAD

**Issue by asimovch** [apache/incubator-dolphinscheduler#871]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
run EasyScheduler in Mac,then run a flow finished, there is nothing logs in the log path.
(使用mac 在本地运行项目，跑完项目成功结束，在日志目录下没有相关文件，没有对日志目录做过修改)

**To Reproduce**
Steps to reproduce the behavior, for example:
1. run project;
2. run project;
3. wait for finished,and look at log file
4. nothing even directory

**Which version of Easy Scheduler:**
 -[branch-master]

**Comment by dailidong** [comment]
how to run? 
do you have logback.xml in the service[for example: escheduler-server] resource directory？

**Comment by asimovch** [comment]
> 怎么跑？
> 服务[例如：escheduler-server]资源目录中是否有logback.xml？

run with IDEA,
yes,
![1569374098717](https://user-images.githubusercontent.com/45529589/65561432-00da8780-df75-11e9-889b-40ebc0362039.jpg)
<img width="307" alt="WX20190925-091628@2x" src="https://user-images.githubusercontent.com/45529589/65561488-33848000-df75-11e9-8771-f14bf70bb6ae.png">

**Comment by elonlo** [comment]
Check if profile JVM parameters are specified at runtime
e.g.
-Dspring.profiles.active=api
![image](https://user-images.githubusercontent.com/5669148/70493911-52da8480-1b44-11ea-90db-b79803112245.png)
