### ISSUE TITLE
In workflow, three operators are allocated. The strategy continues to be executed for failure, and the third operator does not execute after the second operator fails.

### ISSUE THREAD

**Issue by userNever** [apache/incubator-dolphinscheduler#874]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
In workflow, three operators are allocated. The strategy continues to be executed for failure, and the third operator does not execute after the second operator fails

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Configuration Execution Policy：Failure to continue execution
![image](https://user-images.githubusercontent.com/55739797/65500419-dbf10080-def1-11e9-85ff-237680a011cb.png)

2. In the workflow instance, sql1 succeeds, SQL fails, and SQL3 does not execute
![image](https://user-images.githubusercontent.com/55739797/65561162-0e434200-df74-11e9-8fc7-762d0c47ee69.png)

3. Task Example Reference
![image](https://user-images.githubusercontent.com/55739797/65561168-169b7d00-df74-11e9-8736-e9d1611efbc4.png)

**Expected behavior**
After the second operator fails, the third operator should continue to execute.

**Screenshots**
Screenshots as above

**Which version of Easy Scheduler:**
 [1.0.5-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

-

**Comment by dailidong** [comment]
please update/add  title and description in English for better global communication, thx!

**Comment by userNever** [comment]
> please update/add title and description in English for better global communication, thx!



> please update/add title and description in English for better global communication, thx!

Updated

**Comment by qiaozhanwei** [comment]
失败策略不是这样理解的，是对于并行任务，如果有失败的，并行任务是继续执行还是要Kill掉
Failure strategy is not so understood. It's about parallel tasks. If they fail, do parallel tasks continue or Kill them out?

**Comment by userNever** [comment]
> 失败策略不是这样理解的，是对于并行任务，如果有失败的，并行任务是继续执行还是要Kill掉
> Failure strategy is not so understood. It's about parallel tasks. If they fail, do parallel tasks continue or Kill them out?



> 失败策略不是这样理解的，是对于并行任务，如果有失败的，并行任务是继续执行还是要Kill掉
> Failure strategy is not so understood. It's about parallel tasks. If they fail, do parallel tasks continue or Kill them out?

串行化流程的策略设置中，没有相应的忽略此节点的失败的策略，我怎么满足上述需求呢？
In the policy setting of serialization process, there is no corresponding strategy to ignore the failure of this node. How can I meet the above requirements?

**Comment by huzekang** [comment]
I have the same question about how to use failure strategy.
this is my choose when i run process.
![image](https://user-images.githubusercontent.com/18548053/81462018-45ecba80-91e2-11ea-9109-f3d4e973620e.png)
but the instance stop when first task fail. 
![image](https://user-images.githubusercontent.com/18548053/81461983-1473ef00-91e2-11ea-9e83-ac858201d5fd.png)

**Comment by huzekang** [comment]
I find the failure strategy take effect like below.
![image](https://user-images.githubusercontent.com/18548053/81462792-9ca8c300-91e7-11ea-84a7-0bcc00320b74.png)
