### ISSUE TITLE
[Feature] New display content in the task instance interface

### ISSUE THREAD

**Issue by victoryjames** [apache/incubator-dolphinscheduler#875]
1. When the data is filled, it is impossible to check which specific data date is complemented by the workflow task instance. At present, it can only be performed by viewing the log mode, and it is desired to directly reflect on the interface.
2. Host does not have to display content, generally only pay attention when troubleshooting problems, the content can be selected, the default does not show
3. Workflow instance creation wants to add attributes such as creator, modify person, etc.

**Comment by dailidong** [comment]
please update/add title and description in English for better global communication! thx!

**Comment by cconlyou** [comment]
+1
The "Task Instance" UI funcion only show "Submit & Start & End time". We need to know the "Scheduling Time" of each task instance, especially when complementing data.

**Comment by cconlyou** [comment]
By the way, I want to know if there are some concurrency limits in projects and worker nodes. If no or others policies, consider these to avoid server overload

**Comment by wenhemin** [comment]
There is a concurrency limit. You can look at the resource file.
master.properties 
worker.properties

**Comment by cconlyou** [comment]
> There is a concurrency limit. You can look at the resource file.
> master.properties
> worker.properties

Thanks~~

**Comment by chengshiwen** [comment]
Close since it has been resolved
