### ISSUE TITLE
[BUG] zh_CN.js Content repetition

### ISSUE THREAD

**Issue by iamnotgay** [apache/incubator-dolphinscheduler#877]
path escheduler-ui/src/js/module/i18n/locale/zh_CN.js 

![image](https://user-images.githubusercontent.com/19225068/65576158-faafcf80-dfa3-11e9-9ba8-e947be645d6c.png)

**Comment by dailidong** [comment]
submit a pr please!

**Comment by iamnotgay** [comment]
ok Submitted

**Comment by dailidong** [comment]
good!
