### ISSUE TITLE
[BUG] It's failed that uploading a file that doesnot exist in HDFS to HDFS.

### ISSUE THREAD

**Issue by buildupchao** [apache/incubator-dolphinscheduler#878]
dolphinscheduler: v1.1.0
It's failed when I upload a jar file that does not exist in HDFS to HDFS by user dw_mr of dw tenant.

- Firstly, I get an error message 'hdfs operation error' by browser debug mode. 
- Secondly, I hold an exception message 'NullPointerException' by checking the back-end api-server log. 
- Of course, HDFS directory does not have this jar file, either. 

Could you please help me resolve this issue?

![1 1](https://user-images.githubusercontent.com/25910406/65578394-50867680-dfa8-11e9-9071-0a16ade7bc77.png)
![1 2](https://user-images.githubusercontent.com/25910406/65578395-50867680-dfa8-11e9-8e31-236da1184e20.png)
![1 3](https://user-images.githubusercontent.com/25910406/65578396-50867680-dfa8-11e9-8364-8213b989712d.png)
![1 4](https://user-images.githubusercontent.com/25910406/65578397-511f0d00-dfa8-11e9-8781-e175a9d13205.png)

**Comment by dailidong** [comment]
which version do you use?
version 1.1.0, HadoopUtils.java  line number 322 :
![image](https://user-images.githubusercontent.com/15833811/65594926-407d8f80-dfc6-11e9-8d4e-c5544d4acf65.png)

**Comment by buildupchao** [comment]
> which version do you use?
> version 1.1.0, HadoopUtils.java line number 322 :
> ![image](https://user-images.githubusercontent.com/15833811/65594926-407d8f80-dfc6-11e9-8d4e-c5544d4acf65.png)

Yes, I use version 1.1.0. I got this package from latest release link 'https://github.com/apache/incubator-dolphinscheduler/releases'. The screen shoot of installation package as below:
![es_installation_package](https://user-images.githubusercontent.com/25910406/65599312-2b0d6300-dfd0-11e9-882e-63275f81cb79.png)

**Comment by qiaozhanwei** [comment]
There is no such problem with normal operation.

Is there any question now?

This problem generally does not exist with directories. I think you and directories exist. Is it that HDFS is not enabled in the middle, and then HDFS is started?

Or try creating a new tenant upload resource

正常操作是没有这个问题的
现在还有这个问题吗？
这个问题一般都是跟目录不存在，我看你跟目录是存在的是，是中间先是hdfs没有启用，之后启动hdfs的吗？
或者你试试创建一个新的租户上传资源

**Comment by buildupchao** [comment]
> There is no such problem with normal operation.
> 
> Is there any question now?
> 
> This problem generally does not exist with directories. I think you and directories exist. Is it that HDFS is not enabled in the middle, and then HDFS is started?
> 
> Or try creating a new tenant upload resource
> 
> 正常操作是没有这个问题的
> 现在还有这个问题吗？
> 这个问题一般都是跟目录不存在，我看你跟目录是存在的是，是中间先是hdfs没有启用，之后启动hdfs的吗？
> 或者你试试创建一个新的租户上传资源

No, HDFS is always running. I'll give you feedback after I create a new tenant and test.

**Comment by buildupchao** [comment]
> There is no such problem with normal operation.
> 
> Is there any question now?
> 
> This problem generally does not exist with directories. I think you and directories exist. Is it that HDFS is not enabled in the middle, and then HDFS is started?
> 
> Or try creating a new tenant upload resource
> 
> 正常操作是没有这个问题的
> 现在还有这个问题吗？
> 这个问题一般都是跟目录不存在，我看你跟目录是存在的是，是中间先是hdfs没有启用，之后启动hdfs的吗？
> 或者你试试创建一个新的租户上传资源

Oh, No! I create a new tenant. Not only cannot upload a file to HDFS, but also does not create a directory for tenant in HDFS system. It's extremely terrible for v1.1.0. Do you need me to provide the installation package that I hold version 1.1.1?

**Comment by buildupchao** [comment]
> There is no such problem with normal operation.
> 
> Is there any question now?
> 
> This problem generally does not exist with directories. I think you and directories exist. Is it that HDFS is not enabled in the middle, and then HDFS is started?
> 
> Or try creating a new tenant upload resource
> 
> 正常操作是没有这个问题的
> 现在还有这个问题吗？
> 这个问题一般都是跟目录不存在，我看你跟目录是存在的是，是中间先是hdfs没有启用，之后启动hdfs的吗？
> 或者你试试创建一个新的租户上传资源

Hi, the question does not occur after re-creating a tenant. Thanks for you help!
