### ISSUE TITLE
[BUG] The number of processes defined under the single project home page counts the number of processes for all projects

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#884]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The number of processes defined under the single project home page counts the number of processes for all projects

**To Reproduce**
1. View the number of process definitions for project management. As shown in the following figure, the number of process definitions for all projects is 6, and the number of test007 is 3.
![image](https://user-images.githubusercontent.com/55787491/65589820-48d0cd00-dfbc-11e9-8594-c868b4d141cc.png)
2. Click test007, enter the project home page of test007, view the process definition statistics, as shown below:
![image](https://user-images.githubusercontent.com/55787491/65589980-91888600-dfbc-11e9-934d-7368d36263cc.png)

**Expected behavior**
For the project home page of a single project, the number of process definition statistics should be defined for the process of the project, and the number of processes for all projects should not be counted.

**Which version of Easy Scheduler:**
 -[dev分支]

**Comment by dailidong** [comment]
good job!
