### ISSUE TITLE
[BUG] HadoopUtils's method copyHdfsToLocal fail to handle exception 

### ISSUE THREAD

**Issue by iture123** [apache/incubator-dolphinscheduler#887]
![image](https://user-images.githubusercontent.com/12154864/65597655-3ced0700-dfcc-11e9-8934-1e65d40d86ed.png)
HadoopUtils's method copyHdfsToLocal fail to handle exception when dstPath is a dir

**Comment by dailidong** [comment]
good job!

could you submit a pr to solve this?

**Comment by dailidong** [comment]
pr #919 fix this!
