### ISSUE TITLE
[BUG] Can successfully import an existing workflow

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#896]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Successfully import an existing workflow, importing an existing workflow should not succeed

**To Reproduce**
1. Enter the workflow definition page of project management, import an existing workflow, and import it successfully, as shown below:
![image](https://user-images.githubusercontent.com/55787491/65656129-4f5d5400-e051-11e9-8cbf-2e772c7d4c88.png)

**Expected behavior**
Cannot import an existing workflow

**Which version of Easy Scheduler:**
 -[dev分支]

**Comment by dailidong** [comment]
good job!

**Comment by fancyChuan** [comment]
I want to fix this bug by renaming the workflow to another name, like:  xxx-copy

**Comment by chongchongzi** [comment]
I've fixed it. I'll submit it it later.
