### ISSUE TITLE
[BUG] SQL task SQL type from query mode to non-query mode

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#901]
Switch from query mode to non-query mode
由查询模式切换到非查询模式
![1](https://user-images.githubusercontent.com/23756105/65674295-e7bdfd80-e07e-11e9-9bc4-f7d7f6b42606.png)

After the operation is completed, the subject, the recipient and the CC are actually echoed.
运行完毕之后，主题，收件人和抄送人竟然回显了
![2](https://user-images.githubusercontent.com/23756105/65674325-f4425600-e07e-11e9-9b4a-d4ebac6ac7aa.png)

**Comment by break60** [comment]
Front end repaired
