### ISSUE TITLE
[DISCUSSION] change column type of `update_time`

### ISSUE THREAD

**Issue by qrfxiaoge** [apache/incubator-dolphinscheduler#903]
1. `update_time` datetime NOT NULL COMMENT '更新时间'
2. `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

if we prefer the 2nd type, it would be more easier when the record is updated.

**Comment by chengshiwen** [comment]
Close since no updates for long time
