### ISSUE TITLE
[BUG] The postgresql data source of the SQL task, if it is connected to the public schema, does not need to write the database.

### ISSUE THREAD

**Issue by qiaozhanwei** [apache/incubator-dolphinscheduler#909]
The postgresql data source of the SQL task, if it is connected to the public schema, does not need to write the database.
The front end needs to remove the validation of the database. The backend needs to be jdbc:postgresql://192.168.xx.xx:5432/ when jdbc is connected. The final backslash is required.

SQL任务的postgresql数据源，如果是连接public schema，是不需要写数据库的
前端需要去掉数据库的验证，后端需要在jdbc连接的时候jdbc:postgresql://192.168.xx.xx:5432/，需要有最后的反斜杠

**Comment by break60** [comment]
Front end resolved
