### ISSUE TITLE
[Feature]  The same node executes shell across different users

### ISSUE THREAD

**Issue by maimaip** [apache/incubator-dolphinscheduler#911]
1.1.0 版本 在测试发现 不同用户组免密，但是一个用户组运行不属于这个用户权限的脚本，会提示输入密码，
su - hdfs <<EOF
 sh /data/test.sh
exit;
EOF
exit 
再用root 用户安装调度系统后  无法调用 提示输入密码 
提示为 ： 密码：su: 鉴定故障
已经解决 是租户问题

**Comment by maimaip** [comment]
你好我这边已经解决了

**Comment by chengshiwen** [comment]
Close this issue since it has been resolved
