### ISSUE TITLE
[BUG] WORKER 在一次任务失败暂停后，无法再次 在该节点worker 上提交以前成功的任务(需要再次重新启动worker-server)

### ISSUE THREAD

**Issue by maimaip** [apache/incubator-dolphinscheduler#912]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
worker 在一次任务失败后无法再次执行任务，显示失败

**To Reproduce**
 我在一个节点运行一个任务停止后，该节点无法运行以前成功运行的任务 显示为失败，日志中返回状态code 为
[log.txt](https://github.com/apache/incubator-dolphinscheduler/files/3662002/log.txt)
1 ，但是我手动执行日志中的脚本 没问题。目前还发现在新增worker 后 会导致某些正在运行worker 无法运行任务。
**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0]

**Comment by qiaozhanwei** [comment]
是不是指定了worker分组？指定了机器，而机器不存在？

Is a worker group specified? A machine was specified and the machine does not exist?
