### ISSUE TITLE
[BUG] When the worker starts, it does not need to load and run the deleted task instance

### ISSUE THREAD

**Issue by wangshu-zhouyunfan** [apache/incubator-dolphinscheduler#915]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Currently, when the Worker restarts, the deleted task instance is loaded and run. This is unreasonable. When failover occurs, it is better to judge whether the current task is deleted first, and then judge whether the corresponding task instance needs to be run.

**To Reproduce**
Steps to reproduce the behavior, for example:
1.  Run a large number of task instances.
2.  Delete related tasks.
3. Check whether the worker restores the current task instance and runs

**Expected behavior**
A large number of deleted task instances continue to run.

**Comment by qiaozhanwei** [comment]
1, first delete the process instance will delete the corresponding task, the database level cascading delete
2, once the process instance and task instance are deleted, even if the task has reached the zk queue, it will not be scheduled to execute.
3, for non-final process instances and task instances, the service will be fault tolerant when restarting


1，首先删除流程实例会把对应的任务删除，数据库级别的级联删除
2，一旦流程实例和任务实例删除了，就算任务已经到了zk queue中，也不会调度执行
3，对非终态的流程实例和任务实例，服务在重新启动的时候会进行容错

**Comment by wangshu-zhouyunfan** [comment]
Thanks @qiaozhanwei,
Let me confirm one thing first. Is what you said already supported by us or what we expect to support this time?

1. 我先确认一点，你说的这个是我们已经支持了的，还是这期我们期待要支持的？

**Comment by qiaozhanwei** [comment]
1.2.0 supported
