### ISSUE TITLE
[BUG] English version of the home page and project home page data display is incomplete, style confusion

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#933]
![image](https://user-images.githubusercontent.com/55787491/65842913-53df8080-e361-11e9-96b5-475594f11bdb.png)
![image](https://user-images.githubusercontent.com/55787491/65843539-bede8680-e364-11e9-9ece-c8bb8922dd9e.png)
![image](https://user-images.githubusercontent.com/55787491/65843711-ac188180-e365-11e9-922d-f3206118233d.png)
![image](https://user-images.githubusercontent.com/55787491/65843727-c05c7e80-e365-11e9-99f1-3e45add151c0.png)
![image](https://user-images.githubusercontent.com/55787491/65843737-d66a3f00-e365-11e9-9c09-1a28af607e49.png)
![image](https://user-images.githubusercontent.com/55787491/65843743-e124d400-e365-11e9-9734-b6060f0166c8.png)
![image](https://user-images.githubusercontent.com/55787491/65843756-f00b8680-e365-11e9-9ccc-14e95480c99f.png)
![image](https://user-images.githubusercontent.com/55787491/65843784-19c4ad80-e366-11e9-817f-3778e790d18f.png)
![image](https://user-images.githubusercontent.com/55787491/65843800-2812c980-e366-11e9-90f0-1a79884878b8.png)
![image](https://user-images.githubusercontent.com/55787491/65843903-93f53200-e366-11e9-97f4-0e349c0e80b6.png)
![image](https://user-images.githubusercontent.com/55787491/65843908-9c4d6d00-e366-11e9-90c1-c0798fdb7f31.png)
![image](https://user-images.githubusercontent.com/55787491/65844359-8ccf2380-e368-11e9-8c81-5da4fc79cd34.png)

**Comment by break60** [comment]
Part repaired
