### ISSUE TITLE
[BUG] All crontab tasks doesnot execute after upgrading v1.1.0

### ISSUE THREAD

**Issue by buildupchao** [apache/incubator-dolphinscheduler#934]
All crontab tasks doesnot execute after upgrading v1.1.0. Only created crontab task can be scheduled. Could you please help me quickly resolve this question?

升级v1.1.0版本后，所有的原先配置好的定时任务均不能被调度执行。只能执行新增的定时任务。

**Comment by lgcareer** [comment]
because v1.1.0 fix a bug. The previous timing id cannot be associated.You can try offline and online

**Comment by buildupchao** [comment]
> because v1.1.0 fix a bug. The previous timing id cannot be associated.You can try offline and online

But I do try offline and online for some times. It still does not work. What should I do?

**Comment by qiaozhanwei** [comment]
如果定时不要使用，可以先让t_escheduler_scheduler表的 release_state 变为0，然后将QRTZ_CRON_TRIGGERS，QRTZ_JOB_DETAILS，QRTZ_TRIGGERS 表情况

之后，再上定时上线

If you don't use it regularly, you can first set the release_state of the t_escheduler_scheduler table to 0, then change the QRTZ_CRON_TRIGGERS, QRTZ_JOB_DETAILS, and QRTZ_TRIGGERS table conditions

After that, go online regularly
