### ISSUE TITLE
[BUG] Mouse over the name, it is recommended to remove the gesture icon and underline

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#935]
![image](https://user-images.githubusercontent.com/55787491/65844708-d9672e80-e369-11e9-96e5-90145fb63d85.png)
![image](https://user-images.githubusercontent.com/55787491/65844729-f0a61c00-e369-11e9-84f0-903fe8cd016b.png)
![image](https://user-images.githubusercontent.com/55787491/65844751-01569200-e36a-11e9-87d3-42e75ad2c91a.png)
![image](https://user-images.githubusercontent.com/55787491/65844791-264b0500-e36a-11e9-9ec4-de0c4555dbcc.png)

**Comment by break60** [comment]
Repaired
