### ISSUE TITLE
[BUG] You can enter the wrong password infinitely when logging in. Should limit the number of times the wrong password is entered

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#936]
1.You can enter the wrong password infinitely when logging in,Should limit the number of times the wrong password is entered.
2.When adding a user, you can enter the weak passaword 123456, it is recommended to increase the password complexity.
![image](https://user-images.githubusercontent.com/55787491/65846221-a58f0780-e36f-11e9-893b-5af6369775ca.png)

**Comment by wuchunfu** [comment]
Good idea.

**Comment by qiaozhanwei** [comment]
@break60

**Comment by break60** [comment]
Frontend has been fixed

**Comment by break60** [comment]
Frontend has been fixed(#1432 )
