### ISSUE TITLE
[BUG] docker build fail on centos7

### ISSUE THREAD

**Issue by frank3gogo** [apache/incubator-dolphinscheduler#937]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
The error message is as follows.
```
incubator-dolphinscheduler-1.1.0/sql/upgrade/1.1.0_schema/mysql/escheduler_dml.sql
mv: cannot stat 'EasyScheduler-1.1.0': No such file or directory
The command '/bin/sh -c cd /opt &&     wget https://github.com/analysys/EasyScheduler/archive/${version}.tar.gz &&     tar -zxvf ${version}.tar.gz &&     mv EasyScheduler-${version} easyscheduler_source &&     rm -rf ./${version}.tar.gz' returned a non-zero code: 1
```

**To Reproduce**
docker build command:
docker build -t dolphinscheduler:1.1.0 --build-arg version=1.1.0 --build
-arg tar_version=1.1.0 .

**Expected behavior**

**Screenshots**

**Which version of Easy Scheduler:**
 -[1.1.0]

**Additional context**
The changes I made in Dockerfile are as follows,
```
68    #mv EasyScheduler-${version} easyscheduler_source && \
69    mv incubator-dolphinscheduler-${version} easyscheduler_source && \
```

**Requirement or improvement
os: centos7 (vm)

**Comment by khadgarmage** [comment]
Please reference to #1009
