### ISSUE TITLE
通过dockerfile启动问题

### ISSUE THREAD

**Issue by erienniu** [apache/incubator-dolphinscheduler#954]
mac本地dockerfile启动时，会出现启动api-server master-server worker-server中的一个时会导致其他两个进程的死亡，另外任务实例执行后无日志（日志丢失），没有相关案例，想知道是否需要配置除了dockerfile外的东西

**Comment by erienniu** [comment]
目前通过dockerfile构建启动，无hadoop接入，所有任务没有日志。
-------
now i run dolphin in docker mode(standalone) without hadoop, but it seems every task instance leaves no log for me.

**Comment by khadgarmage** [comment]
Please reference to #1009 , the readme of dev-db branch has note this problem.

**Comment by CalvinKirs** [comment]
Please reference to #1009
