### ISSUE TITLE
[BUG] Login to different accounts in the same browser, the old account display is not changed to new account

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#956]
*For better global communication, please give priority to using English description, thx! *
**To Reproduce**
1. Log in to the 'admin' account on the browser tab A.
2. Log in to the 'chenxingchun' account in tab B of the same browser.
3. On the tab page A switch page, check that the login account is still 'admin', it should be 'chengxingchun'

【1. 在浏览器标签页A登录admin账号
    2. 在同一个浏览器的标签页B再登录chenxingchun账号
    3. 进入标签页A切换页面，查看登录的账号仍为admin，应该为chengxingchun】

**Which version of Easy Scheduler:**
 -[dev分支]

**Comment by dailidong** [comment]
good job！
