### ISSUE TITLE
[dev]Zookeeper 管理 can't response right datas.

### ISSUE THREAD

**Issue by lianayu** [apache/incubator-dolphinscheduler#967]
We Compiled dev source code  and start service .We found that the interface  "escheduler/monitor/zookeeper/list" could not obtain zk right state
![image](https://user-images.githubusercontent.com/6259646/66449174-b1bd4800-ea86-11e9-9919-e3f48fac7846.png)
but We started release 1.1.0 backend，response right

I also run  release 1.1.0 source 
![image](https://user-images.githubusercontent.com/6259646/66449253-006ae200-ea87-11e9-972f-f948314e35fc.png)
but run dev echo this msg.
![image](https://user-images.githubusercontent.com/6259646/66449294-242e2800-ea87-11e9-9491-c520df07b4c3.png)
--------------------------
    我们通过dev 分支打包，启动服务后发现“escheduler/monitor/zookeeper/list”接口获取的数据不正确；但是我们启动 release 1.1.0 的backend 接口返回没问题。
我们本地运行release 1.1.0 分支代码也能够获取zk 状态信息；但是运行dev 分支就不行。。
**Which version of Easy Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
don't use dev branch, dev branch is used by developers to develop new features or fix bugs , maybe there will be many bug, for now we just begin to test dev

**Comment by lianayu** [comment]
this bug also find in release 1.2.0

**Comment by dailidong** [comment]
pr #1000 resolve this issue!

**Comment by dailidong** [comment]
thanks!
