### ISSUE TITLE
[BUG] Files should not be deleted and renamed after they are associated with a workflow

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#971]
*For better global communication, please give priority to using English description, thx! *
**To Reproduce**
![image](https://user-images.githubusercontent.com/55787491/66462865-877f8080-eaae-11e9-838d-cb9d734286cf.png)

**Which version of Easy Scheduler:**
 -[dev分支]

**Comment by dailidong** [comment]
does this issue fixed? if fixed, please close this issue, thx!
@xingchun-chen

**Comment by bannerkun** [comment]
为什么有我？我不应该存在里面啊
