### ISSUE TITLE
[BUG] After the workflow fails to run multiple times, the number of failures of the home page and the project home page is incorrect

### ISSUE THREAD

**Issue by xingchun-chen** [apache/incubator-dolphinscheduler#979]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
After the workflow run fails, the re-run 3 times fails,  the number of failures of the task status statistics on the home page and the project home page is incorrect
【工作流运行失败后，重跑3次均失败，首页和项目首页的任务状态统计的失败次数为1，应该为4】

**To Reproduce**
1.Workflow definition setting failed retries 3 times
![image](https://user-images.githubusercontent.com/55787491/66540755-80fd1180-eb5f-11e9-9987-1ce04f7e11af.png)
2.After running the workflow, there are 4 failure data for viewing the task instance, as shown below
![image](https://user-images.githubusercontent.com/55787491/66540897-f7017880-eb5f-11e9-93f1-2b3d9dd723cd.png)
3.The number of failures of task status statistics on the home page and project home page is 1. It should be 4
![image](https://user-images.githubusercontent.com/55787491/66540971-392aba00-eb60-11e9-835e-d20d08686f09.png)
![image](https://user-images.githubusercontent.com/55787491/66540982-43e54f00-eb60-11e9-8e56-32d99df3c9db.png)

**Which version of Easy Scheduler:**
 -[dev分支]

**Comment by dailidong** [comment]
good job!
